### ISSUE TITLE
Term-URI fra Roald?

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#100]
Hei,
Siden vi nå offisielt ikke bruker Ask lenger har UBB sluttet å lage bibsys-poster for elektroniske objekter fra vårt institusjonsarkiv BORA, fremst master-oppgaver, og noen doktoravhandlinger. Vi skal da sette emneord direkte på objektene i Dspace. De som drifter Dspace her har sagt at de kan legge til et felt for Realfagstermer, hvor vi kan legge inn URI-er for termene. Så får vi se når de rekker å aktivere de. Kunne en ønske en URI-knapp i Roald?

Edit: ser nå at allt ikke er helt ferdig for LD ennå.

@knuthe @bibliomari @danmichaelo

**Comment by knuthe** [comment]
Burde jo være mulig. Hvordan skal dette se ut? En linje pr URI (eller annet skilletegn). Er det noe med strenger vi burde tenke på? (jeg har hodet et annet sted i øyeblikket, men det synker vel inn).

**Comment by mittinatten** [comment]
I DSpace må en legge de inn en og en. En eksport-funksjon for de enkelte termene, i selve term-vinduet kanskje, hadde vært best, for dette formålet i hvert fall.

Feltet er allerede på plass faktisk. Jeg regner med termer er mest relevant, men burde jeg be om form, tid og sted også?

**Comment by danmichaelo** [comment]
Hm, dette var veldig interessant – send veldig gjerne et skjermbilde av hvordan redigeringsvinduet ser ut når det er på plass! 

Men kanskje feltet ikke trenger å være spesifikt for Realfagstermer? Kanskje det kan være et felles emnefelt der man kan legge inn URIer fra alle vokabularer? Så kan humsam f.eks. bruke Humord om de ønsker det. Fra å følge URIene får man jo informasjon om vokabulartilhørighet.

**Comment by knuthe** [comment]
Kanskje det kunne ordnes sånn at man valgte DSpace-modus i Roald og at URI-er dukket opp i BIBSYS-vinduet nederst etterhvert som man fant fram termer, så kunne kan kopiere linjevis derfra? Jeg ser ikke bort fra at DM kan tenke ut noe smartere :-)

**Comment by mittinatten** [comment]
Sånn ser det ut nå:
![dspace](https://cloud.githubusercontent.com/assets/2842140/5955963/c48aa430-a7a8-11e4-94b7-c8056f2d476d.png)

**Comment by mittinatten** [comment]
Eksempel på et objekt med realfagsterm (jeg har laget URI manuelt basert på hvordan de ser ut i LodLive).
https://bora.uib.no/handle/1956/9236?show=full

**Comment by mittinatten** [comment]
De sier at modellen de bruker har ett felt per vokabular. Forhåpentligvis får de til å vise termen på en bedre måte etter hvert.

**Comment by danmichaelo** [comment]
Nå demrer det noe.. Jeg har veldig dårlig kjennskap til DSpace, men vi snappet jo opp i høst at det finnes en [håndbok for bruk av metadata i norske forskningsarkiv](http://www.cristin.no/om/aktuelt/aktuelle-saker/2014/metadatahandbok.html) og spilte inn at Realfagstermer skulle være med. 

La merke til at LD-mann @tarjelavik var med i prosjektgruppen, så jeg tenkte at han sikkert har gjort seg noen tanker om hvordan ting kan uttrykkes i RDF :) [dcterms:subject](http://dublincore.org/documents/domain-range/#dctermssubject) har ihvertfall ressurs som verdiområde og burde være en kandidat for alle emneord som har URIer. Blir spennende å høre mer om dette!

Drømmesituasjon: At redigeringsfeltet i DSpace kunne fått autofullføring mot [APIet vårt](http://data.ub.uio.no/realfagstermer/api/search?query=Akvak) :)

(Ellers minner dette meg om at vi må ta en omkamp på emnesituasjonen i vår Duo…)

**Comment by mittinatten** [comment]
Jeg kan altfor lite om dette for å kunne si noe intelligent, men det er Tarje jeg har snakket med, så jeg regner med at det gjøres på en riktig måte :)

**Comment by bibliomari** [comment]
Ojojoj, jeg prøver å henge med, spennende!

**Comment by mittinatten** [comment]
Hva skjer hvis en term slettes? Slettes den, eller blir den deprecated med se-henvisning? Hvis den virkelig slettes må vi finne noe som tilsvarer lokar for dspace.

**Comment by knuthe** [comment]
Sikkert noen som har tenkt ut en logikk og funksjonalitet for type "deprecated" med se-henvisning. Så får vi implementere det. Tror ikke vi skal satse på at dspace har lokar (eller vil få). Se vedlagte funksjonalitet for Roald-URI. Bilde før og etter og før og etter ...
![roalduri-1](https://cloud.githubusercontent.com/assets/9070826/5959707/a7c01420-a7d0-11e4-8392-56e91328d983.JPG)
![roalduri-2](https://cloud.githubusercontent.com/assets/9070826/5959708/a7c3430c-a7d0-11e4-9b04-6ed13a675035.JPG)

**Comment by mittinatten** [comment]
Veldig bra! Kan det lastes ned fra det vanlige stedet?

**Comment by knuthe** [comment]
Ikke ferdig testet. Vent til i morgen.

----- Reply message -----
Fra: "Simon Mitternacht" <notifications@github.com>
Til: "realfagstermer/realfagstermer" <realfagstermer@noreply.github.com>
Kopi: "Knut Hegna" <knut.hegna@ub.uio.no>
Emne: [realfagstermer] Term-URI fra Roald? (#100)
Dato: tor., jan. 29, 2015 16:21

Veldig bra! Kan det lastes ned fra det vanlige stedet?

**Comment by tarjelavik** [comment]
Så jeg var nevnt. Veldig bra arbeid med RF! Ser frem til å få kobla oss på!

Håndboka er skrevet med tanke på tekststrenger. Bruker man uri hadde man jo ikke trengt alle disse emnefeltene. Dersom Simon legger inn noen realfagstermer så får vi se hvordan vi kan benyttes oss av det, i BORA eller i LD-baserte nettsider vi lager (f.eks. marcus.uib.no).

Dspace kan slå opp hos LC, så kan kanskje relativt enkelt tilpasses API'en deres? 

Hva er lokar?

**Comment by danmichaelo** [comment]
Hehey, pingingen funket :)

LOKAR er en slags søk-og-erstatt kommando vi må kjøre i Bibsys-blåskjermen for å rette emneord i katalogposter etter at vi har endret i autoritetsfilen.

Interessant at Dspace kan slå opp i LCSH, det visste jeg ikke. Vet du hva slags endepunkt (URL) den bruker? Det hadde vært veldig interessant å teste om vi kunne få til noe tilsvarende med Realfagstermer etterhvert! APIet vårt er forresten bare et lite php-script som snakker med Virtuoso (snart Fuseki TDB).

Jeg må bare spørre litt mer.. er det slik at dere nå skal i gang med å mappe DSpace-attributtene til RDF og legge metadataene i en triple store? Hørte såvidt at DSpace 5 skulle få støtte for noe sånt. Har dere begynt å jobbe med mappingskjema – eller er det kanskje noe det planlegges å jobbes med nasjonalt? (Lurer på om jeg må invitere de som driver med DSpace her på en kaffe, jeg finner de jo ikke på github..)

**Comment by tarjelavik** [comment]
Når noen kaller LD-mannen, så må man troppe opp :-).

Du finner det her: https://github.com/DSpace/DSpace/blob/master/dspace/config/dspace.cfg#L1614-L1615. http://alcme.oclc.org/srw/search/lcnaf. Det er ikke LCSH, men LC names. Tenkte man kunne laget en plugin basert på denne.

Vel, jeg tenkte å gjøre det, men Dspace5 sin nye RDF mulighet gjør nok at vi bare vasker våre data og lar Dspace sin mapping gjøre jobben. Den virker enkel å tilpasse: https://github.com/DSpace/DSpace/blob/master/dspace/config/modules/rdf/metadata-rdf-mapping.ttl. 

Ang nasjonal mapping. Mappingen burde bli enkel. Vi kan følge håndboken delvis og oppdatere de delen som ikke gir mening når man bruker uri'er. Selv er jeg ikke så opptatt av at alle gjør det samme, men dersom alt dette skal havne i Alma eller en eller annen index så må vi vel mappe litt... 

(vi bruker også Fuseki TDB, http://sparql.ub.uib.no/)

**Comment by knuthe** [comment]
Da er det fikset og beskjed sendt (og bruksanvisning oppdatert). Jeg la inn URI-ene linjevis i systemklipp i fall noen skulle lage en mulighet for å klistre inn flere URI i ett registreringsfelt for realfagstermene. Det hadde vært kjekt.

Så var det dette med deprekaterte termer, da. Jeg sender saken over til Sonja foreløpig.

**Comment by danmichaelo** [comment]
Diskusjonen om URI-er i Dspace5 fortsatte på https://github.com/realfagstermer/realfagstermer/issues/280#issuecomment-118011257 og nedover.

**Comment by danmichaelo** [comment]
Foreløpig ikke mer å gjøre her. Åpner ny sak hvis det trengs.
