### ISSUE TITLE
Kopernikanske system

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1000]
Slå sammen med `Heliosentrisk teori`?

--
URI: http://data.ub.uio.no/realfagstermer/c006531
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kopernikanske%20system%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006531

**Comment by danmichaelo** [comment]
Heliosentrisk teori / verdensbilde er jo mer enn det kopernikanske system, men så lenge det bare var ett dokument på hver av dem så synes jeg det gir mer mening å slå sammen.
