### ISSUE TITLE
Zeditt

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#1001]
Finner ingen forklaring av dette ordet 

--
URI: http://data.ub.uio.no/realfagstermer/c001513
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Zeditt%22
Soksed: https://soksed.biblionaut.net/concepts/REAL001513

**Comment by danmichaelo** [comment]
Kan det være skrivefeil av zeolitt..? :/ Spør Tone

**Comment by danmichaelo** [comment]
Slått sammen med zeolitter
