### ISSUE TITLE
Kopperreagenser

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1002]
Kan noen legge til `Kobberreagenser` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c003562
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kopperreagenser%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003562

**Comment by danmichaelo** [comment]
Gjort. Vi har forresten "Kobber" som foretrukket term for grunnstoffet, så burde kanskje være konsekvente på "b" som foretrukket, "p" som alternativ. Fikser.
