### ISSUE TITLE
Kvinnearbeid

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1003]
Slette?

--
URI: http://data.ub.uio.no/realfagstermer/c010275
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kvinnearbeid%22
Soksed: https://soksed.biblionaut.net/concepts/REAL010275

**Comment by Hypsibius** [comment]
Sikkert. Er det no det passar å minne om at å spa og stable torv var kvennfolkarbeid, for det måtte gjerast den tida karane var på 'fiskje'? Eller var det når karane var i Vestisen? Går litt i surr....

**Comment by danmichaelo** [comment]
Sletta. 0 dok
