### ISSUE TITLE
Kyanitt

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1004]
Skal denne egentlig være flertall?

--
URI: http://data.ub.uio.no/realfagstermer/c007356
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kyanitt%22
Soksed: https://soksed.biblionaut.net/concepts/REAL007356

**Comment by danmichaelo** [comment]
@Violabibaluba fiksa flertall i sta. Vi trooor @edinab har sagt en gang at det er greit å ha mineraler i flertallsform, men vi er ikke 100 % sikre.

**Comment by Violabibaluba** [comment]
Endrer tilbake til entall etter innspill fra Edina.
