### ISSUE TITLE
Hard X-Ray Burst Spectrometer (HXRBS)

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#1005]
Denne er dobbelt opp på emneord

--
URI: http://data.ub.uio.no/realfagstermer/c006263
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hard%20X-Ray%20Burst%20Spectrometer%20(HXRBS)%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006263

**Comment by danmichaelo** [comment]
Slått sammen! Skal nok også flyttes.
