### ISSUE TITLE
Meiofauna (REAL003084) og Meiobentos (REAL006498)

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1006]
I praksis er vel meiobentos jamt over kun fauna?

jf Wikipedia. SNL har inga innførsle

https://en.wikipedia.org/wiki/Meiobenthos

**Comment by BioHeidi** [comment]
Ja hvis du ikke føler du må slikke på dem slår vi sammen. Bruken tilsier også det.

**Comment by BioHeidi** [comment]
herrregud! skille!

**Comment by Hypsibius** [comment]
??? Skille eller slå saman? Eg foreslår slå saman, sidan  - det over.....

**Comment by BioHeidi** [comment]
Hehe. Ja, men jeg skrev "Ja hvis du ikke føler du må slikke på dem slår vi sammen." Var rask til å editere, men det hjelper jo ikke når jeg eksponerer det igjen :rofl:

**Comment by BioHeidi** [comment]
Og nå er det gjort og vi kan alle glemme at dette har skjedd.
