### ISSUE TITLE
Nyterm Foronider

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1007]
Jf SNL https://snl.no/dyr (liste over rekker langt nede på sida)

EN Phoronids LA Phoronida

Aktuelt dokument
 https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71506996760002201

**Comment by danmichaelo** [comment]
Opprettet. La til `Phoronider` som alternativ term siden SNL brukte det. Og definisjon "rekke i dyreriket"
 @BioHeidi , kan du se over?

**Comment by Hypsibius** [comment]
'Rekke' er definert i systematikken, 'gruppe' brukast laust om noko som høyrer saman, og som kan befinne seg på ulikt (diskutabelt?) systematisk nivå. Så nei.

**Comment by Hypsibius** [comment]
Men ja, fint du la til Rekke :-)
