### ISSUE TITLE
Nyterm Sjøknelere

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1008]
Forslår nyterm Sjøknelere NN Sjøknelarar En Mantis shrimps LA Stomatopoda

jf https://snl.no/sj%C3%B8knelere

Aktuelt dokument: 

https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71514564250002201

**Comment by danmichaelo** [comment]
Opprettet. @BioHeidi , se gjerne over

**Comment by BioHeidi** [comment]
Åh! De er så kule! Og smaker godt. Legg også inn bf knelerreker, det er det jeg kjenner dem som.

**Comment by danmichaelo** [comment]
Hm, knelarrekar på nyn.. neppe :D `Knelarreker` troor jeg det blir, siden de har `Knelarar` og `Reker`

**Comment by Hypsibius** [comment]
Knelarreker, ja. Ei reke, kjønnet på ordet følgjer siste ledd.  Smake? Er du av dei som smakar deg gjennom dyreriket, @BioHeidi ???
