### ISSUE TITLE
Hvite blodceller

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1009]
Kan noen legge til `Hvite blodlegemer` og `Leukocytter` på norsk?

Jeg la til `WBC` på engelsk (forkortelse), men skal det egentlig være `WBCs` siden vi kjører flertall?

--
URI: http://data.ub.uio.no/realfagstermer/c008288
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hvite%20blodceller%22
Soksed: https://soksed.biblionaut.net/concepts/REAL008288

**Comment by anjamaa** [comment]
Samme greie for `Lipopolysakkarider`.

**Comment by danmichaelo** [comment]
Gjort!

Forkortelser er nok ikke behandlet helt konsekvent. I redigeringsprogrammet Sonja som vi jobber med har vi et eget felt for forkortelse, men dette er språkuavhengig, så der må vi nesten ligge inn entallsform.. Mange ting som har forkortelser er uansett entall, men når den utskrevne formern er flertall synes jeg det blir mest konsekvent at forkortelser også er i flertall.

Så min stemme går til `WBCs` her. (Hvis forkortelsen i det hele tatt trengs da.)

Lukker saken nå, men vi kan kanskje ta en egen diskusjon på flertallsform for forkortelser, @Violabibaluba @BioHeidi ?
