### ISSUE TITLE
Retting - Coyoter

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#101]
Frå korrektur-lista: 

I dag finst det ein innførsel for Coyoter. Foreslår å rette til Prærieulv, BF coyote EN coyote LA Canis latrans

NB, eintal. Det finst rett nok fleire underartar, men berre ein 'god' art. Jf ulv vs ulver @BioHeidi

**Comment by BioHeidi** [comment]
Gjort!
