### ISSUE TITLE
Cerenkovstråling

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1010]
Legger noen til `Tsjerenkovstråling` på norsk? Og eventuelt `Vavilov–Tsjerenkov-stråling`? Ser at SNL har begge.

Er "Cerenkovstråling" en skriveleif? Ser IBV har brukt det. På norsk har vi jo for vane å omskrive til Tsj-, mens engelsk er Ch-, men hvor kommer C- fra? Fra gammelt av?

--
URI: http://data.ub.uio.no/realfagstermer/c001162
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Cerenkovstr%C3%A5ling%22
Soksed: https://soksed.biblionaut.net/concepts/REAL001162

**Comment by danmichaelo** [comment]
Godt spørsmål :nerd_face: Overraskende mange treff på Cerenkov-stråling.  I [Gyldendals store konversasjonsleksikon fra 1959](http://www.nb.no/nbsok/nb/b8aef82001cb19231b2ef4d6ca1afdaa?index=23#917) er det en oppføring `Čerenkov, P. A., se Tsjerenkov`. Så det ser ut som Č har vært brukt for å transkribere Ч (og så har det blitt til C på datamaskiner med begrensa tegnsett..)..  Hopper videre til [Russiske navn : samnordiske staveregler, navneliste](http://www.nb.no/nbsok/nb/d5eb88fb05421e61af2d7274084fb58c?index=4#0) fra 1970 :nerd_face: Se der, Č-en kommer fra  [ISO 9](https://en.wikipedia.org/wiki/ISO_9) :)

Uansett, la inn Tsjerenkovstråling og Vavilov–Tsjerenkov-stråling, men beholdt Cerenkovstråling som alternativ term for søkbarhets skyld :)

**Comment by anjamaa** [comment]
Oooh, men da er det bra å beholde!
