### ISSUE TITLE
Chomskys hierarki

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1011]
Legger noen til `Chomsky–Schützenberger-hierarkiet` på norsk?

Wikipedia bruker "Chomskyhierarkiet" istedenfor "Chomskys hierarki", skal vi endre til det / legge det til?

--
URI: http://data.ub.uio.no/realfagstermer/c004128
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Chomskys%20hierarki%22
Soksed: https://soksed.biblionaut.net/concepts/REAL004128

**Comment by danmichaelo** [comment]
Utflesket!
