### ISSUE TITLE
Fermi-paradokset

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1012]
Legge til `Fermis paradoks` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c009697
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Fermi-paradokset%22
Soksed: https://soksed.biblionaut.net/concepts/REAL009697

**Comment by danmichaelo** [comment]
Gjort
