### ISSUE TITLE
Fysikalske molekylstrukturer

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1013]
Er "fysikalske molekylstrukturer" i det hele tatt et begrep? Skjønner ikke hva det skal bety? Slette?

--
URI: http://data.ub.uio.no/realfagstermer/c006704
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Fysikalske%20molekylstrukturer%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006704

**Comment by danmichaelo** [comment]
Eeeeh, dette tror jeg må være to ord som har blitt slått sammen feil eller noe.. Sletter
