### ISSUE TITLE
Havert

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1014]
Legge til `Gråsel` og `Havkobbe` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c003236
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Havert%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003236

**Comment by danmichaelo** [comment]
Gjort
