### ISSUE TITLE
Homoptera

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1015]
Slå sammen med `Plantesugere`?

--
URI: http://data.ub.uio.no/realfagstermer/c008264
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Homoptera%22
Soksed: https://soksed.biblionaut.net/concepts/REAL008264

**Comment by Hypsibius** [comment]
Skal vi vidareføre termen? Står slik i Wikipedia: " paraphyletic, and therefore deprecated (obsolete)."

Personleg ville eg dfå heller lagt på multiple, gyldige termar

**Comment by BioHeidi** [comment]
Juryen er visst fortsatt i diskusjon på Homoptera, men ITIS har forkastet den enn så lenge. Vi slår sammen og lar den stå med en definisjon og SO-termer (evt OT/UT)

**Comment by grosyn** [comment]
Dei blei slått saman i 2018.
