### ISSUE TITLE
Kac-moody

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1018]
Endre til `Kac–Moody-algebraer` og/eller `Kac–Moody-grupper` eller liknende? Trenger uansett tankestrek og versal M :)

--
URI: http://data.ub.uio.no/realfagstermer/c000569
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kac-moody%22
Soksed: https://soksed.biblionaut.net/concepts/REAL000569

**Comment by danmichaelo** [comment]
Endra til `Kac–Moody-grupper`. Ok, @TorgunnKarolineMoe ?
