### ISSUE TITLE
Gammastråleastronomi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1019]
Wikipedia bruker "Gammaastronomi", og SNL bruker "Gamma-astronomi". Legge til en eller begge av disse?

--
URI: http://data.ub.uio.no/realfagstermer/c006370
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Gammastr%C3%A5leastronomi%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006370

**Comment by danmichaelo** [comment]
La til begge, `Gammaastronomi` som foretrukket
