### ISSUE TITLE
Cumaceer - tillegg

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#102]
Foreslår Cumaceer BF kommakreps LA Cumacea

**Comment by Hypsibius** [comment]
PS: tenkte å vise til bruk på Havforskinga, same blir brukt på UiB http://www.imr.no/nyhetsarkiv/2013/juni/arets_forste_mareano-tokt_er_i_gang/nb-no

**Comment by BioHeidi** [comment]
Kommakreps er "norskere" enn Cumaceer, hva med Kommakreps som oppslagsord, BF Cumaceer? Heia Mareano! :)

**Comment by Hypsibius** [comment]
Vanskeleg greie, for sjølv om noko er norskast, er det ofte ikkje det som er best etablert. Unntatt i Bergen :-P Men så lenge begge gir treff, så what the heck, gå for kommakreps :-)

**Comment by bibliomari** [comment]
Gjort
