### ISSUE TITLE
Varangerhalvøya Nasjonalpark

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1020]
Retter noen til `Varangerhalvøya nasjonalpark` på norsk? :)

--
URI: http://data.ub.uio.no/realfagstermer/c031038
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Varangerhalv%C3%B8ya%20Nasjonalpark%22
Soksed: https://soksed.biblionaut.net/concepts/REAL031038

**Comment by danmichaelo** [comment]
Fiksa! Tok `Arabiske Halvøy`, `Dominikanske Republikk` og `Den Norske Kyststrømmen` samtidig (den siste er veldig rar fordi jeg oppretta den selv: #278 , lurer på hva som kan ha skjedd der..)
