### ISSUE TITLE
Økofilosofi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1021]
Slå sammen med `Økosofi`?

--
URI: http://data.ub.uio.no/realfagstermer/c010961
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22%C3%98kofilosofi%22
Soksed: https://soksed.biblionaut.net/concepts/REAL010961

**Comment by Hypsibius** [comment]
Ja, korleis var det der, igjen? Eg missa det berømmelege UiO-kurset med Arne Næss, har angra sidan...

**Comment by BioHeidi** [comment]
Ble sittende og lese og surrret meg bort i Tvergastein. For en plass! Økosofien til Arne Næss var vel en spesiell gren av økofilosofien, så litt avhengig av belegg kan vi kanskje beholde som to termer? Men rydde og definere, da.

**Comment by BioHeidi** [comment]
Og #534

**Comment by danmichaelo** [comment]
Lukker som duplikat
