### ISSUE TITLE
Likevektsteorier

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1022]
Enda en term om likevekt! Denne har ingen katalogposter. Slette?

--
URI: http://data.ub.uio.no/realfagstermer/c013043
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Likevektsteorier%22
Soksed: https://soksed.biblionaut.net/concepts/REAL013043

**Comment by danmichaelo** [comment]
Bra å få rydda opp! Sletta (dobbeltsjekka i Alma at det var 0 poster)
