### ISSUE TITLE
Linser

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1023]
I tillegg til linser brukt om instrumenter, har denne en katalogpost om dyreøyne. Fjerne emneordet fra denne posten?

--
URI: http://data.ub.uio.no/realfagstermer/c009319
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Linser%22
Soksed: https://soksed.biblionaut.net/concepts/REAL009319

**Comment by danmichaelo** [comment]
@BioHeidi , vil du almarere?

Tips:
- `almar list --titles 'Linser'` for å liste titlene og finne MMS id
- `almar --cql 'alma.mms_id=990108432564702201' remove 'Linser'

**Comment by Hypsibius** [comment]
Skal vi finne på noke med augelinsene? Eller berre latar vi som ingenting?

**Comment by Violabibaluba** [comment]
Dokumentet har emneordet Øyet. Handler ikke spesifikt om linser i øyet. Vi tar den bort fra posten.
