### ISSUE TITLE
Manganarsenid

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1024]
Retter noen til `MnAs`? :)

--
URI: http://data.ub.uio.no/realfagstermer/c004891
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Manganarsenid%22
Soksed: https://soksed.biblionaut.net/concepts/REAL004891

**Comment by danmichaelo** [comment]
Hepp!
