### ISSUE TITLE
Mecklenburg-Vorpommern

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1025]
Slette?

--
URI: http://data.ub.uio.no/realfagstermer/c030792
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Mecklenburg-Vorpommern%22
Soksed: https://soksed.biblionaut.net/concepts/REAL030792

**Comment by danmichaelo** [comment]
Denne har ett dokument: https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlSearch.do?institution=UBO&vid=UBO&search_scope=bibsys_ils&query=any,contains,990105685064702201

**Comment by anjamaa** [comment]
Ingenting kom opp i okapi :(

**Comment by danmichaelo** [comment]
Nei, vet, var derfor jeg la inn lenke. Okapi er en eksperimentell tjeneste som ikke er 100 % til å stole på. Nå har forresten Emnesøk begynt å virke igjen, så kanskje jeg skal gå over til å lage lenker dit: https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030792

**Comment by danmichaelo** [comment]
Eh, og Emnesøk ga to treff, men det er fordi Oria ikke skiller mellom ulike vokabular for stedstermer.. Disse tingene er litt mer komplisert enn de burde være føler jeg..
