### ISSUE TITLE
Metabolisme

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1026]
Hvorfor har vi `Metabolismen` i tillegg til `Metabolisme`?

--
URI: http://data.ub.uio.no/realfagstermer/c013661
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Metabolisme%22
Soksed: https://soksed.biblionaut.net/concepts/REAL013661

**Comment by Hypsibius** [comment]
Beats me!

**Comment by BioHeidi** [comment]
Vi har ikke det? @danmichaelo har du allerede ryddet den bort?

**Comment by danmichaelo** [comment]
Tror ikke det. Finner ikke noe i loggen. Det var rart.

Hm, kan det være at spørsmålet gjaldt hvorfor vi har med begge termene (på samme begrep)?

**Comment by anjamaa** [comment]
Tror det var siste, ja, @danmichaelo :) Lurte på hvorfor vi har med bestemt form når vi ellers ikke har det? Kan hvert fall ikke huske å ha sett det noe særlig?

**Comment by BioHeidi** [comment]
Aha! Det var det det gjaldt! Det er nok resultatet av en sammenslåing og litt sløvhet i bortrydding av BF-termer. Kan ryddes (men har ingen praktisk betydning, eller hva @Violabibaluba ?)

**Comment by danmichaelo** [comment]
Lurer på om Viola har skrudd av epostvarslingen..

**Comment by danmichaelo** [comment]
men ja, jeg tok vekk "Metabolismen", det så litt rart ut
