### ISSUE TITLE
Metalloider

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1027]
Slå sammen med `Halvmetaller`?

--
URI: http://data.ub.uio.no/realfagstermer/c001810
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Metalloider%22
Soksed: https://soksed.biblionaut.net/concepts/REAL001810

**Comment by danmichaelo** [comment]
Gjort, Halvmetaller som foretrukket
