### ISSUE TITLE
Mikrober

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1028]
Slå sammen med `Mikroorganismer`?

--
URI: http://data.ub.uio.no/realfagstermer/c000683
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Mikrober%22
Soksed: https://soksed.biblionaut.net/concepts/REAL000683

**Comment by BioHeidi** [comment]
Finnes en tråd om dette allerede, tror jeg?

**Comment by danmichaelo** [comment]
#130 ?
