### ISSUE TITLE
Mikroøkonomisk teori

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1029]
Slå sammen med `Mikroøkonomi`?

--
URI: http://data.ub.uio.no/realfagstermer/c007046
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Mikro%C3%B8konomisk%20teori%22
Soksed: https://soksed.biblionaut.net/concepts/REAL007046

**Comment by danmichaelo** [comment]
Gjort!
