### ISSUE TITLE
Cyanobakterier

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#103]
Vi har både Cyanobakterier og Cyanophyta. Det siste er eit alternativt namn for det latinske Cyanobacteria, så Cyanophyta treng ingen eigen innførsel. Kan vi legge in cyanophyta som ein ekstra latinsk term?

**Comment by BioHeidi** [comment]
Gjort. Jeg støtter meg (igjen) på ITIS og legger Cyanobacteria over på engelsk term istedet for latin.
