### ISSUE TITLE
Beskyttelseslikhet

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1030]
Slå sammen med `Mimikry`?

--
URI: http://data.ub.uio.no/realfagstermer/c011523
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Beskyttelseslikhet%22
Soksed: https://soksed.biblionaut.net/concepts/REAL011523

**Comment by anjamaa** [comment]
Og eventuelt legge til `Vernelikhet`?

**Comment by Hypsibius** [comment]
Altså, finst dei termane på norsk? Ein lærer så lenge ein lever! 

Aldri høyrt før, og eg har lese masse om mimicry. Som eg heller ikkje har sett brukt som Mimikry den måten ;-) MEN, ser at Giske og Jakobsen 2007 brukar Mimikry, SNL og Wikipedia dei andre. Så ja, slå saman og så blir spørsmålet kva som skal vere foretrukken term...

**Comment by BioHeidi** [comment]
Da holder vi oss til det norskeste og bruker beskyttelseslikhet som foretrukken. Jeg visste heller ikke om den!

**Comment by danmichaelo** [comment]
Fiksa `Beskyttelseslikhet BF Mimikry BF Vernelikhet`
