### ISSUE TITLE
Myosin

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1031]
Skulle denne egentlig vært `Myosiner`?

--
URI: http://data.ub.uio.no/realfagstermer/c004809
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Myosin%22
Soksed: https://soksed.biblionaut.net/concepts/REAL004809

**Comment by anjamaa** [comment]
La inn entall på engelsk enn så lenge, så det må eventuelt også endres på.

**Comment by Hypsibius** [comment]
Trur det. Blei i stuss

**Comment by BioHeidi** [comment]
Aktin og myosin bør i alle fall være søkbare i entall, siden det er det som er mest brukt. Men begge er proteinfamilier med flere typer aktiner og myosiner, så strengt tatt, ja.

**Comment by danmichaelo** [comment]
Endra til fl.tall! Litt usikker på nynorsk, men satsa på at `Myosin` er flertallsformen der. Endre engelsk.

Aktin også.
