### ISSUE TITLE
Naftener

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1032]
Legge til `Sykloalkaner` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c008800
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Naftener%22
Soksed: https://soksed.biblionaut.net/concepts/REAL008800

**Comment by danmichaelo** [comment]
Slått sammen, vi hadde begge
