### ISSUE TITLE
Olbers paradoks

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1035]
Retter noen til `Olbers' paradoks` på norsk? :)

--
URI: http://data.ub.uio.no/realfagstermer/c013979
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Olbers%20paradoks%22
Soksed: https://soksed.biblionaut.net/concepts/REAL013979

**Comment by danmichaelo** [comment]
Fiksa
