### ISSUE TITLE
Omega-3-fettsyre

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1036]
Skulle disse vært i flertall? La inn entall på engelsk også enn så lenge.

--
URI: http://data.ub.uio.no/realfagstermer/c001512
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Omega-3-fettsyre%22
Soksed: https://soksed.biblionaut.net/concepts/REAL001512

**Comment by danmichaelo** [comment]
Rimelig sikker på det, så fiksa
