### ISSUE TITLE
Pdp

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1037]
Retter noen til `PDP` og legger til `Programmed Data Processor` på norsk?

@danmichaelo, du kan få velge hovedterm :)

--
URI: http://data.ub.uio.no/realfagstermer/c003825
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Pdp%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003825

**Comment by danmichaelo** [comment]
Takk :D Beholdt `PDP` som hovedterm jeg
