### ISSUE TITLE
Peptidaser

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1038]
Slå sammen med `Proteaser`?

--
URI: http://data.ub.uio.no/realfagstermer/c005004
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Peptidaser%22
Soksed: https://soksed.biblionaut.net/concepts/REAL005004

**Comment by BioHeidi** [comment]
Gjort!
