### ISSUE TITLE
Seiland Nasjonalpark

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1039]
Retter noen til `Seiland nasjonalpark`? :)

--
URI: http://data.ub.uio.no/realfagstermer/c031028
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Seiland%20Nasjonalpark%22
Soksed: https://soksed.biblionaut.net/concepts/REAL031028

**Comment by danmichaelo** [comment]
Fiksa
