### ISSUE TITLE
Spermatofytter

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1040]
Slå sammen med `Frøplanter`?

--
URI: http://data.ub.uio.no/realfagstermer/c006251
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Spermatofytter%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006251

**Comment by BioHeidi** [comment]
Gjort!
