### ISSUE TITLE
Stereoselektivitet

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1041]
Burde det vært `Diastereoselektivitet` istedenfor `Diastereoselektiv`?

--
URI: http://data.ub.uio.no/realfagstermer/c002553
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Stereoselektivitet%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002553

**Comment by danmichaelo** [comment]
Ja, litt latskap der. Fiksa!
