### ISSUE TITLE
Stokes lov

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1043]
Retter noen til `Stokes' lov`? :)

--
URI: http://data.ub.uio.no/realfagstermer/c001140
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Stokes%20lov%22
Soksed: https://soksed.biblionaut.net/concepts/REAL001140

**Comment by danmichaelo** [comment]
Fiksa
