### ISSUE TITLE
Stomata

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1044]
Slå sammen med `Spalteåpninger`?

--
URI: http://data.ub.uio.no/realfagstermer/c002086
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Stomata%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002086

**Comment by Hypsibius** [comment]
Ser sånn ut!

**Comment by BioHeidi** [comment]
Did!
