### ISSUE TITLE
Stora Alvaret

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1045]
Retter noen til `Stora alvaret` på norsk? :)

--
URI: http://data.ub.uio.no/realfagstermer/c030963
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Stora%20Alvaret%22
Soksed: https://soksed.biblionaut.net/concepts/REAL030963

**Comment by danmichaelo** [comment]
Fiksa

**Comment by Hypsibius** [comment]
What? Og dette er ikkje svensk?

**Comment by anjamaa** [comment]
Ifølge Wikipedia heter det "Stora Alvaret" på både bokmål og nynorsk, men det er jo litt rart likevel.

**Comment by Hypsibius** [comment]
Tekte på Stora Allvaret (*får jag be om störssssta möjliga allvar....*)
