### ISSUE TITLE
Supertunge elementer

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1046]
Legge til `Supertunge grunnstoffer` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c009778
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Supertunge%20elementer%22
Soksed: https://soksed.biblionaut.net/concepts/REAL009778

**Comment by danmichaelo** [comment]
Gjort (som foretrukket)
