### ISSUE TITLE
T-lymfocytter

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1047]
Slå sammen med `T-celler`?

--
URI: http://data.ub.uio.no/realfagstermer/c007375
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22T-lymfocytter%22
Soksed: https://soksed.biblionaut.net/concepts/REAL007375

**Comment by BioHeidi** [comment]
Done!
