### ISSUE TITLE
Universitetsbibliotek

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1048]
"University library"?

Og hva skal vi oversette "Høgskolebibliotek" til? "Høgskole" tilsvarer jo ikke helt "college".

--
URI: http://data.ub.uio.no/realfagstermer/c010667
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Universitetsbibliotek%22
Soksed: https://soksed.biblionaut.net/concepts/REAL010667

**Comment by danmichaelo** [comment]
Dette må være en sak for @superLine ... finnes det ikke egne ordlister for sånt?

**Comment by danmichaelo** [comment]
Eh, på den annen side, trenger vi egentlig å skille mellom dem? Mesteparten av litteraturen ser ut til å være om "academic libraries". Holder det med `Fagbibliotek BF Høgskolebibliotek BF Universitetsbibliotek`?

**Comment by superLine** [comment]
Ja, tenker fagbibliotek dekker de øvrige (har jo også instituttbibliotek hos forskningsinstituttene osv). Veldig sjeldent fagbibliotek ikke har "akademikere" som målgruppe (studentene er jo kommende akademikere)

**Comment by superLine** [comment]
Ved behov kan man jo legge til BF  University library -  BF University college library

**Comment by danmichaelo** [comment]
Ihvertfall nå som alle høgskolene helst vil være universitet :)
Enig i BF
