### ISSUE TITLE
Adenosintrifosfat

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1049]
Legge til `ATP` på engelsk også?

--
URI: http://data.ub.uio.no/realfagstermer/c012708
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Adenosintrifosfat%22
Soksed: https://soksed.biblionaut.net/concepts/REAL012708

**Comment by danmichaelo** [comment]
Den ligger egentlig i et eget forkortelsesfelt som egentlig skal kopieres til alle språk. Det er antakelig en feil i konverteringen, men hvis du finner flere tilfeller der forkortelse mangler på engelsk trenger du ikke melde fra om det

**Comment by anjamaa** [comment]
Skjønner ikke helt, vil det si at jeg ikke skal skrive forkortelse hvis jeg oversetter et ord (som har forkortelse på den norske oppføringa) som enn så lenge mangler engelsk oversettelse? Men skal jeg likevel gjøre det hvis forkortelsen er ulik på norsk og engelsk? Og havner de da begge to i egne forkortelsesfelt?
