### ISSUE TITLE
Darwinistisk medisin

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#105]
Her vil eg ha evolusjonær medisin, bf drawinistisk medisin, darwinsk medisin. Det korresponderer med andre termar vi har (evolusjonspsykologi, evolusjonær genetikk), og fokuserer på mekanisme heller enn oppdagar. Det er også det som gir absolutt flest treff i google

**Comment by BioHeidi** [comment]
Enig. Jeg synes godt vi kan unngå "darwinisme" der vi kan, det er litt gammeldags?

**Comment by BioHeidi** [comment]
Jeg rettet, og slo samtidig sammen Darwinisme og Darwinismen. Klarer vi å lage en definisjon på når det er greit å bruke Darwinismen i stedet for Evolusjonsteorien?

**Comment by Hypsibius** [comment]
Eg tenkjer vel at rådande evolusjonsteori er den moderne syntesen (med forsterking frå molekylært/genetisk hald). At darwinismen er darwins 'opprinnelege ide', pre Mendel, pre Fisher/Dobzhansky/Haldane & resten av gutta....

**Comment by bibliomari** [comment]
@Hypsibius og @BioHeidi komme med definisjoner - hvis dere bare vil ha interne bruksnoter kan det jo godt stå omtrent som @Hypsibius skrev :D

**Comment by BioHeidi** [comment]
Intern note.

**Comment by bibliomari** [comment]
Gjort.
