### ISSUE TITLE
Afro-amerikansk litteratur

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1050]
Skal det ikke være `Afro-American literature`? Med versal A?

[Wikipedia](https://en.wikipedia.org/wiki/African-American_literature) bruker forresten "African-American literature", skal vi legge det til som alternativ?

Skal vi forresten også ha `Afroamerikansk litteratur` på norsk (uten bindestrek)? Ser ut som "afroamerikansk" har flere treff enn "afro-amerikansk" på Google.

--
URI: http://data.ub.uio.no/realfagstermer/c010101
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Afro-amerikansk%20litteratur%22
Soksed: https://soksed.biblionaut.net/concepts/REAL010101

**Comment by danmichaelo** [comment]
0 dokumenter, sletter.

Nå har vi forresten *kun* `Amerikansk litteratur` av ulike kulturers litteratur.. Mulig vi bare skulle sletta den også, og henvist til Humord.

**Comment by Hypsibius** [comment]
I USA brukast African-American(s) og ikkje Afro-American(s), som sjåast som belasta. Språkrådet tviheld på Afro-amerikansk <det eine og det andre>, noko som ikkje burde hindre oss i å legge til Afrikansk-amerikansk literatur

**Comment by danmichaelo** [comment]
Men vi hadde ikke bøker om det uansett (ihvertfall ikke indeksert), så vi trenger ikke tenke mer på det :stuck_out_tongue_closed_eyes:

**Comment by Violabibaluba** [comment]
Vi sletter pga vi ikke har andre typer litteratur. Og bare to dokumenter om Amerikansk litteratur.
