### ISSUE TITLE
Afrodisiaka

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1051]
Denne har flertall på norsk, men entall på engelsk.

--
URI: http://data.ub.uio.no/realfagstermer/c008858
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Afrodisiaka%22
Soksed: https://soksed.biblionaut.net/concepts/REAL008858

**Comment by danmichaelo** [comment]
:+1:
