### ISSUE TITLE
Agglutinerte foraminiferer

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1052]
Legge til `Agglutinerte poredyr` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c003640
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Agglutinerte%20foraminiferer%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003640

**Comment by anjamaa** [comment]
Det er hvert fall i tråd med hva vi har gjort tidligere :)

**Comment by danmichaelo** [comment]
:+1:
