### ISSUE TITLE
Akklimatisering

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1053]
Legge til `Acclimatisation` også?

Wikipedia har også "acclimation" og "acclimatation", skal vi legge til en eller begge av disse også?

--
URI: http://data.ub.uio.no/realfagstermer/c000786
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Akklimatisering%22
Soksed: https://soksed.biblionaut.net/concepts/REAL000786

**Comment by danmichaelo** [comment]
:+1:

**Comment by Hypsibius** [comment]
Prøver å huske frå fysiologien, desse har ulik tyding der. Skal prøve å rekonstruere

**Comment by Hypsibius** [comment]
|  
-- | --

**Comment by Hypsibius** [comment]
Shcmidt-Nielsen 1990, 4. utg

![sn](https://user-images.githubusercontent.com/9350370/31383460-6f26a61c-adbb-11e7-95c1-b0090a281c33.JPG)

**Comment by danmichaelo** [comment]
Åpner igjen, jeg tok ikke egentlig stilling til "acclimation" og "acclimatation"

**Comment by Violabibaluba** [comment]
Vi oppretter akklimering når vi rydder.
