### ISSUE TITLE
Alkaloider

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1054]
Hvorfor har denne både flertall og entall på engelsk?

--
URI: http://data.ub.uio.no/realfagstermer/c010271
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Alkaloider%22
Soksed: https://soksed.biblionaut.net/concepts/REAL010271

**Comment by danmichaelo** [comment]
Det kan jeg ikke svare på, men kan slette entallsformen :) 

(Hva er det motsatte av utflesking?)
