### ISSUE TITLE
Alkylfenol

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1055]
Endre til flertall (på både norsk og engelsk)?

--
URI: http://data.ub.uio.no/realfagstermer/c004471
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Alkylfenol%22
Soksed: https://soksed.biblionaut.net/concepts/REAL004471

**Comment by danmichaelo** [comment]
:+1:
