### ISSUE TITLE
Anoksisk vann

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1056]
Mangler engelsk term, men er låst?

--
URI: http://data.ub.uio.no/realfagstermer/c006772
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Anoksisk%20vann%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006772

**Comment by danmichaelo** [comment]
Vet ikke helt hvorfor det skjer. Kan grave i det hvis det skjer ofte. Nå la jeg bare inn termen i Sonja
