### ISSUE TITLE
Anthocyaniner

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1057]
Ser ut som riktig norsk term skal være `Antocyaniner`?

--
URI: http://data.ub.uio.no/realfagstermer/c006253
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Anthocyaniner%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006253

**Comment by danmichaelo** [comment]
:+1:
