### ISSUE TITLE
Antibakterielle legemidler

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1058]
Er dette en separat term fra `Antibiotika` med vilje?

--
URI: http://data.ub.uio.no/realfagstermer/c013735
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Antibakterielle%20legemidler%22
Soksed: https://soksed.biblionaut.net/concepts/REAL013735

**Comment by danmichaelo** [comment]
Det var en av de jeg hoppet over da jeg korrekturleste. Lurte på det samme.

**Comment by Hypsibius** [comment]
Hmmm

**Comment by BioHeidi** [comment]
Ja, mener det er med vilje, da det finnes legemidler som dreper bakterier og likevel ikke regnes som antibiotika. Sulfonamider er en av dem. Men jeg er ikke sikker på om termen trengs, kunne vært slått sammen med Antimikrobielle stoffer kanskje?

**Comment by danmichaelo** [comment]
God idé. Slo sammen

```
Antimikrobielle stoffer
BF Antibakterielle legemidler
```

**Comment by anjamaa** [comment]
Når jeg søker opp "antibakt*" i soksed, så kommer ikke `Antimikrobielle stoffer` opp, selv om den også har `Antibakterielle legemidler` under seg? Har ikke opplevd det før.

**Comment by danmichaelo** [comment]
> Når jeg søker opp "antibakt*" i soksed, så kommer ikke `Antimikrobielle stoffer` opp, selv om den også har `Antibakterielle legemidler` under seg? Har ikke opplevd det før.

Men hvis du søker opp "antibakt" uten stjerne kommer den opp :tophat: Litt rart, ja..
