### ISSUE TITLE
Antimon

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1059]
Ser at denne har med grunnstofforkortelsen (på engelsk). Skal alle grunnstoffene ha med forkortelse?

--
URI: http://data.ub.uio.no/realfagstermer/c012198
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Antimon%22
Soksed: https://soksed.biblionaut.net/concepts/REAL012198

**Comment by danmichaelo** [comment]
Nei, fjernet den.
