### ISSUE TITLE
Forskjellige dimorfismer

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#106]
Ved oppslag på dimorfisme oppdaga eg at kjønnsdimorfisme og seksuell dimorfisme har separate innførslar. Foreslår kjønnsdimorfisme BF seksuell dimorfisme

**Comment by BioHeidi** [comment]
Gjort. Så også at Dimorfisme kun var brukt på Kjønnsdimofisme, så jeg slettet termen og la Kjønnsdimofisme på de to postene det gjaldt.
