### ISSUE TITLE
B-lymfocytter

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1060]
Bør vi endre til "samme" foretrukkede term på engelsk og norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c011595
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22B-lymfocytter%22
Soksed: https://soksed.biblionaut.net/concepts/REAL011595

**Comment by danmichaelo** [comment]
:+1: Jeg tok B-celler fritt etter WP
