### ISSUE TITLE
Backus-naur-form

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1061]
Retter noen til `Backus–Naur form` på engelsk og `Backus–Naur-form` på norsk?

Wikipedia bruker også "Backus normal form", skal vi legge til det på engelsk?

--
URI: http://data.ub.uio.no/realfagstermer/c009572
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Backus-naur-form%22
Soksed: https://soksed.biblionaut.net/concepts/REAL009572

**Comment by danmichaelo** [comment]
Har du begynt på `exists:prefLabel@en AND -has:wikidataItem `? 👍 

(Fiksa)

**Comment by anjamaa** [comment]
Har begynt rett på "(intet filter)" :)
