### ISSUE TITLE
Baffinbukta

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1062]
Retter noen til `Baffin Bay` på engelsk?

--
URI: http://data.ub.uio.no/realfagstermer/c030948
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Baffinbukta%22
Soksed: https://soksed.biblionaut.net/concepts/REAL030948

**Comment by danmichaelo** [comment]
:+1:
