### ISSUE TITLE
Bekjempelse

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1064]
Er ingen katalogposter. Er det snakk om bekjempelse som i biologisk bekjempelse? Biological Control?

--
URI: http://data.ub.uio.no/realfagstermer/c013725
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Bekjempelse%22
Soksed: https://soksed.biblionaut.net/concepts/REAL013725

**Comment by Hypsibius** [comment]
No idea! Slett?

**Comment by BioHeidi** [comment]
Er tre poster såvidt jeg kan se, og i alle fall tre av dem er i streng. Jeg troooor denne har noe om å ikke brukes alene. Grei å ha i streng, slik som Snegler : Bekjempelse, Lakselus: Bekjempelse som den er brukt til.
