### ISSUE TITLE
Arbeidsmiljø

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1065]
Her er det 3 norske emner knyttet sammen som jeg mener er ganske forskjellige fra hverandre. Er det riktig at de skal være samlet?

--
URI: http://data.ub.uio.no/realfagstermer/c007649
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Arbeidsmilj%C3%B8%22
Soksed: https://soksed.biblionaut.net/concepts/REAL007649

**Comment by BioHeidi** [comment]
Det er nok gjort av praktiske hensyn, da vi ikke har veldig mye litteratur i emnet og strengt tatt bare skal være realfagstermer. Vi har hatt bruk for noen samfunnsvitenskapelige/tverrfaglige emneord også, men bruker da gjerne ganske brede kategoriseringer. Enig i at det kan se rart ut når så forskjellige begreper blir samlet i ett.

Jeg tror uansett ikke vi gjør noe med det, for vi ser fremover langt der fremme i det fjerne mot en felles norsk terminologi...

**Comment by danmichaelo** [comment]
Jeg fjernet `Arbeidsplasser`, jeg. Skjønner hvorfor de ble slått sammen, men det blir litt feil hvis man leser arbeidsplasser i betydningen jobber (som er fort gjort)
