### ISSUE TITLE
Etikk og Moral

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1066]
Vrient å holde fra hverandre? Slå sammen? Humord har gjort det.

Hvis vi tenker etikk som teori om moral

**Comment by Hypsibius** [comment]
Strengt tatt burde vi vel?

**Comment by BioHeidi** [comment]
Det er vel etisk riktig å gjøre det

**Comment by danmichaelo** [comment]
Dånn
