### ISSUE TITLE
Spillifisering

### ISSUE THREAD

**Issue by starseekr** [realfagstermer/realfagstermer#1069]
DE: Wikipedia: Spillifisering er å anvende spill-mekanismer og spill-elmenter i sammenhenger som er utenom videospill. Grunnideen bak spillifisering er å belønne deltakerne som fullfører oppgaver som ønskes utført. Belønninger kan for eksempel være å gi virtuelle hedersbevisninger («badges») eller å skåre poeng.

EN:  Gamification

**Comment by BioHeidi** [comment]
Og nynorsk? :D :dagger:

**Comment by starseekr** [comment]
Spelifisering

**Comment by starseekr** [comment]
Er ikke enig i definisjonen i wiki helt heller, for det trenger ikke være virtuelle badges - kan være gullstjerner på klistrelapper feks. Og spillmekanismer kan like gjerne hentes fra rolle-/brettspill som videospill :P (Pirk, men ser at så ufattelig mange setter alt om gamification på dataspill/digitalt whatever, og det trenger ikke stemme!

**Comment by BioHeidi** [comment]
Vi kan skrive vår egen definisjon, det er faktisk enda bvedre enn å bruke wikipedia sin! Kan du formulere en som dekker termen sånn som vi bruker den?

**Comment by starseekr** [comment]
Kanskje: Spillifisering er anvendelsen av spilldesignelementer og spillprinsipper i situasjoner utenfor spill-sammenheng. Slike designelementer og prinsipper brukes for eksempel til læring, rekruttering, evaluering, markedsføring, fysisk trening, forbedring av brukerengasjement, økt organisatorisk produktivitet og i en rekke andre situasjoner. En av elementene som ofte brukes er å belønne deltakere som fullfører oppgaver som ønskes utført.

**Comment by danmichaelo** [comment]
Knall, med slike definisjoner kan vi snart lage lommeleksikon (på Universitetsforlaget :rocket:) 

Opprettet som REAL031903. Tok meg friheten å kopiere definisjonen over på Wikipedia også siden du ikke allerede haddde gjort det.
