### ISSUE TITLE
Dekapoder og tifotkreps

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#107]
separate innførslar på dekapodar og tifotkreps. Foreslår tifotkreps BF dekapoder

**Comment by BioHeidi** [comment]
Ja, skal gjøre det når filen er ledig. Den er mye opptatt for tiden.

**Comment by Hypsibius** [comment]
Pussig, gitt :-)

**Comment by BioHeidi** [comment]
Etter 16 er det rom! Fikset.

**Comment by Hypsibius** [comment]
Hurra!

(jobbar seint i dag ☺)
