### ISSUE TITLE
Kjedesilikater

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1071]
Legge til `Inosilikater` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c006003
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kjedesilikater%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006003

**Comment by danmichaelo** [comment]
Fiksa!
