### ISSUE TITLE
Religon og vitenskap

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1072]
Lurer på om vi skulle hatt en sammensatt term for  forholdet mellom vitenskap og religion?

```
Religon og vitenskap
BF Vitenskap og religon
```

Lurt? Teit?

Fra før har vi strengen `Vitenskapshistorie :  Religionsvitenskap`, men jeg synes denne er litt dårlig fordi det ikke nødv. er snakk om Religionsvitenskap.

Dokument: https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBO:default_scope:BIBSYS_ILS71544699910002201

**Comment by BioHeidi** [comment]
Rellion!

(Og enig)

**Comment by danmichaelo** [comment]
Oppretta (REAL031904)

**Comment by Hypsibius** [comment]
Uhm, overordna term: Konflikter?

(Sowwy, kunne ikkje la vere)
