### ISSUE TITLE
Forskningsfond

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1073]
Endre til `Forskningsfinansiering` og slå sammen med `Finansiering`?

---
*REAL001148 (Forskningsfond) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c001148), [Skosmos](http://data.ub.uio.no/realfagstermer/c001148), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Forskningsfond%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL001148)*

**Comment by BioHeidi** [comment]
Gjort
