### ISSUE TITLE
Lisensavtaler

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1074]
Må flyttes fra form/sjanger til emne

---
*REAL030162 (Lisensavtaler) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030162), [Skosmos](http://data.ub.uio.no/realfagstermer/c030162), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Lisensavtaler%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL030162)*

**Comment by grosyn** [comment]
Gjort!
