### ISSUE TITLE
Mange geo-atlas som form-termer

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1076]
Vi ser på disse med @edinab en dag:

* [Breatlas](http://ub-soksed.uio.no/concepts/REAL030128?q=type:GenreForm%20atlas,)
* [Geologiske atlas](http://ub-soksed.uio.no/concepts/REAL030128?q=type:GenreForm%20atlas,)
* [Geofysisk atlas](http://ub-soksed.uio.no/concepts/REAL030136?q=type:GenreForm%20atlas,)
* [Geokjemisk atlas](http://ub-soksed.uio.no/concepts/REAL031678?q=type:GenreForm%20atlas,)
* [Geologisk atlas](http://ub-soksed.uio.no/concepts/REAL030137?q=type:GenreForm%20atlas,)
* [Seismisk atlas](http://ub-soksed.uio.no/concepts/REAL030147?q=type:GenreForm%20atlas,)

Også sjekke:
* [Berggrunnskart](http://ub-soksed.uio.no/concepts/REAL030072?q=kart,)
* [Geofysiske kart](http://ub-soksed.uio.no/concepts/REAL030124?q=type:GenreForm%20atlas,)
* [Geologiske kart](http://ub-soksed.uio.no/concepts/REAL030138?q=type:GenreForm%20atlas,)
* [Hydrografiske kart](http://ub-soksed.uio.no/concepts/REAL030140?q=kart,)

**Comment by grosyn** [comment]
NB er i ferd med å ferdigstilla Norsk tesaurus for sjanger og form,[https://www.nb.no/nbvok/ntsf/nb/](url). Humord har bestemt at dei frå no bruker NTSF i 655. Sidan Realfagstermer byrjar å bli meir og meir samkjørt med Humord, har me bestemt at me òg skal bruka denne tesaurusen. På bakgrunn av dette har eg byrja å rydda i Formtermene våre. 
I denne saka, ser eg at det har blitt rydda (før mi tid), slik at Breatlas, Geofysisk atlas og Geokjemisk atlas har blitt flytta til Geologisk atlas. (Fleirtalsforma Geologiske atlas finn eg ikkje spor av, men det er jo denne forma som er korrekt.)
Det første spørsmålet mitt er om eg kan få lov til å flytta Seismisk atlas òg til Geologisk atlas (som vil få forma Geologiske atlas)? Seismisk atlas ligg kun på 2 dokument.

Når det gjeld alle karta, har Berggrunnskart blitt flytta til Geologiske kart (før mi tid). 
Det andre spørsmålet mitt er om eg kan flytta Geofysiske kart (brukt på 1 dokument) og Hydrografiske kart (òg brukt på 1 dokument) til Geologiske kart?

@edinab @BioHeidi

**Comment by grosyn** [comment]
Eg er ikkje heilt enig med meg sjølv her. Slik deler [NTSF ](https://www.nb.no/nbvok/ntsf/nb/page/?uri=https%3A%2F%2Fid.nb.no%2Fvocabulary%2Fntsf%2F141) opp Kart. Eg kan jo prøva å få dei til å ta inn Geofysiske kart, Geologiske kart og Hydrografiske kart som underordna til Kart, og som underordna [Atlas](https://www.nb.no/nbvok/ntsf/nb/page/?uri=https%3A%2F%2Fid.nb.no%2Fvocabulary%2Fntsf%2F17), Geologisk atlas og Seismisk atlas. 
Koss høyrest dét ut?

@edinab @BioHeidi

**Comment by BioHeidi** [comment]
Lukkes pga overgang til [NTSF](https://www.nb.no/nbvok/ntsf/nb/index)
