### ISSUE TITLE
Primat

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#1078]
Heter det Primat i flertall av Primater på nynorsk?
Wikipediaartikkel sier Primatar, men samme artikkel bruker også "kloten" for kloden (selv om det sikkert er riktig det og).

**Comment by danmichaelo** [comment]
Herlig illustrasjon av primat på [den artikkelen](https://nn.wikipedia.org/wiki/Primatar)!

Men dette er jo bare å sjekke den glimrende ordboken som UiB har *reddet* fra slemme UiO som ikke ville ha den: http://ordbok.uib.no/perl/ordbok.cgi?OPP=Primat&ant_bokmaal=5&ant_nynorsk=5&begge=+&ordbok=begge

[Klote](http://ordbok.uib.no/perl/ordbok.cgi?OPP=klote&ant_bokmaal=5&ant_nynorsk=5&begge=+&ordbok=begge) er også riktig (nå lærte eg noko njnytt!)

**Comment by Hypsibius** [comment]
Og ja, Ordboka er seif. For no...

**Comment by bibliomari** [comment]
My God, jeg savner dere! Ikke like kule emneord på jussen :-)

9. nov. 2017 10.24 skrev "Hypsibius" <notifications@github.com>:

**Comment by danmichaelo** [comment]
Fiksa `Primat` -> `Primatar`. God helg!
