### ISSUE TITLE
Fri energi

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#108]
Vet ikke helt hur dette sentrale begrep ikke har kommet med ennå

    Fri energi
    BF Gibbs fri energi
    BF Helmholtz fri energi
    BF Fri entalpi
    NN Fri energi
    EN Free energy
    EN Gibbs free energy
    EN Helmholtz free energy

Jeg tenker det er uproblematisk å slå sammen Gibbs og Helmholtz.

Jeg tenker og at strengen `Fri energi : Beregninger` er relevant (eller termen `fri-energi-beregninger`).

Belegg http://bibsys-primo.hosted.exlibrisgroup.com/UBB:BIBSYS_ILS150136080

**Comment by knuthe** [comment]
Jeg har ikke mye å si til dette annet enn at jeg setter pris på å lære hvordan man lenker direkte til et objektid i Oria.

**Comment by mittinatten** [comment]
De genereres gjennom _send til_, liker de bedre enn de en får ved å bruke _permanent lenke til denne posten_ under _detaljer_.

Har fått beskjed om å bruke lenker på følgende form for å få de institusjonsuavhengige: www.oria.no?search=BIBSYS_ILS150136080, men den formen er tydeligvis ikke garantert å være permanent.

**Comment by mittinatten** [comment]
Finnes "oria," som kommando i terminalen nå også

**Comment by danmichaelo** [comment]
Snedig, den institusjonsuavh. formen kjente jeg ikke til. Uheldigvis får jeg null treff siden UBO ikke har den... Tenk så mye triveligere det hadde vært om Oria kunne si "Ingen treff ved ditt bibliotek, men dokumentet finnes ved ett eller flere andre norske fagbibliotek". But I digress...

Selv om "Fri energi" er et sentralt *begrep* kan jeg godt tenke meg at det ikke er *emne* for så mange dokumenter (selv om det er omtalt i mange). Men greit å få på plass.

**Comment by mittinatten** [comment]
Ja, det kan hende beleggen ikke er så mange, men vi har entropi, energi og entalpi allerede, og fri energi-beregninger _burde_ jo i hvert fall være et tema :)

Jeg er òg missfornøyd med hvordan treffene vises når de ikke finnes på ens egen institusjon.

**Comment by danmichaelo** [comment]
Oppretta!
