### ISSUE TITLE
Kloakk

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1080]
Har litt dobbel betydning, både kloakk som i avløpssystemer og kloakk som i zoologi.

---
*REAL005066 (Kloakk) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005066), [Skosmos](http://data.ub.uio.no/realfagstermer/c005066), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kloakk%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL005066)*

**Comment by Hypsibius** [comment]
Nemleg! Skal vi spesifisere med parentesar igjen?

**Comment by BioHeidi** [comment]
Vi har foreløpig kun brukt det på avløpsvann. Kan vi fikse det så enkelt som at vi slår sammen? Avløpsvann BF Kloakk? Og så eventuelt oppretter Kloakk som egen term ved behov?

**Comment by danmichaelo** [comment]
Gjort!
