### ISSUE TITLE
Karoo

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1081]
Endre til stedsterm?

---
*REAL011428 (Karoo) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011428), [Skosmos](http://data.ub.uio.no/realfagstermer/c011428), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Karoo%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL011428)*

**Comment by Hypsibius** [comment]
Ja, er det også noko anna?

**Comment by danmichaelo** [comment]
Ja, det var termterm :D 650 altså.. Flytta nå:

    almar replace '650 Karoo' '651'
