### ISSUE TITLE
Havforskning og Oseanografi

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1082]
Slå sammen? Oseanografi som foretrukket?

* REAL008679 (Havforskning) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008679), [Skosmos](http://data.ub.uio.no/realfagstermer/c008679), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Havforskning%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008679)
* REAL008096 (Oseanografi) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008096), [Skosmos](http://data.ub.uio.no/realfagstermer/c008096), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Oseanografi%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008096)

**Comment by Hypsibius** [comment]
Her er eg ikkje einig. Havforsking omfattar mykje meir enn oseanografi, det omfattar i tillegg marinbiologi, marin ressursforvaltning, marin geologi, marin kjemi etc. Visst finst biologisk oseanografi (som ikkje heilt samanfell med marinbiologi), men står 'oseanografi' åleine, oppfattar eg (som marinbiolog) det som i snever form!

**Comment by BioHeidi** [comment]
Enig med @Hypsibius. Men mulig det burde ryddes (av noen)

**Comment by danmichaelo** [comment]
Lukker denne som duplikat av #426
