### ISSUE TITLE
Foreslår ny stadterm: Californiabukta

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1083]
BF Californiabukten BF Golfo de California NN Californiabukta EN Gulf of California EN Sea of Cortez

http://www.sprakradet.no/sprakhjelp/Skriverad/navn-pa-steder-og-personer/Geografiske_namn/utanlandske-stadnamn-aa/#c

https://snl.no/Golfo_de_California

Aktuelt dokument: https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71549096810002201

**Comment by danmichaelo** [comment]
Oppretta! Beklager at det tok sykt lang tid!
