### ISSUE TITLE
Foreslår ny term Stortare

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1084]
Stortare NN Stortare LA Laminaria hyperborea 

https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=11230#null

https://snl.no/stortare

Aktuelt dokument https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71488386430002201

**Comment by BioHeidi** [comment]
Gjort :)
