### ISSUE TITLE
Marker

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#1086]
https://app.uio.no/ub/emnesok/realfagstermer/search?term=Marker 

Det ser ut som marker har blitt brukt om både "Mark og eng"-marker og meitemark-marker.
Her trengs det definisjon og litt homonymi-rydding.

**Comment by BioHeidi** [comment]
Vekk med marker for leddormer iallefall!

**Comment by danmichaelo** [comment]
Du tar denne med almar, @BioHeidi ? Si fra hvis du trenger hjelp!
