### ISSUE TITLE
Berøring

### ISSUE THREAD

**Issue by starseekr** [realfagstermer/realfagstermer#1087]
Savner et ord for alle ting touch-basert innen IT? Touch skjermer, bord - gestural og touch interfaces. 

Grensesnitt : berøring?

**Comment by starseekr** [comment]
...ordnett.no sier forøvrig at touch kan oversettes til tøtsj(!).

**Comment by danmichaelo** [comment]
```
Berøringsgrensesnitt
BF Tøtsjgrensesnitt
```

kanskje?

**Comment by danmichaelo** [comment]
@starseekr ?

**Comment by starseekr** [comment]
Beklager! Ja! Det ser veldig bra ut. Selv om jeg får litt spader av å se det stavet tøtsj :)
