### ISSUE TITLE
Flertydig: Spektralanalyser

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#109]
Som Simon påpekte har vi både `Spektrumanalyse` og `Spektralanalyser`, som burde kunne slås sammen. Men dessverre ser sistnevnte ut til å [være brukt](http://ask.bibsys.no/ask/action/result?cql=%28bs.lokoeo-frase+%3D+%22Spektralanalyser%22%29++AND+%28bs.avdeling+%3D+%22ureal?%22%29&aktivKilde=biblio%3AUBO) i minst to av betydningene gitt på disambigueringssiden https://en.wikipedia.org/wiki/Spectral_analysis 

* Dette: http://ask.bibsys.no/ask/action/show?pid=962173614&kid=biblio
* er noe helt annet enn dette: http://ask.bibsys.no/ask/action/show?pid=971015341&kid=biblio

Antakelig må vi omklasse en del bøker for å få ryddet opp.

**Comment by mittinatten** [comment]
Hmm, sammenslåing var kanskje ikke så enkelt som jeg først trodde. Definisjoner nødvendige?

Hva med:

     Spektroskopi
     BF Spektrumanalyse
     EN Spectroscopy
     EN Spectrum analysis
     SO Spektralteori

og 

     Spektralteori 
     BF Spektralanalyse
     SO Spektrumanalyse

Sikkert en del omklassing nødvendig, men ingen risiko for feilklassing seinere tror jeg?

**Comment by danmichaelo** [comment]
Hm, nå ble jeg i tvil...
* Jeg lurer på om eksempelet jeg fant var et særtilfelle, og at det er bedre å ha `Spektralanalyse` under `Spektroskopi`. Jfr. SNL.
* Eller kanskje vi skal ha `Spektralanalyse BF Spektrumanalyse BF Frekvensanalyse SO Spektroskopi SO Spektralteori` som et eget emne?

Antakelig trenger vi definisjoner.. 

* [ ] Og forresten kan vi vel slette `Spektralfysikk` som term?

**Comment by mittinatten** [comment]
Vanskelig dette! Jeg tenker vi har tre konsepter:

1. Spektroskopi: Å måle spektrum til fysiske objekt og prosesser, en eksperimentell metode. Termen brukes ofte om selve analysen også: "vi fant ut X ved hjelp av Y-spektroskopi". 

2. "Spektral(um)analyse": Analyse av spektrum til fysiske objekt og prosesser (som i SNL-artikkelen), altså å prøve å forstå det en har målt med spektroskopisk metoder - men også analyse av spektrum i overført forstand, for eksempel frekvenser i stokastiske prosesser.

3. Spektralteori: Studie av egenverdispektrum til matematiske operatorer

Jeg tror vi trenger å separere de tre (som i ditt andre kulepunkt). Har ingen sterke meninger om Spektral- vs Spektrumanalyse som foretrukket. Hvis vi kutter ut spektralanalyse i overført forstand fra 2. kan vi slå sammen 1. og 2. med spektroskopi som term.

Ja til sletting av Spektralfysikk.

**Comment by danmichaelo** [comment]
Gjort (omklasset tre bøker)
