### ISSUE TITLE
Fotokjemiske oksydanter

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1091]
Endre til "oksidanter"? Eventuelt legge til `Fotokjemiske oksidanter` og ha det som foretrukket term, med `Fotokjemiske oksydanter` som ekstra?

---
*REAL003196 (Fotokjemiske oksydanter) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003196), [Skosmos](http://data.ub.uio.no/realfagstermer/c003196), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Fotokjemiske%20oksydanter%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL003196)*

**Comment by Hypsibius** [comment]
Oksidanter har vi frå før (Oksidanter (REAL006038)) , alle tre treff (snevert søk, alle bibl) der omhandlar såvidt eg kan sjå også fotokjemiske oksidantar.  Synest derfor det mest fornuftige er å bruke oksidanter for begge. Skulle det bli behov seinare, får vi heller skille ut Fotokjemiske Oksidanter då.

**Comment by danmichaelo** [comment]
Endret til `Fotokjemiske oksidanter`, flettet inn og fjernet `Oksidanter` i stedet. `Oksidant` / `Oksidasjonsmidler` er jo *veldig* bredt? Skrik ut hvis uenig.
