### ISSUE TITLE
Mössbauer-effekten

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1092]
Her er det gode muligheter for flere kombinasjoner (ö/ø, bindestrek/ikke, ss/ß) hvis noen er gira!

---
*REAL012658 (Mössbauer-effekten) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c012658), [Skosmos](http://data.ub.uio.no/realfagstermer/c012658), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22M%C3%B6ssbauer-effekten%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL012658)*

**Comment by danmichaelo** [comment]
Dette vokser fort til mange kombinasjoner.. jeg tok noen ihvertfall :)
