### ISSUE TITLE
NK-celler

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1093]
Legge til `Naturlige dreperceller` på norsk?

---
*REAL012031 (NK-celler) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c012031), [Skosmos](http://data.ub.uio.no/realfagstermer/c012031), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22NK-celler%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL012031)*

**Comment by Hypsibius** [comment]
:-O

**Comment by danmichaelo** [comment]
:boom: Oh yeah!
