### ISSUE TITLE
Domkirkeodden

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1096]
Dette står som museum i realfagtermers beskrivelse. Da skal det kanskje ut av realfagstermer?

---
*REAL030897 (Domkirkeodden) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030897), [Skosmos](http://data.ub.uio.no/realfagstermer/c030897), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Domkirkeodden%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL030897)*

**Comment by danmichaelo** [comment]
Slettet
