### ISSUE TITLE
Bøhmen

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1097]
Foreslår alternativ skrivemåte / endring: -> Böhmen
---
*REAL030469 (Bøhmen) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030469), [Skosmos](http://data.ub.uio.no/realfagstermer/c030469), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22B%C3%B8hmen%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL030469)*

**Comment by Hypsibius** [comment]
Jf http://www.sprakradet.no/sprakhjelp/Skriverad/navn-pa-steder-og-personer/Geografiske_namn/utanlandske-stadnamn-aa/#b

**Comment by danmichaelo** [comment]
Endra!
