### ISSUE TITLE
Børsjøen

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1098]
Det er mange sjøer som heter Børsjøen. Denne er i Tynset kommune. Kan kanskje legges til?

---
*REAL030649 (Børsjøen) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030649), [Skosmos](http://data.ub.uio.no/realfagstermer/c030649), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22B%C3%B8rsj%C3%B8en%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL030649)*

**Comment by danmichaelo** [comment]
Lagt på def.!
