### ISSUE TITLE
Fogo

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1099]
Foreslår å legge til en note her som sier at dette er Fogo på Kapp Verde, det finnes Fogo Island i Canada også.

---
*REAL030872 (Fogo) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030872), [Skosmos](http://data.ub.uio.no/realfagstermer/c030872), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Fogo%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL030872)*

**Comment by danmichaelo** [comment]
God idé, gjort
