### ISSUE TITLE
Galapagos

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1102]
Foreslår Galápagosøyene som skrivemåte her.

http://www.sprakradet.no/sprakhjelp/Skriverad/navn-pa-steder-og-personer/Geografiske_namn/utanlandske-stadnamn-aa/#g
---
*REAL030522 (Galapagos) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030522), [Skosmos](http://data.ub.uio.no/realfagstermer/c030522), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Galapagos%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL030522)*

**Comment by danmichaelo** [comment]
:earth_asia: Gjort!
