### ISSUE TITLE
Gironde

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1103]
på min liste (https://lambda.biblionaut.net/export/list-real-geo.html) 
for Gironde, står det "estuary", som tilsier at det er snakk om en elvemunning. Det fremgår dog ikke av selve termen. Hva er rett? Om det er en elvemunning, bør det kanskje presiseres?

---
*REAL030859 (Gironde) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030859), [Skosmos](http://data.ub.uio.no/realfagstermer/c030859), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Gironde%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL030859)*

**Comment by danmichaelo** [comment]
Ganske sikker på at denne var feilmappa. Har endra til departementet. Lista skal være riktig på mandag.
