### ISSUE TITLE
Herøy (Møre og Romsdal)

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1104]
Er denne realfagstermen inne igjen? I ccmapper ligger det kommentar om at den er slettet.

---
*REAL030617 (Herøy (Møre og Romsdal)) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030617), [Skosmos](http://data.ub.uio.no/realfagstermer/c030617), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Her%C3%B8y%20(M%C3%B8re%20og%20Romsdal)%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL030617)*

**Comment by danmichaelo** [comment]
Kan det ha vært en midlertidig glitch i ccmapper? Ser ikke noe note om det nå. Og finner ingenting på vår side som tyder på at den har vært slettet
