### ISSUE TITLE
Diverse

### ISSUE THREAD

**Issue by HegeNenseth** [realfagstermer/realfagstermer#1105]
Slå sammen [Elektrotermisk atomisering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001022) og [Atomisering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005324)?
[Eukalyptus](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c007009) / [Eucalyptus](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005094)
Endre på/slå sammen [Endoparasittisme (Endozoa)](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005046) og [Entozoa](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001607)

**Comment by danmichaelo** [comment]
> Slå sammen [Elektrotermisk atomisering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001022) og [Atomisering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005324)?

Gjort! Jeg beholdt bare `Atomisering` som term.

> [Eukalyptus](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c007009) / [Eucalyptus](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005094)

Takk! Beholdt `Eukalyptus` som hovedterm.

> Endre på/slå sammen [Endoparasittisme (Endozoa)](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005046) og [Entozoa](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001607)

@BioHeidi, tar du denne? `Endoparasittisme BF Entozoa`...?

**Comment by BioHeidi** [comment]
FIkset! Nå er det:
Endoparasitter BF Endoparasittisme, Endozoa, Entozoa
