### ISSUE TITLE
Spesifikke verk → 630-feltet

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#1107]
Som [Almagest](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Almagest)

Og se #255

**Comment by danmichaelo** [comment]
og [Kyotoavtalen](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011299), fra #1176

**Comment by danmichaelo** [comment]
- [x] Almagest
```diff
-650 #7 $a Almagest $2 noubomn $0 (NO-TrBIB)REAL000405
+630 07 $a Almagest $2 bare $0 (NO-TrBIB)1542227320952
```
