### ISSUE TITLE
Langtjern

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1109]
Det er en upregnant tittel. Jeg foreslår å slette denne. 3 dokumenter, vanskelig å finne ut hvilken Langtjern det er snakk om  - eller om det er snakk om det samme.

---
*REAL030448 (Langtjern) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030448), [Skosmos](http://data.ub.uio.no/realfagstermer/c030448), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Langtjern%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL030448)*

**Comment by danmichaelo** [comment]
Enig, ser at jeg hadde lagt inn kommentaren "men hvilken Langtjern??" i oversettingsverktøyet. Bare brukt på et par masteroppgaver, muligens om forskjellige tjern, så jeg sletter.
