### ISSUE TITLE
Liquid etc

### ISSUE THREAD

**Issue by knuthe** [realfagstermer/realfagstermer#111]
Noen som har bedre greie på fagfeltet, kan kanskje se på de termene som begynner på Liquid (se nedenfor). De bør (muligens) få norsk betegnelse og den engelske bør stå i engelsk-feltet.

![liquid](https://cloud.githubusercontent.com/assets/9070826/6021726/226f8c92-abb8-11e4-8567-1c0667ffe8e1.png)

**Comment by mittinatten** [comment]
Kan ikke fagfeltet heller, men wikipedia og SNL bruker væskekromatografi. Vi har termene gasskromatografi og gasskromatografi-massespektrometri fra før.

**Comment by mittinatten** [comment]
De termene på HPLC bør vurderes i samme slengen

**Comment by bibliomari** [comment]
God start, @danmichaelo. Vi får involvere Tone i fortsettelsen.

**Comment by BioHeidi** [comment]
Jeg har noen av disse på listen min. Jeg er ekspert i den forstand at jeg selv har kjørt HPLC, men da tenkte jeg ikke så mye over hva det het (haha)

Utdrag fra min retteliste, kun de som har med liquid å gjøre:

High-performance liquid chromatography -> High performance liquid chromatography
Hplc -> High performance liquid chromatography (Legg på akronym + BF High pressure l.c.)
Høyoppløselig væskekromatografi -> High performance liquid chromatography
Høyoppløselig spektroskopi -> NMR?

Men om vi skal konvertere til skikkelig norsk (jeg er jo egentlig tilhenger av det der det gir mening) så må det ses på igjen. Må bare få tilføye ay ingen jeg har hørt som bruker teknikkene sier "høyoppløselig væskekromatografi", men jeg har hørt "væskekromatografi" brukt, så jeg er ikke imot.

**Comment by danmichaelo** [comment]
Men de sier vel ikke "High performance liquid chromatography" heller? Jeg heller mot å bruke akronymer som foretrukket term på de lengre variantene (HPLC, ...) og norske navn på de enkle ("Væskekromatografi", "Gasskromatografi", ...)

**Comment by bibliomari** [comment]
Jeg har vekket denne til live igjen, og har omsider gjennomført de foreslåtte endringene, etter beste evne. Strever litt med språkvariantene her... Jeg har blant annet samlet alle "high performance liquid chromatography"/HPLC under Høyytelsesvæskekromatografi. Jeg innrømmer at det ser rart ut. 

Sender nå resten av saken videre til vår kjemiker.

**Comment by danmichaelo** [comment]
Rydda videre i kromatografimetodene nå, deriblant HPLC:

```
HPLC
BF Høyoppløselig væskekromatografi
BF Høyytelsesvæskekromatografi
BF Høypresisjonsvæskekromatografi
NN …
EN High performance liquid chromatography
EN High pressure liquid chromatography
```

Tok ikke med `High price liquid chromatography` :D

Sletta `Høyoppløselig spektroskopi`.

**Comment by danmichaelo** [comment]
Lukker siden vi ikke har noen gjenværende uoversatte "Liquid*"-termer
