### ISSUE TITLE
Papua New Guinea

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1110]
http://www.sprakradet.no/sprakhjelp/Skriverad/navn-pa-steder-og-personer/Geografiske_namn/utanlandske-stadnamn-aa/#p

Bruke norsk navneform?

 
*REAL030581 (Papua New Guinea) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030581), [Skosmos](http://data.ub.uio.no/realfagstermer/c030581), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Papua%20New%20Guinea%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL030581)*

**Comment by danmichaelo** [comment]
Ja, vi følger Språkrådet når vi kan! Fikser!
