### ISSUE TITLE
Vegårdsvassdraget

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1111]
Finner skrivemåten Vegårvassdraget (uten d) når jeg søker, bla på Wikipedia

---
*REAL030706 (Vegårdsvassdraget) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030706), [Skosmos](http://data.ub.uio.no/realfagstermer/c030706), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Veg%C3%A5rdsvassdraget%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL030706)*

**Comment by danmichaelo** [comment]
Det skal være Vegårvassdraget, ja! Fikser!
