### ISSUE TITLE
Stable marriage problem

### ISSUE THREAD

**Issue by jennynnej** [realfagstermer/realfagstermer#1112]
Er dette det norske uttrykket for det?

---
*REAL000722 (Stable marriage problem) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000722), [Skosmos](http://data.ub.uio.no/realfagstermer/c000722), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Stable%20marriage%20problem%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000722)*

**Comment by danmichaelo** [comment]
Antakelig ingen som har oversatt dette før.

Stabilt ekteskapsproblem? Det stabile ekteskapsproblemet? Ekteskapsproblemet..?

**Comment by mittinatten** [comment]
Da burde vi benytte anledningen til å kalle det Ekteskapsproblemet.

**Comment by danmichaelo** [comment]
Jeg synes den er fin! Kanskje vi får noen google-treff også :D

**Comment by Hypsibius** [comment]
Kva med 'Stable Genious Problem'?
