### ISSUE TITLE
Sammenslåinger 12.01.18

### ISSUE THREAD

**Issue by HegeNenseth** [realfagstermer/realfagstermer#1114]
Foreslår å slå sammen følgende:

- [Fikspunkter](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011827) og [Fikspunkt](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010792)

- [Fiskehjernen](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011971) og [Fisker--Hjernen](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031347​)

- [Flavoner](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004445) og [Flavonoider](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005100) (?)

- [Fletting](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009228) og [Flettesortering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010957)

**Comment by danmichaelo** [comment]
> Foreslår å slå sammen følgende:
> 
> - [Fikspunkter](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011827) og [Fikspunkt](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010792)

:heart:  Gjort

> - [Fiskehjernen](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011971) og [Fisker--Hjernen](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031347​)

Huhu, ja.. Vi har nok en del slike for tidligere har vi ikke kunne erstatte strenger med enkle termer på postene. Men nå skal vi kunne gjøre det med [almar](https://github.com/scriptotek/almar), så jeg prøver meg på denne nå. Gjort.

> - [Flavoner](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004445) og [Flavonoider](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005100) (?)

Ser ut som flavoner er en type flavonoider, men med litteraturbelegget vårt synes jeg det gir mening å slå sammen. Gjort.

> - [Fletting](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009228) og [Flettesortering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010957)

Slettet `Fletting`. For mangetydig.
