### ISSUE TITLE
Very large scale integration

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1115]
Er det norske emnet det engelske?

---
*REAL009310 (Very large scale integration) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009310), [Skosmos](http://data.ub.uio.no/realfagstermer/c009310), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Very%20large%20scale%20integration%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009310)*

**Comment by danmichaelo** [comment]
Noen ganger kan det forsvares å bruke det engelske ordet på norsk. Men i dette tilfellet lurer jeg på om det er bedre å bare bruke akronymet som hovedterm. Tror man ville sagt VLSI på norsk.

**Comment by danmichaelo** [comment]
Endret til VLSI
