### ISSUE TITLE
Stugusjøen

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1116]
Denne stugusjøen er i Tydal, ihht litteraturbelegget 
Legge på en kvalifikator?

---
*REAL030564 (Stugusjøen) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030564), [Skosmos](http://data.ub.uio.no/realfagstermer/c030564), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Stugusj%C3%B8en%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL030564)*

**Comment by danmichaelo** [comment]
Vi har definisjon, men den nevnte Sør-Trøndelag :D Må kjøre søk-og-erstatt "Sør/Nord-Trøndelag" -> "Trøndelag" nå..
