### ISSUE TITLE
Sølna

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1117]
Her er det ikke overensstemmelse mellom realfagsterm og dokument. 
Emneordet er Sølna, men engelsk: Solna municipality.

Dette kan enten være Solna ved Stockholm i Sverige (stemmer med engelsk term), eller det kan være Sølna som er en eller flere elver i Hedmark. Det stemmer utfra boken som har fått emneordet. Jeg mapper ikke denne foreløpig.

---
*REAL030721 (Sølna) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030721), [Skosmos](http://data.ub.uio.no/realfagstermer/c030721), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22S%C3%B8lna%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL030721)*

**Comment by danmichaelo** [comment]
Slettet, brukt på ett dokument (https://www.nb.no/items/URN:NBN:no-nb_digibok_2012071308196)
