### ISSUE TITLE
Sørnesset

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1118]
Det Norske videnskaps-akademi (Sørnesset, Sollia) \|b Biologisk stasjon

--

Lurer på om denne bør utgå fra realfagstermer. Finnes som 110 i BARE

---
*REAL031061 (Sørnesset) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c031061), [Skosmos](http://data.ub.uio.no/realfagstermer/c031061), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22S%C3%B8rnesset%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL031061)*

**Comment by danmichaelo** [comment]
Enig! Gjort:

```bash
almar --diffs replace \
    '651 #7 $$a Sørnesset $$2 noubomn'
    '610 27 $$a Det Norske videnskaps-akademi (Sørnesset, Sollia) $$b Biologisk stasjon $$2 bare'
```

Resultat:
```diff
--- Original
+++ Modified
-651 #7 $a Sørnesset $2 noubomn
+610 27 $a Det Norske videnskaps-akademi (Sørnesset, Sollia) $b Biologisk stasjon $2 bare $0 (NO-TrBIB)1021897
```
