### ISSUE TITLE
Transylvania

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1119]
http://www.sprakradet.no/sprakhjelp/Skriverad/navn-pa-steder-og-personer/Geografiske_namn/utanlandske-stadnamn-aa/#t

Transilvania (tysk Siebenbürgen) landskap i Romania; transilvansk

Endre skrivemåte?
---
*REAL030738 (Transylvania) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030738), [Skosmos](http://data.ub.uio.no/realfagstermer/c030738), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Transylvania%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL030738)*

**Comment by danmichaelo** [comment]
Gjort!
