### ISSUE TITLE
Diøci - tillegg

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#112]
Var litt i stuss om dette er korrekt form av ordet, @BioHeidi  , for det var temmeleg få treff. Finn ikkje heilt noko betre heller. Forslag? Foreslår at vi definerer 'særbu' som foretrukken term BF 'tvebu' og 'diøci'. EN dioecy.

**Comment by Hypsibius** [comment]
Få treff, som i google-treff. Beklager, dårleg på å gi kontekst her....

**Comment by BioHeidi** [comment]
Særkjønnet er det mest brukte (og mest forståelige, jeg har aldri hørt om diøci). Kan vi bruke det, eller er det konflikt et sted? Har også hørt begrepet diklinisk brukt om planter, det kan vi evt legge på som BF.

**Comment by Hypsibius** [comment]
Hadde heller ikkje høyrt ordet diøci, men kunne resonnere meg fram, iom at eg har høyrt diøk/monoøk om særkjønna/samkjønna. Men skal vi ikkje fram til ei substantivform? Så blir det evt 'særkjønnethet', som synest litt *konstruert* på meg...

**Comment by Hypsibius** [comment]
Men særbu og sambu har eg høyrt brukt, også i denne samanheng ;-)

**Comment by BioHeidi** [comment]
Joo, særkjønnethet? Særkjønn? Hm. Særbu og sambu er så... NYnorsk! :dancers:

**Comment by Hypsibius** [comment]
Åja, eg tenkte det var ein rest etter samnorsk (særnorsk?), men særbo/sambo skulle vel også fungere?

Damer? Og Edit? Kven er det? :dancers:

**Comment by danmichaelo** [comment]
Som her : https://no.wikipedia.org/wiki/S%C3%A6rbu ?

**Comment by danmichaelo** [comment]
(denne er kanskje ikke heeelt "ferdig diskutert", men nesten :))

**Comment by Hypsibius** [comment]
Ja, som der. Låg denne der for eit par månader sidan? Må ha sjekka litt dårleg ,-)

Og om nokon vil diskutere denne vidare utover kvelden, så har eg kveldsvakt og må jo finne på NOKE å gjere på....

**Comment by danmichaelo** [comment]
Opprettet i 2007 av https://no.wikipedia.org/wiki/Bruker:Hanno ;)

**Comment by Hypsibius** [comment]
Då så :-)

**Comment by BioHeidi** [comment]
Gjort, med masse BFer
