### ISSUE TITLE
Vosges

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1120]
Vosges er både et departement i Frankrike og et fjellområde. I denne filen: https://lambda.biblionaut.net/export/list-real-geo.html står det at det er fjell. Det bør kanskje presiseres for å unngå misforståelser?

---
*REAL030476 (Vosges) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030476), [Skosmos](http://data.ub.uio.no/realfagstermer/c030476), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Vosges%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL030476)*

**Comment by danmichaelo** [comment]
Lagt på def. "fjellkjede øst i Frankrike"
