### ISSUE TITLE
Lipariske øyer

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1121]
Språkrådet bruker Lipariøyene
http://www.sprakradet.no/sprakhjelp/Skriverad/navn-pa-steder-og-personer/Geografiske_namn/utanlandske-stadnamn-aa/#l

---
*REAL031213 (Lipariske øyer) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c031213), [Skosmos](http://data.ub.uio.no/realfagstermer/c031213), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Lipariske%20%C3%B8yer%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL031213)*

**Comment by danmichaelo** [comment]
Endra!
