### ISSUE TITLE
Ryddeforslag Flyging

### ISSUE THREAD

**Issue by HegeNenseth** [realfagstermer/realfagstermer#1123]
[Flyging](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c003683) er brukt om både om dyrs flyging og luftfart.

**Comment by danmichaelo** [comment]
Høres ut som en grei `almar interactive`-jobb. Forbeholde Flyging for dyr, og flytte resten til [Flyteknikk](http://data.ub.uio.no/realfagstermer/c001476) e.l.? Har du lyst, @BioHeidi ?

**Comment by BioHeidi** [comment]
Vil gjerne, men får feilmelding i almar:
![image](https://user-images.githubusercontent.com/8614183/36965591-69105b9e-205a-11e8-832e-d5976022f1c3.png)

**Comment by danmichaelo** [comment]
Hm, du kjører Python 2, det er ikke helt bra. Jeg har egentlig prøvd å fått aktivert Python 3 for alle brukere, men det har jeg visst ikke klart. Kanskje fordi du bruker et annet shell enn Bash. Har gjort en endring nå, kan du se om det hjalp? Skriv `python --version` og se om du får `Python 3.6.3`. Isåfall bør det helst funke.

**Comment by BioHeidi** [comment]
Fikset sånn at jeg kjører bash, så da fikk jeg versjon 3.6.3. Siden jeg skulle gå nå (i sted) så får jeg teste i morgen om det faktisk funket ;)

**Comment by BioHeidi** [comment]
Gjort!
