### ISSUE TITLE
Padleturer

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#1125]
Det er kommet inn forslag om emneord: Padleturer. 
Vi bør kanskje ta stilling til om vi skal beholde spesifikke turer i termer slik eller lage strenger eks Turer:Padling eller lignende.

Også forslag om streng her:

Padleturer:Norge

Gi beskjed til Gro Synnøve! @grosyn

**Comment by danmichaelo** [comment]
`Ferdsel på vann : Fritid`? Neida :D

Gjelder det en turbok, @grosyn ? Vi har jo formen `Turbøker`, så vi kunne kanskje laget strengen `Padling : Turbøker`?

**Comment by Hypsibius** [comment]
Så har vi na-tur. Pågår det ferieplanlegging der aust?

**Comment by danmichaelo** [comment]
Glemte BF :canoe:

**Comment by BioHeidi** [comment]
Hva ble konklusjonen? :D

**Comment by kyrretl** [comment]
Beklager kortfattethet!
Her er konklusjonen: https://app.uio.no/ub/emnesok/realfagstermer/search?id=c031947&broad=true&lang=nn

Vi la til Kano- og kajakkpadling som term
