### ISSUE TITLE
Deformasjoner BF Formendringer

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#1128]
ref Edina

**Comment by BioHeidi** [comment]
Jeg tror denne sto åpen fordi vi trenger å rydde bort termen (over på Deformasjoner (Geologi) eller Deformasjoner (Matematikk). Såvidt jeg kan se er det ikke gjort ennå.

**Comment by kyrretl** [comment]
Denne saken ble lukket da vi løste Deformasjoner BF Formendringer, men vi har en egen sak om Deformasjoner, gående: se: 

https://github.com/realfagstermer/realfagstermer/issues/566

Lukker denne saken om det ikke er videre behov for å diskutere Deformasjoner vs Formendringer
