### ISSUE TITLE
Hypoteser BF Formodning

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#1129]
Er litt usikker på om formodning har en annen betydning, men det står bf hypotese på den...?

**Comment by Hypsibius** [comment]
Det synest eg ikkje er det same. Å formode er å anta, Det vbil seie at konklusjonen er sannsynleggjort. Ei hypotese må vere opa og falsifiserbar. 

![image](https://user-images.githubusercontent.com/9350370/35216459-fb14982a-ff67-11e7-9d50-d21f7d2675e1.png)

**Comment by kyrretl** [comment]
Enig. En hypotese i Realfagstermers øyemed er ikke bare en formodning

**Comment by danmichaelo** [comment]
[REAL001647](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c001647) Formodning bør avgrenses til matematiske formodninger ([conjecture](https://en.wikipedia.org/wiki/Conjecture)). Legger inn definisjon "en antatt sann setning som ennå ikke har blitt bevist". Snodig nok hadde den også NN Hypotese, endret det til Formodning.
