### ISSUE TITLE
Drift - spesifisere fagområde

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#113]
Vi har eigen term drift (utan spesifisering) , i tillegg til genetisk drift og kontinentalderift. I daglegtalen omtalar gjerne både genetikarar og geologar det som 'drift', samtidig som ordet også kan ha andre tydingar, som kvegdrift etc etc etc http://www.nob-ordbok.uio.no/perl/ordbok.cgi?OPP=+drift&bokmaal=+&ordbok=bokmaal For å leie folk rett, ville det vere greitt å spesifisere fagområde. 

I denne kjapt søk tydar på at vi snakkar om drift av verksemder og ulike slags anlegg, kan nokon kome opp med ei god spesifisering?

**Comment by knuthe** [comment]
Jeg fikk 6 treff hos oss, hvorav 5 dreidde seg om datasystemer og nettverk), den siste om bygninger. Jeg innfører "drift (datasystemer)" for de fem og "drift (anlegg)" for den siste (og venter litt før jeg gjør det ...)

**Comment by Hypsibius** [comment]
Fint! Så får vi innføre kvegdrift etc. ved behov. Blitt nokre år sidan siste drifta gjekk over Jostedalsbreen på veg til slakteri, synest mindre aktuelt i våre dagar ;-)

Hege
