### ISSUE TITLE
Information processing language

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1130]
Finnes det et norskt emne? 

---
*REAL002736 (Information processing language) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002736), [Skosmos](http://data.ub.uio.no/realfagstermer/c002736), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Information%20processing%20language%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002736)*

**Comment by danmichaelo** [comment]
Tviler, dette er jo et egennavn, men fikser versalene: Information Processing Language
