### ISSUE TITLE
Large Magellanic Cloud

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1131]
Finnes det et norskt emneord?

---
*REAL000673 (Large Magellanic Cloud) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000673), [Skosmos](http://data.ub.uio.no/realfagstermer/c000673), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Large%20Magellanic%20Cloud%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000673)*

**Comment by danmichaelo** [comment]
[Den store magellanske skyen](https://no.wikipedia.org/wiki/Den_store_magellanske_skyen)? Fikser
