### ISSUE TITLE
Marker

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1132]
Dette emnet er marker både som i "skog og mark", og som i dyret mark. 

---
*REAL002962 (Marker) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002962), [Skosmos](http://data.ub.uio.no/realfagstermer/c002962), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Marker%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002962)*

**Comment by Hypsibius** [comment]
hmmmm. Burde vi dele opp?

**Comment by jeanetvi** [comment]
jeg trodde flertallsformen for mark var mark, så noe må gjøres ihvertfall :P

2018-01-22 11:29 GMT+01:00 Hypsibius <notifications@github.com>:

**Comment by Hypsibius** [comment]
Neida, marker er korrekt: 

![image](https://user-images.githubusercontent.com/9350370/35217785-bf8792b2-ff6c-11e7-8fcb-206ddeff294f.png)

**Comment by Hypsibius** [comment]
Det er vel elles desse betydelsane som er relevante for oss: 

![image](https://user-images.githubusercontent.com/9350370/35217855-ffb9e9ca-ff6c-11e7-80b1-781c63805064.png)

**Comment by BioHeidi** [comment]
Se her: #1086

**Comment by danmichaelo** [comment]
Lukker som duplikat
