### ISSUE TITLE
Biomatematikk og Matematisk biologi, Biomedisin og Matematisk medisin

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1133]
Disse har SO mellom seg, så noen har antakelig ønsket å beholde begge tidligere, men skjønner ikke umiddelbart fra litteraturbelegget hva tanken kan ha vært. Slå sammen eller legge på definisjoner?

* *REAL013365 (Biomatematikk) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013365), [Skosmos](http://data.ub.uio.no/realfagstermer/c013365), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Biomatematikk%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL013365)*
* *REAL013364 (Matematisk biologi) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013364), [Skosmos](http://data.ub.uio.no/realfagstermer/c013364), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Matematisk%20biologi%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL013364)*

---
* *REAL006011 (Biomedisin) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006011), [Skosmos](http://data.ub.uio.no/realfagstermer/c006011), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Biomedisin%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL006011)*
* *REAL011111 (Medisinsk biologi) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011111), [Skosmos](http://data.ub.uio.no/realfagstermer/c011111), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Medisinsk%20biologi%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL011111)*

**Comment by Hypsibius** [comment]
Du spør så vanskeleg. Sett på spissen er biomatematikk den delen av matematikken biologar finn det bryet verdt å setje seg inn i for å få analysert sine datasett. Matematisk biologi er den delen av biologien matematikikarane synest det er spennande å teste ut sine verkty på :-P

**Comment by danmichaelo** [comment]
Oi, vi hadde allerede en sak på biom: #537

**Comment by danmichaelo** [comment]
Vi slo sammen: `Biomatematikk BF Matematisk biologi`
