### ISSUE TITLE
Matematikkdidaktikk: Fikse engelsk

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1139]
Mathematics didactics som foretrukket

---
*REAL012459 (Matematikkdidaktikk) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c012459), [Skosmos](http://data.ub.uio.no/realfagstermer/c012459), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Matematikkdidaktikk%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL012459)*

**Comment by Hypsibius** [comment]
Ordet Didactics brukast annleis enn på norsk (SNL: Generelt omhandler didaktikk sammenhengen mellom undervisningens begrunnelse, innhold og gjennomføring. Mer konkret omfatter didaktikken kunnskap om sammenhengen mellom undervisningens gjennomtenkning, planlegging, gjennomføring og evaluering.) og nødig på engelsk, der 'didactic' = nedlatande.

**Comment by danmichaelo** [comment]
Interessant! Men UHRs termbase har oversatt didaktikk som [didactics](http://termbase.uhr.no/?q=didaktikk&submit=Oversett). Og google finner masterprogram i [didactics of mathematics](https://www.ugr.university/pages/prospective_students/masters_students/masters-programmes/didactics-of-mathematics). Så jeg lurer på om termen er tilstrekkelig etablert på engelsk til at vi kan bruke den? 

Tidligere hadde vi "Mathematics teaching" som engelsk term, men da ble det den samme oversettelsen på [Matematikkundervisning](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009721) – og det ble jo ganske forvirrende 😕

**Comment by mittinatten** [comment]
Termen er overraskende lite brukt i MESC
https://www.zentralblatt-math.org/matheduc/classification/. Mange treff i
databasen der, men ser ut som det er mye oversettelser.

**Comment by danmichaelo** [comment]
Sant nok. Men jeg tror ikke vi kan gjøre noe annet enn å oversette den som didactics, og heller ha SO-henvisning til/fra undervisning.
