### ISSUE TITLE
Seretonin -> Serotonin

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1141]
Skriveleif.

Sjekk samtidig om det kan være sammenslåingskandidater, ssri eller noe sånt

---
*REAL008520 (Seretonin) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008520), [Skosmos](http://data.ub.uio.no/realfagstermer/c008520), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Seretonin%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008520)*

**Comment by Hypsibius** [comment]
SSRI ligg under Antidepressiva (REAL013860)

![image](https://user-images.githubusercontent.com/9350370/35215883-fbdf9086-ff65-11e7-9841-0830f8ab1d25.png)

Treff på serotonin såg ut til å vere meir sprsifikt på stoffet og reseptorar, og ikkje på medisinsk effekt. Synest derfor det er greit å halde desse skilde.

**Comment by danmichaelo** [comment]
Ah, ja, jeg så bare på det ene dokumentet som hadde fått `Seretonin` (med "e"). Det så ut til å handle om antidepressiva. Men flytter det bare over til Serotonin siden det er litt vanskelig å vurdere uten dokumentet i handa.
