### ISSUE TITLE
nyterm Radiorekombinasjonslinjer

### ISSUE THREAD

**Issue by superLine** [realfagstermer/realfagstermer#1142]
Radio recombination lines er et begrep som er mye brukt - finner lite på norsk - sjekket med Maria og vi ønsker oss "radiorekombinasjonslinjer"

**Comment by danmichaelo** [comment]
Opprettet som REAL031944.

Tok sjansen på at det ble Radiorekombinasjonslinjer på nynorsk også..

**Comment by danmichaelo** [comment]
Er det greit med `Spektrallinjer` som overordnet? UAT har ingen oppføring på (Radio) recombination lines, men de har spectral lines, så hvis vi har en kobling dit får vi plassert begrepet litt.

**Comment by danmichaelo** [comment]
Ping @superLine

**Comment by kyrretl** [comment]
Vi gjorde det!
