### ISSUE TITLE
Div. sammenslåing 01.02.18

### ISSUE THREAD

**Issue by HegeNenseth** [realfagstermer/realfagstermer#1147]
Foreslår å slå sammen:

[Mallefisker](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004848) og [Maller](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c000714)

[Marine fugler](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004075) og [Sjøfugler](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c002250)

[Masseoverføring](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c002234) og [Massetransport](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c007612)

[Massedød](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c002126​) og [Masseutryddelser](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c006476)

[Matematikk : Undervisning](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c020542) og [Matematikkundervisning](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009721)

**Comment by Hypsibius** [comment]
Absolutt!

**Comment by danmichaelo** [comment]
@BioHeidi , tar du en titt også?

**Comment by kyrretl** [comment]
Masssedød er jo annerledes enn Masseutryddelser. 
Massedød er når masse individer  i en poplulasjon eller hele populasjoner dør ut, mens Masseutryddelse er utryddelse av arter.
Men siden alle (de fire) postene med emneordet Massedød egentlig handlet om Masseutryddelser, overførte vi alle postene fra Massedød -> Masseutryddelse og slettet Massedød ;-)

**Comment by danmichaelo** [comment]
> [Matematikk : Undervisning](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c020542) og [Matematikkundervisning](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009721)

Slått sammen. Vi har nok flere slike.
