### ISSUE TITLE
Sletteforlag 01.02.18

### ISSUE THREAD

**Issue by HegeNenseth** [realfagstermer/realfagstermer#1148]
Det finnes [Marine pattedyr](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009937), og [Sjøpattedyr](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c000527), da kan man kanskje slette [Marine sjøpattedyr](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008913)?

Har også kommet over følgende termer som er enten egennavn eller er uten dokumenter (noen er tilknyttet masteroppgaver) :

[Frekvensmodulasjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001674)
[Fremmedord](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009396)
[Fttc](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011718)
[Fugler : Hybridisering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031140)
[Fuglevern](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001065)
[Fulbright-stipend](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010386)
[Fyringsbriketter](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c002688​)
[Generell økonomisk operasjonsanalyse](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013176​)
[Magmatisk differensiasjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004383)
[Magnetisk avkjøling](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011731)
[Magnetiske ertser](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c006528)
[Florence-prosjektet](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008844)
[Magnetokalorisk effekt](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008526)
[Major histocompatibility complex](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004504)
[Major histocompatibility complex class 2](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c000106)
[Makrellfiske](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c006737)
[Makroanalyser](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013060)
[Makroprossesser](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009618)
[Malmanrikelser](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009285)
[Maskinen Frederic](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c000617​)
[Massestrømmer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031863)
[Matematisk astrofysikk](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013357)
[Maternell vektøkning](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009190​)
[Matriksinterferenser](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c006128)
[Matrikspreferanser](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001466)
[Medisinplanter : Mikroskopi](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c026986)
[Mesopelagialsonen](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031877)

**Comment by Hypsibius** [comment]
"Det finnes Marine pattedyr, og Sjøpattedyr, da kan man kanskje slette Marine sjøpattedyr?".  

NB! Ikkje slette, slå saman! Min personlege smak gpr i retning av å behandle Sjøpattedyr som hovudinnførsle, med BF Marine pattedyr!

**Comment by Hypsibius** [comment]
Behold også for all del mesopelagialsonen, så skal eg legge inn emneord og bedre mitt dårlege samvit!

**Comment by danmichaelo** [comment]
@BioHeidi , tar du en titt?

**Comment by Hypsibius** [comment]
Og plutseleg var det mange dokument på Mesopelagialsonen, i alle fall :-)

**Comment by BioHeidi** [comment]
**Fikset:**
Sjøpattedyr BF Marine pattedyr, Marine sjøpattedyr
Biobrensel BF Fyringsbriketter
Økonomisk operasjonsanalyse BF Generell økonomisk operasjonsanalyse (husker at @bibliomari en gang hadde en regel om at vi ikke skulle rydde i økonomitermene, men jeg har glemt hvorfor, og finner det ikke igjen!)
Magmatisme BF Magmatisk differensiasjon
Magnetokalorisk effekt BF Magnetisk avkjøling
Fiske BF Makrellfiske
Makroprossesser rettet til Markov-prosesser

**Slettet:**
Fttc (fiber to the curb)
Fuglevern
Fulbright-stipend (har Studiestipend som emneord)
Magnetiske ertser
Major histocompatibility complex
Major histocompatibility complex class 2
Makroanalyser
Medisinplanter  :Mikroskopi

**Beholdt:**
Fugler : Hybridisering (nå på 1 dok)
Mesopelagialsonen

**Overlater til andre:**
Frekvensmodulasjon
Fremmedord
Florence-prosjektet
Malmanrikelser
Maskinen Frederic
Massestrømmer
Matematisk astrofysikk
Maternell vektøkning
Matriksinterferenser
Matrikspreferanser

**Comment by danmichaelo** [comment]
**Slettet:**
Frekvensmodulasjon
Fremmedord
Malmanrikelser
Matematisk astrofysikk
Maternell vektøkning
Matriksinterferenser
Matrikspreferanser

**Beholdt**:
Massestrømmer (653#issuecomment-290336133)

**Må flyttes:**
Florence-prosjektet
Maskinen Frederic

**Comment by danmichaelo** [comment]
Opprettet termen `Tidlige datamaskiner` og flyttet dokumentene om `Maskinen Frederic` dit.
