### ISSUE TITLE
Transport socket layer

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1149]
Finnes det et emneord på norsk?

---
*REAL006422 (Transport socket layer) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006422), [Skosmos](http://data.ub.uio.no/realfagstermer/c006422), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Transport%20socket%20layer%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL006422)*

**Comment by danmichaelo** [comment]
Nei, dette er et egennavn. Men det skal jo være `Transport Layer Security`, så jeg endret det. Mulig `Transport Socket Layer` er en eldre betegnelse.
