### ISSUE TITLE
Abyssal bentos vs dyphavsbentos

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#115]
Per i dag har vi 'dyphavsbentos, se abyssal bentos'. Googling av den siste ga nøyaktig fire treff, alle frå 'realfagstermer'. Googling av den andre ga i alle fall eitt treff hos miljødirektoratet. Synest det er mest logisk å bytte om, og ta dyphavsbentos BF abyssal bentos, også fordi dette då blir parallelt med termar som 'dyphavssedimenter' etc. 

Vent litt, var det eg som foreslo 'abyssal bentos' kanskje? I så fall har eg ombestemt meg ;-)

**Comment by Hypsibius** [comment]
Og når vi er i gang, kva er i grunnen forskjellen mellom dyphav og dypvann? @mzyg

**Comment by mzyg** [comment]
Dypvann dannes i dyphavet :-)
I oseanografi er dypvann en term for en vannmasse. Vannmasser klassifiseres etter temperatur og salinitet og er en grov oppdeling av hvordan verdenshavene fordeler seg.
definisjon: https://metlex.met.no/wiki/Vannmasser. 
eksempel: http://www2.bjerknes.uib.no/pages.asp?kat=8&id=1979&lang=1
Men:
Det ser ut som biologer bruker det lit annerledes : http://nettskole.ndla.no/mesopelagisk

Dyphavet ble ikke brukt så mye i oseanografi, flest i sammenheng med dypvann (Dypvann dannes i dyphavet). Nederste delen av havet som er dyp (>18000) og mørk. Kanskje mer et relevant utrykk for biologer (habitat/område)?
http://en.wikipedia.org/wiki/Deep_sea

**Comment by danmichaelo** [comment]
sååå....? @Hypsibus

**Comment by Hypsibius** [comment]
Går for Dypvannsbentos BF Dyphavsbentos BF Abyssal bentos

**Comment by danmichaelo** [comment]
Fiksa! Djupvassbentos på nynorsk
