### ISSUE TITLE
Leksikalsk analyse

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1150]
Tror Leksikalsk analyse (informatikkbegrep) og Leksikografi er feilaktig slått sammen.

---
*REAL010532 (Leksikalsk analyse) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010532), [Skosmos](http://data.ub.uio.no/realfagstermer/c010532), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Leksikalsk%20analyse%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010532)*

**Comment by grosyn** [comment]
Tok bort 450 Leksikografi i autoritetsposten. La til (Informatikk) som kvalifikator. Har rydda.
