### ISSUE TITLE
Hardys

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1151]
Er dette et eget emne, eller refererer det egentlig til hardy-rom eller hardyklasser på noe vis? 

---
*REAL008156 (Hardys) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008156), [Skosmos](http://data.ub.uio.no/realfagstermer/c008156), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hardys%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008156)*

**Comment by danmichaelo** [comment]
Endret til `Hardys ulikhet` siden det sto i tittelen.
