### ISSUE TITLE
Elektronoverførere

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#1152]
Er dette et godt nok ord, mtp at det bare er benyttet på én katalogpost?
Det beskriver like mye som en strømledning, men det er mulig det er et faguttrykk jeg ikke er kjent med.

---
*REAL009026 (Elektronoverførere) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009026), [Skosmos](http://data.ub.uio.no/realfagstermer/c009026), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Elektronoverf%C3%B8rere%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009026)*

**Comment by danmichaelo** [comment]
Det var nok denne: https://en.wikipedia.org/wiki/Electron_transfer

Har endret til "Elektronoverføring" og slåt sammen med en annen term.
