### ISSUE TITLE
Bilturer:Norge

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1155]
Ønsker termen Bilturer og strengen Bilturer:Norge.

**Comment by danmichaelo** [comment]
Mye fritidsaktiviteter for tida :) Lagt til med nynorsk "Bilturar" og engelsk "Road trips"

**Comment by Hypsibius** [comment]
(Ivar) Awsome!

**Comment by BioHeidi** [comment]
Oi, kom visst til å slette Bilturer tror jeg. Hadde vi ikke bestemt oss for å redusere antall termer om spesifikke typer turer? Jfr padletur-diskusjonen?

**Comment by danmichaelo** [comment]
Og jeg kjørte visst almar etterpå. Det var disse to postene: [990711042084702201, 999920117776002201](https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/search?query=any,contains,990711042084702201,OR&query=any,contains,999920117776002201,AND&tab=default_tab&search_scope=default_scope&sortby=date&vid=UIO&lang=no_NO&mode=advanced&offset=0)

Tror vi bare bestemte oss for å prøve å holde dem litt i sjakk, ikke for å utrydde dem..?

**Comment by Violabibaluba** [comment]
Vi må jo sette emneord på bøker vi skal ha i samlingen selv om den handler om spesifikke typer turer? Dan Michael gjenoppretter strengen.
