### ISSUE TITLE
Nyterm Pilegrimsveier

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1156]
Lurer på om det er nokon på Realfagsbiblioteket som drøymer om ferie.

Her er uansett endå eit turrelatert forslag:

Pilegrimsveier

og strengen Pilegrimsveier:Norge

**Comment by Hypsibius** [comment]
I alle fall på realfagsbiblioteket i Bergen. Endå så nytt og flott det er. Skikkeleg dritver ute!

**Comment by danmichaelo** [comment]
Oppretta! 
EN Pilgrimage routes BF Pilgrims' ways
NN Pilegrimsvegar
