### ISSUE TITLE
Overforbruk av nivå?

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1158]
Kva tenkjer vi om postar som har denne typen emneord?

Eg tenkjer at REGISTERET skal hjelpe folk å finne fram oppover og nedobver i nivåa, og at ein ikkje skal behøve å legge inn 'heile systematikken' på kvar post. her har vi altså bløtdyr - snegler - bakgellesnegler - nakensnegler. Sånt genererer masse støy. Kanskje blei dette arva frå eksisterande frie emneord? Eg tenderar til å gå for den finaste oppløysinga og er skrekkeleg freista til å slette 'snegler' og 'bløtdyr' i slike tilfelle, men kva gjer dokke andre?

![image](https://user-images.githubusercontent.com/9350370/36255496-92950f46-124f-11e8-9e2d-fbebd7f21b6d.png)

**Comment by danmichaelo** [comment]
Vi sletter! Dette er arv fra fortiden. Dessverre en veldig omfattende arv.

**Comment by Hypsibius** [comment]
Då held eg fram som eg stevnar og slettar ned for fote!

**Comment by kyrretl** [comment]
PS.

Vi har et retningslinjedokument som er under arbeid, men er dessverre adgangsbegrenset.
Hvis dere har tilgang til UiO-ansattes sider, kan dere se det her:
https://www.uio.no/for-ansatte/enhetssider/ub/samlingsarbeid/ureal/kat-klass-emne/klassifisering/realfagstermer/

Når det blir ferdig @Violabibaluba @BioHeidi, kan vi legge en kopi ut på et åpent sted

**Comment by Violabibaluba** [comment]
Ja, det kan vi!
