### ISSUE TITLE
Ryddeforslag 15.02.18

### ISSUE THREAD

**Issue by HegeNenseth** [realfagstermer/realfagstermer#1159]
[Motorer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010171) blir brukt om maskiner i tillegg til verker om [Molykulære motorer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008538 ).
[Ormer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010824) blir brukt om båre mark og slanger.

Foreslår å slå sammen [Mimo](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010821 ) og [Multiple-input multiple-output](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010425)..
[Observasjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c012164) og [Observasjoner](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001223).
[Organiske løsemidler](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005500) og [Organiske løsninger](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010997).

**Comment by Hypsibius** [comment]
Hem. Vanskeleg å kvitte seg med dei fleirtydige ormane, utan vidare, ettersom termane finst som hevdnamn. Derimot kan våre innførslar vere entydige, og så får vi putte inn SO. Ormer er jo også både Annelida og Nematoda ++

**Comment by danmichaelo** [comment]
> [Motorer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010171) blir brukt om maskiner i tillegg til verker om [Molykulære motorer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008538 ).

Takk! Fiksa :ambulance:

> [Ormer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010824) blir brukt om båre mark og slanger.

Overlater til @BioHeidi 

> Foreslår å slå sammen [Mimo](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010821 ) og [Multiple-input multiple-output](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010425)..

Gjort!

> [Observasjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c012164) og [Observasjoner](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001223).

Hm, "Observasjon" ser ut til å handle mer om observasjon som metode og det vitenskapsfilosofiske grunnlaget. Mens "Observasjoner" ser ut til i all hovedsak å være astro-observasjoner. @superLine , skulle vi prøvd å spesifisert som observasjonastronomi e.l..?

> [Organiske løsemidler](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005500) og [Organiske løsninger](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010997).

Flyttet det ene dokumentet som hadde "Organiske løsninger" til "Organiske løsemidler" da det vitterlig sto "solvents" i tittelen..

**Comment by BioHeidi** [comment]
Så litt på trefflisten til "Ormer" og besluttet meg for å fjerne termen. Dokumentene hadde andre, mer dekkende termer på seg, med få unntak (som jeg fikset manuelt).

**Comment by grosyn** [comment]
Sidan denne diskusjonen har Observasjonsastronomi blitt oppretta, og eg lukkar med det heile saka.
