### ISSUE TITLE
dyrebestander

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#116]
Etter mi meining øverflødig, klarer oss lenge med 'bestander'. Meir relevant å spesifisere inn for enkeltgrupper, e.g. rovdyrbestanden, el artar, e.g. gaupebestanden (eintal om vi ser Noreg som forvaltningsområde), toskebestander (fleirtal, fordi vi snakkar om separate bestandar som i liten grad hybridiserar). Eller finst det eksempel på bruk der termen tilfører noko?

**Comment by bibliomari** [comment]
Toskebestand synes jeg var et knallforslag :) 

Ellers enig med deg i at Dyrebestander og Bestander ikke begge er nødvendige. Men blir ikke Bestander litt vel uspesifikt? Ser ut som mye av det vi har kan ryddes vekk, og bli f.eks. Laksebestander, Torskebestander ... Eller er det sammenhenger hvor biologene @Hypsibius og @BioHeidi mener vi trenger Bestander i tillegg til Bestandsberegninger, Bestandsmodellering osv. ?

**Comment by Hypsibius** [comment]
Jepp, ingen grunn til å raudliste toskebestanden om dagen ;-) 

Skjønt, det er 'fole toskje' å ikkje korrekturlese før ein sender inn..... 

Bestander (biologi) eller bestander (økologi) vil vere greie for teoretiske behandlingar av bestand som eining (uavhengig av art/gruppe), tenkjer eg, for bestandsberegninger/bestandsmodellering blir skrekkeleg spesifikke. Dermed kan det fort tvinge seg fram nye termar der dei ikkje er dekkjande... Men spent på kva @BioHeidi tenkjer om saka :-)

**Comment by Hypsibius** [comment]
*siste innlegg korrekturlest, men neppe feilfritt*

**Comment by Hypsibius** [comment]
Og når vi er i gang, kan vi også slette dyrepopulasjoner, foreslår bestander BF populasjoner EN populations

**Comment by BioHeidi** [comment]
Hiller det hele. Kjør ryddmagi.

**Comment by bibliomari** [comment]
Holder på...

**Comment by BioHeidi** [comment]
Marine populasjoner kan også slettes.Fiskepopulasjoner og Fiskebestander kan slås sammen.

**Comment by BioHeidi** [comment]
Det er fortsatt noe å rydde her med bestands- og populasjons-

**Comment by bibliomari** [comment]
Kan du være mer spesifikk, @BioHeidi , så skal jeg rydde.

**Comment by Hypsibius** [comment]
Har nettopp lokarert 'marine populasjoner' og erstattta med ingenting, men fikk bittelitt vondt i magen. Kan vere vi burde beholdt som 'marine bestander'?

**Comment by grosyn** [comment]
Har rydda med almar og sletta Bestander.
