### ISSUE TITLE
NOSIP

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#1161]
Dette emnet har flere søketreff som "Nitric oxide synthase-interacting protein". Bør vi ha det som en kommunikasjonsstandard?

---
*REAL000845 (NOSIP) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000845), [Skosmos](http://data.ub.uio.no/realfagstermer/c000845), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22NOSIP%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000845)*

**Comment by danmichaelo** [comment]
Njej, brukt på ett dokument, der NOSIP også er tittelen på dokumentet, så jeg synes ikke det. Sletter.
