### ISSUE TITLE
Solstråletabeller

### ISSUE THREAD

**Issue by JakobUiO** [realfagstermer/realfagstermer#1162]
Evt. slettes? Emneord fra 1970 som linkes på en bog i Oria: 
Solas stilling i Norge : tabeller over solas høyde og asimut for 204 steder i Norge, på Svalbard og Jan Mayen
Ordet findes meget begrænset på Google og kanske det ikke er et ord?
Det som evt menes med ordet er: Solar position tables

---
*REAL002332 (Solstråletabeller) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002332), [Skosmos](http://data.ub.uio.no/realfagstermer/c002332), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Solstr%C3%A5letabeller%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002332)*

**Comment by danmichaelo** [comment]
Sletter. @superLine , det var denne:

https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71463609780002201&vid=UIO&lang=no_NO
