### ISSUE TITLE
Uvær

### ISSUE THREAD

**Issue by JakobUiO** [realfagstermer/realfagstermer#1163]
Godt vær som er det modsatte af uvær er fair weather. Men det modsatte af fair weather finder jeg ikke. Mangler innspil her tak

---
*REAL002556 (Uvær) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002556), [Skosmos](http://data.ub.uio.no/realfagstermer/c002556), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Uv%C3%A6r%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002556)*

**Comment by danmichaelo** [comment]
Godt spørsmål. På norsk bruker vi jo storm veldig spesifikt om vind med en bestemt vindstyrke, men på engelsk lurer jeg på om [storm](https://www.merriam-webster.com/dictionary/storm) også brukes litt som vi bruker "uvær".

Men siden emneordet var brukt på to dokumenter som primært handlet om naturkatastrofer så slettet jeg det bare :)
