### ISSUE TITLE
Eksoskjelett

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1164]
BF Ektoskjelett BF Ytre skjelett NN Eksoskjelett EN Exoskeleton

Aktuelt for dette: https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71484310490002201&context=L&vid=UBB&search_scope=blended_scope&tab=alle_bibliotek&lang=no_NO

**Comment by danmichaelo** [comment]
Hadde vi ikke det altså? Lagt til 🚑

**Comment by danmichaelo** [comment]
ping @BioHeidi i tilfelle du vil sjekke

**Comment by Hypsibius** [comment]
Forstår ingenting. Huskar ikkje heller noko. Men det er på plass, så eg berre brukar det, eg :-)
