### ISSUE TITLE
Engelske termer

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#1166]
Finner noen engelske som sikkert burde ha norsk term isteden:
[Natural organic matter](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000695) -> Naturlig organisk materiale
[Dissolved Natural Organic Matter](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006601) -> Løst naturlig organisk materiale
[Total dissolved solids](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c001390) -> Totalt oppløste partikler

**Comment by danmichaelo** [comment]
Fiksa
