### ISSUE TITLE
Sletteforslag 28.02

### ISSUE THREAD

**Issue by HegeNenseth** [realfagstermer/realfagstermer#1168]
Her kommer ennå en liste med emner som kan vurderes:

[Digitale byer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010114)
[Nobelstiftelsen](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001335​)
[O-notasjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009246)
[Oksidasjonsredaksjoner](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c000634​)
[Oljeleting : Miljøeffekter](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c022092)
[Oljespredning](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010735)
[Oppgradering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c002993)
[Oppløsningslikevekter](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004564)
[Opposisjoneffekten](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c000581)
[Oppvekstområde](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031511)
[Optimal systemkontroll](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013194)
[Optisk form](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011392)
[Optisk partikkelanalyse](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001413)
[Optisk romforskning](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008513)
[Optisk stereoisomeri](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010654)
[Organisk petroleumsgeologi](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004461)
[Organisk spektroskopi](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005659)
[Organiske modifikatorer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011281)
[Organiske naturstoffer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009144)
[Organiske produkter](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013873)
[Organiske systemer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008614​)
[Oscillografisk polarografi](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c007908)
[Oscillometri](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c000700)
[Organiske forbindelser : Halogenider](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c020879)
[Oslonett](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c002396)
[Overflatemodifikasjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011911)
[Overgangssoner](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001518)
[Papirkvalitet](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011699)
[Parallell optimalisering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009377)
[Parallellimport](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004718)
[Paralysegifter](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008456)
[Paralytic shellfish poisoning](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011683)
[Partiell evaluering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c003613)
[Partikkelfysikk : Simuleringer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031329)
[Partikkelmekanikk](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013569)
[Parts-per-billion](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011600)
[Pasientovervåking](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004744​)
[Patogene stoffer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010225)
[Patulin](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c002103​)
[Pekerteori](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c007981)
[Pesticider : Økologiske effekter](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031896)
[Petroleumsøkonomi](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c012013)
[Petrologi : Sporstoffer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031845)
[Pi-ressurser](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010007)
[Planetrotasjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c012139​)
[Planteplankton : Primærproduksjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031739​)
[Planter : Metabolisme](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031547)
[Planter : Sekvenseringsmetoder](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031700)
[Platinakatalysatorer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010831)
[Platinakomplekser](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010470)
[Polarstrømmer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005215)
[Politiske aspekter](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c014004)
[Polyfarmasi](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009081)
[Polymerisasjonskontroll](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004648)
[Populasjonsmodeller](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004250)
[Population viability analysis](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009598)
[Portabilitet](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c000312​)
[Postmaskiner](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c007791)
[Praktisk kjemi](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004552)
[Praktiske hjelpemidler](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001506)
[Praktiske metoder](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005115)
[Predisponering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c012077)
[Prekursorer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001594​)
[Probabilistisk automatteori](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013205)
[Probabilistisk logikk](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031780)
[Profesjonskultur](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008361​)
[Prolegemidler](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c000715)
[Prosessering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008401​)
[Prosessorkommunikasjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c003612)
[Proteinseparasjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004756)
[Proteinteknikk](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c003162)
[Protokollmaskin](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005516)
[Protonledningsevne](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010859)
[Prøveinnføring](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c002674)
[Prøvekonstruksjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c012029)
[Prøvemetoder](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011135)
[Psykonevroendokrinologi](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c012115)
[Pulsed Field Gradient-Nuclear Magnetic Resonance](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009010​)
[Radielle basisfunksjoner](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031159)
[Programforståelse](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001960)
[Programkopiering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010169)
[Programmeringsuttrykk](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c006960)
[Programvareflytting](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001274)
[Reaksjonsprosesser](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c003615)
[Regneprogrammer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c002711​)
[Rendering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031486)
[Renframstilling](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013275)
[Rensevæsker](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013036)
[Reprofilering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013841​)
[Reversforkastninger](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031723)
[Rhodamin](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010565)
[Rietveldmetoden](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008632)

**Comment by danmichaelo** [comment]
**Slettet**:
[Digitale byer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010114)
[O-notasjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009246)
[Oksidasjonsreaksjoner](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c000634​)
[Oljespredning](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010735) (slått sammen med Oljeforurensning)
[Oppgradering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c002993)
[Oppløsningslikevekter](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004564) (erstatta med Kjemisk likevekt)
[Oppvekstområde](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031511)
[Optimal systemkontroll](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013194)
[Optisk form](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011392)
[Optisk partikkelanalyse](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001413) (slått sammen med Partikkelanalyse)
[Optisk romforskning](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008513)
[Optisk stereoisomeri](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010654)
[Organisk petroleumsgeologi](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004461)
[Organisk spektroskopi](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005659)
[Organiske forbindelser : Halogenider](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c020879)
[Organiske modifikatorer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011281)
[Organiske naturstoffer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009144)
[Organiske produkter](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013873) (brukes i streng)
[Organiske systemer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008614​)
[Oscillografisk polarografi](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c007908)
[Oscillometri](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c000700)
[Overflatemodifikasjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011911)
[Papirkvalitet](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011699)
[Parallell optimalisering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009377)
[Parallellimport](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004718)
[Partiell evaluering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c003613)
[Partikkelfysikk : Simuleringer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031329)
[Partikkelmekanikk](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013569)
[Parts-per-billion](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011600)
[Patogene stoffer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010225) (slått sammen med Patogener)
[Petrologi : Sporstoffer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031845)
[Pi-ressurser](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010007)
[Planetrotasjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c012139​)
[Planteplankton : Primærproduksjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031739​)
[Platinakomplekser](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010470)
[Polarstrømmer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005215)
[Postmaskiner](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c007791)
[Praktisk kjemi](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004552) (slått sammen med Anvendt kjemi)
[Praktiske hjelpemidler](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001506)
[Praktiske metoder](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005115)
[Prekursorer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001594​)
[Probabilistisk automatateori](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013205)
[Probabilistisk logikk](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031780)
[Profesjonskultur](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008361​)
[Programkopiering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010169)
[Programmeringsuttrykk](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c006960)
[Programvareflytting](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001274)
[Prosessering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008401​)
[Prosessorkommunikasjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c003612)
[Protokollmaskin](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c005516)
[Protonledningsevne](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010859)
[Prøveinnføring](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c002674)
[Prøvekonstruksjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c012029)
[Prøvemetoder](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011135)
[Psykonevroendokrinologi](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c012115)
[Pulsed Field Gradient-Nuclear Magnetic Resonance](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009010​)
[Reaksjonsprosesser](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c003615) (erstattet av Kjemiske reaktorer)
[Regneprogrammer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c002711​)
[Rensevæsker](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013036)

**Beholdt**:
[Oljeleting : Miljøeffekter](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c022092)
[Opposisjonseffekten](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c000581)
[Petroleumsøkonomi](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c012013)
[Politiske aspekter](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c014004) (brukt i streng)
[Rendering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031486) (i bruk av ubb? #208)
[Reversforkastninger](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031723) (i bruk av ubb? #555)


**Må flyttes**:
[Nobelstiftelsen](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001335​)
[Oslonett](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c002396)

**Ikke behandlet enda**:
[Overgangssoner](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001518)
[Paralysegifter](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008456)
[Paralytic shellfish poisoning](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c011683)
[Pasientovervåking](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004744​)
[Patulin](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c002103​)
[Pekerteori](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c007981)
[Pesticider : Økologiske effekter](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031896)
[Planter : Metabolisme](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031547)
[Planter : Sekvenseringsmetoder](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031700)
[Platinakatalysatorer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010831) (må sjekke mot de andre `*katalysatorer`-termene. Mulig det holder med `Metallkatalysatorer` + metallet)
[Polyfarmasi](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009081)
[Polymerisasjonskontroll](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004648)
[Populasjonsmodeller](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004250)
[Population viability analysis](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009598)
[Portabilitet](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c000312​)
[Predisponering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c012077)
[Prolegemidler](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c000715)
[Proteinseparasjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004756)
[Proteinteknikk](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c003162)
[Radielle basisfunksjoner](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031159)
[Programforståelse](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001960)
[Renframstilling](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013275)
[Reprofilering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013841​) (brukt i streng, må evt. finne erstatningsterm)
[Rhodamin](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010565)
[Rietveldmetoden](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008632)

**Comment by BioHeidi** [comment]
Planteplankton : Primærproduksjon hadde vært en fin term å ha på en del dokumenter. Tror jeg hadde en spesifikk doktoravhandling i tankene?

Planter : Metabolisme er også en fin streng, finner en del bøker som kunne fått dette, men spørs om vinningen er så stor at vi gidder?

Planter : Sekvenseringsmetoder har jeg to spesifikke bøker i tankene for.

Populasjonsmodeller kan erstattes av Økologi : Matematiske modeller

**Comment by Hypsibius** [comment]
Vil ikkje den siste bli veldig vid, @BioHeidi ?

**Comment by grosyn** [comment]
Her har det tydelegvis blitt gjort ein jobb sidan mars 2018. Fleire av termane har blitt sletta, og dei som står att er:
[Paralysegifter](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c008456)
[Pasientovervåking](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004744%E2%80%8B)
[Patulin](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c002103%E2%80%8B)
[Pekerteori](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c007981)
[Polyfarmasi](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c009081)
[Portabilitet](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c000312%E2%80%8B)
[Prolegemidler](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c000715)
[Proteinseparasjon](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c004756)
[Proteinteknikk](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c003162)
[Programforståelse](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c001960)
[Reprofilering](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c013841%E2%80%8B) 

Eg lukkar saka.
