### ISSUE TITLE
Editering

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#117]
Her er eg litt usikker på bruken. Søket (i ask) gir fleire treff på redigering i film o.l., samt to treff som omhandlar DNA/RNA . Desse siste to treffa kjem truleg med fordi vi også har termen RND-editering. Dreier dette seg om gensløyd? @BioHeidi @mittinatten 

Vi har også termen redigering inne alt. Eg vil foreslå redigering BF editering, eller krasjar det med nokon former for bruk?

**Comment by mittinatten** [comment]
"Gene editing" er en teknisk term som jeg hørt genetikk-folk snakke om innimellom, men aldri visst akkurat hva det er. Har gjort litt research nå :)

Til å begynne med har Wikipeida litt forvirrende info: "Gene editing" peker til "Gene therapy". Vi har også "Genome editing" som er navn på en metode for å syntetisk endre DNA. 

Fra Springers _Encyclopedia of Genetics, Genomics, Proteomics and Informatics_

**Gene Editing**: Parts of natural genes are replaced or completed by synthetic DNA chains or a natural repair process eliminates gaps or mismatches in the DNA (called also proofreading).

**Editing**: Some DNA polymerases, aminoacyl tRNA synthetases, aptamers also have nuclease functions and eliminate replicational mistakes or prevent translational errors.

**RNA Editing**: A means of posttranscriptional or cotranscriptional altering of the RNA transcript
(mRNA, tRNA, rRNA, 7 SLRNA). It is a very common process in the mitochondria of Trypanosomes. A separately transcribed 40–80-base “guide RNA” with homology to the 5′-end of the RNA to be modified pairs with the target. Then, uracil residues from the 3′-end tract of the guide are transferred into the target sequences. [... lang artikkel]

Så konklusjonen er at det neppe er tilfeldig at "editering" er blitt brukt i tekster som omhandler genetikk.

**Comment by Hypsibius** [comment]
Og dermed vil gjerne heller ikkje alle tilfella falle inn under RNA-editering. Kva med å spesifiere med 'editering (genetikk)' for dei aktuelle tilfella og ut over det 'editering, se redigering'?

**Comment by mittinatten** [comment]
Eller `Redigering SO Editering (genetikk)` ?

**Comment by Hypsibius** [comment]
Jepp

**Comment by BioHeidi** [comment]
Stiller meg bak det siste forslaget! Vi bør vel også ha en SO på Editering (genetikk), SO RNA-editering.

**Comment by bibliomari** [comment]
Gjort
