### ISSUE TITLE
Toksikanter

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1170]
Er det nødvendig å ha to ulike emner for dette eller kan begge være under "Toksiner"?

---
*REAL012777 (Toksikanter) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c012777), [Skosmos](http://data.ub.uio.no/realfagstermer/c012777), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Toksikanter%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL012777)*

**Comment by BioHeidi** [comment]
Nei det er forskjellige ting - jeg skal se om jeg kan få lagt på definisjoner.

**Comment by BioHeidi** [comment]
Gjort
