### ISSUE TITLE
Nytermforslag: Hørselshjelpemidler

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1171]
Skulle hatt Hørselshjelpemidler som term.

(Gjeld dokid k16047315.)

**Comment by danmichaelo** [comment]
Oppretta! Tror kanskje jeg har en oppgave til den kan brukes på :)

**Comment by danmichaelo** [comment]
Det blir riktig med "Høyrselshjelpemiddel" (fl.tall) på nynorsk? Legg gjerne ved nynorsk-forslag også når du melder nye termer.

**Comment by grosyn** [comment]
Ja, det meiner eg. Ein kan òg seia "Høyrslehjelpemiddel", men eg likar "Høyrselshjelpemiddel" best.

**Comment by danmichaelo** [comment]
Takk, legger inn Høyrslehjelpemiddel som alternativ term!
