### ISSUE TITLE
Byggemetoder

### ISSUE THREAD

**Issue by maritsan** [realfagstermer/realfagstermer#1172]
Kanskje ikke et godt emneord på denne boka? Slette?

---
*REAL006919 (Byggemetoder) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006919), [Skosmos](http://data.ub.uio.no/realfagstermer/c006919), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Byggemetoder%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL006919)*

**Comment by BioHeidi** [comment]
Ja, slette.

**Comment by danmichaelo** [comment]
Slettet!
