### ISSUE TITLE
Byggesett

### ISSUE THREAD

**Issue by maritsan** [realfagstermer/realfagstermer#1173]
Skulle vært Molekylbyggesett, og som form.

---
*REAL003280 (Byggesett) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003280), [Skosmos](http://data.ub.uio.no/realfagstermer/c003280), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Byggesett%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL003280)*

**Comment by danmichaelo** [comment]
Slettet! Endret den ene posten
