### ISSUE TITLE
Celledannelse

### ISSUE THREAD

**Issue by maritsan** [realfagstermer/realfagstermer#1174]
Brukt på ett dokument fra 1880. Kanskje ikke et godt emneord?

---
*REAL008304 (Celledannelse) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008304), [Skosmos](http://data.ub.uio.no/realfagstermer/c008304), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Celledannelse%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008304)*

**Comment by BioHeidi** [comment]
Nei, den sletter vi.

**Comment by danmichaelo** [comment]
I gamle dager da cellene hadde bedre dannelse...

Slettet!
