### ISSUE TITLE
Bruer

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1175]
Har dere en politikk på å bruke "radikalt bokmål"? Slik denne termen står nå, får man ikke treff på "Broer", det er kanskje litt uheldig?

---
*REAL013598 (Bruer) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013598), [Skosmos](http://data.ub.uio.no/realfagstermer/c013598), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Bruer%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL013598)*

**Comment by danmichaelo** [comment]
La inn broer som BF. Takk for tips!
