### ISSUE TITLE
Kyotoavtalen

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1176]
Er dette egentlig en realfagsterm? Heller et 130 / 630-emne?

---
*REAL011299 (Kyotoavtalen) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011299), [Skosmos](http://data.ub.uio.no/realfagstermer/c011299), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kyotoavtalen%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL011299)*

**Comment by danmichaelo** [comment]
Flyttet til #1107
