### ISSUE TITLE
Obstetrikk

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1177]
Hei, humord har termen "Fødselshjelp" her. Noe å legge som henvisning?

---
*REAL013958 (Obstetrikk) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013958), [Skosmos](http://data.ub.uio.no/realfagstermer/c013958), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Obstetrikk%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL013958)*

**Comment by danmichaelo** [comment]
Gjort! Takk for tips
