### ISSUE TITLE
Fagbevegelsen

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1179]
Henvisningen er morsom. Men.... Fagbevegelsen! Fagbevegelsen! Fagbevegelsen!  ?? :-)

---
*REAL006978 (Fagbevegelsen) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006978), [Skosmos](http://data.ub.uio.no/realfagstermer/c006978), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Fagbevegelsen%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL006978)*

**Comment by danmichaelo** [comment]
Har ikke hjerte til å fjerne den :D
