### ISSUE TITLE
Ekso/astro/xeno-biologi eller bioastronomi?

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#118]
Hjelp! Vi har alle desse innførslane separat! Wikipedia og SNL brukar Astrobiologi som hovedinnførsel. Kan vi samle oss om dette, BF alle dei andre?

**Comment by BioHeidi** [comment]
Nesten.
Det finnes såvidt jeg har fått med meg et nytt og fremadstormende fagfelt innenfor syntetisk biologi som nå bruker termen xenobiologi. Så hvis vi kan plukke ut de postene hvor xenobiologi er brukt som synonym til astrobiologi kan vi beholde xenobiologi med definisjon (se lenke under), og ha hovedterm astrobiologi BF eksobiologi, exobiologi, bioastronomi.

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2909387/

**Comment by Hypsibius** [comment]
Jojo, men det får halde, det :-)

**Comment by danmichaelo** [comment]
Wikipdia har gjort det samme, og har en fin forklaring: https://en.wikipedia.org/wiki/Xenobiology#Difference_between_xeno-.2C_exo-.2C_and_astro-biology

**Comment by danmichaelo** [comment]
Skal vi begynne med å slå de sammen, og så kan du grave ut xenobiologi-bøkene etterpå @BioHeidi ?

**Comment by danmichaelo** [comment]
Og så hadde vi visst `Rombiologi` også :)

**Comment by Hypsibius** [comment]
Skvis det med. Så får @BioHeidi behalde xenobliologien sin :-)

**Comment by BioHeidi** [comment]
Viktig tema å få orden på nå med Trappist-1!
Slå ivei.

**Comment by danmichaelo** [comment]
Har slått. Men skill gjerne ut Xenobiologi ved høve!
