### ISSUE TITLE
Kreatinin

### ISSUE THREAD

**Issue by maritsan** [realfagstermer/realfagstermer#1182]
Er kreatinin og creatine det samme?... 

Kreatin og kreatinin, fysiologisk viktige forbindelser som finnes i mange organismer, særlig i forskjellig animalsk vev. Kreatin, C4H9O2N3, finnes f.eks. i muskler, mens kreatinin, C4H7ON3, er et anhydrid av kreatin som utskilles i urinen hos pattedyr.

---
*REAL012052 (Kreatinin) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c012052), [Skosmos](http://data.ub.uio.no/realfagstermer/c012052), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kreatinin%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL012052)*

**Comment by BioHeidi** [comment]
Ja!

**Comment by danmichaelo** [comment]
Skulle vi kanskje hatt `Kreatin` som foretrukket term, med `Kreatinin` som henvisningsterm? Nå har vi bare `Kreatinin`.

**Comment by kyrretl** [comment]
Neeeeeii!

Creatinine og Kreatinin er det samme
Creatine og Kreatin er det samme

Kreatinin og Kreatin er IKKE det samme. 

Kreatin er en nitrogenholdig organisk syre som finnes naturlig i virveldyr og bidrar til å levere energi til alle celler i kroppen, først og fremst muskler ved å øke dannelsen av adenosintrifosfat (ATP).

Kreatinin er et nedbrytningsprodukt fra kreatinfosfat i muskel, og produseres vanligvis med en konstant hastighet i kroppen. Brukes til å sjekke nyresvikt.

jmf engelsk wikipedia: https://en.wikipedia.org/wiki/Creatinine

"Not to be confused with Creatine" og vise versa for artikkelen med Creatinine

Ser at det er feilkatalogisert med Kreatinin for Creatine, det skal være Kreatin. I tillegg er Kreatinin kinase også feil, det skal være Kreatin Kinase for den éne posten vi har. Nynorsk har samme feil

Kyrre

**Comment by danmichaelo** [comment]
Da har vi endret "Kreatinin" til "Kreatin", og "Kreatinin kinase" til "Kreatin kinase".

**Comment by danmichaelo** [comment]
Ferdig?

**Comment by BioHeidi** [comment]
Leste visst litt fort... bra du passer på! Betyr det at alle postene vi hadde på Kreatinin handlet om Kreatin? Ellers blir jo ikke dette riktig.

**Comment by kyrretl** [comment]
Ja, men "alle postene" var bare én post ;-)
Vi rettet det opp, men det blir ikke synlig før i natt
