### ISSUE TITLE
Ungdom og Ungdommer

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1183]
Slå sammen, med Ungdom som foretrukket term? Det virker som vi har brukt de overlappende, om "unge folk".

---
*REAL001986 (Ungdommer) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c001986), [Skosmos](http://data.ub.uio.no/realfagstermer/c001986), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Ungdommer%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL001986)*

**Comment by grosyn** [comment]
Slo saman Ungdommer med Ungdom og rydda i katalogen.
