### ISSUE TITLE
Melkeproduksjon

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1186]
Ut ifra katalogpostene oversatte jeg til `Lactation`, bare å fikse hvis den "industrielle" siden skal være med også!

---
*REAL010875 (Melkeproduksjon) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010875), [Skosmos](http://data.ub.uio.no/realfagstermer/c010875), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Melkeproduksjon%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010875)*

**Comment by anjamaa** [comment]
Burde vi forresten også hatt `Laktasjon` på norsk?

**Comment by anjamaa** [comment]
Nå ble jeg usikker på hvordan denne henger sammen med [denne](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006777). @BioHeidi, @Hypsibius, har dere innspill?

**Comment by kyrretl** [comment]
Melkesekresjon og Melkeproduksjon har bare to poster hver som ser ut til å handle om det samme og dekkes av Laktasjon. Ser ikke noe som tyder på industriell produksjon.
Store Norske har Laktasjon, Wikipedia har ikke det, men det er nok bare en mangel siden de har "Mannlig laktasjon"...

Jeg foreslår at Laktasjon blir foretrukket term og Melkesekresjon og Melkeproduksjon er synonymer.

Kyrre

**Comment by Hypsibius** [comment]
"Okejda", sa hun motvillig. Hun hadde nok foretrukket "melkesekresjon" :-)

**Comment by kyrretl** [comment]
Var egentlig enig at det er bedre med Melkesekresjon, men så kom jeg til å tenke på at melke er sæd hos fisk og kan muligens lage litt forvirring. Laktasjon bør ikke kunne forvirres med noe annet :-)

DM fiksa det nå
