### ISSUE TITLE
Messierobjekter

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1187]
Skal vi legge til `Messierkatalogen` på norsk?

---
*REAL006121 (Messierobjekter) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006121), [Skosmos](http://data.ub.uio.no/realfagstermer/c006121), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Messierobjekter%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL006121)*

**Comment by danmichaelo** [comment]
Kanskje litt sammenblanding av verk og emne, men jeg synes det må være lov her. Gjort!
