### ISSUE TITLE
Øvre pasvik

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1188]
Rette til `Øvre Pasvik`? Eller slette?

---
*REAL031358 (Øvre pasvik) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c031358), [Skosmos](http://data.ub.uio.no/realfagstermer/c031358), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22%C3%98vre%20pasvik%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL031358)*

**Comment by danmichaelo** [comment]
Vi har en del nasjonalparker, så jeg endret den til `Øvre Pasvik nasjonalpark` i første omgang ihvertfall.
