### ISSUE TITLE
Vrml

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1189]
Rette til `VRML` på norsk?

---
*REAL006431 (Vrml) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006431), [Skosmos](http://data.ub.uio.no/realfagstermer/c006431), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Vrml%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL006431)*

**Comment by danmichaelo** [comment]
:+1:
