### ISSUE TITLE
Bayesiansk programmering

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#119]
Foreslår

     Bayesiansk programmering
     EN Bayesian programming

Belegg: http://bibsys-primo.hosted.exlibrisgroup.com/UBB:BIBSYS_ILS141581158

Wikipedia: http://en.wikipedia.org/wiki/Bayesian_programming

**Comment by Hypsibius** [comment]
Tenker at om mannen heiter Bayes, så ville den logiske forma vere bayesisk og ikkje bayesiansk, men ser at google gir treff for begge deler. Kva står i norske lærebøker?

**Comment by mittinatten** [comment]
Vi har allerede 6 emneord på Bayesiansk, 0 på Bayesisk. På UiBs hjemmesider er Bayesiansk brukt 3 ganger, og Bayesisk 1 gang. UiO har 165 treffer for Bayesiansk (3 kurser med Bayesiansk i tittelen), og 22 treff på Bayesisk. Så jeg vil si Bayesiansk dominerer.

For øvrig verifierer det min fordom at UiOs nettsider er mer innholdsrike enn UiB sine :)

**Comment by mittinatten** [comment]
Kan jo gjerne slenge inn `BF Bayesisk ...` på alle termene.

**Comment by Hypsibius** [comment]
Det løser jo problemet med gjenfinning. Det basale problemet gjenstår, at ein term først får -an som tillegg på engelsk og derpå -sk på norsk, når den sidan blir omsett til norsk (eller skandinavisk), når -an og -sk ellers har lik funskjon i språka. Det SER grisete ut, men vi kan dessverre ikkje vere normative, berre deskriptive ;-) *svelger kamel*

**Comment by mittinatten** [comment]
Bayesiansk blir brukt i ihvertfall en norsk lærebok http://www.nb.no/nbsok/nb/19e60b806545408361ba300aa69cf3af.nbdigital?lang=no#89

Det omhandles nok grundig ført på en nivå hvor en oftest har engelske lærebøker.

Enig i at Bayesisk på mange måter er bedre.. Ser at både norske og svenske wikipedia har blandet bruk. Kanskje kan si at det er Bayesisk på nynorsk? ;)

**Comment by Hypsibius** [comment]
Diil!

**Comment by danmichaelo** [comment]
Jeg la den inn jeg. Håper jeg klarte å skrive bayesiansk riktig :P 
Jeg er forsåvidt også "vant med" 'bayesiansk', men la inn 'bayesisk' som alternativ form.

**Comment by mittinatten** [comment]
Flott, da har jeg lagt den inn. Noen som vet hva som kommer å skje med emneord på e-bøker i Alma? Overføres de?

**Comment by danmichaelo** [comment]
Merkelig nok hadde ikke Bibsys noen plan for å overføre emneord til poster som blir re-importert. Planen deres var å ikke overskrive poster som hadde fått kat-status, men det hjelper ikke oss siden vi ikke tar kat når vi indekserer. Å hente ut en liste over alle poster som inneholder "$2 no-ubo-mn" var visst "for vanskelig" (veldig merkelig), så i januar eksperimenterte jeg med å trekke ut en sånn liste selv fra en katalogdump fra OAI-PMH. Det funka ganske greit bortsett fra at OAI-PMH-tjeneren er veldig treig og hadde lange perioder hvor den ikke ville svare i det hele tatt :) Jeg vet ikke akkurat hvor saken står nå, men kan høre med Marit
