### ISSUE TITLE
Very Large Telescope Interferometer (VLTI)

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1190]
Slå sammen med `Very Large Telescope Interferometer`?

---
*REAL002609 (Very Large Telescope Interferometer (VLTI)) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002609), [Skosmos](http://data.ub.uio.no/realfagstermer/c002609), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Very%20Large%20Telescope%20Interferometer%20(VLTI)%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002609)*

**Comment by danmichaelo** [comment]
Oi, rart ingen har sett den før! Fiksa. Også lagt til i #255
