### ISSUE TITLE
Lineære vektorrom

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1191]
Wikipedia sier at "vector space" og "linear space" er det samme? Bør denne da slås sammen med `Vektorrom`?

---
*REAL009633 (Lineære vektorrom) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009633), [Skosmos](http://data.ub.uio.no/realfagstermer/c009633), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Line%C3%A6re%20vektorrom%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009633)*

**Comment by danmichaelo** [comment]
Ooh, godt funn! Hadde ikke hørt termen lineære rom før, men ser ut som det er en historisk betegnelse på det samme, ja: https://math.stackexchange.com/questions/248532/why-are-vector-spaces-sometimes-called-linear-spaces

**Comment by danmichaelo** [comment]
Slått sammen
