### ISSUE TITLE
Vektorrom

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1192]
Legge til `Lineære rom` på norsk? Se også #1191.

---
*REAL007387 (Vektorrom) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007387), [Skosmos](http://data.ub.uio.no/realfagstermer/c007387), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Vektorrom%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL007387)*

**Comment by danmichaelo** [comment]
Slått sammen
