### ISSUE TITLE
Svarte (folkegrupper)

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1195]
Er dette helt politisk korrekt?

---
*REAL003932 (Svarte (folkegrupper)) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003932), [Skosmos](http://data.ub.uio.no/realfagstermer/c003932), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Svarte%20(folkegrupper)%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL003932)*

**Comment by danmichaelo** [comment]
Nei, se #892
