### ISSUE TITLE
Morgan-Keenan klassifikasjon

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1196]
Endre til tankestrek og så bindestrek?

---
*REAL009867 (Morgan-Keenan klassifikasjon) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009867), [Skosmos](http://data.ub.uio.no/realfagstermer/c009867), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Morgan-Keenan%20klassifikasjon%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009867)*

**Comment by anjamaa** [comment]
Jeg fant forresten en del flere engelske termer, bør noen flere legges til på norsk?

**Comment by danmichaelo** [comment]
Gjerne det! Fikset tanke-binde-strek

**Comment by anjamaa** [comment]
Tror du eller @superLine må legge til, har såvidt jeg vet ikke mulighet til å legge inn på norsk?

**Comment by anjamaa** [comment]
Bumper denne for flere termer på norsk :)

**Comment by danmichaelo** [comment]
Haha, takk for påminnelse, jeg så nok bare det øverste :blush: Nå er alt lagt til på BM og NN
