### ISSUE TITLE
Sjøskorpioner

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1197]
Legge til "Eurypterider" på norsk?

---
*REAL031352 (Sjøskorpioner) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c031352), [Skosmos](http://data.ub.uio.no/realfagstermer/c031352), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Sj%C3%B8skorpioner%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL031352)*

**Comment by anjamaa** [comment]
På [Wikipedia](https://en.wikipedia.org/wiki/Eurypterid) står det "Eurypterids, often informally called sea scorpions". Bør vi ha `Eurypterids` eller `Sea scorpions` som hovedterm?

**Comment by BioHeidi** [comment]
Stemmer for Sea scorpions som foretrukken på engelsk. Eurypterider og Eurypterids som BF, og Eurypterida som latinsk term. NN for Eurypterider?

**Comment by danmichaelo** [comment]
Fiksa!

**Comment by Hypsibius** [comment]
Litt uviss på nynorsken, faktisk! Om det er "ein eyrupteid", vil eg tenkje det skal vere "fleire eurypteridar" (ar-ending)

**Comment by danmichaelo** [comment]
Prøver det da
