### ISSUE TITLE
Veterinærfarmasi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1198]
Jeg prøver å koble til [denne](https://en.wikipedia.org/wiki/Veterinary_pharmacy), men det ser ikke ut som det finnes en Wikidata-side for den? Under "Tools" på venstre side mangler "Wikidata item".

---
*REAL000435 (Veterinærfarmasi) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000435), [Skosmos](http://data.ub.uio.no/realfagstermer/c000435), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Veterin%C3%A6rfarmasi%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000435)*

**Comment by danmichaelo** [comment]
Fiksa, takk for tips! 🤓
