### ISSUE TITLE
Selektivitet

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1199]
Denne har litt diverse treff i emnesøket, trenger den en rydding?

---
*REAL000586 (Selektivitet) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000586), [Skosmos](http://data.ub.uio.no/realfagstermer/c000586), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Selektivitet%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000586)*

**Comment by danmichaelo** [comment]
Med bredt søk? Med snevert søk finner jeg bare ett dokument.

**Comment by anjamaa** [comment]
Ja, i bredt søk! Så da er det kanskje ikke så dumt likevel?

Selektivitet er også et begrep innenfor organisk kjemi, burde egentlig øverste treff fra bredt søk være med i snevert søk ("Directed selectivity in organic synthesis : a practical guide")? Det er en annen betydning av "selektivitet" enn treffet i snevert søk, da, så det er kanskje derfor den ikke er med?

**Comment by danmichaelo** [comment]
Bredt søk gir flere treff på bekostning av presisjon. Treffene der har vi ikke direkte kontroll, men vi kunne endret termen så den ikke overlappet med andre. Men iom. at vi bare har brukt et såpass bredt begrep på kun ett dokument (masteroppgave) er jeg litt fristet til å bare slette det.

**Comment by anjamaa** [comment]
Ser i oria at vi har noen flere poster som kunne gått innunder "selektivitet" (i organisk kjemi), men jeg er enig i at det like så godt kan slettes :)

**Comment by danmichaelo** [comment]
Slettet!
