### ISSUE TITLE
Sekvenser

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1200]
Ser ut som denne trenger litt rydding :)

---
*REAL000814 (Sekvenser) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000814), [Skosmos](http://data.ub.uio.no/realfagstermer/c000814), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Sekvenser%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000814)*

**Comment by danmichaelo** [comment]
Fikset de to dokumentene som ikke hadde noe med bio å gjøre (matematikerne bruker "følger" om "sequences").

Ser forresten ut som vi mangler `Proteinsekvensering`. Burde vi hatt det?

**Comment by Hypsibius** [comment]
Om vi har dokument til an, så?

**Comment by BioHeidi** [comment]
Opprettet og lagt på to bøker. La også Sekvenser og Sekvensanalyse til Sekvenseringsmetoder. Men lurer på om vi burde ha foretrukken term Gensekvensering, for å gjøre skillet mellom den og Protinsekvensering tydeligere? Hva tror dere?

**Comment by danmichaelo** [comment]
Høres i hvert fall veldig lurt ut for en ikke-biolog. Endret.
