### ISSUE TITLE
Modellering

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1201]
Kan noen legge til `Modelling` på engelsk? :)

---
*REAL004126 (Modellering) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004126), [Skosmos](http://data.ub.uio.no/realfagstermer/c004126), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Modellering%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL004126)*

**Comment by danmichaelo** [comment]
Gjort! Troor alle modelleringstermene våre har begge former nå.
