### ISSUE TITLE
Foldinger og Folder

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1202]
Er det samme ting? Eller ei? 

---
*REAL007431 (Foldinger) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007431), [Skosmos](http://data.ub.uio.no/realfagstermer/c007431), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Foldinger%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL007431)*

**Comment by Hypsibius** [comment]
jf denne: https://github.com/realfagstermer/realfagstermer/issues/155

**Comment by Hypsibius** [comment]
og denne: https://github.com/realfagstermer/realfagstermer/issues/698

**Comment by danmichaelo** [comment]
Oi, dårlig research fra min side!
