### ISSUE TITLE
Råstoffer og Råvarer

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1203]
Er det verdt bryet å prøve å rydde og definere? Fristet til å bare slette dem, ser ikke helt at de kan fungere som spesielt nyttige kategorier i realfagstermer.

---
*REAL010919 (Råstoffer) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010919), [Skosmos](http://data.ub.uio.no/realfagstermer/c010919), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22R%C3%A5stoffer%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010919)*

**Comment by BioHeidi** [comment]
Stemmer for å slette. Om noen dokumenter blir uten term (så kjapt over, de fleste hadde massevis) kan Naturressurser kanskje dekke.

**Comment by danmichaelo** [comment]
Slettet
