### ISSUE TITLE
Romlig fordeling

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1204]
Er dette en nyttig søketerm? Er det noen som kommer til å på å søke etter det?

---
*REAL007909 (Romlig fordeling) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007909), [Skosmos](http://data.ub.uio.no/realfagstermer/c007909), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Romlig%20fordeling%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL007909)*

**Comment by danmichaelo** [comment]
Eller tja, den kan kobles til https://en.wikipedia.org/wiki/Spatial_distribution . Den hadde kanskje fungert bedre som ledd i streng, men kanskje ikke krise å bare beholde den som den er heller?

La inn SO til Romlig statistikk

**Comment by BioHeidi** [comment]
Spatial distribution og Spatial ecology (Romlig økologi står som BF) er termer som er mye brukt, så ja, jeg vil gjerne beholde. Kunne kanskje ha vært forbeholdt streng, men fungerer også på egen hånd.
