### ISSUE TITLE
Plastisitet og Fenotypisk plastisitet

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#1206]
Her trengs katalogrydding og kanskje definisjoner. Kjapp jobb, ikke lange trefflister.
Vurdere også å slå sammen Plasisitet og Plastisitetsteori?

**Comment by kyrretl** [comment]
Det var ikke så mye, så jeg og DM tok det. Det var tre kategorier, mekanikk/materialvitenskap, medisin og biologi,

Så nå har vi 

For biologi: Fenotypisk plastisitet
For medisin: Nevroplastisitet
For mekanikk/materialvitenskap: Plastisitet (Mekanikk) (her la vi også til BF-termer: Plastisitet (Fysikk) og Plastisitet (Materialvitenskap)).

Vi slettet Plastiske bearbeidingsprosesser og absorberte Plastisitetsteori inn i Plastisitet (Mekanikk).

**Comment by danmichaelo** [comment]
Gjort: `almar --diffs interactive 'Plastisitet' 'Plastisitet (mekanikk)' 'Nevroplastisitet' 'Fenotypisk plastisitet'`
