### ISSUE TITLE
Kolonnepakking

### ISSUE THREAD

**Issue by maritsan** [realfagstermer/realfagstermer#1207]
Hei!
Kanskje ikke riktig her å henvise til kolonnekromotografi på wikipedia. 
Men dere kan jo rette det.
Marit

---
*REAL011717 (Kolonnepakking) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011717), [Skosmos](http://data.ub.uio.no/realfagstermer/c011717), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kolonnepakking%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL011717)*

**Comment by danmichaelo** [comment]
Det interessante er at det avslører at vi mangler begrepet «Kolonnekromatografi»! Kan vi ikke bare endre Kolonnepakking til Kolonnekromatografi? Så har vi et litt mer anvendelig begrep som det er større sjanse for at kan brukes på flere dokumenter.
