### ISSUE TITLE
Lambda

### ISSUE THREAD

**Issue by maritsan** [realfagstermer/realfagstermer#1208]
Hei!
Jeg lurer på om det her er snakk om bakteriofag lambda, https://en.wikipedia.org/wiki/Lambda_phage ?

---
*REAL007406 (Lambda) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007406), [Skosmos](http://data.ub.uio.no/realfagstermer/c007406), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Lambda%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL007406)*

**Comment by BioHeidi** [comment]
Ja det er det nok. Skal vi slå sammen med Bakteriofager?

**Comment by kyrretl** [comment]
De to (2) dokumentene som har Lambda som emneord har også Bakteriofager som emneord. Ettersom det er forvirrende fordi Lambda er brukt i funksjoner og konstanter osv. i annen realfag og samtidig er veldig snevert innen "bakteriefagologi" så foreslår jeg at vi bare sletter det. 

De to dokumentene har jo allerede Bakteriofager og det er 28 bøker totalt i samlingen vår som har Bakteriofager som emneord, ikke så mye å bla gjennom dersom man er på jakt etter Lambda eller Mu-type bakteriofager.

**Comment by danmichaelo** [comment]
Slettet!
