### ISSUE TITLE
Altmetri / Altmetrics

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#1209]
Nytermforslag fra Bente.
Fant en defininsjon her: https://nb.glosbe.com/nb/en/altmetri
"alternative måter å måle forskningsproduksjon og -gjennomslag på"

Ser det ok ut? Hva heter det på nynorsk tro? :)

**Comment by danmichaelo** [comment]
Tenkte den ikke trengte diskusjon, men egentlig veldig fint å samle alle forslag her!

Definisjon er også fint å få lagt på!

**Comment by Violabibaluba** [comment]
Lagt på definisjon
