### ISSUE TITLE
Embeddings

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#121]
Her må vi vel ha ein norsk term?

**Comment by knuthe** [comment]
Den er brukt én gang på en matematikkbok og stammer egentlig fra 691-feltet og der står det "... lagrangian embeddings ...". Jeg har ikke noen oversettelse av det, kanskje andre har<?

**Comment by mittinatten** [comment]
I følge en svensk-engelske matematikkordbok er den svenske termen for "embed" "inbädda" (https://www.acc.umu.se/~olletg/donner/dox/matordbok.pdf). Det skulle bli `innbedding` på norsk. Kan ikke se at den har blitt brukt, "lagrange-innbedding" gir for eksempel ingen relevante treff på google. Kanskje den termen bare kan slettes?

**Comment by Hypsibius** [comment]
Innfelle eller innbygge er kanskje alternativ på norsk, avh av samanheng?

**Comment by mittinatten** [comment]
Det en mener med embedding er at en instans av en matematisk struktur er "del av" (contained in) en annen instans. For eksempel er alle naturlige tall (1,2,3,...) også heltall (...-2,-1,0,1,2,...) og derfor innbeddet i heltallene. http://en.wikipedia.org/wiki/Embedding. Det er mer komplisert enn at de er en delmengde. 

Jeg ser det som usannsynlig at det kommer å være mange titler som har embedding som et hovedtema, det er snarere et generelt konsept en kan bruke i mange matematiske sammenhenger (se wikipedia-artikkelen), og tenker vi kan slette termen. Det er mulig Lagrangian embeddings er noe som er mer sannsynlig å være et viktig tema for en tekst, men da tenker jeg vi heller skal ha `Lagrange-innbeddinger` som term.

**Comment by knuthe** [comment]
OK. Jeh skal slette den i morgen. Jeg endrer i samme slengen "mikrosystemer" (Embedded systems) til "Innebygde systemer".

**Comment by mittinatten** [comment]
Bra, jeg har tenkt flere ganger at mikrosystemer er litt missvisende.

**Comment by knuthe** [comment]
Da er det fikset. "Mikrosystemer" stammer fra fagmiljøet her (mange år tilbake), men de har endret oppfatning.
