### ISSUE TITLE
Jordrøykfamilien

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1213]
Dette er vel egentlig en subfamilie under papaveraceae (APG IV)
Skal det fortsatt stå som egen familie?

---
*REAL001498 (Jordrøykfamilien) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c001498), [Skosmos](http://data.ub.uio.no/realfagstermer/c001498), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Jordr%C3%B8ykfamilien%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL001498)*

**Comment by Hypsibius** [comment]
Vi får vel søke å vere sånn passe oppdatert?

**Comment by BioHeidi** [comment]
Slettet
