### ISSUE TITLE
Hinebegerfamilien

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1215]
Eller skal det egentlig være "Hinnebeger"? (Plumbaginaceae)

---
*REAL002837 (Hinebegerfamilien) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002837), [Skosmos](http://data.ub.uio.no/realfagstermer/c002837), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hinebegerfamilien%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002837)*

**Comment by BioHeidi** [comment]
Jepp! Fisket!
