### ISSUE TITLE
Misjon

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1216]
Her ingen katalogposter. 
Er det snakk om kristen misjon?

---
*REAL005273 (Misjon) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005273), [Skosmos](http://data.ub.uio.no/realfagstermer/c005273), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Misjon%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL005273)*

**Comment by danmichaelo** [comment]
Hvem vet? Feilskriving av emisjon? :) Slettet ihvertfall, fant ingen spor av katalogposter.
