### ISSUE TITLE
Flimmerormer

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1219]
Usikker på om jeg finner noen gode engelske navn på Flimmerormer. 
Det ser ikke ut som at de har noe mer spesifikt en flatorm.

---
*REAL000544 (Flimmerormer) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000544), [Skosmos](http://data.ub.uio.no/realfagstermer/c000544), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Flimmerormer%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000544)*

**Comment by Hypsibius** [comment]
Barnes (min gamle invertebratbibel) gir ikkje noko hevdnamn på gruppa, oppgir berre Turbellaria, så dette kan vi legge til som engelsk/latin

Dog er termen 'invalid' hos ITIS. Moderne analyser har vel omfordelt eit par grupper derfrå, og flimmerormane er dessutan parafyletiske. Finn det likevel vanskeleg å gi slepp på. Kva seier du, @BioHeidi ?

**Comment by BioHeidi** [comment]
Tror det enkleste er å slå sammen med Flatormer - Playthelmintes. Turbellaria er lagt som synonym i ITIS.
