### ISSUE TITLE
Materialteknikk, -teknologi det samme? Og hva med Materialvitenskap?

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#122]
Jeg synes det ser ut som jeg kan slå sammen Materialteknikk og Materialteknologi (Materials technology). 

Wikipedia samler dessuten dette under Materialvitenskap / Materials science

Kan jeg slå sammen alle tre?

**Comment by danmichaelo** [comment]
Jeg tenker ihvertfall på dette som ett fagfelt.

**Comment by mittinatten** [comment]
Jeg tenker og vi kan slå de tre sammen.

Finnes det noensinne en grunn til å ha både -teknikk og -teknologi?

**Comment by danmichaelo** [comment]
Har lurt på det samme.. men uansett minner det meg om at vi må ha med "Materials engineering" som engelsk alternativ term.

**Comment by danmichaelo** [comment]
Disse er allerede slått sammen.
