### ISSUE TITLE
Vaksinering

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1220]
Slå sammen med `Vaksiner`? Eller ikke?

---
*REAL009537 (Vaksinering) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009537), [Skosmos](http://data.ub.uio.no/realfagstermer/c009537), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Vaksinering%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009537)*

**Comment by Hypsibius** [comment]
Jepp, det synest eg. Prosess/produkt igjen

**Comment by grosyn** [comment]
Har no sletta Vaksinering og behalde Vaksiner. Har òg rydda i katalogen.
