### ISSUE TITLE
Utsatt art

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1221]
Er "Utsatt art" det samme som "Truet dyreart"? Det øverste treffet handler om "endangered species", som er den engelske termen for `Truede arter`. Slå sammen disse?

---
*REAL007218 (Utsatt art) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007218), [Skosmos](http://data.ub.uio.no/realfagstermer/c007218), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Utsatt%20art%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL007218)*

**Comment by Hypsibius** [comment]
Lelease Blian!

Sanneleg om eg veit! Den første handla rett nok om 'endangered species', men også om restoration, noko som KAN bety repatriering (jf utsetjing av bever/ulv/bjørn rundt omkring). 

Det KAN og tolkast som invaderande artar (typ mink, som blei sleppt fri då pelsmarkedet krasja i mellomkrigstida). 

For å unngå forvirring, meinar eg vi bør endre hovudinnførsel til Truete Arter NN Trua artar (NB: fleirtal!). Litt usikker på om vi treng ein bfd-term som utsatte/utsette artar. Om vi treng ein innførsel til som kan dekkje utsetjing, og om det i så fall skal dekkje utsetjing av ender til jakt eller gjeninnføring/forsterking av trua av artar, er ei anna sak. Kva seiere dokke biofolk?

**Comment by anjamaa** [comment]
Vekker denne tråden igjen! Jeg ser at `Innførte arter` ligger under `Invaderende arter` nå, men ser også at `Utsatt art` fortsatt har katalogposter om "naturalisation"? De skal kanskje flyttes over?

**Comment by kyrretl** [comment]
Bra du tok tak i dette. Vi har fjernet "Utsatt art" og flyttet over to av de tre bøkene som lå på emneordet til "Innførte arter" og én til "Truede arter".

RIP Utsatt art

PS. Det var et temmelig forvirrende emneord og ikke var det satt i flertall engang!

**Comment by kyrretl** [comment]
Ehm, mente selvsagt "Invaderende arter", "Innførte arter" er fremdeles brukt for.

Altså nå har vi bare "Invaderende arter" og "Truede arter" som hovedtermer.

"Innvaderende arter": https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013939
"Truede arter": https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013791
