### ISSUE TITLE
Tyrosin

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1222]
Skal aminosyrer ha én- og/eller trebokstavsforkortelsene sine?

---
*REAL002531 (Tyrosin) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002531), [Skosmos](http://data.ub.uio.no/realfagstermer/c002531), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Tyrosin%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002531)*

**Comment by Hypsibius** [comment]
I alle fall trebokstavsforkortelsane, burde dei ikkje? Blir det kanskje mykje støy med søk etter einbokstavsforkortelsar?

**Comment by danmichaelo** [comment]
La inn Tyr. Er litt tilbakeholden med for mange forkortelser, det blir fort støy.

Fin navneliste på Wikidata forresten :)

* Tyr
* Y
* (2S)-2-amino-3-(4-hydroxyphenyl)propanoic acid
* (−)-α-amino-p-hydroxyhydrocinnamic acid
* (S)-alpha-amino-4-Hydroxybenzenepropanoic acid
* L-Tyrosin
* TYROSINE
* (-)-alpha-amino-P-Hydroxyhydrocinnamic acid
* (S)-Tyrosine
* (S)-3-(p-Hydroxyphenyl)alanine
* (S)-α-amino-4-hydroxybenzenepropanoic acid
* (S)-2-Amino-3-(p-hydroxyphenyl)propionic acid
* 4-hydroxy-L-phenylalanine
* (S)-(-)-Tyrosine
* (2S)-2-amino-3-(4-hydroxyphenyl)propionic acid
* (2S)-2-azanyl-3-(4-hydroxyphenyl)propanoic acid
* L-tyrosine
