### ISSUE TITLE
Tetrafenylporfyrin

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1225]
Slette?

---
*REAL013159 (Tetrafenylporfyrin) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013159), [Skosmos](http://data.ub.uio.no/realfagstermer/c013159), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Tetrafenylporfyrin%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL013159)*

**Comment by danmichaelo** [comment]
Slettet
