### ISSUE TITLE
Termometrisk titremetri

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1226]
Skal det være "[...] titrimetri"? Eventuelt slette termen?

---
*REAL010971 (Termometrisk titremetri) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010971), [Skosmos](http://data.ub.uio.no/realfagstermer/c010971), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Termometrisk%20titremetri%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010971)*

**Comment by danmichaelo** [comment]
Slettet, `Titremetri` får holde
