### ISSUE TITLE
Tarmbakterier

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1227]
Kan denne slås sammen med `Tarmflora`?

---
*REAL009211 (Tarmbakterier) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009211), [Skosmos](http://data.ub.uio.no/realfagstermer/c009211), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Tarmbakterier%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009211)*

**Comment by Hypsibius** [comment]
Stemmer for!

**Comment by kyrretl** [comment]
Hm, det er litt komplekst siden Tarmbakterier er underordnet Tarmflora og hvis disse slås sammen kan vi miste spesifisitet eller vise til en spesifisitet som ikke dekkes av objektet (boka).

Det er 7 objekter som har emneord Tarmbakterier og én bok som har emneord Tarmflora.

Tarmbakterier:
https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009211

Tarmflora:
https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005573

Foreslår at vi beholder begge emneordene, men legger til Tarmflora der det passer slik at dette emneordet  om slik at det blir mer riktig:

For det éne dokumentet med Tarmflora beholder vi emneordet på dokumentet.

Når det gjelder de andre 7 dokumentene med Tarmbakterier foreslår jeg følgende:
1) Hjernen og tarmen : om kroppens skjulte samtale
Legge til Tarmflora

2) Microbiota of Atlantic salmon (Salmo salar L.) during their early and adult life
Mikrobiota dekker mer enn tarmen (hud, munn, nese etc). Men siden det her er blitt gitt Tarmbakterier regner jeg med at det også omhandler tarmbakterier spesifikt, dermed skader det ikke å legge til Tarmflora her. Her kunne vi ev. erstattet Tarmbakterier med Tarmflora, men uten å ha boka foran meg er det litt vanskelig å sjekke (dette er Bergens bok).

3 og 4) Gastrointestinal microbiology 1/2
Legge til Tarmflora

5) Coliforms and E. coli : problem or solution? 
Foreslår å fjerne Patogene tarmbakterier (som bare finnes på det dokumentet) og erstatte med Patogene bakterier og legge til Tarmsystemet

6 og 7) 
A short course in bacterial genetics : a laboratory manual and handbook for Escherichia coli and related bacteria ...
Disse er greie.

Kanskje vi bør ha en se-også henvisning mellom Tarmbakterier og Tarmflora

**Comment by danmichaelo** [comment]
Imponerende research!

- [x] Lagt til SO mellom `Tarmbakterier` og `Tarmflora`
- [x] Erstattet `Patogene tarmbakterier` med `Patogene bakterier` + `Tarmbakterier` og så fjernet termen
- [x] Oppdatert de 7 katalogpostene
