### ISSUE TITLE
Syre-base-likevekter

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1229]
Endre til tankestrek eller skråstrek først? Altså `Syre–base-likevekter` eller `Syre/base-likevekter`?

---
*REAL006321 (Syre-base-likevekter) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006321), [Skosmos](http://data.ub.uio.no/realfagstermer/c006321), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Syre-base-likevekter%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL006321)*

**Comment by danmichaelo** [comment]
Fikset. Og slo den sammen med Syree–base-reaksjoner
