### ISSUE TITLE
Endozoa

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#123]
Foreslår å erstatte med Endoparasitter, BF endozoa. Vi har frå før endoparasittisme som innførsel, og blir då på linje med SNL, wikipedia og legemiddelverket ;-)

**Comment by BioHeidi** [comment]
Ja.

**Comment by BioHeidi** [comment]
Trenger vi både enoparasittisme og endoparasitter?

**Comment by Hypsibius** [comment]
Ntjaaa, lurte også litt på det. Skal vi sjå om vi kan klare oss med berre endoparasittisme?

**Comment by BioHeidi** [comment]
Ja. Gjort.
