### ISSUE TITLE
Syntetisk acetylenkjemi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1230]
Slette?

---
*REAL008495 (Syntetisk acetylenkjemi) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008495), [Skosmos](http://data.ub.uio.no/realfagstermer/c008495), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Syntetisk%20acetylenkjemi%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008495)*

**Comment by danmichaelo** [comment]
Ja, denne stammet fra "masterstudenter setter emneord på egne oppgaver"-tiden
