### ISSUE TITLE
Supermolekyler

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1231]
Legge til "supramolekyler" på norsk? Slå sammen med `Supramolekylær kjemi`?

---
*REAL006873 (Supermolekyler) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006873), [Skosmos](http://data.ub.uio.no/realfagstermer/c006873), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Supermolekyler%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL006873)*

**Comment by danmichaelo** [comment]
:+1: Og `Supermolekylære systemer`

**Comment by danmichaelo** [comment]
Slått sammen og utvidet
