### ISSUE TITLE
Mikroporøse oksider

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1236]
Slette denne og overføre katalogposten til `Mikroporøse materialer`?

---
*REAL003741 (Mikroporøse oksider) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003741), [Skosmos](http://data.ub.uio.no/realfagstermer/c003741), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Mikropor%C3%B8se%20oksider%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL003741)*

**Comment by grosyn** [comment]
Blei gjort 28.02.2019
