### ISSUE TITLE
Lr-parsering

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1238]
Rette til "LR[...]"?

---
*REAL001288 (Lr-parsering) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c001288), [Skosmos](http://data.ub.uio.no/realfagstermer/c001288), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Lr-parsering%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL001288)*

**Comment by danmichaelo** [comment]
Fiksa. Også LL-parsering.
