### ISSUE TITLE
Ligningsteorier

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1239]
Legge til "Likningsteorier" på norsk?

---
*REAL013040 (Ligningsteorier) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013040), [Skosmos](http://data.ub.uio.no/realfagstermer/c013040), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Ligningsteorier%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL013040)*

**Comment by danmichaelo** [comment]
...og fiksa!

**Comment by danmichaelo** [comment]
men eeeh. hva er ligningsteorier, mon tro..?

**Comment by danmichaelo** [comment]
Ok, det er (eller var) en greie: https://en.wikipedia.org/wiki/Theory_of_equations

Endret til `Ligningsteori BF Likningteori`
