### ISSUE TITLE
Spising/Matinntak

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#124]
Noen viktige nyanseforskjeller her, @Hypsibius og @BioHeidi, eller kan jeg bare slå sammen?

**Comment by Hypsibius** [comment]
Hm, og eg ville ikkje kalla det nokon av delene i en fagleg samanheng, men 'fødeinntak' ;-) #HvaSkaViEta Ser ikkje umiddelbart nokon nyanseforskjell, kva med deg, @BioHeidi ?

**Comment by BioHeidi** [comment]
Vi har også disse:
Ernæring BF Føde, Fødeopptak
Furasjering
Fødevalg BF Dietter
Foring BF Mating
Matvaner
Næringsopptak BF Matopptak
Næringssøk
Næringsvalg


Og kanskje litt på siden:
Matressurser
Matforsyning

Ser at disse er brukt litt om hverandre. Kan vi plukke ut noen gode og slå sammen resten? Så kan jeg rydde. Trefflistene er ikke veldig lange her, bortsett fra Ernæring som har masse treff.

Foreslår iallefall at Furasjering, Næringssøk, Næringsvalg og Fødevalg slås sammen (basert på trefflistene), og kanskje også Matvaner? Og at Ernæring beholdes som den er (evt med rydding), og får BF Næringsopptak, Matopptak. Og Foring BF Mating forbeholdes foring av dyr ved menneskelig inngripen.

**Comment by Hypsibius** [comment]
Kjøper den!

**Comment by bibliomari** [comment]
Go, Heidi! Jeg overlater til deg, eller skal jeg Sonjafisere? @BioHeidi
