### ISSUE TITLE
Lie

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1240]
Slette denne siden vi har både `Lie-algebraer` og `Lie-grupper`?

---
*REAL005549 (Lie) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005549), [Skosmos](http://data.ub.uio.no/realfagstermer/c005549), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Lie%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL005549)*

**Comment by danmichaelo** [comment]
😱 Slettet

**Comment by danmichaelo** [comment]
Kjørt `almar --diffs interactive 'Lie' 'Lie-grupper' 'Lie-algebraer'`
