### ISSUE TITLE
Leppeceller

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1241]
Legge til "[Lukkeceller](http://www.mn.uio.no/ibv/tjenester/kunnskap/plantefys/leksikon/l/lukkeceller.html)" og sette det som foretrukket term? Ser ut som det er mest brukt?

---
*REAL011722 (Leppeceller) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011722), [Skosmos](http://data.ub.uio.no/realfagstermer/c011722), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Leppeceller%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL011722)*

**Comment by kyrretl** [comment]
Vi har bestemt å legge Leppeceller (1 Post) inn i Spalteåpninger (5 poster) og ha BF Leppeceller, BF Lukkeceller på Spalteåpninger, siden den ene posten handler om Stomata (Spalteåpninger)

**Comment by danmichaelo** [comment]
...og fiksa!
