### ISSUE TITLE
Lepidoptera

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1242]
Slå sammen med `Sommerfugler`? Latinsk navn har vel et eget felt? Legge til "Lepidopterans" på engelsk?

---
*REAL012144 (Lepidoptera) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c012144), [Skosmos](http://data.ub.uio.no/realfagstermer/c012144), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Lepidoptera%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL012144)*

**Comment by Hypsibius** [comment]
Absolutt! Har forsøkt å ta sånne når eg oppdagar, men mange smett igjennom

**Comment by kyrretl** [comment]
Ja, slå sammen Sommerfugler og Lepidoptera. Preflabel Sommerfugler, EN Lepidopterans, Butterflies, LA Lepidoptera. Butterflies ligger også som engelsk term på Dagsommerfugler, så vi kan sette SO mellom Sommerfugler og Dagsommerfugler. Evt. også SO mellom Sommerfugler og Nattsommerfugler.

**Comment by Hypsibius** [comment]
Definitivt SO mellom dag- og nattsommerfuglar :-)

**Comment by danmichaelo** [comment]
Fiksa!
