### ISSUE TITLE
Kumultativ indeks

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1243]
Slette termen? Hvis ikke i det minste rette til "Kumulativ indeks"?

Forøvrig skriveleif i tittelen til katalogposten også, men har lagt igjen beskjed i skranken om det :)

---
*REAL008545 (Kumultativ indeks) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008545), [Skosmos](http://data.ub.uio.no/realfagstermer/c008545), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kumultativ%20indeks%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008545)*

**Comment by kyrretl** [comment]
Enig. Rettes til "Kumulativ indeks"

**Comment by danmichaelo** [comment]
Dårlig emneord, slettet den jeg :)
