### ISSUE TITLE
Foreslår nyterm Taksier

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1244]
NN Taksiar EN?? BF Fototaksier/ar BF kjemotaksier/ar BF geotaxier/ar BF Termotaksier/ar

jf https://snl.no/taksis

Aktuelt dok: https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71475214950002201&context=L&vid=UBB&search_scope=default_scope&tab=default_tab&lang=no_NO

**Comment by kyrretl** [comment]
EN: Taxis https://www.wikidata.org/wiki/Q949618
Enige her i emnered, hva sier du @BioHeidi

**Comment by kyrretl** [comment]
ok fra emnered (nå også heidi)

**Comment by Hypsibius** [comment]
Men det blir vel EN: Taxies om vi skal halde på fleirtalsforma?

**Comment by danmichaelo** [comment]
Opprettet :rocket:
