### ISSUE TITLE
Tekstparsering

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1245]
Skulle først til å slå denne sammen med `Parsering` siden parsering tross alt er analyse av tekst, men det er litt påfallende at alle bøkene bortsett fra én ser ut til å handle mer om "string matching algorithms", enten "approximate string matching" eller "exact string matching" enn om parsing/syntaktisk analyse. Så jeg lurer jeg på om det egentlig er betydningen "[Tekstprosessering](https://app.uio.no/ub/emnesok/realfagstermer/)" som er tiltenkt "Tekstparsering" og at disse kan slås sammen i stedet? 

---
*REAL007234 (Tekstparsering) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007234), [Skosmos](http://data.ub.uio.no/realfagstermer/c007234), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Tekstparsering%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL007234)*

**Comment by kyrretl** [comment]
Altså slette "Tekstparsering" og legge postene som hadde denne termen inn under "Tekstprosessering"?
Enig (vi i redaksjonen)

**Comment by danmichaelo** [comment]
Fikset!
