### ISSUE TITLE
Allergiplanter

### ISSUE THREAD

**Issue by kyrretl** [realfagstermer/realfagstermer#1246]
Dette emneordet dekker bare to (2) poster, og det er ikke noe artikkel i Wikipedia om temaet.

Post nr. 2 har i tillegg emneord Allergi og Planter
Foreslår at vi fjerner emneordet og legger til Allergi og Planter på post 1.

---
*REAL004977 (Allergiplanter) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004977), [Skosmos](http://data.ub.uio.no/realfagstermer/c004977), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Allergiplanter%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL004977)*

**Comment by kyrretl** [comment]
Vi er enige etter diskusjon i emneredaksjonen om å gjøre dette!

**Comment by Hypsibius** [comment]
Vi snakkar om allergiframkallande planter, og ikkje allergiske planter? Vil det ikkje då vere logisk å legge på Allergener (REAL010389), heller enn allergi?

**Comment by kyrretl** [comment]
Enig, i det

**Comment by danmichaelo** [comment]
Gjort!
