### ISSUE TITLE
Higgsbosoner

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#125]
Fra @BioHeidi s liste:
> Higgsbosoner -> Higgs-boson? Higgs boson?

Jeg har også stusset over denne, flertallsformen er så uvant at det høres liksom feil ut, men samtidig virker det jo som vi bruker ubestemt flertall konsekvent for andre partikler: elektroner, positroner, fotoner, nøytrinoer... Og nå sjekket jeg INSPEC og den bruker også flertallsform.

Noen tanker om dette, @mittinatten? Skal vi bare la det være som det er?

**Comment by mittinatten** [comment]
Jeg skrev nettopp til @BioHeidi om dette som svar på hennes e-post. Mener det burde være plural av akkurat den grunnen - vi har protoner, elektroner, kvarker, etc. Det er jo bare litt tilfeldig at Higgsbosoner har fått et personnavn. Men er helt enig med deg at det høres veldig uvant ut :)

**Comment by mittinatten** [comment]
`BF Gudpartikler`?

**Comment by danmichaelo** [comment]
Neida, det trenger vi ikke :wink:

![Say God particle one more goddamn time](http://kollokvium.files.wordpress.com/2011/12/vxji3.jpg)

**Comment by mittinatten** [comment]
:D
