### ISSUE TITLE
Animasjon - dataanimasjon?

### ISSUE THREAD

**Issue by Violabibaluba** [realfagstermer/realfagstermer#1255]
Bør ha brukt for Dataanimasjon? Eller skulle det vært en egen term? Mappes foreløpig til 777.7 Animasjon.

---
*REAL012613 (Animasjon) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c012613), [Skosmos](http://data.ub.uio.no/realfagstermer/c012613), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Animasjon%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL012613)*

**Comment by Violabibaluba** [comment]
Ok. Ser at det  i alle fall er her-note i 777 om digital filmfotografi  med hierarkisk gjennomslag -eller hva det nå heter

**Comment by danmichaelo** [comment]
Alle dokumentene handler om dataanimasjon, så det er implisitt at det er det vi mener med termen :) Men enig i at den godt kan ligge der eksplisitt også, så jeg la den til! Mapping til 006.696 også?

**Comment by BioHeidi** [comment]
Mapping gjort. Takk for påminnelsen!
