### ISSUE TITLE
Brensel  og Brennstoff

### ISSUE THREAD

**Issue by Violabibaluba** [realfagstermer/realfagstermer#1256]
Same same eller ikke? Prøver å mappe...

---
*REAL002317 (Brensel) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002317), [Skosmos](http://data.ub.uio.no/realfagstermer/c002317), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Brensel%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002317)*

**Comment by Hypsibius** [comment]
![image](https://user-images.githubusercontent.com/9350370/39993309-a711555e-5775-11e8-97da-ab2c1f0efe41.png)

![image](https://user-images.githubusercontent.com/9350370/39993332-be0a7074-5775-11e8-8b4d-9cfd3bf5f109.png)

jf denne

![image](https://user-images.githubusercontent.com/9350370/39993359-dcba7ca8-5775-11e8-96d1-d7f11e993802.png)

**Comment by Hypsibius** [comment]
Merk at brennstoff, ikkje drivstoff her jf med fuel???

**Comment by danmichaelo** [comment]
Slått sammen.

```
Brensel
BF Brennstoffer
EN Fuels
SO Kjernebrensel, Drivstoff
DE Materiale som gjennom forbrenning frigjør energi som kan brukes til oppvarming eller omgjøres til arbeid.
```

```
Drivstoffer
EN Transportation fuels
EN Motor fuels
DE Brensel som brukes til å drive en motor.
```

Litt usikker på form. Drivstoff eller Drivstoffer, @Violabibaluba ?

**Comment by danmichaelo** [comment]
Eller, etter å ha sett på katalogbelegget vårt så tenker jeg at vi antakelig kan sammen Brensel og Drivstoffer også.

**Comment by danmichaelo** [comment]
Viola svarte på epost:

> Drivstoffer høres veldig rart ut…

Iflg. ordboka er båd Drivstoff og Drivstoffer gyldig flertallsform på bokmål, så da kan vi jo foretrekke Drivstoff, men beholde begge.
