### ISSUE TITLE
Utryddelse og Artsutryddelse

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1258]
Slå sammen?

*REAL010550 (Artsutryddelse) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010550), [Skosmos](http://data.ub.uio.no/realfagstermer/c010550), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Artsutryddelse%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010550)*
*REAL013806 (Utryddelse) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013806), [Skosmos](http://data.ub.uio.no/realfagstermer/c013806), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Utryddelse%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL013806)*

**Comment by Hypsibius** [comment]
Vil tru det, kva seier @BioHeidi ?

**Comment by BioHeidi** [comment]
Gjort
