### ISSUE TITLE
Infrarød*

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#126]
Fra @BioHeidi s liste:

> Infrarøde spektra -> Infrarøde stråler -> Infrarødt lys -> Infrarødt spektrum  -her er rom for merging

Ser sånn ut. Også Infrarøde spektra. Kommer tilbake til denne over helgen :)

**Comment by mittinatten** [comment]
To termer er logiske for meg:
1. Infrarøde spektra BF Infrarødt spektrum
2. Infrarød stråling BF Infrarøde stråler BF Infrarødt lys

Generelt har vi mange term med både -stråler og -stråling. Foreslår vi rydder til bare stråling og setter BF på stråler?

**Comment by danmichaelo** [comment]
Enig, men nå har jeg omkatalogisert de fire av våre bøker som brukte `Infrarøde spektra` til `Infrarød spektroskopi` + `Spektralatlas` som form (håper det var ok, tilgivelse/tillatelse osv.. :)). Dermed trenger vi bare

Infrarød stråling BF Infrarøde stråler BF Infrarødt lys

**Comment by bibliomari** [comment]
Gjort
