### ISSUE TITLE
Ernæring og Kosthold

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1261]
Begge er foreløpig oversatt som "Nutrition". Er det rom for sammenslåing eller er det oversettelsene vi må gjøre noe med?

**Comment by Hypsibius** [comment]
Nær nok. Samanslåing!

**Comment by danmichaelo** [comment]
Ser at en kunne oversatt Kosthold som Diets, men dokumentoverlappet er såpass stort at jeg tror det er like greit å slå sammen. Gjort!

**Comment by Hypsibius** [comment]
Hm, slik eg ser det, blir ernæring uansett eit spm om førekomst av næringsstoffa i kvart item 

Gu'kko langt bak i hjernen OFT/Optimalfurasjeringsteori har hamna :-/
