### ISSUE TITLE
Arvelære og Genetikk

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1262]
Begge er foreløpig oversatt som Genetics, så vi må enten fikse bedre oversettelser eller slå sammen.

Hvis genetikk er er læren om arv og gener så høres det jo ut som det er litt overlapp her :) Men Arvelære er kanskje mer en historisk term? Mulig å definere? Avgrenset til Mendels arvelære eller ikke?

P.S. Vi har også Arvelighet.

**Comment by Hypsibius** [comment]
Eg tenkjer samanslåing
