### ISSUE TITLE
Vannhusholdning

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1263]
Dette var et veldig rart emne. Hva er det? vannbruk i planter? 

---
*REAL002293 (Vannhusholdning) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002293), [Skosmos](http://data.ub.uio.no/realfagstermer/c002293), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Vannhusholdning%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002293)*

**Comment by Hypsibius** [comment]
Meir sånn typ vannressursforvaltning? Økonomisering?

**Comment by danmichaelo** [comment]
Morsomt ord, men lett googling viser jo at det er i bruk. Iflg. SNL er det en del av [plantefysiologi](https://snl.no/plantefysiologi) og handler om planters vannopptak, vanntransport og transpirasjon. Men hva det blir på engelsk da...? Plant-water relations er ett forslag: http://www.els.net/WileyCDA/ElsArticle/refId-a0001288.html

**Comment by Hypsibius** [comment]
Hm, det bør nok med som BF-term. Men Olav Aas, fagreferent m ansvar for botanikk, foreslår Water Balance, og seier det er det flest lærebøker brukar. Mi vassressursforvaltar-søster seier det også brukast på kurs på NMBU.

**Comment by danmichaelo** [comment]
Takk for sjekk! Da prøver vi `Water balance BF Plant-water relations`. Water balance brukes også i hydrologi: https://en.wikipedia.org/wiki/Water_balance , men det går greit så lenge vi har en liten note om at vårt begrep er for planter.
