### ISSUE TITLE
Havstrender og Strender

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1264]
`Havstrender` og `Marine strender` slo jeg sammen uten å spørre. Men trenger vi skillet mellom `Havstrender` og `Strender`? Får litt følelsen av at mange av [dokumentene om strender](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007438) er om havstrender.

En idé kunne jo også vært å opprette "Fersksvannsstrender"(?) hvis vi har bøker om det.

**Comment by Hypsibius** [comment]
I tillegg til eit spm om salinitet, er det eit spørsmål om eksponeringsgrad. Brukar nokon begrepet 'havstrand', antar i alle fall eg at vi snakkar om ei eksponert strand, meeeen: 

![image](https://user-images.githubusercontent.com/9350370/40352792-18b2b14a-5db0-11e8-82a1-a797fc3b8788.png)

![image](https://user-images.githubusercontent.com/9350370/40352813-2b02ffbc-5db0-11e8-9347-934523bf891c.png)

**Comment by Hypsibius** [comment]
Indeed. Men det er ikkje fleire treff på strender enn at vi burde kunne bruke Strender BF Havstrender BR Marine Strender. Er i det pragmatiske hjørnet i dag....

**Comment by danmichaelo** [comment]
Slått sammen
