### ISSUE TITLE
Heterosykliske aromatiske hydrokarboner

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1266]
Er ingen katalogposter på dette emnet.

---
*REAL013728 (Heterosykliske aromatiske hydrokarboner) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013728), [Skosmos](http://data.ub.uio.no/realfagstermer/c013728), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Heterosykliske%20aromatiske%20hydrokarboner%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL013728)*

**Comment by danmichaelo** [comment]
Slettet
