### ISSUE TITLE
Legemiddelhistorie

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1268]
Er ingen katalogposter på emnet.

---
*REAL031331 (Legemiddelhistorie) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c031331), [Skosmos](http://data.ub.uio.no/realfagstermer/c031331), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Legemiddelhistorie%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL031331)*

**Comment by danmichaelo** [comment]
Hm, det var litt merkelig. Tror jeg skal sjekke denne med Bente. Kanskje den kan slås sammen med Apotekhistorie.

**Comment by danmichaelo** [comment]
Tror det må ha skjedd noe rart i 653-konverteringen. Vi har et dokument, "Friedrich Wilhelm Sertürner, morfinets oppdager |c Anders Bærheim Svendsen", med

    653 | __ \|a farmasihistorie \|a morfin \|a alkaloider \|a legemiddelhistorie

Mulig det holder med `Farmasihistorie BF Legemiddelhistorie`

**Comment by danmichaelo** [comment]
Bente var enig, da slår vi sammen `Farmasihistorie BF Legemiddelhistorie`
