### ISSUE TITLE
Generell likevekt (økonomi)

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1269]
Er ingen katalogposter på emnet

---
*REAL031309 (Generell likevekt (økonomi)) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c031309), [Skosmos](http://data.ub.uio.no/realfagstermer/c031309), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Generell%20likevekt%20(%C3%B8konomi)%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL031309)*

**Comment by danmichaelo** [comment]
Eeeh, vi hadde ett dokument med `Generell likevekt (økonomi) : Matematikk`, men altså ingen med `Generell likevekt (økonomi)`. Flytter.
