### ISSUE TITLE
Kalluskulturer

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1272]
Ingen katalogposter på emnet.

---
*REAL009499 (Kalluskulturer) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009499), [Skosmos](http://data.ub.uio.no/realfagstermer/c009499), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kalluskulturer%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009499)*

**Comment by danmichaelo** [comment]
Noen treff i bredt søk. Skal vi legge termen på disse postene, eller slette den, @realfagstermer/bio ?

**Comment by BioHeidi** [comment]
Ja det holder nok med vevskulturer.
