### ISSUE TITLE
Kataklysmiske variable

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1273]
Det norske emnet var litt rart. skal det egentlig stå "variabler"?

---
*REAL008121 (Kataklysmiske variable) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008121), [Skosmos](http://data.ub.uio.no/realfagstermer/c008121), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kataklysmiske%20variable%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008121)*

**Comment by danmichaelo** [comment]
Hvis det er variable stjerner tror jeg det er riktig. @superLine ?

**Comment by danmichaelo** [comment]
Endret til "Kataklysmiske variable stjerner"
