### ISSUE TITLE
Kjerner

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1275]
HJELP!

Jeg syns dette emnet er vanskelig fordi det brukes så ufattelig bredt. 
Går det ann å avgrense til astronomi, algebra, informatikk, botanikk, cellebiologi etc, eller skal man bare bruke noe så banalt som "core" eller "kernel"?

---
*REAL006807 (Kjerner) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006807), [Skosmos](http://data.ub.uio.no/realfagstermer/c006807), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kjerner%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL006807)*

**Comment by jeanetvi** [comment]
Her brukte jeg Galactic nuclei fordi det er astro det lenker til, men det er ikke en god oversettelse av ordet "kjerner"

**Comment by danmichaelo** [comment]
Den sletter jeg! Nesten alle bøkene hadde også `Aktive galaksekjerner BF Aktive kjerner` som emneord, så ganske sikker på at den ikke skulle eksistert. `Kjerner` i seg selv blir, som du sier, for mangetydig.
