### ISSUE TITLE
Klinisk legevitenskap

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1276]
Ingen katalogposter på emnet.

---
*REAL005865 (Klinisk legevitenskap) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005865), [Skosmos](http://data.ub.uio.no/realfagstermer/c005865), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Klinisk%20legevitenskap%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL005865)*

**Comment by danmichaelo** [comment]
Slettet. Vi har `Klinisk medisin`
