### ISSUE TITLE
Klipping

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1277]
klipping er et ord med mange bruksområder. Hva er riktig her? snipping? cutting?

---
*REAL010674 (Klipping) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010674), [Skosmos](http://data.ub.uio.no/realfagstermer/c010674), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Klipping%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010674)*

**Comment by danmichaelo** [comment]
✂️ ✂️ ✂️

Slettet både `Klipping`, `Skjæring` og `Materialkutting` – alle sammen var bare brukt på det samme ene dokumentet. Erstattet `Termisk metallskjæring` med `Metallskjæring`.
