### ISSUE TITLE
Bøhmtrær

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#1278]
Jeg finner bare Bøhmtrær på nett via realfagstermer og under informatikk. Er det riktig?

---
*REAL011052 (Bøhmtrær) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011052), [Skosmos](http://data.ub.uio.no/realfagstermer/c011052), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22B%C3%B8hmtr%C3%A6r%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL011052)*

**Comment by danmichaelo** [comment]
https://en.wikipedia.org/wiki/B%C3%B6hm_tree

Vi hadde Gøteborg også, så det er noen som har hatt sansen for å "fornorske" ö til ø :) Kanskje det var vanligere tidligere, jeg vet ikke.

**Comment by Hypsibius** [comment]
Det var i alle fall praksis i BIBSYS
