### ISSUE TITLE
Børsvesen

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#1279]
Direkte oversatt fra google translate er dette "Stock being". Det høres litt for lett ut i mine ører, men er det riktig?

---
*REAL007018 (Børsvesen) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007018), [Skosmos](http://data.ub.uio.no/realfagstermer/c007018), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22B%C3%B8rsvesen%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL007018)*

**Comment by danmichaelo** [comment]
Niks. Men hva *er* riktig? Prøv et søk etter "*vesen" på ordnett.no, så får du kanskje noen ideer fra andre vesener :)

Er ikke helt sikker på om vi trenger termen heller. Aksjemarkeder er kanskje en mer nyttig term.

**Comment by danmichaelo** [comment]
Løst ved at jeg flytta dokumentene til termen `Finansmarkeder`
