### ISSUE TITLE
Meduser og Medusermaneter

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#128]
Kan de slås sammen? @BioHeidi @Hypsibius

**Comment by Hypsibius** [comment]
Den siste termen verkar ikkje veldig legit på meg, tar den ikkje for god fisk. Mistenkjer at denne manglar eit komma og eit mellomrom.... Kun eitt treff i Ask, dessutan. Erstatt med meduser!

**Comment by bibliomari** [comment]
Takk!
