### ISSUE TITLE
Knopper

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1280]
Heisann!

Jeg er ikke matematiker, men skal det egentlig være kropper og ikke knopper? 
Finner ikke noe etter søk på knopp og matematikk.

---
*REAL000335 (Knopper) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000335), [Skosmos](http://data.ub.uio.no/realfagstermer/c000335), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Knopper%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000335)*

**Comment by danmichaelo** [comment]
Matematikerne har mange rare termer, men basert på presisjonsnivået på de andre termene på disse bøkene er jeg trygg nok på at dette er en skrivefeil til å slette den.
