### ISSUE TITLE
Data-orientering

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#1281]
Dette ordet har ingen emneposter. Er det noen god direkte oversettelse på det?

---
*REAL003914 (Data-orientering) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003914), [Skosmos](http://data.ub.uio.no/realfagstermer/c003914), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Data-orientering%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL003914)*

**Comment by danmichaelo** [comment]
Slettet
