### ISSUE TITLE
Konkurranserett

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1283]
Ingen katalogposter på emnet

---
*REAL009549 (Konkurranserett) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009549), [Skosmos](http://data.ub.uio.no/realfagstermer/c009549), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Konkurranserett%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009549)*

**Comment by danmichaelo** [comment]
Slettet. Andre dekker dette bedre enn oss uansett :D
