### ISSUE TITLE
Koronaen

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1284]
Er det nødvendig å ha denne i bestemt form entall når det aller meste er i ubestemt form? 

---
*REAL011991 (Koronaen) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011991), [Skosmos](http://data.ub.uio.no/realfagstermer/c011991), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Koronaen%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL011991)*

**Comment by danmichaelo** [comment]
Hvis vi viser til Solkoronaen så er det greit, fordi det bare er én av den.

Men det er rart at vi har `Koronaen` og `Korona`, ikke `Koronaen` og `Koronaer`. Og `Korona` er brukt om både koronaen til sola og andre (f.eks. "Stellar coronae in the Chandra and XMM-Newton era"). Her må vi rydde, @superLine

**Comment by superLine** [comment]
Veldig greit med rydding ja! Jeg sjekker kildene

**Comment by superLine** [comment]
Etter samtale med DM: solkoronaen brukt for koronaen (solas korona)  - og "koronaer" for alle de andre koronaenen... :-D

**Comment by danmichaelo** [comment]
Ups, @BioHeidi hadde allerede slått dem sammen. Men det gjør egentlig ikke noe siden postene uansett var rotet sammen. Endret Koronaen til [`Solkoronaen BF Koronaen BF Solas korona EN Solar corona [...]`](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc011991), opprettet [`Koronaer EN Stellar coronae [...]`](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc032104) og almarerte. Greit å ha dem adskilt fra den store mengden dokumenter om solkoronaen tror jeg.
