### ISSUE TITLE
Krystallfeil

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1286]
Krystallfeil og defekter er to emner som det kanskje er litt rart at er koblet md samme betydning?

---
*REAL013909 (Krystallfeil) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013909), [Skosmos](http://data.ub.uio.no/realfagstermer/c013909), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Krystallfeil%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL013909)*

**Comment by danmichaelo** [comment]
Hm, her henger jeg ikke helt med. Utdyp gjerne litt.
- "Krystallfeil" og "Krystalldefekter" tenker jeg på som to ulike oversettelser av samme ting. Enig?
- Du sikter kanskje at "Defekter" omfatter mer enn bare "Krystalldefekter"/"Krystallfeil"? Det er jo språklig sett riktig, men jeg troor alle dokumentene vi har handler om Krystalldefekter/-feil: https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013909 . Si fra hvis du ser noen som ikke ser ut som de gjør det.
- (eller kanskje du sikter til noe helt annet :))

**Comment by danmichaelo** [comment]
Endret til `Gitterfeil` som foretrukket term, lurer på om det er en klarere term. Tror det er en grei samleterm, men tar gjerne opp tråden igjen hvis ikke.
