### ISSUE TITLE
Handlingsvalg

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1289]
Ingen katalogposter på emnet

---
*REAL006021 (Handlingsvalg) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006021), [Skosmos](http://data.ub.uio.no/realfagstermer/c006021), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Handlingsvalg%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL006021)*

**Comment by danmichaelo** [comment]
Slettet
