### ISSUE TITLE
Korporasjoner. Var:Bittelitt - overflødig? Europeiske union : Europa

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#129]
Kan vere grunn til å spedifiere dei gongane EU går ut over sine grenser, men er ikkje anna gitt, antar eg at EU-sakar omhandlar Europa.....

**Comment by bibliomari** [comment]
Du har helt rett. Dessuten er EU for korporasjon å regne, så jeg kastet alt, jeg.

**Comment by BioHeidi** [comment]
Åpner igjen bare for å spørre: Alle korporasjoner skal ut? Jeg har slettet Informatikkbiblioteket! :-P
Men vi har noen usikkerhetsmomenter innen for astrofysikk. F.eks. Hubble Space Telescope, James Clerk Maxwell Telescope, James Webb Space Telescope, Infrared Astronomical Satellite, Infrared Space Observatory, Gamma-Ray Observatory... og sikkert flere. Ut med alt?

**Comment by bibliomari** [comment]
Jeg jobber sakte etter prinsippet ut med alt, ja. Særlig Informatikkbiblioteket :D Men jeg er ganske forsiktig, sjekker endel (OG retter enkeltposter!), for poenget er at det skal stå som emne korporasjon i 610. Hvis det er emne da, ofte er det jo ikke det. Jeg synes vi skal passe litt på alle teleskopene og sånn, men jeg kan jo snakke med Line om det, kanskje det ikke er så viktig som jeg tror.

**Comment by BioHeidi** [comment]
Siden jeg ikke aner noe om det med 610: Kan du samtidig se på Free software foundation.
