### ISSUE TITLE
Separasjon

### ISSUE THREAD

**Issue by maritsan** [realfagstermer/realfagstermer#1290]
Hei!
Tror ikke det er skilsmisse det er snakk om ;-)

---
*REAL011619 (Separasjon) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011619), [Skosmos](http://data.ub.uio.no/realfagstermer/c011619), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Separasjon%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL011619)*

**Comment by danmichaelo** [comment]
Hehe, godt eksempel på at automatisk lenking feiler ;)

Men lenking til denne blir vel greit? https://no.wikipedia.org/wiki/Separering

**Comment by maritsan** [comment]
Ja ;-)



________________________________
