### ISSUE TITLE
Syrer

### ISSUE THREAD

**Issue by maritsan** [realfagstermer/realfagstermer#1291]
Hei ;-)
Det kan jo være snakk om planter, men lurer på om det ikke er helt riktig link her.

---
*REAL009799 (Syrer) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009799), [Skosmos](http://data.ub.uio.no/realfagstermer/c009799), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Syrer%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009799)*

**Comment by danmichaelo** [comment]
Kanskje jeg ikke viste deg det, men du kan legge inn riktig mapping i Soksed ved å søke på termen slik:

![screen shot 2018-05-30 at 16 35 05](https://user-images.githubusercontent.com/434495/40727129-825a09e0-6427-11e8-9684-6340f32cc2a9.png)

Når man lagrer blir det slik:

![screen shot 2018-05-30 at 16 36 16](https://user-images.githubusercontent.com/434495/40727161-9a86952e-6427-11e8-896e-8d54eae0f1c7.png)

**Comment by danmichaelo** [comment]
Forresten, det vises ikke automatisk riktig i Emnesøk etter en har lagt inn riktig mapping i Soksed, men det kommer etterhvert ;)
