### ISSUE TITLE
Byggesaker

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#1293]
Er dette et godt begrep?

---
*REAL001603 (Byggesaker) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c001603), [Skosmos](http://data.ub.uio.no/realfagstermer/c001603), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Byggesaker%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL001603)*

**Comment by danmichaelo** [comment]
Sletta
