### ISSUE TITLE
Intern rotasjon

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1296]
ingen katalogposter på emnet

---
*REAL001874 (Intern rotasjon) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c001874), [Skosmos](http://data.ub.uio.no/realfagstermer/c001874), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Intern%20rotasjon%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL001874)*

**Comment by Hypsibius** [comment]
Blir ikkje dette uansett frykteleg spesifikt? Stryk!

**Comment by danmichaelo** [comment]
Slettet
