### ISSUE TITLE
Informasjonsledelse

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1297]
Ingen katalogposter på emnet

---
*REAL005319 (Informasjonsledelse) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005319), [Skosmos](http://data.ub.uio.no/realfagstermer/c005319), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Informasjonsledelse%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL005319)*

**Comment by Hypsibius** [comment]
Stryk!

**Comment by danmichaelo** [comment]
Slettet
