### ISSUE TITLE
Ingeriørmekanikk

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1298]
Er dette en skrivefeil i emnet? 
Ingeniørmekanikk ligger som egen emne. 

---
*REAL003290 (Ingeriørmekanikk) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003290), [Skosmos](http://data.ub.uio.no/realfagstermer/c003290), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Ingeri%C3%B8rmekanikk%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL003290)*

**Comment by Hypsibius** [comment]
Kan vel ikkje vere så mykje anna?

**Comment by danmichaelo** [comment]
Fiksa!
