### ISSUE TITLE
Instrumentanalyser

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1299]
Er det nødvendig å både ha instrumentanalyse og instrumentell analyse som emneord?

---
*REAL007658 (Instrumentanalyser) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007658), [Skosmos](http://data.ub.uio.no/realfagstermer/c007658), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Instrumentanalyser%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL007658)*

**Comment by danmichaelo** [comment]
Njet! Slått sammen!
