### ISSUE TITLE
Vannfugler

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#13]
Til @BioHeidi fra Gro Synnøve:

I Norske Webdewey står det 'akvatiske fugler' på 598.176 med ei her-note på termen 'vannfugler'. I Roald finn eg ikkje 'akvatiske fugler', kun 'vannfugler'. Etter dét eg kan sjå er 'akvatiske fugler' ikkje nemnt i samband med 'vannfugler' i Roald.

**Comment by Hypsibius** [comment]
Altså, her skulle eg nok sagt noko for ei stund sidan, men 'vannfulger' er for meg, som er oppvaksen nær tunge ornitologiske miljø eit ukjent begrep. 'Sjøfugler' og 'vadefugler' derimot... Der ein av desse kan brukast, ville eg alltid velje den termen framfor 'akvatiske fugler'

**Comment by BioHeidi** [comment]
Jeg er i og for seg enig, vannfugler lyder litt rart for meg. Jeg skal se på trefflisten om jeg kan spesifisere sjøfugler og/eller vadefugler på treffene istedet, og kanskje vi helt kan kvitte oss med akvatiske fugler.

**Comment by BioHeidi** [comment]
Gjort.
