### ISSUE TITLE
Lederroller

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1300]
Ingen katalogposter på emnet

---
*REAL006865 (Lederroller) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006865), [Skosmos](http://data.ub.uio.no/realfagstermer/c006865), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Lederroller%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL006865)*

**Comment by Hypsibius** [comment]
Stryk!

**Comment by danmichaelo** [comment]
Slettet
