### ISSUE TITLE
Lederutvikling

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1301]
Ingen katalogposter på emnet

---
*REAL003695 (Lederutvikling) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003695), [Skosmos](http://data.ub.uio.no/realfagstermer/c003695), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Lederutvikling%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL003695)*

**Comment by Hypsibius** [comment]
Stryk!

**Comment by danmichaelo** [comment]
Slo sammen med Ledelse
