### ISSUE TITLE
Legemiddelhistorie

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1302]
Ingen katalogposter på emnet

---
*REAL031331 (Legemiddelhistorie) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c031331), [Skosmos](http://data.ub.uio.no/realfagstermer/c031331), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Legemiddelhistorie%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL031331)*

**Comment by Hypsibius** [comment]
Vent, hadde ikkje vi ein annan liknande term? Kjem ikkje på i farta. I så fall bur denne inn som BF.term

**Comment by danmichaelo** [comment]
Nå er det ihvertfall `Farmasihistorie BF Legemiddelhistorie`.
