### ISSUE TITLE
Levedyktige bestander

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1303]
Ingen katalogposter på emnet

---
*REAL000389 (Levedyktige bestander) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000389), [Skosmos](http://data.ub.uio.no/realfagstermer/c000389), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Levedyktige%20bestander%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000389)*

**Comment by Hypsibius** [comment]
Stryk! Tenker dette uansett kan puttast under Bestandsanalyse og/eller Levedyktighet

**Comment by danmichaelo** [comment]
Slettet!
