### ISSUE TITLE
Lignocelluloser

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1304]
Ingen katalogposter på emnet

---
*REAL013041 (Lignocelluloser) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013041), [Skosmos](http://data.ub.uio.no/realfagstermer/c013041), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Lignocelluloser%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL013041)*

**Comment by Hypsibius** [comment]
Stryk!

**Comment by danmichaelo** [comment]
Slettet!
