### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1306]
Ingen katalogposter på emnet

---
*REAL010354 (Logger) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010354), [Skosmos](http://data.ub.uio.no/realfagstermer/c010354), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Logger%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010354)*

**Comment by BioHeidi** [comment]
Slette

**Comment by danmichaelo** [comment]
Slettet
