### ISSUE TITLE
Logplan '88

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1307]
Skal det norke emnet egentlig være loglan 88 det også?

---
*REAL010214 (Logplan '88) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010214), [Skosmos](http://data.ub.uio.no/realfagstermer/c010214), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Logplan%20'88%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010214)*

**Comment by BioHeidi** [comment]
Ja!

**Comment by danmichaelo** [comment]
Endret den til bare `Loglan` jeg, så dekker den Loglan 82 også -- som vi sikkert har *maaasse* litteratur om :D
 
Med en note om at den ikke må forveksles med det logiske språket http://foldoc.org/Loglan

Fikk ryddet litt opp på Wikidata samtidig, så føltes det litt mindre meningsløst :)
