### ISSUE TITLE
Mappeevaluering

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1308]
Ingen katalogposter på emnet

---
*REAL002887 (Mappeevaluering) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002887), [Skosmos](http://data.ub.uio.no/realfagstermer/c002887), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Mappeevaluering%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002887)*

**Comment by Hypsibius** [comment]
I så fall: stryk

**Comment by danmichaelo** [comment]
Slettet!
