### ISSUE TITLE
Elektromatografi

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#1309]
Jeg finner ikke igjen dette begrepet når jeg søker på det. Er det skrivefeil, eller er jeg dårlig til å søke? :

---
*REAL001693 (Elektromatografi) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c001693), [Skosmos](http://data.ub.uio.no/realfagstermer/c001693), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Elektromatografi%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL001693)*

**Comment by BioHeidi** [comment]
Sletter denne, dokumentet har mer forståelige emneord på seg. Antar det skulle være Elektrokromatografi, men det er ikke nødvendig på dette dokumentet (som har elektroforese som annet emneord).

**Comment by danmichaelo** [comment]
Slettet.
