### ISSUE TITLE
Evolusjonsalgoritmer. 

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#131]
Ingen treff. Antar det er snakk om evolusjonære algoritmer? Det finst, det kan vi behalde, evolusjonsalgoritmane synest eg vi kan slette.

Men når det er først snakk om det, forstår eg ikkje heilt kva for  evolusjonære algoritmer som ikkje er genetiske algoritmer (som vi også har)? Iflg wikipedia brukar EA "mechanisms inspired by biological evolution, such as reproduction, mutation, recombination, and selection", som er det same GA brukar. Men så forstår eg meg ikkje heller på algoritmar ;-)

**Comment by knuthe** [comment]
"Evolusjonsalgoritmer" er fjernet.
