### ISSUE TITLE
Etnofarmasi

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#1310]
Mistenker at denne er ganske likt som "Etnofarmakologi"? Dette begrepet er i alle fall mer utbredt på nett.

---
*REAL010029 (Etnofarmasi) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010029), [Skosmos](http://data.ub.uio.no/realfagstermer/c010029), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Etnofarmasi%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010029)*

**Comment by danmichaelo** [comment]
Denne har vært oppe før: #127 

Slo de sammen nå. Litt mer usikker på Folkemedisn / Etnomedisin.
