### ISSUE TITLE
Dekking

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#1311]
Jeg forstår ikke hva dette skal være på engelsk...

---
*REAL010032 (Dekking) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010032), [Skosmos](http://data.ub.uio.no/realfagstermer/c010032), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Dekking%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010032)*

**Comment by Hypsibius** [comment]
Har det med deck å gjere?

**Comment by Violabibaluba** [comment]
Dette skjønner ingen1 Så den sletter vi bare!
