### ISSUE TITLE
Gamere

### ISSUE THREAD

**Issue by iloveyellow** [realfagstermer/realfagstermer#1312]
Ønsker å sette denne termen på boka "Game Boys" av Michael Kane

**Comment by iloveyellow** [comment]
@danmichaelo foreslår evt gamerkultur, gaming eller dataspillkultur.

**Comment by danmichaelo** [comment]
@starseekr, @kyrretl  : Meninger om denne?

`E-sport` kunne kanskje også vært en bra term for denne boka?

Holder det med ett sekkebegrep (`E-sport BF Gaming, gamere, profesjonell dataspilling, ...`) eller trenger vi flere? Hvis ett, hva bør være foretrukket term?

https://www.amazon.com/Game-Boys-Heartbreak-Battleground-Competitive/dp/0452295440

**Comment by danmichaelo** [comment]
Kanskje vi skal ha to?
- `E-sport BF Profesjonell dataspilling, Profesjonell gaming, ...`
- `Gamere BF dataspillere, gamerkultur, ...` om persongruppen og kulturen?

Og så har vi jo `Dataspill` fra før.

**Comment by iloveyellow** [comment]
I emneregisteret fins også Dataspill : Fritidssosiologi og Psykologiske aspekter : Dataspill

**Comment by starseekr** [comment]
Jeg støtter to-begrepsinndeling en med e-sport for profesjonelle og noe som handler om spillere (og spillkultur - er spillkultur et eget ord?).  Men er ikke helt for gamer(e) i norsk emneordsliste, selv om det definitivt er det mest innarbeidede.  Spillere? Dataspillere? 

Og boken som er eksempel her bør kanskje ha begge emnene hektet på?

**Comment by iloveyellow** [comment]
ok, hva blir det til?

boken er forresten skrevet av en sosiolog og en dataspillforsker, og handler om politikk og maktstrukturer inne spillene, de ideologiske nettverkene rundt produksjonen av dataspill, hvordan spills ideologier påvirker spilleres ideologier, hvordan gamere blir resosialisert og utvikler sin personlige karakter gjennom interaksjon med spillet, og forholdet mellom produsenter og konsumenter av dataspill. Jeg syns nesten vi kan kalle dette spillsosiologi.

**Comment by starseekr** [comment]
Spillsosiologi høres heller ikke feil ut. Jeg kan kjøre en sjekk med en tidligere kollega som jobber med akkurat dette (Faltin Karlsen, professor i medievitenskap og en av landets fremste på spill og kultur/samfunn/avhengighet/brukerpåvirkning etc).

**Comment by iloveyellow** [comment]
humord har forresten dataspillteori.

**Comment by iloveyellow** [comment]
ja, så fint at du sjekker @starseekr ! :1st_place_medal:

**Comment by starseekr** [comment]
Faltin er på ferie, så vet ikke helt når jeg får svar. Men, evt! Det vi kan gjøre er å snakke med Karoline Hoff på HumSam - jeg TROR hun lagde forslag til en thesaurus for dataspill som bacheloroppgave :)

**Comment by starseekr** [comment]
Jeg tror jeg holder en knapp på DMs forslag fortsatt: 
* e-sport - om alt rundt e-sport, fra utøvere til tilskuere, pengeflyt, platformer, serverløsninger osv
* dataspillere - om spillerne og alt som har med mennesker rundt spill å gjøre (på engelsk også brukes players mer enn gamers om dette)

Kobler du disse to får du jo med det essensielle for denne boken, og diskuteres det andre ting brukes gjerne de samme ordene som for øvrige medier/situasjoner? Er det en stor forskjell på sosiologi og spillsosiologi? 

Ang Dataspillteori: dette handler i spillutviklerverdenen om alt rundt design av spill, fra historiefortelling til spillmekanismer og balansering.

**Comment by iloveyellow** [comment]
ok, jeg vet ikke hvordan man legger det inn.

**Comment by BioHeidi** [comment]
Og Solveig og Karoline deler kontor på torsdager (men kanskje ikke nå i sommerferien), så dere kan jo diskutere videre ved anledning :)

**Comment by danmichaelo** [comment]
Lagt til på boka.
