### ISSUE TITLE
Dyrehold

### ISSUE THREAD

**Issue by Violabibaluba** [realfagstermer/realfagstermer#1313]
Hva er forskjellen på denne og Husdyrhold? Prøver å mappe til dewey...Slås sammen?

---
*REAL002566 (Dyrehold) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002566), [Skosmos](http://data.ub.uio.no/realfagstermer/c002566), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Dyrehold%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002566)*

**Comment by Hypsibius** [comment]
Hm. Iflg definisjonen er husdyr tamde dyr, noko som burde omfatte alt frå bufe til katt, kaniner og papegøyer. Men er alle kjæledyr tamde og følgjeleg husdyr? Kva med fisk og krepsdyr? Korallar i saltvassakvariar? Og kva med hjort eller elg i innhegning? Bjørn i dyrepark? Desse er nok ikkje etter generell oppfatning husdyr, men det dreier seg likevel om dyrehald....

**Comment by BioHeidi** [comment]
Vi kan rydde vekk termen dyrehold som er brukt på 5 dok. Noen kan få husdyrhold som ekstra term, på noen kan termen bare slettes fordi andre dekker bedre.
