### ISSUE TITLE
Caudofoveata 

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1314]
Foreslår nyterm Caudofoveata BF Chaetodermomorpha 

jf

ITIS

SLN og Wikipedia held på termen Aplacophora, men denne er iflg ITIS ikkje valid, og truleg ikkje monofyletisk :-/ Dermed finst det heller ikkje noko godt, gyldig norsk namn, såvidt eg forstår. 

Aktuelt dokument: https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71560698940002201&context=L&vid=UBB&search_scope=default_scope&tab=default_tab&lang=no_NO

http://hdl.handle.net/1956/17813

**Comment by BioHeidi** [comment]
Vi kan likevel legge på BF Aplacophora.
Kan vi bruke ormebløtdyr og/eller pelsmollusker? 
Jfr https://www.artsdatabanken.no/Taxon/Aplacophora/456

**Comment by Hypsibius** [comment]
Pelsmolluskar var nytt for meg, men så treffande! VI kan vel ikkje la sjansen gå frå oss til eitt så fantastisk namn? Og la oss ta med Ormebløtdyr og Aplacophora også, så folk får hjelp til å finne rett.

**Comment by danmichaelo** [comment]
Kult! Hvilken term som foretrukket?

**Comment by Hypsibius** [comment]
Trur nesten det må bli Caudofoveata, sjølv om pelsmollusker er kulare

**Comment by danmichaelo** [comment]
Opprettet! REAL032031
