### ISSUE TITLE
Skaper / Maker

### ISSUE THREAD

**Issue by starseekr** [realfagstermer/realfagstermer#1315]
Jeg klarer ikke finne noe emneord for skaperbevegelsen / maker movement - makerspaces og hele filosofien rundt dette. 

Forslag: 

No: Skaperbevegelsen - skaper, skaperverksteder
Eng: Maker movement - makerspaces, maker culture, hackerspace, hacker culture

Eng wiki: https://en.wikipedia.org/wiki/Maker_culture
No wiki: https://no.wikipedia.org/wiki/Skaperverksted <- mangler noe på bevegelsen...

**Comment by danmichaelo** [comment]
Nei, på tide å gjøre noe med det! Skaparrørsla høres jo kjempefint ut :)

Har opprettet: [REAL032010](http://data.ub.uio.no/realfagstermer/c032010). La inn noen flere termer også.

**Comment by Hypsibius** [comment]
😬 Fryktar antidarwinistisk vekkjing på vestlandet, men la gå
