### ISSUE TITLE
Nyterm Mesokosmos

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1317]
Nyterm Mesokosmos NN Mesokosmos En Mesocosm

Frå Wikipedia: A mesocosm (meso- or 'medium' and -cosm 'world') is any outdoor experimental system that examines the natural environment under controlled conditions. In this way mesocosm studies provide a link between field surveys and highly controlled laboratory experiments.[1]

https://en.wikipedia.org/wiki/Mesocosm

Mykje brukt på UiB til å studere alt frå algar og sedimentering til fiskelarvarr. 

Aktuelt  dokument: https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71500885900002201&context=L&vid=UBB&search_scope=default_scope&tab=default_tab&lang=no_NO

**Comment by BioHeidi** [comment]
Heh, har vi ikke denne allerede? (Hilsen mesokosmoseksperten)
Er ikke definert bare til felteksp, men også i lab.

**Comment by danmichaelo** [comment]
Opprettet. Med flertallsform "Mesocosms" på engelsk. 

La inn Mesokosmer også som alternativ term på bokmål og nynorsk (litt usikker på bøyningen på nynorsk, blir `Mesokosmer` bra?).

**Comment by danmichaelo** [comment]
Vi har forresten [Lukkete økosystemer](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000323). Skal vi beholde den og legge til SO Mesokosmos? Eller gjøre noe annet med den?

**Comment by BioHeidi** [comment]
Mesokosmoser vel? Det sier i alle fall jeg :D
Posten på "Lukkete økosystemer" kan få Mesokosmos istedet.

**Comment by Hypsibius** [comment]
Nopes! Ingen av delene! Eit/et kosmos, fleire/flere kosmos. Nynorsk såvel som bokmål. Meso-kosmos må vel følge same bøying, såvidt eg forstår? 

:-P

**Comment by danmichaelo** [comment]
Ok, mesokosmer er nok norwenglish (eller engorsk?). Vi kan vente med den til vi får et "hiddenLabel"-felt der vi kan legge inn vanlige skrivefeil og sånt :)
