### ISSUE TITLE
Nyterm: Filterspisere

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1318]
Nytern Filterspisere BF Filterspisende BF Filtrerere BF Filteretere NN Filteretarar Filteretande NN Filtrerarar EN Filter feeders

https://no.wikipedia.org/wiki/Filterspiser

https://snl.no/.search?utf8=%E2%9C%93&query=filterspiser

Aktuelt dokument: https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=TN_crossref10.1017/S0025315400033464&context=PC&vid=UBB&search_scope=default_scope&tab=default_tab&lang=no_NO

**Comment by danmichaelo** [comment]
Oppretta :ocean:

**Comment by Hypsibius** [comment]
Ojda! Vi har også Suspensjonsetere (REAL004129)

**Comment by danmichaelo** [comment]
Legge inn SO mellom dem?

**Comment by Hypsibius** [comment]
Etter litt diskusjon her og sjekk i Oxford References (fleire oppslagsverk der brukar denne definisjonen), trur eg vi oppfattar dei som det same, og brukar BF. Beklager, skulle såklart oppdaga dette før vi oppretta nyterm. Mi utgåve av Valiela er litt diffus i definisjonane og snakkar veldig om aktivt og passivt fødeval i ulik viskositet. Nyaste utgåva ser ikkje ut til å knytte dette til begrepsbruken (særs kjapp skumming)

![image](https://user-images.githubusercontent.com/9350370/44515814-c80e1600-a6c3-11e8-8af0-9aff21aaaa7b.png)

**Comment by danmichaelo** [comment]
Null problem. Har flere ganger opprettet nye termer og så angret meg.

Da har vi Suspensjonsetere BF Filterspisere
