### ISSUE TITLE
Fjellrotter

### ISSUE THREAD

**Issue by eirillsh** [realfagstermer/realfagstermer#1319]
Norsk:
Også kjent som fjellmarkmus

Latin: 
Microtus oeconomus

---
*REAL010452 (Fjellrotter) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010452), [Skosmos](http://data.ub.uio.no/realfagstermer/c010452), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Fjellrotter%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010452)*

**Comment by danmichaelo** [comment]
Lagt til!
