### ISSUE TITLE
Evolusjonsbiologi - Brukes IKKE

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#132]
I innførselen står det: NO BRUKES IKKE! Bruk "evolusjon". Må ryddes på poster.

Vi har ikkje ein open issue på det, vel?

**Comment by BioHeidi** [comment]
Nå har vi det. Det var så utrolig mye rart der, så vi måtte unngå å få mer rart der.

**Comment by BioHeidi** [comment]
Men, trenger du termen Evolusjonsbiologi? Som noe annet enn Evolusjon? Har en ide om å bare slå de to sammen når det rare er plukket ut.

**Comment by Hypsibius** [comment]
Når du seier det sånn, skal eg nok greie meg med Evolusjon...

**Comment by BioHeidi** [comment]
Gjort
