### ISSUE TITLE
Flygeledere

### ISSUE THREAD

**Issue by eirillsh** [realfagstermer/realfagstermer#1320]
Norsk:
Flyveleder

er forøvrig usikker på om dette blir entall eller flertall. Flygeledere kan telles, mens yrket flygeleder kan ikke telles.

---
*REAL005223 (Flygeledere) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005223), [Skosmos](http://data.ub.uio.no/realfagstermer/c005223), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Flygeledere%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL005223)*

**Comment by danmichaelo** [comment]
Normen ser ut til å være å behandle yrker som persongrupper, altså flertall, så jeg la bare inn `Flyveledere`.
