### ISSUE TITLE
Meteorstormer

### ISSUE THREAD

**Issue by eirillsh** [realfagstermer/realfagstermer#1321]
Norsk:
Også Meteorsverm

---
*REAL011493 (Meteorstormer) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011493), [Skosmos](http://data.ub.uio.no/realfagstermer/c011493), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Meteorstormer%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL011493)*

**Comment by danmichaelo** [comment]
Lagt til!
