### ISSUE TITLE
Moderne algebra

### ISSUE THREAD

**Issue by eirillsh** [realfagstermer/realfagstermer#1322]
Kan også referere til en "betydningsfull bok" i matematikken.

---
*REAL007163 (Moderne algebra) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007163), [Skosmos](http://data.ub.uio.no/realfagstermer/c007163), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Moderne%20algebra%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL007163)*

**Comment by danmichaelo** [comment]
Lol, sletter denne.
