### ISSUE TITLE
Leseteknikk

### ISSUE THREAD

**Issue by eirillsh** [realfagstermer/realfagstermer#1323]
Norsk:
Studieteknikk

---
*REAL007351 (Leseteknikk) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007351), [Skosmos](http://data.ub.uio.no/realfagstermer/c007351), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Leseteknikk%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL007351)*

**Comment by danmichaelo** [comment]
Slo de sammen siden vi bare hadde ett dokument om leseteknikk.

    Studieteknikk BF Leseteknikk
