### ISSUE TITLE
Leseferdighet

### ISSUE THREAD

**Issue by eirillsh** [realfagstermer/realfagstermer#1324]
Norsk:
Lesekyndiget

---
*REAL008089 (Leseferdighet) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008089), [Skosmos](http://data.ub.uio.no/realfagstermer/c008089), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Leseferdighet%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008089)*

**Comment by danmichaelo** [comment]
Takk, lagt inn!
