### ISSUE TITLE
Lego og leketøy

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1326]
Vi har bare ett dokument om [leketøy](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006268), og det handler om [lego](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010179), som vi har tre dokumenter om (inkludert strengene...). Flytte det over og slette Leketøy? Vi kan jo opprette den igjen ved behov.

Ser at både LCSH og GND har LEGO som emneord, så da kan vel vi også.

**Comment by BioHeidi** [comment]
Ja

**Comment by grosyn** [comment]
Gjort.
