### ISSUE TITLE
Plantesosiologi og Fytososiologi

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1328]
Samme ting? Eller ei?

---
*REAL002149 (Plantesosiologi) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002149), [Skosmos](http://data.ub.uio.no/realfagstermer/c002149)

*REAL004953(Fytososiologi) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004953), [Skosmos](http://data.ub.uio.no/realfagstermer/c004953)

**Comment by BioHeidi** [comment]
Ja, samme. Kunne evt vurdere å legge Plantesamfunn i potten, og Vegetasjonstyper: https://snl.no/plantesosiologi

**Comment by grosyn** [comment]
Slo saman - valde Plantesosiologi som hovudemneord. Rydda i katalogen. Oppdaga så at Plantesosiologi syner til Plantesamfunn (etter ei endring i mars 2019). Eg endra i almar endå ein gong :-) No er det Plantesamfunn som gjeld. 
Skal Vegetasjonstyper òg vera med på denne moroa, eller stå for seg sjølv som sin eigen term, slik den gjer i dag?

**Comment by BioHeidi** [comment]
Ja, la Plantesamfunn og Vegetasjonstyper ha det moro sammen. Plantesamfunn BF Vegetasjonstyper.

**Comment by grosyn** [comment]
Slått saman, og Vegetasjonstyper er sletta.
