### ISSUE TITLE
Gjenfangst

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1329]
Endre til `Fangst/gjenfangst-metoden EN Capture-recapture method`? Eller brukes gjenfangst om flere ting (som vi har litteratur om)?

---
*REAL011745 (Gjenfangst) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011745), [Skosmos](http://data.ub.uio.no/realfagstermer/c011745), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Gjenfangst%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL011745)*

**Comment by BioHeidi** [comment]
Brukes ikke om noe annet såvidt jeg vet, men jeg vil gjerne beholde den enkle termen Gjenfangst som hoved, kan heller legge på fangst-gjenfangst... som BF. Merking-gjenfangst-metode er også en betegnelse som evt kunne legges på, og en haug andre:
https://en.wikipedia.org/wiki/Mark_and_recapture

**Comment by danmichaelo** [comment]
Okidoki!
