### ISSUE TITLE
Evolusjonsøkologi - til evolusjonær økologi

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#133]
Foreslår å erstatte hovedinnførsel med 'evolusjonær økologi'. Dette samsvarar med wikipedia/sln, og bukast dessutan i presentasjon av feltet både ved UiO og UiB. Mao evolusjonær økologi BF evolusjonsøkologi

**Comment by BioHeidi** [comment]
Enig.

**Comment by BioHeidi** [comment]
Gjort
