### ISSUE TITLE
Local Non-metric Multidimensional Scaling

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1330]
Vi har denne veldig snevre termen, men mangler de overordnede "Multidimensional Scaling" og "Non-metric Multidimensional Scaling". Foreslår å endre den til enten `Multidimensjonal skalering` (MDS) eller `Ikke-metrisk multidimensjonal skalering` (NMDS). Siden metoden er brukt av bio, spør jeg @realfagstermer/bio hvilken dere synes er best? (Gitt dokumentene vi har og synsing om fremtidig bruk)

---
*REAL003746 (Local Non-metric Multidimensional Scaling) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003746), [Skosmos](http://data.ub.uio.no/realfagstermer/c003746), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Local%20Non-metric%20Multidimensional%20Scaling%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL003746)*

**Comment by BioHeidi** [comment]
Stemmer for Multidimensjonal skalering.

**Comment by Caroline-A** [comment]
Jeg er enig med MDS BF NMDS, siden jeg tror at NMDS er [en type MDS](https://en.wikipedia.org/wiki/Multidimensional_scaling#Non-metric_multidimensional_scaling_(nMDS)).

**Comment by danmichaelo** [comment]
Endra!
