### ISSUE TITLE
Fuktighet

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1331]
Litt brei term.. Endre til `Jordfuktighet EN Soil moisture`? Blir ikke det riktig for de dokumentene vi har?

---
*REAL002032 (Fuktighet) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002032), [Skosmos](http://data.ub.uio.no/realfagstermer/c002032), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Fuktighet%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002032)*

**Comment by danmichaelo** [comment]
Ser at Wikipedia har slått sammen "Water content" og "Soil moisture". Det kunne vi *evt.* gjort også, vi har allerede "Vanninnhold" (brukt om vanninnhold i sement), så `Vanninnhold BF Jordfuktighet`. Men litt usikker på om det er en god idé. Innspill ønskes :)

**Comment by BioHeidi** [comment]
Vanninnhold kan jo være et mål på mye mer enn bare jord og sement, f.eks. i planter og matvarer. Vi beholder vanninnhold som egen samleterm. Markvann BF Jordvann er termen vi trenger for dokumentene under Fuktighet. Så kan fuktighet slettes som term. Jordfuktighet tror jeg ikke jeg har hørt noen bruke.

**Comment by danmichaelo** [comment]
Ok!

```
$ almar --diffs replace 'Fuktighet' 'Markvann'
2018-11-02 17:05:20 INFO     ✔ Authorized: 650 $a Markvann $2 noubomn $0 (NO-TrB                                                                                         IB)REAL001569
2018-11-02 17:05:21 INFO     2 catalog records to be changed
Continue? [Y/n] y
2018-11-02 17:05:26 INFO     Updating record 1/2: 997820000104702201
2018-11-02 17:05:27 INFO     Diff:
--- Original
+++ Modified
@@ -12,7 +12,7 @@
 300 ## $a xiv,342s. $b ill.
 490 1# $a Studies in ecology $v 4
 500 ## $a Har bibliografi.
-650 #7 $a Fuktighet $2 noubomn $0 (NO-TrBIB)REAL002032
+650 #7 $a Markvann $2 noubomn $0 (NO-TrBIB)REAL001569
 650 #7 $a Ernæring $2 noubomn $0 (NO-TrBIB)REAL013411
 650 #7 $a Rotsystemer $2 noubomn $0 (NO-TrBIB)REAL013708
 650 #7 $a Pedologi $2 noubomn $0 (NO-TrBIB)REAL009039

2018-11-02 17:05:27 INFO     Updating record 2/2: 998030880274702201
2018-11-02 17:05:28 INFO     Diff:
--- Original
+++ Modified
@@ -12,7 +12,7 @@
 500 ## $a "A Wiley-Interscience publication."
 650 #7 $a Tilpasning $2 noubomn $0 (NO-TrBIB)REAL010480
 650 #7 $a Temperatur $2 noubomn $0 (NO-TrBIB)REAL000793
-650 #7 $a Fuktighet $2 noubomn $0 (NO-TrBIB)REAL002032
+650 #7 $a Markvann $2 noubomn $0 (NO-TrBIB)REAL001569
 650 #7 $a Vann $2 noubomn $0 (NO-TrBIB)REAL013034
 650 #7 $a Planter $2 noubomn $0 (NO-TrBIB)REAL013826
 653 ## $a planter $a adaptasjon $a vann $a fuktighet $a temperatur $a stress

2018-11-02 17:05:28 INFO     Job 5222f0419ce39e4861b2f605b1f4e4ffd42b3ea8 completed. Made 4 changes to 2 records
```

og slettet `Fuktighet`.
