### ISSUE TITLE
Språkteknologi

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1334]
ingen katalogposter

---
*REAL032021 (Språkteknologi) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c032021), [Skosmos](http://data.ub.uio.no/realfagstermer/c032021), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Spr%C3%A5kteknologi%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL032021)*

**Comment by danmichaelo** [comment]
→ Datalingvistikk
