### ISSUE TITLE
Innenrikshandel

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1336]
ingen katalogposter

---
*REAL000385 (Innenrikshandel) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000385), [Skosmos](http://data.ub.uio.no/realfagstermer/c000385), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Innenrikshandel%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000385)*

**Comment by danmichaelo** [comment]
Slettet
