### ISSUE TITLE
Sosialt samkvem

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1337]
ingen katalogposter

---
*REAL000822 (Sosialt samkvem) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000822), [Skosmos](http://data.ub.uio.no/realfagstermer/c000822), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Sosialt%20samkvem%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000822)*

**Comment by danmichaelo** [comment]
Sletta
