### ISSUE TITLE
Sletting: Exocytose, samt merging av eksocytose og exocytosis

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#134]
Så vidt eg kan finne, er korrekt stavemåte på norsk eksocytose (jf eksempelvis norsk medisinsk leksikon). Foreslår derfor å slette exocytose som term. Vi beheld altså eksocytose, men slår saman med EN exocytosis

**Comment by BioHeidi** [comment]
Enig.

**Comment by bibliomari** [comment]
Gjort
