### ISSUE TITLE
Sar

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1342]
Rart emne brukt på to vidt forskjellige katalogposter.

---
*REAL003292 (Sar) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003292), [Skosmos](http://data.ub.uio.no/realfagstermer/c003292), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Sar%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL003292)*

**Comment by Hypsibius** [comment]
og rarare blir det når vi jamfører m wikipediaoppslaget 

![image](https://user-images.githubusercontent.com/9350370/44257414-38242400-a20c-11e8-80d5-9bbca42451ab.png)

**Comment by danmichaelo** [comment]
Flytter det første dokumentet til [Syntetisk apertur-radar](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013710), og så tror jeg vi bare kan slette den.
