### ISSUE TITLE
Utstråling

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1345]
Jeg er litt usikker på om det egentlig er noen forskjell på "utstråling" og "stråling".  Er det nødvendig å ha to emneord på det, når det bare er en katalogpost på "utstråling"?

---
*REAL011105 (Utstråling) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011105), [Skosmos](http://data.ub.uio.no/realfagstermer/c011105), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Utstr%C3%A5ling%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL011105)*

**Comment by danmichaelo** [comment]
Absolutt ikke! Sletter

(Stråling i seg selv er også et ganske dårlig emneord fordi bøkene som har det emneordet har veldig lite til felles, men utsetter det problemet)
