### ISSUE TITLE
Veikanter

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1347]
Ingen katalogposter på emnet

---
*REAL013736 (Veikanter) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013736), [Skosmos](http://data.ub.uio.no/realfagstermer/c013736), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Veikanter%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL013736)*

**Comment by Hypsibius** [comment]
Nei, men vi har to på  veikanter: planter

**Comment by danmichaelo** [comment]
Ikke nå lenger! Vi fikk ryddet vekk denne.
