### ISSUE TITLE
Økonomisk produksjonsøkonomi

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1349]
Er ikke dette emneordet litt smør på flesk? 

---
*REAL006584 (Økonomisk produksjonsøkonomi) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006584), [Skosmos](http://data.ub.uio.no/realfagstermer/c006584), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22%C3%98konomisk%20produksjons%C3%B8konomi%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL006584)*

**Comment by Hypsibius** [comment]
Dette høyrest ut som eit oppdelingsproblem frå den opprinnelege importen av frie enmeord?

**Comment by danmichaelo** [comment]
Wow! Sletter! (Den ene boka hadde andre gode emneord)
