### ISSUE TITLE
Fargeforandringer

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#135]
Ikkje heilt nøgd med termen slik den står. Skal tydelegvis (ut frå trefflista) dekkje kamuflasje eller aposematisme, over evolusjonær tid eller over kort tid. Synest ikkje begrepet er spesifikt nok til å bli brukt om 'pigment translocation', eller justering av reflekterande flater og liknande fenomen....

**Comment by BioHeidi** [comment]
Enig i at det er en dårlig term. Ser at den i de fleste tilfeller er brukt overflødig også, det finnes andre emneord på postene som dekker bedre. Stemmer for at termen slettes, og så får vi lage nye spesifikke termer etter behov.

**Comment by Hypsibius** [comment]
Jepp!

**Comment by bibliomari** [comment]
Gjort
