### ISSUE TITLE
Økologiske faktortall

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1351]
Er det nødvendig å ha både økologiske faktortall og økologiske faktorer som selvstendige emner? 

---
*REAL006453 (Økologiske faktortall) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006453), [Skosmos](http://data.ub.uio.no/realfagstermer/c006453), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22%C3%98kologiske%20faktortall%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL006453)*

**Comment by Hypsibius** [comment]
Faktortall? Hæ?

**Comment by danmichaelo** [comment]
Slått sammen, fjernet faktortall
