### ISSUE TITLE
Økologisk tilstand

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1352]
Ingen katalogposter på emnet

---
*REAL005945 (Økologisk tilstand) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005945), [Skosmos](http://data.ub.uio.no/realfagstermer/c005945), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22%C3%98kologisk%20tilstand%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL005945)*

**Comment by Hypsibius** [comment]
Loddent og tvilsamt omgrep i alle fall?

**Comment by danmichaelo** [comment]
Slettet
