### ISSUE TITLE
Åreføttinger

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1353]
Googlesøk på åreføtting kommer ikke opp med noe treff. Er det en art som har at annet vanlig navn?

---
*REAL008367 (Åreføttinger) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008367), [Skosmos](http://data.ub.uio.no/realfagstermer/c008367), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22%C3%85ref%C3%B8ttinger%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008367)*

**Comment by Hypsibius** [comment]
:-O :-O :-O Oppvaksa i ein ornitologheim var dette eit komplett nytt begrep for meg: 
![image](https://user-images.githubusercontent.com/9350370/44326232-4c119500-a45b-11e8-8776-1e1590933253.png)

![image](https://user-images.githubusercontent.com/9350370/44326254-5af84780-a45b-11e8-981b-1cb321c09ba3.png)

**Comment by BioHeidi** [comment]
Her har vi ment Bladfotinger (Branchiopoda), så jeg har lagt sammen. Men jeg tror jeg sletter Åreføttinger som BF, for å ikke få forveksling med skarv. (Artsdatabanken har forresten Årefotinger som synonym til Bladfotinger (Branchiopoda) også).

**Comment by Hypsibius** [comment]
Lurt!
