### ISSUE TITLE
Verifikasjoner

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1354]
Er det nødvendig å ha både emnet verifikasjon og emnet verifikasjoner?

---
*REAL012036 (Verifikasjoner) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c012036), [Skosmos](http://data.ub.uio.no/realfagstermer/c012036), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Verifikasjoner%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL012036)*

**Comment by danmichaelo** [comment]
Nope! Derimot burde vi nok ideelt sett delt opp `Verifikasjon` i mer spesifikke og veldefinerte begreper, men det kan bli litt vanskelig...
