### ISSUE TITLE
Vekstøkologi

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1355]
Er litt usikker på hva dette emnet refererer til. Vekst som i å bli større eller vekst som i vekster. 

---
*REAL005601 (Vekstøkologi) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005601), [Skosmos](http://data.ub.uio.no/realfagstermer/c005601), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Vekst%C3%B8kologi%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL005601)*

**Comment by BioHeidi** [comment]
Slettet.
