### ISSUE TITLE
Skogssamfunn

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1357]
Er det nødvendig å ha både skogsamfunn og skogssamfun som emner?

---
*REAL005941 (Skogssamfunn) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005941), [Skosmos](http://data.ub.uio.no/realfagstermer/c005941), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Skogssamfunn%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL005941)*

**Comment by Hypsibius** [comment]
Absolutt ikkje!

**Comment by jeanetvi** [comment]
Soksed

**Comment by jeanetvi** [comment]
Ja.
Vet ikke om disse lenken fungerer:
http://ub-soksed.uio.no/concepts/REAL008440?view=mapping&q=skogsamfunn,&sort=label:asc
http://ub-soksed.uio.no/concepts/REAL005941?view=mapping&q=skogssamfunn,&sort=label:asc

Skogsamfunn er oversatt. Skogssamfunn er ikke det. 

Hvis du tenker på skogssamfun så er det bare jeg som hoppet over en 'n' i samfunn :P

**Comment by danmichaelo** [comment]
Joda, lenkene funker. Jeez, noen ganger blir man helt blind :O  Slår sammen!
