### ISSUE TITLE
Skuldere

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1358]
Skulle det vært skulder, eller skuldre i flertall?

---
*REAL008076 (Skuldere) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008076), [Skosmos](http://data.ub.uio.no/realfagstermer/c008076), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Skuldere%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008076)*

**Comment by danmichaelo** [comment]
Skulle nok vært skuldre, men blir det riktig å si at fisk har skuldre eller skulle det vært en annen term? Skulderbuer? @realfagstermer/bio

**Comment by Hypsibius** [comment]
Brystfinnar? Som er analoge med amfibiar og reptilar sine skuldrar :-)

Ellers: http://peanuts.wikia.com/wiki/July_1982_comic_strips?file=19820713.gif

**Comment by danmichaelo** [comment]
Gah, @BioHeidi , du må rydde denne i Sonja, jeg tar ikke sjansen

**Comment by BioHeidi** [comment]
Slettet den. Letteste ryddingen :dancing_men:

**Comment by BioHeidi** [comment]
Og her skulle det stått noe om byrder og skuld(e)re...
