### ISSUE TITLE
Slam

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1359]
Usikker på om dette refererer til Simultaneous localization and mapping eller noe annet?

---
*REAL008847 (Slam) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008847), [Skosmos](http://data.ub.uio.no/realfagstermer/c008847), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Slam%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008847)*

**Comment by danmichaelo** [comment]
Hvis du ser i Emnesøk så står det "Programmeringsspråk" under termen. Videre kan man søke opp boktitlene. Boka "Introduction to simulation and SLAM II" fant jeg ikke i fulltekst, men fant [en annen artikkel om SLAM II](https://pdfs.semanticscholar.org/3179/71d8063290acec8245d7b9622a833d790c24.pdf) som viser at det står for "Simulation Language for Alternative Modeling". Mangler foreløpig Wikipedia-side :)
