### ISSUE TITLE
Feilbehandling - error treatment

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#136]
Dette er vel ikkje medisinsk feilbehandling, sjølv om det får flest treff på første side? For det heiter vel treatment error? (feil behandling vs behandling av feil/når feil oppstår)

**Comment by BioHeidi** [comment]
Jeg synes på trefflisten det ser mest ut som feilsøking (i programmeringskontekst). @knuthe

**Comment by Hypsibius** [comment]
Ja, men fordi den søker meir generelt (bd) får den også med medisinsk feilbehhndling. Oppgi disiplin? Eksempelvis feilbehandling (programmering)?

**Comment by mittinatten** [comment]
Jeg vet ikke helt hva feilbehandling i programmering skulle, vi har jo feilretting/debugging/avlusing som term og feilkorrigerende koder også. Muligens da "exception handling", men da er nok ikke feilbehandling beste term heller. Glemmer jeg noe @knuthe @danmichaelo ?

**Comment by knuthe** [comment]
10 av de 12 postene som har "feilbehandling" er innen data. De to siste medisin. Jeg lager "feilbehandling (medisin)". De andre rettes til "feilretting". Retting er vel måten å behandle feil på.
