### ISSUE TITLE
Solkonstanten

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1360]
Unødvendig å ha både solarkonstanten og solkonstanten som emne?

---
*REAL010596 (Solkonstanten) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010596), [Skosmos](http://data.ub.uio.no/realfagstermer/c010596), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Solkonstanten%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010596)*

**Comment by danmichaelo** [comment]
Definitivt :) En liten kuriositet at Wikipedia på bokmål har artikkel om solkonstanten, mens nynorsk (og SNL) har solarkonstanten. Valgte solarkonstanten som foretrukket term, men det kan jo enkelt byttes om hvis vi finner grunner til det.
