### ISSUE TITLE
Digitale kartsystemer og Kartsystemer

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1362]
Ser ut som disse kan slås sammen. Litteraturbelegget til Kartsystemer handler bare om digitale. Vi har også strengen ` Kartsystemer : Digitale kart`, der `Digitale kart` er brukt feilaktig som *formterm*. Generelt ser det egentlig ut som formtermen Digitale kart er brukt feil.

---
*REAL004919 (Digitale kartsystemer) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004919), [Skosmos](http://data.ub.uio.no/realfagstermer/c004919), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Digitale%20kartsystemer%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL004919)*

**Comment by grosyn** [comment]
DM slo saman Kartsystemer med Digitale kartsystemer. 
Eg endra i katalogpostane som hadde formtermen Digitale kart - dei fekk emnetermen Digitale kartsystemer i staden for. Sletta Digitale kart (eksisterer som henvisning).
