### ISSUE TITLE
Ørretoppdrett

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1365]
![image](https://user-images.githubusercontent.com/42732381/44848883-a62f0900-ac58-11e8-929d-934136cac4ea.png)
![image](https://user-images.githubusercontent.com/42732381/44848962-db3b5b80-ac58-11e8-96bd-39fc9f059a62.png)

Foreslår:
EN Trout selective breeding
EN Trout artificial selection

**Comment by Caroline-A** [comment]
Hei!
Ja, jeg kan gjerne prøve den hvis den er mer direkte. Jeg tror jeg har autoriserte min konto.
Mvh Caroline

**Comment by danmichaelo** [comment]
Beklager at det tok litt tid. Nå har du tilgang:

http://ub-soksed.uio.no/concepts/?view=mapping

Det ligger en liten beskrivelse av studentenes oppgave her hvis du er nysgjerrig:

https://docs.google.com/document/d/1LdbfXSOSQ4Dfum25-JGRMGRQxBordqmzL52GbTwRpZo/edit

Glemte forresten at termene som allerede er korrekturlest er låst, så de må du fremdeles melde fra om her på GitHub. Forhåpentligvis blir ting ryddigere i fremtiden, men vi venter litt på nyheter om Bibsys BARE før vi gjør alt for drastiske endringer.

**Comment by Caroline-A** [comment]
Fint, takk. Jeg har lest dokumenten, veldig nyttig, men jeg vil bare sjekke – må jeg gjøre noe med den «Godkjenne» knapp ved siden av de engelske termene, eller er det bare til å «lagre» når jeg legger noe inn?

**Comment by danmichaelo** [comment]
Det holder å lagre, så kan vi godkjenne. Takk for hjelpen!
