### ISSUE TITLE
Fiskeforvaltning

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1366]
![image](https://user-images.githubusercontent.com/42732381/44850261-e6908600-ac5c-11e8-9166-f38439d79d26.png)
Under Fiskeforvaltning står Fiskeutsetting som alternativ. På Engelsk står:
![image](https://user-images.githubusercontent.com/42732381/44850311-117ada00-ac5d-11e8-9e22-5e9d7b678186.png)

Foreslår "EN Fish stocking" legges til.

**Comment by danmichaelo** [comment]
Takk, lagt til!
