### ISSUE TITLE
Strukturanalyser

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1369]
Er det nødvendig å ha både strukturanalyse og strukturanalyser?

---
*REAL011889 (Strukturanalyser) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011889), [Skosmos](http://data.ub.uio.no/realfagstermer/c011889), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Strukturanalyser%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL011889)*

**Comment by danmichaelo** [comment]
Nei, det synes jeg ikke. Slo sammen og ryddet
