### ISSUE TITLE
Styring

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1370]
Kanskje et litt rart emne med tanke på variasjonen i katalogpostene. 

---
*REAL009961 (Styring) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009961), [Skosmos](http://data.ub.uio.no/realfagstermer/c009961), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Styring%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009961)*

**Comment by danmichaelo** [comment]
Jah! Dette er sånt som henger igjen fra de frie emneordene, men som vi absolutt vil ha vekk!

**Comment by danmichaelo** [comment]
(Alle bøkene hadde bedre emneord)
