### ISSUE TITLE
Syklotomiske kropper

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1371]
Alle tre katalogpostene her er om Cyclotomic fields. Burde emnet egentlig være syklotomiske felt?

---
*REAL002051 (Syklotomiske kropper) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002051), [Skosmos](http://data.ub.uio.no/realfagstermer/c002051), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Syklotomiske%20kropper%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002051)*

**Comment by danmichaelo** [comment]
@TorgunnKarolineMoe ?

**Comment by danmichaelo** [comment]
Never mind @TorgunnKarolineMoe , dette vet jeg jo egentlig, "fields"= "kropper", "felt" brukes ikke. #1373
