### ISSUE TITLE
Synkronstråling

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1372]
Ingen katalogposter på emnet. 

Finger ikke eposten hvor du skrev noe om disse emnene, men fortsetter å melde ifra om de :)

---
*REAL008114 (Synkronstråling) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008114), [Skosmos](http://data.ub.uio.no/realfagstermer/c008114), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Synkronstr%C3%A5ling%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008114)*

**Comment by danmichaelo** [comment]
Helt greit! Denne gjetter jeg er en feilskriving av synkrotronstråling.. har ihvertfall slettet den
