### ISSUE TITLE
Tallkropper

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1373]
Her er samme spørsmål som i går, er felt og kropper det samme?

---
*REAL000491 (Tallkropper) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000491), [Skosmos](http://data.ub.uio.no/realfagstermer/c000491), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Tallkropper%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000491)*

**Comment by danmichaelo** [comment]
Ah, nå skjønte jeg. Svaret er ja: https://no.wikipedia.org/wiki/Kropp_(matematikk)

**Comment by jeanetvi** [comment]
Aha skjønner:) 
Matte er ikke faget mitt, men da lærte jeg noe nytt
