### ISSUE TITLE
Tilgroing

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1376]
Jeg skjønner ikke dette emnet. 

---
*REAL005818 (Tilgroing) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005818), [Skosmos](http://data.ub.uio.no/realfagstermer/c005818), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Tilgroing%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL005818)*

**Comment by Hypsibius** [comment]
!!!

![image](https://user-images.githubusercontent.com/9350370/44981683-9cb4e200-af73-11e8-80a2-8d64dca27efa.png)
 
Samanklikne også med påvekst 

![image](https://user-images.githubusercontent.com/9350370/44981720-bf46fb00-af73-11e8-8fa5-b21dc5eafb73.png)
 og 

![image](https://user-images.githubusercontent.com/9350370/44981757-d84fac00-af73-11e8-86b8-0fe59d41c4ad.png)

![image](https://user-images.githubusercontent.com/9350370/44981805-f9b09800-af73-11e8-968c-09ec9eec8a01.png)

I det tilfellet som faktisk har fått denne termen, skulle ein heller brukt påvekst. I andre tilfelle kan tilgroing dekkjast primært av gjengroing, sekundært av suksessjon. Foreslår: Slå saman m gjengroing, som blir hovudinnførsel. Den aktuelle posten får i staden 'Påvekst'. Kg kva gjer vi med gjengroing = EN: reforestation? Det siste oppfattar eg som aktiv planting, imotsetning til gjengroing, som er typ setervollar som blir skogkledd etter år utan beite/slått.....

**Comment by Hypsibius** [comment]
@Caroline-A ?

**Comment by danmichaelo** [comment]
Gjort:
1) flyttet det ene dokumentet om "Tilvekst" til "Påvekst".
2) slått sammen `Gjengroing BF Tilgroing` og endret engelsk til `Regrowth BF Reforestation, Regeneration`

Ok?

---

> Re Påvekst/Begroing EN termer - Påvekst kan brukes også for å beskrive "epiphytism" (e.g. påvekstalger, [Thesis UiO](https://www.duo.uio.no/handle/10852/38823)). Det er en vanlig term å søke med i marinbiologi. Men da blir det komplisert med alle alternativer (epibiotic, epilithic etc.) 

Kanskje legge inn SO? `Epifytter SO Påvekst`? Eller blir det feil?

**Comment by Caroline-A** [comment]
Jeg er ikke sikkert om den se-også - kanskje trenger innspill fra en nordman som er mer kjent med bruk av "påvekst" enn meg :) @Hypsibius 

Men jeg foreslår at "påvekstalger" legges til epifytter uansett (i.e. _Epifytter BF Påvekstalger_)

Lurer på om vi burde også legge til "NB epibiota / EN epibionts" som BF term et sted, men jeg vet ikke om det er best som term under påvekst eller som hovedterm med BF epifytter BF påvekstalger.

**Comment by Hypsibius** [comment]
Hmmm, trur det blir minst forvirrande om vi samlar det som 

Påvekst En Epibiota En Epiphytes En Epizoic organisms En Epilithes BF fouling etc EN BF Epibionter BF Epizoonter BF Epifytter BF Epilitter

Om vi deler opp, blir det ei kompleks matrise og veldig få postar på kvar. Samme organisme kan vekse på stein, algar og dyr, same plante kan ha både algar og dyr veksande på seg....

**Comment by Caroline-A** [comment]
Er enig. + BF påvekstalger, og termene som ligge allerede i soksed (EN Biofouling, Fouling, Biological fouling) :)

**Comment by danmichaelo** [comment]
Ok, here we go: http://data.ub.uio.no/realfagstermer/c031465

Ser nynorskformene ok ut? Var ikke sikker på endelsen på Epifyttar, Epilittar, Epizoontar, Epibiontar..

```
Påvekst
BF Påvekstorganismer
BF Påvekstalger
BF Begroing
BF Epifytter
BF Epilitter
BF Epizoonter
BF Epibionter
NN Påvekst
NN Påvekstorganismar
NN Påvekstalgar
NN Begroing
NN Epifyttar
NN Epilittar
NN Epizoontar
NN Epibiontar
EN Fouling
EN Biofouling
EN Biological fouling
EN Epiphytes
EN Epilithes
EN Epizoic organisms
EN Epibiota
DE vekst av mikroorganismer, planter, alger eller dyr på fuktige overflater
```

**Comment by Hypsibius** [comment]
Nynorsken ser heilt fin ut, den! Nokre ord trur eg til og med er alldeles splitter nye, men likevel korrekt bygde 😍
