### ISSUE TITLE
Tilstander

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1377]
Hvordan håndterer man at ulike emner på norsk får samme engelske oversettelse, 
slik som tilstand og state som begge blir oversatt state, men med ulik betydning?

---
*REAL003000 (Tilstander) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003000), [Skosmos](http://data.ub.uio.no/realfagstermer/c003000), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Tilstander%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL003000)*

**Comment by Hypsibius** [comment]
Eksempelvis tilstander (medisin) vs Tilstander (Kjemi)?

**Comment by danmichaelo** [comment]
Det kan håndteres enten md kvalifiserende parentes; "States (political entities)", eller utbrodering; "Chemical states". Meen er [Tilstander](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003000) et bra emneord? Det kan jo bety nesten hva som helst. To av de fire bøkene har dessuten det mer spesifikke emneordet "Kjemisk tilstand", så jeg er ganske sikker på at vi kan slette "Tilstander".

**Comment by Hypsibius** [comment]
Medisinsk ei omsetjng av 'disorders'. Skulle ønske vi hadde ein betre term

**Comment by danmichaelo** [comment]
Slettet Tilstander. Trenger vi noe for medisinske tilstander i fremtiden kan vi jo opprette den da.
