### ISSUE TITLE
Tropevegetasjon

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1378]
Det er kanskje ikke nødvendig å både ha emnet tropevegetasjon og tropisk vegetasjon da det omhandler det samme. 

---
*REAL010211 (Tropevegetasjon) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010211), [Skosmos](http://data.ub.uio.no/realfagstermer/c010211), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Tropevegetasjon%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010211)*

**Comment by Hypsibius** [comment]
Slå saman, m Tropisk vegetasjon som hovudinnførsel

**Comment by danmichaelo** [comment]
Gjort!
