### ISSUE TITLE
... and the list goes on....

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#138]
Altså, om de for eit øyeblikk ignorererer at alle ø-ane er blitt borte og at 'fi' blir til kvinnekamp: For meg er det ikkje logisk at alle desse skal vere samansette ord, men er heller ikkje sikker på kvar det er mest logisk å setje grensa og lage strengar? Kan jo lukke auene og late som ingenting, men dette er vel typisk sånt som evt genererer fleire omsetjingstimar for nynorskingane, om det ikkje blir rydda først?

Ferskvannsalger
Ferskvannsavsetninger , se Ferskvannssedimenter
Ferskvannsbiologi
Ferskvannsbltdyr
Ferskvannsdyr, se Ferskvannsfauna
Ferskvannsfauna
Ferskvannssk, se Ferskvannssker
Ferskvannsske
Ferskvannssker
Ferskvannsforurensning (Freshwater pollution)
Ferskvannsinsekter
Ferskvannskreps
Ferskvannslaguner

**Comment by BioHeidi** [comment]
Dette er et område hvor vi trenger at strenger kan peke til et synonym. For eksempel:
Insekter : Ferskvann BF Ferskvannsinsekter

Det er mange andre områder hvor det hadde vært greit. F.eks. kunne vi få ryddet i fugletermene:
Naturvern : Fugler (eller omvendt) BF Fuglevern

Og i -undervisningstermene.

Kan vi få til det? @bibliomari @knuthe

**Comment by knuthe** [comment]
Det burde kunne la seg gjøre. Må bare la det synke inn litt for å identifisere strukturelle problemer først.

**Comment by danmichaelo** [comment]
Kunne dette vært en muuhulighet?

    Ferskvann SO Ferskvannsinsekter
    Insekter UT Ferskvannsinsekter

    Fugler SO Fuglevern
    Naturvern UT Fuglevern

**Comment by BioHeidi** [comment]
Det løser ikke problemet egentlig? Det vil bli fruktelig mange SO-er på Fugler og på Ferskvann f.eks.

Hva er UT?

**Comment by danmichaelo** [comment]
Underordnet term – vi skal jo snart få #73 

Fruktelig mange SO-er er vel ikke så mye værre enn fruktelig mange strenger? Men kanskje det holder med bare UT?

**Comment by BioHeidi** [comment]
Med min begrensede hjernekapasitet klarer jeg ikke å rydde Realfagstermene med tanke på fremtidig hierarki. For det har jo innvirkning på både frasetermer og $a $b-strenger generelt, men vi lager da fortsatt disse?

**Comment by BioHeidi** [comment]
Legger inn her at dersom vi får til en løsning på dette kan vi også bruke samme ryddemåte på Historisk-,  Historiske-, -historie. Iallefall prøve å få til konsekvens.

**Comment by Hypsibius** [comment]
Hjelp! Mi forskerutdanning har gjort det umogeleg for meg å tenke strengt hierarkisk. Eg tenker i matriser, i meir eller mindre fullt faktorielt design. Eg klarer med mi beste evne ikkje å sjå kvifor ferskvann: innsekter skulle vere meir eller mindre logisk eller ha forrang framfor insekter: ferskvann. På same måte som eg ikkje ser kvifor nokon av echinodermata: osmoregulering og osmoregulering:echinodermata skulle ha forrang over den andre. Var det ikkje for å unngå slike ting at ein oppfann hypertekst? Og finst det ikkje bedre måtar å behandle dette på i databasar enn hierarki? #flatstruktur #småanarkistisketendensar

**Comment by danmichaelo** [comment]
Tenker "Ferskvannsinsekter" ("Insekter som lever i ferskvann") som en underklasse av "Insekter" fordi alle "Ferskvannsinsekter" er "Insekter", men ingen er "Ferskvann". Det kan fortsatt være en relasjon mellom "Ferskvannsinsekter" og "Ferskvann", men da ikke-hierarkisk – f.eks. en se-også-relasjon.

Hvis "Echinodermata : osmoregulering" uttrykker noe sånt som "Osmoregulering hos echinodermata"(?) vil jeg tilsv. si at det er en underklasse av "Osmoregulering".

(men det er garantert masse strenger som ikke lar seg angripe på denne måten…)

**Comment by knuthe** [comment]
Et tema på møtet på fredag 27/2 kan være hvor mange relasjonstyper vi vil ha i systemet. I utgangspunktet var det enkelt: se-også-relasjoner og "synonym"-kontroll. Nå er overordnet/underordnet på vei, uten at type hierarki spesifiseres (se tidligere diskusjon om generiske, partitive etc relasjoner). 

Vi må ta ett skritt av gangen. Det fins en grense for hvor langt vi skal utvikle programvare selv. Roald/Sonja - i all sin primitivitet - fungerer greit mot blå-bibsys og bibsys ask. Men det kommer nye systemer vi må forholde oss til :-) Da kan vi se etter andre løsninger.
