### ISSUE TITLE
Personer

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1384]
Dette er et litt rart emne. Spesielt når den kun brukes på en katalogpost. 

---
*REAL010407 (Personer) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010407), [Skosmos](http://data.ub.uio.no/realfagstermer/c010407), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Personer%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010407)*

**Comment by danmichaelo** [comment]
Slettet
