### ISSUE TITLE
Konodonter

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1387]
Er det det samme som Conodonter?  (to ulike realfagstermer)

---
*REAL000456 (Konodonter) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000456), [Skosmos](http://data.ub.uio.no/realfagstermer/c000456), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Konodonter%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000456)*

**Comment by danmichaelo** [comment]
Takk, slått sammen! Begge skrivemåtene var i bruk på SNL, så jeg tipset fagansvarlig der også. Ikke helt sikker på hvilken som er best, men både WP og SNL hadde "con" som hovedoppslag, så gikk for den selv om "kon" virker som bedre norsk når navnet kommer fra "konisk"..
