### ISSUE TITLE
Bentosalger + Fastsittende alger

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1388]
![image](https://user-images.githubusercontent.com/42732381/45552733-32812480-b832-11e8-971d-f71ffae93368.png)

![image](https://user-images.githubusercontent.com/42732381/45552755-3dd45000-b832-11e8-9d16-fdb983146535.png)

Foreslår sammenslåing, med bentosalger som hovedterm? Fastsittende alger har bare 3 dokumenter.

**Comment by BioHeidi** [comment]
Ja, enig!

**Comment by danmichaelo** [comment]
Gjort!
