### ISSUE TITLE
Fett - litt termslanking

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#139]
Treng vi i tillegg til termen 'fett' også 'fettprodukter', 'fettstoffer' og 'fettsyrer', eller kan vi slanke bort nokre av desse?

Er også usikker på kva som ligg i termen 'fettdannelse', ikkje minst sidan den einaste bruken i BIBSYS er på russisk og frå 1909 ;-)

**Comment by danmichaelo** [comment]
Jeg begynte med å slette `Fett : Konferanser` :D 

Så flettet jeg `Fettprodukter`, `Fettstoffer`og `Fettdannelse` inn i `Fett`. Men `Fettsyrer` beholdt jeg, den vil nok kjemikerne ha som egen term. La også på en `SO Lipider`
