### ISSUE TITLE
Byggesaker

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1392]
Jeg finner ingen god oversettelse og dette brukes kun på en katalogpost. Går det an å endre eller slette emnet? 

---
*REAL001603 (Byggesaker) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c001603), [Skosmos](http://data.ub.uio.no/realfagstermer/c001603), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Byggesaker%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL001603)*

**Comment by danmichaelo** [comment]
Slettet denne. Det ligger i periferien av vokabularet vårt og det virket ikke som det var det mest sentrale emnet for dokumentet det var brukt på.
