### ISSUE TITLE
Falklandskarakara

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1393]
Det kan se ut som at Falklandskarakara ike er riktig navn på arten, men at den betegnes som Brungumpkarakara. Det latinske navnet stemmer ihvertfall. 

---
*REAL010717 (Falklandskarakara) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010717), [Skosmos](http://data.ub.uio.no/realfagstermer/c010717), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Falklandskarakara%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010717)*

**Comment by danmichaelo** [comment]
@realfagstermer/bio

**Comment by Hypsibius** [comment]
Antar det er lista her du tar utgangspunkt i?  http://www.birdlife.no/fuglekunnskap/nyheter/?id=1988

**Comment by danmichaelo** [comment]
Sant, ser ut som Falklandkarakara er navnet på tysk, men ikke på norsk, så fjerner den.
