### ISSUE TITLE
Fangstkulturer

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1394]
Finner ingen god oversettelse og finnes kun på en post som i stor grad er dekket av de andre emnene. 

---
*REAL003891 (Fangstkulturer) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003891), [Skosmos](http://data.ub.uio.no/realfagstermer/c003891), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Fangstkulturer%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL003891)*

**Comment by BioHeidi** [comment]
Kan slettes!

**Comment by danmichaelo** [comment]
Slettet!
