### ISSUE TITLE
Fastsittende alger

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1395]
Hva tror dere er Benthic algae en ok oversettelse? 
Er vel egentlig en definisjon på alger som lever på bunnen, men det vil vel i stor grad si at de også "sitter fast". 

Det er så lite vitenskapelig med  "permanent algae" eller noe slikt noe. 

---
*REAL008110 (Fastsittende alger) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008110), [Skosmos](http://data.ub.uio.no/realfagstermer/c008110), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Fastsittende%20alger%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008110)*

**Comment by danmichaelo** [comment]
Oi, nå ser jeg at @Caroline-A tok opp akkurat fastsittende alger for 3 dager siden i #1388 :) Ser sammenslåingsforslaget ok ut?

**Comment by jeanetvi** [comment]
Hun og jeg var ihvertfall enige :)

**Comment by jeanetvi** [comment]
Ops, var ikke meningen å lukke tråden:P

**Comment by Hypsibius** [comment]
Enig!

**Comment by danmichaelo** [comment]
Da er de slått sammen: `Bentosalger BF Fastsittende alger`
