### ISSUE TITLE
Fracking/hydraulisk frakturering

### ISSUE THREAD

**Issue by ken075** [realfagstermer/realfagstermer#1396]
Hei, er ny fagreferent for geofag og teknologi på UiB (tatt over for Marta Lorenz). Foreslår nytt emneord i forbindelse med denne boken:

[The fracking debate : the risks, benefits, and uncertainties of the shale revolution](https://www.thefrackingdebate.com/)

usikker på om det engelske ordet "fracking" eller oversettelsen "hydraulisk frakturering" blir riktig?

**Comment by danmichaelo** [comment]
Hei, velkommen skal du være :tada: 

Litt overraskende at vi ikke allerede hadde det som emneord, men har opprettet det nå ihvertfall. La inn "Hydraulisk frakturering" som foretrukket term og "Fracking" og "Hydraulisk oppsprekking" som alternative termer. Alle blir da søkbare i Oria og Emnesøk.

https://data.ub.uio.no/skosmos/realfagstermer/nb/page/c032039 (virker i morgen)
