### ISSUE TITLE
Innhøsting + Høsting

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1398]
![image](https://user-images.githubusercontent.com/42732381/45620687-fb06b800-ba7d-11e8-873c-121509201e2f.png)
![image](https://user-images.githubusercontent.com/42732381/45620697-04902000-ba7e-11e8-8669-ab2ce5ee841d.png)

Jeg har hørte litt med Hege og forstår at disse er ikke helt det samme konseptet. Men lurte på om de er så like at de burde sammenslåes? Foreslår engelsk oversettelse som harvesting, gathering, foraging.

**Comment by BioHeidi** [comment]
Tror egentlig godt vi kan bruke begrepet Høsting på alt det vi har av litteratur, men BF Innhøsting hvis noen skulle være spesielt opptatt av det ;)

**Comment by Hypsibius** [comment]
Enig i samanslåing. Tenkjer at hausting er vidare, og dekkjer alle tilfelle av innhausting? Ellers, dette understrekar behovet for å koordinere nynorsk- og bokmålsordbøkene (eit arbeid som no er i gang!)

![image](https://user-images.githubusercontent.com/9350370/45674889-4e384380-bb2e-11e8-9e41-0a49a3e71678.png)

![image](https://user-images.githubusercontent.com/9350370/45674930-63ad6d80-bb2e-11e8-8b7d-5b449e50eda9.png)

**Comment by danmichaelo** [comment]
Slått sammen og tilføyd engelsk!
