### ISSUE TITLE
Spiselige alger?

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1399]
Vi har termer Spiselige planter (REAL000934) og  Matsopper (REAL013231). 

Foreslår: Spiselige alger; NN Etande algar, Etelege algar, Spiselige algar (??); BF: Matalger, spiselige makroalger; EN: Edible macroalgae, edible seaweeds, sea vegetables.

Det er stor interesse nå om høsting av makroalger til mat, enten i anlegg eller høsting fra natur. Lurte på om spiselige alger kunne brukes til disse typer verk. Kom på det med [denne ](http://bora.uib.no/handle/1956/18055 )- den er ikke direkte om høsting, men det er relevant at algen som hun studerte er spiselig.

**Comment by Hypsibius** [comment]
NN Etande :-)

**Comment by danmichaelo** [comment]
Etande er sjølvsagt med :)
