### ISSUE TITLE
Fetus - embryoer - fostere

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#140]
Pr i dag har vi 'fetus' som term (feil form uansett), men ikkje det norske 'fostere'. Desse to termane brukast vel omlag på same måten, men er ikkje heilt utbyttbare med 'embryoer', sjølv om overgangen er glidande. Kan vi likevel samle desse? Evt samordne med 'embryologi'?

Foreslår fostere, BF fetuses

Eller skal vi gå lenger?

**Comment by BioHeidi** [comment]
Jeg tror vi kan legge alt inn i Embryologi.

**Comment by Hypsibius** [comment]
Skal vi konkludere med det, då, at vi legg alt inn i embryologi?

**Comment by BioHeidi** [comment]
Jepp

**Comment by bibliomari** [comment]
Gjort
