### ISSUE TITLE
CO2-foam/CO2-skum ny realfagsterm?

### ISSUE THREAD

**Issue by ken075** [realfagstermer/realfagstermer#1400]
Jeg har kommet borti ganske mange masteroppgaver i reservoarfysikk som omhandler begrepet "CO2 (karbondioksid) foam" 

(Til informasjon så dreier det seg altså om et skum bestående av karbondioksid og såpe som er med på øke utvinningsgraden av olje)

Foreslår derfor CO2-skum som ny realfagsterm. Tanker?

Mvh,
Kjersti Enerstvedt

**Comment by danmichaelo** [comment]
CO2-injeksjon blir kanskje litt for overordnet? Ser at vi mangler den. Men vi kan godt opprette CO2-skum også! Det kan vel uansett være en "se også"-henvisning til "Økt oljeutvinning"?

**Comment by ken075** [comment]
Enig i alt!

**Comment by danmichaelo** [comment]
Altså, du vil ha både CO2-injeksjon og CO2-skum?

**Comment by ken075** [comment]
Jeg tenker at begge er ok å ha. CO2-skum er mer spesifikt, men det er tydeligvis en term som er mye brukt i fagmiljøet her i Bergen i hvert fall.
