### ISSUE TITLE
Nordishavet

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1402]
![image](https://user-images.githubusercontent.com/42732381/45736916-adf52400-bbec-11e8-8ddd-874e34fca91a.png)
![image](https://user-images.githubusercontent.com/42732381/45736928-b5b4c880-bbec-11e8-9d89-b8515b27f3a7.png)

Jeg vet ikke om dette er korrekt - Nordishavet ekisterer både som emne og som sted?

**Comment by danmichaelo** [comment]
Oi, nei, slik har vi ikke pleid å skille. Slår de sammen så det bare blir en stedsterm.
