### ISSUE TITLE
De Nordiske hav

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1403]
Det er flere dokumnenter i BORA som har [de Nordiske hav](https://snl.no/De_nordiske_hav) som studieområde (e.g. [1](http://bora.uib.no/handle/1956/18087), [2](https://bora.uib.no/handle/1956/18088)). Tenkte den kunne være opprettet som en stedsterm?
EN: The Nordic seas

**Comment by danmichaelo** [comment]
Oppretta :ocean: 

```
De nordiske hav
BF Nordiske hav
NN De nordiske hav
NN Nordiske hav
EN Nordic seas
```

WP: https://en.wikipedia.org/wiki/Nordic_Seas
