### ISSUE TITLE
Feller + Dyrefeller

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1405]
![image](https://user-images.githubusercontent.com/42732381/45742552-84db9000-bbfa-11e8-9bd9-ac1abce92e2c.png)
![image](https://user-images.githubusercontent.com/42732381/45742781-04695f00-bbfb-11e8-93fa-38e54650dde2.png)

Var litt usikker på hvilken er best å bruke i biologisk sammenheng. Jeg kan se at "feller" er brukt med dok som er biologiske (e.g. insektfeller) og fysisk (e.g. sediment traps). 

Obs. vi har også fangstmetoder (REAL008837). Kanskje trenger innspill from en nordmann :)

Hvis dyrefeller er beholdt, jeg foreslår å utfleske den med:
BF: Fangstfeller
BF: [Lysfeller ](https://no.wikipedia.org/wiki/Lysfelle)(med tanke at jeg jobbe med [denne ](https://bora.uib.no/handle/1956/18095)nå)
EN: Light traps

**Comment by Hypsibius** [comment]
Så lenge vi er konsistente og ikkje snakkar om 'furs'

😳

**Comment by danmichaelo** [comment]
Slo de sammen som

```
Feller
BF Dyrefeller
BF Fangstfeller
BF Lysfeller
...
```

Skilte ut de to dokumentene som handlet om sedimentfeller.

(Holdt meg unna Ektefeller)
