### ISSUE TITLE
Ny realfagsterm: protonterapi ?

### ISSUE THREAD

**Issue by ken075** [realfagstermer/realfagstermer#1406]
Foreslår at "protonterapi" blir en ny realfagsterm

**Comment by danmichaelo** [comment]
Lagt til, men med Protonbehandling som foretrukket term, siden det er det de har valgt i [norske MeSH](http://mesh.uia.no/). Og Strålebehandling som overordnet.

```
Protonbehandling
BF Protonterapi
NN Protonbehandling
NN Protonterapi
OT Strålebehandling
EN Proton therapy
```
