### ISSUE TITLE
Senking

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1408]
Litt rart emne på denne ene katalogposten. Tipper det kanskje er om å senke kolestrol eller noe slikt, men er ikke helt intuitivt.

---
*REAL002611 (Senking) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002611), [Skosmos](http://data.ub.uio.no/realfagstermer/c002611), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Senking%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002611)*

**Comment by jeanetvi** [comment]
Jo det hørstes sikkert ut som en mye bedre forklaring! 
Men er fortsatt ikke sikker på om det er et godt emne på en enkelt katalogpost.

**Comment by Hypsibius** [comment]
Enig.

**Comment by danmichaelo** [comment]
Sletta
