### ISSUE TITLE
Hausdorff-rom

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1409]
En liten skrivefeil her? s75NM03423eparated space

---
*REAL006851 (Hausdorff-rom) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006851), [Skosmos](http://data.ub.uio.no/realfagstermer/c006851), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hausdorff-rom%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL006851)*

**Comment by danmichaelo** [comment]
Ops, fiksa!
