### ISSUE TITLE
Strengeforslag: Kryptografi : Matematikk

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#141]
belegg: http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS121199703&vid=UBB

Edit: dewey 005.820151

**Comment by grosyn** [comment]
Strengar er ikkje lenger i bruk, så eg lukkar saka.
