### ISSUE TITLE
Pelagialsonen

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1410]
Vi har mesopelagialsonen men ikkje pelagialsonen!

![image](https://user-images.githubusercontent.com/9350370/46002196-ad0d3800-c0ad-11e8-9cbd-0253768718da.png)

Foreslår (etter mønster frå mesopelagialen): 

Pelagialsonen BF Pelagialsona Perlagialen Pelagial sone  NN Pelagialsona Pelagialen En  Pelagic Zone

**Comment by Hypsibius** [comment]
Aktuelt dokument: https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71515631300002201&context=L&vid=UBB&search_scope=default_scope&tab=default_tab&lang=no_NO

**Comment by danmichaelo** [comment]
Opprettet! Vi har et par termer som begynner med "Pelagisk *" (fangst, fauna, vegetasjon), er det noen av dem som kan slås sammen?

**Comment by Caroline-A** [comment]
Jeg synes Pelagisk fauna, sekkdyr, reker kunne stå som separate emner. 

Pelagisk fangst er kanskje unødvendig? Det er bare brukt på [en dokument](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc005446), og jeg synes den er bedre dekket av hvalfangst enn av pelagisk fangst. 

Pelagisk vegetasjon er jeg ikke helt sikkert om.  Jeg tror ikke at det er en veldig brukt term. [Dokumentet den er brukt på i Oria ](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc004317)er om phytoplankton, og jeg synes dette emneord kunne brukes istedenfor. Det eneste situasjon jeg kan tenke meg at pelagisk vegetasjon ville har være mest aktuellt er på dokumenter om "floating seaweed rafts" eller lignende. Men vi har ikke noe sånt, som jeg kan se.

**Comment by danmichaelo** [comment]
Takk! Da slettet jeg pelagisk fangst og vegetasjon (La på Planteplankton/phytoplankton på dokumentet)
