### ISSUE TITLE
Algeoppblomstringer

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1411]
![image](https://user-images.githubusercontent.com/42732381/46084118-2fc3ef00-c1a3-11e8-80aa-2519eac7b43e.png)
![image](https://user-images.githubusercontent.com/42732381/46084136-3a7e8400-c1a3-11e8-89fa-1e51a6be24af.png)

Oversettelsen er låst, men jeg vil foreslå flere engelske termer for å dekke alt at man ville søker etter. 

EN: Red tides, Brown tides, [spring blooms](https://en.wikipedia.org/wiki/Spring_bloom), [harmful algal blooms](https://en.wikipedia.org/wiki/Harmful_algal_bloom)

**Comment by danmichaelo** [comment]
Supert :grinning:  Lagt til
