### ISSUE TITLE
Lego

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1414]
Skal denne mappes? Korporasjon?

---
*REAL010179 (Lego) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010179), [Skosmos](http://data.ub.uio.no/realfagstermer/c010179), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Lego%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010179)*

**Comment by danmichaelo** [comment]
Bøkene handler om produktet lego, ikke selskapet lego, så jeg tenker at det kanskje ikke er korporasjon. Men kan ta feil :/

Jfr. skillet mellom [LEGO](https://www.wikidata.org/wiki/Q170484) (leketøy og merkenavn) og [Lego Group](https://www.wikidata.org/wiki/Q1063455) (selskap) på Wikidata.
