### ISSUE TITLE
Wikipedia

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1415]
Dette er vel en korporasjon? Mappes ikke?

---
*REAL007943 (Wikipedia) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007943), [Skosmos](http://data.ub.uio.no/realfagstermer/c007943), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Wikipedia%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL007943)*

**Comment by danmichaelo** [comment]
Mm, kan flytte til BARE: https://authority.bibsys.no/authority/rest/authorities/v2/html/11062550

**Comment by danmichaelo** [comment]
Gjort:
```
almar --diffs replace \
  '650 #7 $$a Wikipedia $$2 noubomn' \
  '610 27 $$a Wikipedia $$2 bare'
```
