### ISSUE TITLE
Smittevernloven

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1416]
Enkeltlover hører vel ikke inn som Real-term? 110 Norge - Smittevernloven, ville jeg tenke

---
*REAL008269 (Smittevernloven) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008269), [Skosmos](http://data.ub.uio.no/realfagstermer/c008269), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Smittevernloven%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008269)*

**Comment by danmichaelo** [comment]
Hm, finner den i LC: http://viaf.org/processed/LC%7Cn%20%2097053664
men ikke i BARE, så da må vi vel opprette BARE-post. Det husker jeg ikke hvordan man gjorde

**Comment by vibekelundetrae** [comment]
Regner med at dere tar dere av dette.

Vibeke

**Comment by danmichaelo** [comment]
> Regner med at dere tar dere av dette. Vibeke

Ja, såklart :)
