### ISSUE TITLE
Samfunnsøkologi

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1417]
![image](https://user-images.githubusercontent.com/42732381/46275617-dd495080-c55d-11e8-8378-d5b6c620281b.png)

Den har vært oversatt (låst) som "Socioecology", men jeg synes det treffer ikke helt... som jeg forstår det [har socioecology mer fokus på social atferd](http://www.oxfordbibliographies.com/view/document/obo-9780199830060/obo-9780199830060-0045.xml), mens samfunnsøkologi er bredere, og korresponderer bedre med "[Community ecology](https://en.wikipedia.org/wiki/Community_(ecology))".

**Comment by danmichaelo** [comment]
Takk, her har det nok gått litt fort i korrekturlesingen! Beholdt `Synecology` som alternativ term.
