### ISSUE TITLE
Mikrobiell genetikk - Mikrobiologisk genetikk

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1418]
![image](https://user-images.githubusercontent.com/42732381/46276064-49788400-c55f-11e8-82f5-072ef21c0379.png)
![image](https://user-images.githubusercontent.com/42732381/46276093-572e0980-c55f-11e8-93b7-16e5397ffdd3.png)

Sammenslåes?

Edit: Beklager, glemte å søke først. Ser at [dere har diskuterte dette før](https://github.com/realfagstermer/realfagstermer/issues/130)... bruker vi bare streng nå da?

**Comment by danmichaelo** [comment]
Slo sammen `Mikrobiell genetikk BF Mikrobiologisk genetikk`. Det er jo uansett en forbedring, uavh. av om @BioHeidi evt. strengifiserer mer i fremtiden :)
