### ISSUE TITLE
Mikrobiell teknikk - Mikrobiell bioteknologi

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1419]
Med henvisning til [min forrige Issue](https://github.com/realfagstermer/realfagstermer/issues/1418), vil jeg også forelså at disse sammenslåes, med mindre dere har andre planer for disse "mikrobiell" termer.  
![image](https://user-images.githubusercontent.com/42732381/46276472-7b3e1a80-c560-11e8-844a-f897c820a36d.png)
![image](https://user-images.githubusercontent.com/42732381/46276484-85601900-c560-11e8-97f6-aa4583a40fbc.png)

**Comment by danmichaelo** [comment]
Slått sammen som `Mikrobiell bioteknologi BF Mikrobiell teknikk`
