### ISSUE TITLE
Miljøindikatorer/Økologiske indikatorer

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#142]
Noen grunn til ikke å slå sammen disse, @BioHeidi og @Hypsibius ? Si gjerne hva som er foretrukken term.

I det hele tatt en fantastisk liste med miljø- ... Jeg gjør så godt jeg kan grovkornet, men det er garantert noe igjen som dere kan pusle med i deres seniorarbeidsliv 30 år fram i tid.

**Comment by Hypsibius** [comment]
Jo men så blir vi ikje alrbeidsledige :-P Miljøindikatorer kling best, og ja, slå saman!

**Comment by bibliomari** [comment]
:D

**Comment by BioHeidi** [comment]
Tar denne opp igjen for å si at du godt kan slå sammen med dette disse termene:
Bioindikatorer
Indikatorarter
Indikatorer

Har sjekket trefflisten og de er brukt likt. Men spesielt de to første er begreper som brukes, så de er viktig å ha med som BF.

**Comment by Hypsibius** [comment]
I'm all over it :-)

**Comment by BioHeidi** [comment]
Jeg har slått sammen, men vil egentlig helst ha Bioindikatorer som foretrukken term her. Er det ok at jeg snur på det, Bioindikatorer BF Miljøindikatorer, Indikatorarter, Økologiske indikatorer? Sletter termen Indikatorer.

**Comment by Hypsibius** [comment]
Kva skjedde der, blei du overkøyr, @BioHeidi? For det blei køyrt ein lokar på det opprinnelege forslaget, som eg pliktskyldigst fugte ;-)

Kan forsåvidt pliktstkyldigst køyre den tilbake...

**Comment by grosyn** [comment]
@BioHeidi 
Skal eg endra på det, slik at det blir slik du beskriv her: "Jeg har slått sammen, men vil egentlig helst ha Bioindikatorer som foretrukken term her. Er det ok at jeg snur på det, Bioindikatorer BF Miljøindikatorer, Indikatorarter, Økologiske indikatorer? Sletter termen Indikatorer." ?

**Comment by grosyn** [comment]
Då er dette gjort :-)
