### ISSUE TITLE
Marine reservater - Marine vernområde

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1420]
![image](https://user-images.githubusercontent.com/42732381/46292621-abea7800-c591-11e8-94c5-c9ee2aedb579.png)
![image](https://user-images.githubusercontent.com/42732381/46292646-b6a50d00-c591-11e8-8d7e-6c90e45b631b.png)

Sammenslåes? Fant en oppsummering av termer brukt i Norge [her](http://www.miljodirektoratet.no/no/Tema/Verneomrader/Verneformer/), det virker som "naturreservater" og "marine vernområder" er veldig likt, bare at 'reservater' brukes på land.

**Comment by danmichaelo** [comment]
Slått sammen som `Marine verneområder BF marine reservater` :ocean:
