### ISSUE TITLE
Ekstremofiler - Ekstremofile mikroorganismer

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1421]
![image](https://user-images.githubusercontent.com/42732381/46293086-c53ff400-c592-11e8-8699-99d01e3f9808.png)
![image](https://user-images.githubusercontent.com/42732381/46293590-4055da00-c594-11e8-847a-1af51b90611a.png)

Begge to er oversatt (låst) til det samme i søksed ("EN Extremophiles"). De kunne sammenslåes, eller burde "ekstremofile mikroorganismer" oversettes som noe annet (e.g. "EN extremophile microorganisms" "EN extremophillic microorganisms" "EN Extremophillic bacteria"). Jeg synes at de kanskje burde sammenslåes, og så kan man lage streng hvis man vil?

**Comment by Hypsibius** [comment]
Enig m C

**Comment by danmichaelo** [comment]
Slått sammen som `Ekstremofiler BF Ekstremofile organismer`
