### ISSUE TITLE
Viltloven

### ISSUE THREAD

**Issue by eirillsh** [realfagstermer/realfagstermer#1422]
Gir dette mening å oversette til engelsk? Dette er jo en spesifikk lov i det norske lovverket

---
*REAL004782 (Viltloven) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004782), [Skosmos](http://data.ub.uio.no/realfagstermer/c004782), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Viltloven%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL004782)*

**Comment by danmichaelo** [comment]
Nei. Og vi kan flytte den til BARE, jfr. #1416 Smittevernloven
