### ISSUE TITLE
Vitenskapsakademiet

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1425]
Dersom denne termen viser til http://www.dnva.no/ Det Norske vitenskapsakademi, bør vel heller denne flyttes til et 610- emne?

---
*REAL003508 (Vitenskapsakademiet) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003508), [Skosmos](http://data.ub.uio.no/realfagstermer/c003508), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Vitenskapsakademiet%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL003508)*

**Comment by danmichaelo** [comment]
Jeg tenkte også det, men når jeg ser på katalogpostene nå så er jo faktisk alle bøkene om akademier i andre land, så da skal den nok heller slås sammen med `Vitenskapsakademier`
