### ISSUE TITLE
Fiber

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1426]
Foreslår hovedinnførsel på "fibre" som er flertall i ubestemt form.

---
*REAL012635 (Fiber) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c012635), [Skosmos](http://data.ub.uio.no/realfagstermer/c012635), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Fiber%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL012635)*

**Comment by danmichaelo** [comment]
Endrer! Også Karbonfibre, Muskelfibre og Nanofibre.

**Comment by danmichaelo** [comment]
Fjernet også "Fiber" fra bøkene om "Fiberoptikk"

**Comment by danmichaelo** [comment]
Etter å ha ryddet vekk Fiberoptikk og Kostfiber var det faktisk ikke noe igjen, så da slettet jeg "Fiber" :)
