### ISSUE TITLE
Forslag til ny realfagsterm: Polymer flooding?

### ISSUE THREAD

**Issue by ken075** [realfagstermer/realfagstermer#1427]
Foreslår "polymer flooding" som ny realfagsterm i forbindelse med økt oljeutvinning (EOR). Usikker på hva norsk term bør være? 

"Polymer flooding
Polymer flooding consists in mixing long chain polymer molecules with the injected water in order to increase the water viscosity. This method improves the vertical and areal sweep efficiency as a consequence of improving the water/oil Mobility ratio" hentet fra Wikipedia (https://en.wikipedia.org/wiki/Enhanced_oil_recovery)

**Comment by danmichaelo** [comment]
Funker Polymerinjeksjon som norsk term?

**Comment by ken075** [comment]
Flott! Tusen takk!
