### ISSUE TITLE
Nettverk og grafer

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1430]
Er det nødvendig å ha emnet når man har emnet "nettverk" og helt sikkert også har emnet "grafer"?

---
*REAL013204 (Nettverk og grafer) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013204), [Skosmos](http://data.ub.uio.no/realfagstermer/c013204), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Nettverk%20og%20grafer%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL013204)*

**Comment by danmichaelo** [comment]
Nei, slettet, dette er egentlig en term som stammer fra MSC-klassifikasjonen ([94.30 Nettverk og grafer](http://data.ub.uio.no/msc-ubo/94.30))
