### ISSUE TITLE
Tilordninger

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1431]
ingen katalogposter på emnet

---
*REAL013098 (Tilordninger) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013098), [Skosmos](http://data.ub.uio.no/realfagstermer/c013098), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Tilordninger%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL013098)*

**Comment by danmichaelo** [comment]
Slettet
