### ISSUE TITLE
Parallellbehandling

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1433]
Er det forskjell på parallellprogrammering og parallellbehandling?
Veldig usikker på hvordan det sistnevnte skal oversettes når det alikevel er snakk om databehandling/programmering

---
*REAL011859 (Parallellbehandling) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011859), [Skosmos](http://data.ub.uio.no/realfagstermer/c011859), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Parallellbehandling%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL011859)*

**Comment by BioHeidi** [comment]
Ser ut som de kan slås sammen, også Parallelle metoder. Parallellprogrammering som foretrukken term.

**Comment by danmichaelo** [comment]
Bare ut fra termene ville jeg slått sammen parallellprogrammering og parallellbehandling. Men tenkte å gå gjennom litteraturbelegget for alle parallell*-termene våre en dag. Mistenker at noen hovedsakelig viser til [concurrent](https://en.wikipedia.org/wiki/Concurrent_computing), andre til  [parallel](https://en.wikipedia.org/wiki/Parallel_computing) computing.

**Comment by danmichaelo** [comment]
Lukker denne til fordel for #1433
