### ISSUE TITLE
Fuglesang

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1435]
Den er låst i soksed, men foreslår at den utfleskes med EN Bird song EN Birdsong EN Bird calls
![image](https://user-images.githubusercontent.com/42732381/47075342-ad0bde00-d1fc-11e8-8bc0-4e51b3977cf7.png)

**Comment by danmichaelo** [comment]
Takk, gjort!

**Comment by Hypsibius** [comment]
Legg til NN fuglesong også?

**Comment by danmichaelo** [comment]
Ooh, takk!
