### ISSUE TITLE
Leppefisker

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1436]
Foreslår at LA Labridae legges til. (EN Wrasse er allerede på plass i soksed). 
![image](https://user-images.githubusercontent.com/42732381/47078319-581f9600-d203-11e8-96c1-0c023478c7be.png)

Lurer på om noe bør gjøres med Berggylt (ikke et emneord ennå; EN Ballan wrasse LA Labrus bergylta)
Kunne opprettes som eget emneord siden det er mye forskning på den i sammenheng med fiskeoppdrett? Eller kunne være BF/SO under leppefisker? @Hypsibius

**Comment by danmichaelo** [comment]
Gjort! Opprettet Berggylt også. Si fra hvis dere ombestemmer dere, så sletter jeg den bare.

**Comment by Hypsibius** [comment]
Per Pethon brukar visserligen 'berggylt', og det gjer og Havforskinga men Nynorsk/bokmålsordboka er ikkje med dei!

![image](https://user-images.githubusercontent.com/9350370/48404319-3fd26680-e730-11e8-8b28-b5f7f34e8f3d.png)

Litt uviss på kva som bør vere hovudinnførsle når desse sprikar? Google gir hhv ~27.000 mot 22.000 treff...

**Comment by Hypsibius** [comment]
Altså, begge former på med, i begge målformer, berre usikker på hovudterm?

**Comment by danmichaelo** [comment]
Oi.

Artsdatabanken bruker også berggylt: https://artsdatabanken.no/Taxon/Labrus%20bergylta/43034

Så beholdt berggylt som foretrukket term, men la inn berggylte som alternativ term.

**Comment by danmichaelo** [comment]
Greit å ta med "bergsugge" og "bergskjebbe" også? Fra artsdatabanken

**Comment by Hypsibius** [comment]
Absolutt!
