### ISSUE TITLE
Pardanning

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1437]
Pardannelse er et viktig felt også innenfor kjemi. burde dette vært definert på noe vis at er biologiemnet?

---
*REAL012573 (Pardanning) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c012573), [Skosmos](http://data.ub.uio.no/realfagstermer/c012573), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Pardanning%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL012573)*

**Comment by danmichaelo** [comment]
Gjort! + SO Monogami

**Comment by danmichaelo** [comment]
og mappet til https://en.wikipedia.org/wiki/Pair_bond
