### ISSUE TITLE
Italiensk

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1439]
Real: Italiensk språk eksisterer. Trenger man da "italiensk" i tillegg?

---
*REAL008380 (Italiensk) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008380), [Skosmos](http://data.ub.uio.no/realfagstermer/c008380), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Italiensk%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008380)*

**Comment by danmichaelo** [comment]
Sikkert vært ment for italiensk kultur e.l., men med ett dokument så sletter jeg den.
