### ISSUE TITLE
Fylogeni - Fylogenetikk - Kladistikk

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1444]

**Comment by Caroline-A** [comment]
![image](https://user-images.githubusercontent.com/42732381/47914755-00d72200-dea1-11e8-8020-af8d290ccd79.png)
![image](https://user-images.githubusercontent.com/42732381/47914763-0a608a00-dea1-11e8-9776-a1c1ed0266da.png)

Vi har "phylogenetic trees" på begge to. Lurte på hvordan vi tenker på disse to. Obs at vi også har Kladisktikk. Jeg synes den burde være sammenslått med en av de to. 
![image](https://user-images.githubusercontent.com/42732381/47915045-ea7d9600-dea1-11e8-9e4a-0627e25ee6a1.png)

**Comment by danmichaelo** [comment]
@realfagstermer/bio

**Comment by BioHeidi** [comment]
Ja jeg synes egentlig vi bare kan slå de sammen. Og også Kladistikk, som ofte brukes som et slags synonym men som vel er selve metoden? Termene er brukt på mange de samme dokumentene.

**Comment by Hypsibius** [comment]
What @BioHeidi said!

**Comment by Caroline-A** [comment]
Ser bra ut! Men så at det er samsvar med norsken foreslår jeg å legge til EN phylogenomics EN cladistics.

**Comment by danmichaelo** [comment]
Takker!
