### ISSUE TITLE
Mikrobiell økologi - Økologisk mikrobiologi

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1447]
![image](https://user-images.githubusercontent.com/42732381/47993858-f4490880-e0f0-11e8-8224-ee13a47c193b.png)
![image](https://user-images.githubusercontent.com/42732381/47993873-ff039d80-e0f0-11e8-9e53-758eba4656d4.png)

Foreslår sammenslåing som Mikrobiell økologi BF Økologisk mikrobiologi

**Comment by danmichaelo** [comment]
@realfagstermer/bio

**Comment by danmichaelo** [comment]
Slått sammen.
