### ISSUE TITLE
Invaderende arter

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1448]
![image](https://user-images.githubusercontent.com/42732381/47997417-08463780-e0fc-11e8-852e-86d72c9cdfe7.png)
![image](https://user-images.githubusercontent.com/42732381/47997381-e77de200-e0fb-11e8-9b96-3d5e51a52da3.png)

Vil gjerne utfleske med synonymer:
EN Alien species
EN Non-native species
EN Non-indigenous species
EN Exotic species
EN Biological invasions

**Comment by danmichaelo** [comment]
Glemte å lukke saken, men det er lagt til!
