### ISSUE TITLE
Næring - næringen

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#145]
Vi har innførsla 'fiskerinæring', og dessutan 'turistnæring'. Kjem ikkje desse i klassen av ting det berre finst ein av, og som derfor skal førast inn i bunden form, jf 'hjertet', 'leveren'? Foreslår derfor at desse blir retta til fiskerinæringen, turinstnæringen. Rett nok har desse sikkert a-ending som alternativ, men når nynorsken kjem på plass, ordnar jo det seg :-)

**Comment by danmichaelo** [comment]
Mjo, blir ikke det riktig?

**Comment by mittinatten** [comment]
FiskerinæringEN høres for meg ut som noe nasjonalt, men Fiskerinæring omfatter alle næringer globalt, som et fenomen og ikke som en "institusjon". Dette er bare intuisjonsbaset, så jeg tar sikkert feil.

**Comment by danmichaelo** [comment]
Hm, jo, kanskje det er mer et fenomen enn en ting?

**Comment by danmichaelo** [comment]
Jeg er visst ikke mye til hjelp her...

Humord har [Turistnæring](http://li148-205.members.linode.com/humord/nb/page/?uri=http%3A%2F%2Fdata.ub.uio.no%2Fhumord%2Fc07761) og [Fiskerinæring](http://li148-205.members.linode.com/humord/nb/page/c07625), men også [Skipsfartsnæringen](http://li148-205.members.linode.com/humord/nb/page/?uri=http%3A%2F%2Fdata.ub.uio.no%2Fhumord%2Fc25419) og [Landbruksnæringen](http://li148-205.members.linode.com/humord/nb/page/?uri=http%3A%2F%2Fdata.ub.uio.no%2Fhumord%2Fc07637) (begge BF-termer)

**Comment by bibliomari** [comment]
Nei, dette tror jeg blir sammenblanding. Hjortsæter: Som oftest settes emneordet i ubestemt form. Unntak er emneord som betegner enkelte abstrakte begreper, ting det bare finnes en av og organer og organsystemer som hvert individ bare har ett av. (...) 

Jeg er helt med på at Fiskerinæring er et entallsord, men ikke at det skal ha bestemt form. I Hjortsæters eksempler, som hun for øvrig er ganske gnien med, er vel det eneste sammenlignbare "Katolisisme", altså ikke "Katolisismen". Hjortsæter 2005, Emneordskatalogisering s. 41

**Comment by Hypsibius** [comment]
Ok, I'm folding ;-)
