### ISSUE TITLE
Ressursforvaltning

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1450]
Akkurat nå er den brukt for det meste om [natur ressurs](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc010010). Men termen selv er faktisk ganske bred - kan brukes i [mange måter](https://en.wikipedia.org/wiki/Resource_management_(disambiguation)), e.g. innenfor teknologi og [økonomi/organisajonsteori ](http://web.bi.no/info/kurs1999.nsf/e0444df87e8ed06ec12567980047f457/f738c6dbf14755dbc125678d0045bb62!OpenDocument). 

Lurer på om den burde endres for å være mer spesifikk, e.g. naturressursforvaltning.

**Comment by Hypsibius** [comment]
Som eksempelvis Ressursforvaltning (Naturressurser)?

**Comment by danmichaelo** [comment]
Godt poeng! Endra til `Naturressursforvaltning BF Ressursforvaltning (Naturressurser)`
