### ISSUE TITLE
Citizen Science

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1451]
Jobbe med [denne ](https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71565298290002201&context=L&vid=UBB&search_scope=default_scope&isFrbr=true&tab=default_tab&lang=no_NO)nå. Kan ikke finne noe tegn at vi har citizen science som emneord, men jeg er ikke helt sikkert på det fordi jeg vet ikke hvordan det er best oversatt (...det virker som jeg er ikke alene der: se [her ](https://twitter.com/yokokula/status/399901151455236096)og [her](https://twitter.com/nrkviten/status/470828435724836865?lang=en)!)

Foreslår: 
Folkeforskning BF Allmenvitenskap BF Allmenforskning BF Borgelig vitenskap BF Borgerforskning
EN Citizen science

**Comment by Hypsibius** [comment]
NN Folkeforsking. Likar både ordet og fenomenet :-) Borgervitenskap kanskje, i staden for Borgelig?

**Comment by danmichaelo** [comment]
Jeg har også hørt Folkeforskning brukt før, så det var også min første tanke. Men så oppdaget jeg at Humord (@vibekelundetrae) har gått for [Dugnadsforskning](http://data.ub.uio.no/humord/c29947), og må si jeg fikk litt sansen for den termen, for det er jo noe dugnadspreget over citizen science. Hva synes dere?

**Comment by Caroline-A** [comment]
Jeg tok en kjapt google av begge to, og fikk _kanskje_ flere hits som var faktisk om citizen science med "folkeforskning" (e.g. [UiB UM evertebrate blog](https://evertebrat.w.uib.no/tag/folkeforskning/), [forskning.no](https://forskning.no/blogg/viten-om-naturen/tre-tips-til-deg-som-vil-drive-med-folkeforskning), [UiO ](https://www.mn.uio.no/geo/english/research/groups/latice/news/latice-folkeforskning.html), [NTNU](http://blogg.vm.ntnu.no/nudibranchia/2017/03/12/nakensnelgsafarien-er-folkeforskning/)). Men dugnadsforskning er i bruk også ([Forskningsrådet](https://www.forskningsradet.no/prognett-miljoforsk/Nyheter/Ny_humanistisk_kunnskap_om_miljo_klima_og_berekraft/1254035676656/p1254008430070)). 
Har ikke noe sterk mening om hvilken er best. Men uansett hvilken er valgt som hovedterm, synes jeg at det er smart å ta med alle mulige termer som BF akkurat nå, siden det virker som det er ikke så mye konsensus over det beste norske oversettelse - på noen norske prosjekter ser jeg at de bruker bare "citizen science" på engelsk.

**Comment by Hypsibius** [comment]
Likar begge, kan leve med begge. Og det finst autoritetar. Blir hipp som happ om vi følgjer UIO/NTNU el Forskingsrådet m hovudterm. Alt blir søkbart lell :-)

**Comment by danmichaelo** [comment]
Gikk for Dugnadsforskning som hovedterm: http://data.ub.uio.no/realfagstermer/c032057

Vi kan alltids snu senere :)
