### ISSUE TITLE
Koronaen

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1452]
Vi trenger både "Korona" og "Koronaen"?

---
*REAL011991 (Koronaen) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011991), [Skosmos](http://data.ub.uio.no/realfagstermer/c011991), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Koronaen%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL011991)*

**Comment by danmichaelo** [comment]
Duplikat av #1284
