### ISSUE TITLE
Hubble Space Telescope

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1455]
Ligger som autoritet i BARE

---
*REAL004852 (Hubble Space Telescope) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004852), [Skosmos](http://data.ub.uio.no/realfagstermer/c004852), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hubble%20Space%20Telescope%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL004852)*

**Comment by danmichaelo** [comment]
Gjort:

```
almar --diffs replace \
  '650 #7 $$a Hubble Space Telescope $$2 noubomn' \
  '610 27 $$a Hubble Space Telescope $$2 bare'
```
