### ISSUE TITLE
Challenger-ekspedisjonen

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1456]
Denne ligger i BARE: Challenger Expedition. Slettes som realfagsterm?

---
*REAL004311 (Challenger-ekspedisjonen) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004311), [Skosmos](http://data.ub.uio.no/realfagstermer/c004311), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Challenger-ekspedisjonen%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL004311)*

**Comment by vibekelundetrae** [comment]
BARE er Bibsys' autoritetsregister. Tilgang via Alma, søk på Authorities
Man kan da heller legge inn Challenger Expedition som et korporasjons-emne i marcfelt 610

**Comment by danmichaelo** [comment]
Sjekket med NB, som svarte:

> Ekspedisjoner o.l. skal ha 111, jfr. Alphabetical List of Ambiguous Headings: https://www.loc.gov/marc/authority/ambiguous-headings.html 
> 
> Jeg har derfor flyttet den ene bibliografiske posten som var knyttet til 110-innførselen i autoritetsregisteret og knyttet den opp til 90783810. Jeg har deretter forsøkt å slette 12007101, men Alma lar meg av en eller annen grunn ikke få lov til det. Skal sende feilmedling på dette. Jeg har også (under tvil) endret innførselen til Challenger-ekspedisjonen, med grunnlag i Katalogiserignsregler 24.3C2. Jeg har selvsagt også registrert en se hevnisning fra Challenger Expedition. Posten som bør brukes er i alle fall 90783810.


Flyttet:

```
almar --diffs replace \
  '650 #7 $$a Challenger-ekspedisjonen $$2 noubomn'  \
  '611 27 $$a Challenger-ekspedisjonen $$2 bare'
```
