### ISSUE TITLE
CODASYL

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1457]
korporasjon. Slettes som realfagsterm?

---
*REAL005613 (CODASYL) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005613), [Skosmos](http://data.ub.uio.no/realfagstermer/c005613), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22CODASYL%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL005613)*

**Comment by danmichaelo** [comment]
Slettet
