### ISSUE TITLE
Fiskerotter vs vannrotter vs vånd

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#146]
Her ser det ut til å vere ein del samanblanding. 

Det står 'fiskerotter, se vannrotter'. Søk på realfagstermar i Ask gir tre treff, på artar i to forskjellige trupper. To ser ut til å vere på vånd, som av og til omtalast som vannrotter. I desse tilfella tenkjer eg det er korrekt å legge inn 'vånd, BF vannrotter' i registeret. 

Men det tredje treffet er på 'ichthyomyine rodents'. Ichthyomys får eg treff på som 'fiskerotte' på dansk. Den tilhøyrer iflg ITIS 'Subfamily  Sigmodontinae Wagner, 1843 – New World rats, New World mice'. Med andre ord ei heilt anna gruppe. Kanskje treng vi ikkje eit eige emneord for denne eine boka? Fskerotter kan kanskje berre slettast, og i alle fall haldast separat frå vannrotter.

**Comment by bibliomari** [comment]
@Hypsibius @BioHeidi

**Comment by BioHeidi** [comment]
Enig med Hege, bruk Vånd BF Vannrotter, EN Voles, evt kan vi se på latin, men da må vi ta frem bøkene.
Fiskerotter kan vi godt beholde som egen term, EN Ichthyomyine rodents, Fish-eating rodents, LA Ichthyomyini.

**Comment by BioHeidi** [comment]
Gjort
