### ISSUE TITLE
Blekkspruter

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1460]
![image](https://user-images.githubusercontent.com/42732381/48186748-47150100-e339-11e8-89ef-2c5d1d0d4c9f.png)

Er det en god ide å utfleske den med de forskellige gruppene?
BF Nautilider BF Perlebåter EN Nautiluses EN Octopuses EN Squids EN Cuttlefishes

**Comment by danmichaelo** [comment]
@realfagstermer/bio ?

**Comment by Hypsibius** [comment]
Det er ein del dyre (og sikkert plante-) grupper der ulike taksonomiske har 'slått gjennom' i daglegtalen på ulike språk. På engelsk snakkar ein heller om Octopuses/cuttlefish/squid heller en 'cephs', gjer ein ikkje? På norsk snakkar vi heller om 'Blekksprutar', sjølv om vi berre meinar åttearmingar, eller kanskje berre (ein timarma) akkar. Litt som m svensk "Trollsländor, Flicksländor och jungfrusländor" der vi samlar alt i 'øyenstikkarar' 

Kan vi seie noko generelt og prinsippielt om korleis vi gjer det med sånne? Eller er vi pragmatiske og legg på der vi ser det kan vere berikande?

**Comment by Caroline-A** [comment]
Da jeg laget denne issue hadde jeg tenkt på den "pragmatiske" siden, som du beskriver det :) (i.e. som engelsk-talende ville jeg ha søkt med "cuttlefish" heller enn "cephalopods" hvis det var cuttlefish jeg ville vite om). Men jeg er veldig interessert i å høre tanker/generelle prinsipper rundt dette!

**Comment by BioHeidi** [comment]
Pragmatisk og lurt å legge til dagligtalenavn her. Og jeg hadde aldri hørt om perlebåter før! :-D

**Comment by Hypsibius** [comment]
Nydeleg namn, då ;-)

**Comment by danmichaelo** [comment]
@Hypsibius, hva tror du nynorskformen til Nautilider blir?

**Comment by Hypsibius** [comment]
Nautilidar :-)
