### ISSUE TITLE
DNA-strekkoding

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1461]
Foreslår [DNA-strekkoding](http://www.norbol.org/hva-er-dna-strekkoding/) som ny term, for dok som [denne](https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71479361880002201&context=L&vid=UBB&search_scope=default_scope&tab=default_tab&lang=en_US). 

Er ikke helt sikkert på det bør være "strekkode" eller "strekkoding", eller begge.

DNA-strekkoding BF Genetisk strekkoding
NN ? 
EN DNA-barcoding EN Genetic barcoding

**Comment by Hypsibius** [comment]
NN: Stekkoding 

Tenkjer det er greitt å bruke -koding

**Comment by danmichaelo** [comment]
Ok, oppretta!
