### ISSUE TITLE
Dypvannskoraller

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1462]
![image](https://user-images.githubusercontent.com/42732381/48847093-01c4ea80-eda1-11e8-99c2-04b9626044b9.png)
Kan vi utfleske med BF Kaldtvannskoraller EN Cold-water corals? (Jeg kan ikke nynorsk, men gjerne legg til nynorske versjon også).

**Comment by Hypsibius** [comment]
NN Kaldtvasskorallar

**Comment by danmichaelo** [comment]
Gjort!

**Comment by Hypsibius** [comment]
Når vi er i gang, kan eg gjenopne denne og forelså eit tillegg? 

BF Dyphavskoraller NN Djuphavskorallar

**Comment by danmichaelo** [comment]
Lagt til!
