### ISSUE TITLE
Økologisk modellering - Økologiske modeller

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1463]
Trenger vi begge to eller kan de sammenslåes? 
![image](https://user-images.githubusercontent.com/42732381/48847676-6af92d80-eda2-11e8-8946-bb38ae1f8694.png)
![image](https://user-images.githubusercontent.com/42732381/48847695-73e9ff00-eda2-11e8-8e16-d53de06cc45a.png)

**Comment by Hypsibius** [comment]
Det er jo ein diskusjon vi har hatt generelt, om prosess mot produkt. I dette tilfellet ser eg ikkje heilt situasjonar der det er spesielt fruktbart å separere prosessen frå produktet, så eg tenkjer dei kan slåast saman

**Comment by BioHeidi** [comment]
Her kan vi slå sammen, ser at de er brukt omtrent likt. Økologiske modeller bf Økologisk modellering da, siden det første er mest brukt.

**Comment by danmichaelo** [comment]
Hjort!
