### ISSUE TITLE
Hjelpestoffer

### ISSUE THREAD

**Issue by Violabibaluba** [realfagstermer/realfagstermer#1464]
Vi har Farmasøytiske hjelpestoffer! Hjelpestoffer kun brukt i denne sammenheng.

---
*REAL000995 (Hjelpestoffer) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000995), [Skosmos](http://data.ub.uio.no/realfagstermer/c000995), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hjelpestoffer%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000995)*

**Comment by BioHeidi** [comment]
Tenker vi kan erstatte den med Tilsetningsstoffer.

**Comment by grosyn** [comment]
Fann kun 2 dokument - det eine (Additives) erstatta eg med Tilsetningsstoffer, det andre (Adhesives) med Bindemidler. Sletta Farmasøytiske hjelpestoffer.
