### ISSUE TITLE
Myting - skallskifte/hudskifte?

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1467]
![image](https://user-images.githubusercontent.com/42732381/49225739-221a2800-f3e5-11e8-98ec-40d6558b3625.png)

Meg og @Hypsibius har snakket litt om hva kan brukes når det er snakk om hud/skallskifte hos krepsdyr, insekter, krypdyr. Vi har ikke termer "skallskifte" eller "hudskifte". Jeg jobber med [denne](http://bora.uib.no/handle/1956/12043). Termen kan være nyttig i sammenheng med lakselus.

Myting er oversatt som "[moulting](https://en.wikipedia.org/wiki/Moulting)", men moulting kan brukes både for hud/skallskifte og tap av hår/pels/fjær. Når det er "ecdysis", da snakker vi bare om kutikula. 

Vi så for oss to muligheter - å samle alt under hamskifte, i.e.:
Hamskifte 
BF Myting BF Fjærfelling BF Hudskifte BF Skallskifte 
NN Fjørfelling
EN Moulting EN Ecdysis

Eller å ha de seperat med noe slags disambiguation på engelsk, i.e.
Myting
BF Myting BF Fjærfelling 
NN Fjørfelling
EN Moulting (feathers or fur)

Hudskifte
BF Skallskifte
NN ?
EN Ecdysis EN Moulting (exoskeleton or skin)

**Comment by danmichaelo** [comment]
@realfagstermer/bio

**Comment by BioHeidi** [comment]
Vi hadde så lite litteratur på det at jeg gikk for første løsningen:
Hamskifte BF alt det andre.
