### ISSUE TITLE
Dare

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1469]
Liten skrivefeil i engelsk term :-)

---
*REAL008864 (Dare) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008864), [Skosmos](http://data.ub.uio.no/realfagstermer/c008864), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Dare%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008864)*

**Comment by danmichaelo** [comment]
Takk, fiksa! Ellers kan det vel være den skulle vært flytta til BARE?

**Comment by danmichaelo** [comment]
Tenker resultatet er emnet, men litt usikker på hvor fysisk det er :D Altså, utfra https://www.computer.org/csdl/proceedings/afips/1969/5074/00/50740247.pdf ser det ut som simulerings*programvare*, men antakelig sterkt koblet til bestemt hardware. Så antakelig mer *computer system* enn *computer program*. Isåfall blir det 650 iflg. [reglene](https://www.loc.gov/marc/bibliographic/ambiguous-headings.html):

* Computer programs (established under title) [X30]
* Computer systems [650]

Oh joy!
