### ISSUE TITLE
Hav : Mytologi

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1470]
ER det her snakk om havet - mytologi? I så fall er engelsk term ikke oversatt?

---
*REAL031598 (Hav : Mytologi) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c031598), [Skosmos](http://data.ub.uio.no/realfagstermer/c031598), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hav%20%3A%20Mytologi%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL031598)*

**Comment by danmichaelo** [comment]
Var fordi termen "Hav" ikke var korrekturlest. Fiksa nå. 

jfr. http://id.loc.gov/authorities/subjects/sh85093871.html
