### ISSUE TITLE
Harvard Mark I

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1471]
Måtte sjekke denne litt. LOC authorities har den som: Mark I (Calculator)

---
*REAL001785 (Harvard Mark I) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c001785), [Skosmos](http://data.ub.uio.no/realfagstermer/c001785), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Harvard%20Mark%20I%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL001785)*

**Comment by danmichaelo** [comment]
Det er den, ja: http://id.loc.gov/authorities/subjects/sh85081321.html

De har `Harvard Mark I` som sehenvisning, mens vi har det som foretrukket term. Kanskje litt hipp som happ? La uansett inn noen henvisninger.

Greit å få bekreftet at det skal være en 150-post.
