### ISSUE TITLE
Heliosat

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1472]
Endre til ubestemt flertall?

---
*REAL008794 (Heliosat) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008794), [Skosmos](http://data.ub.uio.no/realfagstermer/c008794), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Heliosat%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008794)*

**Comment by danmichaelo** [comment]
Du mener flytte til BARE..?

**Comment by vibekelundetrae** [comment]
Nei, jeg lurer på om emneordet heller burde være Heliostater? Heller enn ubestemt entall, Heliostat

**Comment by vibekelundetrae** [comment]
Heliostater ligger inne som registerterm i WD: se 523.70284
Det er ikke det samme?

**Comment by danmichaelo** [comment]
Nei. Helios betyr sol, så begge deler har noe med sol å gjøre, men det er hele likheten :)
