### ISSUE TITLE
Himmelmyter

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1474]
Er det nødvendig å ha dette emnet på én katalogpost når emnet ikke er spesielt godt? 

---
*REAL008951 (Himmelmyter) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008951), [Skosmos](http://data.ub.uio.no/realfagstermer/c008951), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Himmelmyter%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008951)*

**Comment by danmichaelo** [comment]
Kunne kanskje vært et greit emneord, men når det eneste vi har er en halvgammel fransk bok så sletter jeg den i denne omgang. Boka er fortsatt gjenfinnbar gjennom Astronomi + Myter.
