### ISSUE TITLE
Romfart : Bemannet romfart

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1475]
Er denne termen litt smør på flesk når man også har Bemannet romfart??

---
*REAL015836 (Romfart : Bemannet romfart) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c015836), [Skosmos](http://data.ub.uio.no/realfagstermer/c015836), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Romfart%20%3A%20Bemannet%20romfart%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL015836)*

**Comment by danmichaelo** [comment]
:D Slettet
