### ISSUE TITLE
Sekkdyr + Ascidier

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1476]
Jeg tror disse kan sammenslåes. Kanskje sekkdyr som foretrukket, [siden det er den artsdatabanken bruker](https://artsdatabanken.no/ScientificName/Ascidiacea/249)?
![image](https://user-images.githubusercontent.com/42732381/49799055-3abf0200-fd44-11e8-96f7-0492d6857ae7.png)
![image](https://user-images.githubusercontent.com/42732381/49799068-43173d00-fd44-11e8-9c67-3cc6b8a78826.png)

Et par andre ting mens jeg jobber med denne:

- Jeg ser at den ene har en SO kappedyr. Lurer på om en overordnet taksonomisk gruppe bør også har SO for underordnet grupper (og vice versa). E.g. kappedyr SO appendikularier, salper, sekkdyr

- Salper er låst i søksed som EN Thaliaceans, men Thaliaceans er ikke bare salps så langt jeg vet. Kunne kanskje utfleskes med [EN salps EN doliolids EN pyrosomes](https://en.wikipedia.org/wiki/Thaliacea)? Og BF [ildpølser](https://snl.no/ildp%C3%B8lser) (et veldig fint norsk navn for pyrosomes!) @realfagstermer/bio 
![image](https://user-images.githubusercontent.com/42732381/49800234-49f37f00-fd47-11e8-89f4-7313427cbb7f.png)

**Comment by Hypsibius** [comment]
Korleis skjedde dette i første omgang? 

Og skal ikkje ein SO-term automatisk funke begge vegar?

**Comment by danmichaelo** [comment]
Supert! :christmas_tree:

- `Sekkdyr + Ascidier`: slått sammen og lagt til `Kappedyr UT Appendikularier, Salper, Sekkdyr` (UT / underordnet term er en form for SO)

- `Salper`: Lagt til `EN Salps EN Doliolids EN Pyrosomes BF Ildpølser` :)

(I parentes: SO kan være enveis, men jeg er personlig ikke så glad i det fordi det bryter med [SKOS](https://www.w3.org/2009/08/skos-reference/skos.html))
