### ISSUE TITLE
Skuldere

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1478]
Er dette kroppsdelen skulder?? 
Eller er det noe annet?

---
*REAL008076 (Skuldere) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008076), [Skosmos](http://data.ub.uio.no/realfagstermer/c008076), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Skuldere%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008076)*

**Comment by danmichaelo** [comment]
Neida, vi har slettet `Veiskuldere` :)

**Comment by danmichaelo** [comment]
Men se #1358
