### ISSUE TITLE
Laboratorieprosedyrer / forsøk / oppgaver / håndbøker / teknikk

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1479]
Disse er vanskelig å bruke siden det er mye som er det samme (samme BF og EN på forskellige hovedtermer) -
- Laboratorieforsøk (REAL001108)
- Laboratoriehåndbøker (REAL030091)
- Laboratorieoppgaver (REAL030092)
- Laboratorieprosedyrer (REAL007575)
- Laboratorieteknikker (REAL001500)
![image](https://user-images.githubusercontent.com/42732381/50337068-4fec1b80-0510-11e9-86a6-d7153fe3f69a.png)
![image](https://user-images.githubusercontent.com/42732381/50337085-5b3f4700-0510-11e9-93d1-35bbc7379ba4.png)
![image](https://user-images.githubusercontent.com/42732381/50337097-64c8af00-0510-11e9-8af6-6354caeb8c6b.png)
![image](https://user-images.githubusercontent.com/42732381/50337113-6f834400-0510-11e9-8f9b-51551258da65.png)
![image](https://user-images.githubusercontent.com/42732381/50337129-77db7f00-0510-11e9-86db-40cdcbdfd1a8.png)

Jeg har prøvd å tenke gjennom, og har et forslåg - men blir fint med andres meninger om dette, siden jeg er ikke overbevist at dette er et bra forslag...!

Foreslår at Laboratorieprosedyrer (REAL007575), Laboratoriehåndbøker (REAL030091) og Laboratorieteknikker (REAL001500) sammenslåes. Da har man:

**Laboratorieteknikker** _- dok. som innholder teknikker for eksperimenter, og veiledning i ikke-eksperimental laboratoriearbeid (e.g. disseksjon, prøver)_
BF Laboratorieprosedyrer BF Laboratoriehåndbøker BF Laboratoriemanualer
EN Laboratory techniques EN Laboratory procedures EN Laboratory protocols EN Laboratory manuals EN laboratory handbooks EN Laboratory guides
SO Laboratoriekurs

**Laboratorieforsøk** _- dok som dokumenterer laboratoriearbeid hvor hypoteser er testet_
BF Laboratorieexperimenter
EN Laboratory experiments

**Laboratoriekurs** - _dok som er kurshefter eller tekster rettet primært mot opplæring_ 
BF Laboratorieoppgaver BF Laboratorieøvelser EN Laboratory courses EN Laboratory exercises
SO Laboratorieteknikker

**Comment by Hypsibius** [comment]
Melder meg på denne og kjem tilbake ein dag eg har noko å tilføre

**Comment by BioHeidi** [comment]
Bra inndeling. Synes det blir mer oversiktlig.

**Comment by Hypsibius** [comment]
Istemmer!

**Comment by Caroline-A** [comment]
Jeg ser hva du mener. Jeg ville ha satt alt som du har under "laboratorieteknikker" under laboratorieteknikker, så det er greit. Men under laboratoriekurs ville jeg kanksje ha satt flere under labteknikker, og ikke under kurs (bare fra tittel). 
I min orginal post sa jeg:
> "Laboratoriekurs  - dok som er kurshefter eller tekster rettet primært mot opplæring
BF Laboratorieoppgaver BF Laboratorieøvelser EN Laboratory courses EN Laboratory exercises
SO Laboratorieteknikker

Men, blir den bedre/lettere hvis den er strammet inn litt til "dok som er kurshefter, komplett kurs, eller et øvelser rettet primært mot studenter"?

Min opprinnelig tankegang med det var at vi kunne skille mellom ting du vil få opp i søk hvis du er et student på kurs, eller underviser som vil få ideer for kurs (labkurs) - vs. - ting du vil få opp i søk hvis du trenger å lære/sjekk opp noen teknikker/prosedyrer (for eks. du er labteknikker, eller stipendiat, som skal gjøre et forsøk) (labteknikker) - vs. - ting du vil få opp hvis du er interessert i forsøk som andre har gjørt (e.g. du er forsker interessert i tidligere lab-basert microcosm experiments) (labforsøk). Men jeg er ikke sikkert på om det er fornuftig!

Jeg ville ha tatt under labkurs (bare ut fra tittel):
- 999216208104702201	Experimental physics for students / R.M. Whittle and J. Yarwood. 1973
- 998811192104702201	Laboratoriekurs i generell kjemi / Katrine Seip Førland. 1988
- 999612552504702201	Laboratory exercises in invertebrate physiology : by John H. Welsh [and] 
- 990409536024702201	Chemical biology : a practical course / Herbert Waldmann and Petra Janning
- 991015769864702201	Laboratoriekurs i generell kjemi / Hilde Lea Lein ... [et al.]. cop. 2010
- 999611661264702201	Instructor's manual to accompany biological investigations in the laboratory
- 990311127064702201	Practical microbiology for secondary schools : a revised
- 999621816334702201	Laboratory text in organic chemistry / James Cason, Henry Rapoport. 1962
- 999612543194702201	Laboratory exercises in cell physiology. 1969
- 999614234554702201	Kjemi laboratorieøvelser : VK1 kjemi- og prosessfag. 1996
- 998430330884702201	Demonstrasjonsforsøk i generell, uorganisk og organisk kjemi / Anne-Lise 
- 999612540334702201	Laborationskompendium i fysiologi / red. av Birger Løfving. 1970

Noen kunne få begge, e.g.:
- 991003001464702201	The organic chem lab survival manual : a student's guide to techniques / James W. Zubrick. cop.2011
- 998903795484702201	Practical organic chemistry : a student handbook of techniques / J.T. Sharp, I. Gosney, and A.G. Rowley. c1989
- 998841282964702201	Introduction to laboratory chemistry : general / Arthur L. Williams ...[ et al.]. c1970
- 990606118394702201	Practical organic synthesis : a student's guide / Reinhart Keese and Martin Brändle ; translated by Trevor Toube. cop. 2006

**Comment by kyrretl** [comment]
Vi har trukket ut alle poster (~200) som har en eller flere hovedtermer som begynner med "Laboratorie..." (ingen poster har fler enn to):

https://docs.google.com/spreadsheets/d/1O4pz_WmWju2MoH4W1qw77mF510fuOZC60vyPnw_tIHs/edit#gid=1194162353

Heldigvis er det stort sett bare "Laboratorieforsøk" og "Laboratorieteknikker" på disse postene, så det trenger ikke ta så mye tid å gå gjennom dem hvis vi tar en bolk hver. 

Jeg er enig med Carolines inndeling, men jeg er også enig med Dan Michael i innsigelsen angående "Laboratorieforsøk" at "dok som dokumenterer laboratoriearbeid hvor hypoteser er testet" kanskje ikke eksisterer. Artikler er jo der hypoteser testes, bøker har ofte andre roller, så jeg regner med at dette skillet, selv om det er bra definert, ikke vil være særlig anvendelig. Men dersom vi gjør definisjonen mer generisk f.eks. at dette emneordet settes på bøker som i det hele tatt viser praktiske labeksperimenter, da kan "Laboratorieteknikker" settes på poster som ikke nødvendigvis inneholder laboratorieforsøk,  men beskriver oppsett for å gjøre forsøk, som Caroline nevnte.

Usikker på om vi klarer å opprettholde et skille mellom "Laboratorieforsøk" og "Laboratorieteknikker" eller om disse bør slås sammen. Det vil uansett bare gjelde ca 200 poster og ved å avgrense med fagområde eller andre termer kan det bli håndterlig i søk. Vi får antakelig et bedre bilde av dette når vi har gått gjennom en god del av postene i regnearket.

Videre foreslår vi istedet for "Laboratoriekurs" bruke *formterm* "Kursmateriell" på poster som er egnet til undervisning/studiebruk og vil ha samme definisjon som Caroline foreslo, men utvides utover labvirksomhet. Dette vil da gjelde for labveiledninger, kompendier, støttebøker, etc som brukes i kurs i tillegg til hovdedpensumboka. Ved å bruke kombinertsøk som kommer snart (TM) kan man søke på "Kursmatereriell" OG "Laboratorie...", "Kursmatereriell" OG "Kjemi", "Kursmatereriell" OG "Insekter", etc. "Kursmateriell"-formen har også en del BF'er som hjelper i gjenfinning:  BF "Kursmateriale" BF "Kurskompendier".

Andre termer:
- "Laboratoriesikkerhet" er en fin term og bør beholdes, men den er ikke satt på alle poster som bør ha den.
- "Laboratorieutstyr": 3 dokumenter kan antakelig flyttes til "Laboratorieteknikker" eller "Vitenskapelige instrumenter"

Kort oppsummert:

1. Bestemme om vi skal slå sammen "Laboratorieforsøk" og "Laboratorieteknikker".
    Hvis vi skal beholde skillet, gå gjennom postene (Google Sheets) og sette term der det egner seg.
2. Sette Form "Kursmateriell" på de postene som skal ha det (Google Sheets).
3. Sette term "Laboratoriesikkerhet" på de postene som mangler den (Google Sheets).
4. Fjerne/Flytte "Laboratorieutstyr" (Google Sheets).

Når vi er (noenlunde) enige om inndelingene lager Dan Michael et skript som retter opp dette på postene basert på dataene i regnearket.

**Comment by kyrretl** [comment]
Vi fant ut at vi må gjøre denne dumpen på nytt (den mangler en del poster dessverre), gir beskjed her når vi har fått lagd ny dump

**Comment by grosyn** [comment]
Kva skjedde med dette? Det kom aldri ein ny dump, ser det ut til. Skulle  "Laboratorieforsøk" og "Laboratorieteknikker" slåast saman? 
@kyrretl

**Comment by grosyn** [comment]
NB er i ferd med å ferdigstilla Norsk tesaurus for sjanger og form, https://www.nb.no/nbvok/ntsf/nb/. Humord har bestemt at dei frå no av bruker NTSF i 655. Sidan Realfagstermer byrjar å bli meir og meir samkjørt med Humord, har me bestemt at me òg skal bruka denne Form-tesaurusen. Me kan be NB ta inn dei termene dei ikkje måtte ha.

Eg ser at det var tanken at Kursmateriell skulle tas i bruk. Då det ikkje er knytt dokument til termen enno, slettar eg den. Skulle me ønska den sidan, kan me be NTSF om å ta den inn.

**Comment by grosyn** [comment]
Eg er usikker på Laboratorieoppgaver. Skal eg be om at NTSF tek det inn, eller skal eg flytta det til Oppgavebøker (som er dét NTSF har for Oppgavesamlinger)?

@BioHeidi

**Comment by grosyn** [comment]
Eg kjem kanskje til å ta opp Kyrre-tråden sidan. Når det gjeld Laboratorieoppgaver, flyttar eg dei til 650.

**Comment by BioHeidi** [comment]
Oppgavebøker funker fint som formterm her tenker jeg. Eller Kursmateriell? Er den helt borte?

**Comment by grosyn** [comment]
Inn med teskei ... Skulle me flytta Laboratoriehåndbøker til Oppgavebøker, eller ha Laboratoriehåndbøker som eigen term? Det er 60 treff på Laboratoriehåndbøker, så me kan prøva å få NB til å ta den inn.

Kursmateriell har eg notert at eg har sletta, men formtermposten finst fortsatt... (Typisk) Skal den slettast? Viss ikkje, må den brukast på noko, elles blir det vanskeleg å argumentera overfor NB.

**Comment by BioHeidi** [comment]
Her er det jeg som må ha teskje nå! Hva ble status etter NB-ryddingen?

**Comment by grosyn** [comment]
Den blei tatt opp i NTSF:
![image](https://github.com/realfagstermer/realfagstermer/assets/12611325/855a28bc-706b-4b4b-b40d-949233e4d1ec)
