### ISSUE TITLE
Varmekjær vegetasjon

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#1480]
Jeg finner ikke en god oversettelse til varmekjær vegetasjon

---
*REAL009198 (Varmekjær vegetasjon) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009198), [Skosmos](http://data.ub.uio.no/realfagstermer/c009198), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Varmekj%C3%A6r%20vegetasjon%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009198)*

**Comment by danmichaelo** [comment]
Også null treff. Noe dere vil beholde, @realfagstermer/bio ?

**Comment by Caroline-A** [comment]
- Jeg sliter også med den! Ser at thermophillic er [i bruk av og til](https://www.researchgate.net/publication/260789703_The_expansion_of_thermophilic_plants_in_the_Iberian_Peninsula_as_a_sign_of_climatic_change), men som du sier er for det meste brukt om ekstremofiler. 
- Med den direkte oversettelsen, warm/warmth-loving, kan jeg få en del treff [i google scholar](https://scholar.google.no/scholar?hl=no&as_sdt=0%2C5&q=%22warmth-loving%22+plants&btnG=)

Jeg vet ikke om det er bedre termer som jeg ikke er bevisst over. 
Det beste jeg kan kom på er derfor EN thermophillic plants EN warmth-loving plants/species EN warm-loving plants/species. Hvis brukt for alle arter, ville jeg har forsatt la det står som "thermophillic plants" for å unngå forvirring med ekstremofiler. Men jeg er ikke sikkert på disse i det hele tatt!

**Comment by BioHeidi** [comment]
Slett :)

**Comment by Hypsibius** [comment]
Ok då ;-)

**Comment by danmichaelo** [comment]
Slettet! Vi kan opprette `Termofile *` ved behov.
