### ISSUE TITLE
Skipsbibliotek

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#1481]
Jeg kan ikke se at dette er et anerkjent begrep. Det forfatter skriver om er lagring av data og sikkerhet. Skal vi lage en oversettelse, elle rhar forfatter allerede oversatt noe jeg ikke har funnet?

---
*REAL010687 (Skipsbibliotek) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010687), [Skosmos](http://data.ub.uio.no/realfagstermer/c010687), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Skipsbibliotek%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010687)*

**Comment by Hypsibius** [comment]
Tjah, bortsett frå oss marinbibliotekarar er det vel marine-bibliotekarane på Sjøkrigsskulen sitt felt. Og SKSK  leggast ned, såvidt eg forstår. Neppe behov for eigen term

**Comment by danmichaelo** [comment]
Slettet den. Ser ikke ut som et etablert begrep
