### ISSUE TITLE
Har vi i grunnen eit fornuftig skille mellom 'Koraller' REAL003153 og 'Koralldyr' REAL004789?

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1482]
![image](https://user-images.githubusercontent.com/9350370/50638708-0d3e3080-0f5f-11e9-8baa-2af869ee334a.png)

![image](https://user-images.githubusercontent.com/9350370/50638741-2810a500-0f5f-11e9-9595-216b121e2c26.png)

Eller kan vi slå saman?

**Comment by Caroline-A** [comment]
Det eneste jeg kan tenke på er at koralldyr inkludere anemoner (Anthozoa), hvis jeg forstår bruk av den riktig. Så hvis jeg for eksempel hadde en dok om bestemmelse av Anthozoa, der passer det med koralldyr, men hvis jeg hadde en dok om korall bleiking, da ville jeg ha brukt koraller?

**Comment by Hypsibius** [comment]
Tenker liksom at 'korralldyr' er den taksonomiske gruppa (inkl anemoner), men 'koraller' er dei fysiske strukturane (e.g. rev). Men her har eg kanskje tenkt heilt feil?

**Comment by BioHeidi** [comment]
Næ, synes egentlig ikke skillet var så fornuftig, vi kan vel si Koralldyr BF Koraller, Anemoner, Sjøanemoner. Vi hadde også termen Sjøanemoner, nemlig. De tre termene har mye overlapp i dokument også.

Så har vi Korallrev som egen term, den synes jeg vi kan beholde siden det er et eget habitat.

**Comment by Hypsibius** [comment]
No snakkar vi! Eg er med!

**Comment by danmichaelo** [comment]
Ok:

Koralldyr
BF Koraller, Anemoner, Sjøanemoner
SO Korallrev
