### ISSUE TITLE
Tråd for termer med lite og gammelt litteraturbelegg (informatikk) 08.01.19

### ISSUE THREAD

**Issue by karolinehoff** [realfagstermer/realfagstermer#1484]
Edit 11.02: Delte opp listene til litt mer bite-size issues. 
Karoline

Her kommer en liste av termer med lettere tvilsomt litteraturbelegg jeg har snublet over mens jeg har jobbet med informatikk- og matematikktermene. Ofte ligger dokumentene med både emneordet fra listen og det over i hierarkiet. 

Slette? Endre? Slå sammen? La dem være? Jeg lar dere eksperter bestemme. 

### Få masteroppgaver og/eller doktorgradsavhandinger
- [x] [REAL007972 Selvbetjente banktjenester](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Selvbetjente%20banktjenester) 1 dokument (Prosjektoppgave i IN165?) fra 1996
- [x] [REAL002261 Flytkontroll](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Flytkontroll) 1 masteroppgave fra 1999
- [x] [REAL002599 Buss-bro](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Buss-bro) 2 masteroppgaver fra 1997
- [x] [REAL002757 Sekvensiell prosessering](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Sekvensiell%20prosessering) 1 masteroppgave fra 2006
- [x] [REAL004273	Hough-transformasjon](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Hough-transformasjon) 3 masteroppgaver fra 1988, 1989 og 1991
- [x] [REAL003070 Programvaredistribusjon](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Programvaredistribusjon) 2 masteroppgaver fra 2006
- [x] [REAL006134	Kodeoptimalisering](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Kodeoptimalisering) 1 doktorgradsavhandling fra 1985
- [x] [REAL008132 Knuth-bendix-algoritmen](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Knuth-bendix-algoritmen) 2 masteroppgaver fra 1992 og 1993 + 1 dokument fra 1984
- [x] [REAL001363 Business process reengineering](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Business%20process%20reengineering) 1 masteroppgave fra 1995 + 1 dokument fra 1995

### Få, eldre dokumenter
- [x] [REAL002161 Bruksmønstre]( https://app.uio.no/ub/emnesok/realfagstermer/search?term=Bruksm%C3%B8nstre) 1 dokument fra 2003. 
- [x] [REAL008062 Runge–Kutta-metoder](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Runge%E2%80%93Kutta-metoder) 3 dokumenter fra 1964, 1965 og 1998
- [x] [REAL007337 Seriell kommunikasjon](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Seriell%20kommunikasjon) 2 dokumenter fra 1990 og 1993
- [x] [REAL002440 Kommandospråk](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Kommandospr%C3%A5k) 1 dokument fra 1976
- [x] [REAL003647 Navnetjenere](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Navnetjenere) 1 dokument fra 1995
- [x] [REAL006559 Objektgjenkjenning](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Objektgjenkjenning) 2 proceedings fra 1997
- [x] [REAL006625 Simscript](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Simscript) 3 dokumenter fra 1963, 1968 og 1995
- [x] [REAL011662 Bull Gamma 60](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Bull%20Gamma%2060) 1 dokument fra 1997
- [x] [REAL007617 Burroughs](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Burroughs) 2 dokumenter fra 1996 og 1997
- [x] [REAL001159 Cray](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Cray) 3 dokumenter fra 1991 og 1997

**Comment by danmichaelo** [comment]
(Lurer på om vi må dele opp denne i flere issues for at det ikke skal bli altfor uoversiktlig)

## Informatikk: Få masteroppgaver og/eller doktorgradsavhandinger

> [REAL007972 Selvbetjente banktjenester](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Selvbetjente%20banktjenester) 1 dokument (Prosjektoppgave i IN165?) fra 1996

Generalisert som `Selvbetjente systemer`.

> [REAL002261 Flytkontroll](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Flytkontroll) 1 masteroppgave fra 1999

Frister å beholde denne, stort emne selv om vi har lite litteratur om det.

> [REAL002599 Buss-bro](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Buss-bro) 2 masteroppgaver fra 1997

Slettet.

> [REAL002757 Sekvensiell prosessering](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Sekvensiell%20prosessering) 1 masteroppgave fra 2006

Slettet.

> [REAL004273	Hough-transformasjon](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Hough-transformasjon) 3 masteroppgaver fra 1988, 1989 og 1991

Beholdes. Kunne evt. vært generalisert som f.eks. "feature extraction techniques", men kommer ikke på noen norsk term i farten.

> [REAL003070 Programvaredistribusjon](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Programvaredistribusjon) 2 masteroppgaver fra 2006

Beholdes, stort emne.

> [REAL006134	Kodeoptimalisering](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Kodeoptimalisering) 1 doktorgradsavhandling fra 1985

Slått sammen med `Programoptimalisering` (og lagt på *optimering)

> [REAL008132 Knuth-bendix-algoritmen](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Knuth-bendix-algoritmen) 2 masteroppgaver fra 1992 og 1993 + 1 dokument fra 1984

Beholdes. Kunne kanskje vært generalisert, men ser ikke umiddelbart hva som ville være en passende generalisering. Forslag mottas med takk :)

> [REAL001363 Business process reengineering](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Business%20process%20reengineering) 1 masteroppgave fra 1995 + 1 dokument fra 1995

Slått sammen med `Endringsledelse`

**Comment by danmichaelo** [comment]
### Få, eldre dokumenter
> [REAL002161 Bruksmønstre]( https://app.uio.no/ub/emnesok/realfagstermer/search?term=Bruksm%C3%B8nstre) 1 dokument fra 2003.

Generalisert som `Bruksdata EN Usage data`. Kunne kanskje vært generalisert ytterligere som `Web analytics` e.l., har vi noen gode norske termer for det?

> [REAL008062 Runge–Kutta-metoder](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Runge%E2%80%93Kutta-metoder) 3 dokumenter fra 1964, 1965 og 1998

Beholdes, stort og viktig emne som vi sikkert egentlig har mer litteratur om.

> [REAL007337 Seriell kommunikasjon](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Seriell%20kommunikasjon) 2 dokumenter fra 1990 og 1993

Beholdes, stort og viktig emne som vi sikkert egentlig har mer litteratur om.

> [REAL002440 Kommandospråk](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Kommandospr%C3%A5k) 1 dokument fra 1976

Usikker, denne burde egentlig ha livets redd, men drukner kanskje litt i mer spesifikke emneord. Har i første omgang lagt inn `SO Skallprogrammering`.

> [REAL003647 Navnetjenere](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Navnetjenere) 1 dokument fra 1995

Beholdes, stort og viktig emne som vi sikkert egentlig har mer litteratur om.

> [REAL006559 Objektgjenkjenning](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Objektgjenkjenning) 2 proceedings fra 1997

Beholdes, stort og viktig emne som vi sikkert egentlig har mer litteratur om.

> [REAL006625 Simscript](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Simscript) 3 dokumenter fra 1963, 1968 og 1995

Lite språk som kun har historisk interesse, men helt greit å beholde som emneord syne sjeg.

> [REAL011662 Bull Gamma 60](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Bull%20Gamma%2060) 1 dokument fra 1997

Usikker. Vi har en del emneord om kjente datamaskiner etter Knut. De må sees i sammenheng.

> [REAL007617 Burroughs](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Burroughs) 2 dokumenter fra 1996 og 1997

Slettet.

> [REAL001159 Cray](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Cray) 3 dokumenter fra 1991 og 1997

Tror det holder med Tungregning / Superdatamaskiner som tematiske emneord. Og så kan Cray overføres til BARE.

**Comment by karolinehoff** [comment]
> (Lurer på om vi må dele opp denne i flere issues for at det ikke skal bli altfor uoversiktlig)

Lurt å formatere til sjekkliste! Men jeg er enig. Hvordan er det best at jeg melder fra om termer som kanskje bør vurderes fra nå? Jeg bare noterer dem underveis.

**Comment by karolinehoff** [comment]
Endret og styrte og stelte litt her i dag. Denne tråden ligger fremdeles under Mat-1 milepælen, men siden DMs kommentarer er til informatikktermene lar jeg dem ligge her. DM, kan du sette riktig milepæl på issuesene mine? Jeg har ikke riktige tillatelser.

**Comment by danmichaelo** [comment]
Fiksa milepæl -- og gitt deg tillatelser

**Comment by danmichaelo** [comment]
Lager en sak på hva vi gjør med Bull Gamma og andre gamle datamaskiner. Tror resten skal være ferdigbehandla.
