### ISSUE TITLE
International Biological Programme

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1485]
https://authorities.loc.gov/cgi-bin/Pwebrecon.cgi?AuthRecID=3749537&v1=1&HC=3&SEQ=20190110014110&PID=quNBWDCpXIVHwwgq72Awx_WnZ6FfR

Tror denne bør flyttes til et 610-emne

---
*REAL011627 (International Biological Programme) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011627), [Skosmos](http://data.ub.uio.no/realfagstermer/c011627), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22International%20Biological%20Programme%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL011627)*

**Comment by danmichaelo** [comment]
https://lccn.loc.gov/n79032843

Finnes også allerede i Bibsys, så flytter dit: 

https://authority.bibsys.no/authority/rest/authorities/html/90118137
