### ISSUE TITLE
Vegglus

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1488]
Skulle det vært Veggelus, ikke Vegglus?

---
*REAL000139 (Vegglus) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000139), [Skosmos](http://data.ub.uio.no/realfagstermer/c000139), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Vegglus%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000139)*

**Comment by Hypsibius** [comment]
Tydeleg vkulle det vere Veggedyr bf Veggelus :-P

![image](https://user-images.githubusercontent.com/9350370/51107043-f795fa00-17ed-11e9-877b-866fb0f43b8b.png)

**Comment by danmichaelo** [comment]
Hah! Slått sammen og endret
