### ISSUE TITLE
Misdannelser/Anomalier

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#149]
Det ser ut som disse kan slås sammen. OK, @BioHeidi @Hypsibius ?

**Comment by Hypsibius** [comment]
Anomalier kan dekke også veldig mykje anna? Det brukast eksempelvis om resultatmessige outliers

**Comment by BioHeidi** [comment]
Ja, se ihvertfall på trefflisten først. Begge emneordene bør finnes, men mulig de ikke er brukt konsekvent.

**Comment by bibliomari** [comment]
Aha. De bør kanskje defineres eller forholde seg til hverandre på noe vis, da?

**Comment by BioHeidi** [comment]
Misdannelser er for meg noe veldig konkret, mens anomalier er som Hege skriver brukt på flere forskjellige ting, så kanskje det må strenges dersom det skal brukes? Men en SO mellom er vel lurt.

**Comment by danmichaelo** [comment]
Hva med `Abnormaliteter`? Det ser ut som det samme som `Misdannelser`?

**Comment by bibliomari** [comment]
@BioHeidi @Hypsibius Kommentar til Abnormaliteter?

**Comment by Hypsibius** [comment]
Kan etter mi meining godt slåast saman, men med 'misdannelser' som foretrukken term

**Comment by BioHeidi** [comment]
Ja

**Comment by bibliomari** [comment]
Gjort
