### ISSUE TITLE
Steinkobbe

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1492]
Foreslår ubestemt flertall på emneordet

---
*REAL004457 (Steinkobbe) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004457), [Skosmos](http://data.ub.uio.no/realfagstermer/c004457), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Steinkobbe%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL004457)*

**Comment by Hypsibius** [comment]
Nope, dette er artsnamn. Jf 

![image](https://user-images.githubusercontent.com/9350370/51472269-4953fc80-1d79-11e9-84d1-d803fcf7fcd6.png)

vs

![image](https://user-images.githubusercontent.com/9350370/51472320-6688cb00-1d79-11e9-94e2-09ba71ca2122.png)
