### ISSUE TITLE
Vindussystemet X

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1493]
Vindussystemet X??
Vi har allerede Windows som real-term.
Rart å oversette et så etablert begrep?

---
*REAL007729 (Vindussystemet X) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007729), [Skosmos](http://data.ub.uio.no/realfagstermer/c007729), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Vindussystemet%20X%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL007729)*

**Comment by danmichaelo** [comment]
Haha, nei, det finnes en verden utenfor Windows. [Vindussystemet X](https://no.wikipedia.org/wiki/Vindussystemet_X) er noe annet. Egentlig heter det bare X, så kan være vi skulle brukt "X (vindussystem)" som oppslagsord i stedet.
