### ISSUE TITLE
B-celler

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1494]
Denne er duplikat og har dessuten bare den ene varianten :)

I samme slengen:
Ser at vi har T-lymfocytter som foretrukket term istedenfor T-celler, og ut ifra #1060 ble B-celler valgt her siden WP-siden hadde det. Så vi bør kanskje ha T-celler som foretrukket term her også? Ser at WP har det.

---
*REAL009381 (B-celler) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009381), [Skosmos](http://data.ub.uio.no/realfagstermer/c009381), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22B-celler%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009381)*

**Comment by danmichaelo** [comment]
Bra funn! :bulb: 

Fjernet duplikaten og endret så vi har

B-celler
BF B-lymfocytter

og 

T-celler
BF T-lymfocytter
