### ISSUE TITLE
Naturlig immunitet

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1495]
Legg til "Medfødt immunitet" på norsk :)

(Med mindre jeg har misforstått, da må de engelske termene jeg la inn bort.)

---
*REAL010552 (Naturlig immunitet) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010552), [Skosmos](http://data.ub.uio.no/realfagstermer/c010552), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Naturlig%20immunitet%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010552)*

**Comment by danmichaelo** [comment]
Ser riktig ut! Gjort :baby:
