### ISSUE TITLE
Immunoglobuliner

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1496]
Slå sammen med `Antistoffer` og legg til / endre til "Immunglobuliner" på norsk :)

---
*REAL002636 (Immunoglobuliner) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002636), [Skosmos](http://data.ub.uio.no/realfagstermer/c002636), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Immunoglobuliner%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002636)*

**Comment by danmichaelo** [comment]
:syringe: :+1: Gjort!
