### ISSUE TITLE
Immunocytokjemi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#1497]
Legg til / endre til "[Immuncytokjemi](https://sml.snl.no/immuncytokjemi)" på norsk :)

---
*REAL003112 (Immunocytokjemi) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003112), [Skosmos](http://data.ub.uio.no/realfagstermer/c003112), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Immunocytokjemi%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL003112)*

**Comment by danmichaelo** [comment]
:+1: Gjort!
