### ISSUE TITLE
Vertikalmigrasjon?

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1498]
Har vi et emneord for denne? Jeg kan ikke finne noe som dekker den. Hvis vi har ikke, jeg foreslår at den er opprettet, kanskje med termen diel med i der et sted også - føler at den er forskjellig nok fra Migrasjon. Jobber med [denne dok her](https://bora.uib.no/handle/1956/18837). @Hypsibius

**Comment by Hypsibius** [comment]
Det bør vi ha! Mykje studert både hos oss og ved UiO. 

Legg til BF Døgnvandringer? Eller, det er jo ikkje automatisk fullt overlapp, men. Nær nok? Alternativt omvendt, sidan vertikalmigrasjon er ein (av fleire) type døgnvandring? Ser stadig kråker på veg til eller frå jobb. Kråkene, altså...

**Comment by Caroline-A** [comment]
Ja jeg synes den er nært nok! Så kanskje - 
Døgnvandringer BF Vertikal migrasjon EN Daily migration EN Diel migration EN Vertical migration EN Diel vertical migration (OT: Migrasjon?)

**Comment by danmichaelo** [comment]
> Døgnvandringer BF Vertikal migrasjon EN Daily migration EN Diel migration EN Vertical migration EN Diel vertical migration (OT: Migrasjon?)

Ok, oppretta den slik. REAL032069
