### ISSUE TITLE
Andeskjell (slette/endre?)

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1499]
![image](https://user-images.githubusercontent.com/42732381/51542386-69f48300-1e5b-11e9-9900-6d7e6c2747a0.png)
Den er mappet i soksed til [en Lepas ](https://en.wikipedia.org/wiki/Lepas)/ [no Andeskjell](https://no.wikipedia.org/wiki/Andeskjell)

Men jeg er usikkert på om andeskjell er bare _Lepas_ på norsk - i følge [denne snl artikel ](https://snl.no/andeskjell) er det brukt for alt innen orden Pedunculata. 
På engelsk, [_Lepas_ er bare en type goose barnacle](https://eol.org/pages/43714) - goose barnacles er enten ([i følge eol](https://eol.org/pages/6965)) family Lepadidae, eller ([i følge wikipedia](https://en.wikipedia.org/wiki/Goose_barnacle)) order Pedunculata. På artsdatabanken heter Pedunculara [langhalser](https://www.artsdatabanken.no/Taxon/Pedunculata/150). 

For å komplisere ting videre - jeg sjekket [WORMS](http://www.marinespecies.org/aphia.php?p=taxdetails&id=106032), og orden Pedunculata var splittet i 2006, så eksistere ikke lengre taksonomisk. 

Det er bare to dok som har dette som emneord. Grunnen at jeg er inn på dette er at jeg jobbe med [denne](http://bora.uib.no/handle/1956/15831), som er om et art fra orden Pedunculata men er ikke en _Lepas_.

Jeg vet ikke hva er vanlig å gjøre med sanne saker @realfagstermer/bio. Jeg foreslår enten at den er slettet, eller at den er brukt koblet til orden Pedunculata (selv om den ekistere ikke taksonomisk) til å dekke alt under den (ink. Lepas). Hvis det er gjørt, den bør også ha NO: langhalser EN: stalked barnacles EN: gooseneck barnacles.

**Comment by Hypsibius** [comment]
Og UT Rur (REAL003211)

**Comment by BioHeidi** [comment]
Lurer på om vi kommer til å få så veldig mange dokumenter på dette? Jeg ser at ved sammenslåing av alt under Rankeføttinger (altså BF Rur og Andeskjell) så har vi vel 12 dokumenter, der en del omhandler rankeføttinger som gruppe eller krepsdyr generelt.

Så det foreslår jeg, altså Rankefotinger BF Rankeføttinger, Rur, Andeskjell, Rotkreps, LA Cirripedia, EN Barnacles osv osv nynorsk.

**Comment by Caroline-A** [comment]
Bra forslag synes jeg :) Hvis vi vil ha med flere vanlige grupper som BF foreslår jeg disse på EN:
EN Barnacles, Acorn barnacles, Goose barnacles, Gooseneck barnacles, Stalked barnacles, Rhizocephalans

**Comment by Hypsibius** [comment]
Istemmer. 'Rotkreps' var ny for meg (namnet, altså). Godt å ha eit norsk namn å vise til!

**Comment by danmichaelo** [comment]
Gjort! http://data.ub.uio.no/realfagstermer/c009851
