### ISSUE TITLE
Byer / urbane områder

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#150]
Trenge vi begge?

**Comment by BioHeidi** [comment]
Nei herfra. Vi har bl.a. Urban økologi, Byøkologi, Byer : Økologi som alle er brukt på samme emne. (begrep?)

**Comment by mittinatten** [comment]
Selv om byer høre mer norsk ut, tenker jeg "urban[e] ..." er bedre, siden det kanskje er litt bredere?

Hva med

    Urbane områder
    BF Byer
    BF Urban miljø
    EN Urban areas
    EN Cities

Og så strenger: `Urbane områder : økologi`, etc

**Comment by bibliomari** [comment]
Hm, hvis dere vil slå sammen de, vil nå iallfall jeg gjerne beholde Urban økologi, istedenfor streng.

Urban økologi
BF Byøkologi

@Violabibaluba

**Comment by danmichaelo** [comment]
Hva med `Tettsteder` i stedet for `Urbane områder`?  Synes det er en litt mer naturlig term på norsk, og betydningsmessig er det vel ok?

```
Tettsteder
BF Byer
BF Urbane områder
BF Urbane miljøer
EN Urban areas
EN Cities
```
og 
```
Urban økologi
BF Byøkologi
EN Urban ecology
```
Alle glade og fornøyde?

**Comment by mittinatten** [comment]
:+1:

**Comment by bibliomari** [comment]
Jeg har gjort den med økologien. 

Men hvorfor vil dere slå sammen Byer og Tettsteder? Jeg grøsser littegrann. Også fordi Humord har mye finere inndeling her. @Violabibaluba 

Vil dere liksom gjøre Digitale byer til Digitale tettsteder også da lizm, hæ?

**Comment by danmichaelo** [comment]
Litt fordi definisjonen av byer er så vanskelig å gripe, og varierer fra land. Og når jeg ser titler som "[Organising waste in the city](http://ask.bibsys.no/ask/action/show?pid=143267337&kid=biblio)" tenker jeg at dette sikkert er relevant for større tettsteder også.

Men det er jo et poeng at vi kanskje ikke trenger å fjerne oss mer fra Humord enn nødv. mtp. en evt. nasjonal tesaurusfremtid... LCSH har "Cities and towns", som vel også kan mappes mot Byer. Kanskje vi skal la det ligge, og bare omdøpe `Urbane områder` til `Tettsteder`? Eller blir det også feil?

**Comment by Hypsibius** [comment]
Hm, tettstad og by er IKKJE det same i mitt hovud. Tettstad er når det ikkje når opp til bystatus (skjønt, med dagens ordning har dei raraste tettstader gitt seg sjølv bystatus.... Tenkjer det heng saman med infrastruktur og planløysing...

**Comment by danmichaelo** [comment]
Tja...

**Comment by Hypsibius** [comment]
Om ein ser bort frå halve parentesar og sånt...

**Comment by Hypsibius** [comment]
Makes my head spin...

**Comment by danmichaelo** [comment]
Mitt også. SSBs tettsted-definisjon inkluderer byer, og er nok synonym med "Urbane områder".. Men det hjelper kanskje ikke så mye om *mange* tenker på byer som "ikke tettsteder" -- jeg merker at jeg til en viss grad gjør det selv :) 

Så vi får kanskje beholde Byer som eget begrep (i første omgang)? Men slår vi sammen Tettsteder og Urbane områder?

**Comment by Violabibaluba** [comment]
Jeg går for Byer BF Urbane områder. Urbane områder og tettsteder er vel ikke det samme. Tettsteder er mye mindre...?  Vi har bare to poster på Urbane områder og to poster på Tettsteder. Mange av dokumentene handler om Urban økologi. Men det kan jo komme dokumenter som handler om noe helt annet og da kan det være greit å skille byer og tettsteder, tenker jeg. Vi slår sammen Byer og Urbane områder.

**Comment by grosyn** [comment]
For å prøva å samkøyra oss med Humord, blei Vibeke og eg samde om å dela opp denne att i Byer og Urbane områder.
