### ISSUE TITLE
Mental helse

### ISSUE THREAD

**Issue by Gunvorev** [realfagstermer/realfagstermer#1501]
Jeg fant ikke denne termen og lurer på om den bør opprettes?

**Comment by danmichaelo** [comment]
Ser at [MESH](http://mesh.uia.no/) har oversatt "Mental health" med "Psykisk helse", så oppretter den "Psykisk helse" som foretrukket term og "Mental helse" som synonym:

```
Psykisk helse
BF Mental helse
BF Mentalhygiene
EN Mental health
EN Mental hygiene
```

Ok?

**Comment by danmichaelo** [comment]
http://data.ub.uio.no/realfagstermer/c032066

**Comment by Gunvorev** [comment]
Supert!!

Den ons. 23. jan. 2019, 12:55 skrev Dan Michael O. Heggø <
notifications@github.com:
