### ISSUE TITLE
Løst naturlig organisk materiale

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1502]
![image](https://user-images.githubusercontent.com/42732381/51615467-392e4f80-1f28-11e9-822a-66eb3861e489.png)
Jeg lurte på om det er en grunn det spesifiseres "naturlig" (DNOM)? Eller kan vi gjøre den litt breddere og inkludere Løst organisk materiale (EN DOM, dissolved organic matter)? Jeg føler at jeg har sett DOM brukt mye mer en DNOM i marin biologi.

**Comment by Hypsibius** [comment]
Same erfaring som @Caroline-A  

Foreslår: DOM BF Løst organisk materiale BF naturlig organisk materiale NN Løyst organisk materiale NN DOM NN Løyst naturleg organisk materiale SO Naturlig organisk materiale

PS: Marinbiologiar snakkar også om POM og PIM (partikulært, også inorganisk). Snakkar vi også om DIM?

**Comment by Caroline-A** [comment]
Jeg har ikke kom bort i DIM selv, for det meste POM og DOM (eller DOC).

**Comment by danmichaelo** [comment]
Høres lurt ut for en ikke-biolog i hvert fall, jeg endrer til 

```
Løst organisk materiale 
BF Løst naturlig organisk materiale
```
