### ISSUE TITLE
Vann formørkning?

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1503]
Jeg foreslår eget emneord for dok om [darkening of ocean waters](https://www.forskningsradet.no/no/Nyheter/Morkere_fjordvann_gir_ferre_fisk_og_flere_maneter/1253981562194/p1174467583739) (e.g. [denne](http://bora.uib.no/handle/1956/15376)). 
Jeg trenger litt hjelp for å finne en bra oversettelse på norsk - vann/marint formørkning? Formørking av kystvann? 
Hvis ja, jeg foreslår også at EN Chromophoric dissolved organic matter, EN colo(u)red dissolved organic matter, EN CDOM, EN gelbstoff er inkludert.

**Comment by Caroline-A** [comment]
Ja, jeg tenkte litt på linje som din tanke om Aksnes. Formørking er et effekt som skjer "på toppen" av vanlig attenuation, som osean varming pga klima endringer skjer på toppen av den vanlige temperatur gradienten. Etter min mening kunne det være greit å ha eget term for fenomenen, siden det er forsket på? Hva med:

- Eufotiske sonen BF Lyssonen BF Lyssvekking (i vann) EN Euphotic zone EN Photic zone EN Light attentuation (in water) SO [formørking foretrukket term]

- Vann/marint formørkning? Formørking av kystvann? EN Chromophoric dissolved organic matter EN Colo(u)red dissolved organic matter EN CDOM EN Gelbstoff SO Eufotiske sonen

Hva syns du? Eller skal begge konsept sammenslåes i et emneord?

**Comment by Hypsibius** [comment]
Denne må eg tygge litt på. Lyssvekking skjer jo ikkje så mykje I den fotiske sona som på veg gjennom fotisk sone og vidare nedover. Gulstoff/tanninar/humussyre vil vel vere mest aktuelt i brakt overflatevatn, eller i det minste dei øvre cm av fotisk sone. (idealisert døme under). 
http://oceanography-leahmoore.blogspot.com/2010/10/light-attenuation-for-various-colors-of.html

I det andre tilfellet sakkar vi jo også om ei eutrofiering :-/

This whole ting makes my head spin...

**Comment by BioHeidi** [comment]
Bør vi skille mellom komponentene som formørker vannet (eks CDOM) og selve formørkingen?
Også fint om emneordet kan brukes på tvers av akvatiske miljøer.

**Comment by Caroline-A** [comment]
Ja, jeg synes du er rett og det er best at de er skillt. Da kan man snakke om disse stoffer i andre sammenheng, og man kan snakke om formørkning uten en bestemt årsak.

- Eufotiske sonen BF Lyssonen EN Euphotic zone EN Photic zone 

- Vann formørkning? BF Formørking av kystvann? EN Darkening of coastal waters?

Disse CDOM termer (gulstoff, humusvann (?), CDOM, [humic substances/gelbstoff](https://www.sciencedirect.com/topics/earth-and-planetary-sciences/humic-substance)) er vanskligere enn jeg trodde... Jeg så nå at vi allerede har "huminsyre" (009698), "humus" (008954), og "humussfæren" (012114). ["Humus" er brukt mye, på dok](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc008954) som omhandler både soil organic matter og DOM/DNOM i akvatiske miljø. [Huminsyre er nesten ikke brukt](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc009698). Jeg ser at jeg ikke er kjent nok med faget til å si om det gir mening/om terminologi er riktig hvis vi skiller mellom humus/humic substances i jord vs. i vann som påvirker akvatiske miljø.

**Comment by danmichaelo** [comment]
Beklager, stanset litt opp her.

- Opprettet `REAL032074 Eufotisk sone BF Eufotiske sonen, Lyssonen ...`

- Opprettet `REAL032075 Vannformørkning BF Kystvannformørkning NN Vannformørking NN Vannmørking Kystvannformørking NN Kystvannmørking EN Water darkening EN Coastal water darkening`. Nynorsk ok, @Hypsibius ?

Skal vi legge inn noen se-også-henvisninger?

**Comment by Hypsibius** [comment]
Justering av NN: SS i staden for NN

NN VaSSformørking NN VaSSmørking KystvaSSformørking NN KystvaSSmørking

**Comment by danmichaelo** [comment]
Takk for korrektur! Ser så opplagt ut i etterkant :)

**Comment by Hypsibius** [comment]
Alltid ;-)
