### ISSUE TITLE
Merkatorpeilinger

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1504]
kun ett emne. Han heter Mercator og ikke Merkator, og finner ikke noe på peilinger, det eneste emnet jeg kan finne noe serlig på Mercator er Mercator projections, men antar at det ikke er det det henvises til her.  

---
*REAL003956 (Merkatorpeilinger) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003956), [Skosmos](http://data.ub.uio.no/realfagstermer/c003956), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Merkatorpeilinger%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL003956)*

**Comment by danmichaelo** [comment]
Fant heller ikke ut av det.. Boka har en del andre emneord, så jeg slettet denne.
