### ISSUE TITLE
Marine fisker + Saltvannsfisker

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1505]
![image](https://user-images.githubusercontent.com/42732381/51754181-edacaa80-20bb-11e9-8aaa-7f1dfaf4402a.png)
![image](https://user-images.githubusercontent.com/42732381/51754222-10d75a00-20bc-11e9-9fd5-43fc3b78f823.png)

Marine fisker BF Saltvannsfisker NN Marine fiskar NN Saltvassfiskar EN Marine fishes EN Saltwater fishes? (OT: Fisker?) :)

**Comment by danmichaelo** [comment]
Slo sammen Saltvannsfisker BF Marine fisker siden jeg tror den første termen er mer utbredt. Rop ut om dere helst vil ha Marine fisker som foretrukket term.

http://data.ub.uio.no/realfagstermer/c011465
