### ISSUE TITLE
Skjermarbeid

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1509]
Ingen treff. Beholde? Slette?

---
*REAL009905 (Skjermarbeid) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009905), [Skosmos](http://data.ub.uio.no/realfagstermer/c009905), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Skjermarbeid%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009905)*

**Comment by danmichaelo** [comment]
Slettet
