### ISSUE TITLE
Mrna, m-rna, mitokondrielt dna (?) ... ja, dere skjønner.

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#151]
Kan jeg slå sammen: 
m-rna
mrna
mithocondrial ribonucleic acid

... til hva?

OG: Hvordan henger de sammen med Mitokondrielt dna? SE OGSÅ, eller ikke noe?

@BioHeidi @Hypsibius

**Comment by mittinatten** [comment]
Det finnes miRNA (micro RNA), mRNA (messenger RNA) og tRNA (transfer RNA), flere? Ikke det samme som mitokondrielt RNA.

**Comment by bibliomari** [comment]
Djeeez, ja, jeg husker nå at det var noe sånn fryktelig ja. 

Mirna har faktisk et eget emneord, så den kan vi holde utenfor :)

**Comment by mittinatten** [comment]
Bra om de alle får formen `miRNA` og ikke `Mirna`, så blir det tydelig hva det handler om.

**Comment by BioHeidi** [comment]
Jeg får ikke lov å gi akronymet liten forbokstav... hjelp @knuthe ?

**Comment by danmichaelo** [comment]
Nå har vi jo fått lov til det i mellomtiden, så jeg fiksa `mRNA` og `miRNA`
