### ISSUE TITLE
Evolusjonsøkologi

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1512]
Dan Michael: denne har null treff på snevert søk, til info. Beholde?

---
*REAL009099 (Evolusjonsøkologi) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009099), [Skosmos](http://data.ub.uio.no/realfagstermer/c009099), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Evolusjons%C3%B8kologi%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009099)*

**Comment by danmichaelo** [comment]
Ja, @BioHeidi har jobbet en del med denne. Foretrukket term ble endret 8. feb:

2019-02-08T12:38:54Z	term: Utviklingsøkologi er endret til Evolusjonsøkologi

Så det er bare mismatch mellom autoritetene og katalogpostene akkurat nå. Når vi får kjørt almar blir det orden på det!
