### ISSUE TITLE
Eufotisk sone

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1513]
Dan Michael:
Denne har null treff, til info. Slette eller beholde?

---
*REAL032074 (Eufotisk sone) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c032074), [Skosmos](http://data.ub.uio.no/realfagstermer/c032074), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Eufotisk%20sone%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL032074)*

**Comment by Caroline-A** [comment]
Jeg satt den på noen dok i dag - jeg forslo oppretting av en annen term og den kom opp på samme tid (https://github.com/realfagstermer/realfagstermer/issues/1503) - jeg hadde ikke tid før nå å sette den på noe! :)

**Comment by vibekelundetrae** [comment]
Fint!
