### ISSUE TITLE
Marine brunalger

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1514]
Det er veldig få phaephyceae som lever i ferskvann - [<1%](https://www.sciencedirect.com/science/article/pii/B9780127415505500234). Derfor synes jeg at vi ikke trenger både brunalger og marine brunalger som emneord. Marine brunalger er brukt på to dok.
(kunne legge til LA Phaeophyceae på "brunalger" REAL013637 også hvis ønskelig)
![image](https://user-images.githubusercontent.com/42732381/52849153-a8a2f380-3110-11e9-900f-b3647c9a1344.png)

**Comment by danmichaelo** [comment]
Gjort! Takk!
