### ISSUE TITLE
Planteøkologi (komparativ, kvantitativ)

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1516]
![image](https://user-images.githubusercontent.com/42732381/52939468-8d302680-3364-11e9-9623-22b4a17f213a.png)
![image](https://user-images.githubusercontent.com/42732381/52939477-91f4da80-3364-11e9-877a-8129324cbc05.png)

Kvantitativ planteøkologi (_2 dok_) er oversatt (låst) som comparative plant ecology, men jeg tror den er egentelig oversettelsen av komparativ planteøkologi (_også 2 dok_). 

Jeg vet ikke hvor mye nytte disse emneord er, siden den er brukt så lite. Sammenslåes med planteøkologi/slettes - en god ide? Man har også "tropisk planteøkologi" REAL006709 som er brukt lite (_1 dok_).

**Comment by danmichaelo** [comment]
@realfagstermer/bio

**Comment by danmichaelo** [comment]
Gjort i samråd med @kyrretl :

- Endret `Kvantitativ planteøkologi` → `Kvantitativ økologi` og fikset oversettelsen. Alle bøkene hadde også 'Planteøkologi' som emneord fra før, så det går an (i fremtiden) å avgrense med kombinertsøk.

- Slettet `Komparativ planteøkologi`. 1 bok flyttet til `Komparativ økologi`, 1 til `Kvantitativ økologi` (feilplassert)

- Slettet `Komparativ biologi`. 2 bøker flyttet til `Komparativ økologi`.

- Slettet `Komparativ sansefysiologi`. 1 bok → `Komparativ fysiologi` + `Sansefysiologi`

- Slettet `Tropisk planteøkologi`. 1 bok → `Tropisk økologi` + `Planteøkologi`

**Comment by grosyn** [comment]
Prøver å finna ut kvifor Kvantitativ økologi blei sletta. Går det an å ta inn att? Hadde passa godt på Handbook of quantitative ecology.

@BioHeidi

**Comment by BioHeidi** [comment]
Jeg tror det ble slettet på grunn av veldig lite bruk. Enig i at det hadde vært en fin term til den! Eventuelt kunne vi brukt den overordnede termen Teoretisk økologi som ikke er så mye brukt. Og kanskje ryddet litt på den, fordi der ligger det noen dokumenter som ikke er typiske "teoretisk økologi"-bøker.

**Comment by grosyn** [comment]
Ok, då bruker eg Teoretisk økologi på den boka.

Ser at det kun er 7 postar (snart 8) der termen er bruka. Om du vil rydda i dei, må du gjerne det. Eg ser nok ikkje kva som er typiske Teoretisk økologi-bøker...
