### ISSUE TITLE
Reproducible research

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1517]
Sakser fra e-post:

@starseekr :
> ​Har vi et emneord på dette? Har prøvd alle norske variasjoner jeg kan komme på (etterprøvbarhet?), men finner ikkeno.

@BioHeidi :
> Nei, det har vi visst ikke, jeg finner heller ikke noe. Vi oppretter Etterprøvbarhet BF Reproduserbarhet og noen NN og EN.

**Comment by danmichaelo** [comment]
Oppretta:

```
REAL032076 Etterprøvbarhet
BF Reproduserbarhet
BF Etterprøvbar forskning
BF Reproduserbar forskning
NN Etterprøvbarheit
NN Reproduserbar forsking
NN Reproduserbarheit
NN Etterprøvbar forsking
EN Reproducability
EN Reproducible research
SO Vitenskapelig metode
```

**Comment by Hypsibius** [comment]
Re det ikkje 'Reproducibility' på engelsk?

Ellers, kan dette inngå som BF-term?

https://en.wikipedia.org/wiki/Replication_crisis

**Comment by danmichaelo** [comment]
Kan ikke alltid skrive rett :open_mouth: 

Rettet! Og la til "Replication crisis" au
