### ISSUE TITLE
Forskningsdata

### ISSUE THREAD

**Issue by starseekr** [realfagstermer/realfagstermer#1518]
Med forbehold for tidligere rot i dag, og at min søke-fu tydeligvis ikke er helt på topp: Har vi noe på forskningsdata? håndtering av? Åpen forskningsdata?

**Comment by danmichaelo** [comment]
Snodig, ser ikke sånn ut  :/ Vi har `Stordata`, men ikke alle forskningsdatasett er jo store!

Opprette både `Forskningsdata` og `Åpen vitenskap` kanskje?

**Comment by danmichaelo** [comment]
Hah, [`Vitenskapelige data`](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc007212) hadde vi faktisk fra før -- det var det som var den magiske søketermen! Men tror jeg utvider den en del så den blir lettere å finne -- og endrer foretrukket term til Forskningsdata

**Comment by danmichaelo** [comment]
Nå har vi

```
REAL032077 Forskningsdata
BF Forskningsdatahåndtering
BF Vitenskapelige data
NN Forskingsdata
NN Vitskaplege data
NN Vitskapelege data
EN Research data
EN Scientific data
EN Research data management
```

og

```
REAL032078 Åpen vitenskap
BF Åpen forskning
NN Open vitskap
NN Open forsking
EN Open science
EN Open research
SO Åpen tilgang
SO Åpen kildekode
SO Etterprøvbarhet
```

**Comment by starseekr** [comment]
Takk!

**Comment by sreuder** [comment]
Bra!
og takk!

**Comment by BioHeidi** [comment]
:+1:

**Comment by danmichaelo** [comment]
Vippet forresten litt frem og tilbake mellom Forskningsdata og Forskningsdatahåndtering som foretrukket term. Landet (inntil videre) på Forskningsdatahåndtering og la inn `SO Måledata`.
