### ISSUE TITLE
Havmus

### ISSUE THREAD

**Issue by kyrretl** [realfagstermer/realfagstermer#1519]
Legg gjerne til flere BF-termer på Havmus:
"havkatt, gullhå, hågylling, spelstrenghyse, levremus og levrekulp."

Hentet fra Wikipedia: https://no.wikipedia.org/wiki/Havmus

---
*REAL000147 (Havmus) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000147), [Skosmos](http://data.ub.uio.no/realfagstermer/c000147), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Havmus%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000147)*

**Comment by danmichaelo** [comment]
Lagt til! Droppet havkatt inntil videre siden den ikke var i Artsdatabanken: https://artsdatabanken.no/Taxon/Chimaera%20monstrosa/42464

**Comment by Hypsibius** [comment]
Og havkatt kan dessutan vere andre artar
