### ISSUE TITLE
Modulasjon, modulering

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#152]
...ser ut for meg som de kan slås sammen. Til Modulasjon. 

TEKORD har forresten Modualsering på samme post, kan jeg slenge på det også?

**Comment by mittinatten** [comment]
Google forteller at på nett er Modualisering mest brukt for Modularisering (skrivefeil?).

**Comment by bibliomari** [comment]
Skrivefeil ja, Modularisering :)

**Comment by bibliomari** [comment]
Men hovedspørsmålet var om Modulasjon = Modulisering

**Comment by mittinatten** [comment]
Ok :)

Modulasjon er noe annet enn Modul[ar]isering: http://no.wikipedia.org/wiki/Modulasjon_%28andre_betydninger%29

**Comment by bibliomari** [comment]
Takk :)

**Comment by danmichaelo** [comment]
Slik det er brukt i katalogen vår synes jeg det ser ut som `Modulasjon` og `Modulering` fint kan slås sammen. Skillet på no.wp ser mest ut som en løsning for å unngå kvalifikator :)

Egentlig enig i at `Modulasjon` er en bedre foretrukket term enn `Modulering`, men hvis vi velger den må også `Bølgemodulering`, `Frekvensmodulering` og `Pulskodemodulering` endres.

**Comment by mittinatten** [comment]
Både norske wikipedia og SNL bruker Modulasjon konsekvent, så det er kanskje ok å endre til det overalt.

**Comment by danmichaelo** [comment]
Ja, enig

**Comment by bibliomari** [comment]
Gjort. @mittinatten kan du lokarere Frekvensmodulering > Frekvensmodulasjon? Ingen poster hos oss, så da genereres heller ingen epost.
