### ISSUE TITLE
Hegrer

### ISSUE THREAD

**Issue by kyrretl** [realfagstermer/realfagstermer#1520]
Legge til Hegrefamilien som BF

Hegrer BF Hegrefamilien

---
*REAL002466 (Hegrer) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002466), [Skosmos](http://data.ub.uio.no/realfagstermer/c002466), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hegrer%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002466)*

**Comment by danmichaelo** [comment]
Gjort!
