### ISSUE TITLE
Hymeniesopper

### ISSUE THREAD

**Issue by kyrretl** [realfagstermer/realfagstermer#1524]
Hymenomycetes er ikke lenger en taksonomisk enhet, erstattet av Agaricomycotina

https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=14094#null

Hymeniesopper er vel fremdeles brukt, men føler at Agaricomycotina burde være knyttet til termen, legges til som LA? eller BF?

Siden Homobasidiomycetes er lagt til som BF bør og så Heterobasidiomycetes legges til som BF, siden dette er to praktiske inndelinger:

---
*REAL031217 (Hymeniesopper) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c031217), [Skosmos](http://data.ub.uio.no/realfagstermer/c031217), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hymeniesopper%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL031217)*

**Comment by kyrretl** [comment]
Ups, denne kom ikke med etter "praktiske inndelinger" https://snl.no/hymeniesopper

**Comment by kyrretl** [comment]
Og Holobasidiomycetes bør også legges til som BF

**Comment by danmichaelo** [comment]
Lagt til Heterobasidiomycetes og Holobasidiomycetes
