### ISSUE TITLE
Inkompatibilitet

### ISSUE THREAD

**Issue by kyrretl** [realfagstermer/realfagstermer#1525]
Foreslår Selvinkompatibilitet, begrepet ser ut til å brukes i biologien og inkompatibilitet er litt vel bredt.

https://www.mn.uio.no/ibv/tjenester/kunnskap/plantefys/genetikk/evolusjon.html#heterostyli

og

https://www.mn.uio.no/ibv/tjenester/kunnskap/plantefys/leksikon/s/selvinkompatib.html

---
*REAL007119 (Inkompatibilitet) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007119), [Skosmos](http://data.ub.uio.no/realfagstermer/c007119), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Inkompatibilitet%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL007119)*

**Comment by danmichaelo** [comment]
Fiksa! 

NN Sjølvinkompatibilitet
