### ISSUE TITLE
Prosjekter

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1526]
Flyttes til 610. Ligger som 110-autoritet i BARE

---
*REAL009101 (Mjølner-prosjektet) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009101), [Skosmos](http://data.ub.uio.no/realfagstermer/c009101), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Mj%C3%B8lner-prosjektet%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009101)*

**Comment by danmichaelo** [comment]
Mm, oppdaget nettopp at vi har en del prosjekter:

- [ ] Kult-prosjektet (nb)
- [ ] Mjølner-prosjektet (nb)
- [ ] Sydpol-prosjektet (nb)
- [ ] Sørpol-prosjektet (nn)

**Comment by BioHeidi** [comment]
Mapping-prosjektet
