### ISSUE TITLE
Backend-utvikling

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1527]
Ingen dokumenter på denne. Ny term?

---
*REAL032082 (Backend-utvikling) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c032082), [Skosmos](http://data.ub.uio.no/realfagstermer/c032082), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Backend-utvikling%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL032082)*

**Comment by danmichaelo** [comment]
Ja! Opprettelsesdato står nederst i Skosmos forresten: https://data.ub.uio.no/skosmos/realfagstermer/nn/page/c032082 , denne ble oppretta 21.02.2019
