### ISSUE TITLE
Vekster

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1528]
kunne man sett at man slo sammen denne med planter?  Og så litt på treffmengden om noe heller kunne flyttes til "vekst"?

---
*REAL010639 (Vekster) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010639), [Skosmos](http://data.ub.uio.no/realfagstermer/c010639), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Vekster%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010639)*

**Comment by BioHeidi** [comment]
Oisann, denne har visst en gang hett Vekst, for trefflisten ser veldig merkelig ut. Der har både fugl og fisk blitt planter.

Men jeg ser at for de treffene hvor det ville vært relevant med planteterm finnes det allerede, så jeg sletter.
