### ISSUE TITLE
Vitaminer

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1529]
Realfagstermer har Vitamin A, men B-vitamin.  Noen grunn til at det ikke er konsistent benevnelse?

---
*REAL007557 (Vitamin A) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007557), [Skosmos](http://data.ub.uio.no/realfagstermer/c007557), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Vitamin%20A%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL007557)*

**Comment by danmichaelo** [comment]
B-vitamin*er* ;) Ser ut som vi har vært konsekvente *innenfor* enkeltvitaminer og vitamingrupper:

<img width="567" alt="screenshot 2019-02-26 at 15 38 09" src="https://user-images.githubusercontent.com/434495/53420713-8fd1f200-39dc-11e9-85e4-2c8e5ddd05b8.png">

Men ja, godt poeng!

**Comment by danmichaelo** [comment]
Skal vi følge MESH? `Vitamin B-komplekset BF B-vitaminer` (og tilsv. for E-vitaminene)? Eller `Vitamin B BF B-vitaminer`?

![capture](https://user-images.githubusercontent.com/434495/53428351-ef36fe80-39ea-11e9-9735-ca0aa7097276.PNG)

**Comment by Hypsibius** [comment]
Altså, trur korrekt norsk er 'x-vitamin' og at 'vitamin x' er smitte frå engelsk. Sjekk denne snl-artikkelen som er grymt inkonsekvent: https://sml.snl.no/vitaminer

Finn ikkje at språkrådet uttalar seg direkte, men ser dei brukar 'C-vitamin' i døme.
https://www.sprakradet.no/sprakhjelp/Skriveregler/Stor_eller_liten_forbokstav/ 

Søk på vitamin A i Ordbøkene gir treff på A-vitamin: 
![image](https://user-images.githubusercontent.com/9350370/53558413-456d8400-3b48-11e9-9b9f-aec8c50564ec.png)

**Comment by danmichaelo** [comment]
Du sier noe!

**Comment by danmichaelo** [comment]
Endra til `A-vitamin BF Vitamin A`, `C-vitamin BF Vitamin C`

`B7-vitamin` høres litt rart ut, kanskje? Endra til `Biotin BF Vitamin B7`.
