### ISSUE TITLE
Flo, fjære og fjæresona

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#153]
Her ser det ut til at fleire begrep blir blanda saman (basert på trefflista)

Fjære, ubestemt form,  - oppfattar eg som *lavvann*. Altså Fjære BF lavvann

Men vi har 'fjære BF fjæresonen'

Foreslår at fjæra (bunden form, alternativt fjæren) brukast som hovudinnførsel, BF fjøresonen/fjøresona/fjæresonen/fjæresona, altså (grovt forenkla) området mellom fjæremål og flomål.

Så har vi såklart også Flo. Her bør vi legge til BF høyvann

Alternativt kan flo & fjære knyttast til tidevann. @bibliomari @BioHeidi @mzyg kva serier dokke?

**Comment by Hypsibius** [comment]
Tekt litt til, og vil utan atterhald gå for tidevann, BF flo, fjære, høyvann, lavvann (bør vi ha med nippflo, springflo?)

fjæra BF fjæresona, tidevannssona

Er litt raddis når eg skriv bokmål, eg, trass år i Bergen ;-)

**Comment by BioHeidi** [comment]
Er med på det! Jeg kan rydde litt i trefflisten til Fjære før vi slår sammen.

**Comment by Hypsibius** [comment]
Flott! Når det er manuell rydding i enkeltpostar, kan jo også eg utføre eitt og anna, det kan vi jo avtale. Så vi ikkje går i beina på kvarandre....
