### ISSUE TITLE
Viltforvaltning : Hjort

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1530]
Her bør vi kanskje slå sammen? Har også termen Hjort - Viltforvaltning :-)

---
*REAL020901 (Viltforvaltning : Hjort) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c020901), [Skosmos](http://data.ub.uio.no/realfagstermer/c020901), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Viltforvaltning%20%3A%20Hjort%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL020901)*

**Comment by danmichaelo** [comment]
Er ikke lett med rekkefølgen på disse strengene :D

**Comment by danmichaelo** [comment]
(Gjetter at `Hjort : Viltforvaltning` er mest riktig her, hvis vi ikke bare skal splitte den opp, som kanskje er like greit)

**Comment by BioHeidi** [comment]
Skal du splitte eller skal du rulle? (Ekstra Joker Nord)

**Comment by grosyn** [comment]
Strengene er sletta, så eg lukkar denne saka.
