### ISSUE TITLE
SAS statistikkpakke - har wiki fra SAS flyselskapet

### ISSUE THREAD

**Issue by starseekr** [realfagstermer/realfagstermer#1531]
SAS 
Statistikkpakke
English: SAS (Brukt for: Statistical Analysis System)
Nynorsk: SAS

https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc003291

**Comment by danmichaelo** [comment]
Huhu, ja, kjent problem. Det er *egentlig* allerede fikset i utviklingsversjonen av Emnesøk:

https://github.com/scriptotek/emnesok/commit/e2788ba9c165ff4b4610ffada7bfcb68c5209c23

Må bare få gjort et par ting til før jeg deployer den...
