### ISSUE TITLE
Kjemisk bekjempelse

### ISSUE THREAD

**Issue by kyrretl** [realfagstermer/realfagstermer#1532]
Dette er ikke et særlig bra emneord og den éne boken den refererer til handler mer om hormoner/feromoner som insektene selv produserer:

https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000992

https://www.sciencedirect.com/book/9780120930500/chemicals-controlling-insect-behavior (mulig bak brannmur)

Foreslår at vi sletter dette emneordet

---
*REAL000992 (Kjemisk bekjempelse) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000992), [Skosmos](http://data.ub.uio.no/realfagstermer/c000992), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kjemisk%20bekjempelse%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000992)*

**Comment by Hypsibius** [comment]
Insekta får også tyn i denne (snek NN) :-O

![image](https://user-images.githubusercontent.com/9350370/53558693-d3496f00-3b48-11e9-8c63-fa7862fb98ec.png)

V behov får vi heller opprette BF-termar under denne eller legge til ein UT m Insekticid

**Comment by BioHeidi** [comment]
Ser at Kjemisk bekjempelse er flyttet til BF-term under Insektbekjempelse, men for denne boken blir det ikke helt riktig da.

**Comment by Caroline-A** [comment]
Kan kjemisk bekjempelse ikke også brukes for e.g. bekjempelse av sopp?

**Comment by Hypsibius** [comment]
Eller lakselus :-/

**Comment by danmichaelo** [comment]
> Ser at Kjemisk bekjempelse er flyttet til BF-term under Insektbekjempelse, men for denne boken blir det ikke helt riktig da. Eller jo, ved nærmere ettersyn, det handler om pest control der også.

Slo de bare sammen for å flytte boka, men beholdt ikke termen som BF fordi Kjemisk bekjempelse i seg selv omfatter mye mer enn Insektsbekjempelse.
