### ISSUE TITLE
Populasjonsstudier

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1533]
![image](https://user-images.githubusercontent.com/42732381/53413883-9a38bf80-39cd-11e9-83f6-592b1e667a2d.png) (2 dok)
Lurer på om populajsonsstudier er nyttig som emneord? Den er sjelden brukt, og jeg tror den kan være vanskelig å bruke uten en av de andre populasjons-emneord i tillegg (biologi, dynamikk, genetikk, modeller, regulering, stuktur, tetthet, økologi). Vi har også bestandsanalyser, som er ganske likt (sammenslåing)?
![image](https://user-images.githubusercontent.com/42732381/53413875-90af5780-39cd-11e9-9407-0cb2c13393a3.png) (37 dok)

**Comment by Hypsibius** [comment]
Istemmer

**Comment by BioHeidi** [comment]
Gjort!
