### ISSUE TITLE
Elver : Økologi

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1534]
Trenger man både denne og "Elveøkologi"?

---
*REAL016913 (Elver : Økologi) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c016913), [Skosmos](http://data.ub.uio.no/realfagstermer/c016913), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Elver%20%3A%20%C3%98kologi%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL016913)*

**Comment by danmichaelo** [comment]
Nei, vi har dessverre en god del sånne. Det beste hadde vært hvis vi kunne fått en henvisning fra Elver : Økologi til Elveøkologi, men det er litt vrient med Sonja.

**Comment by BioHeidi** [comment]
Gjorde det enkelt på denne med bare ett treff, la inn Elveøkologi istedet for Elver : Økologi på posten og slettet strengen.

Hvis det nå bare hadde vært like lett å fikse de postene som har både Elver og Økologi!

**Comment by grosyn** [comment]
Har fiksa postane som har Elver og Økologi - tok vekk termane og erstatta med Elveøkologi. (Var snakk om 34 postar.)
