### ISSUE TITLE
Elveøkologi og Lotiske samfunn

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1535]
@realfagstermer/bio , hva tror dere om REAL002868 (Lotiske samfunn) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002868), [Skosmos](http://data.ub.uio.no/realfagstermer/c002868)? Ser ikke ut til å være en mye brukt term. Kan den slås sammen med [Elveøkologi](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc004223)?

**Comment by BioHeidi** [comment]
Åh, lotisk og lentisk økologi... her fant jeg motsatsen til geologenes mafisk og felsisk! :D 

Men ja. Slår sammen.

**Comment by BioHeidi** [comment]
La også til Rennende vann.

**Comment by Hypsibius** [comment]
Litt skummelt når ein berre huskar orda og klangen og ikkje betydninga. Kva skulle vi gjort utan Google
