### ISSUE TITLE
Interaksjoner

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1536]
Veldig generelt. Vi prøver å rydde katalogpostene over på mer spesifikke emneord slik at vi kan slette denne.

Her er en ferdig almar-snutt til @BioHeidi :

    almar interactive 'Interaksjoner' 'Økologiske interaksjoner' 'Trofiske interaksjoner' 'Legemiddelinteraksjoner'

**Comment by grosyn** [comment]
Kan ein legga til Kjemiske interaksjoner? T.d. MMSID 990305064764702201

**Comment by grosyn** [comment]
21 dok. å retta opp i.

**Comment by BioHeidi** [comment]
Emneordet Interaksjoner kan slettes på alle fire.

**Comment by Hypsibius** [comment]
Kan det? Betyr det at vi står att med "trogfiske", eller tenkte eg dumt no? På eit tidspunkt uttrykte vi sånt med "interaksjoner: Økologi", interaksjoner: Legemidler", er det heilt ut?

**Comment by BioHeidi** [comment]
Det jeg mente er at på alle fire dokumentene som står igjen med "Interaksjoner" som emneord, kan Interaksjoner slettes fra posten uten at det går ut over gjenfinningen. De trenger ikke å få en egen interaksjonsterm.

**Comment by grosyn** [comment]
Ja, @Hypsibius, strenger er heilt ut. Dei blei avvikla i september i fjor.

**Comment by grosyn** [comment]
Har sletta Interaksjoner på postane, og sletta emnetermen.
