### ISSUE TITLE
Klassikere og Kanoner

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1537]
[Klassikere](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Klassikere) og [Kanoner](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Kanoner%20(litteratur)): Fristende å slå sammen, men… hm…

**Comment by Hypsibius** [comment]
Meeen er det ikkje då vi brukar kanon i eintal? Og, ein kanon består av eit visst subsett klassikarar? #idetkverulantiskehjørnet

**Comment by grosyn** [comment]
Får ikkje lenger treff på Klassikere i emnesøket. Eg endra Kanoner (litteratur) til Kanon (Litteratur), etter mønster frå Humord.
