### ISSUE TITLE
Stiftlav

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#1539]
Trenger dette egentlig være et emne på de to katalogpostene? de virker mye mer overordnede enn det emnet stiftlav tilsier. 

---
*REAL004032 (Stiftlav) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004032), [Skosmos](http://data.ub.uio.no/realfagstermer/c004032), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Stiftlav%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL004032)*

**Comment by Hypsibius** [comment]
Enig

**Comment by BioHeidi** [comment]
Enig. Er nok fordi det er en viktig signalart. Sletter.
