### ISSUE TITLE
Molekylfysikk = Molekylær fysikk? 

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#154]
Molekylspektra = Molekylære spektra?

Molekylstruktur = Molekylær struktur?

osv i lange baner :)

**Comment by mittinatten** [comment]
Molekylfysikk syns jeg er en logisk og tydelig sammensetning, molekylær fysikk høres litt rart ut, men kan kanskje være BF. Det samme gjelder de andre.

**Comment by BioHeidi** [comment]
Molekylstruktur. Er alt jeg har å si i dag.

**Comment by mzyg** [comment]
Kanskje molekyfysikk BF molekularfysikk ?

**Comment by mittinatten** [comment]
Noen flere
* `Molekylspektra BF Molekylære spektra`
* `Molekylmodellering BF Molekylmodeller`
* `Molekylæregeler` slettes? (eller rettes)
* `Molekylære systemer BF Molekylsystemer`
* `Molekylkrefter` diskuteres sammen med #167
* `Molekylære interaksjoner` slettes?
* `Molekylreaksjoner` slettes (evt `Kjemiske reaksjoner BF Molekylreaksjoner`)

**Comment by danmichaelo** [comment]
Den eneste jeg er litt usikker på er "Molekylmodeller". Jeg tenker da umiddelbart på sånne fysiske modeller:
![Molekylmodell](https://upload.wikimedia.org/wikipedia/commons/c/ca/Proline_model.jpg)

Det kan løses med en definisjon på "Molekylmodellering" som f.eks. "Modellering av molekylers struktur og reaksjoner med teoretiske metoder" ?

Og kanskje en se-henv. til form-emenordet `Molekylbyggesett`? (Hvor har det blitt av forresten? Det ligger på http://ask.bibsys.no/ask/action/show, men finner det ikke i Roald)

**Comment by danmichaelo** [comment]
Enig i sletting av `Molekylæregeler` (`Geler` får holde), `Molekylære interaksjoner` og `Molekylreaksjoner` forresten

**Comment by mittinatten** [comment]
Kanskje molekylbyggesett er en form? ;)

**Comment by danmichaelo** [comment]
Fant det ikke under form heller :p

**Comment by mittinatten** [comment]
Glemte å svare på spørsmålet, jeg syns definisjonen er bra, og se-henvisning er logisk.

**Comment by bibliomari** [comment]
Ryddet. Lagt inn Molekylbyggesett som form. Men får ikke lov til å legge se også fra emne til form.

Ang. definisjon @danmichaelo, jeg la til det du skrev, men kan du dobbelsjekke at Molekylmodeller og -modellering nå har en klart atskilt betydning??

**Comment by mittinatten** [comment]
Databaserte molekylmodeller kan vel også gå inn under Molekylmodellering?

**Comment by danmichaelo** [comment]
Jeg mener at de bør slås sammen. Skillet nå er veldig uklart. Beregninger kan gjøres på fysiske modeller og datamodeller, selv om datamodeller er dominerende i dag.

Litteraturen som er merket med Molekylmodeller nå ser heller ikke ut til å stemme med definisjonen.

Hvis vi skulle hatt et skille tenker jeg at det kunne vært mellom Molekylmodellering og Molekylvisualisering. Men vi har allerede Molekylgrafikk, som jeg tror dekker det sistnevnte behovet.

**Comment by danmichaelo** [comment]
Sånn, da har vi Molekylmodellering BF Molekylmodeller. Og så har vi Molekylbyggesett som form fra før.
