### ISSUE TITLE
Skriveteknikker vs Vitenskapelig forfatterskap

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1540]
[REAL011577 Vitenskapelig forfatterskap](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc013512) har allerede blitt slått sammen med "Faglig skriveteknikk" og en del andre termer.

Skal vi også flette inn [REAL011577 Skriveteknikker](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011577) eller vil vi prøve å heller etablere et tydelig skille? I så fall, hvor? Ser ut som det er mye overlapp i hvordan de er brukt.

Fristet til å slå de sammen og heller på sikt flytte ut noen dokumenter som har eller kan få spissere emneord.

**Comment by Hypsibius** [comment]
Synest vi kan slå saman, og som du seier, evt seinare skille ut nokre spissare termar

**Comment by BioHeidi** [comment]
Enig.

**Comment by danmichaelo** [comment]
Gjort.
