### ISSUE TITLE
Språktester

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#1542]
Intern note: Trenger til bruk for TOEFL test
Noen som husker hva det var? Kan termen slettes nå? 0 dok.

**Comment by Hypsibius** [comment]
Eg veit i alle fall godt kva ein TOEFL er/var.  Test of English as a Foreign Language. Vi har hatt bøker her på det, men kan ikkje huske å ha fått spm om det på ei stund. Er alt ope og elektronisk no?

**Comment by danmichaelo** [comment]
Den er i bruk i strengen `Engelsk språk : Språktester` ;)

https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc019118

Meneh..

**Comment by Hypsibius** [comment]
Meneh!
