### ISSUE TITLE
Marihuana

### ISSUE THREAD

**Issue by kyrretl** [realfagstermer/realfagstermer#1543]
Slås sammen med Hasj?

Vi har alt Hamp for planten:
https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc004363

Og hasj:
https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc004443

som ser ut til å inneholde bare bøker om rusmiddelet, men jeg ser ikke noe klart skille mellom hasj og marihuana blant disse bøkene og det er vel ikke så nøye å ha et skille i et realfagsemneordsregister!

---
*REAL001401 (Marihuana) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c001401), [Skosmos](http://data.ub.uio.no/realfagstermer/c001401), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Marihuana%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL001401)*

**Comment by Hypsibius** [comment]
Skulle eg tru. Er ikkje det berre eit spørmål om plantedelar, uansett?

**Comment by BioHeidi** [comment]
Gjort. La også til Cannabis selv om det egentlig er både virkestoffet og planten. Tenker det til vårt formål er greit. Dokumentene som omhandler planten/botanikken/dyrking har fått emneordet Hamp.
