### ISSUE TITLE
Etnobiologi : Museumsteknikk

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1544]
Ingen dokumenter tilknyttet. Slette?

---
*REAL031736 (Etnobiologi : Museumsteknikk) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c031736), [Skosmos](http://data.ub.uio.no/realfagstermer/c031736), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Etnobiologi%20%3A%20Museumsteknikk%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL031736)*

**Comment by Hypsibius** [comment]
Gjerne for meg!

**Comment by BioHeidi** [comment]
Gjort!
