### ISSUE TITLE
Undervisning : Naturvitenskap

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1545]
Her har vi også Naturvitenskap : undervisning. Slette den ene?

---
*REAL019834 (Undervisning : Naturvitenskap) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c019834), [Skosmos](http://data.ub.uio.no/realfagstermer/c019834), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Undervisning%20%3A%20Naturvitenskap%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL019834)*

**Comment by Hypsibius** [comment]
Definitivt. Sidan vi allreie er innan  realfaga, og det potensielt kan radiere voldsomt, synest eg det ville vere meir logisk med Undervisning: Naturvitenskap enn omvendt

**Comment by BioHeidi** [comment]
Vi har en del strenger som kunne vært slått sammen, i tillegg til strenger og fraser som også kunne vært slått sammen. Men det tekniske her er ikke rett frem. Kanskje @danmichaelo vil utdype.

**Comment by Caroline-A** [comment]
Jeg har også lagt merke til at her er det ikke konsistent om det er streng eller egen term med undervisning. For eksempel, vi har "biologiundervisning" (REAL032095), og en del andre (kjemi, fysikk, geografi, språk, informatikk, universitets). Men et par av disse har både streng og egen term, e.g.
Naturfagsundervisning (REAL012662) + Undervisning : Naturvitenskap (REAL019834) 
Matematikkundervisning (REAL009721) + Matematikk : Undervisning (REAL020542)

**Comment by danmichaelo** [comment]
I det minste har vi ikke `Matematikkundervisning : Undervisning` 🙄 

Har slettet `Undervisning : Naturvitenskap` forresten. Litt usikker på om Naturfagsundervisning og `Naturvitenskap : Undervisning` kan slås sammen. Naturfag er jo et fag i grunnskolen. Ser at den har fått engelsk terme `Science education`, som antakelig egentlig er en bredere term. `Naturvitenskap : Undervisning` er muligens en slettekandidat.

Har lagt merke til at vi ikke er konsistente, men har liksom sett for meg at vi en dag kunne få til henvisninger fra sammensatte termer til strenger slik de har i LCSH (eks: http://id.loc.gov/authorities/subjects/sh85118587.html `Science : Study and teaching BF Science education`. Meen så var det dette med å unngå å la det beste være det godes fiende da! Så nå slettet jeg `Matematikk : Undervisning` og omklassifiserte med Almar:

    almar --rem 'Matematikk : Undervisning' --add 'Matematikkundervisning'

Vi kan altså omklassifisere ganske enkelt med almar, men vi får ikke hjelp fra Sonja til å generere kommandoen.

(Vi er heller ikke helt konsistente i delingen mellom undervisning/didaktikk/pedagogikk tror jeg)

**Comment by Hypsibius** [comment]
Oh well. Det beste og det gode og alt det der!
