### ISSUE TITLE
Gyting

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1549]
Gyting (REAL005471) - Den er låst i soksed, men ser at gyteområder er med. Kan vi legge til:
EN Spawning
EN Spawning areas
EN Spawning grounds
Den kunne også utfleskes med BF Gytefelt?
![image](https://user-images.githubusercontent.com/42732381/54417365-3e2aa680-4702-11e9-89ca-6f58f29bcb61.png)

**Comment by danmichaelo** [comment]
Gjort!
