### ISSUE TITLE
Vekselvarme dyr

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1553]
Ingen dokumenter her. Opprettet 2014. Beholde?

---
*REAL007941 (Vekselvarme dyr) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007941), [Skosmos](http://data.ub.uio.no/realfagstermer/c007941), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Vekselvarme%20dyr%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL007941)*

**Comment by BioHeidi** [comment]
Har nettopp gjort noe med denne... og da var det dokumenter på? Så rart?

**Comment by vibekelundetrae** [comment]
https://app.uio.no/ub/emnesok/realfagstermer/search?lang=nb&uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc007941  Ingen dokumenter med snevert søk her?

**Comment by Hypsibius** [comment]
Er også temleleg sikker på å ha brukt denne. Hikke?

**Comment by danmichaelo** [comment]
Kjent problem dessverre. Det tar jo typisk noen uker fra vi gjør endringer til en ny autoritetsfil blir importert inn i Alma. I mellomtiden blir den gamle termen hengende igjen på katalogpostene, noe som gjør at den ikke dukker opp i søk (det hadde løst seg om vi kunne søke på term-ID i Oria, men det kan vi ikke).

Det hjelper faktisk ikke at vi endrer den heller, for Alma "retter" den da pent tilbake til den gamle versjonen førstkommende natt (minner om redigeringskriger på Wikipedia).

Bibsys er på saken og inntil videre må vi bare leve med dette.

I dette tilfellet er det `Vekselvarme` som ligger på katalogposten
