### ISSUE TITLE
Vitenskapelig forfatterskap : Matematikk

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1554]
Null treff. Opprettet 2015. Beholde?

---
*REAL024700 (Vitenskapelig forfatterskap : Matematikk) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c024700), [Skosmos](http://data.ub.uio.no/realfagstermer/c024700), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Vitenskapelig%20forfatterskap%20%3A%20Matematikk%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL024700)*

**Comment by danmichaelo** [comment]
Dette er faktisk et eksempel på en streng som kunne vært litt nyttig :) Vi har allerede [Vitenskapelig forfatterskap : Biologi](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Vitenskapelig%20forfatterskap).  Det er noen treff i bredt søk som kunne vært flytta over.

**Comment by grosyn** [comment]
Lukkar denne, då strengene er sletta.
