### ISSUE TITLE
Mosevegetasjon

### ISSUE THREAD

**Issue by kyrretl** [realfagstermer/realfagstermer#1555]
Moser BF Mosevegetasjon?

Vi har to bøker om Mosevegetasjon, er det vesentlig å skille Moser fra Mosevegetasjon?

---
*REAL008576 (Mosevegetasjon) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008576), [Skosmos](http://data.ub.uio.no/realfagstermer/c008576), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Mosevegetasjon%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008576)*

**Comment by BioHeidi** [comment]
Nei. Mosevegetasjon høres litt oppkonstruert ut, så vi slår sammen disse og sletter mosevegetasjon.

**Comment by danmichaelo** [comment]
Gjort
