### ISSUE TITLE
Vitenskapsformidling : Sosiale medier

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1556]
INgen treff. Beholde? Slette? Opprettet 2016

---
*REAL031614 (Vitenskapsformidling : Sosiale medier) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c031614), [Skosmos](http://data.ub.uio.no/realfagstermer/c031614), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Vitenskapsformidling%20%3A%20Sosiale%20medier%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL031614)*

**Comment by Hypsibius** [comment]
Er vi sikre på at null treff betyr null treff? Jf 'vekselvarme dyr'? Ingen hikke i systemet?

**Comment by danmichaelo** [comment]
Ja, denne er gammel.  Og almar fant heller ingen dokumenter.

Slettet
