### ISSUE TITLE
Vitenskap : Religion og vitenskap

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1557]
Opprettet 2015. Ingen dokumenter. Slette?

---
*REAL031394 (Vitenskap : Religion og vitenskap) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c031394), [Skosmos](http://data.ub.uio.no/realfagstermer/c031394), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Vitenskap%20%3A%20Religion%20og%20vitenskap%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL031394)*

**Comment by Hypsibius** [comment]
Denne er uansett lodden, to say the least! Slett gjerne for min del!

**Comment by danmichaelo** [comment]
Slettet! Sammen med `Evolusjon : Religion og vitenskap`
