### ISSUE TITLE
Mårfamilien

### ISSUE THREAD

**Issue by kyrretl** [realfagstermer/realfagstermer#1558]
Slå sammen?
Mårfamilien BF Mårdyr

Nå er de to separate emneord

---
*REAL009327 (Mårfamilien) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009327), [Skosmos](http://data.ub.uio.no/realfagstermer/c009327), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22M%C3%A5rfamilien%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009327)*

**Comment by BioHeidi** [comment]
Ja!

**Comment by danmichaelo** [comment]
Gjort!
