### ISSUE TITLE
Naturskoger

### ISSUE THREAD

**Issue by kyrretl** [realfagstermer/realfagstermer#1559]
Urskoger BF Naturskoger

Er ikke dette synonymer?

---
*REAL010451 (Naturskoger) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010451), [Skosmos](http://data.ub.uio.no/realfagstermer/c010451), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Naturskoger%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL010451)*

**Comment by BioHeidi** [comment]
Jo. Disse slår vi sammen.

**Comment by danmichaelo** [comment]
SNL skiller mellom naturskog (som i liten eller ubetydelig grad er påvirket av mennesker) og urskog (etter streng definisjon helt urørt skog), men de er jo i hvert fall nesten-synonymer. Slår sammen.
