### ISSUE TITLE
Studiebøker

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1560]
er dette egentlig et innholdbeskrivende emne?Ser ut som det er brukt mer som form. Endre eller slette?

---
*REAL000281 (Studiebøker) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000281), [Skosmos](http://data.ub.uio.no/realfagstermer/c000281), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Studieb%C3%B8ker%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL000281)*

**Comment by Hypsibius** [comment]
Her ligg det jo ved ein merknad om at dette er study-guides, så definitivt ein formterm. Men tenkjer termen ikkje er sjølvforklarande. Betre m studentguide eller studentveiledning? 

Oooog, det viste det seg vi OGSÅ hadde, då eg slo det opp: Studentveiledning (REAL003081) 

Kva med å slå saman t Studentveiledning bf Studiebøker? Eller  er 'studiebøker' rett og slett ebrre ein forvirrande term?

**Comment by danmichaelo** [comment]
Nei, synes ikke de bør slås sammen.

* `Studentveiledning` ser ut som bøker for oss (om hvordan *vi* som bibliotekarer (eller forelesere eller andre) kan veilede studenter). 

* `Study guides` tenker jeg er for studenter (med f.eks. tips til hvordan man skal jobbe med et emne (kompendium til pensum), ekstra oppgaver eller løsningsforslag, studieteknikk e.l.). Men tror ikke studiebøker er en veldig etablert term på norsk. Ordnett bruker Studiehåndbøker, som vi også har. Slår sammen `Studiehåndbøker BF Studiebøker` (som form, ikke emne).

**Comment by danmichaelo** [comment]
Ok? Eller skal vi endre noe mer?
