### ISSUE TITLE
Svovelorganiske forbindelser

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1561]
Her er det noe rart. Sjekk REAL008471 og REAL008666

Er ikke dette to termer med helt likt navn? Den ene er mappet. Jeg gjør ikke noe med den andre foreløpig.

---
*REAL008666 (Svovelorganiske forbindelser) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008666), [Skosmos](http://data.ub.uio.no/realfagstermer/c008666), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Svovelorganiske%20forbindelser%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL008666)*

**Comment by BioHeidi** [comment]
De er fortsatt der begge to...

**Comment by danmichaelo** [comment]
![440](https://user-images.githubusercontent.com/434495/57073568-bdd7f900-6ce1-11e9-9236-149a5e763b20.gif)
