### ISSUE TITLE
Vannbalanse, Vanntransport, Væsketransport

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#1563]
Kan vi slå sammen disse tre? Med unntak av ett dokument er de brukt på vanntransport og væskebalanse i biologiske systemer.

**Comment by BioHeidi** [comment]
Og ref  #1263

**Comment by Hypsibius** [comment]
Gjerne for meg, om vi berre held denne utanom: Vannbalanse (hydrologi) (REAL011678)

Hege
