### ISSUE TITLE
Reaksjoner

### ISSUE THREAD

**Issue by kyrretl** [realfagstermer/realfagstermer#1564]
Syns dette er et for generelt begrep. De fleste postene ser ut til å handle om kjemiske reaksjoner (som er egen term) e.l. resten kan vi koble til andre emneord/slette.

Ryddejobb...

---
*REAL004745 (Reaksjoner) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004745), [Skosmos](http://data.ub.uio.no/realfagstermer/c004745), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Reaksjoner%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL004745)*

**Comment by danmichaelo** [comment]
Denne har jeg hatt lyst å slette før. Det er bare litt over 100 bøker, og mange er rett-frem. Jobber meg gjennom dem:

almar interactive 'Reaksjoner' 'Reaksjonsdynamikk' 'Kjemiske reaksjoner' 'Gassreaksjoner' 'Reaksjonskinetikk' 'Kjemiske reaktorer' 'Kjemiske prosesser' 'Organiske reaksjoner' 'Reaksjonsmekanismer' 'Enzymkinetikk' 'Metalloproteiner' 'Diels–Alder-reaksjonen' 'Overflatekjemi' 'Materialkjemi' 'Kaotiske systemer' 'Elektrodereaksjoner' 'Gastronomi'
