### ISSUE TITLE
Legge til Form Pseudovitenskap på bøker som fortjener det

### ISSUE THREAD

**Issue by kyrretl** [realfagstermer/realfagstermer#1565]
For å skille bøker som er skrevet av en kreasjonist fra bøker som ikke har en religiøs agenda (f.eks. de som omhandler kreasjonisme/evolusjons-debatten eller bøker som i avkrefter kreasjonisme/intelligent design fra et vitenskapelig ståsted)

---
*REAL006581 (Skjebne) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006581), [Skosmos](http://data.ub.uio.no/realfagstermer/c006581), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Skjebne%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL006581)*

**Comment by Hypsibius** [comment]
I'm all in! Har beholdt nokre sånne, dom eksempel på kor hårreisande slik litteratur er

**Comment by grosyn** [comment]
Humord har denne som innholdsbeskrivende emneord. Eg endrer difor vår òg frå 155 til 150.
