### ISSUE TITLE
Skiensvassdraget

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#1566]
Flyttes til 630 eller hvor det var

**Comment by Hypsibius** [comment]
Ikkje lite å skulle flytte eit heilt vassdrag ;-) https://forskning.no/norges-forskningsrad-geofag-miljoteknologi/nar-elva-flytter-seg-sideveis/1024580

**Comment by danmichaelo** [comment]
@BioHeidi Sted? 651

Fiksa. Trysilvassdraget også.
