### ISSUE TITLE
Fjørfe

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1567]
Jeg kan ikke finne noe om fjørfe i realfagstermer. Jobber med [bøk om Husdyrlære ](https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71467931640002201&context=L&vid=UBB&search_scope=default_scope&isFrbr=true&tab=default_tab&lang=no_NO).

Vi har hønsefulger (REAL006972), men det er ikke helt det samme tror jeg? Hvis nei, foreslår jeg:
Fjørfe BF Høns Høner ...? NN ...? EN Poultry Hens Chickens Turkeys

**Comment by Hypsibius** [comment]
Dessutan NN: Fjørfe BF Fjærfe 

Korleis skal vi få med fjørfehald av gjes, ender, kalkunar og vaktlar osb utan å krasje m systematiske termar?

**Comment by danmichaelo** [comment]
Oppretta: REAL032103

Tenker du at vi bør ha med  gjes, ender, kalkunar, osv. for kompletthets skyld?

**Comment by Hypsibius** [comment]
Ja, tenkte då det? I alle fall kalkunar, sidan Caroline tar dei med på engelsk?

**Comment by Hypsibius** [comment]
Er muligens merka av at min Reko-ring leverer litt forskjellige fjørfeprodukt...

😶

**Comment by danmichaelo** [comment]
Haha, det la jeg ikke merke til. La til kalkuner/-ar. Fyller bare på med flere ved ønske/behov!
