### ISSUE TITLE
Muskler, Myologi, Muskel-xxx etc

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#1568]
Her er nok rom for sammenslåing. Vi har:
Muskler
Muskelceller
Muskelfibre
Muskelfysiologi
Muskelsystemer
Muskelvev
Myologi
Myotuber
Humane myotuber

(i tillegg til noen mer spesifikke som vi sikkert kan beholde)

**Comment by Hypsibius** [comment]
Med atterhald om at eg ikkje heilt er kjend med 'myotuber' som term og Dr Google ikkje gir meg ein definisjon; er det mange her som trengst å haldast frå kvarandre? Kan tenke meg at vi evt held fysiologien skilt frå struktur/anatomi. Vi skulle kunne behalde 'muskelfibre' separat, men eg får berre eitt treff på snevert søk. Ergo ser eg ikkje behovet. Det vil alltid vere mogeleg å skilje den ut seinare om behovet skulle oppstå.

Men at vi buntar saman -celler i -vev og kallar det musklar, det må vel vere ei god opprensking? 

Foreslår: 

Muskler, BF Muskelceller BF Muskelsystemer BF Muskelvev BF Myologi BF Muskelfibre
Muskelfysiologi?

Så lenar eg meg tilbake og ventar på myotuber-oppklaringa

**Comment by BioHeidi** [comment]
Myotuber er skjelettmuskelceller. 
Litt usikker på om det er nødvendig å holde den utenfor?

**Comment by Hypsibius** [comment]
Nei, det tenkjer eg jo ikkje då. Men skilje mellom fysiologi og anatomi?

**Comment by BioHeidi** [comment]
Da gjør jeg som du foreslo over:
Muskler, BF Muskelceller BF Muskelsystemer BF Muskelvev BF Myologi BF Muskelfibre BF Myotuber

Og holder Muskelfysiologi utenfor.
