### ISSUE TITLE
Økt oljeproduksjon EN enhanced oil recovery

### ISSUE THREAD

**Issue by mzyg** [realfagstermer/realfagstermer#157]
Har en masteroppgave om  ‘Experimental study of diffusive oil recovery (…) during CO2 injection(..)
https://bora.uib.no/handle/1956/9210
Metoden ble brukt for ‘enhanced oil recovery’. Det er en fast term på engelsk. Som fri emneord på norsk brukes flest ‘oljeutvinning, økt’ eller ‘oljeproduksjon, økt’ som to termer.

Foreslår å legge til ‘økt oljeproduksjon EN  enhanced oil recovery’  som term.
https://snl.no/petroleumsutvinning

**Comment by danmichaelo** [comment]
Omsider lagt inn :) Jeg la også inn "Tertiær oljeutvinning" som alternativ term.

**Comment by danmichaelo** [comment]
Jeg valgte Økt oljeutvinning som foretrukket term forresten, siden vi hadde Oljeutvinning fra før
