### ISSUE TITLE
Form/sjanger-ord brukt som emneord

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1577]
Form/sjanger-ord i Realfagstermer kan også brukes som emneord. Vi legger de i 650 og beholder samme identifikator.

Dessverre ser det egentlig ikke ut som Alma takler dette. Ta boka *Science tales*, som opprinnelig hadde `650 Pseudovitenskap`, men som i en eller annen prosess har blitt «rettet» til `655 Pseudovitenskap`, akkurat som de andre Pseudovitenskap-bøkene våre.

Noterer det for å ikke glemme det. Det spørs om ikke vi burde skilt ut egne identifikatorer for begrepene som skal kunne brukes både som form/sjanger og som emneord.

**Comment by grosyn** [comment]
Humord har òg termar som kan brukast både som form/sjanger og som emneord - dei har løyst det med å oppretta 1 emnetermspost og 1 formtermspost (sjå t.d. Altaisk folkediktning).

Når det er sagt, er Pseudovitenskap kun innhaldsbeskrivande term i Humord. Det er kanskje ikkje forma som er av pseudovitskapeleg karakter, men innhaldet? Kjem det protestar dersom eg flyttar den frå form- til emneterm?

@superLine @BioHeidi @TorgunnKarolineMoe @kyrretl @edinab

**Comment by Hypsibius** [comment]
"Når det er sagt, er Pseudovitenskap kun innhaldsbeskrivande term i Humord. Det er kanskje ikkje forma som er av pseudovitskapeleg karakter, men innhaldet? Kjem det protestar dersom eg flyttar den frå form- til emneterm?"

Godt poeng. Eg antar vidare at vi brukar termen når eit dokument tematisk tar opp åpseudovitskap, og ikkje når vi kjm over det vi meinar er pseudovitskap? Det siste kjennest litt - betent?

**Comment by BioHeidi** [comment]
Enig her. Hvis vi plutselig har pseudovitenskap i samlingen (og ikke bøker OM pseudovitenskap) er det kanskje på tide med samlingsrydding og ikke emneordsrydding. 

Ser at vi pr nå bare har ett dokument "Nonsense on stilts" som er veldig lesverdig. Er fristet til å sette emneordet på "Intellectual impostures" også.

**Comment by grosyn** [comment]
Då er me samde, og eg lukkar saka.

**Comment by Hypsibius** [comment]
Kan eg innrømme at eg har tatt inn eit par skikkeleg pseudovitskaplege bøker for at studentane skal ha noko å sette tennene i og filleriste?
