### ISSUE TITLE
Miljøforvaltning

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1579]
Jeg synes at _[Økosystembasert forvaltning](https://www.miljostatus.no/tema/hav-og-kyst/okosystembasert-forvaltning/) EN Ecosystem based management_ kan være greit å ha (jobber med [denne](https://bora.uib.no/handle/1956/13156)) - den kunne legges som BF under _miljøforvaltning_?

**Comment by BioHeidi** [comment]
Gjort:
Vi hadde allerede Økosystemforvaltning som BF, men jeg la til Økosystembasert forvaltning også.
