### ISSUE TITLE
Forensisk kjemi - forensisk farmasi

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#158]
Slit med desse termane, som er dårleg (tunga i kjaken) norvagisering av 'forensic'. Vi har alt rettskjemi, så desse kan slåst saman. Sjølv om begrepet ikkje er mykje brukt, foreslår eg at vi som hovudinnførsel brukar også rettsfarmasi, så det samsvarar med andre termar vi har i registeret, som rettsmedisin, rettsinformatikk, rettstoksikologi.

**Comment by danmichaelo** [comment]
Enig i alt!

**Comment by bibliomari** [comment]
Ferdig
