### ISSUE TITLE
Skildringer

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#1581]
Er skildringer en egen litterær sjanger eller kan det slås sammne med andre litteratur/sjangeremneord?
Det er kun brukt sammen med emneordet Zoologi.

**Comment by Hypsibius** [comment]
Jøss! Ikkje noko eg ville kome på å bruke. Og er det korrekt å ha det som emneord og ikkje formterm? Reiseskildringer er formterm....

**Comment by danmichaelo** [comment]
Har også lurt litt på denne. Humord har [Skildring](https://app.uio.no/ub/emnesok/humord/search?uri=http:%2F%2Fdata.ub.uio.no%2Fhumord%2Fc06575) og [Naturskildring](https://app.uio.no/ub/emnesok/humord/search?uri=http:%2F%2Fdata.ub.uio.no%2Fhumord%2Fc06577). Kanskje vi skulle endre vår til Naturskildring o mappe den som Humords?

**Comment by BioHeidi** [comment]
Ja det er bedre.

**Comment by danmichaelo** [comment]
Endret til `Naturskildringer`
