### ISSUE TITLE
Religiøse tekster

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1584]
Jeg jobber med [denne ](https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71492334210002201&context=L&vid=UBB&search_scope=default_scope&tab=default_tab&lang=no_NO) - Plants of the Bible and the Quran. Vi har bibelen (REAL001676) og Religion og Vitenskap (REAL031904), men jeg føler at det ikke passer helt med sistnevnte. Jeg lurer på om "bibelen" kunne bli mer generelt, e.g. 
Religiøse tekster BF Bibelen, Koranen EN Religious texts, Sacred texts, Bible, Quran, Qur'an, Koran ?

**Comment by danmichaelo** [comment]
Ja, det synes jeg virker som en god idé!

... eller kræsjer hele mappingprosjektet da, @BioHeidi ? :innocent:

**Comment by danmichaelo** [comment]
Njej, Dewey har `208.2 Hellige skrifter`, så jeg tror det går bra

**Comment by Hypsibius** [comment]
Istemmer! Vi hadde ikkje sååå mange dokuemnt, unsett

**Comment by BioHeidi** [comment]
Det går braaaaa... *sukk*

**Comment by danmichaelo** [comment]
Har endret og oppdatert mappingene
