### ISSUE TITLE
Foreslår nyterm Havslanger

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1585]
Foreslår ny term: 

Havslanger EN Sea Snakes EN Coral Reef Snakes LA Hydrophiinae

Døme på bruk: https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71502728440002201&context=L&vid=UBB&search_scope=blended_scope&tab=alle_bibliotek&lang=no_NO

**Comment by danmichaelo** [comment]
Haveslanger? Neida :)

**Comment by Hypsibius** [comment]
Lindormer?

**Comment by BioHeidi** [comment]
Gjort!

**Comment by Hypsibius** [comment]
Her går det unna, gitt!
