### ISSUE TITLE
Elektriske dipolmomenter

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#1586]
Ok å endre denne til bare Dipolmomenter?

@danmichaelo : Det kan ikke gjøres i Sonja fordi vi alleredehar hatt Dipolmomenter som term (nå slettet).

**Comment by danmichaelo** [comment]
Njej, det er vel noen magnetiske også. Tror det er greit å holde dem fra hverandre

**Comment by danmichaelo** [comment]
Men den kan fint få =EQ til 537.243 altså!
