### ISSUE TITLE
Pussig term? Fiskesyn

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1587]
![image](https://user-images.githubusercontent.com/9350370/57133282-96953080-6da2-11e9-97a9-72f60e965786.png)

Burde det evt vere Fiskens syn, Fisker: Syn eller Syn: Fisker? Vi har verken Pattedyrsyn eller fuglesyn :-/

**Comment by danmichaelo** [comment]
Fishvision Song Contest :tada:* Neida..

Wikipedia har https://en.wikipedia.org/wiki/Vision_in_fishes

Er "Syn hos fisk" en mulighet, eller blir det for knotete? Vi kan selvfølgelig ty til strenger, men det var det med hva som skulle først :)

**Comment by Hypsibius** [comment]
Hm, syn hos fisk syn(!)est litt rart, ja. Faktisk ein av få gongar eg tenkjer strengar gjer best jobb. Og vidare at Syn: Fisk er den logiske rekkefølgjen. Det følgjer jo og inndeling i Dewey

**Comment by grosyn** [comment]
Eg har no sletta denne termen, og lukkar saka.
