### ISSUE TITLE
Semantisk analyse

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1589]
Vi må klargjøre hva denne skal bety for oss:

https://en.wikipedia.org/wiki/Semantic_analysis

Ser ut som vi har brukt den litt forskjellig

---
*REAL009708 (Semantisk analyse) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009708), [Skosmos](http://data.ub.uio.no/realfagstermer/c009708), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Semantisk%20analyse%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL009708)*

**Comment by grosyn** [comment]
Det ser ut som alle postane me har brukt dette på er innan Informatikk.
