### ISSUE TITLE
Vegetativ formering og ukjønnet formering

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#159]
Kan vi vel slå saman, vel?

I dag skal resten av lista til pers....

@BioHeidi

**Comment by BioHeidi** [comment]
Ukjønnet kan være partenogenese, men det kaller vi vel egentlig ikke vegetativ formering. Spretthalene mine er ikke vegetasjon! Men med de rette definisjoner... kanskje.

**Comment by Hypsibius** [comment]
Jo, ser den, men partenogenese er ukjønna formering. Så om vi seier Ukjønnet formering bf vegetativ formering?

**Comment by Hypsibius** [comment]
Eller, skulle seie, vegetativ formeiring er ukjønna. Med same konklusjon.

**Comment by BioHeidi** [comment]
Jepp! Done!
