### ISSUE TITLE
Foreslår nyterm: Mikrobiom

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1591]
Nyterm Mikrobiom BF Mikrobiota NN Mikrobiom NN Mikrobiota En Microbiome EN Microbiota SO Biofilm

https://snl.no/mikrobiom

https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71561609220002201&context=L&vid=UBB&search_scope=blended_scope&tab=alle_bibliotek&lang=no_NO

**Comment by danmichaelo** [comment]
Flertallsform på bokmål blir vel *mikrobiomer*? (Selv om SNL-artikkelen ser ut til å bruke *mikrobiom* i flertall også.) Blir dette riktig, mon tro?

```
Mikrobiomer
BF Mikrobiotaer
NN Mikrobiom
NN Mikrobiotaar [??]
EN Microbiotas
EN Microbiomes
SO Biofilm
```

**Comment by Hypsibius** [comment]
Ah, det var ein nynorskisme frå mi side. Beklager!

**Comment by danmichaelo** [comment]
Bra, den er klar: http://data.ub.uio.no/realfagstermer/c032122
