### ISSUE TITLE
Sør-Afrika (område)

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1594]
Vi har både "Sør-Afrika (område)" (REAL030716) og "Sørlige Afrika" (REAL031060), begge to oversatt til Southern Africa.

**Comment by Hypsibius** [comment]
Såklart i tillegg til denne: 

Sør-Afrika (REAL030720)
  EN South Africa
     Republic of South Africa
  DA 2015-02-20
  FT sted

For å unngå samanblanding, foreslår eg å slette Sør-Afrika (område) og overføre alle postar til Sørlige Afrika.

**Comment by danmichaelo** [comment]
Har i hvert fall slått sammen `Sørlige Afrika BF Sør-Afrika (område)`. Mer usikker på om det er lurt å slå sammen med landet, det burde vel gå an å holde dem fra hverandre?

(I parentes: Ser at vi også har Sør-Trøndelag :D)

**Comment by danmichaelo** [comment]
(Slo sammen Trøndelag BF Sør-Trøndelag BF Nord-Trøndelag)

**Comment by Caroline-A** [comment]
> Har i hvert fall slått sammen `Sørlige Afrika BF Sør-Afrika (område)`. Mer usikker på om det er lurt å slå sammen med landet, det burde vel gå an å holde dem fra hverandre?

Takk! Jeg er enig i at landet og området bør holdes seperat.

**Comment by Hypsibius** [comment]
I fall det var uklart, så meinte eg absolutt IKKJE at vi skulle slå saman m Sør-afrika. Tvert om at vi burde fjerne Sør-afrika som område og heller bruke Sørlige Afrika , når vi snakkar om området, slik at vi står med to termar: Sørlige Afrika (som område) og Sørafrika (land)

**Comment by danmichaelo** [comment]
Det var ikke så uklart egentlig, bare jeg som leste litt for fort!

Har fjernet "Sør-Afrika (område)" helt, var på nippe til å gjøre det sist også.
