### ISSUE TITLE
Quorum sensing

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1595]
Jeg jobber med [denne ](http://bora.uib.no/handle/1956/19016)som snakker om [quorum sensing](https://en.wikipedia.org/wiki/Quorum_sensing). Tenker at det kunne vært fint å legge den til som BF - spørsmål er hvor!
Lurer på Cellekommunikasjon? Men jeg er litt usikker siden quorum sensing er bare for bacteria som jeg forstår det. Kanskje Biofilm? Vi har ikke term for mikrobiell kommunikasjon eller noe. 
![image](https://user-images.githubusercontent.com/42732381/58002826-bbe2a800-7adf-11e9-8ff2-c9955efcd68a.png)
![image](https://user-images.githubusercontent.com/42732381/58003260-ba65af80-7ae0-11e9-8fce-31f311fe92dc.png)
Jeg kan også bare bruke Bakterier $$x Signalmolekyler $$0 (NO-TrBIB)REAL018264 for denne, men det kommer an på om vi synes quorum sensing er fint å ha et sted i ordliste.

**Comment by BioHeidi** [comment]
Er Jessica her?

**Comment by jessiclo** [comment]
Hei! Jeg tror cellekommunikasjon kan være litt forvirrende, tror ikke mikrobiolger vil finne det da. Jeg ville ha foreslått Bakteriekommunikasjon. Hva tenker dere om det?

**Comment by danmichaelo** [comment]
Opprettet `Quorum sensing` som eget emneord forresten (REAL032126).

**Comment by danmichaelo** [comment]
"Fornorsket" den litt ved å endre til quorumsensing i ett ord. Og la til quorum(-)registrering fra https://www.mn.uio.no/ibv/tjenester/kunnskap/plantefys/leksikon/q/quorum.html, som jeg synes var en litt god variant, bedre enn sansing/sansning.

**Comment by grosyn** [comment]
Har sidan denne diskusjonen fått innførsel i SNL, med oppslagsord Quorum-registrering
