### ISSUE TITLE
Planteøkologi - Vegetasjonsøkologi

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1597]
Jeg synes at disse kunne sammenslåes? Det er noen situasjoner hvor det er en forskjell - e.g. hvis vi snakker om alger, da kan vi bruke "vegetasjon" men ikke "plant". Men jeg ser at vegetasjonsøkologi er så ofte brukt for planter, så det er mye overlap. Foreslår _vegetasjonsøkologi_ brukes som hovedterm, og _planteøkologi_ brukes som BF.
![image](https://user-images.githubusercontent.com/42732381/58006401-4f1fdb80-7ae8-11e9-9e2a-4bf4421cc30c.png)
![image](https://user-images.githubusercontent.com/42732381/58006427-59da7080-7ae8-11e9-8696-1baa778c1302.png)

**Comment by danmichaelo** [comment]
Enig, @BioHeidi ?

**Comment by BioHeidi** [comment]
Enig!

**Comment by danmichaelo** [comment]
Gjort! (omsider)
