### ISSUE TITLE
Ny stedterm: Sudan

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1601]

**Comment by Hypsibius** [comment]
Sudan NN Sudan EN Sudan (enkel sånn)

TBF https://bibsys-almaprimo.hosted.exlibrisgroup.com/permalink/f/8hnp7t/BIBSYS_ILS71574089890002201

**Comment by danmichaelo** [comment]
Den har vi da? REAL030484

**Comment by Hypsibius** [comment]
Uhm, har eg leitt i emnetermane igjen? *rødme*

**Comment by danmichaelo** [comment]
Sonja er nådeløs! Hvis jeg får det som jeg vil blir den litt snillere i neste versjon…
