### ISSUE TITLE
Nytermforslag: Skjeggkre

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1603]
"Håndbok om skjeggkre" (978-82-91070-15-5)

**Comment by danmichaelo** [comment]
Haha, oppretter :)

```
id= REAL032125
te= Skjeggkre
nn= Skjeggkre
en= Gray silverfish
en= Long-tailed silverfish
la= Ctenolepisma longicaudata
```

**Comment by Hypsibius** [comment]
Ingen skrekktillegg? Papyrovora? Vi har forresten hatt dei reinaste økosystem i våre magasin. Skjeggkre, edderkoppar og rovbiller....
