### ISSUE TITLE
språk

### ISSUE THREAD

**Issue by superLine** [realfagstermer/realfagstermer#1604]
Språk som egen term er slettet, men jeg har en bok om språk i Doctor Who --> what do I do ?

**Comment by Hypsibius** [comment]
Leser den?

**Comment by danmichaelo** [comment]
Hvilken bok? Vi kan gjenopprette "Språk" ved behov, men det er jo et veldig generelt emneord. Det finnes ikke noen snevrere som kan brukes? Evt. noen vi kan opprette?

**Comment by superLine** [comment]
Language of Doctor Who - 71473457370002201  - jeg fant ikke noe snevrere i roald, men jeg er veldig åpen for forslag altså.

**Comment by Hypsibius** [comment]
Vil det vere kunstige språk? På linje med Klingon?

**Comment by danmichaelo** [comment]
Ble du ferdig med denne, @superLine ? Kan vi lukke?

(`Science fiction` som emne kunne nesten vært relevant? :))

**Comment by danmichaelo** [comment]
Lukker basert på inaktivitet
