### ISSUE TITLE
whisky

### ISSUE THREAD

**Issue by superLine** [realfagstermer/realfagstermer#1605]
fant ikke i Roald, men har boken "The Science and commerce of Whisky" foran meg :-D

**Comment by superLine** [comment]
mms 991434331644702201

**Comment by danmichaelo** [comment]
Fyll på: https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc032128
