### ISSUE TITLE
Slå saman Fugletrekk og Trekkfugler?

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1606]
'Prosess' mot 'organismar', men vanskeleg å tenke seg at ein snakkar om det eine utan det andre? 

![image](https://user-images.githubusercontent.com/9350370/64103106-af721a80-cd71-11e9-94cd-1fe40ea4ccce.png)

![image](https://user-images.githubusercontent.com/9350370/64103127-c31d8100-cd71-11e9-877e-3caf5f32e37e.png)

**Comment by danmichaelo** [comment]
Tilbøyelig til å være enig. Hva synes @BioHeidi ?

**Comment by danmichaelo** [comment]
Slo de sammen som Fugletrekk BF Trekkfugler etter en liten konsultasjon med BioKirsten
