### ISSUE TITLE
Foreslår nyterm Flekksteinbit

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1607]
Flekksteinbit  BF Leopardfisk NN Flekksteinbit EN Spotted wolffish LA Anarhichas minor

Aktuelt på denne: https://bibsys-almaprimo.hosted.exlibrisgroup.com/permalink/f/16a854r/BIBSYS_ILS71577389200002201

**Comment by danmichaelo** [comment]
Opprettet!
