### ISSUE TITLE
Antropocen (REAL031113)

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1609]
Den er låst i søksed så jeg kunne ikke redigere direkte, men bokstaving av den engelske oversettelse trengs redigering :)
![image](https://user-images.githubusercontent.com/42732381/65131702-0168a080-da00-11e9-886b-91897cc3f9a1.png)

**Comment by danmichaelo** [comment]
Oi :O 

Takk, har fiksa!
