### ISSUE TITLE
Fleire strengekandidatar

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#161]
Vi har: 

Fossile alger
Fossile bløtdyr
Fossile bryophyta
Fossile dinofllagellatcyster
Fossile fisker
Fossile fugler
Fossile hominider
Fossile hvaler
Fossile korallrev
Fossile mennesker
Fossile mikroorganismer
Fossile mollusker
, se Fossile bløtdyr
Fossile pattedyr
Fossile planter
Fossile virveldyr
Fossiler

Blir ikkje dette bedre løyst med strengar, eksempelvis fossiler: alger, Fossiler: bløtdyr, fossiler: bryophyta etc? (Hurra, er på siste arket no!)

**Comment by bibliomari** [comment]
Nei
