### ISSUE TITLE
Intelligens

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1610]
Ref issue #436
De norske termene for intelligens og naturlig intelligens har blitt slått sammen, men den engelske mangler "intelligence". Foreslår at den legges til (låst i søksed). Vet at termen er overordnet term, men jeg tror at "natural intelligence" er et ganske rart uttrykk, som jeg tipper blir ikke brukt så mye...? 
![image](https://user-images.githubusercontent.com/42732381/65131928-5efced00-da00-11e9-8f89-b55649cb755c.png)

**Comment by Hypsibius** [comment]
I kva grad brukast det forresten på norsk? Kunstig intelligens spesifiserast vel, så handlar alt anna om naturleg intelligens? #hilsenbiolog

**Comment by danmichaelo** [comment]
Mm, det gjør nok det. Vi fjernet "Naturlig intelligens". Og fikset "Intelligence" på engelsk.
