### ISSUE TITLE
Øyenstikkere

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1611]
Foreslår at vi legge til LA Odonata
![image](https://user-images.githubusercontent.com/42732381/65307502-3273dd00-db88-11e9-8956-d14911f93856.png)
https://en.wikipedia.org/wiki/Odonata
https://no.wikipedia.org/wiki/%C3%98yenstikkere

**Comment by danmichaelo** [comment]
Gjort!
