### ISSUE TITLE
Villblomster - Markblomster

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1612]
![image](https://user-images.githubusercontent.com/42732381/65324035-48df6000-dbab-11e9-8a49-f8cde196ab17.png)
![image](https://user-images.githubusercontent.com/42732381/65324044-509f0480-dbab-11e9-9170-34df7037df2e.png)
Jeg tror disse er det samme?

**Comment by danmichaelo** [comment]
Nært nok antakelig. Vi slo de sammen som Villblomster BF Markblomster.
