### ISSUE TITLE
Matplanter vs. Spiselige planter

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1613]
For meg er forskjellen litt vanskelig her (er den ene mer om villplanter som kan spises, mens den andre mer om planter som er dyrket for mat?). Det virker som de er brukt ganske mye om hverandre. 
NB vi har også **Jordbruksvekster** (real008322) og **Landbruksplanter** (real002860). 
![image](https://user-images.githubusercontent.com/42732381/65328543-dd02f480-dbb6-11e9-8d51-18e1e075eb07.png)
![image](https://user-images.githubusercontent.com/42732381/65328567-e68c5c80-dbb6-11e9-9578-b7eb28d6fefd.png)

**Comment by danmichaelo** [comment]
Ja, det er nok det. Diskuterte disse litt med @haraldse : 
- `Nytteplanter BF Nyttevekster`: Eksisterer allerede. Grei term for planter med andre bruksformål enn mat.
- `Jordbruksplanter BF Jordbruksvekster, Matplanter`: Her slår vi sammen litt.
- `Spiselige planter`: Planter som sankes, ikke dyrkes
- <s>`Landbruksplanter`</s>: Slettes. Brukt på et lite knippe bøker som heller kan få Jordbruksplanter, Skogbruk e.l.

**Comment by Hypsibius** [comment]
Eg sjekka litt korleis SNL har brukt omgrepet 'matplante'. Dei har inga eiga innførsle, men i ein artikkel om nomadar, brukar dei det om ville plantar som vert sanka inn, i andre artiklar om planter som i tidlegare tider har vore ein nytta ressurs (truleg utan å ha vore dyrka). Intuitivt oppfattar eg matplante som både dyrka plantar OG spiselege nyttevekstar som har utgjort viktig tilskot gjennom sanking. Det er dessutan ein glidande overgang mellom rein sanking og eksempelvis samisk jordbruk der ein har planta eller sådd på vårparten, anrika med gjødsel og hausta ved passering på haustparten. jf også Ojibwe sin bruk av villris i Nordamerika.

https://snl.no/nomader

"Jakt og sanking
De aller fleste ervervsformer som er basert på sanking av viltvoksende plantekost og jakt betinger også nomadisk levevis, dels på grunn av sesongvekslinger hos de tilgjengelige matplanter og dels viltets vandringer (se for eksempel pygmeer og san)."

Kan eg ellers bemerke at det er ufatteleg inkonsistent av SNL-forfattar å unngå hottentott for San, og så bruke 'pygme' for kongolesiske jegar- og samlarar....

**Comment by danmichaelo** [comment]
Ja, det er nok en glidende overgang og derfor lurer jeg på om det kan funke med `Spiselige planter BF Matplanter`? Med hovedfokus på planter som sankes, men ikke strengt avgrenset til det.

Eller tenker du at vi burde ha `Matplanter` som egen term for å kunne kombinere den med `Jordbruksplanter`?

**Comment by Hypsibius** [comment]
Nei, som det første du foreslo.

**Comment by Hypsibius** [comment]
Altså Spiselige planter BF Matplanter. Men med relevante SO-termar

**Comment by danmichaelo** [comment]
Bra, da prøver vi det!
