### ISSUE TITLE
Aktinomyceter

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1614]
Skal vi endre denne til aktinobakterier? Jfr. https://www.mn.uio.no/ibv/tjenester/kunnskap/plantefys/leksikon/a/aktinomy.html

**Comment by jessiclo** [comment]
Ja, det burde endres.
Hilsen Jessica


20. sep. 2019 kl. 15:30 skrev Dan Michael O. Heggø <notifications@github.com<mailto:notifications@github.com>>:


Skal vi endre denne til aktinobakterier? Jfr. https://www.mn.uio.no/ibv/tjenester/kunnskap/plantefys/leksikon/a/aktinomy.html

**Comment by danmichaelo** [comment]
Fint, da gjorde jeg det!
