### ISSUE TITLE
Allium

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1617]
**Foretrukket term:**

 - Bokmål: Allium
 - Nynorsk: Allium
 - Engelsk: Allium

**Dewey-nummer:**

Vet ikke

**Eksempel-dokument:**

A taxonomic review of Allium subg. Melanocrommyum in Iran (9783981309638)

Fra @grosyn

**Comment by danmichaelo** [comment]
Kan vi bruke *løkslekta* på norsk @haraldse ? https://no.wikipedia.org/wiki/Løkslekta / https://www.artsdatabanken.no/Taxon/Allium/99403

**Comment by Hypsibius** [comment]
Skulle vi vel kunne? (Frå Lids Flora under). 

Men ville hatt Løkslekta på Bokmål, NN Laukslekta, LA Allium EN Allium

![image](https://user-images.githubusercontent.com/9350370/67202991-3e162600-f40a-11e9-9c4f-8f592fe47c23.png)

**Comment by danmichaelo** [comment]
Takk! Da oppretta jeg `Løkslekta` med NN Laukslekta, LA Allium EN Allium

**Comment by danmichaelo** [comment]
>  Allioideae; agapant, gressløk, hvitløk, kepaløk, purre, sjalottløk flyttet fra 584.33 til 584.78
2016-11-16, Utgave 23

**Comment by Hypsibius** [comment]
Ooops, beklagar forelda Dewey
