### ISSUE TITLE
Turisthytter

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1619]
**Foretrukket term:** Turisthytter

 - Bokmål: (Fylles inn) Turisthytter
 - Nynorsk: (Fylles inn) Turisthytter
 - Engelsk: (Fylles inn) Tourist hut (ordnett.no)/ hikers' cabin / cabin

**Alternative termer:** DNT-hytter

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen) 

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:** Veit ikkje

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:** 

Norges beste hytte til hytteturer (ISBN: 9788205511187)
https://bibsys-almaprimo.hosted.exlibrisgroup.com/permalink/f/13vfukn/BIBSYS_ILS71549683070002201

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by grosyn** [comment]
På DNT sine engelske siden omtaler dei hyttene som cabins.

**Comment by danmichaelo** [comment]
Takk, denne er opprettet, glemte å svare.

La inn en del varianter på engelsk: http://data.ub.uio.no/realfagstermer/c032154
