### ISSUE TITLE
Desmids

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1620]
**Foretrukket term:**
 - Bokmål: Desmideer / Desmider (?)
 - Nynorsk: Desmideer / Desmider (?)
 - Engelsk: Desmids
- Latin: Desmidiales

**Definisjon, se-også-henvisninger og annet**
https://en.wikipedia.org/wiki/Desmidiales

**Dewey-nummer:**
579.837

**Eksempel-dokument:**
https://bibsys-almaprimo.hosted.exlibrisgroup.com/permalink/f/8hnp7t/BIBSYS_ILS71466511810002201

**Comment by danmichaelo** [comment]
Bare litt usikker på navneformen. Rent språklig høres "desmider" med én "e" umiddelbart mest riktig ut. Er det vanlig å bruke to "e"-er i lignende navn?

Og hva tror du om nynorsk-formen, @Hypsibius ?

**Comment by Hypsibius** [comment]
Ah, ja, det har du rett i! Desmider (NN: Desmidar) høyrest meir korrekt ut. @Caroline-A . Ingen klargjering å finne verken på Wikipedia, SLN eller artsdatabanken. Og det meste eg finn av faglitteratur på norsk, er marint. Kan du evt spørre Kjersti, @Caroline-A ?

**Comment by Caroline-A** [comment]
Ja jeg var litt usikker om dette. Jeg lar inn begge to fordi jeg har sett begge som fritte emneord. 
Jeg tror at "desmideer" har blitt brukt på svensk (jeg har funnet to tittler - Desmideer fran Gronland, og: 
![image](https://user-images.githubusercontent.com/42732381/69937433-13c08980-14db-11ea-8a49-153eb40ff0a1.png))
men på [svensk wikipedia er det Desmider](https://sv.wikipedia.org/wiki/Gr%C3%B6nalger).
Kanksje begge to er i bruk, den ene litt mer gammeldags...?
