### ISSUE TITLE
skiveprolaps

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1621]
**Foretrukket term:**

 - Bokmål: skiveprolaps
 - Nynorsk: (Fylles inn)
 - Engelsk: Spinal disc herniation

**Alternative termer:**
Slipped disc (disambiguation)

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)https://en.wikipedia.org/wiki/Spinal_disc_herniation
https://sml.snl.no/skiveprolaps

**Dewey-nummer:**
616.73

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:**

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by Hypsibius** [comment]
NN Skiveprolaps

**Comment by danmichaelo** [comment]
Opprettet! La inn noen flere termer fra http://mesh.uia.no/ også (irriterende at det ikke går an å dyplenke til et bestemt emne der)

**Comment by Hypsibius** [comment]
Og er salig glad for å ha sluppe unna full prolaps. Har klart meg med ein liten 'protrusjon' på nerven, og det heldt i veldig lange banar!

**Comment by haraldse** [comment]
haha - jeg har både her og der så jeg liker hjertet :-)
