### ISSUE TITLE
Tarer

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1622]
- Bokmål: 
 - Nynorsk: Tarar
 - Engelsk: Kelps
- Latin: Laminariales

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)
https://snl.no/tang_og_tare_-_brunalger

https://no.wikipedia.org/wiki/Tarer 
men denne burde redigerast, om nokon gidd >:-( 

Dewey-nummer: 579.887

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:**

https://bibsys-almaprimo.hosted.exlibrisgroup.com/permalink/f/8hnp7t/BIBSYS_ILS71549969330002201

**Comment by danmichaelo** [comment]
Opprettet!
