### ISSUE TITLE
Glykosylering

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1623]
**Foretrukket term:** Glykosylering

 - Bokmål: Glykosylering
 - Nynorsk: Glykosylering
 - Engelsk:  Glycosylation

**Alternative termer:**

Glykosidering (ifg. SNL)

**Eksempel-dokument:** 

https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71579946270002201&context=L&vid=UIO&lang=no_NO&search_scope=default_scope&adaptor=Local%20Search%20Engine&tab=default_tab&query=any,contains,bacterial%20protein%20glycosylation&offset=0

**Comment by danmichaelo** [comment]
Takk, opprettet

```
Glykosylering
BF Glykosidering
SO Glykobiologi
...
```
