### ISSUE TITLE
Coral Sea

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1624]
**Foretrukket term:**

 - Bokmål: (Korallhavet)
 - Nynorsk: Korallhavet
 - Engelsk:Coral Sea

**Alternative termer:**

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**
vi har lagt inn Great Barrier Reef

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)
https://www.google.com/search?client=firefox-b-d&q=coral+sea
https://www.google.com/search?client=firefox-b-d&q=korallsj%C3%B8en

**Dewey-nummer:**
T2-(943) eller 995

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:**

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by haraldse** [comment]
DM-blir dette levert??

**Comment by BioHeidi** [comment]
Her er et eksempel på at det kan være nyttig å holde på geografiske emneord også i Realfagstermer. Eller vil Korallhavet være en term som er naturlig å finne i andre vokabularer? Slike bioregioner er vel mest aktuelle å omtale i vår verden?

**Comment by haraldse** [comment]
hm- denne er det lenge siden jeg så på, men mener du Korallhavet er et godt ord eller er ok? det inkluderer flere geografiske områder

**Comment by BioHeidi** [comment]
Oppretter du, @grosyn ?

**Comment by grosyn** [comment]
Ja, det kan eg gjera.

**Comment by grosyn** [comment]
Ser at det er ein kommentar over om at Great Barrier Reef ligg inne. Skal eg laga Se også-henvisningar frå G B R til Korallhavet og vice versa?

**Comment by BioHeidi** [comment]
Ja, kan godt ha en SO til GBR. Og ja, bruk Webdeweys nummer for Korallhavet.
