### ISSUE TITLE
Leppeblomstordenen

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1625]
**Foretrukket term:**

 - Bokmål: (Leppeblomstordenen)
 - Nynorsk: (leppeblomordenen)
 - Engelsk: (lamiales?)

**Alternative termer:**
Lamiales

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)
https://en.wikipedia.org/wiki/Lamiales
https://en.wikipedia.org/wiki/APG_IV_system

**Dewey-nummer:**
583.96

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:**

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by Hypsibius** [comment]
Også NN Lepeblomsterordenen NN Leppeblomsterordenen

EN og LA ser ut til å vere samanfallande

**Comment by haraldse** [comment]
grusomt tungt, tror få søker på det ordet, but but
leppeblomster blir for snevert = familien

**Comment by danmichaelo** [comment]
@Hypsibius Leppeblomordenen på NN vel? Vil du ha med de andre også? (Lepeblomsterordenen, Leppeblomsterordenen)

https://artsdatabanken.no/Taxon/Lamiales/1329

**Comment by danmichaelo** [comment]
Opprettet (virker i morgen): http://data.ub.uio.no/realfagstermer/c032226

**Comment by Hypsibius** [comment]
Ta med heile røkla! JF

![image](https://user-images.githubusercontent.com/9350370/70992619-5e8cf480-20ca-11ea-9959-b9753fda1908.png)
