### ISSUE TITLE
Tetrachondraceae

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1626]
**Foretrukket term:**
har ikke norskt navn 
 - Bokmål: (Fylles inn)
 - Nynorsk: (Fylles inn)
 - Engelsk: (Fylles inn)

**Alternative termer:**
evnt bare bruke overordnet Leppeblomstordenen(Lamiales) 

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)
https://en.wikipedia.org/wiki/Lamiales

**Dewey-nummer:*583.96

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:**

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by Hypsibius** [comment]
I ilfelle der vi manglar norsk namn tenker deg det kan vere lurt å sjå på kor ofte vi ventar det vil bli brukt, og om vi kan klare oss med ein overordna term?

**Comment by haraldse** [comment]
ja- enig

**Comment by Hypsibius** [comment]
:-)

**Comment by danmichaelo** [comment]
Kan vi se på denne på fredag, @BioHeidi ?

**Comment by BioHeidi** [comment]
En eller annen fredag (eller mandag) så jeg på denne i alle fall!

Vi klarer oss med [Leppeblomstordenen](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc032226&broad=false). Vi har riktignok to familier under ordenen ([Leppeblomstfamilien](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc009890&broad=false) og [Snylterotfamilien](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc032225&broad=false)), men vi har bare dokumenter på Leppeblomstfamilien, ikke på Leppeblomstordenen eller Snylterotfamilien. Så jeg tenker vi er dekket. Da får vi i alle fall et dokument på ordensnivå!
