### ISSUE TITLE
Snylterotfamilien

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1627]
**Foretrukket term:**

 - Bokmål: (Snylterotfamilien)
 - Nynorsk: (Fylles inn)
 - Engelsk: (Broomrapes)

**Alternative termer:**
evnt Lamiales = Leppeblomstordenen

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)
https://snl.no/snylterotfamilien
https://no.wikipedia.org/wiki/Snylterotfamilien

**Dewey-nummer:**
583.96
(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:**
vol 17: Flora of North america

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by Hypsibius** [comment]
NN Snylterotfamilien (jf Lids Flora). 

Men er ikkje Orobanchaceae korrekt LA? Den ligg under Lamiales, som kanskje treng egen innførsel?

**Comment by danmichaelo** [comment]
Opprettet

**Comment by danmichaelo** [comment]
Vi har bare Leppeblomstfamilien, ikke Leppeblomstordenen. Vil vi ha SO mellom Leppeblomstfamilien og Snylterotfamilien? (siden de er i samme orden)
