### ISSUE TITLE
Asterider

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1628]
**Foretrukket term:**

 - Bokmål: Asterider
 - Nynorsk: Asterider
 - Engelsk: Asterids
Latin: Asteridae

Norsk dewey bruker Asterider. Artsnavndatabanken ikke 

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)
https://no.wikipedia.org/wiki/Asteridae

**Dewey-nummer:**
583.9

**Eksempel-dokument:**

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
@Hypsibius : Er du enig med nynorsken her?

**Comment by danmichaelo** [comment]
Opprettet

**Comment by Hypsibius** [comment]
NN-wikipedia har talt! Trur vi heng med dei, anna belegg kan det bli vanskeleg å finne! Og lener intuitivt mot maskulinum sjølv men ikjke utan tvil...

https://nn.wikipedia.org/wiki/Asteridar
