### ISSUE TITLE
Afganistan

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1629]
**Foretrukket term:**

 - Bokmål: Afganistan
 - Nynorsk:Afganistan
 - Engelsk: Afghanistan

**Alternative termer:**

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)
https://en.wikipedia.org/wiki/Afghanistan

**Dewey-nummer:**
h2-581 her 580.9581
(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:**
Vascular plants of Afghanistan
https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71580620100002201&context=L&vid=UIO&lang=no_NO&search_scope=default_scope&adaptor=Local%20Search%20Engine&tab=default_tab&query=any,contains,plants%20afghanistan&offset=0
(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
Denne eksisterer allerede: https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc031041

Hvis du ikke fant den i Roald, husk å bytte til "Steder" når du søker etter stedsnavn.
