### ISSUE TITLE
Sibir

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1630]
**Foretrukket term:**

 - Bokmål: Sibir
 - Nynorsk: Sibir
 - Engelsk:Siberia

**Alternative termer:**

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)
https://en.wikipedia.org/wiki/Siberia

**Dewey-nummer:**
-0957
(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:**
582.10957
(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)
https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71580638570002201&context=L&vid=UIO&lang=no_NO&search_scope=default_scope&adaptor=Local%20Search%20Engine&tab=default_tab&query=any,contains,introduction%20of%20woody%20plants%20in%20siberia

**Comment by danmichaelo** [comment]
Eksisterer også allerede: https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc030740
