### ISSUE TITLE
Nystrengforslag

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1631]
**Foretrukket term:** monolittiske materialer

 - Bokmål: (Fylles inn) monolittiske materialer
 - Nynorsk: (Fylles inn) monolittiske materialar
 - Engelsk: (Fylles inn) monolithic materials

**Alternative termer:**

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:** 

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:** https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71476014550002201&context=L&vid=UIO&lang=no_NO&search_scope=default_scope&adaptor=Local%20Search%20Engine&isFrbr=true&tab=default_tab&query=any,contains,monolithic%20materials&offset=0

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
Opprettet. La på def. "Kromatografisk pakkemateriale (sorbent)" og SO "Kapillærelektrokromatografi"
