### ISSUE TITLE
katastrofehåndtering

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1632]
**Foretrukket term:**

 - Bokmål: (katastrofeberedskap
 - Nynorsk: (vernebuing - evnt. 
 - Engelsk: (disaster preparedness)

**Alternative termer:**

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)
https://sml.snl.no/katastrofeberedskap

**Dewey-nummer:**
363.34525
(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:**
https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71577139810002201&context=L&vid=UIO&lang=no_NO&search_scope=default_scope&adaptor=Local%20Search%20Engine&isFrbr=true&tab=default_tab&query=any,contains,feeding%20everyone%20no%20matter%20what&offset=0
(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
"Katastrofeberedskap" har vi allerede. Legger på "Katastrofehåndtering" som alternativ term på den.
