### ISSUE TITLE
Filefjell - nytt stadnamn

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1633]
**Foretrukket term:** Filefjell

 - Bokmål: (Fylles inn) Filefjell
 - Nynorsk: (Fylles inn) Filefjell
 - Engelsk: (Fylles inn) Filefjell

**Alternative termer:**

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:**

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:** "Filefjell : natur, folk og landskap"

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
Opprettet!
