### ISSUE TITLE
Nytt emneord: 3D-modellering

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1634]
**Foretrukket term:** 3D-modellering

 - Bokmål: (Fylles inn) 3D-modellering
 - Nynorsk: (Fylles inn) 3D-modellering
 - Engelsk: (Fylles inn) 3D modeling

**Alternative termer:** 

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:**

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:** https://tinyurl.com/shjw796

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
Opprettet, men vi må se litt på overlapp mot eksisterende emneord, særlig Tredimensjonal representasjon
