### ISSUE TITLE
Sauer (REAL003652)

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1635]
Foreslår at vi legge til:
BF Villsauer
NN Villsauar (?) @Hypsibius  
EN Lambs, Sheep husbandry, Sheep farming, Wild sheep

**Comment by Hypsibius** [comment]
NN tillet både Sauer og Sauar, faktisk, men sidan det er snakk om sauerase (breed) heller enn slekt/familie, tenker eg det er korrekt m eintal. Om vi då ikkje skal skilje Ovis Aries frå dei ordentleg ville sauene? Mufflon og sånt? 

Foreslår tillegg: BF Utegangersau BF Gammelnorsk sau NN Utegangarsau NN Utegongarsau NN Gamalnorsk sau

**Comment by danmichaelo** [comment]
Lagt til. Droppet "Wild sheep" på engelsk for å unngå sammenblanding med ordentlig ville sauer.

Kan være villsau kunne vært eget emneord. Har vi mer enn ett dokument?

**Comment by Hypsibius** [comment]
Ser ut som 'villsau'/utegangar på engelsk omtalast som Old Norwegian Sheep på engelsk: https://en.wikipedia.org/wiki/Old_Norwegian_Sheep

**Comment by danmichaelo** [comment]
Lagt til.

Lurer fortsatt på om villsau burde vært eget emneord, men vi kan komme tilbake til det.
