### ISSUE TITLE
Trær

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1636]
Vi har mange termer om trær/tre og jeg lurer på om noen av dem burde sammenslåes. Har gruppert alle som jeg kunne finne under: 

650 _7 > **Trær** $$0 (NO-TrBIB)REAL000468 $$2 noubomn
650 _7 > **Treslag** $$0 (NO-TrBIB)REAL013931 $$2 noubomn
Sammenslåes? Men jeg er litt usikker på om "treslag" gjelder typer ved (i.e. typer tremateriale) eller typer trær (i.e. trearter) (?). Akkurat nå er den oversatt som "woods" - dette bør fjernes uansett tenker jeg. 

650 _7 > **Trematerialer** $$0 (NO-TrBIB)REAL013932 $$2 noubomn
650 _7 > **Treprodukter** $$0 (NO-TrBIB)REAL010913 $$2 noubomn
650 _7 > **Ved** $$0 (NO-TrBIB)REAL008237 $$2 noubomn
Sammenslåes? Per i dag er alle "wood" eller "wood products" på engelsk. Flere har BF treverk/trevirke. 

650 _7 > **Treteknologi** $$0 (NO-TrBIB)REAL005762 $$2 noubomn
Jeg vet ikke helt hva denne gjelder. Brukt på bare to dok.

650 _7 > **Tresløyd** $$0 (NO-TrBIB)REAL002201 $$2 noubomn
650 _7 > **Treskurder** $$0 (NO-TrBIB)REAL008970 $$2 noubomn
Jeg synes disse kunne holdes seperat, men at EN "wood whittling" og "wood carvings" burde legges til Treskurder (hvis det er snakk om både aktivitetet og produktet). 

650 _7 > **Vedanatomi** $$0 (NO-TrBIB)REAL007676 $$2 noubomn
650 _7 > **Treanatomi** $$0 (NO-TrBIB)REAL010108 $$2 noubomn
Vedanatomi er oversatt som "wood structures" - dette høres ut som e.g. et hus, og jeg tror at dette ikke er meningen. Per i dag står "Tree rings" på vedanatomi og ikke treanatomi. Jeg er litt usikker men lener mot sammenslåing. 

650 _7 > Trepleie $$0 (NO-TrBIB)REAL003383 $$2 noubomn

**Comment by Caroline-A** [comment]
@realfagstermer/bio

**Comment by Hypsibius** [comment]
I grove trekk einig med Caroline. Ordbøkene har faktisk ingen bokmålsdefinisjon (!) av treslag, men brukar det dess fleire gonger i forklaringar (!). JF nynorskordboka, kan det brukast både om art, slekt og vyrke frå gitt art, tydelegvis.

**Comment by danmichaelo** [comment]
Takk, her var det behov for opprydning! Har foreløpig gjort følgende:

* Slått sammen `Trær BF Treslag BF Tresorter`. Som nevnt var `Treslag` brukt en del om vedtyper, så jeg flytter de postene over til `Trevirke`.

* Slått sammen `Trevirke BF Treverk BF Trematerialer BF Ved BF Treprodukter`. Kanskje litt pragmatisk å blande sammen alt mulig som kommer fra trær, men ut fra dagens bruk så det ikke ut som sammenslåingen ville føre til redusert spesifisitet. Skulle vi ønske å skille ut noe i fremtiden, er det nok et bedre utgangspunktet å ta det ut fra en samlet dokumentbase.

* Slettet `Treteknologi`.

* Endret `Treskurder` til `Treskurd` og la til `Treskjæring` (nb) / `Treskjering` (nn).

`Tresløyd` lot jeg stå inntil videre. Det er vel definert som en ikke-profesjonell aktivitet, mens `Treskurd` også kan være profesjonell. Men vet ikke helt. Litt usikker på om jeg synes sløyd hører hjemme i Realfagstermer i det hele tatt også.

**Comment by danmichaelo** [comment]
Slo sammen Treanatomi BF Vedanatomi, jfr. https://github.com/realfagstermer/realfagstermer/issues/480#issuecomment-656666874

Fjernet "Wood structures".

Tror ikke det gjenstår noe mer da? Si fra hvis jeg har glemt noe!
