### ISSUE TITLE
Nytt stedsnavn: Moldova

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1637]
**Foretrukket term:** Moldova

 - Bokmål: (Fylles inn) Moldova
 - Nynorsk: (Fylles inn) Moldova
 - Engelsk: (Fylles inn) Moldova

**Alternative termer:** Republikken Moldova, Republic of Moldova, Republica Moldova

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:**

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:** "The red book of the Republic of Moldova" (k19040355)

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
Opprettet! Beklager at det tok så lang tid!
