### ISSUE TITLE
Inkonsistens - Polarområdene

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1638]
Ville det ikkje vere logisk å ha Polarområder BF Polområder eller Polarområdene BF Polområdene?

Polarområdene (REAL030576)
  EN Polar regions
  BF Polarområder
     Polområder
     Polare strøk
  DA 2015-02-20
  DR 2016-05-24
  FT sted

**Comment by Hypsibius** [comment]
Vidare manglar NN og EN 

NN Polarområda (bestemt form)  Polarområde (ubestemt form)
NN Polområda vs Polområde
NN Polare strok

EN Polar Regions

**Comment by danmichaelo** [comment]
Tror bestemt form er riktig hvis vi snakker om to bestemte områder (områdene rundt Nord- og Sydpolen)

La til 

BF Polområdene
BF Polarregionene
BF Polregionene
NN Polarområda
NN Polområda
NN Polarregionane
NN Polregionane
NN Polare strok

Engelsk fantes fra før.
