### ISSUE TITLE
Opiater og opioider

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#1639]
Mail fra Bente:

> Ser at opiat finnes i Roald Har nå en diss om opioider, og finner denne artikkelen:
>
> https://tidsskriftet.no/2011/07/sprakspalten/opiat-eller-opioid
>
> Skal vi endre, eller lumpe dem sammen?

Fra artikkelen: "Moderne teknologi har gjort begrepet opiat avleggs og uklart, siden det i dag er mulig å fremstille også de naturlig forekommende opiatene syntetisk"

Så vi endrer til opioider. Beholder opiater som alternativ term inntil videre for søkbarheten, men vi kan jo vurdere å skjule den etterhvert hvis vi får støtte for skjulte termer, siden det finnes opiater som ikke er opioider.

**Comment by BioHeidi** [comment]
Ser det greit ut Jessica? Fikser du, Gro Synnøve? (eller er det gjort allerede og vi kan lukke denne?)

**Comment by vibekelundetrae** [comment]
Det ser ut som de er slått sammen allerede i Realfagstermer
https://data.ub.uio.no/skosmos/realfagstermer/nb/page/c003557

Tror saken kan lukkes

**Comment by grosyn** [comment]
Ok, då lukkar eg den.
