### ISSUE TITLE
Oljeindustri, Petrokjemisk industri, Petroleumsindustri, Gassindustri

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#164]
Rom for sammenslåing?

**Comment by mzyg** [comment]
Petroleumsindustri inkluderer gassindustri og oljeindustri, men gassindustri (oljeindustri) inkluderer ikke alle fasetter av petroleumsindustrien. Jeg kan tenke meg at det er nyttig at man kan søke bare for enten gassindustri eller oljeindustri. 
Petrokjemi er en term for (blant annet) den kjemiske omvandlingen fra petroleum – kanskje også en del av petroleumsindustrien men helt sikkert ikke et synonym.
 Svaret er derfor nei, jeg syns ikke at det er rom for sammenslåing. :-)

**Comment by danmichaelo** [comment]
Men trenger vi det spesifisitetsnivået? Olje- og gassindustrien sees veldig ofte samlet. Jeg stemmer for `Petroleumsindustri BF Oljeindustri, Gassindustri`, men beholde `Petrokjemisk industri`.

**Comment by mzyg** [comment]
Det kan vi gjøre.

**Comment by danmichaelo** [comment]
Gjort
