### ISSUE TITLE
morkaken 

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1642]
**morkaken **

 - Bokmål: (morkaken )
 - Nynorsk: (morkak a/en)
 - placenta: 

**Alternative termer:**
placenta 

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:**
612.64

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:**

https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71493814200002201&context=L&vid=UIO&lang=no_NO&search_scope=default_scope&adaptor=Local%20Search%20Engine&isFrbr=true&tab=default_tab&query=any,contains,placenta%20loke&offset=0

Loke: life's vital link 9780199694518
(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by Hypsibius** [comment]
Er denne lukka fordi den er oppretta? Og gløyte eg å legge til til min kommentar? *gremmm*

Altså: Korrigere til 

Bokmål: (morkaka/en)
Nynorsk: (morkaka)
BF placentaen 

Jf https://ordbok.uib.no/perl/ordbok.cgi?OPP=morkake&ant_bokmaal=5&ant_nynorsk=5&begge=+&ordbok=begge

![image](https://user-images.githubusercontent.com/9350370/75023515-38078300-5498-11ea-9f85-4ee38c62df0a.png)

**Comment by danmichaelo** [comment]
Vet ikke. Den var ikke opprettet i hvert fall. Men nå er den det :)

REAL032234
