### ISSUE TITLE
Kiselalger REAL013933

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1643]
Jeg synes at vi bør legge til EN Diatoms
Jeg tror at diatomes kan brukes men er sjelden brukt. 
![image](https://user-images.githubusercontent.com/42732381/74834848-855ee580-531c-11ea-8e18-fdb46aafd4a3.png)

**Comment by danmichaelo** [comment]
La Diatoms som foretrukket term, Diatomes som alternativ.
