### ISSUE TITLE
Øyet REAL006305

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1644]
![image](https://user-images.githubusercontent.com/42732381/74840157-c78d2480-5326-11ea-9448-27b17a563a6d.png)
Jeg foreslår at denne utvides litt til å dekke forskellige typer øye, siden jeg kan ikke finne en egen term for disse, e.g.
EN Eyespot(s), EN Ocelli, (EN Ocellus) EN [Simple eye](https://en.wikipedia.org/wiki/Simple_eye_in_invertebrates), EN Compound eye
(brukt parantheses fordi jeg er litt usikker om disse bør være flertall eller entall).

Det er muligens en liten disambiguation problem med ["eyespots" siden den er også brukt i sammenheng med mimicry](https://en.wikipedia.org/wiki/Eyespot_(mimicry)).

**Comment by danmichaelo** [comment]
Den var allerede brukt om en del forskjellige øyne, så endret "Øyet" til "Øyne". Fasettøyne hadde vi som eget begrep. La inn SO mellom dem.

```
Øyne
BF Punktøyne
NN Augo
NN Punktaugo
EN Eyes
EN Simple eyes
EN Eyespots
EN Ocelli
SO Fasettøyne
```

Kan være vi kunne hatt flere typer øyne som egne emneord, men virker som det er et vell av dem
