### ISSUE TITLE
Skogplanting + Skogreising

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1645]
![image](https://user-images.githubusercontent.com/42732381/75020135-64200580-5492-11ea-9c62-d7dcf4c9a082.png)
![image](https://user-images.githubusercontent.com/42732381/75020148-6b471380-5492-11ea-8e95-60c302e5a0c4.png)
Litt usikker hvilke burde være foretrukket termen. 
Foreslår også at vi legge til en SO Gjengroing (REAL010085), siden på engelsk er afforestation og reforestation ganske tett.

**Comment by danmichaelo** [comment]
Hm, så [`skogreising`](http://www.skogbruk.nibio.no/skogreising) er (primært) "planting eller såing på arealer som tidligere ikke var klassifisert som skog", mens [`skogplanting`](http://www.skogbruk.nibio.no/stende-volum-1-1) brukes bredere, også om "planting etter hogst"?

Hvis de skal slåes sammen bør vel da skogplanting være foretrukken term. Men kan være en også skulle beholdt begge, og endret oversettelsen for "Skogplanting" til "Forestation"..?

**Comment by Caroline-A** [comment]
Ah ok, jeg forstår forskjellen nå, jeg var litt forvirret med den engelske _afforestation_ :) De kan godt holdes seperat da, men da er jeg enig med deg i at den engelske termen på skogplanting endres - jeg foreslår _EN Reforestation EN Forestation_. 

_Forestation_ er litt bredere enn _reforestation_ ([ifølge wikipedia dekke den både reforestation og afforestation](https://en.wikipedia.org/wiki/Forestation)), men da er den kanskje det samme som den norske _skogplanting_, som virker også litt overordnet. Så kanksje dette er ok. Skulle _skogreising_ være UT for _skogplanting_?

 _EN Reforestation_ er også brukt som term på "_Gjengroing_" (REAL010085). Men det er kanksje litt uungåelig at vi må bruke den to ganger, siden _reforestation_ kan brukes for både naturlig gjengroing og skogreising...

**Comment by danmichaelo** [comment]
Endret til `EN Reforestation EN Forestation`, la til definisjon "planting eller såing på arealer som tidligere ikke var klassifisert som skog (Nibio)" på Skogreising, og la til `SO Gjengroing`.
