### ISSUE TITLE
Mykotoksiner + Soppgifter

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1646]
![image](https://user-images.githubusercontent.com/42732381/75033923-4f506b80-54ac-11ea-9e75-6269c043ada2.png)
![image](https://user-images.githubusercontent.com/42732381/75033934-54adb600-54ac-11ea-8d48-a7cafc63a4f5.png)
Jeg er ikke sopp ekspert men tror at disse er det samme. 
https://www.who.int/news-room/fact-sheets/detail/mycotoxins

**Comment by danmichaelo** [comment]
Godt funn! Sjekket med @haraldse (som er gift med en soppekspert :)) og slo de sammen.
