### ISSUE TITLE
Makroalger

### ISSUE THREAD

**Issue by Caroline-A** [realfagstermer/realfagstermer#1647]
![image](https://user-images.githubusercontent.com/42732381/75040757-8bd79380-54bb-11ea-9acf-33ab47a50161.png)
![image](https://user-images.githubusercontent.com/42732381/75040778-93973800-54bb-11ea-9675-3df73bc98a30.png)
Her har tare blitt lagt til _Makroalger_ som BF, men den har også egen term. 
Jeg foreslår at BF/NN Tare og EN Kelp fjernes fra _Makroalger_; og at BF Tare er lagt til _Tarer_. 
Vi har LA Laminariales på _Tarer_, men det er litt uheldig at ikke alle tarearter tilhører Laminariales (e.g. Draugtare). Jeg lurer på om den skulle fjernes.

**Comment by danmichaelo** [comment]
Takk, fiksa!

La til henvisninger også (Brunalger -> Tarer, og Tarer <> Makroalger)

Usikker når det gjelder vit. navn. Hvis tare er et navn som *primært* viser til *Laminariales* kan det kanskje være ok å beholde allikevel. Rent praktisk, er det (potensielt) nyttig at søket utvides med "Laminariales" hvis en søker etter "tare(r)"?

**Comment by Caroline-A** [comment]
Bra med disse henvisninger!
Ja, fra en praktisk perspektiv er det en fordel at Laminariales beholdes, selv om det ikke er 100 % biologisk korrekt :) Gjerne beholde den - jeg var litt usikker på hvor streng vi er med slike ting.

**Comment by Hypsibius** [comment]
Var sikkert eg som mvar litt kjapp med å slenge på laminarialesane, beklager. Og formene (tare vs tarer) forklarar kvifor eg ikkje fekk treff på tarane då eg søkte. Makroalgar er jo ellers  ein overordna term (OT), og i tillegg til tang og tare, omfattar den jo både raudalgar og makroskopiske grønalgar. Og brunalgar som ikkje er verken laminariales eller fucales, Tenker likevel vi har nok tarelitteratur til å kunne skille ut 'tarer' som eigen term. I staden for å fjerne Laminariales, kan vi kanskje legge til andre relevante ordnar, som 'Tilopteridales'? Eller er ikkje alle å betrakte som 'tarar'? Er det evt fleire?

**Comment by Caroline-A** [comment]
Mange Tilopteridales er ikke tare, det er bare en art i Norge (som jeg vet om) som regnes som tare fra denne gruppe. Så jeg tror det er best om den ikke legges til. 

Jeg synes at henvisninger ser bra ut som de er nå i systemet, men man kunne ha _Stortare_ <> _Tarer_. Det er kanksje litt rart å ha _Blæretang_ som egen term (REAL012832), det er bare en dok som den er brukt på. Den kunne slettes? Evt. kan vi opprette en term for Fucaceae.

**Comment by danmichaelo** [comment]
>  jeg var litt usikker på hvor streng vi er med slike ting. 

Vi er ganske pragmatiske :)

> Jeg synes at henvisninger ser bra ut som de er nå i systemet, men man kunne ha _Stortare_ <> _Tarer_.

Lagt til! 

> Det er kanksje litt rart å ha _Blæretang_ som egen term (REAL012832), det er bare en dok som den er brukt på. Den kunne slettes? Evt. kan vi opprette en term for Fucaceae. 

Sant. Vi kan enten opprette _Fucaceae_, eller eventuelt _Tang (Fucales)_? Er det greit at tang er en BF på Makroalger, eller hadde det vært bedre å ha den som eget emneord?

**Comment by Caroline-A** [comment]
Jeg begynte faktisk på å foreslå et emneord for Fucales - de er en viktig gruppe. Men så gå opp litt fordi jeg synes ordet "tang" er vanskelig på norsk. Det virker som noen ganger er den brukt bare om Fucales, mens andre ganger er den brukt for alle slags makroalger, særlig når det gjelder spiselige alger. Skolmetang og Japansk drivtang tilhører Fucales, men ikke Fucaceae. 
Hvis det går en med en slags disambiguation som du foreslår her (_Tang (Fucales)_) da kan det kanskje fungere. Men det er kanskje også lurt at _Tang_ beholdes også som BF på _Makroalger_ (?)

Da er forslaget mitt:

Tang (Fucales)
BF _Sauetang, blæretang, grisetang, spiraltang, sagtang, båetang, skolmetang_
EN Fucoids, wracks, rockweeds, _serrated wrack, toothed wrack, bladderwrack, channelled wrack, knotted wrack, egg wrack, two-headed wrack_
LA Fucales
OT Brunalger, Makroalger
SO Brunalger, Tarer
(Dewey 579.888)

Jeg er usikker på om det er lurt å legge til artsnavn for noen arter som er vanlige i norge (gitt i italics). Jeg har ikke sett slik praksis for andre artsgrupper, så kanskje de bør ikke tas med...

**Comment by Hypsibius** [comment]
Tenker det kan løysast på den måten, @Caroline-A Vi har lagt til aktuelle artar som ikkje får eigen innførsel på tilsvarande mæte før, men kanksje ikkje like mange av slengen? Eg oppfattar 'tang' som Fucales, men som alle hevdnamn, brukast den upresist i blant ;-)

Vi er dessutan utsette for smitte frå dansk og svensk, som brukar tang om fleire grupper

Skal vi legge til bF Kaurtang, som synonym for spiraltang?

**Comment by danmichaelo** [comment]
Har omsider lagt inn forslaget til `Tang (Fucales)`! Beklager forsinkelsen. Tok med alle artsnavnene. Søkemessig er det ganske praktisk å ha dem med, selv om vi ideelt sett skulle kunne skilt dem ut på en eller annen måte. Vi kan evt. ta en prinsipiell diskusjon om det på et senere tidspunkt når @BioHeidi er tilbake. Hyggelig å se deg på biblioteksløyd forresten, @Caroline-A !
