### ISSUE TITLE
Østensjøvannet

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1648]
**Foretrukket term:**

 - Bokmål: (Fylles inn)
 - Nynorsk: (Fylles inn)
 - Engelsk: (Fylles inn)

**Alternative termer:**

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:**

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:**
Fuglene ved Østensjøvannet i Oslo / MMS ID 999920723393602201
(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

NB!! Trenger strengen Fugler : Østensjøvannet

**Comment by Hypsibius** [comment]
Den strengen trur eg på!

**Comment by danmichaelo** [comment]
Omsider opprettet!
