### ISSUE TITLE
kinaser

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1649]
**kinaserForetrukket term:**

 - Bokmål: (kinaserFylles inn)
 - Nynorsk: kinasar)
 - Engelsk: (kinases)

**Alternative termer:**

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:**
616.9940072

jeg får ikke opp dewey til å sjekke kinaser 
(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:**
Sissel Hauge doktorgrad: Tageting cancer cells through inhibition of cell cycle checkpoint kinases 
(https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=TN_proquest1664202530&context=PC&vid=UIO&lang=no_NO&search_scope=default_scope&adaptor=primo_central_multiple_fe&tab=default_tab&query=any,contains,sissel%20hauge&offset=0Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
Opprettet! (omsider)
