### ISSUE TITLE
Foreslår Ny term Læringspsykologi? treng vi det?

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#1650]
Altså, eg oppfattta begrepet som distinkt frå læring. 

Humord har det som separat innførsel

SNL Har kun ein artikkel om læring, men snakkar likevel i fleire artiklar om Læringspsykologi

Eit google-søk eksempelvis gir treff som dei under. Kva seier de?For messy? Eller treng vi termen?

Søkeresultater
Nettresultater

Læringspsykologipsyk.cc › lbok
Kapittel 1. Introduksjon. Atferd hos dyr og mennesker kjennetegnes ved både stabilitet og endring. Stabilitet i atferd ses i en rekke sammenhenger: Folk ...

læring – Store norske leksikonsnl.no › Psykologi › Kognitiv psykologi
25. nov. 2013 - Moderne læringspsykologi har videreutviklet prinsippene beskrevet i de klassiske studiene nevnt over. Klassisk betinging har fått stor betydning i ...

Læringspsykologi - Norliwww.norli.no › laeringspsykologi
Boken tar for seg sentrale forskningsresultater og teorier innen læringspsykologien. Den går gjennom hva læring er, teoretiske fortolkninger og problemområder ...

Læringspsykologi - Psykologisk.nopsykologisk.no › emne › laeringspsykologi
Bør vi snu om på undervisningen? Universitetslærere bør bli mer opptatt av å få ting ut av studentenes hode, skriver Rannveig Grøm Sæle og Torstein Låg. 

Aktuelt dokument: https://bibsys-almaprimo.hosted.exlibrisgroup.com/permalink/f/8hnp7t/BIBSYS_ILS71476462940002201

**Comment by danmichaelo** [comment]
Hm, ja, vi har [`Læringsteorier`](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc013055), som nærmeste relaterte ("describes how students absorb, process, and retain knowledge during learning", https://en.wikipedia.org/wiki/Learning_theory_(education) )

Kjenner ikke feltet, men kan være vi også kan ha `Læringspsykologi`, med SO mellom dem? Mapping til https://en.wikipedia.org/wiki/Educational_psychology ?

```
Læringspsykologi
BF Utdanningspsykologi
NN Læringspsykologi
NN Utdanningspsykologi
EN Educational psychology
EN Psychology of education 
SO Læringsteorier
```

?

**Comment by grosyn** [comment]
@danmichaelo 
No er det vel bestemt at me ikkje skal ta inn slike termar som er litt på sida vis-à-vis realfag? Det held kanskje at dette er i Humord? 
Kan eg lukka saka?

**Comment by danmichaelo** [comment]
@grosyn Ja, enig!
