### ISSUE TITLE
Skjelldyr

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1651]
**Foretrukket term:**

 - Bokmål: Skjelldyr
 - Nynorsk: Skjelldyr
 - Engelsk: Pangolins

**Alternative termer:**

brukt for Pangoliner

**Definisjon, se-også-henvisninger og annet**

https://no.wikipedia.org/wiki/Skjelldyr

**Dewey-nummer:**
599.31

**Eksempel-dokument:**
k20009028

**Comment by danmichaelo** [comment]
Beklager treeeg saksbehandling! Opprettet nå!

**Comment by haraldse** [comment]
Søt, og takk - pangoliner er søte dyr

-----Original Message-----
