### ISSUE TITLE
sialinsyre

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1655]
**Foretrukket term:**

 - Bokmål: sialinsyre
 - Nynorsk: sialic acid
 - Engelsk: sialin syre 

**Alternative termer:**

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)
https://en.wikipedia.org/wiki/Sialic_acid
https://snl.no/sialinsyrer
**Dewey-nummer: 573.8419**¨
547.037

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her):
547.037

**Eksempel-dokument:**
k20005005
(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)
https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71588429960002201&context=L&vid=UIO&lang=no_NO&search_scope=default_scope&adaptor=Local%20Search%20Engine&isFrbr=true&tab=default_tab&query=any,contains,sialic%20acids%20and%20sialoglycoconjugates%20in%20the%20biology%20of%20life%20health%20and%20disease,%20ghosh%20shyamasree&sortby=date&facet=frbrgroupid,include,483496479&offset=0

**Comment by danmichaelo** [comment]
Endret fra entall til flertall. Opprettet

```
Sialinsyrer
NN Sialinsyrer
EN Sialic acids
```
