### ISSUE TITLE
DNA-polymerase

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1656]
**Foretrukket term:**

 - Bokmål: DNA-polymerase
 - Nynorsk: DNA-polymerase
 - Engelsk: DNA polymerases

**Alternative termer:**

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)
https://en.wikipedia.org/wiki/DNA_polymerase
https://snl.no/DNA-polymerase
https://www.mn.uio.no/ibv/tjenester/kunnskap/plantefys/leksikon/d/dnapo.html

**Dewey-nummer:**
5728645

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:**
k18051544
(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)
https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71567089820002201&context=L&vid=UIO&lang=no_NO&search_scope=default_scope&adaptor=Local%20Search%20Engine&tab=default_tab&query=any,contains,Dokid%20k18051544%20%20Human%20DNA%20polymerases%20:%20biology%20%20medicine%20and%20biotechnology&mode=Basic

**Comment by danmichaelo** [comment]
Endret bokmål og nynorsk fra entall til flertall. Opprettet

```
DNA-polymeraser
NN DNA-polymerasar
EN DNA polymerases
```

Vil du ha med "Se også: RNA-polymerase"?
