### ISSUE TITLE
Sandollar

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1657]
**Foretrukket term:**

 - Bokmål: sjømus
 - Nynorsk: sjømus
 - Engelsk: sand dollar

**Alternative termer:**
sandollar

sjøpiggsvin = kråkeboller+sjømus
(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

sjøpiggsvin = kråkeboller+sjømus. Realfagstermer nå= kråkeboller BF sjøpiggsvin 

https://snl.no/sj%C3%B8mus
(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)
https://en.wikipedia.org/wiki/Sand_dollar
https://snl.no/sanddollar

**Dewey-nummer:**
593.95
(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:**
K20005008
(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
Jeg tror en bedre løsning er å endre "Kråkeboller BF Sjøpiggsvin" til "Sjøpiggsvin BF Kråkeboller". Da har termen samme omfang på norsk og engelsk. Trenger du fortsatt sandollar da?

**Comment by danmichaelo** [comment]
Lukker denne. Kan åpnes igjen ved behov.
