### ISSUE TITLE
industriell mikrobiologi 

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1658]
**Foretrukket term:**

 - Bokmål: industriell mikrobiologi 
 - Nynorsk: industriell mikrobiologi 
 - Engelsk: Industrial microbiology

**Alternative termer:**
Anvendt mikrobiologi ? 
(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:**
660.62
(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:**
k20008870 
(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
Lag til `BF Industriell mikrobiologi` på `Anvendt mikrobiologi`
