### ISSUE TITLE
Algeoppblomstring

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#166]
Foreslår at det rettast til algeoppblomstringer (fleiretal). EN Algal blooms.Ser at det finst ein BF toksisk algeoppblomstring. Men gitt at ikkje-giftige algeoppblomstringar er meir eller mindre regelmessige og nødvendig næringsgrunnlag, er det ikkje mest ryddig å la giftige algeoppblomstringar vere for seg sjølv under 'giftige alger'?

**Comment by bibliomari** [comment]
@BioHeidi Jeg har lagt til engelsk. Trenger vi flertall her? Jeg tenker visst på det som et fenomen mer enn som konkrete manifestasjoner av fenomenet, men det er flisespikkeri det da, vi kan ha begge deler og bruke hva dere vil som foretrukken term. 

Heidi, ok å fjerne Toksisk oppblomstring? Kanskje Oppblomstring også...

**Comment by Hypsibius** [comment]
Jo, ser poenget med fenomen kontra konkrete manifestasjonar, har fleire liknande døme. Held likevel ein knapp på 'algeoppblomstringer' i fleirtal, ettersom marinbotanikerar ser ut til å tenke på dei i fleirtal (vår- og haustopplomstringar, suksesjon av ulike algegrupper gjennom ein oppblomstringssituasjon)

**Comment by Hypsibius** [comment]
Kan vi konkludere, tru?

**Comment by BioHeidi** [comment]
Jeg må rydde litt i trefflisten på denne hvis vi skal skille ut 'toksisk algeoppblomstring' og hive de aktuelle treffene over på 'giftige alger'.

**Comment by Hypsibius** [comment]
Sei frå om det er noko arbeid eg kan gjere, som eg ikkje treng tilgang til den S-greia for å gjere?

**Comment by bibliomari** [comment]
Algeoppblomstringer er gjort.

**Comment by Hypsibius** [comment]
Tida for denslags! https://www.nersc.no/sites/www.nersc.no/files/imagecache/front_service_image/123_0.jpg
