### ISSUE TITLE
Kjemiske forsøk

### ISSUE THREAD

**Issue by kyrretl** [realfagstermer/realfagstermer#1661]
Slettes! 
Er på ett dokument og er overflødig i forhold til Kjemiforsøk -> Kjemieksperimenter

---
*REAL002461 (Kjemiske forsøk) i [Emnesøk](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002461), [Skosmos](http://data.ub.uio.no/realfagstermer/c002461), [Okapi](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kjemiske%20fors%C3%B8k%22), [Soksed](http://ub-soksed.uio.no/concepts/REAL002461)*

**Comment by danmichaelo** [comment]
Slettet

**Comment by danmichaelo** [comment]
Overordnet sak: #1479
