### ISSUE TITLE
Utslippshandel

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1665]
**Foretrukket term:** Utslippshandel

 - Bokmål: (Fylles inn) Utslippshandel
 - Nynorsk: (Fylles inn) Utsleppshandel
 - Engelsk: (Fylles inn) Emissions trading

**Alternative termer:** Kvotehandel

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet** Kvotejamdel; Handel med CO2-kvoter
https://no.qwe.wiki/wiki/Emissions_trading
(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:**

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:** The evolution of carbon markets : design and diffusion - https://www.taylorfrancis.com/books/e/9781315228266

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)
https://tinyurl.com/yc9wygoa

**Comment by danmichaelo** [comment]
Beklager sen behandling! Opprettet!
