### ISSUE TITLE
Første verdenskrig

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1666]
**Foretrukket term:** Første verdenskrig

 - Bokmål: (Fylles inn) Første verdenskrig
 - Nynorsk: (Fylles inn) Første verdskrig / den første verdskrigen / 1. verdskrig
 - Engelsk: (Fylles inn) World War I / (the) First World War / WWI / WW1 / the Great War

**Alternative termer:** Verdenskrigen 1914-1918 / 1. verdenskrig

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet** 

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.) https://en.wikipedia.org/wiki/World_War_I

**Dewey-nummer:**

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:** 

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)
https://tinyurl.com/y6rbbxnq

**Comment by danmichaelo** [comment]
Beklager sen behandling! Opprettet!

**Comment by danmichaelo** [comment]
Fantes allerede som tidsperiode. Jeg er ikke 100 % sikker på at det er riktig å ha historiske hendelser der, men det er en annen sak :)

La den inn på 999920208206402204
