### ISSUE TITLE
kroniske sykdommer

### ISSUE THREAD

**Issue by haraldse** [realfagstermer/realfagstermer#1667]
**Foretrukket term:**

 - Bokmål: kroniske sykdommer
 - Nynorsk: kroniske sjukdommar
 - Engelsk: kroniske sjukdomar

**Alternative termer:**

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**kanskje...ha med Følgesykdommer  (se også) Definisjon, se-også-henvisninger og annet**

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)
https://no.wikipedia.org/wiki/Kronisk_sykdom
https://www.fhi.no/publ/2020/oppfolging-av-kroniske-sykdommer-med-medisinsk-avstandsoppfolging-i-primarh/
https://en.wikipedia.org/wiki/Multiple_morbidities
https://apps.who.int/iris/bitstream/handle/10665/252275/9789241511650-eng.pdf?sequence=1

**616.044**

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71467243720002201&context=L&vid=UIO&lang=no_NO&search_scope=default_scope&adaptor=Local%20Search%20Engine&isFrbr=true&tab=default_tab&query=any,contains,abc%20of%20multimorbidity&offset=0**

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
Opprettet! Med "chronic diseases" på engelsk.
