### ISSUE TITLE
Oumuamua

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1668]
**Foretrukket term:** Oumuamua

 - Bokmål: (Fylles inn) Oumuamua
 - Nynorsk: (Fylles inn) Oumuamua
 - Engelsk: (Fylles inn) Oumuamua

**Alternative termer:** 

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet** Interstellare objekter

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.) https://sv.wikipedia.org/wiki/1I/%CA%BBOumuamua
https://en.wikipedia.org/wiki/%CA%BBOumuamua

**Dewey-nummer:** 576.839

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:** "Extraterrestrial : the first sign of intelligent life beyond Earth" 
https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=BIBSYS_ILS71613849440002201&context=L&vid=UIO&lang=no_NO&search_scope=default_scope&adaptor=Local%20Search%20Engine&tab=default_tab&query=any,contains,extraterrestrial%20the%20first&offset=0

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
Kanskje i mest spesifikke laget, men opprettet den, jeg. Med `ʻOumuamua` som foretrukken term.

**Comment by grosyn** [comment]
Ja, eg tenkte den var litt spesifikk, men det var jo det boka handla om.

Mvh
Gro Synnøve


17. jun. 2021 kl. 15:24 skrev Dan Michael O. Heggø ***@***.***>:

﻿

Kanskje i mest spesifikke laget, men opprettet den, jeg. Med ʻOumuamua som foretrukken term.
