### ISSUE TITLE
Intermolekylære krefter/reaksjoner

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#167]
Jeg så i lokar-loggen at Intermolekylære krefter har blitt endret til Intermolekylære reaksjoner. Jeg mener at det blir missvisende av flere grunner.

1. I kjemiske reaksjoner tenker jeg at den kovalente strukturen endres hos en eller flere komponenter. Intermolekylære krefter er relevante for mange fenomener hvor der ikke skjer noen reaksjoner i den forstanden. Noen eksempel fra biokjemien: lipider i cellmembraner, amyloid aggregering, proteinfolding, proteindenaturering (det vil si hydrofobe krefter, van der Waals, saltbrygger, hydrogenbindninger, etc.)
2. Hva betyr Intermolekylære reaksjoner? Siden alle reaksjoner inneholder mer enn et ledd, enten A+B->C eller A->B+C, eller noe mer komplisert - altså hvilke kjemiske reaksjoner er ikke intramolekylære? Muligens vil en skille mellom atomære og molekylære, men intermolekylære gir ikke mening.
3. Som forfatter av flere vitenskaplige artikler om inter/intra-molekylære krefter i proteiner mener jeg definitivt detter er et separat og viktig emne  ;)

Edit: Det er mulig termen kan slettes hvis begge betydningen dekkes av andre termer, men det er definitivt to forskjellige ting.

**Comment by danmichaelo** [comment]
Enig, virker som en liten glipp. Fra en liten titt på litteraturbelegget fant jeg forresten `Molekylkrefter`. Den kan vi vel legge inn som BF på `Intermolekylære krefter`?

**Comment by mittinatten** [comment]
Ja, og legge til `BF Intramolekylære krefter`, siden det er samme krefter dreier seg om. Hadde kanskje vært mest logisk å ha `Molekylære krefter` eller noe lignende som hovedterm, men tror nok `Intermolekylære krefter` er den mest brukte varianten.

**Comment by mittinatten** [comment]
Jeg foreslår

    Intermolekylære krefter
    BF Molekylære krefter
    BF Intramolekylære krefter
    BF Molekylkrefter
    EN Intermolecular forces
    EN Intramolecular forces
    EN Molecular forces
    NN ...krafter

**Comment by danmichaelo** [comment]
:+1:

**Comment by Hypsibius** [comment]
Kjøper resten usett, men insisterer på NN ...krefter ;-)

**Comment by mittinatten** [comment]
Det jeg glemte å si var at termen Molekylkrefter også må slettes, men kanskje Sonja sier fra automatisk når en legger til en BF-term som allerede finnes som selvstendig term.

Jeg ser nå at i hvert fall engelsek wikipedia skiller på intra- og inter-: kovalente bindninger er inkludert i intramolekylære krefter, selv om jeg syns det føles litt rart å snakke om kovalente krefter. Jeg tenker at kovalente bindninger er inkludert i skillet intra/inter, siden det er det som avgjører om to atomer tilhører samme molekyl eller ikke, altså det er en del av definisjonen av inter vs intra, ikke en kreft i denne sammenhengen.

Jeg foreslår en definisjon for å gjøre det tydeligere: Ikke-kovalente interaksjoner mellom molekyler og mellom forskjellige deler av samme molekyl.

**Comment by BioHeidi** [comment]
Ups, min feil! Det er definitivt en glipp ja, jeg vet ikke helt hva jeg har lest der. Jeg rydder.

**Comment by BioHeidi** [comment]
M - olekyl - milestone.
Jeg har snudd på term og BF og fjernet Intermolekylære reaksjoner. Og lagt til alle BF-ene og engelsk. Sjekk at det ser rett ut nå!

**Comment by mittinatten** [comment]
Ser bra ut! Definisjonen var bare et forslag, det er mulig den kan forbedres.

**Comment by danmichaelo** [comment]
Denne er ferdig diskutert, er den ikke?

**Comment by mittinatten** [comment]
Ja

**Comment by bibliomari** [comment]
Og ser ut som den også kan lukkes, eller hva @BioHeidi
