### ISSUE TITLE
Pegmatitter

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1670]
**Foretrukket term:** Pegmatitter

 - Bokmål: (Fylles inn) Pegmatitter
 - Nynorsk: (Fylles inn) Pegmatitter
 - Engelsk: (Fylles inn) Pegmatites

**Alternative termer:** OT: Gangbergarter OT: Dypbergarter/Plutoniske bergarter

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet** "Pegmatitt er en meget grovkornet bergart, vanligvis dannet ved krystallisasjon av vandige restløsninger som blir tilbake ved størkningen av et magma." (SNL) - https://snl.no/pegmatitt
https://no.wikipedia.org/wiki/Pegmatitt

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:** 552.3 (Plutoniske bergarter) 

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:** k18059302 "Pegmatites" 
Oria: https://tinyurl.com/ye4jsc8a
(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
Opprettet, og lagt på posten!
