### ISSUE TITLE
Reddiksopper

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1671]
**Foretrukket term:** Reddiksopper

 - Bokmål: (Fylles inn) Reddiksopper
 - Nynorsk: (Fylles inn) Reddiksoppar
 - Engelsk: (Fylles inn) Hebeloma (usikker på om dei har ein engelsk term)

**Alternative termer:** Hebeloma (lat.) 

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet** 
https://snl.no/reddiksopp
https://en.wikipedia.org/wiki/Hebeloma

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:** 579.6

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:** k21014769 - Hebeloma (Fr.) P. Kumm.
https://bibsys-almaprimo.hosted.exlibrisgroup.com/permalink/f/13vfukn/BIBSYS_ILS71565678460002201

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
Opprettet (REAL032275)
