### ISSUE TITLE
Kragesopper/Kragesoppfamilien

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1672]
**Foretrukket term:** Kragesopper eller Kragesoppfamilien ?

 - Bokmål: (Fylles inn) Kragesopper/Kragesoppfamilien
 - Nynorsk: (Fylles inn) Kragesoppar/Kragesoppfamilien
 - Engelsk: (Fylles inn) Strophariaceae (har ikkje funne engelsk term)

**Alternative termer:** Strophariaceae (lat.); Stropharia

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet** 
https://snl.no/kragesopp
https://en.wikipedia.org/wiki/Strophariaceae

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:** 579.6

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:** k21014767 - Strophariaceae 
https://bibsys-almaprimo.hosted.exlibrisgroup.com/permalink/f/13vfukn/BIBSYS_ILS71487394230002201

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
Opprettet. Litt usikker på det med å legge på undergrupper som *Stropharia* som alternative termer, men det er jo litt praktisk at de gir treff i søk uten at vi trenger å opprette egne termer for dem. Hva tenker du om det, @BioHeidi ?
