### ISSUE TITLE
Kryptiske arter

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1673]
**Foretrukket term:** Kryptiske arter

 - Bokmål: (Fylles inn) Kryptiske arter
 - Nynorsk: (Fylles inn) Kryptiske artar
 - Engelsk: (Fylles inn) Cryptic species

**Alternative termer:** Artsflokker, Artssvermer, Søskenflokker; Artskompleks (OT); Kryptiske søskenarter (UT)

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet** 
https://forskning.no/planteverden-dyreverden-dna/kronikk-forskere-krangler-om-kryptiske-arter/1164912
https://snl.no/artskompleks
https://no.wikipedia.org/wiki/Kryptisk_art

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:** ??

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:** 
https://bibsys-almaprimo.hosted.exlibrisgroup.com/permalink/f/13vfukn/BIBSYS_ILS71595969980002201

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
Opprettet (REAL032272). **Artskompleks**, som ble foreslått som OT, finnes ikke. Trenger vi den også? @BioHeidi
