### ISSUE TITLE
Fobier

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1674]
**Foretrukket term:** Fobier

 - Bokmål: (Fylles inn) Fobier
 - Nynorsk: (Fylles inn) Fobiar
 - Engelsk: (Fylles inn) Phobias

**Alternative termer:** OT: Frykt, Angst, Engstelse 
Frå HUMORD: https://data.ub.uio.no/skosmos/humord/nb/page/c29593

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet** 

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:** 

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:** 
https://bibsys-almaprimo.hosted.exlibrisgroup.com/permalink/f/13vfukn/BIBSYS_ILS71472236110002201
https://bibsys-almaprimo.hosted.exlibrisgroup.com/permalink/f/13vfukn/BIBSYS_ILS71616623200002201
https://bibsys-almaprimo.hosted.exlibrisgroup.com/permalink/f/vo8oc9/BIBSYS_ILS71615855290002201

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by vibekelundetrae** [comment]
Ja, enig i det!
