### ISSUE TITLE
Veganisme

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1675]
**Foretrukket term:** Veganisme

 - Bokmål: (Fylles inn) Veganisme
 - Nynorsk: (Fylles inn) Veganisme
 - Engelsk: (Fylles inn) Veganism

**Alternative termer:** Vegetarianisme

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet** 

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:** 179.3

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:** 
https://bibsys-almaprimo.hosted.exlibrisgroup.com/permalink/f/13vfukn/BIBSYS_ILS71611908670002201

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
Er dette kanskje en term vi overlater til Humord nå som vi har bestemt at vi gjør det for generelle termer? @grosyn @vibekelundetrae ?

**Comment by vibekelundetrae** [comment]
God idé!
