### ISSUE TITLE
Klimafiksing

### ISSUE THREAD

**Issue by vibekelundetrae** [realfagstermer/realfagstermer#1679]
**Foretrukket term:** Klimafiksing

 - Bokmål: Klimafiksing
 - Nynorsk: (Fylles inn)
 - Engelsk: Geoengineering

**Alternative termer:**

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet** Å gjøre inngrep i Jordas klimasystem med sikte på å redusere den globale oppvarmingen (UiO-definisjon)

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:**363.738747

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:** Barcode: k1702136

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

OBS! Humord bruker "Geoengineering" for dette også som norsk term

**Comment by danmichaelo** [comment]
REAL032273
