### ISSUE TITLE
oppstrømning EN upwelling

### ISSUE THREAD

**Issue by mzyg** [realfagstermer/realfagstermer#168]
15d006618 – har avhandling om ‘(..) upwelling in (..) India (..) during summer monsoon’ 
Foreslår oppstrømning NN oppvelling EN upwelling 
http://no.wikipedia.org/wiki/Oppstr%C3%B8mning
https://metlex.met.no/wiki/Oppstr%C3%B8mning

**Comment by bibliomari** [comment]
Gjort.
