### ISSUE TITLE
Atacama Large Millimeter/submillimeter Array (ALMA)

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1680]
**Foretrukket term:** Atacama Large Millimeter/submillimeter Array (ALMA)

 - Bokmål: (Fylles inn) Ser ikke ut som denne er oversatt til norsk - se på denne SNL-sida: https://snl.no/Betelgeuse
 - Nynorsk: (Fylles inn) Har heller ikkje funne ei omsetjing til nynorsk av denne termen
 - Engelsk: (Fylles inn) Atacama Large Millimeter/submillimeter Array

**Alternative termer:** ALMA

(Fyll inn eventuelle alternative termer her (synonymer, nær-synonymer og nærliggende termer som for praktiske formål grupperes sammen)

**Definisjon, se-også-henvisninger og annet** "Atacama Large Millimeter Array (ALMA) er en gruppe radioteleskoper i Atacamaørkenen i Chile bestående av 66 radioteleskoper spredt over et område på opptil 16 kilometer i diameter,[1] som tilsammen har en oppløsning på 0,01 buesekunder." 
https://no.wikipedia.org/wiki/Atacama_Large_Millimeter_Array 
https://www.eso.org/public/teles-instr/alma/

(Definisjon, lenke til Wikipedia/SNL, se-også-henv.)

**Dewey-nummer:** 

(Hvis du har et forslag til matchende Dewey-nummer, fyll det inn her)

**Eksempel-dokument:** 
https://bibsys-almaprimo.hosted.exlibrisgroup.com/permalink/f/140c4go/BIBSYS_ILS71633437270002201

(Legg gjerne inn en lenke til et dokument i Oria du har tenkt å bruke emneordet på)

**Comment by danmichaelo** [comment]
I LC er det en navneautoritet (https://id.loc.gov/authorities/names/no2002028046.html), men det har vi ikke, så opprettet den som term (650).

REAL032269

@superLine t.o.
