### ISSUE TITLE
CO2-håndtering som ny term?

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1687]
Eg har sett på SINTEF sine sider, samt Regjeringen.no at CO2-håndtering blir bruka om CO2 fangst, transport og lagring. Forkortinga som vert bruka er den engelske CCS - Carbon Capture and Storage. 
Me har CO2-lagring i Realfagstermer. Denne blir for snever i mange samanhenger. Eg har ei doktoravhandling framføre meg som heiter "Applicability of noble gases for CO2 capture and storage monitoring". Her ville det kanskje ha passa betre med CO2-håndtering enn med CO2-lagring?

 Ein kunne òg tenka seg at sidan me har CO2-lagring, burde me òg hatt CO2-fangst og CO2-transport som emnetermar?

Kva seier de, @edinab og @danmichaelo ?

**Comment by BioHeidi** [comment]
Jeg er ikke Edina eller Dan Michael, men jeg sier ja, opprett CO2-håndtering, og om det ikke er noen som protesterer ville jeg har satt CO2-lagring/fangst som BF. CO2-transport er tvetydig (i blod, i planter...)

**Comment by edinab** [comment]
Enig med Heidi.

+ CO2-transport kan også være aktuelt i noe tilfeller, men ikke ofte har jeg sett det.

Edina
________________________________

**Comment by danmichaelo** [comment]
Støtter utvidelse av `CO2-lagring` til `CO2-håndtering` / `CCS` og at det legges på BF-er fremfor å opprette flere forskjellige emner:

```
CO2-håndtering
BF CO2-lagring
BF CO2-fangst
osv..
```

(flere av dokumentene vi har fra før nok ville fått CCS om de hadde blitt klassifisert i dag)

I tillegg kan en jo opprette emner for bestemte metoder for CO2-fangst ved behov, f.eks. `aminvasking`.
