### ISSUE TITLE
Protoceller og Chemoton

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#1688]
Chemoton er såvidt jeg skjønner en tidli teori om Protoceller. Slås sammen med mindre noen protesterer.

**Comment by BioHeidi** [comment]
Og jeg tror Protoceller er mappet feil (BM til 572.57 Lipider og RM til 576.83, men burde være motsatt).

**Comment by grosyn** [comment]
@BioHeidi Har slått saman desse no, men er usikker på korleis eg rettar opp det andre.
