### ISSUE TITLE
Bananer

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1698]
Eg har ei bok her som heiter "Bananas and plantains". Bananer må vel inn som emneord? (Me har f.eks. Epler frå før.)
Eg ser at ein kan bruka Kokebanan, Melbanan, Matbanan og Plantain på norsk om "Plantain", men har det noka hensikt å ta dette inn som nytt emneord? Kor mange bøker får me om kokebanan? 
Mitt forslag er å ta inn Bananer som hovudterm, og ha henvisningar frå Kokebanan, Melbanan, Matbanan og Plantain - sjølv om dette vel blir feil reint botanisk sett.

Kva seier de, @BioHeidi @haraldse ?

**Comment by BioHeidi** [comment]
Alltid litt tricky med domestiserte greier. 
Og "feil botanisk sett" kan vi ikke ha i Realfagstermer symes jeg, så da foreslår jeg:
Det kan være greit å ha et emneord for frukten banan, som også kan dekke planteslekten Musaceae (banan og ensete). Men vi må skille mellom (ekte) plantain og kokebanan, for plantain tilhører en annen orden enn banan. Så da spørs det hva som dekkes i boken, er det kokebanan eller ekte plantain? Hvis det er det første trenger vi ikke å opprette plantains som emneord, da kan vi ha:

Bananer BF banan, kokebanan, melbanan, matbanan
NN fikser du bedre enn meg!
EN Bananas
LA Musaceae
OT Ingefærfamilien

**Comment by BioHeidi** [comment]
Dewey: Det er litt lenge siden jeg tenkte på dette, men hvordan var det med inkluderernotene igjen, skulle de mappes BM eller RM? Ser på mappingene til 584.88 at det er gjort begge deler. Bananer mappes hit og til 641.34772.

**Comment by grosyn** [comment]
Eg får ikkje sjekka boka lenger, sidan den er på veg til NHM, men her er eit samandrag eg fann:
"Bananas and plantains are major fruit crops in the tropics and subtropics, making a vital contribution to the economies of many countries. In the last 15 years, substantial changes have occurred in banana production, among them the increased importance of fungal and viral diseases and their serious impact on Cavendish export cultivars, smallholder plantains and cooking bananas. Changes in production systems such as protected greenhouse cultivation, organic, fair-trade and integrated cultivation and their respective certification schemes have also become prominent. This book provides an accessible review of the scientific principles of banana production and how these relate to field practices. Revised and updated with expanded coverage of world trade statistics and policies, breeding of new cultivars in relation to disease resistance and markets, prospects for genetically-modified bananas and the increasing role of endophytes in controlling pests and diseases, this new edition is an essential resource for researchers and students in horticulture."

På posten frå LC ligg emneorda Bananas og Plantago.

LC har brukt 641.34772 som Dewey (utg. 22)

**Comment by haraldse** [comment]
Jeg forstår snl og artsdatabanken. slik at bananer, kokebananer  inkludert , tilhører slekten Muca. Med andre ord er emneord bananer helt greit  Botanisk. Sitter på iPhone så dobbeltsjekk litt tungt men kommer tilbake hvis jeg er finner det feil. Jeg ser at ordet plantain finnes på norsk, men det er ikke brukt

**Comment by haraldse** [comment]
Ser du Heidi har funnet at plantain tilhører en annen orden.  Fant ikke det.  , men snakker vi om Plabtago? Det er noe annet enn banan. Da snakker vi om kjempeslekta

**Comment by grosyn** [comment]
Slik er det ordna i Dewey:
![image](https://user-images.githubusercontent.com/12611325/152934821-ea7169ab-37e8-4d06-82af-5c1e84e4a9c1.png)

Og frå den på engelsk:
![image](https://user-images.githubusercontent.com/12611325/152934633-882f6f8c-22a1-4618-a289-018c705967f2.png)

**Comment by grosyn** [comment]
Slik er det ordna i WebDewey:
![image](https://user-images.githubusercontent.com/12611325/152935332-0e5fb14e-9686-42bb-a64b-ae48278144b5.png)

Og i engelsk WebDewey:
![image](https://user-images.githubusercontent.com/12611325/152935408-631d458c-03ea-43bc-89ae-5d5eab1928dd.png)
