### ISSUE TITLE
Skal familie inn som OT?

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1699]
@BioHeidi @haraldse 
Dyre- og plantenamn: Er regelen at ein skal legga inn familien i OT? Skal eg t.d. legga til Perlemorsfisker i OTen til Laksesild?

**Comment by BioHeidi** [comment]
Før: Nei. Med tanke på mulig konvertering til hierarkisk vokabular: Usikker. @danmichaelo ?

**Comment by grosyn** [comment]
Takk, Heidi, for svar som eg fekk på møtet i dag. Då brukar eg førebels kun i OT termar som allereie finst i Realfagstermer, og slenger difor ikkje på Perlemorsfisker på Laksesild.
