### ISSUE TITLE
blokkerende høytrykk?

### ISSUE THREAD

**Issue by mzyg** [realfagstermer/realfagstermer#170]
15d006620 – avhandling om ‘(..) influence of orographic and dynamic blocking on large scale atmospheric flow.
Lurer på om man burde legge til 
Blokkering eller blokkerende høytrykk EN blocks eller blocking highs  
Syns ikke at det holder med høytrykk/sykloner (som finnes som term)  og atmosfærisk sirkulasjon
@kristinran

**Comment by danmichaelo** [comment]
Jeg la den inn, jeg
