### ISSUE TITLE
Stata inn som emneord?

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1700]
@Quether 
Skal eg ta inn Stata som nytt emneord?

k22003303

**Comment by Quether** [comment]
Hadde kanskje ikke vært så dumt, men dere er nok bedre på å evaluere emneord enn meg :)

**Comment by grosyn** [comment]
Nei, det er difor eg spør fagpersonar her på GitHub :-) 
Tek inn Stata.
