### ISSUE TITLE
Paleoherpetologi - ny term?

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1701]
@edinab 
Boka Temnospondyli I i serien Handbook of paleoherpetology (k22004088) har kun Fossiler og Amfibier som emneord foreløpig. 
Skal me i tillegg oppretta Paleoherpetologi? Og kva med Temnospondyli og Tetrapoder?

**Comment by BioHeidi** [comment]
For et halvår siden ville jeg ha foreslått strengen Herpetologi : Paleozoologi ;)
Ja til temnospondyler (engelsk temnospondyls, latin Temnospondyli). Tetrapoder er jeg mer usikker på, se på mulig belegg her?

**Comment by grosyn** [comment]
No har eg tatt inn Temnospondyler, men ikkje Tetrapoder (i denne omgang).
