### ISSUE TITLE
Terrassering og Chinampa - nye emneord

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1702]
Me fekk ei bok (9780199257690) som handlar om tradisjonelt landbruk i Sør-Amerika. Her blir termane "Chinampa" https://no.wikipedia.org/wiki/Chinampa og Terrassering brukt.
Skal desse inn?

@BioHeidi @haraldse

**Comment by BioHeidi** [comment]
Ja, ta dem inn. Legg gjerne på definisjoner, og terrasse som BF på terrassering, og Jordbrukslandskap som OT på begge.
