### ISSUE TITLE
Nanoskala

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1703]
@edinab  @BioHeidi

Dette gjeld https://www.mn.uio.no/geo/forskning/aktuelt/arrangementer/disputaser/2022/geopgp/guren.html
Eg fann eit Dewey-nr som eg håpar ser bra ut: 551.302 (Erosjon og forvitring - og eg ser at Kjemisk forvitring er mappa hit).

Emneord eg har tenkt på er Kjemisk forvitring og Erosjon. Me burde vel få med at dette er i nanoskala. 
Skal me oppretta Nanoskala som ny emneterm? Blir "Nanoskala" meir brukt enn "Nanoskopisk skala"?

**Comment by BioHeidi** [comment]
Nanoskala kan opprettes (Finne deweynr...hmm)
Geologiske prosesser kan opprettes (sjekk historikk, den ble slettet en gang)

**Comment by grosyn** [comment]
@danmichaelo 
Korleis sjekkar ein historikken? Eg finn ingenting i Sonja om dette.

**Comment by danmichaelo** [comment]
Hm, jeg synes kanskje nanoskala blir et for bredt emneord. Kan vi bruke nanogeovitenskap ref. https://en.wikipedia.org/wiki/Nanogeoscience ?

DEF f.eks. "Studie av nanoskalafenomener i geologiske systemer"

SO Nanosystemer

**Comment by danmichaelo** [comment]
> @danmichaelo Korleis sjekkar ein historikken? Eg finn ingenting i Sonja om dette.

Njej, det eneste du ser i Sonja er vel at det har blitt slettet (som du ser ved at den vises med rød skrift). Noen ganger kan du finne noe om hvorfor ved å søke i GitHub:

https://github.com/realfagstermer/realfagstermer/search?q=Geologiske+prosesser&type=issues

men ikke alltid.

**Comment by edinab** [comment]
OK :-)
