### ISSUE TITLE
Ph.D. i Fysikk - "Computational study of Langmuir probe properties in ionospheric plasma"

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1705]
@danmichaelo @superLine 
Dette gjeld denne:
https://www.mn.uio.no/fysikk/english/research/news-and-events/events/disputations/2022/Kai_Morgan_Kjolerbakken

Eg foreslår å bruka emneorda Langmuir-sonder og Plasmafysikk. Skal eit emneord som Ionosfærer òg vera med? Andre?

Når det gjeld Dewey, har eg funne eit allereie bygd nr., 530.442 
Dersom det handlar mest om sjølv instrumentet, bør me kanskje heller ha 681.2?
Forfattar skriv i samandraget: "The purpose of this thesis has been to study the central properties of a Langmuir probe system, such as the distance between probes and how the system responds to changes in the bias. This will lead to better designs of Langmuir probe systems,..."

**Comment by superLine** [comment]
Hm, her trodde jeg jeg hadde kommentert - om jeg raskt skal prøve å huske: vi har pleid å bruke 621 for en del av dette.

**Comment by superLine** [comment]
621.044	Plasmateknikk
