### ISSUE TITLE
Floer-homologi, ny term?

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1706]
@TorgunnKarolineMoe 
(Dette har ingen umiddelbar hast, då avhandlinga befinn seg på VB - det er kun posten i Alma som er mangelfull.)

Det gjeld https://www.mn.uio.no/math/english/research/news-and-events/events/disputations/2022/Helle.html, som eg ikkje trur eg fekk keywords på. 
Eg lurer på om me kan bruka desse emneorda:
Overflater
Mangfoldigheter
Homologi (matematikk)
Homologisk algebra
Kanskje eg må kutta ut nokre av dei?

Og så må vel kanskje Floer-homologi inn som nytt emneord?

I Roald ligg allereie Fire-mangfoldigheter - skal me ta inn Tre-mangfoldigheter òg?

Det einaste Deweynr. eg kan foreslå her er 512.6 - og dette er kanskje heilt feil?

**Comment by grosyn** [comment]
Tusen takk!

Litt usikker på kva du meiner eg skal gjera med 3-mangfoldigheter. 
Det som ligg inne er Fire-mangfoldigheter. Skal eg laga se hit-henvisning frå Tre-mangfoldigheter, eller oppretta Tre-mangfoldigheter som ny emneterm?

**Comment by grosyn** [comment]
Eg laga forresten henvisning frå 4-mangfoldigheter no.

**Comment by TorgunnKarolineMoe** [comment]
Ny emneterm 3-mangfoldigheteter, ja! (Tallet foran sier noe om dimensjonen, og det er mye uløst og derfor mye forskning på 3 og 4-mangfoldigheter.)


Hilsen Karoline



________________________________

**Comment by grosyn** [comment]
Supert! Då blir det straks ein ny term. 
Men sidan det alt må ha blitt bestemt at oppslagstermen på 4-mangfoldigheter er Fire-mangfoldigheter, må me ha Tre-mangfoldigheter som oppslagsord på 3-mangfoldigheter. Ser forresten at Fire-mangfoldigheter blei oppretta i 2014.

**Comment by grosyn** [comment]
Lurer òg kva Dewey-nr Tre-mangfoldigheter og Fire-mangfoldigheter skal mappast til. Bare 516.07, Mangfoldigheter?

**Comment by BioHeidi** [comment]
Her bestemte vi på fellesmøte: Begge skal mappes til 516.07 (RM) og 514.34 (BM)
