### ISSUE TITLE
Skyprogrammering, tåkeprogrammering

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#1707]
Denne avhandlingen:
https://www.mn.uio.no/ifi/forskning/aktuelt/arrangementer/disputaser/2022/Lan.html

Forslag til nye termer: 
Tåkeprogrammering, evt tåkedatabehandling, tåkeberegning? BF Tåking?
Skyprogrammering, Skydatabehandling, Skyberegning? (BF Skying? neida haha)

Mulig dewey: 
004.6782 Nettskyen
eller 004.36 Distribuert databehandling

**Comment by danmichaelo** [comment]
Jeg foreslår at vi bruker den eksisterende termern `Skytjenester` fremfor å opprette `Skyprogrammering`. Denne kan gjerne få ny henvisningsterm `Skydatabehandling`, men `Skyprogrammering` og `Skyberegning` synes jeg ikke er gode termer.

Når det gjelder fog computing er det litt uklart for meg hva som skiller edge og fog computing, men edge computing er langt mer kjent, og jeg tror det går an å regne fog computing som en form for edge computing (`Edge computing BF Fog Computing`). Men det gjør det jo ikke enklere å finne en norsk term… Noen har forsøkt seg med ["Kantenheter"](https://www.google.com/search?client=firefox-b-d&q=kantenheter) og "Databehandling på kanten", men det er jo ikke akkurat supergode termer.… men kanskje `Kantdatabehandling BF Kantenheter BF Tåkedatabehandling`..?  DEF `Desentralisert databehandling i kanten av et nettverk.`? Siden det desentraliserte er det definerende her tenker jeg 004.36


@grosyn
