### ISSUE TITLE
Norsk term for Barcode medication administration (BCMA)?

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1708]
@jessiclo @BioHeidi 

Dette gjeld denne doktoravhandlinga:
https://www.mn.uio.no/farmasi/english/research/news-and-events/events/disputations/2022/mulac-alma.html

Eg lurer på kva term ein brukar på norsk for Barcode medication administration (BCMA). Dette virkar temmeleg sentralt i oppgåva, sidan den tek for seg feilmedisinering ved sjukehus, og korleis ein kan førebygga dette. 

Vidare lurer eg veldig på Dewey her. Eg finn eit nr for Medisinsk feilbehandling: 344.0411, og eit nr. for Feilbehandling ved sykehus: 344.03211. Desse ligg under Rettsvitenskap. Eg er litt frista til å bruka 615.58 for Legemiddelbehandling, som jo ligg under Farmakologi. For dette er vel Klinisk farmasi? Ein kunne kanskje ha bygd ut dette til 615.58028, @BioHeidi?

**Comment by danmichaelo** [comment]
> Det er ikke funnet en norsk oversettelse av begrepet BCMA, det er derfor valgt å oversette
begrepet til norsk for videre bruk i oppgaven. Barcode Medication Administration (BCMA) er
heretter oversatt til strekkodeassistert legemiddeladministrering (SALA).

ref. https://hdl.handle.net/11250/2682917 "Strekkodeassistert legemiddeladministrering (SALA) i sykehus : Omfang og årsaker til handlinger som avviker fra prosedyrer for legemiddelhåndtering" Kristiansen, Rune (2020)
