### ISSUE TITLE
Definisjonar på emnetermar

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1709]
@danmichaelo @BioHeidi 
Eg har sett litt på Realfagstermer i det siste, og i fleire tilfelle, manglar ein definisjon.
Finst det ein måte å få opp alle emnetermar som manglar ein definisjon?

**Comment by danmichaelo** [comment]
Hei @grosyn ,

Ikke direkte i Sonja/Roald, men du kan få ut lister fra spørretjenesten:

* [Alle begreper med definisjoner](https://data.ub.uio.no/query/#query=PREFIX+skos%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX+dct%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX+real%3A+%3Chttp%3A%2F%2Fdata.ub.uio.no%2Frealfagstermer%2F%3E%0APREFIX+ubo%3A+%3Chttp%3A%2F%2Fdata.ub.uio.no%2Fonto%23%3E%0A%0ASELECT+%3Fconcept+%3Fterm+%3Fdefinition%0AFROM+%3Chttp%3A%2F%2Fdata.ub.uio.no%2Frealfagstermer%3E%0AWHERE%0A%7B%0A++%3Fconcept+a+ubo%3ATopic+%3B%0A+++++++++++skos%3AprefLabel+%3Fterm+%3B%0A++skos%3Adefinition+%3Fdefinition+.%0A%0A%23++FILTER+EXISTS+%7B+%3Fconcept+skos%3Adefinition+%3Fdefinition+%7D%0A++FILTER(LANG(%3Fterm)+%3D+%22nb%22)%0A%7D%0AORDER+BY+ASC(%3Fterm)) (651 stk.)
* [Alle begreper uten definisjoner](https://data.ub.uio.no/query/#query=PREFIX+skos%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX+dct%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX+real%3A+%3Chttp%3A%2F%2Fdata.ub.uio.no%2Frealfagstermer%2F%3E%0APREFIX+ubo%3A+%3Chttp%3A%2F%2Fdata.ub.uio.no%2Fonto%23%3E%0A%0ASELECT+%3Fconcept+%3Fterm+%3Fdefinition%0AFROM+%3Chttp%3A%2F%2Fdata.ub.uio.no%2Frealfagstermer%3E%0AWHERE%0A%7B%0A++%3Fconcept+a+ubo%3ATopic+%3B%0A+++++++++++skos%3AprefLabel+%3Fterm+.%0A%0A++FILTER+NOT+EXISTS+%7B+%3Fconcept+skos%3Adefinition+%3Fdefinition+%7D%0A++FILTER(LANG(%3Fterm)+%3D+%22nb%22)%0A%7D%0AORDER+BY+ASC(%3Fterm)) (12 941 stk.)

> Eg har sett bittelitt på dette med arter, slekter, familier, orden. Eg trur det hadde vore fint med ein liten definisjon på termar som Abbor og Abborer. Den treng ikkje vera lenger enn "Arten abbor" under Abbor og "Slekten abbor" under Abborer. Kan eg putta på slike definisjonar når eg kjem over noko som bør forklarast for folk som ikkje kan så mykje biologi? 

Høres greit ut med slike definisjoner! Vi har tidligere gjerne brukt definisjoner av typen "Art av båndfluer", "Art i aloefamilien", "Planteslekt i gresskarfamilien" osv. Jeg synes også det fungerer å bare bruke "Art", "Slekt" osv. som definisjon hvis en vil effektivisere. Å gjenta navnet i definisjonen (som i "Arten abbor") synes jeg blir litt unødvendig.

> Og her burde det kanskje vore Se også-henvisning frå Abborer og Abbor til dei andre abbor-relaterte begrepa? Det er ein frå Abborfisker til Abbor, elles ikkje.

Gjerne det

**Comment by grosyn** [comment]
Tusen takk for listene!
