### ISSUE TITLE
brønnkomplettering EN well completion

### ISSUE THREAD

**Issue by mzyg** [realfagstermer/realfagstermer#171]
14d224618 – Bok: Advanced well completion engineering
Finnes bare petroleumsteknologi/borehullsteknologi som term. Kan vi legge til
brønnkomplettering EN well completion?

**Comment by mzyg** [comment]
@danmichaelo jeg har ingen mulighet å legge til labels. Mangler jeg rettigheter ? Kan dette fikses? Takk!

**Comment by danmichaelo** [comment]
Da må vi spørre @knuthe  :)

**Comment by bibliomari** [comment]
Er du sikker, @mzyg ? Labelsknappen ligger i øvre høyre del av skjermbilde, grå og tilsynelatende uvalgbar. Har du prøvd å klikke på den?

**Comment by bibliomari** [comment]
Lagt til.
