### ISSUE TITLE
Opium og Meskalin

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1710]
@BioHeidi @danmichaelo 

Hadde ei bok om opium, koffein og meskalin (k22008569). Me har Koffein som emneord frå før, og då reknar eg med at det ikkje er noko problem om eg legg til Opium og Meskalin som emnetermar? 
Me har Opiumsvalmue frå før. Denne boka handlar litt om dyrking av valmuen, men mest om produktet Opium, og korleis det påverkar hjernen.

**Comment by BioHeidi** [comment]
Du kan legge til Hallusinogener og Opioider, de har vi fra før og de har ikke fryktelig mange treff.
