### ISSUE TITLE
Ingeniørfag - statistikk

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1713]
Dersom ein søker på Ingeniørfag blir ein henvist til Ingeniørvitenskap. Er litt usikker på kva Ingeniørfag - statistikk er, eitt samansatt ord med bindestrek, eller ein slag streng? Eg har lyst til å sletta den. Skal den erstattast med dei to termane Ingeniørfag og Statistikk i dei 3 postane den er brukt?

No har eg sett på denne igjen, og lurer på om me skal endra den til anten Statistikk (Ingeniørfag) eller til Ingeniørstatistikk?

@danmichaelo @BioHeidi

**Comment by danmichaelo** [comment]
Beklager sent svar! Foreslår å slette strengen. Den første boka er om statistikk i finans, de to neste bio/medisin. Ingen av dem er typisk ingeniørfag. Bøkene har dessuten mer spesifikke statistikkemenord, så de trenger ikke bare "Statistikk".

**Comment by grosyn** [comment]
Takk!!
