### ISSUE TITLE
Vindkraftmodellering? Vindkraftmodeller?

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1714]
@TorgunnKarolineMoe 
Dette gjeld denne: https://www.mn.uio.no/math/english/research/news-and-events/events/disputations/2022/Puica.html

MSC gitt av forf. er 60G99 (Probability theory and stochastic processes), så 519.2 eller 519.23?

Hennar eigne keywords er: energy, wind speed, wind power, spatio-temporal, kriging
Skal Vindkraftmodellering og/eller Vindkraftmodeller inn som ny term?

**Comment by TorgunnKarolineMoe** [comment]
Tja.. Dette er jo "politisk". Enten Vindkraftmodellering eller både Vindkraft og matematisk modellering. Jeg er fornøyd uansett løsning, så det er opp til politikken fra oven!


Hilsen Karoline



________________________________
From: grosyn ***@***.***>
Sent: 22 June 2022 11:28:08
To: realfagstermer/realfagstermer
Cc: Karoline Moe; Mention
Subject: [realfagstermer/realfagstermer] Vindkraftmodellering? Vindkraftmodeller? (Issue #1714)


@TorgunnKarolineMoe<https://github.com/TorgunnKarolineMoe>
Dette gjeld denne: https://www.mn.uio.no/math/english/research/news-and-events/events/disputations/2022/Puica.html

MSC gitt av forf. er 60G99 (Probability theory and stochastic processes), så 519.2 eller 519.23?

Hennar eigne keywords er: energy, wind speed, wind power, spatio-temporal, kriging
Skal Vindkraftmodellering og/eller Vindkraftmodeller inn som ny term?

**Comment by grosyn** [comment]
Takk!
