### ISSUE TITLE
Astrogeologi og Selenologi

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1715]
@superLine @edinab 

Det gjeld den ekte strengen: "Planeter : Geologi" (som jo er på veg ut). Her har Line kommentert: "erstattes med astrogeologi" og "men vanskelig - geologi i solsystemet eller ekstrasolar geologi - her kan vi nok rydde litt. Ser noen kunne fått selenologi (opprettes evt)" Skal eg oppretta "Selenologi", og putta det på dei postane her som har med månen å gjera, eller skal me bare erstatta "Planeter : Geologi" med "Astrogeologi"? Det dreier seg ikkje om mange postar:
![image](https://user-images.githubusercontent.com/12611325/176155702-129dee8a-56d8-4fae-8a03-09e3d61eecb3.png)

**Comment by edinab** [comment]
Jeg ville si 'Astrogeologi', Selenologi blir for spesifikk.

Edina
ps: kom ikke til riktig sted i github. ?

-----Original Message-----
From: grosyn ***@***.***> 
Sent: Tuesday, June 28, 2022 12:19 PM
To: realfagstermer/realfagstermer ***@***.***>
Cc: Edina Pozer ***@***.***>; Mention ***@***.***>
Subject: [realfagstermer/realfagstermer] Astrogeologi og Selenologi (Issue #1715)

@superLine <https://github.com/superLine>  @edinab <https://github.com/edinab> 

Det gjeld den ektre strengen: "Planeter : Geologi" (som jo er på veg ut). Her har Line kommentert: "erstattes med astrogeologi" og "men vanskelig - geologi i solsystemet eller ekstrasolar geologi - her kan vi nok rydde litt. Ser noen kunne fått selenologi (opprettes evt)" Skal eg oppretta "Selenologi", og putta det på dei postane her som har med månen å gjera, eller skal me bare erstatta "Planeter : Geologi" med "Astrogeologi"? Det dreier seg ikkje om mange postar:
 <https://user-images.githubusercontent.com/12611325/176155702-129dee8a-56d8-4fae-8a03-09e3d61eecb3.png>

**Comment by grosyn** [comment]
Takk, Edina!

Det har ikkje noko å seia om du svarer på e-post eller i Git Hub :-)

**Comment by edinab** [comment]
Hei hei,
Topp, takk!

Edina :-)

-----Original Message-----
