### ISSUE TITLE
Mixed models / Linear mixed models / Hierarchical linear models / Multilevel models

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#172]
Denne termen har så mange synonymer, så det er mulig vi har den og jeg bare ikke har funnet den. Jeg har funnet belegg for termen Blandede modeller i kursmateriale fra UiO. _Flernivåmodeller_ og _hierarikiske lineæra modeller_ finner jeg også belegg for i akademiske sammenheng (den siste fra 1991), de siste to er hyppig brukt i Sverige resp. Danmark. Foreslår:

    Blandede modeller
    BF Blandede lineære modeller
    BF Hierarkiske lineære modeller 
    BF Flernivåmodeller
    EN Mixed models
    EN Multilevel models
    EN Linear mixed models
    EN Hierarchical linear models
    AK LMM

Belegg: http://ask.bibsys.no/ask/action/show?cmd=alle&pid=150282583&kid=biblio
Wikipedia: http://en.wikipedia.org/wiki/Multilevel_model

Har vi noen statistikere i redaksjonen som kan mer enn meg om det her?

**Comment by bibliomari** [comment]
Gjort
