### ISSUE TITLE
Genomisk preging

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1722]
@BioHeidi @haraldse 

Dette gjeld denne: https://www.mn.uio.no/ibv/english/research/news-and-events/events/disputations/2022/ekelenburg.html
Han skriv sjølv her: https://www.mn.uio.no/ibv/english/people/aca/yurisv/ at "For my PhD I continue to work in the field of genomic imprinting and I am working on understanding the role of genomic imprinting using both a forward and reverse genetics screen."

Skal Genomisk preging inn som ny term?

https://no.wikipedia.org/wiki/Genomisk_preging
https://snl.no/.search?query=genomisk+preging

**Comment by BioHeidi** [comment]
Ja, vi kan vel egentlig ha Genomisk preging som term. Med Epigenetikk som OT.

**Comment by grosyn** [comment]
Då er denne oppretta.
