### ISSUE TITLE
Respirasjonsorganer

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1723]
Kunne ein hatt BF Luftveiene her, eller er det ein stor skilnad på dei to termene? 
Ein bør vel i alle fall få treff på Luftveiene i Realfagstermer?

@BioHeidi

**Comment by Hypsibius** [comment]
Respirasjonsorgan dekkjer jo og gjeller?

**Comment by BioHeidi** [comment]
Ja det gjør det. Vi har både gjeller og lunger som egne emneord. Vi har ikke trakeer eller spirakler. Så hierarkisk ville vi sette OT Repirasjonsorganer med UT Gjeller, UT Lunger

**Comment by grosyn** [comment]
Har no ordna med henvisningar.
