### ISSUE TITLE
Cytokrom P450 (eit ja/nei-spørsmål)

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1724]
@BioHeidi @jessiclo 

Har ei doktoravhandling om Cytokrom P450. 
https://www.mn.uio.no/farmasi/english/research/news-and-events/events/disputations/2022/kvitne-kine-eide.html

Me har Cytokromer som emneterm frå før. Blir dette altfor vidt å bruka, slik at eg skal oppretta Cytokrom P450 som ny emneterm?

**Comment by BioHeidi** [comment]
Det holder å ha Cytokromer, men den kan godt få BF Cytokrom P450. Og CYP-enzymer. EN: Cytochrome P450, CYP enzymes, CYPs.

**Comment by grosyn** [comment]
Tusen takk! Då er dette gjort.
