### ISSUE TITLE
Programmeringsspråk

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1725]
Ser at på nokre programmeringsspråk, er (programmeringsspråk) brukt som kvalifikator, t.d. C (programmeringsspråk) og D (programmeringsspråk). Når det gjeld R, er foretrukket term Rspråk. Vil det seia at ein snakkar om Rspråk, og ikkje kun R når ein omtalar dette programmeringsspråket? 

Ser forresten at det har vore diskutert tidlegare (Dan M. og Knut) - Dan M. ville at alle skulle ha (programmeringsspråk) som kvalifikator. 

@TorgunnKarolineMoe

**Comment by BioHeidi** [comment]
Vi kaller det bare R, ikke Rspråk. For å være konsekvent kan vi sikkert ha R (programmeringsspråk) som foretrukken, men ha med Rspråk og Rstat som BF.
