### ISSUE TITLE
Matsikkerhet

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#173]
Legg til BF mattrygghet, HACCP (treng vi å skrive det heilt ut, eller held det med akronym?)
http://en.wikipedia.org/wiki/Hazard_analysis_and_critical_control_points

**Comment by Hypsibius** [comment]
EN Food safety

**Comment by BioHeidi** [comment]
Etter fire år med oppdrag fra Mattilsynet på vurdering av GMOer i Vitenskapskomiteen for mattrygghet har jeg ennå ikke hørt om HACCP! Skammelig. Men vi bruker altså ikke det begrepet. Kanskje andre faggrupper innenfor VKM bruker det.

Men alt er lagt til.
