### ISSUE TITLE
Myrkonglefamilien BF Andematfamilien?

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1736]
Basert på det som står m.a. i Wikipedia, lurer eg på om det er ok å slå saman Myrkonglefamilien med Andematfamilien:
«Andematfamilien var en plantefamilie med fem slekter. Den anerkjennes ikke lenger og alle slekter er innordnet i myrkonglefamilien.»
@BioHeidi

**Comment by BioHeidi** [comment]
Ja! Andematfamilien som BF.

**Comment by grosyn** [comment]
Gjort
