### ISSUE TITLE
Storkrepser endrast til Storkreps?

### ISSUE THREAD

**Issue by grosyn** [realfagstermer/realfagstermer#1737]
Det er valfritt å skriva Storkrepser eller Storkreps i fleirtal på bm. Etter det eg ser er det den einaste staden me har -krepser istaden for -kreps. Me har m.a. Tifotkreps og Hoppekreps (som heller ikkje er arter, etter det eg kan sjå). Er det ok at eg endrer til Storkreps + rettar opp dei 11 postane dette ligg på i almar? 

I Nynorskordboka står det Krepsar i fleirtal. På Tifotkreps, burde det stått Tifotkrepsar som første oppslagsord.

@BioHeidi

**Comment by BioHeidi** [comment]
Ja jeg synes det er bedre å si storkreps enn storkrepser. Kreps og sopp høres bedre ut i flertall enn krepser og sopper. Men nå spurte du ikke om sopper og jeg husker ikke hva vi landet på så bare ignorer det. Storkreps som flertall.
Nynorsk vet du og Hege best.
