### ISSUE TITLE
Grøntområder

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#174]
Lokar-politiet her igjen. Så at `Grøntområder` er blitt sammenslått med `Urban økologi`, jeg mener grøntområder handler om byplanleggin - parker og lignende, og urban økologi handler om økologi i byer, uavhengig av om de er grøne eller ikke. Nå var det bare et objekt som hadde grøntområder (990355632), og der passer det kanskje bedre med urban økologi, men blir ikke BF Grøntområder missvisende?

@BioHeidi @Hypsibius

**Comment by BioHeidi** [comment]
Enig. Det var meningen at BF skulle fjernes på denne, jeg har gjort en del sammenslåinger i Sonja der trefflisten har vært avgjørende (fordi det gjør det enkelt i lokar etterpå) men hvor termene ikke nødvendigvis er synonymer. Jeg pleier å huske å rydde i Sonja. Vi kan godt legge Grøntområder på Parker istedet (Parker BF Grøntområder).

**Comment by bibliomari** [comment]
Som vegvesenfrue er jeg opptatt av grøntområder som ikke har noe med parker å gjøre.... Hva med alle bøkene om grøntområder langs veianlegg, for eksempel?

**Comment by Hypsibius** [comment]
Ja, eller på bygda. Det finst heldigvis etter kvart grøntområde også der :-)

**Comment by mittinatten** [comment]
Er ikke hele bygda et grøntområde?

**Comment by Hypsibius** [comment]
Stemmer nok ikkje for Odda, Høyanger og Årdal ;-) Oppfattar ellers 'grøntområde' som planlagt og regulert, i motsetnad til kulturlandskap, som meir eller mindre er grønt 'by default'

**Comment by BioHeidi** [comment]
Har vi så mye litteratur om dette at vi må ha emneordene separat, da? Det ene dokumentet vi hadde på Grøntområder handlet om Urban økologi (og det ble lagt på som emneord), så i prinsippet burde jeg vel ha slettet emneordet Grøntområder istedet for å legge det som BF på Parker.

**Comment by danmichaelo** [comment]
Hehe, hvis Parker er én form for Grøntområder kan vi kanskje bare bytte om slik at Grøntområder blir hovedtermen? Eeeller bare slette :)

**Comment by danmichaelo** [comment]
"innslag av naturpregede arealer i byer og tettsteder", morsom definisjon: https://snl.no/gr%C3%B8nnstruktur

**Comment by BioHeidi** [comment]
heh :)

**Comment by bibliomari** [comment]
Jeg slettet Grøntområder jeg. Vi kan heller opprette det ved behov.
