### ISSUE TITLE
Hunder

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#175]
Hunder, hundehold, hunderaser, hundedressur etc. Jeg skal rydde her, hvis noen har kommentarer til det.

**Comment by bibliomari** [comment]
God fornøyelse! Jeg tenker at dette er et typisk område der det kom masse fra 691, og du kan sikkert kaste litt. Humord bruker bare Hunder (UT Førerhunder, Gjeterhunder, Trekkhunder) og Hundehold.

**Comment by Hypsibius** [comment]
Rydd gjerne. Har ikkje umiddelbart kommentarar, men kan kanskje klare å kome på noko å seie når det kjem konkrete forslag :-)

**Comment by Hypsibius** [comment]
Wafflebot?

**Comment by BioHeidi** [comment]
Hehe. Ja, det var jeg som stengte tråden etter rydding, wafflebot blandet seg inn i labellingen.

**Comment by danmichaelo** [comment]
Tenk om Wafflebot faktisk lagde vafler.. det hadde vært noe!

**Comment by Hypsibius** [comment]
Ja, har lenge vore litt misunneleg på vaffelkulturen borte hos dokke :-/
