### ISSUE TITLE
Røntgendiffraksjon

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#178]
Ønsker `Røntgendiffraksjon`, `Lavtemperatur røntgendiffraksjon`, `X-ray diffraction` og `Xrd` sydd sammen i ett begrep:

```
Røntgendiffraksjon
BF Lavtemperatur røntgendiffraksjon
EN X-ray diffraction
EN Low temperature X-ray diffraction
AK XRD
AK SXRD
SO Røntgenkrystallografi
SO Pulverdiffraksjon
```

I neste omgang burde nok forholdet mellom `Røntgendiffraksjon`, `Røntgenkrystallografi` og `Pulverdiffraksjon` vært klargjort. `Énkrystallrøntgendiffraksjon` (eller `Énkrystalldiffraksjon`) er mer eller mindre synonymt med `Røntgenkrystallografi` (eller `Énkrystallrøntgenkrystallografi`), behandles som synonymer i [RSC Chemical Methods Ontology](http://www.rsc.org/publishing/journals/prospect/ontology.asp?id=CMO:0000159&MSID=B312763J)(som jeg akkurat oppdaget). Men dette er litt mer utfordrende å rydde i, så vi kan godt la det ligge.

**Comment by danmichaelo** [comment]
Ser at vi også har `Enkrystaller` brukt på ett dokument som handler om `Énkrystallrøntgenkrystallografi`.. Kanskje vi bare skal legge inn `Énkrystallrøntgenkrystallografi` som BF på `Røntgenkrystallografi` og slette `Enkrystaller`?

**Comment by mittinatten** [comment]
Ja, jeg mener det bare finnes grunn til å skille termene åt hvis beleggen er store for de enkelte variantene. _Cryo_ blir ikke brukt for lave temperaturer i denne sammenhengen eller?

Ellers minner Énkrystallrøntgenkrystallografi litt om "MAP-kinaskinaskinaskinas" (http://en.wikipedia.org/wiki/MAP_kinase_kinase_kinase_kinase)

**Comment by danmichaelo** [comment]
:D

Nei, har ikke sett cryo.

**Comment by bibliomari** [comment]
Her var det mange lange ord!!

Det er mange treff på Røntgenkrystallografi, så det stakkars enkrystallet vil drukne der. La enkrystaller leve, sier nå jeg :)

**Comment by bibliomari** [comment]
Jeg har samlet røntgendiffraksjonen. 

Til denandre: Jeg har beholdt Enkrystaller og tenker at det kan være sånn, så får man heller kombinere på posten hvis røntgenkrystallografien gjelder enkrystaller :8ball:

**Comment by danmichaelo** [comment]
OK!
