### ISSUE TITLE
Vitenskapshistorie

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#181]
Vi har både `Vitenskapshistorie`, `Naturvitenskap : Historie`, `Vitenskap : Historie` og `Vitenskapshistorie : Historie`. Det burde holde med en eller muligens to av de (hvis en vil skille på Vitenskap og Naturvitenskap).

**Comment by bibliomari** [comment]
Jeg har slettet den siste av strengene. Å rydde opp i Naturvitenskap og Vitenskap er for stort, så da måtte vi evt bare bestemt oss for å slå dem sammen. Jeg har ikke så lyst til det siden Humord har begge to.

**Comment by mittinatten** [comment]
Det finnes sikkert gode argumenter for å skille mellom Naturvitenskap og Vitenskap. Men vel ikke mellom `Vitenskap : historie` og `Vitenskapshistorie`?

**Comment by danmichaelo** [comment]
Forhåpentligvis ikke :) Men klarer LOKAR å erstatte Vitenskap : Historie med Vitenskapshistorie  ?

**Comment by grosyn** [comment]
Strengane er sletta, men eg erstatta postane som inneheldt både Vitenskap OG Historisk framstilling (som Historie no har blitt) med Vitenskapshistorie. (52 postar blei endra.) Almar klarte det fint :-)
