### ISSUE TITLE
Strandsonen, Strandområder, Strandlinjer

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#182]
Er det ok å slå disse sammen? Tenker spesielt på Strandlinjer, har det egen geologisk betydning forskjellig fra strandsonen/strandsoner? @kristinran @mzyg

**Comment by kristinran** [comment]
jeg sitter opptatt i møte utenlands med litt dårlig nett, men veldig 
kort:

strandlinjer er klart definert geologisk begrep og kan ikke slås sammen 
med de andre emneordene. det handler ikke om strandsonen, men eldre 
strandlinjer kan ligge langt innenfor dagens strandsone og viser 
landhevningen etter istidene.

Kristin

**Comment by BioHeidi** [comment]
Takk! Men da forstår jeg det sånn at `Strandsonen` og `Strandområder` kan merges? `Strandområder` fremstår for meg som et ikke så godt emneord, men vi kan legge det til som BF.

**Comment by Hypsibius** [comment]
Kan vi også legge til eit BF strandsona? Eller, NN-term ir vel treff uansett?

**Comment by BioHeidi** [comment]
Ja hvis det står Strandsona i NN så får alle treff.

**Comment by Hypsibius** [comment]
Enn så lenge ikkje mot Oria, vel?

**Comment by bibliomari** [comment]
Gjort. Med Strandsona også som bokmål.
