### ISSUE TITLE
Fermentering / gjæringsprosesser

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#183]
Nok en lokar-observasjon :) Så at fermentering ble sammenslått med gjæringsprosesser.

Som tilhenger av surkål, kimchi, surdeig, yoghurt, ost, etc mener jeg det finnes viktige fermenteringsprosesser som enten bare involverer bakterier, eller hvor de spiller minst like viktig rolle som gjær. Jeg skulle si at gjæring er UT til fermentering. Hvis en i norsk språkbruk mener fermentering med alle mulige mikroorganismer når en sier gjæring, syns jeg det er vårt oppdrag å endre på det!

@Hypsibius @BioHeidi

**Comment by BioHeidi** [comment]
Ok, jeg handlet på ordre. Skal fiske når jeg har tid ;-)

**Comment by Hypsibius** [comment]
Drøymer eg også om. Stang, agnfiske, dorg?

:-P

**Comment by Hypsibius** [comment]
Men tilbake til det seriøse, kva om vi vi snur det på hovudet og skriv fermentering BF gjæring?

**Comment by mittinatten** [comment]
Ja, det er i hvert fall logisk :)

**Comment by Hypsibius** [comment]
Altså, logisk er det jo også at gjæring er UT til fermentering. Spørsmålet er om det er unødvendig detaljert.

**Comment by BioHeidi** [comment]
Snudde på foretrukken og BF. Så får vi evt splitte opp trefflisten hvis det er behov for det.

**Comment by danmichaelo** [comment]
Oppfatter det som at det ikke er kritisk at vi splitter trefflisten? Da kan vi vel lukke denne, og heller evt. ta opp tråden ved senere anl.?
