### ISSUE TITLE
Fiskeforvaltning

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#184]
Hei! Ved dagens klassing oppdaga eg at vi hadde både fiskeforvaltning og fiskeriforvaltning. Det burde eg sikkert ha oppdaga og meldt inn før (eller har eg det?) sidan det fall inn i mitt spenn... Men: vi treng vel ikkje begge? Tenkjer at fiskeforvaltning også omfattar forvaltning i hht  sportsfiske, habitatsendringar etc... Kva med Fiskeforvaltning bf fiskeriforvaltning?

**Comment by BioHeidi** [comment]
Det er en liten forskjell der, men det gjenspeiles ikke helt i trefflistene. `Fiskeforvaltning` omfatter i tillegg til det du presiserer også bestandsforvaltning av ufiskbare fiskearter, mer i retning bevaringsøkologi og biodiversitet (altså "fisker"), mens `Fiskeriforvaltning` kun omfatter "fiske", ikke "fisker". Det hadde blitt tydeligere om `Fiskeforvaltning` kunne hete `Fiskforvaltning`, men den går nok ikke igjennom sensuren ;-)
Forslag til bedre termer som gjenspeiler forskjellen på fisker og fiske?
Evt, blir det for spesifikt til at det er noe poeng å skille de to?

**Comment by Hypsibius** [comment]
Har vi då bestemt oss?

**Comment by danmichaelo** [comment]
Hm... så `Fiskeriforvaltning` ~ `Fisheries management`, mens `Fiskeforvaltning` ~ `Fish conservation` ? Fiskebestandsforvaltning?? Fiskebevaring?  Nei, jeg vet ikke, kanskje de bare skal være som de er..? (gjerne med definisjon)

**Comment by Hypsibius** [comment]
Vil nok gjerne samle, det er vel mogeleg å legg inn også to engelske termar? Alternativt er fiskeforvaltning ein term som også omfattar fiskeriforvaltning. ...

**Comment by danmichaelo** [comment]
Joa, det er mulig, jeg ble bare litt i tvil om dette var to fagfelt som sto så langt fra hverandre at de som er interessert i bøker om det ene kanskje ikke var interessert i bøker om det andre. Men det er ikke sikkert det altså! @BioHeidi får ta en avgjørelse :)

**Comment by Hypsibius** [comment]
Er nok eit ganske greitt overlapp, og sjølv om enkelte forskarar forsøker å late som ingenting, må dei nok til ei viss grad forhalde seg til kvarandre sin litteratur ;-)

**Comment by BioHeidi** [comment]
Som Hege sier (beklager treghet fra min side). Vi slår de sammen, gjerne med to engelske termer for å understreke at vi både snakker om conservation og management.

**Comment by BioHeidi** [comment]
Og @bibliomari , her står det rydding fordi jeg tenkte å rydde i trefflistene før sammenslåing. Men om du blir utålmodig så bare gjør Sonja-magi.

**Comment by grosyn** [comment]
Har nokon sett på Humords behandling av desse termane? Dei bruker ingen av termane, og henviser frå Fiskeriforvaltning til Fiske, som kan kombinerast med Offentlig forvaltning t.d. Eg veit ikkje om dette er betre enn slik de tenker, men eg kan evt ta det opp med Vibeke?

**Comment by BioHeidi** [comment]
Fiske : Offentlig forvaltning vil begrense seg til Fiskeriforvatltning og ikke ta hensyn til Fiskeforvaltning. Så om vi slo disse sammen  den gang i hine hårde så må vi dele de opp igjen først.

**Comment by Hypsibius** [comment]
@grosyn Realfagtermar bør nok vere komplementære til HUMORD. Tenker det at humord ikkje skiller her er fordi fiskeforvaltning og fiskeriforvaltning akademisk sett fell under realfaga og jus. Humord har neppe behov for same distnksjonar. Mortalitetsmodellar, bestandsmodellar og bestandsdata som inngår ligg generelt under klassisk hav- og ferskvasssforsking. 

Er litt usikker på om @BioHeidi har rett i at kun fiskeriforvaltningkan definierast som offentleg forvantning. Derimot skjer forvaltning og kvotetildeling på departementalt nivå, medan det meste som gjeld overvåking av vatn og vassdrag sker regionsvis, delegert gjennom statsfrvaltar. Tekninsk sett er vel begge deler under offentleg   & statleg forvalting 

Ei litt meir praktisk tilnærming vil vere å tenke på kva folk vil komme på å søke etter, eller sagt med andre ord: Om du er på jakt etter dokument om fiskeriforvaltning, kjem du då på at du skal søke etter offentleg forvaltning?

**Comment by BioHeidi** [comment]
"Fiske" er vel den begrensende faktoren her, siden den ikke inkluderer "Fisk". Men ja, ser hva du mener!

**Comment by grosyn** [comment]
Usikker på kva konklusjonen blei her.
Grunnen til at eg syner til Humord, er at eg har inntrykk av at Realfagstermer truleg vil gå inn i Humord på eit eller anna tidspunkt i framtida. Det er ikkje blitt bestemt enno, men eg er redd det vil koma.

**Comment by Hypsibius** [comment]
Reint bortsett frå at det da gjerne ikkje bør heite Humord ;-) Men altså rasjonalisering og samordning viktig, og så er det viktig at ulike deler av vokabulara blir vedlikehalde av dei som til ei kvar tid har kompetanse og behov! 
A propos det, har de nokon kommunikasjon med våre spesialsamlingar og termbasane der? Eg forsøkte før ferien å be nytilsett terminolog (terminator?) kontakte meg angåande Realfagstermar.

**Comment by grosyn** [comment]
Fiskeriforvaltning ligg no i Humord, så eg slår no Fiskeforvaltning saman med denne. (Fiskeressursar har jo òg på eit eller anna tidspunkt blitt slått saman med Fiskeriressursar.)
