### ISSUE TITLE
Normalmodus / egensvinging / modalanalyse

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#185]
Vet ikke om vi trenger en eller to termer her men foreslår

    Egensvinginger
    NN Eigensvinginger
    EN Normal modes
    BF Normalmodi (-moder?, -modus?)
    BF Normalsvinginger
    SO Modalanalyse

og

    Modalanalyse
    EN Modal analysis
    SO Egensvinginger

Muligens kunne vi slått de sammen under Modalanalyse. Hva mener du @danmichaelo ?

UiB har hatt flere doktorgrader på temaet, den siste har objektid 150435452.

**Comment by mittinatten** [comment]
En relatert term til er relevant for forskningen ved UiB

    Elastiske nettverk
    BF Elastiske nettverksmodeller
    EN Elastic network models

**Comment by bibliomari** [comment]
Har lagt til alle tre.
