### ISSUE TITLE
Orientering/Navigering

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#186]
Vi har Orientering og Orienteringsevne, ser ut til å være brukt likt, om dyr/fugler. Kan vi legge til noe for å beskrive dette emnet bedre - og bør det holdes unna Navigering (som også bl.a. er brukt om dyr)

@Hypsibius @BioHeidi

**Comment by Hypsibius** [comment]
Hm. Tenketenke. Eit skille mellom orienteringsevne og navigering (for dyr) blir på sett og vis forskjellen mellom å vite kvar ein er og å bruke den kunnskapen til å kome seg ein annan stad. Vil tru at den eine hos dyr føreset den andre, og at det er meiningslaust å forsøke å skilje dei (jf flo/fjøre). 

Saman med dette må vi sjå begrep som magnetsans https://snl.no/sanseorganer_hos_dyr#menuitem5, kjemisk sans (gradient brukast ofte til orientering) etc., synssans og electroreception (kva kallar vi det på norsk?). Andre relevante begrep som kunne vore BF-termar er homing, nokon som har eit godt norsk namn på det?

**Comment by BioHeidi** [comment]
Homing synes jeg vi har diskutert et sted før? På e-post kanskje?
Jeg synes det blir kunstig med et skille mellom evnen og å bruke den, så jeg synes vi kan slå sammen orientering/orienteringsevne/navigering. Men vi kan godt ha egne emneord for de fysiologiske strukturene i form av sanseorganene.

**Comment by Hypsibius** [comment]
Einig!

**Comment by bibliomari** [comment]
Diskutert med @BioHeidi , enige om å beholde skillet mellom Navigering og Orientering, og legge til bruksnote (eller definisjon, men den må formuleres mer omtenksomt) om at Navigering skal brukes om det tekniske aspektet, mens Orientering brukes om den medfødte evnen/orienteringsevne uten bruk av tekniske hjelpemidler.

**Comment by Hypsibius** [comment]
OK!
