### ISSUE TITLE
Spor, sportegn, dyrespor

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#187]
Foreslår `Sportegn` BF Dyrespor, Spor
Vi har også `Biologiske spor`, som er brukt på ett dokument (forensic science), har noen forslag om andre emneord som kan ha blitt brukt her?
Så har vi `Sporanalyser`, som beskriver analyse av sporelementer, og `Spordannelse`, som jeg ikke vet hva er (ser ut som det er brukt innenfor molekylærbiologi på noen av våre dokumenter).

**(**Og jeg leker med *Markdown***)**

**Comment by mittinatten** [comment]
`Spordannelse` kanskje skal være `Sporedannelse`? https://snl.no/spore%2Fbotanikk

**Comment by BioHeidi** [comment]
Hm ja jeg tenkte på det men syntes ikke det passet. Men mulig det er det likevel og at det bare er dårlig emneordssatt.

**Comment by Hypsibius** [comment]
Hei! Eit kjapt søk i realfagstermar tydar på at dette er danning av hjulspor i asfalt/anna vegdekke så denne trur eg vi må halde heilt unna resten :-D

**Comment by Hypsibius** [comment]
Dene er vel arv frå NTNU, ikkje noko som studerast mykje hos oss, vaffal!

**Comment by BioHeidi** [comment]
Ja ser det, når jeg ikke bare søker på Ureal! Men de tre treffene hos oss forvirret meg.

**Comment by BioHeidi** [comment]
Tenker vi kan gjøre om `Biologiske spor` til `Kriminalteknikk` som vi har fra før. Og så lar vi `Spordannelse` og `Sporelementer` stå. Og ellers som jeg foreslo i første post.

**Comment by Hypsibius** [comment]
Tiltredes!

**Comment by bibliomari** [comment]
Gjort
