### ISSUE TITLE
Svikt i synonymkontrollen

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#188]
Da jeg skulle slå opp termene fra bibkodelisten fikk jeg mer enn ett treff på noen av termene. Her er hele listen med avkrysningsbokser hvis noen synes det er greit å kunne krysse av etterhvert som en går gjennom – helt frivillig vel og merke!

(Høyttenkning: Det kan tenkes at det finnes tilfeller der det faktisk er hensiktsmessig å ha like altLabler på forskjellige begreper. Men det bør nok holdes på et minimum siden de vil bli blandet sammen i et emnesøk som ikke støtter disambiguering, som Oria... I vårt eget emnesøk burde det ikke ha noen betydning så vidt jeg klarer å se.)

- [x] Øret (nb)
 - prefLabel, http://data.ub.uio.no/realfagstermer/c004485)
 - prefLabel, http://data.ub.uio.no/realfagstermer/c004486)

- [x] Salmo salar (la)
 - prefLabel, http://data.ub.uio.no/realfagstermer/c012698)
 - prefLabel, http://data.ub.uio.no/realfagstermer/c012700)

- [x] Ras (nb)
 - altLabel, http://data.ub.uio.no/realfagstermer/c002936)
 - altLabel, http://data.ub.uio.no/realfagstermer/c013619)
   - Forslag: "Ras" fjernes fra "Grafiske filformater" siden det er et ganske obskurt filformat, mens "Ras" i betydningen "Skred" er et viktig oppslagsord.

- [x] Datanettverk (nb)
 - altLabel, http://data.ub.uio.no/realfagstermer/c009975)
 - prefLabel, http://data.ub.uio.no/realfagstermer/c007470)

- [X] Måleteknikk (nb), se #239
 - altLabel, http://data.ub.uio.no/realfagstermer/c012656)
 - altLabel, http://data.ub.uio.no/realfagstermer/c013918)

- [x] Datanett (nb)
 - prefLabel, http://data.ub.uio.no/realfagstermer/c009980)
 - altLabel, http://data.ub.uio.no/realfagstermer/c009975)

- [x] Selvorganisering (nb)
 - prefLabel, http://data.ub.uio.no/realfagstermer/c008553)
 - altLabel, http://data.ub.uio.no/realfagstermer/c011088)

- [x] Bruddstyrke (nb)
 - prefLabel, http://data.ub.uio.no/realfagstermer/c009879)
 - altLabel, http://data.ub.uio.no/realfagstermer/c011579)

- [x] Nettsky (nb)
 - altLabel, http://data.ub.uio.no/realfagstermer/c013934)
 - altLabel, http://data.ub.uio.no/realfagstermer/c003034)

- [x] Nettverksarkitektur (nb)
 - prefLabel, http://data.ub.uio.no/realfagstermer/c004289)
 - altLabel, http://data.ub.uio.no/realfagstermer/c001205)

- [x] Medikamenter (nb), se #241
 - altLabel, http://data.ub.uio.no/realfagstermer/c013959)
 - altLabel, http://data.ub.uio.no/realfagstermer/c010646)

- [x] Søkemotorer (nb)
 - altLabel, http://data.ub.uio.no/realfagstermer/c006519)
 - prefLabel, http://data.ub.uio.no/realfagstermer/c005425)

- [x] Komplekser (nb)
 - prefLabel, http://data.ub.uio.no/realfagstermer/c002800)
 - altLabel, http://data.ub.uio.no/realfagstermer/c011497)

- [x] Problemløsning (nb)
 - prefLabel, http://data.ub.uio.no/realfagstermer/c007145)
 - altLabel, http://data.ub.uio.no/realfagstermer/c008443)

- [x] Forretningsvirksomhet (nb)
 - altLabel, http://data.ub.uio.no/realfagstermer/c004305)
 - altLabel, http://data.ub.uio.no/realfagstermer/c001933)

- [x] Havområder (nb)
 - prefLabel, http://data.ub.uio.no/realfagstermer/c004991)
 - altLabel, http://data.ub.uio.no/realfagstermer/c000761)

- [x] Facebook (nb)
 - altLabel, http://data.ub.uio.no/realfagstermer/c014025)
 - altLabel, http://data.ub.uio.no/realfagstermer/c005692)

- [x] Fluider (nb)
 - prefLabel, http://data.ub.uio.no/realfagstermer/c006884)
 - altLabel, http://data.ub.uio.no/realfagstermer/c003650)

- [x] Ramaneffekt (nb)
 - prefLabel, http://data.ub.uio.no/realfagstermer/c013013)
 - altLabel, http://data.ub.uio.no/realfagstermer/c013016)

- [x] Genmodifisert mat (nb)
 - altLabel, http://data.ub.uio.no/realfagstermer/c013721)
 - altLabel, http://data.ub.uio.no/realfagstermer/c013720)

- [x] Typer (nb)
 - prefLabel, http://data.ub.uio.no/realfagstermer/c004896)
 - altLabel, http://data.ub.uio.no/realfagstermer/c006954)

**Comment by mittinatten** [comment]
Mine kommentarer på de som faller under mine fag. I nesten alle tilfeller virker det som dubbleringen ikke er nødvendig

* Det er logisk å ha `Typer` som "synonym" til `Typeteori` (men kanskje ikke nødvendig). Å bruke termen typer for for eksempel fugletyper virker lite nødvendig (som i noen av treffene, burde finnes bedre emneord der), hvis det dreier seg om typografi burde det holde med `typografi`.
* `Ramaneffekt` og `Ramanspredning` kan slås sammen
* For nettverkene foreslår jeg å beholde Nettverk, slette de andre to, og legge til SO til `Nettverksteori`, jeg tenker at når en mener nettverk som ikke er datanett, er nettverksteori en god term (muligens trenger vi en definisjon):

    Nettverk
    BF Datanettverk
    BF Datanet
    EN Networks
    EN Computer networks
    SO Nettverksteori

* `Selvorganisering` har vært oppe: #53 (slå de sammen)
* `Skysystemer` kan sikker slås sammen med `Distribuerte systemer`
* `Nettverksarkitektur` og `Nettverksdesign` kan slås sammen?
* Burde `Facebook` virkelig være nevnt under `Nettsamfunn`? Den delen av begrepet nettsamfunn som omfatter Facebook dekkes vel av termen `Sosiale medier`. Usikkert om vi trenger nettsamfunn i det hele tatt?

**Comment by Hypsibius** [comment]
Ooops, inkompetansenivå-alert! Her heng eg ikkje heilt med i svingane. Eg forstår ikkje så mykje av tabellane du viser til, og er litt uviss på kva som er tenkt med avkryssinga: Kryssar eg av for eigen del? Eller for å vise dei som har tilgang til Sonja kva for termar eg synest det er greitt å berre slå saman? Eller skal eg opprette saker for kvart punkt for oppfølging frå @bibliomari og @BioHeidi ?

Kva *typer* og biologi angår, har dette ein ganske spesifikk betydning her: Når ein ny art beskrivast, skal eit eksemplar konserverast og gjerast tilgjengeleg for etterprøving. Dette eksemplaret som artsbeskrivelsen er basert på, kallast 'typen'. I dette tilfellet tenkjer eg det er mest korrekt å skilje det ut som 'typer (biologi)' http://no.wikipedia.org/wiki/Artsbeskrivelse

**Comment by danmichaelo** [comment]
No worries, det er bare å spørre når jeg glemmer å forklare ting jeg burde forklart ;)

Avkryssingen er ikke personlig, når noen krysser av vises det for alle. Så ideen min var at vi kunne diskutere (alt som trenger å diskuteres) i denne tråden, og at @bibliomari eller @BioHeidi kunne krysse av hvert tilfelle som de anså som ferdigbehandlet (fikset i Sonja, eller evt. bestemt oss for at vi ikke skal fikse)

**Comment by knuthe** [comment]
Den fila (Sonja.txt) under nynorskprosjektet ser jo greit ut å 
importere. Hvordan tenker du deg rutinene rundt dette her? Og hvordan 
aksesserer jeg evt fila?

Har du forresten en adresse til nynorskverktøyet?

Knut

Den 06.03.15 15:02, skrev Dan Michael O. Heggø:
>
> No worries, det er bare å spørre når jeg glemmer å forklare ting jeg 
> burde forklart ;)
>
> Avkryssingen er ikke personlig, når noen krysser av vises det for 
> alle. Så ideen min var at vi kunne diskutere (alt som trenger å 
> diskuteres) i denne tråden, og at @bibliomari 
> <https://github.com/bibliomari> eller @BioHeidi 
> <https://github.com/BioHeidi> kunne krysse av hvert tilfelle som de 
> anså som ferdigbehandlet (fikset i Sonja, eller evt. bestemt oss for 
> at vi ikke skal fikse)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/realfagstermer/realfagstermer/issues/188#issuecomment-77562608>.
>

-- 
Førstebibliotekar / Senior academic librarian
Science library, informatics dept.
Box 1128 Blindern
0316 Oslo
Norway

**Comment by bibliomari** [comment]
Det er noe rart med Øret, @knuthe: Jeg får allslags rare beskjeder fra Sonja når jeg prøver å a) slå sammen Øret og Øret eller b)prøver å slette Øret. Tror kanskje du må fikse fra innsiden?

**Comment by bibliomari** [comment]
Medikamenter trenger jeg et eget seminar om... Der er det så utrolig mye i bruk (medisiner, legemidler +++).

Typer: Kan @BioHeidi bygge ut termen så betydningen som @Hypsibius forklarer, framgår? Jeg har slettet Typer fra Typeteori (kan komme tilbake igjen hvis det blir ramaskrik...)

**Comment by Hypsibius** [comment]
Ellers ingen innvendingar til samanslåing av termar innan mine felt

**Comment by knuthe** [comment]
Var det ikke slik at vi kunne ha samme BF under flere termer?

Ellers syns jeg vi skulle beholde både "skysystemer" og "distribuerte systemer".

**Comment by danmichaelo** [comment]
> Var det ikke slik at vi kunne ha samme BF under flere termer?

Jeg tror kanskje det. Hvis man søker på "Medikamenter" er det jo ikke noe i veien for at man kan få resultater fra "Medisiner" OG "Legemidler" (eller muligheten til å velge hvis grensesnittet tillater det). Men en BF bør ihvertfall ikke også være en foretrukken term.

**Comment by bibliomari** [comment]
Jeg har fjernet "nettsky" som BF til Distribuerte systemer, og laget Se også mellom Distribuerte systemer og Skysystemer.

**Comment by knuthe** [comment]
Når det gjelder "øret". Opphavet til denne feilen (og kanskje andre i denne tråden) er at Sonja mangler en kontroll når man bytter prefLabel/altLabel. Sonja sjekker ikke om den nye prefLabel fins fra før. Jeg legger meg flat i programmeringspositur.

**Comment by BioHeidi** [comment]
Jeg slo under tvil sammen `Atlanterhavslaks` og `Villaks`. Tenker at vi heller fremover må bli flinkere til å bruke `Oppdrettslaks` der det er snakk om det.

**Comment by knuthe** [comment]
Ny versjon av Sonja er lagt ut til bruk. Sjekk versjonsloggen (under hjelp-menyen) for å se at du har riktig versjon (dvs henter programmet fra riktig sted).

**Comment by danmichaelo** [comment]
@knuthe Kan du også se på om det er noen av "dine" som kan slås sammen i listen øverst? Trenger vi f.eks. både "Datanettverk" og "Datanett"?

**Comment by knuthe** [comment]
<data>nett<verk> . jeg har begynt å se på det. Ureal har brukt "datanett" 60 ganger og "datanettverk" 9. Jeg går for korteste variant om ingen protesterer. 

Når det gjelder "nettverk", så er det verre. 240 treff his ureal. Den har både "datanett og datanettverk som BF!!!) I tillegg er den brukt i forbindelse med grafteori, sosiale nettverk etc). Første iterasjon på den må være å fjerne BF-ene. Så må trefflista gås gjennom for hånd for å skille mellom datanett og nettverk.

Nettverksarkitektur og nettverksdesign. Kan slås sammen.

**Comment by knuthe** [comment]
Jeg har gått ikke gått gjennom de 240 ennå, men resten av "mine" skulle være fikset nå.

**Comment by danmichaelo** [comment]
Flott! Men mener du at vi skal ha både "Søkemaskiner" og "Søkemotorer"? Hva er forskjellen mellom disse?

**Comment by knuthe** [comment]
Beklager, overså den. Fikset.

**Comment by danmichaelo** [comment]
:+1: Da lukker jeg denne saken. Det som gjenstår er skilt ut som egne saker
