### ISSUE TITLE
Löwnerligningen

### ISSUE THREAD

**Issue by totlevase** [realfagstermer/realfagstermer#195]
Kan du byta plass på nynorskformene, slik at den alternative forma vert føretrekt, og den føretrekte forma vert alternativ? =)

--
URI: http://data.ub.uio.no/realfagstermer/c031231
Bruk: https://katapi.biblionaut.net/documents?q=real:Löwnerligningen

**Comment by danmichaelo** [comment]
Ja, det er vel ikke noen grunn til at ikke Löwnerligningen kan være foretrukken form på nynorsk også? Lurer på om det bare henger igjen fordi vi byttet om på hvilken som var foretrukken på bokmål #46
