### ISSUE TITLE
Abyssal bentos

### ISSUE THREAD

**Issue by jorgenem** [realfagstermer/realfagstermer#196]
Hovudforma på bokmål skulle kanskje vore på engelsk?

--
URI: http://data.ub.uio.no/realfagstermer/c013885
Bruk: https://katapi.biblionaut.net/documents?q=real:Abyssal bentos

**Comment by Hypsibius** [comment]
Nei, på engelsk skal det vere *abyssal benhtos* med h. Om ikkje @BioHeidi er veldig usamd, tenkjer eg det greiaste er å bruke dyphavsbenthos som hovudinnførsel. NN djuphavsbenthos BF bathyal bentos, abyssal bentos, hadal bentos.
http://en.wikipedia.org/wiki/Benthic_zone#Habitats

**Comment by BioHeidi** [comment]
Eg er einig, her er det du som er eksperten! (På engelsk: Ben*th*os)
