### ISSUE TITLE
Nordsjøen

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#198]
Kan det verkeleg stemme at *Nordsjøen* manglar som term her? Har eg gjort noke hakkande gale når eg har søkt? Foreslår evt  lagt til Nordsjøen NN Nordsjøen EN North Sea

https://bora.uib.no/handle/1956/6585

**Comment by bibliomari** [comment]
Nordsjøen er en stedterm, @Hypsibius . Jeg legger til alternativformene dine.

**Comment by Hypsibius** [comment]
Duh! *rødme*
