### ISSUE TITLE
REAL000001

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#2]
Hva skal vi bruke denne spesielle identifikatoren til? I #1 foreslo jeg "Universet" som én mulighet, inspirert av Wikidatas [Q1](http://wikidata.org/wiki/Q1). @BioHeidi  foreslo "Realfagstermer". Andre morsomme ideer?

**Comment by bibliomari** [comment]
Hah, så morsomme vi er! Men konkluderte vi noensinne?

**Comment by knuthe** [comment]
Foreslår "Ctrl-alt-delete".

**Comment by danmichaelo** [comment]
Tror vi konkluderer med at vi ikke klarte å konkludere :D

**Comment by BioHeidi** [comment]
Neeeiiiii
