### ISSUE TITLE
Atomenergi / Kjernekraft

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#203]
Foreslår `Kjernekraft BF Atomenergi`

**Comment by danmichaelo** [comment]
Tror jeg er enig i at de ikke trenger å skilles i litteraturøyemed :)

**Comment by mittinatten** [comment]
Så det finnes en forskjell?

**Comment by danmichaelo** [comment]
Godt spørsmål, nei, jeg tenkte bare på at kraft og energi jo ikke er det samme (gode, gamle *E = PT*), men det er vel egentlig ikke interessant her

**Comment by mittinatten** [comment]
Og jeg lurte om det var forskjell i hvorvidt fisjon/fusjon er inkludert i den ene, men man inkluderer kanskje ikke fusjon i noen av de, vanligvis.

**Comment by danmichaelo** [comment]
Hehe, ja, det var også noe... nei, antakelig ikke

**Comment by bibliomari** [comment]
Gjort.
