### ISSUE TITLE
Fukushima

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#204]
Siden jeg så at vi har `Reaktorulykker : Tsjernobyl` foreslår jeg også `Reaktorulykker : Fukushima` (Stedet `Fukushima` må legges til)

Belegg: http://ask.bibsys.no/ask/action/show?pid=140622462&kid=biblio
http://ask.bibsys.no/ask/action/show?kid=biblio&pid=150579780

**Comment by danmichaelo** [comment]
Her synes jeg det er litt unødvendig med strenger.. Hva med `Fukushima-ulykken`? Og omdøpe den andre til `Tsjernobyl-ulykken`? Med overordnet (forekomst-av) `Reaktorulykker`

(Humord opprettet forresten [Fukushimaulykken 2011](http://li148-205.members.linode.com/humord/nb/page/c27808) den 2015-01-26 :))

**Comment by mittinatten** [comment]
Har ingen sterke meninger om stedsstreng vs term her. Regner med vi må gjøre manuell oppdatering hvis vi går fra sted-streng til term (siden stedet ikke ligger i $b), men det er sikkert ikke så mange treff, så det går sikker fort.

Det er altså et tema i tiden :)

**Comment by danmichaelo** [comment]
Jupp, jeg kan egentlig også nyttiggjøre meg emneordet når jeg skal klassifisere [denne](http://ask.bibsys.no/ask/action/show?pid=143525824&kid=biblio) :)

**Comment by knuthe** [comment]
Ja, når vi først snakker om kjernekraftulykker, syns jeg denne må med:

https://www.youtube.com/watch?v=FjuhW-4tyEI

**Comment by Hypsibius** [comment]
Venta på den , ja :-P

**Comment by mittinatten** [comment]
:D

Takk for boktips @danmichaelo, bestilte den og.

**Comment by danmichaelo** [comment]
Nå har jeg opprettet `Fukushima-ulykken`, men Mari må nok lokare (fint verb i grunnen) `Tsjernobyl` til `Tsjernobyl-ulykken` før vi kan lukke saken :)

**Comment by bibliomari** [comment]
Lokarere, du liksom - manuell flytting fra sted til term, det er det jeg må. Og det skal jeg gjøre nuh før lunsj.
