### ISSUE TITLE
Min ryddeliste del I

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#205]
Puh

* [x] `Dotcom`: slette (intet litteraturbelegg, lite trolig at det kommer)
* [x] `År2000-problemet`: omdøpe til `År 2000-problemet`
* [x] `A programming language`: omdøpe til `APL`? @knuthe  (APL har jeg faktisk hørt om, men visste ikke hva det sto for)
* [x] `Abnormaliteter` : hm, er dette det samme som `Misdannelser`? Se også #149
* [x] `Abstract window tools - java` : slette
* [x] `Abundans` : har [flere betydninger](https://en.wikipedia.org/wiki/Abundance). Brukt på [ett dok.](http://ask.bibsys.no/ask/action/result?cql=%28bs.lokoeo-frase+%3D+%22Abundans%22%29++AND+%28bs.avdeling+%3D+%22ureal?%22%29&aktivKilde=biblio%3AUBO) -- klargjøre med definisjon eller slette?
* [x] `Acidofile bakterier` : Intet litteraturbelegg -- slette?
* [x] `Acridine orange` : brukt på [én masteroppgave](http://ask.bibsys.no/ask/action/show?pid=031571352&kid=biblio) som har mange andre relevante emneord. Trenger vi denne? Vi kan vel ikke ha emneord for hver eneste lille forbindelse?
* [x] `Active Cavity Radiometer Irradiance Monitor`, `Advanced Composition Explorer`, `Advanced Satellite for Cosmology and Astrophysics` og `Advanced Solar Observatory` : satelitter -- omtalt korporasjon? eller..?
* [x] `Active galactic nuclei` og `Aktive galaktiske kjerner` -> `Aktive galaksekjerner` @superLine ? 
* [x] `Skadelige planter` : Skadelig for... oss? Dekkes [denne](http://ask.bibsys.no/ask/action/result?cql=%28bs.lokoeo-frase+%3D+%22Skadelige+planter%22%29++AND+%28bs.avdeling+%3D+%22ureal?%22%29&aktivKilde=biblio%3AUBO) av `Giftige planter` kanskje`? @BioHeidi
* [x] `Skadelige stoffer` -> `Helsefarlige stoffer` ?
* [x] `Adhd` -> `ADHD`
* [x] `Adp-ribosyltransferase` -> `ADP-ribosyltransferaser` (stemmer at det skal være fl.tall? @BioHeidi) 
* [x] Stjerneklasser: `Ae-type`, `B-type`, `Be-type spektra`, `F-type`, `G-type`, `K-type`, `O-type` og `Ob-stjerner`: vi bør vel ha disse på samme form? Hvilken er best, @superLine ? `Ae-stjerner`, `B-stjerner` osv. (ála [Astrotesaurusen](http://www.altbibl.io/astrothesaurus/uat/termrecords/A+stars.html)) eller `Ae-type`, `B-type`...? Og stor 'B' i `OB-stjerner`?
* `Aggresjon` og `Aggresivitet` : slå sammen?
* [x] `Air Force Cambridge Research Laboratories` : ingen katalogtreff.. Derimot en del treff på [AFCRL](http://ask.bibsys.no/ask/action/result?cmd=&kilde=biblio&q=afcrl).. men dette er egentlig en korporasjon, eller hva?
* [x] `Airglow` -> `Natthimmellys` (nå har jeg akkurat flyttet den på bokmålswikipedia også :))
* [x] `Aix` -> `AIX`... men [ser ikke ut til](http://ask.bibsys.no/ask/action/result?cmd=&kilde=biblio&cql=bs.lokoeo-frase+%3D+%22Aix%22&feltselect=bs.lokoeo-frase) at vi har litteraturdekning (lenger?) Skal vi bare slette den da? @knuthe
* [x] `Akselerasjon` : Blir fort litt hummer&kanari -- [disse](http://ask.bibsys.no/ask/action/result?cql=%28bs.lokoeo-frase+%3D+%22Akselerasjon%22%29++AND+%28bs.avdeling+%3D+%22ureal?%22%29&aktivKilde=biblio%3AUBO) dokumentene har jo ikke noe særlig til felles. Slette? @mittinatten
* [x] `Akseptor` : fl.tall. Men jeg er også usikker på om vi trenger denne som egen term. Brukt på [én masteroppgave](http://ask.bibsys.no/ask/action/show?pid=012145327&kid=biblio). Jeg la den inn som underordnet `Dopelementer` nå, men ser at vi ikke har "Donorer" som egen term, den andre typen av disse.. @mittinatten
* [x] `Aktive nebulae` : slettes, brukt på [én bok](http://ask.bibsys.no/ask/action/show?pid=890058806&kid=biblio), ser ut til å være en miks av to termer. Enig, @superLine ?
* [x] `Aktive områder` : er dette begrenset til stjerner, @superLine ? Kanskje vi kan legge på en "definisjon"/forklaring
* [x] `Aktiviteter` : er ikke det litt vagt?
* [x] `Solflekkaktiviteten` : holder det ikke med `Solflekk` + `Solaktivitet` ?
* [x] `Akvareller` : øhm, vi har ikke noe litteratur om dette :)
* [x] `Akvariedekorasjon` : her derimot *hadde* vi én bok, men den er tapt.
* [x] `Akvariefisker` :tropical_fish: og `Akvarieplanter` : Trenger vi denne spesifisiteten, eller kan de inn som BF på `Akvarier`?
* [x] `Alder`: Er dette interessant som emneord? (Vi har også `Aldersbestemmelse`, `Aldring` m.fl.) @BioHeidi @Hypsibius
* [x] `Alfastråling` inn som BF på `Alfapartikler`.
* [x] `Algebraisk k-teori` -> `Algebraisk K-teori` (stor K)
* [x] `Algebraiske jacobi-funksjoner` : stor J.. eller slette. Både `Jacobi-funksjoner` og `Algebraiske jacobi-funksjoner` er begge brukt én gang, på samme dokument. Da burde vi ikke trenge begge.
* [x] `Alginat` og `Alginater` : Trenger vi begge` @BioHeidi @Hypsibius ?
* [x] `Allisi-type strukturer` : Det tok litt tid før jeg skjønte at dette var `AlLiSi`-type krystallstruktur :) men jeg synes egentlig ikke vi kan ha alle mulig type krystallstrukturer som emneord. Brukt på ett dok.
* [X] `Allmenndannelse` :  ser ikke ut som vi har noe litteratur om dette :open_mouth:
* [x] `American Geophysical Union`: ingen treff. Koporasjon?
* [x] `Analysedata` : brukt på [ett dok](http://ask.bibsys.no/ask/action/show?pid=922414130&kid=biblio), som ser ut til å være bedre beskrevet av `Analyselaboratorier`. Slette?
* [x] `Analyseprosesser` -> `Analysemetoder` ? 
* [x] `Analytiske metoder` : hummer&kanari -- slette?
* [x] `Anatomisk medisin` : [ett dok](http://ask.bibsys.no/ask/action/result?cql=%28bs.lokoeo-frase+%3D+%22Anatomisk+medisin%22%29++AND+%28bs.avdeling+%3D+%22ureal?%22%29&aktivKilde=biblio%3AUBO) -- holder det ikke med `Anatomi`?
* [x] `Angrep` : hummer&kanari  -- slette? evt. sjekke/legge på mer spesifikke emneord på [disse tre dokumentene](http://ask.bibsys.no/ask/action/result?cql=%28bs.lokoeo-frase+%3D+%22Angrep%22%29++AND+%28bs.avdeling+%3D+%22ureal?%22%29&aktivKilde=biblio%3AUBO) først, @knuthe @BioHeidi 
* [x] `Ansiktet` : fl.tall?
* [x] `Antibakterielle legemidler` og `Antibakterielle peptider` : Kan de slås sammen som `Antibakterielle midler`? Med SO `Antibiotika`?
* [x] `Antimikrobielle stoffer` og `Antimikrobielle behandlinger` : Slås sammen som `Antimikrobielle midler` ?
* [x] `Apollo` -> `Apolloprogrammet` (som forresten skal være `Apollo-programmet`?)
* [x] `Apotekpersonale` : slette? Vi har `Apotekere`
* [x] `Applikasjonsprogrammering` og `Applikasjonsutvikling` slås sammen @knuthe ? 
* [x] `Approksimasjon av funksjoner` : slette? Intet litteraturbelegg, men har MSC
* [x] `Arbeider` : Litt hummer&kanari. Delvis brukt i betydningen "papers". Mulig vi kunne klargjort med en definisjon at den *bare* skal brukes til det? Men er det da en formterm? Er `Samlete verker` dekkende?
* [x] `Arbeid` : slette? Vi har `Arbeidsliv` og mange flere mer spesifikke emner
* [x] `Aromater` og `Aromatiske forbindelser` slås sammen
* [x] `Aroma` slettes? Eller BF på `Aromastoffer`?
* [x] `Artificial intelligence` -> `Kunstig intelligens`
* [x] `Ascii` -> `ASCII`
* [x] `Tcp/ip` -> `TCP/IP`
* [x] `Askelag` -> `Aske` ?
* [x] `Aspectj` -> `AspectJ`

**Comment by mittinatten** [comment]
Kommentarer på mine: 
* Akselerasjon: ja slettes
* Akseptor, Donor, Dopelementer: slås sammen til Dopelementer, tenker det er litt som flo, fjære og tidevann. Holder med en term.

**Comment by bibliomari** [comment]
Ansiktet: Ubestemt flertall brukes ikke på ting som det "bare finnes en av/et par av", f.eks. Ansiktet, Lungene. Vi er selvsagt ikke perfekte her, men Ansiktet får stå :)

**Comment by knuthe** [comment]
AIX - husker ikke helt. Det var vel en Unix-variant fra DEC (?) Jeg skal sjekke om vi -tross null treff- har AIX i hylla. Men dette reiser jo også spørsmålet om vi skal samordne unix-varianter og deres skall (bash, etc).

**Comment by Hypsibius** [comment]
No er alle haka av, betyr det alt lista er klar?

**Comment by danmichaelo** [comment]
Ja, vi tok en fellesøkt på tirsdag og gikk gjennom resten. De eneste punktene som gjenstår er skilt ut som egne saker. Og så er det del II da :)
