### ISSUE TITLE
Ray tracing / Rendering / etc

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#208]
Jeg føler vi trenger et eller to emneord til for 3D grafikk, nå har vi bare `Datagrafikk` og `Tredimensjonal representasjon` hva jeg kan se. Men, har ikke klart å finne noen gode norske termer, det er mulig de allerede er i listen, da kanskje det holder å legge på engelsk på de (sånn at jeg finner de neste gang :) ) @danmichaelo @knuthe

**Comment by mittinatten** [comment]
Belegg http://ask.bibsys.no/ask/action/show?kid=biblio&cmd=reload&pid=150600690

**Comment by knuthe** [comment]
"rendering" har ufattelig mange betydninger, men kan jeg foreslå framstilling eller presentasjon som grunnord som kan kombineres slik "grafisk framstilling" (fins i Roald med BF "Grafisk presentasjon").
Her avventer jeg reaksjoner.

"Ray tracing" - har ikke norsk ord, men flesker  til med "strålesporing" eller "lyssporing". Det første fikk jeg i etterhånd faktisk treff på i Google. Jammen fikk jeg treff på "lyssporing" også. Jeg legger dette inn i Sonja så kan det brukes inntil vi finner på noe bedre.

**Comment by mittinatten** [comment]
Strålesporing syns jeg høres bra ut!

Verbet _å rendere_ virker jo å være tillatt norsk, selv om grafikk-betydelsen ikke finnes i ordlisten (hva jeg kan se). Går det an å si 

    3D-rendering
    BF tredimensjonal rendering
    EN 3D rendering
    UT Strålesporing
    SO 3D-grafikk

pluss
     
     3D-grafikk
     BF tredimensjonal grafikk
     EN 3D graphics
     SO 3D-rendering

Eller må den sifferfrie versjonen være foretrukket? Jeg tenker den første som prosess og den andre som produkt. Alle bøker om 3D-grafikk handler ikke om rendering, men alle om rendering handler nok om grafikk.

**Comment by danmichaelo** [comment]
Synes det ser fint ut. Fikser du i Sonja hvis du enig, @knuthe?

**Comment by danmichaelo** [comment]
Fiksa det jeg. Tror rendering kommer inn i ordlista etter hvert. La inn `Rendering BF 3D-rendering`. Ellers akkurat som du foreslo.

**Comment by danmichaelo** [comment]
@knuthe Vi bør kanskje ta en titt på noen av bøkene som i dag er merka `Tredimensjonal representasjon`
