### ISSUE TITLE
Scanning electron microscope

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#209]
kan fornorskes som `Sveipelektronmikroskopi` med AK SEM

**Comment by bibliomari** [comment]
Love it!!
Den 17. mars 2015 13:22 skrev "Dan Michael O. Heggø" <
notifications@github.com> følgende:

**Comment by bibliomari** [comment]
Gjort. Og da dukker spørsmålet opp: Må denne

http://ask.bibsys.no/ask/action/show?pid=071610804&kid=biblio

ha sin EGEN sære metode, LVSEM?

**Comment by danmichaelo** [comment]
Jeg synes ikke det.
