### ISSUE TITLE
Merkelappene

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#21]
Fine labels, men jeg vet ikke helt hvilken jeg skal bruke på generell rydding/sammenslåing, som f.eks. fiske/fiskeri. Korrektur? Eller skal jeg lage ny label som heter rydding eller sammenslåing?

**Comment by danmichaelo** [comment]
"Rydding" ble litt hummer og kanari, så omdøpte den til "trenger katalogrydding". Og så har vi jo fått "sammenslåing"
