### ISSUE TITLE
Dokumentarfilm

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#211]
Vi har formene `Tegnefilm` og `Spillefilm`, men mangler `Dokumentarfilm`.

Belegg: http://ask.bibsys.no/ask/action/show?kid=biblio&cmd=reload&pid=150440715

(På akkurat denne er `Biografier` like relevant som `Dokumentarfilm`, er det ok å ha mer enn en form på samme objekt? En bibliotekar hos oss har lagt til Humordet DVD, er det logisk?)

@bibliomari

**Comment by bibliomari** [comment]
Helt greit å ha flere former, ja. Og humordet er også greit siden de har med $b form (som markerer at det ikke handler om film, men er film), men det er jo en opplysning som også finnes i annen form på katalogposten, så den er ikke strengt nødvendig. 

Dokumentarfilm er lagt til (selvom jeg også fuderte på om vi skulle nøyd oss med "dokumentar", slik at vi også kan bruke det til dokumentarromaner og... ?).

**Comment by knuthe** [comment]
og selvfølgelig radiodokumentarer :-) : 

http://radio.nrk.no/serie/radiodokumentaren/MDSP01001115/14-03-2015

**Comment by mittinatten** [comment]
Ja, bare dokumentar er kanskje bedre, selv om jeg ikke vet om jeg hadde kjent igjen en dokumentarroman om jeg hadde en i handen :)

**Comment by bibliomari** [comment]
Da har jeg endret til dokumentar :)

**Comment by grosyn** [comment]
Som nevnt i andre saker den siste tida, er me i ferd med å få over til å bruka [NTSF](https://www.nb.no/nbvok/ntsf/nb/). 
Dei har både Dokumentarfilmer og Dokumentarromaner. Sidan våre treff på Dokumentar er filmar, blir desse no bytta ut med Dokumentarfilmer.
