### ISSUE TITLE
Forekomster

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#212]
`Ertsforekomster`, `Malmforekomster`, `Mineralforekomster` og `Forekomster` : Er dette ulike begreper, eller kan (noen av) de slås sammen? For meg ser det umiddelbart som alle handler om "mineraler i økonomisk drivverdige mengder", men jeg er jo på veldig faglig tynn is her!

@kristinran

**Comment by kristinran** [comment]
jeg vil vel si at som emneord er det behov for malmforekomster og mineralforekomster, siden ikke alle mineralerforekomster er malmforekomster. hva dewey har av muligheter er en annen sak, begge emneord får antagelig samme dewey.



Kristin

________________________________

**Comment by danmichaelo** [comment]
Takk for oppklaring her og på flyplassen :) Konklusjonen ble vel at vi kan slå `Ertsforekomster` inn i `Malmforekomster`, men beholde resten. `Forekomster` er litt overflødig, men kan kanskje være grei å ha for å bygge strenger for spesifikke forekomster, f.eks. `Tinn : Forekomster`.

**Comment by BioHeidi** [comment]
Gjort
