### ISSUE TITLE
Min ryddeliste del II

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#214]
Joho, bedre sent enn aldri! Jeg har tagget personer noen steder, men ikke helt konsekvent.

**Astro:** -- @superLine @mittinatten
- [x] `Astrofysisk romforskning`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Astrofysisk romforskning) og `Astrofysisk forskning` (ett dokument) - trenger vi den siste? 
- [x] `Astrofysisk plasma`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Astrofysisk plasma), `Plasmaastrofysikk`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Plasmaastrofysikk) og `Kosmiske plasma`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Kosmiske plasma): slås sammen? Eller beholde to? Astrotesaurusen har [Plasma-astrofysikk](http://www.altbibl.io/astrothesaurus/uat/termrecords/Plasma+astrophysics.html) og [Romplasma/Astrofysiske plasma](http://www.altbibl.io/astrothesaurus/uat/termrecords/Space+plasmas.html)
- [x] `Kosmonauter`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Kosmonauter) flettes inn i `Astronauter`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Astronauter)
- [x] `Astronomiske konstanter`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Astronomiske konstanter) : brukt på ett dok., holder det ikke med `Fysiske konstanter` + `Astronomi`?
- [x] `Astronomiske parametre`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Astronomiske parametre) : vagt? Brukt på ett dok.
- [x] `Astronomiske systemer`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Astronomiske systemer) : trenger vi denne? De to dok. ser ut til å være dekket av `Gravitasjon` + `Solsystemet`
- [x] `Astronomiske teleskoper`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Astronomiske teleskoper) og `Teleskoper`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Teleskoper&show=sh) : trenger vi begge? 
- [x] `Asymptotic giant branch`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Asymptotic giant branch) -> `Den asymptotiske kjempegrenen` eller kanskje `AGB-stjerner`?? 
- [x] `Bakgrunnsstråling`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bakgrunnsstråling) og `Infrarød bakgrunnsstråling` flettes inn i `Kosmisk bakgrunnsstråling`
- [x] `Banebevegelser`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Banebevegelser) og `Baner` inn i `Baneberegninger`? (med SO Planetbaner, Satellittbaner)

**Informatikk:** -- @knuthe
- [x] `Asymmetric digital subscriber line`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Asymmetric digital subscriber line) -> `ADSL` ?
- [x] `Asynchronous javascript xml`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Asynchronous javascript xml) -> `Ajax` BF `Asynchronous JavaScript and XML`
- [x] `Asynchronous transfer mode`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Asynchronous transfer mode) -> `Asynchronous Transfer Mode` AK `ATM`
- [x] `Automatiseringssystemer`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Automatiseringssystemer) : nødv. utover `Automatisering`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Automatisering)? Slette?
- [x] `Awt`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Awt) : ingen treff. Skulle antakelig vært en se-henv.
- [x] `Awk`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Awk) og `Gawk` slås sammen
- [x] `Basic Input-Output System`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Basic Input-Output System) -> `BIOS`?
- [x] `Daml-s`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Daml-s) -> `DAML-S` (Eller slette synes egentlig jeg. Lite brukt ontologi tror jeg, erstattet av OWL-S)
- [x] `Brannmur`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Brannmur) : flertall?
- [x] `Brukerorientert`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Brukerorientert) -> `Brukersentrert utvikling` f.eks... ? @knuthe 
- [x] `Brukerstøtte`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Brukerstøtte) og `Brukerstøttesystem` : trengs begge?
- [x] `Brukerprogram`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Brukerprogram) : Hva er det?
- [x] `Bsd`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bsd) -> `BSD`
- [x] `Funksjonsprogrammering`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Funksjonsprogrammering) -> `Funksjonell programmering`
- [x] `Bull gamma 60`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bull gamma 60) : emneord?
- [x] `Grafisk billedbehandling`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Grafisk billedbehandling) : smør på flesk
- [x] `Bibtex`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bibtex) -> `BibTeX`
- [x] `Cisc`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Cisc) -> `CISC` 
- [x] `Cmos`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Cmos) -> `CMOS` og flett inn `Complementary Metal Oxide Semiconductor`
- [x] `Bcpl`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bcpl) -> `BCPL`
- [x] `Bredbåndsapplikasjoner`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bredbåndsapplikasjoner) : Er dette en interessant kategori av applikasjoner? Jeg synes ikke umiddelbart det, men kanskje @knuthe er uenig?
- [x] `Båndvidde`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Båndvidde) -> `Båndbredde` eller kanskje heller slette. Bare brukt på to dokumenter, som kanskje heller kunne hatt `Modemer`. @knuthe
- [x] `Bærbare maskiner`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bærbare maskiner) -> `Bærbare datamaskiner`
- [x] `Cafeobj`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Cafeobj) -> `CafeOBJ` hvis vi trenger dette som eget emneord..
- [x] `Caml`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Caml) og `Ocaml` : slås sammen
- [x] `Cca`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Cca) - Hva er det -- et akronym`
- [x] `Ccd`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Ccd) -> `CCD` (og flett inn Ccd-kamera)
- [x] `Ccl`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Ccl) -> `CCL` 
- [x] `Cd4`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Cd4) -> `CD4` + definisjon `glykoprotein`
- [x] `Cdrom`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Cdrom) -> `CD-ROM` (hehe, jeg var sikker på at denne hadde blitt misbrukt som formterm, men [neida](http://katapi.biblionaut.net/documents?q=real:Cdrom&show=sh)! Vi mangler bare strengen `CD-ROM : Japan` :D)
- [x] `Cuda`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Cuda) -> `CUDA` 

**Bio:** -- @BioHeidi @Hypsibius
- [x] `Balsam`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Balsam) : Trenger kanskje en definisjon? Jeg tenkte først på hårproduktet :P
- [x] `Bekjempelse`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bekjempelse) : For vagt, slettes
- [x] `Bioelektriske energikilder`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bioelektriske energikilder) : Denne komboen skjønner jeg ikke helt, men tror vi burde være dekket med `Biolektrisitet` og `Bioenergi`.. Slette?
- [x] `Biologisk kjemi`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Biologisk kjemi) -> `Biokjemi` ?
- [x] `Biomasse`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Biomasse) og `Biomasseenergi` : trengs begge? @bioheidi 
- [x] `Cytoskjelettet`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Cytoskjelettet) : skal det være bestemt form?

**Alle:**
- [x] `Athena`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Athena) : ingen treff, slette?
- [x] `Atomabsorpsjon`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Atomabsorpsjon)[(bruk)](http://katapi.biblionaut.net/documents?q=real:Atomabsorpsjon&continue=1&show=sh) : ser ut som bare brukt i betydningen `Atomabsorpsjonsspektrometri`
- [x] `Atomforskere`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Atomforskere) : slettes. For den ene boka som har emneordet burde heller vært `Kjernefysikere` , eller kanskje det holder med `Fysikere : Historie` + `Atomvåpen : Historie`.
- [x] `Attributter`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Attributter)[(bruk)](http://katapi.biblionaut.net/documents?q=real:Attributter&show=sh) : flertydig? brukt på ett dok. slette?
- [x] `Audiofysikk`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Audiofysikk)[(bruk)](http://katapi.biblionaut.net/documents?q=real:Audiofysikk&show=sh): Kan ikke omgjøres til en BF på `Akustikk`?
- [x] `Autoimmunitet`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Autoimmunitet) og `Autoimmune sykdommer` : trengs begge?
- [x] `Avfall`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Avfall)[(bruk)](http://katapi.biblionaut.net/documents?q=real:Avfall&continue=1&show=sh) og `Avfallsbehandling`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Avfallsbehandling&continue=1&show=sh) : har vi behov for å skille mellom disse?
- [x] `Avrenning`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Avrenning)[(bruk)](http://katapi.biblionaut.net/documents?q=real:Avrenning&continue=1&show=sh) og `Avrenningsområder`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Avrenningsområder&continue=1&show=sh) : og mellom disse?
- [x] `Avstander`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Avstander)[(bruk)](http://katapi.biblionaut.net/documents?q=real:Avstander&continue=1&show=sh), `Avstandsberegninger`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Avstandsberegninger&continue=1&show=sh), `Avstandsbestemmelser`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Avstandsbestemmelser&continue=1&show=sh), `Avstandsmålinger`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Avstandsmålinger&continue=1&show=sh) og `Avstandsmålere`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Avstandsmålere&continue=1&show=sh) : og disse?
- [x] `Balansert utvikling`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Balansert utvikling)[(bruk)](http://katapi.biblionaut.net/documents?q=real:Balansert%20utvikling&continue=1&show=sh) : Slettes
- [x] `Banach algebra`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Banach algebra) -> `Banach-algebraer`
- [x] `Banach`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Banach) slettes (dekkes av `Banach-algebra`.. som jeg forresten lurer på om ikke skal være i fl.tall?)
- [x] `Bankid`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bankid) : Ingen litteratur, slettes?
- [x] `Bassengsimulering`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bassengsimulering) og `Bassengmodellering` : trengs begge?
- [x] `Bassengkonfigurasjon`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bassengkonfigurasjon): Er det et begrep? @kristinran Her spør jeg bare fordi jeg er usikker
- [x] `Beregnbare funksjoner`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Beregnbare funksjoner) inn i `Beregnbarhet`
- [x] `Bergverk`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bergverk), `Bergverksdrift` og `Bergvesen`: Trengs alle tre?
- [ ] `Bestråling`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bestråling)[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bestråling&continue=1&show=sh) : hummer&kanari.. Jeg tror det greieste her er å omklasse til de ulike typene stråling: UV-stråling, Røntgenstråling, osv... Bare 9 dokumenter
- [x] `Betastråler`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Betastråler) -> Betastråling BF Betahenfall
- [x] `Bibelfortolkning`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bibelfortolkning) og `Bibelkritikk` -> `Bibelen`
- [x] Vi har veldig mange `Bibliotek*`-emner :) Trenger vi f.eks. `Bibliotekvirksomhet`[(bruk)](https://katapi.biblionaut.net/documents?q=real:Bibliotekvirksomhet)
- [x] `Desimalklassifikasjon`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Desimalklassifikasjon) ser ut til i praksis å handle om `Deweys desimalklassifikasjon` og kan antakelig slettes
- [x] `Bibliografisk standard`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bibliografisk standard) : flertall? Og burde det kommet inn noen henvisninger? BF Referansestiler SO Sitatbruk kanskje?
- [x] `Bicmos`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bicmos) -> `BiCMOS`
- [x] `Bind`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bind) : Intet litteraturbelegg, uklar betydning. Slette
- [x] `Bindinger`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bindinger) -> `Kjemiske bindinger` (de fleste dokumentene har den allerede, se [katapi](http://katapi.biblionaut.net/documents?q=real:Bindinger&show=sh,k))
- [x] `Bjelker`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bjelker) og `Bjelkestrukturer` : trengs begge?
- [x] `Bonner Durchmusterung`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bonner Durchmusterung) og `Cape Photographic Durchmusterung` : skal dette være emneord? @linena @bibliomari #81
- [x] `Bose-Einstein condensates`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bose-Einstein condensates) -> `Bose-Einstein-kondensat` (kan antakelig være både entall og flertall avh. om en snakker om tilstanden eller forbindelser i tilstanden.. Tanker, @mittinatten ?)
- [x] `Bosonmodellen`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bosonmodellen) -> `Bosoner`
- [x] `Bourne`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bourne) : ingen litteratur @knuthe
- [x] `Brannfarlige og eksplosjonsfarlige stoffer`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Brannfarlige og eksplosjonsfarlige stoffer) og `Brannfarlige tekstiler` : intet litteraturbelegg, slettes
- [x] `Brebevegelser`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Brebevegelser) -> `Isbrebevegelser` for konsistens?
- [x] `Brauer grupper`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Brauer grupper) -> `Brauer-grupper`
- [ ] `Bremiljøer`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bremiljøer) : Er det en term?
- [ ] `Bretermer`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bretermer) : Nødvendig å ha dette som egen term? Og kanskje vi skulle hatt `Terminologi`?
- [x] `Byggverk`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Byggverk) slettes basert på [bruken](https://katapi.biblionaut.net/documents?q=real:Byggverk)
- [x] `Bylandskap`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bylandskap) : Tja.. holder det ikke med de andre By.../Urban...-termene vi har?
- [x] `Byklima`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Byklima) -> `Bymiljø`
- [x] `Bærekraftighet`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bærekraftighet), `Bærekraftige naturressurser`, `Bærekraftig utnyttelse` og `Bærekraftig utvikling` : slå sammen?
- [x] `Bølgefordeling`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Bølgefordeling): hva er det?
- [x] `Børshistorie`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Børshistorie) : `Børsvesen` + `Historie` ? 
- [x] `Calabi-yau`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Calabi-yau) -> `Calabi-Yau-mangfoldigheter`
- [x] `Cauchy-kovalevskaya teoremet`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Cauchy-kovalevskaya teoremet) -> `Cauchy-Kovalevskaja-teoremet` (bindestrek og riktig transkribering)
- [x] `Centre National de la Recherche Scientifique`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Centre National de la Recherche Scientifique) og `Centre National d'Études Spatiales` : korporasjoner, ingen treff
- [x] `Centrifugal partition chromatography`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Centrifugal partition chromatography) : for spesifikt synes jeg. Vi har `Fordelingskromatografi`.
- [x] `Chemical abstracts`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Chemical abstracts) : Slette
- [x] `Chiral`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Chiral) : Ingen treff, slette? Vi har `Kiralitet` som er hva jeg antar det er meningen det er snakk om her.
- [x] `Church-turingtesen`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Church-turingtesen) -> `Church-Turing-tesen`
- [x] `Chebyshev*`, `Cholesky*` : skal det ikke inn bindestreker etter egennavnet her? [ref](http://www.korrekturavdelingen.no/K4EgennavnFellesnavn.htm)
- [ ] `Cluster Active Archive`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Cluster Active Archive) : emneord?
- [x] `Co2*` -> `CO2`
- [x] `Communication with Extraterrestrial Intelligence`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Communication with Extraterrestrial Intelligence), `Communication with Extra-Terrestrial Intelligence`, `Search for Extra-Terrestrial Intelligence` og `Search for Extra-Terrestrial Intelligence (SETI)` -> SETI
- [x] `Conseil Européen pour la Recherche Nucléaire`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Conseil Européen pour la Recherche Nucléaire) -> `CERN` (egentlig korporasjon...)
- [x] `Consistent force field`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Consistent force field) som for snevert (det finnes altfor mange slike).. Meneh, ser at vi mangler en term for [Kraftfelt](https://en.wikipedia.org/wiki/Force_field_%28chemistry%29)
- [x] `Cosinus transformasjon`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Cosinus transformasjon) : dårlig emneord. Inn som BF på `Fouriertransformasjoner`.
- [x] `Coulomb`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Coulomb) : øh... mannen? Neppe. Slett
- [x] `Cr-functions`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Cr-functions) : funksjoner?
- [x] `Cyclic adenosine monophosphate`[(bruk)](http://katapi.biblionaut.net/documents?q=real:Cyclic adenosine monophosphate) -> `Syklisk AMP` kanskje? https://no.wikipedia.org/wiki/Syklisk_AMP

**Comment by mittinatten** [comment]
Astronomi
* Holder med `Astrofysisk forskning`
* `Astrofysiske plasma BF Romplasma BF Kosmiske plasma`
* Astronomiske konstanter og parametre: slett
* Astronomiske systemer: slett
* Holder med `Teleskoper`
* `Asymptotic giant branch`, usikker på form, men asymptotisk kjempegren er bra, vet ikke om det bør være "den"
*  Ja til bakgrunnstrålingene inn under `Kosmisk bakgrunnsstråling`

Informatikk
* Holder med `Automatisering` mener jeg
*  `Awk BF Gawk`
* `BSD BF OpenBSD BF FreeBSD BF Berkeley Software Distribution SO Mac OS`
* Veldig for `Funksjonell programmering BF Funksjonsprogrammering` heller enn omvendt.

Alle
* Vi har 6 termer som begynner med Bayesiansk. `Bayesiansk teori` virker å være den minst meningsfulle, men kanskje skal ta det opp som en separat tråd.
* `Bose-Einstein kondensat`: stemmer for entallsform. Det er i høyere grad et konsept enn noe en går ut i naturen og teller opp :)
* `Bourne`:  `Bash` -> `BASH BF Bourne again shell`
* `Bærekraftighet`, trenger kanskje en separat tråd på den også?
* Chebyshev* -> Tjebysjov-*, plus BF/EN med Chebyshev
*  `Cr-functions` -> `CR-mangfoldigheter BF Cauchy-Riemann-mangfoldigheter EN CR manifolds` muligens? Ikke det samme men kan kanskje grupperes i klassifiseringssammenheng.
* `Consistent force field` -> `Kraftfelt`

De andre punktene som faller under mine fag har jeg ikke kommentert på fordi jeg er enig.

**Comment by Hypsibius** [comment]
Kommenterer ein for ein: 

Bio: -- @BioHeidi @Hypsibius

    Balsam(bruk) : Trenger kanskje en definisjon? Jeg tenkte først på hårproduktet :P. *Ingen ide* 

    Bekjempelse(bruk) : For vagt, slettes *kva tenkjer du som alternativ? Eg ser for meg svartlisteartar...*

    Bioelektriske energikilder(bruk) : Denne komboen skjønner jeg ikke helt, men tror vi burde være dekket med Biolektrisitet og Bioenergi.. Slette? *gjerne for meg*

    Biologisk kjemi(bruk) -> Biokjemi ? *vil eg tru*

    Biomasse(bruk) og Biomasseenergi : trengs begge? @bioheidi *overlet til @BioHeidi *

    Cytoskjelettet(bruk) : skal det være bestemt form? *Ja, skal det ikkje det? Som hjertet, leveren, ryggraden? Vil ikkje ein organelle skulle behandlast på same måte som eit organ her?*

Alle:

**Comment by Hypsibius** [comment]
øh, blir ikkje klok på formatteringane, men orkar helle rikkje bruke tid på det...

**Comment by kristinran** [comment]
ad bassengmodellering: mener det må holde med bassengmodellering som emneord

**Comment by danmichaelo** [comment]
Jeg slettet likegodt `Cyclic adenosine monophosphate` siden den ikke var i bruk. Kanskje den har vært brukt på et dokument som har blitt kassert.

**Comment by knuthe** [comment]
Da har jeg vært gjennom "informatikk" i del 2 av ryddelista til DM. To står igjen som tilhører andre. Jeg har også tatt den ene under "alle" der jeg var tagget, samt informatikken til Simon. Da tror jeg at jeg kan ta ferie med god samvittighet.

**Comment by danmichaelo** [comment]
Knall! God ferie :sunglasses:

**Comment by knuthe** [comment]
Takk i like måte. (det forstås vel implisitt at dette er fikset i BIBSYS og Sonja også).

**Comment by BioHeidi** [comment]
Biomasse(bruk) og Biomasseenergi : trengs begge?
Nei, Biomasse får stå, Biomasseenergi kan legges inn som BF-term til Bioenergi.

Cytoskjelettet(bruk) : skal det være bestemt form?
Enig med Hege: Ja.

Autoimmunitet(bruk) og Autoimmune sykdommer : trengs begge?
Ja.

 Avfall(bruk)(bruk) og Avfallsbehandling(bruk) : har vi behov for å skille mellom disse?
Tja. Jeg tror "Avfall" i mange tilfeller her kommer fra "Radioaktivt avfall". Sånn som jeg ser det er brukt skilles det ikke, så vi kan slå sammen til Avfallshåndtering. Men jeg kan godt se for meg behov for å bare ha Avfall som eget emneord - vi får gjenopprette det ved behov, det blir litt mye å rydde i med nåværende treffliste.

Bylandskap(bruk) : Tja.. holder det ikke med de andre By.../Urban...-termene vi har?
Jo, jeg ville ha lagt det sammen med Bymiljø.

Byklima(bruk) -> Bymiljø
Byklima er derimot et helt eget emneord. Vind i by med høye bygninger! Kul bok!

**Comment by BioHeidi** [comment]
@kristinran 
Bremiljøer(bruk) : Er det en term?
Holder kanskje med Glasiologi? 

Bretermer(bruk) : Nødvendig å ha dette som egen term? Og kanskje vi skulle hatt Terminologi?
Skulle vel vært streng på det dokumentet: Glasiologi : Ordbøker

**Comment by danmichaelo** [comment]
Har lyst å lukke denne :zap:  Det som gjenstår er [Bestråling](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011038), [Bremiljøer](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005381) og [Bretermer](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006388). 
- Har ryddet unna litt i `Bestråling`, det som gjenstår nå er stort sett matvarbestråling og det ser ikke så rotete ut lenger, kan forsåvidt bli stående slik tror jeg.
- `Bretermer`: Ellers har vi bare `Tekniske termer` av denne typen. Heller mot å slette den og legge på form `Terminologi` på dokumentet. Enig @BioHeidi @Violabibaluba ?
- `Bremiljøer`: Som @BioHeidi er jeg usikker på om det er en term. Gir den noe utover de andre bretermene vi har? @jw-geo @edinab ?

**Comment by Hypsibius** [comment]
Bremiljøer: Skulle denne i grunnen beskrive forskningsmiljø, brenære habitat eller reine abiotiske faktorar knytt til bre? Ikkje openberrt ut frå termen, men det eine treffet tydar på den siste tolkinga

**Comment by kristinran** [comment]
Tror det må være tenkt den siste betydningen, ser ikke annen åpenbar bruk innenfor geofag.



Kristin

________________________________
Fra: Hypsibius <notifications@github.com>
Sendt: 2. februar 2017 10:19
Til: realfagstermer/realfagstermer
Kopi: Kristin Rangnes; Mention
Emne: Re: [realfagstermer/realfagstermer] Min ryddeliste del II (#214)


Bremiljøer: Skulle denne i grunnen beskrive forskningsmiljø, brenære habitat eller reine abiotiske faktorar knytt til bre? Ikkje openberrt ut frå termen, men det eine treffet tydar på den siste tolkinga

-

**Comment by danmichaelo** [comment]
Slettet Bretermer (boka var dekket av `Glasiologi` + `Ordbøker`) og Bremiljøer.
