### ISSUE TITLE
Terrestrial gamma ray flashes (TGF)

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#217]
Ny term: `Terrestriske gammastråleblink`?? Jeg er helt lost på hva som er god norsk her. @danmichaelo 

Belegg: https://bora.uib.no/handle/1956/9348
Wikipedia: http://en.wikipedia.org/wiki/Terrestrial_gamma-ray_flash

**Comment by danmichaelo** [comment]
Hadde aldri hørt om dette, men fra litt googling fant jeg `Terrestriske gammaglimt` brukt et par ganger. Det virker for som en god term synes jeg.

**Comment by knuthe** [comment]
Jeg har hørt om gammaglimt, men ikke sett noen (heldigvis?). Jeg la inn DMs norske og SMs engelske.

**Comment by mittinatten** [comment]
Takk! Glimt er mye bedre en blink :)
