### ISSUE TITLE
Utviklingsbiologi

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#218]
Denne termen brukar vi om 'development' og ikkje 'evolution, ikkje sant, @BioHeidi ? Skal denne sjåast i samanheng med Evodevo?

**Comment by Hypsibius** [comment]
Eller, ikkje eit spørsmål om 'om' men om 'korleis' (den skal sjåast i samanheng)?

**Comment by BioHeidi** [comment]
Ja, vi bruker den om development. Bør sette det som engelsk term.  Vi har jo både utviklingsbiologi og embryologi, fordi det skjer en utvikling også etter at embryofasen er over. Som hos oss betyr etter fødsel, siden vi kaller all forsteutvikling for embryologi i emneordene. Jeg tenker at evodevo-bøker kan få begge emneordene, evt evolusjon og embryologi. Eller blir det rart?

**Comment by Hypsibius** [comment]
Ikkje rart, men kan tenkje meg at noko søker direkte etter evo-devo, og då er spørsmålet kva dei evt skal få treff på...

**Comment by Hypsibius** [comment]
Om noko...

**Comment by BioHeidi** [comment]
Da får de ikke treff på noe, og må søke Evolusjon OG Utvikling, og da ser de sikkert Utviklingsbiologi, og så ordner alt seg.

**Comment by BioHeidi** [comment]
Fikset!
