### ISSUE TITLE
Rydding i Havvann, sjøvann, saltvann

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#22]
Kom med innspill, jeg rydder kraftig her når jeg får tid.

**Comment by Hypsibius** [comment]
@mzyg Kva seier du?

**Comment by danmichaelo** [comment]
Holdt på å slette Saltvann nå fordi det ikke var noen dokumenter der: https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009720

Skjønner du hva som kan ha skjedd, @BioHeidi ?

**Comment by Hypsibius** [comment]
??? I så fall må det inn ein BF-term på havvann!

**Comment by BioHeidi** [comment]
Legger det inn som BF på Havvann. Den ble stående som term fordi dokumentene som hadde denne termen ble ryddet over på andre ting, så da tenker jeg at den termen ikke var så sentral. Men en BF må til.
