### ISSUE TITLE
Milleniumsproblemene

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#220]
Epost fra Karoline:

> Jeg ønsker meg et emneord på millenniumproblemene.
> Om det skal være matematikk : millenniumproblemene eller millenniumproblemene eller millenniumproblem eller millenniumproblemer er litt opp til dere.
> 
> Vi bør også være mer spesifikke (noe vi også er med de to første):
> - Riemannhypotesen / Riemann hypothesis
> - Navier-Stokes likninger
> - Poincaréformodningen / Poincaré conjecture
> - P versus NP
> - Yang-Mills eksistens / Yang-Mills existence
> - Birch og Swinnerton-Dyer formodningen / Birch and Swinnerton-Dyer conjecture
> - Hodgeformodningen / Hodge conjecture (Her har vi Hodgeteori, men jeg vil si at det er litt mer generelt.)
> 
> Jeg er litt usikker på om det burde vært underkategorier av millenniumproblemene,
> eller at begge emneordene faktisk bør ligge på i disse tilfellene, men det har kanskje dere tanker om?
> millenniumproblemene : Poincaréformodningen

**Comment by mittinatten** [comment]
Mye hellre to emneord enn underordnet. At noen har laget en liste over problemer betyr ikke at problemene er underordnet listen :)

**Comment by danmichaelo** [comment]
Foreløpig forslag:
* Ny term: `Millenniumproblemene EN Millennium prize problems EN Millennium problems DEF Sju matematiske problemer annonsert av Clay Mathematics Institute i 2000`
* Se-også-henv. 
* De andre kan legges inn ved behov

**Comment by bibliomari** [comment]
Gjort
