### ISSUE TITLE
Miljøkatastrofer

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#221]
Foreslår ny term: miljøkatastrofer NN miljøkatastrofer EN environmental disasters. Dessverre ser det spesifikke Dewenynummeret ut til å vere 'discontinued': 
(363[.3497] Disasters induced by human activity)

Belegg: http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS141919000&vid=UBB

Bør vurderast mot andre termar som *miljøulykker*, *miljøforstyrrelser*, *miljøskader* etc... Vi bør ha ei form for gradering, men kor mange grader bør vere med?

**Comment by danmichaelo** [comment]
Forslag: Foreløpig oppretter vi `Miljøkatastrofer` som foreslått

**Comment by Hypsibius** [comment]
Jepp :-) God stad å starte

**Comment by Hypsibius** [comment]
Ah! Ferdig snakka :-)

**Comment by danmichaelo** [comment]
Hehe, det gjør ikke noe å kommentere etterpå heller altså, men vi eksperimenterer med et nytt system der vi setter på "ferdig-diskutert" når vi anser at saken er kommet dit at det bare er for noen med Sonja å gjøre det som gjøres må der :)

**Comment by danmichaelo** [comment]
Vi kunne forsåvidt også kalt den "klar-for-sonja" :D

**Comment by danmichaelo** [comment]
Oppretta!
