### ISSUE TITLE
Geologisk ordbok

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#222]
Bør være `Geologi : Ordbøker`

**Comment by mittinatten** [comment]
Beklager her gikk det visst lit kjapt, `Ordbøker` finnes selvfølgelig :)

**Comment by mittinatten** [comment]
Dere som har følgt med har kanskje sett at jeg redigert første spørsmålet. Jeg lurer på når jeg skal bruke formen `Ordbøker` og når jeg skal bruke `Terminologi`. Kan jeg bruke begge samtidig for en fagordbok? @bibliomari (i mitt tilfelle arabisk-engelsk fagordbok for informatikk http://ask.bibsys.no/ask/action/show?pid=890250871&kid=biblio)

**Comment by bibliomari** [comment]
@mittinatten Endelig noe som står i retningslinjene :D 
"Alle ordbøker får formtermen Ordbøker i tillegg til emneterm for kildespråk. Term for målspråk registreres som underemneterm." (jeg vet ikke hvor lurt det siste er, jeg skal ta det opp med @Violabibaluba )
"Fagordbøker får i tillegg term for fagområde og formtermen Terminologi"

**Comment by mittinatten** [comment]
Ok, unntatt det med underemneterm er alt klart nå!
