### ISSUE TITLE
Bayesiansk teori

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#223]
Er dette et begrep avgrenset fra `Bayesiansk statistikk` og `Bayesiansk beslutningsteori`?

Fra [(bruk)](http://katapi.biblionaut.net/documents?q=real:Bayesiansk teori) ser det ut som  `Bayesiansk teori` kan erstattes av `Bayesiansk statistikk`, men at noen av bøkene bør i stedet få  `Bayesiansk beslutningsteori`.

**Comment by mittinatten** [comment]
Ja, det ser sånn ut. Jeg kan ikke så mye om bayesiansk statistikk, men kan ikke helt forstå hva teorien skulle være utover statistikken- muligens om en vil fremheve det filosofiske perspektive, og sette det opp mot et frekventistisk perspektiv, men vi trenger kanskje ikke det skillet. 

Bør vi legge `BF Bayesisk ...` på alle termene (se #119)? Ser at tekord har `Bayes statistikk`.

**Comment by danmichaelo** [comment]
* [X] La inn "Bayesisk ..." på alle nå

**Comment by bibliomari** [comment]
... så da kan denne lukkes, @danmichaelo ? Eller er det noe igjen som jeg skal gjøre? Jeg skjønner nemlig ikke hva :)

**Comment by danmichaelo** [comment]
Nei, det var dette med å erstatte `Bayesiansk teori` med `Bayesiansk statistikk`, men i noen tilfeller med `Bayesiansk beslutningsteori`...

**Comment by danmichaelo** [comment]
Ryddet i katalogen og slettet `Bayesiansk teori`
