### ISSUE TITLE
Form: Forelesningsnotater

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#226]
Kunne vi hatt bruk for formen `Forelesningsnotater`?

**Comment by danmichaelo** [comment]
Hm, hva er litteraturbelegget?

**Comment by mittinatten** [comment]
Vi har mange av denne typen http://ask.bibsys.no/ask/action/show?kid=biblio&cmd=reload&pid=932425518

**Comment by bibliomari** [comment]
Jeg har lagt til Forelesningsnotater som form, tar gjerne imot forslag til definisjon/alternative betegnelser/andre språkformer. Jeg vet jo at vi også har litt av dette, @knuthe 

Humord har "Forelesninger", men det ser hakket mer publisert ut?

**Comment by mittinatten** [comment]
Det er mulig `Forelesninger` er en bedre form. Da kan en inkludere ting som er litt mer bearbeidet, mer publisert, som sagt.

**Comment by Hypsibius** [comment]
Hm, er forskjellen at 'forelesningsnotater' er det eg tar når eg sit i salen på forelesninga, og 'forelensinger' er det kompendiet forelesaren gir ut?

**Comment by mittinatten** [comment]
Mange bøker har ordet forelesningsnotater i tittelen (for eksempel bokseriene "Lecture notes in ..." fra Springer). Så skulle si det er en etablert term for denne type materiale. Muligens gjør termen `Forelesninger` at ser at det ikke fremst dreier seg om håndskrivne notater, som du sier, uten at det også kan være et utkast til en lærebok. Så jeg vet ikke hva som veier tyngst, etablert praksis innenfor i hvert fall noen felt som matematikk, informatikk, etc (forelesningsnotater), eller å legge seg opp mot humord (forelesninger) og kanskje unngå noen missforstand?

**Comment by danmichaelo** [comment]
Jeg la inn `Forelesninger` som alternativ term, og `Lecture notes` som engelsk.. Jeg er veldig usikker på hvordan dette skal defineres, men hvis jeg har forstått det riktig dreier seg om materiale som ikke har blitt til en lærebok, men som er "lærebokstoff"? Det kan være brukt i forelesninger, men ikke nødvendigvis. Mye av det som publiseres i "Lecture notes in ..."-seriene tror jeg ikke er det. Og det kan være publisert, men ikke nødvendigvis.

**Comment by danmichaelo** [comment]
Vi kan evt. bare droppe definisjon og lukke saken, men hvis noen har forslag til definisjon er det fint :)

**Comment by mittinatten** [comment]
Når jeg skulle søke opp formen i Roald for å legge til på eksemplet over fant jeg og termen `Knallforelesninger`. Tenker at denne kan legges inn som BF på `Presentasjonsteknikk`

**Comment by mittinatten** [comment]
Definisjon: "Alt fra studenters notater til uformelle lærebøker." (for vagt?)

Et godt eksempel på verdien av det første har vi her: http://bibsys-primo.hosted.exlibrisgroup.com/UBB:BIBSYS_ILS121835359

**Comment by danmichaelo** [comment]
Hjelp, hva er egentlig fellesnevneren til eksempelet ditt og f.eks. en artikkel i Lecture notes in physics?

**Comment by mittinatten** [comment]
hmmm må kanskje snevre inn lite ja.. :)

**Comment by bibliomari** [comment]
Det viser seg at vi har Kommentarer som emneord. Det kan ryddes og forvandles til formordet Kommentarer BF Kommentarutgaver. Forelesninger (lectures) for foreleserens egne manus/presentasjoner. Forelesningsnotater (lecture notes) for andres notater. Knallforelesninger går over som BF til ny form Populærforelesninger, som også kan romme ted talks og andre fancy former.

**Comment by danmichaelo** [comment]
Bare for å rydde litt i mine egne tanker: Etter dagens lille diskusjon tror jeg vi kom til at `Forelesninger` vil dekke en del av det som kalles "Lecture notes" på engelsk… men at vi kanskje legger på en intern note om at termen ikke ukritisk skal legges på alt som har "lecture notes" i tittelen.

For `Forelesninger` skulle vi da ha to mappinger klare:
* http://id.loc.gov/authorities/genreForms/gf2014026122.html
* http://li148-205.members.linode.com/humord/nb/page/c01209

Og så blir `Forelesningsnotater` forbeholdt «notater *fra* forelesninger», ikke «notater *til* forelesninger». Om det vil funke i praksis finner vi ut :blush:

(skiller ut Knallforelesninger i en egen diskusjon :))

**Comment by danmichaelo** [comment]
For Kommentarer / Kommentarutgaver, se #39 ;)

**Comment by bibliomari** [comment]
@mittinatten @danmichaelo OBS nå har vi altså TO former: Forelesningsnotater og Forelesninger. Meld fra hvis skillet ikke funker!!

Boka http://ask.bibsys.no/ask/action/show?pid=121691527&kid=biblio har allerede fått formen Forelesningsnotater. Rett eller feil etter ny ordning? @danmichaelo

**Comment by grosyn** [comment]
Sidan NTSF og Humord kun har Forelesninger, flytter eg Forelesningsnotater til Forelesninger, og ber NTSF ha Forelesningsnotater som henvisningsterm.
