### ISSUE TITLE
Lisp / Scheme / Clojure

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#228]
Kan slås sammen? `Lisp BF Scheme BF Clojure`. 

Eller er det dumt at den som søker på Scheme eller Clojure får treff på alle Lisp-bøker? (Vi har allerede `BF Common Lisp` og `BF T-lisp`)

**Comment by bibliomari** [comment]
@knuthe

**Comment by knuthe** [comment]
Hos meg er treffene slik: list-51; scheme-2; clojure-2. treffene på scheme har også lisp. Det kan vel være OK å få alt om man søker på Lisp, men ha muligheten til å avgrense med de to andre. (Altså at jeg setter Lisp på de to Clojure-postene.

**Comment by mittinatten** [comment]
Høres ut som en logisk løsning.

**Comment by mittinatten** [comment]
Har lagt til `Lisp` på våre Clojure-bøker også

**Comment by knuthe** [comment]
Jeg la inn se-også mellom disse tre.
