### ISSUE TITLE
IBM

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#229]
Termen `International business machines` bør enten få akronym IBM eller ha IBM som foretrukket term og nåværende som BF. @knuthe

**Comment by knuthe** [comment]
Enig. Kunne ikke bruke lokar for "International business machines" var akkurat ett tegn for langt for skjemaet. De tre postene ble rettet for hånd til "IBM". Hermed er beskjed gitt til @mittinatten :-)
