### ISSUE TITLE
torsk - utflesking av termen

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#230]
torsk NN torsk EN cod LA Gadus morhua BF skrei BF kysttorsk

**Comment by Hypsibius** [comment]
Eller, burde vi skille mellom ulike torskestammar?

**Comment by danmichaelo** [comment]
Jeg la inn
> NN torsk EN cod LA Gadus morhua BF kysttorsk

men ikke "Skrei" siden den allerede finnes som emneord. @BioHeidi har kanskje noen tanker om hvorvidt vi fortsatt bør ha "Skrei" og "Torsk" som adskilte emneord eller ei?

**Comment by BioHeidi** [comment]
Slå sammen torsk og skrei. Og legg på BF Atlanterhavstorsk.

**Comment by Hypsibius** [comment]
Jess!

**Comment by bibliomari** [comment]
Gjort
