### ISSUE TITLE
Livshistorieteorier

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#231]
Foreslår eintal, ikkje fleirtal: Det finst ulike livhistoriestrategiar, men teorien om kva parametrar som avgjer kva strategi som lønner seg under gitte miljøbetingelsar kan vi vel samle under livshistorieteori (Life history theory), jf wikipedia?
http://no.wikipedia.org/wiki/Livshistorieteori og snl https://snl.no/Livshistorieteori

**Comment by danmichaelo** [comment]
Høres riktig ut :)

**Comment by danmichaelo** [comment]
Bestemt form også mon tro?

**Comment by bibliomari** [comment]
Gjort

**Comment by Hypsibius** [comment]
Blei det eintal eller fleirtal? Eg ville gått for eintal...
