### ISSUE TITLE
To UFOer

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#232]
Fra @superLine :

> vi har to ufoer!
> En med akronomym i parantes og en uten.
> Slår dere sammen "UFO" ?

**Comment by danmichaelo** [comment]
Men det skal kanskje også være ubestemt flertall? Hva med

UFO-er
BF Uidentifiserte flygende objekter
EN Unidentified flying objects
EN Flying saucers

(Siste en inspirasjon fra
http://id.loc.gov/authorities/subjects/sh85139676.html)

**Comment by bibliomari** [comment]
Enig, jeg var ikke helt fornøyd med den engelske varianten på norsk... Også vil jeg selvsagt legge til Flygende tallerkner :)

**Comment by danmichaelo** [comment]
:alien:

**Comment by knuthe** [comment]
Ja "Flygende tallerkener" må med. Det  var mye snakk om det i min barndom.

**Comment by knuthe** [comment]
"Flygende tallerkener" har fått prisen for årets synonym. Jeg har identifisert emneordet og ryddet.
Fjorårets pris for årets emneord gikk til "Vinkelens tredeling".
