### ISSUE TITLE
`Medisinplanter` og `Legeplanter`

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#233]
er vel det samme?

**Comment by Hypsibius** [comment]
Vil eg tru. det er vel dei som pleier å få artsepitetet officinalis? https://en.wikipedia.org/wiki/Officinalis

Men sidan vi brukar plantene til å utvinne medisin, og ikkje til å utvinne legar, vil eg argumentere for Medisinplanter, BF Legeplanter

(Og jada, forstår at det er plantar ein LEGE brukar eller som har LEGEnde effekt, men står ved forslaget)

**Comment by BioHeidi** [comment]
Heheh. Enig.

**Comment by bibliomari** [comment]
Gjort
