### ISSUE TITLE
Røntgen*

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#234]
I samme ånd som #126, kan vi slå sammen `Røntgen`, `Røntgenstråler` og `Røntgenstråling` til

```
Røntgenstråling
BF Røntgenstråler
BF Røntgen
EN X-radiation
EN X-rays
```

**Comment by danmichaelo** [comment]
Og `Røntgenspektra` mener jeg kan slettes, det burde holde med `Røntgenspektroskopi` (@mittinatten får rope ut hvis han er uenig)

**Comment by mittinatten** [comment]
(roper ikke ut)

**Comment by bibliomari** [comment]
Gjort.
