### ISSUE TITLE
Feynmandiagrammer og Feynmanintegraler

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#236]
Bør det ikke være `Feynman-diagrammer` og `Feynman-integraler` ref. http://www.korrekturavdelingen.no/K4EgenFellesAdjektiv.htm ?

**Comment by mittinatten** [comment]
Jeg tenker disser er godt nok innarbeidet for å skrives uten bindestrek.

**Comment by mittinatten** [comment]
mer wienerpølse enn Arsenal-spiller.

**Comment by danmichaelo** [comment]
feynmanintegraler og wienerpølser – vakker kombo :D

Men jo, enig. Det var egentlig bare fordi vi alltid bruker stor forbokstav jeg tenkte det ble riktigere med bindestrek. Men så lenge vi alltid bruker stor forbokstav bør jeg vel egentlig tenke på forbokstavens *case* som ubestemt.. Kanskje jeg heller skal ønske meg mulighet for å lagre termer med liten forbokstav i neste versjon av Sonja :)

**Comment by mittinatten** [comment]
Jeg så nå i lokar-loggen at disse var endret til formene med bindestrek, jeg trodde vi kom frem til at de ikke skulle ha bindestrek? @knuthe

**Comment by knuthe** [comment]
Ja, det var jeg som rettet uten å sjekke diskusjonen. Jeg tar det tilbake.
