### ISSUE TITLE
Ny teknologi

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#238]
Er ikke det litt for vagt til å være nyttig som emneord? Slette?

**Comment by mittinatten** [comment]
ja

**Comment by bibliomari** [comment]
Gjort

**Comment by Hypsibius** [comment]
Alternativt burde ein term som dette sj�lvdestruere etter passande tidsperiode?

H

Sendt fra min Sony Xperia�-smarttelefon


---- Mari Lundevall skrev ----


Gjort

�

**Comment by danmichaelo** [comment]
Ypperlig, når man indekserer kunne man fått spørsmålet: "Hvor lenge forventer du at denne teknologien vil regnes som 'ny teknologi' "?

**Comment by Hypsibius** [comment]
Gitt problema min telefon har med teikn, er den definitivt ikkje lenger 'ny teknologi, i alle fall'  ;-)
