### ISSUE TITLE
Måleteknikk, metrologi, målemetoder

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#239]
`Måleteknikk` brukes i dag som BF på både `Metrologi` og `Målemetoder`, jfr.  #188. Noen innvendinger mot å slå disse sammen?

```
Metrologi
BF Måleteknikk
BF Målemetoder
```

? Evt.

```
Måleteknikk
BF Metrologi
BF Målemetoder
```

siden Måleteknikk sikkert er en mer kjent og intuitiv term enn Metrologi (pluss at det gir mindre sjanse for sammenblanding med "Meteorologi").

@mittinatten @knuthe

**Comment by mittinatten** [comment]
Helt enig i forvekslingsrisikoen med meteorologi. Jeg kunne tenkt meg `Målemetoder` som foretrukket, så unngår vi også forvirring med "måleteknologi". 

Vi har også de stort sett synonyme termene `Instrumenter` og `Instrumentering`. Jeg mener disse kan slås sammen til `Instrumenter` og kanskje da en med `SO Målemetoder`. Så skiller vi tydelig på utstyr og bruk av utstyr.

**Comment by danmichaelo** [comment]
Mja, trenger vi et skille mot måleteknologi? Jeg ville anta at alle disse kunne puttes i båsen "praktisk metrologi":

- Måleteknologi: http://www.uib.no/emne/PHYS328 
- Måleteknikk: https://www.ntnu.no/studier/emner/TFY4185#tab=omEmnet 
- Måleteknikk: http://www.uio.no/studier/emner/matnat/fys/FYS3230/

"Målemetoder" synes jeg høres veldig "laboratoriehåndbok" ut -- *føler* (i mangel av noe bedre) at den skurrer litt som term på mer teoretiske verk.

**Comment by mittinatten** [comment]
Ja, det er nok riktig, i klassifiseringsøyemed har det ikke noe å si.

**Comment by danmichaelo** [comment]
Så da har vi
```
Måleteknikk
BF Metrologi
BF Målemetoder
BF Måleteknologi
SO Instrumenter
```
?

**Comment by danmichaelo** [comment]
Hm, vi har også `Vitenskapelige instrumenter`... Kanskje vi burde legge SO-en dit i stedet. Og legge inn en note på `Instrumenter` om at `Vitenskapelige instrumenter` bør brukes når det er mulig.

**Comment by mittinatten** [comment]
enig i  alt :)

**Comment by danmichaelo** [comment]
Hurra, konsensus oppnådd :D

**Comment by bibliomari** [comment]
Menneh unnskyld hvis jeg dreper festen, men hva med emneordet Mål? Det foresvever meg at det ikke er så lett å skille det fra Metrologi.... @mittinatten @danmichaelo 

Mål 
BF Målteori
EN Measure
EN Measure theory

(og også sorry at jeg ikke har lært meg markup ennå, kan vi ha et seminar @danmichaelo ?)

**Comment by mittinatten** [comment]
Dette må holdes separat, det er et matematisk begrep http://en.wikipedia.org/wiki/Measure_%28mathematics%29

**Comment by mittinatten** [comment]
Muligen at det burde hete `Mål (matematikk)`?

**Comment by danmichaelo** [comment]
Eller kanskje bytte til målteori som foretrukken term? https://snl.no/m%C3%A5lteori 

( @bibliomari : :arrow_down: ikke :arrow_up: ;) Seminar når som helst. Et tips er forresten at du skal kunne trykke på redigeringsblyanten på alle kommentarer, ikke bare dine egne, og dermed se kilden. Det kan være en grei måte å lære på. )

**Comment by mittinatten** [comment]
Ja, jeg tenker målteori er mer presist, det fanger bedre opp det som bøkene faktisk handler om, og en unngår forvirring med andre bruk av ordet mål. 

I samme slengen kan vi også ta `Grupper` og `Gruppeteori`. Og `Ringer` og `Kropper`, disse uten teori. Grupper og gruppeteori kan slås sammen eller så må grupper ha en definisjon (hvis noe ikke-matematisk menes). Ringer og Kropper burde få appendikset `(matematikk)`, tror ikke termene ringteori ok kroppteori er brukt særlig mye. Kanskje flere matematiske termer som har samme problem, vi har jo allerede vært innom `Analyse`.

**Comment by mittinatten** [comment]
Laget en ny sak av dette #274

**Comment by bibliomari** [comment]
Jeg har gjort måleteknikkbiten. SO til Vitenskapelige instrumenter. MEN igjen: Vi har jammen også Måleinstrumenter !!! Kanskje den også vil ha SO?

**Comment by danmichaelo** [comment]
Oi, ja, egentlig mellom alle tre, jeg la inn triangel-SO :) Så at Mål / Målteori også var fikset, så da kan vel saken lukkes? 
(Rydding i Instrumenter / Måleinstrumenter / Vitenskapelige instrumenter er vel noe vi må fremskyve til en vakker dag..)
