### ISSUE TITLE
Legemidler, Medisiner

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#241]
Skilt ut fra #188 . Foreslår å slå sammen `Legemidler` og `Medisiner`. Bente sier seg enig.

```
Legemidler
BF Medisiner
BF Medikamenter
EN Pharmaceutical drugs
EN Medicaments
```
(dropper engelsk medicine siden den er tvetydig..)

**Comment by bibliomari** [comment]
Gjort
