### ISSUE TITLE
Dataprogrammering/Programmering

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#243]
Finnes ingen grunn til å skille på de to termene eller?

**Comment by knuthe** [comment]
Jeg vet ikke om forskjellen kan begrunnes ut fra forskjellen mellom DDC 005.1 og 519.7.

**Comment by mittinatten** [comment]
Godt poeng. Er 519.7-betydningen av termen fremdeles i bruk? Dynamisk og lineær programmering hør jeg om i innimellom, men skjeldent om bare programmering i matematisk betydning. Har aldri forstått forskjellen mellom matematisk programmering og optimering, og lurer på om skillet i Dewey er litt artifisielt?

I hvert fall, hvis vi skal beholde begge betydningene tenker jeg en mer moderne oppdeling er termene `Dataprogrammering` -> `Programmering` og `Programmering` -> `Matematisk programmering`, med en del omklass-problematikk muligens.

**Comment by knuthe** [comment]
Ifølge den forrige matematikkfagreferenten her er dette i bruk. Ikke noe skille mellom matematisk programmering og optimering (altså heltallsprogrammering = heltallsoptimering; stokastisk programmering = stokastisk optimering, osv se MSC 90.50, 90.56, 90.57, 90.58, 90.59, 90.60 i Roald).

Når jeg søker i BIBSYS på "programmering" fra Roald2, så er det litt forskjellig som kommer fram.

**Comment by mittinatten** [comment]
Skal vi da kanskje heller ha

    Matematisk optimering
    BF Matematisk programmering
    SO Programmering

    Programmering
    BF Dataprogrammering
    SO Matematisk optimering

Det blir litt av en ryddejobb å skille ut de som har emne `Programmering` i den matematiske betydningen, men det kanskje uansett er nødvendig?

**Comment by knuthe** [comment]
Bra forslag. jeg retter dataprogrammering til programmering og tar en kikk på de 341 (se nedenfor) og setter matematisk optimering på de få det er aktuelt for.

Her
programmering                             341
programmering : biologi                    5
programmering : brukergrensesnitt   5
programmering : danmark                 1
programmering : Historie                    2
programmering : lærebøker                3
programmering : tabeller                    1

dataprogrammering 4
