### ISSUE TITLE
Steinertrær - eller finnes bare ett? 

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#244]
Vi har emneordet Steinertrær, men når jeg googler finner jeg Steinertreproblemet. Er det riktig med Steinertrær eller må dette stelles litt? @TorgunnKarolineMoe @mittinatten

**Comment by TorgunnKarolineMoe** [comment]
Steinertrær virker i utgangspunktet ok for meg, men vi har steinernettverk også, og det er kanskje en fin tanke å trekke inn steinertreproblemet? Kanskje finner man ett ord for alle disse? Ingen av emneordene er særlig flitting brukt, og mange av bøkene er på UREAL/INF, så jeg overlater beslutningen til Knut.



Hilsen Karoline

________________________________

**Comment by mittinatten** [comment]
Jeg syns og det burde holde med

    Steinertrær
    BF Steinernettverk
    BF Steinertreproblemet
    EN Steiner trees
    EN Steiner networks
    EN Steiner tree problem

**Comment by knuthe** [comment]
Steinernettverk er slått inn under steinertrær med engelsk som foreslått og tre (!) BF.
