### ISSUE TITLE
Fraktalteknologi

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#245]
"Er" dette noe eget eller kan det integreres med et av våre andre emneord: Fraktaler, Fraktalgeometri, Fraktalteori? Jeg har kommet så langt som til å se at Fraktaler kan anvendes i teknologien, men der stopper min ringe forståelse. 

Jeg synes ellers ikke trefflista virker som den rettferdiggjør bruken av emneordet. 

@TorgunnKarolineMoe @mittinatten @danmichaelo

**Comment by danmichaelo** [comment]
Hm, det sier ikke meg noe heller. Hvis betydningen er "Anvendelser av fraktalgeometri i teknologi" virker det ikke som trefflista reflekterer dette særlig bra. Vi kan godt slette denne for min del.

**Comment by mittinatten** [comment]
Det eneste jeg kan tenke meg er teknologi for å fremstille bilder  av fraktaler, det stemmer kanskje litt bedre med trefflisten, men jeg syns ikke det er en særlig relevant term.

**Comment by danmichaelo** [comment]
Det er mulig, ja. Men da sletter vi den?

**Comment by bibliomari** [comment]
Gjort
