### ISSUE TITLE
Lysreaksjoner

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#246]
Kan Lysreaksjoner slettes? Vi har kun ett treff, det kommer fra gamle dagers 691 og det handler om Fotosyntesen (og sikkert lysreaksjoner haha) @BioHeidi @Hypsibius

**Comment by Hypsibius** [comment]
Slett!!!

**Comment by bibliomari** [comment]
Juhu!

**Comment by bibliomari** [comment]
Gjort
