### ISSUE TITLE
Bæredyktighet

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#247]
Slettes. Brukt en gang, likt som Bærekraftig utvikling.

**Comment by mittinatten** [comment]
Legg til som BF på `Bærekraftighet`?

**Comment by bibliomari** [comment]
OK da :)

**Comment by Hypsibius** [comment]
'-ighet' er vel drygt, sjølv på bøkmål? Kva med det enkle 'bærekraft' NN berekraft? Det brukar Wikipedia :-) http://no.wikipedia.org/wiki/B%C3%A6rekraft SLN Brukar bærekraftig utvikling

**Comment by Hypsibius** [comment]
Men vi bør vel ha det som BF-term, gitt at nokon vil søke på det...

**Comment by mittinatten** [comment]
Vi har 

* Bærekraftig forvaltning
* Bærekraftig industri
* Bærekraftig miljøpolitikk
* Bærekraftig skogbruk
* Bærekraftig turisme
* Bærekraftig utnyttelse
* Bærekraftig utvikling
* Bærekraftige naturressurser
* Bærekraftighet

Er enig i at `Bærekraft` høres bedre ut for den siste. Muligens kan noen av de andre slås sammen?

**Comment by Hypsibius** [comment]
Hm, kanskje forvaltning, utnyttelse og naturresurser skulle kunne bi slått saman?

**Comment by bibliomari** [comment]
Jeg har ryddet litt, sikkert rom for mer. Det som gjenstår nå er: 

Bærekraftig forvaltning
Bærekraftig miljøpolitikk
Bærekraftig skogbruk
Bærekraftig utvikling

Dessuten har vi: 

Grønn kjemi
Økoturisme

**Comment by Hypsibius** [comment]
Ser bra ut :-)

**Comment by Hypsibius** [comment]
Men 'Bærekraft' åleine har vi framleis ikkje?

**Comment by Violabibaluba** [comment]
lagt på Bærekraft på Bærekraftig utvikling
