### ISSUE TITLE
Stjernetyper

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#250]
Skilt ut fra #205 :

> Stjerneklasser: `Ae-type`, `B-type`, `Be-type spektra`, `F-type`, `G-type`, `K-type`, `O-type` og `Ob-stjerner`: vi bør vel ha disse på samme form? Hvilken er best, @superLine ? `Ae-stjerner`, `B-stjerner` osv. (ála [Astrotesaurusen](http://www.altbibl.io/astrothesaurus/uat/termrecords/A+stars.html)) eller `Ae-type`, `B-type`...? Og stor 'B' i `OB-stjerner`?

Diskutert med @superLine i dag. Jeg tror vi ble enige om å endre alle til formen `X-stjerner`.

**Comment by bibliomari** [comment]
Gjort
