### ISSUE TITLE
Alginat, alginater, alginsyre

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#251]
@Hypsibius @BioHeidi Kan disse slås sammen? Evt defineres/skilles fra hverandre med f.eks. Se også, hvis det er mer riktig?

**Comment by Hypsibius** [comment]
Sak samma! Aglinat/alginater er vel berre eintalsform/fleirtalsformer. Og skal vi gå for syra eller saltet som foretrukken term? Eg vil ha saltet, mao Alginater!

**Comment by BioHeidi** [comment]
Alginater BF Alginat, Alginsyre, Algininsyre

**Comment by danmichaelo** [comment]
Gjort
