### ISSUE TITLE
Alder, Aldring, Aldersbestemmelse

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#252]
Skilt ut fra #205 :

Trenger vi alle? Min magefølelse er at `Aldersbestemmelse` og kanskje `Aldring` er ok emneord, men at `Alder` er et rart emneord.

@BioHeidi @Hypsibius

**Comment by Hypsibius** [comment]
Einig!

**Comment by BioHeidi** [comment]
Einig!

**Comment by danmichaelo** [comment]
Så da sletter vi `Alder`?

**Comment by BioHeidi** [comment]
Ja. Gjort.
