### ISSUE TITLE
Apoptose = Celledød?

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#254]
Har dere forslag til et bedre norsk ord og evt def for Apoptose? Kan Celledød brukes?

@BioHeidi @Hypsibius

**Comment by mittinatten** [comment]
I følge wikipedia omfatter "programmed cell death" både `Apoptose` og `Autofagi` (og necroptosis).  Basert på trefflistene er begge relevante som emneord. Kanskje med `OT Programmert celledød`?

**Comment by Hypsibius** [comment]
Går for 'programmert celledød' http://nn.wikipedia.org/wiki/Apoptose
