### ISSUE TITLE
A programming language

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#256]
Utskilt fra #205 :

omdøpe til APL? @knuthe (APL har jeg faktisk hørt om, men visste ikke hva det sto for)

**Comment by bibliomari** [comment]
Jeg har omdøpt, men var kanskje litt kjapp @knuthe  (jeg også...). Ser det bra ut nå?

**Comment by knuthe** [comment]
Ser utmerket ut
