### ISSUE TITLE
Skadelige planter/stoffer

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#257]
Utskilt fra #205 : 

- `Skadelige planter` : Skadelig for... oss? Dekkes denne av `Giftige planter` kanskje...? 

-  `Skadelige stoffer` → `Helsefarlige stoffer` ?

@BioHeidi @Hypsibius

**Comment by Hypsibius** [comment]
Hm, tenkjer at Skadelige planter dekkjer breiare enn Giftige planter. Kan tenkje meg fleire måtar dei kan vere skadelege på enn kun giftigheit. Kva med Skadelige planter, BF Giftige planter?

Enig med nummer to der, men kva er skilnaden mellom Helsefarlige stoffer og Helsefarlige kjemikalier?

**Comment by danmichaelo** [comment]
> Hm, tenkjer at Skadelige planter dekkjer breiare enn Giftige planter. Kan tenkje meg fleire måtar dei kan vere skadelege på enn kun giftigheit. Kva med Skadelige planter, BF Giftige planter?

Høres fint ut!

> Enig med nummer to der, men kva er skilnaden mellom Helsefarlige stoffer og Helsefarlige kjemikalier?

Godt spørsmål! Vi kan gjerne slå de sammen for min del :)

**Comment by Hypsibius** [comment]
Då stemmer eg for det!

**Comment by bibliomari** [comment]
Gjort.

**Comment by BioHeidi** [comment]
Jeg gjenåpner denne, fordi jeg som toksikolog gjerne vil ha Giftige planter BF Skadelige planter. Hvis vi har tilfeller av skadelige planter som ikke er giftige kan jeg prøve å sette noe annet på dem (også), men jeg mistenker at litteraturen her gjelder toksisitet.

Helsefarlige stoffer og kjemikalier er det samme, den protesterer jeg ikke på.

**Comment by bibliomari** [comment]
Gjort.
