### ISSUE TITLE
Adp-ribosyltransferase

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#258]
Skilt ut fra #205 :

`Adp-ribosyltransferase` → `ADP-ribosyltransferaser`

Stemmer at det skal være fl.tall? @BioHeidi @Hypsibius

**Comment by Hypsibius** [comment]
Trudde det, men?

**Comment by danmichaelo** [comment]
Men..?

**Comment by BioHeidi** [comment]
Ja, det finnes flere av disse enzymene. Noen morsomme bakterietoksiner, og f.eks. PARPene som involverer seg med prorgammert celledød og slikt (jfr annen tråd) :)

**Comment by bibliomari** [comment]
Gjort
