### ISSUE TITLE
Stamceller/Celledifferensiering

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#260]
@BioHeidi @Hypsibius Bør disse ha se også- mellom seg? Eller på annet vis forklares (iallfall det siste ordet)?

**Comment by BioHeidi** [comment]
Synes egentlig ikke de trenger "se også". Stamceller er en av tre typer celler (de andre to er somatiske og kjønnsceller), mens celledifferensiering er en prosess. Kan forsøke med denne definisjonen på celledifferensiering fra Store medisinske leksikon: "Celledifferensiering, prosess som en celletype gjennomgår i utviklingen mot en spesialisert celletype". 

https://sml.snl.no/celledifferensiering
