### ISSUE TITLE
Matematikkultur 

### ISSUE THREAD

**Issue by TorgunnKarolineMoe** [realfagstermer/realfagstermer#261]
Trenger "dette" emneordet (eller noe liknende) for å beskrive en bok som handler om kulturen i matematikk og blant matematikere. Det er ingen biografi el, men et forsøk på å beskrive yrkesgruppen og dens tradisjoner. Noen innspill?

**Comment by mittinatten** [comment]
Kanskje bedre å opprette "fagkultur" eller noe lignende og lage en streng?

**Comment by bibliomari** [comment]
Fint ønske, hvilken bok er eksemplet ditt, @torgunnkarolinemoe ?

**Comment by TorgunnKarolineMoe** [comment]
Mathematics without aplologies.


http://press.princeton.edu/titles/10317.html


-Karoline

________________________________

**Comment by Violabibaluba** [comment]
Vi har omsider opprettet "Fagkultur" med strengen "Fagkultur - Matematikk" - Matematikkultur er lagt inn som se hit-henvisning slik at dette også er søkbart.
