### ISSUE TITLE
Knallforelesninger

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#264]
Skilt ut fra #226 

@mittinatten 13. mai:

> Når jeg skulle søke opp formen i Roald for å legge til på eksemplet over fant jeg og termen `Knallforelesninger`. Tenker at denne kan legges inn som BF på `Presentasjonsteknikk`.

@bibliomari 3. juni: 

> Knallforelesninger går over som BF til ny form Populærforelesninger, som også kan romme ted talks og andre fancy former.

Mm.. eller kanskje heller `Kjemiske eksperimenter`? (som kanskje kunne vært `Kjemieksperimenter`?) Jeg har pleid å bruke `Fysikkeksperimenter` på bøker om demonstrasjonsforsøk i fysikk.

**Comment by bibliomari** [comment]
Ja, jeg er enig med deg her, @danmichaelo. Og det løser også problemet som oppstod nå da jeg skulle lage Populærforelesninger og tenkte HJELP, er dette enda et formord??
