### ISSUE TITLE
Hav: Svartehavet

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#265]
Oppdaga denne strengen då eg søkte etter stadterm Svartehavet. 

Er ikkje det ein temmeleg overflødig streng?

**Comment by danmichaelo** [comment]
Hehe, jo... Er det egentlig noen av hav-strengene vi trenger å beholde? Kanskje `Hav : Oppslagsverk`?

```
Hav
: Aden
: Antarktis
: Arktis
: Atlanterhavet
: Atlas
: Baltiske Hav
: Barentshavet
: Barentsregionen
: Bestemmelseslitteratur
: Bibliografier
: Ekskursjonsguider
: Finland
: Floraer
: Håndbøker
: Indiske Hav
: Karahavet
: Karibiske Hav
: Kart
: Kaspiske Hav
: Konferanser
: Madagaskar
: Maldivene
: Mombasa
: Nordsjøen
: Norge
: Oppslagsverk
: Russland
: Rødehavet
: Sri Lanka
: Stillehavet
: Svartehavet
```

**Comment by Hypsibius** [comment]
Eventuelt behalde desse?

: Atlas
: Bestemmelseslitteratur
: Bibliografier
: Ekskursjonsguider
: Floraer
: Håndbøker
: Kart
: Konferanser
: Oppslagsverk

**Comment by Hypsibius** [comment]
Skjønt, dei fleste gir meir meining om dei blir kombinert med snevrare term, evt havområde, el oseanografi, marinbiologi etc...

**Comment by bibliomari** [comment]
Jeg har kastet ut en del. Kanskje litt mange, kanskje litt få...?
