### ISSUE TITLE
Klekkerier

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#266]
Ønskjer termen klekkerier NN klekkeri EN hatcheries

Belegg: http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS861079922&vid=UBB

**Comment by danmichaelo** [comment]
Skulle vi avgrenset til "Fiskeklekkerier" for å unngå sammenblanding med kylling?

**Comment by Hypsibius** [comment]
Eg trur ikkje det er lurt, for eg kan ikkje forestille meg at fiskerifolk vil søke på det ordet. I så fall burde vi heller bruke klekkeri (akvakultur) og klekkeri (fjørfe)

**Comment by bibliomari** [comment]
Men gjør det noe om Klekkerier evt brukes for kyllinger også? Klekkeri er klekkeri...? Eller er jeg fredagssløv? Jeg oppretter uansett Klekkerier som ønsket, @Hypsibius , så kan du bruke det mens vi funderer på om vi burde spesifisere det.

**Comment by bibliomari** [comment]
Hm, vi hadde termen Klekking, som selvsagt er brukt på en bok om fugl og en om fisk. Jeg satte Se også mellom Klekking og Klekkerier.

**Comment by Hypsibius** [comment]
Flott, @bibliomari! Tenkte som deg, at det gjer ingenting å få treff frå både hønseri og akvakultur. Men er muligens også fredagssløv... Du får evt stramme oss opp, @BioHeidi !

**Comment by danmichaelo** [comment]
Sikkert helt greit slik, men da venter vi på @BioHeidi s øyne får vi lukker saken, da

**Comment by BioHeidi** [comment]
Godkjentstempel.

**Comment by danmichaelo** [comment]
@Hypsibius Kan du prøve å legge på `Klekkerier` på eksempelposten? (For å teste emnesøket er jeg litt på jakt etter noen eksempler på poster med Realfagstermer uten UBO-beholdning.)

**Comment by mittinatten** [comment]
Hege er ikke på jobb denne uken, men jeg har lagt til termen
