### ISSUE TITLE
Lomre

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#267]
Foreslår ny term Lomre NN Lomre En Lemon Sole LA Microstomus kitt

Belegg: http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS873024850&vid=UBB

**Comment by Hypsibius** [comment]
SLN: https://snl.no/lomre

**Comment by danmichaelo** [comment]
Oppretta. Er det ok å legge til "bergflyndre" og "oterflyndre" som alternative termer? (tatt fra "også kjent som" på SNL)

**Comment by danmichaelo** [comment]
og vil du evt. ha de på nynorsk også? ;)

**Comment by Hypsibius** [comment]
http://www.nob-ordbok.uio.no/perl/ordbok.cgi?OPP=+lomre&nynorsk=+&ordbok=nynorsk, og veldig fint med alternative artsnamn på BF!

**Comment by danmichaelo** [comment]
Jupp, jeg la de inn
