### ISSUE TITLE
Benguelastrømmen

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#269]
Foreslår ny term: Benguelastrømmen NN Benguelastraumen EN (The) Benguela current 

http://en.wikipedia.org/wiki/Benguela_Current

https://snl.no/Benguelastr%C3%B8mmen

Belegg http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS02080251x&vid=UBB

**Comment by danmichaelo** [comment]
Oppretta
