### ISSUE TITLE
Rspråk

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#27]
Vi har termen `Rspråk` om [R](https://no.wikipedia.org/wiki/R_%28programmeringsspr%C3%A5k%29). Jeg synes det ser veldig rart ut, (programmerings)språk er vel en kvalifikator i denne sammenhengen?

Og så ser det ut som vi har to ulike praksiser i sving. Mens [denne boka](http://ask.bibsys.no/ask/action/show?pid=11234139x&kid=biblio) er merket "Statistisk programvare", er [denne](http://ask.bibsys.no/ask/action/show?pid=120123649&kid=biblio) merket "Rspråk". Hvordan løser vi dette, @knuthe ?

**Comment by grosyn** [comment]
Me har no starta med "X (programmeringsspråk)", så då lukkar eg denne.
