### ISSUE TITLE
Vandringer og migrasjon

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#270]
Hadde ikkje vi ein eigen label for 'samanslåing'? Ikkje?

Nuvel: 

Oppdaga at vi har ein term 'vandringer' (eksempelvis: vandringer: serengeti)  og ein annan 'migrasjon' (BF dyretrekk)

Foreslår å slå desse saman til vandringer, BF migrasjoner, dyretrekk

**Comment by bibliomari** [comment]
Ja, det ser ut som Vandringer kan inngå med Migrasjon. Men foretrekker dere Vandringer som term, BF Migrasjon, altså? Siden dette brukes både om fugl og fisk, gir Vandringer meg ikke de rette assosiasjonene. Men @BioHeidi og @Hypsibius har siste faglige ord her, selvsagt :)

**Comment by bibliomari** [comment]
Se også #437 , disse bør løses i sammenheng. OG kan/bør vi ha SE OGSÅ Innvandring?

**Comment by Hypsibius** [comment]
Føretrekk 'vandringer' som hovudterm. Her i vest snakkar vi eksempelvis om vertikalvandringar, ikkje vertikalmigrasjonar

**Comment by BioHeidi** [comment]
Mens jeg foretrekker Migrasjon BF Vandringer. Dette er nok fagavhengig, og begge deler blir forstått.

Og så synes jeg vi skal ha Migrasjon BF Innvandring, og ikke innvandring som egen term. Den kan humsam få ta seg av. Det som står i #437 består.

**Comment by Hypsibius** [comment]
Ok då, skal ikkje vere sååå vanskeleg. Migrasjon it is ;-)

**Comment by danmichaelo** [comment]
Sånn, da har vi

```
Migrasjon
BF Vandringer
BF Innvandring
osv...
```
