### ISSUE TITLE
Påvekstorganismer

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#272]
Foreslår ny term Påvekstorganismer NN Påvekstorganismar EN fouling organisms. 

Til samanlikning med termane epifytt (som finst som realfagsterm, men som er avgrensa til det som veks på plantar), epizoont (påvekst på dyr, manglar som realfagsterm) og epibiont (påvekst på alle slags organismar, manglar i RT). Desse kan likevel ikkje nyttast om påvekst på båtar og andre strukturar. Påvekst brukast ved UiB, også i artsdatabanken: 

http://www.artsdatabanken.no/NiN/Naturtype/475

Belegg: http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS940044048&vid=UBB

**Comment by BioHeidi** [comment]
Kan vi bruke termen "Påvekst", som da omhandler både fenomenet med påvekst, og selve organismene? Kan evt ha BF Påvekstorganismer. Eller vil du helst ha de separat?

**Comment by Hypsibius** [comment]
Heilt fint for meg. Tenkte berre ikkje så langt...

**Comment by BioHeidi** [comment]
Gjort
