### ISSUE TITLE
Konforme avbildinger

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#273]
Vi har `Kvasikonforme avbildinger`, men trenger også `Konforme avbildinger EN Conformal mappings`.

belegg: http://ask.bibsys.no/ask/action/show?kid=biblio&cmd=reload&pid=932109098

**Comment by mittinatten** [comment]
eller avbildNinger kanskje

**Comment by danmichaelo** [comment]
Tror det skal være entall (@bibliomari ?). Jeg la inn
```
Konform avbildning
NN Konform avbilding
EN Conformal mapping
SO Kvasikonforme avbildninger
```

http://id.loc.gov/authorities/subjects/sh85031060.html
