### ISSUE TITLE
værvarsler BF værvarsling

### ISSUE THREAD

**Issue by mzyg** [realfagstermer/realfagstermer#275]
Vi har værvarsler og værvarsling som 2 termer. Forskjellen er marginal..
Kan gjerne tas sammen
Værvarsler
BF værvarsling
EN weather forecasting
EN weather forecast

(03d018118)

**Comment by danmichaelo** [comment]
Enig! Men er det ikke bedre med `Værvarsling` som foretrukket term? Med `Værvarsler` tenker jeg på de konkrete varslene (prognosene)

**Comment by mzyg** [comment]
Værvarsling som foretrukket term er i hvert fall bedre, det er riktig!
Værvarsler er prognosen og værvarsling kan vel være prognosen og handlingen for å få prognosen...

**Comment by danmichaelo** [comment]
Fint, da er vi enige

**Comment by bibliomari** [comment]
Slått sammen, men deretter fjernet Værvarsler. Det passet ikke på det ene dokumentet det var brukt på, og da foretrekker jeg ikke å blande prosess med resultatet av prosessen når jeg kan slippe :)
