### ISSUE TITLE
(gen)sekvensering

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#276]
Kunne vi fått med gensekvensering som BF på `Sekvensering`? Og ryddet vekk strengen `Genetikk : sekvensanalyse`, siden `Sekvensanalyse` implisitt betyr genetikk (kanskje legge til `BF Gensekvensanalys` for å gjøre det tydeligere, alternativt lage en definisjon) . Fra trefflistene ser det ikke ut som termene er brukt for noe annet enn genetikk.

**Comment by mittinatten** [comment]
Og ja, burde sikker også ha `Sekvensering BF DNA-sekvensering`.

**Comment by Hypsibius** [comment]
Enig!

**Comment by bibliomari** [comment]
Gjort
