### ISSUE TITLE
Økologisk fragmentering

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#277]
Det ein meinar her er habitatfragmentering, ikkje sant? Foreslår å endre, til habitatfragmentering, BF økologisk fragmentering NN habitatfragmentering EN habitat fragmentation

JF: http://www.biologforeningen.org/enbiolog/topic.asp?TOPIC_ID=17395

https://en.wikipedia.org/wiki/Habitat_fragmentation

NB: ser at artsdatabanken brukar formen habitatSfragmentering (med genitivs-s). Forma gir likevel berre 40 treff i google, medan den andre gir 2400 treff....

**Comment by BioHeidi** [comment]
Einig!

**Comment by bibliomari** [comment]
Gjort.
