### ISSUE TITLE
Den norske kyststrømmen

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#278]
Er det eg som søker heilt tussete, har den eit synonym eg ikkje kjenner eller manglar den norske kyststrømmen som term?

Foreslår:

Den norske kyststrømmen NN Den norske kyststraumen EN The Norwegian Coastal Current

Stadterm, om no golfstraumen er det. Men det synest kontraintuitivt...

http://www.imr.no/temasider/kyst_og_fjord/den_norske_kyststrommen/nb-no

Belegg: http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS811171957&vid=UBB

**Comment by danmichaelo** [comment]
Vi har vel mindre havforskning her østpå :) Morsomt nok var det jo også artikkel om strømmen på nynorsk Wikipedia, men ikke bokmål.. (kanskje jeg skal teste det nye oversettelsesverktøyet på Wikipedia! )

Jeg oppretta den som stedterm, jeg. Synes óg det virket litt rart, men den har vel en *noenlunde* fast geografisk avgrensning (med fuzzy grenser), og det ser ut som LC også har strømmer som geografiske emneord.
