### ISSUE TITLE
Ekstremal grafteori

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#280]
Foreslår termen `Ekstremal grafteori EN Extremal graph theory`.

Belegg: https://bora.uib.no/handle/1956/9951

Wiki: https://en.wikipedia.org/wiki/Extremal_graph_theory

**Comment by bibliomari** [comment]
Opprettet. Dere mener alvor med "ekstremal grafteori", ikke ekstrem, ja? 

SO Grafteori, SO Algebraisk grafteori? @mittinatten @danmichaelo

**Comment by mittinatten** [comment]
Ja, det høres litt rart ut, men det er det ordet som brukes. Usikker på om vi trenger SO?

**Comment by danmichaelo** [comment]
(Digresjon: Gratulerer med Dspace 5 forresten – jeg så plutselig at det var en RDF-lenke i venstremargen, men den ga 500 og 403 på én gang :laughing: @tarjelavik ?)

**Comment by tarjelavik** [comment]
(Takker! Det blir fikset i morgen. Må redeploy'e med riktig endpoint og så kjøre rdf-genereringen.)

**Comment by danmichaelo** [comment]
( :+1: )

Men ellers… :) Jeg har heller ikke noen sterk mening om SO eller ikke her. Ekstremal grafeori ~ Grafteori har vel egentlig et hierarkisk forhold, men vi kan jo bruke SO inntil videre

**Comment by danmichaelo** [comment]
( @tarjelavik : Men ingen emneord i RDF-representasjonen :sob: Noen ideer om hvordan det kan bli lagt til? Det hadde vært supertkult å få inn URI-ene våre )

**Comment by tarjelavik** [comment]
(La til mapping i går. Kommer etter neste redeploy, i morgen kanskje?)

**Comment by danmichaelo** [comment]
(Wow, virker som «i morgen» er svaret på alt jeg spør om – ting skjer kjapt i Bergen :) Da jeg spurte når Duo skal oppgraderes til DSpace 5.x va svaret «ikke i år»)

**Comment by tarjelavik** [comment]
(bare "manjana, manjana" i Bergen. Må nok si neste uke på denne, hehe. Til DUO's forsvar er den tettere integrert i "stuff" enn vi)

**Comment by danmichaelo** [comment]
(Jada, og integrasjonene er visst ikke lokalt utviklet, så da er det sikkert litt mer styr)

**Comment by tarjelavik** [comment]
(ok, jeg gir opp. ikke pokker om dspace vil konvertere realfagsterm til rdf. tror det er noe med rdfizer og dspace metadataschemas.)

**Comment by danmichaelo** [comment]
(jaiks, så kjipt! Det skulle være noe sånt, sant?
```turtle
:rtURI
  dm:metadataName "noa.realfagsterm";
  dm:condition "^http://data.ub.uio.no/.+" ;
  dm:creates [
    dm:subject dm:DSpaceObjectIRI ;
    dm:predicate dcterms:subject ;
    dm:object [
      a dm:ResourceGenerator ;
      dm:pattern "$DSpaceValue" ;
    ];
  ];
  .
```
Og så kommer det bare ikke noe ut av kværnen?)

**Comment by danmichaelo** [comment]
(lukker saken siden vi ikke lenger snakker om ekstremal grafteori, men det er fortsatt lov å fortsette parentes-diskusjonen :))
