### ISSUE TITLE
Poster med både ferdig diskutert og rydding

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#281]
Hvordan holder vi i de postene som er merket både ferdig diskutert og rydding - kan de som rydder fjerne ryddemerkelappen når ryddingen er gjort, f.eks.? Jeg er usikker på om jeg skal utføre eller vente.

**Comment by danmichaelo** [comment]
Jeg har egentlig ikke hatt noe klart bilde av når `rydding` skal brukes. Har tenkt på den litt som "rydding i eksisterende emneord, det meste som ikke er `nytermforslag`", men da blir den egentlig veldig overflødig.

Tenker du at `rydding` (kan) brukes i tilfeller der det trengs manuell rydding i katalogposter? Det er sikkert ingen dum idé. Da kunne vi kanskje omdøpt den til `trenger-katalogrydding` eller noe sånt?

**Comment by Hypsibius** [comment]
Hm, har brukt det som @danmichaelo . Og savnar evt ein eigen merkelapp for samanslåing...

**Comment by danmichaelo** [comment]
@Hypsibius Sjekk om du ikke kan opprette den her: https://github.com/realfagstermer/realfagstermer/labels

**Comment by Hypsibius** [comment]
Då gjorde eg det :-)

**Comment by danmichaelo** [comment]
Jeg omdøpte like godt "rydding" til "trenger katalogrydding"

**Comment by BioHeidi** [comment]
Jeg har brukt den som label når jeg trenger å rydde i katalogposter før en evt sammenslåing og sletting av emneord, så jeg vil gjerne beholde den sånn. Jeg har prøvd å være "flink" til å rydde den vekk når jeg er ferdig å rydde. Men "ferdig" er veldig relativt, så bare mas på meg om det ser ut som om noe blir liggende.

**Comment by danmichaelo** [comment]
> Jeg har brukt den som label når jeg trenger å rydde i katalogposter før en evt sammenslåing og sletting av emneord, så jeg vil gjerne beholde den sånn.

Da er jo det nye navnet perfekt!
