### ISSUE TITLE
Slå sammen Ekteskap og Ektefeller ?

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#284]
Holder sikkert med Ektefeller?

http://katapi.biblionaut.net/documents?q=real:Ektefeller&show=sh
http://katapi.biblionaut.net/documents?q=real:Ekteskap&show=sh

**Comment by bibliomari** [comment]
Sorry ass, men jeg har ikke noe lyst til å slå det sammen. Men STRYKE ekteskap, det er jeg med på.

**Comment by bibliomari** [comment]
*sa hun bittert*

**Comment by danmichaelo** [comment]
Knis.. Stryking er er helt greit :)
