### ISSUE TITLE
Foreslår ny(e) term(ar) Flerbestandsmodellering, Flerbestandsforvaltning

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#286]
Flerbestandsmodellering gir ~1000 treff i Google, dog kun tre i Oria (alle bib). 

Grunnlag: http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS981213685&vid=UBB

Litt usikker på om vi også burde ha Flerbestandsforvaltning (~600 treff i google, 35 i Oria, alle bib). Begge synest relevante for dokumentet eg sit med.

**Comment by BioHeidi** [comment]
Multispecies! Det har jeg jobbet litt med i mikro- og mesokosmos-skala. Men vi bør vel skille mellom flerbestands- og flerarts-.
Vi kan godt ha både modellering og forvaltning (management), og det er sikkert fler termer som kan bli aktuelle senere.
Vil det være hensiktsmessig og forståelig å bruke Flerbestandssystemer : Modellering, Flerbestandssystemer : Forvaltning ? Eller vil det være dumt siden begrepene som ett ord er innarbeidet allerede. Det var det med å kunne ha BF-termer på strenger igjen, da.

**Comment by Hypsibius** [comment]
Ja, altså, trur 'flerbestandsmodellering' er innarbeidd term, typ på havforskinga. Då vil ikkje folk søke etter 'flerbestandssystemer', sjølv om det kunne vere greitt med ein vidare term...

**Comment by bibliomari** [comment]
Flerbestandsmodellering og -forvaltning er opprettet. Ville dere ha flere? @BioHeidi @Hypsibius

**Comment by BioHeidi** [comment]
Ikke flere foreløpig herfra.

**Comment by Hypsibius** [comment]
Nei, kjem tilbake om eg treng fleire :-)
