### ISSUE TITLE
Kalkflagellater

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#287]
Foreslår Kalkflagellater (som i SNL https://snl.no/kalkflagellater) BF Coccolithophorider LA   Coccolithophorida (jf ITIS). Ikkje heller her er det samsvar mellom SNL og ITIS, trass at Throndsen er artikkelforfattar i SLN. Dog er denne artikkelen gamal. 

Vi bør gjerne sjå denne i samanheng med ein innførsel vi alt har, kokkolitter BF coccolitter. Dette tilseier gjerne at vi bør legge til BF 'kokkolithophorider' i termen over?

**Comment by danmichaelo** [comment]
kokkoliko?

La inn

```
Kalkflagellater
NN Kalkflagellater

BF Coccolithophorider, Kokkolithophorider
DEF Klasse av encellede alger
EN Coccolithophores
LA Coccolithophorida
```

Ok?

**Comment by Hypsibius** [comment]
Så lenge det ikkje er kokkelimonke. Ser bra ut!

**Comment by BioHeidi** [comment]
Åpner igjen for å spørre om det er greit å si Kalkflagellater BF Kokkolitter. Kokkolittene er vel bare "skillet" til kalkflagellatene.

**Comment by Hypsibius** [comment]
Tenketenke. Forsåvidt rett, kva får det å seie i geofag? Sedimentering? Er geologane einige? @jw-geo ?

**Comment by jw-geo** [comment]
Kokkoliter kan være bergartsdannende i kalkstein, så det er kanksje viktig å skille mellom organismen og Kokkolitter som bestanddel av sedimenter. Derfor ville jeg beholde Kokkolitter som term, gjerne med SO.

**Comment by Hypsibius** [comment]
Tenkte det kanskje kunne vere sånn. Det er greit for meg å behalde begge

**Comment by BioHeidi** [comment]
Ok, vi beholder begge, men kan dere se på trefflistene om det er noe som må ryddes? Og se om definisjonene er ok?

**Comment by Hypsibius** [comment]
Ana (min vikar & phytoplanktonbiolog) og eg er ikkje heilt nøgde med definisjonane av kokkolottar: Forelsår i staden ei utviding (inspirert av SNL) 

Mikroskopiske, skiveformete kalkplater, ca. 1–30 μm i diameter, dannet som skallplater av 
planktoniske kalkflagellatar. Disse er en bergartsdannende bestanddel i kalkstein/kalksediment

**Comment by BioHeidi** [comment]
Da er det oppdatert definisjon.
