### ISSUE TITLE
Stell, evt røkt. 

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#288]
Vi har birøkt, og vi har viltstell, samt akvakultur og husdyrrelaterte termar som dekkjer stell av husdyr. Men eg finn ingen term eg kan bruke for stell av laboratoriedyr i samband med eksperiment/undersøkingar? Eller har eg oversett noko? Foreslår 'Røkt' BF stell. 

http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS782038190&vid=UBB

**Comment by BioHeidi** [comment]
Ja, i labdyr-kategoriene har vi Laboratoriedyr, Forsøksdyr, Dyreforsøk, Laboratoriemus, Laboratorierotter.
Av stell/røkt-relaterte som er brukt med disse har vi Dyrehold, Dyreoppdrett, Dyrevelferd.
Vi har også Modellorganismer.
Vi bør vel prøve å samle noen av disse, f.eks si Forsøksdyr BF Laboratoriedyr, og legge mus og rotter i streng med dette istedet for å ha egne emneord.
Kan det da evt brukes en streng Forsøksdyr : Dyrehold ?

**Comment by bibliomari** [comment]
Jeg har slått sammen Forsøksdyr og Laboratoriedyr, og tatt inn Laboratorierotter og -mus (laget strenger av disse på postene, men fikk ikke lagret strenger i Sonja i dag). 

Røkt: Jeg la det som en BF på Dyrehold, men dersom dere er uenige, si fra! Mulig Dyrehold er mye mer omfattende enn jeg tenker? @Hypsibius @BioHeidi

**Comment by Hypsibius** [comment]
Tenkjer at Dyrehold burde holde

**Comment by BioHeidi** [comment]
Enig.
