### ISSUE TITLE
Kveis

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#289]
Foreslår ny term: Kveis LA Anisakis (og minst ei slekt til)

Alternativt kan vi legge det inn som ein BF-term under Parasittiske nematoder. Sidan det er ei ikkje-taksonomisk (eller i det minste polyfyletisk) gruppering, er kanskje det siste like greitt?

Trudde eg hadde meldt inn denne før, men kunne ikkje finne den igjen

**Comment by Hypsibius** [comment]
PS: aktuelt dokument er http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS150669488&vid=UBB

**Comment by bibliomari** [comment]
Jeg har lagt inn Kveis som BF på Parasittiske nematoder, ikke gjort noe med LA. @BioHeidi får gjerne overstyre :)

**Comment by BioHeidi** [comment]
Godkjentstempel.
