### ISSUE TITLE
Toktrapporter (formterm)

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#290]
Foreslår å legge til formterm Toktrapporter

Døme: http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS86414024x&vid=UBB

**Comment by bibliomari** [comment]
@BioHeidi

**Comment by bibliomari** [comment]
Har lagt til formtermen. Forslag til engelsk navn, @Hypsibius eller @BioHeidi ?

**Comment by Hypsibius** [comment]
Må eg gnage litt på. Kan sjekke med meir røynde folk enn meg. Eller, kanskje @mzyg veit?
