### ISSUE TITLE
Foreslår ny term: dykkefysiologi

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#293]
Dykkefysiologi BF dykkemedisin BF barofysiologi BF dykkermedisin BF dykkerfysiologi EN Underwater diving physiology

NUTEC, som er leiande i landet og fysiologane ved UiB brukar 'dykkefysiologi'. http://www.uib.no/personer/Ivar.Ronnestad#

Eg ser at dykkermedisin og dykkerfysiologi faktisk er meir i bruk, men foretrekk likevel denne formen. Den kan ein argumentere for omfattar ikkje-menneskelege luftpustande dykkarar, som kval, sel, pingvinar etc. Ved å bruke dykkefysiologi som hovudterm, inkluderer vi den generelle kunnskapen om utfordringar og tilpasningar undervatn, og begrensar oss ikkje til menneskeleg fokus ;-)

Døme: http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS093691114&vid=UBB

**Comment by danmichaelo** [comment]
Gjort!

Kortet ned EN til "Diving physiology", og la inn "NN Dykkefysiologi"
