### ISSUE TITLE
Foreslår ny term: vitenskaplig dykking

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#294]
Foreslår: Vitenskaplig dykking NN Vitskapleg dykking 

For bruk av dykking for fotografering/dokumentering, registrering, oppsetting av eksperiment etc under vatn. 

Frå brosjyre ved UNIS: "Vitenskapelig dykking, er knyttet til oppgaver som observasjon, dokumentasjon (video, foto), innsamling av materiale, analyseringer og operasjon av ulikt måleutstyr. Konstruksjon eller bruk av tyngre verktøy faller ikke under vår oppfatning av begrepet vitenskapelig dykking. 
Vitenskapelig dykking innebærer at fagkunnskap og viten anvendes under vann, og dermed 
er det også gitt at en del undervannsoppgaver må utføres av personell med vitenskapelig 
kompetanse. "

Døme: http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS921166486&vid=UBB

**Comment by Hypsibius** [comment]
![vitdykk](https://cloud.githubusercontent.com/assets/9350370/8821622/7b9bf7a2-305f-11e5-859f-0975c3baa4eb.JPG)

Sånn, omtrent

**Comment by danmichaelo** [comment]
Hoho, vi burde ha med illustrasjoner i Realfagstermer egentlig! (Og med avansert bildetolkingsprogramvare kunne vi utført søk basert på det brukeren tegnet :D)

Jeg oppretta den jeg. Med engelsk scientific diving, http://www.si.edu/dive/

**Comment by Hypsibius** [comment]
Sant? Overlet det til dokke å løyse det teiknesøket, i mellomtida er eg happy med å ha fått termen :-)
