### ISSUE TITLE
Slå saman dyreplankton og zooplankton

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#295]
Får litt dårleg samvit av å dumpe så mange saker på dokke til ferien er over, meeen: 
Vi kan ikkje ha både zooplanton og dyreplankton! IOM at vi har gått for planteplankton foreslår eg: 

dyreplankton BF zooplankton

**Comment by bibliomari** [comment]
Og jeg har dårlig samvittighet for min lange Sonjaferie!!
