### ISSUE TITLE
Havenes optikk

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#296]
Skilt ut fra #271 : @Hypsibius  [14.juli](https://github.com/realfagstermer/realfagstermer/issues/271#issuecomment-121205835)

> Gjer meg litt vanskeleg her, men vi bør gjerne ha ein tilsvarande gjennomgang av 'havenes optikk'. som eg heller ikkje synest er ein glimrande term?

**Comment by danmichaelo** [comment]
Enig. Hydrooptikk er vel heller ikke noen god term, så da blir det `Undervannsoptikk`? EN `Underwater optics` og `Ocean optics`. Hva blir det på nynorsk? `Undervassoptikk`? Noe mer?

/ @Hypsibius @mittinatten

**Comment by Hypsibius** [comment]
Om det blir 'undervannsoptikk, går eg for undervassoptikk på nynorsk.

**Comment by danmichaelo** [comment]
Da ble det `Undervannsoptikk EN Underwater optics EN Ocean optics NN Undervassoptikk`

**Comment by Hypsibius** [comment]
Kan eg gjenopne denne, tru? Treng vi både optisk oseanografi og undervannsoptikk?

![image](https://user-images.githubusercontent.com/9350370/46133414-b4187f80-c240-11e8-8703-b8364892a31a.png)

![image](https://user-images.githubusercontent.com/9350370/46133429-be3a7e00-c240-11e8-90e1-be5d5edfdd92.png)


![image](https://user-images.githubusercontent.com/9350370/46133473-e1652d80-c240-11e8-95c0-9db577350288.png)

**Comment by danmichaelo** [comment]
Hm, ja, dette ser ut til å være innenfor samme felt:

* "The subdiscipline of *ocean optics* (sometimes called *marine* or *hydrologic optics*) concerns the
study of light and its propagation through the ocean, whereas *bio-optical oceanography* or *bio-optics* connotes biological effects on optical properties and vice versa" ([Optical oceanography: Recent advances and future directions using global remote sensing and in situ observations](https://dx.doi.org/https://doi.org/10.1029/2003RG000148))

Vi trenger vel ikke være så fininndelte, men vi kan jo ta med termene. Ser dette ok ut?

```
id= REAL009762
te= Optisk oseanografi
bf= Marin optikk
bf= Bio-optisk oseanografi
nn= Optisk oseanografi
nn= Marin optikk
nn= Bio-optisk oseanografi
en= Optical oceanography
en= Ocean optics
en= Marine optics
en= Hydrologic optics
en= Bio-optical oceanography
```

Fjernet undervannsoptikk, det så brått så feil ut..
