### ISSUE TITLE
Antropiske prinsipp

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#298]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL007768?view=nn&q=has:editorialNote,graph:local)

> nb burde heller vera "Ant. prinsipper"?

Hm, nei, dette skal vel være entall? Men kanskje vi skulle slengt på "Det" foran? 
(Kanskje vi skulle hatt et eget sorteringsfelt i Sonja også)

**Comment by mittinatten** [comment]
Enig, det finnes bare et antropisk prinsipp (vel?), og kanskje tydeligst med "Det".

**Comment by bibliomari** [comment]
OK
