### ISSUE TITLE
Analoger

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#299]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL009007?view=nn&q=has:editorialNote,graph:local)

> Forstår ikkje oppslaget. Analog er ikkje substantiv korkje på nb eller nn. Er det analogi som er meint, eller skal dette oppslaget vera eit adjektiv?

Ikke jeg heller :) 
Brukt på ett dok: http://ask.bibsys.no/ask/action/show?pid=070661030&kid=biblio

Antakelig betydningen https://en.wikipedia.org/wiki/Structural_analog#Chemistry

Hvis vi skal beholde det bør vi legge på en definisjon. Men vet ikke helt om vi trenger det..

**Comment by bibliomari** [comment]
Kasta den, jeg...
