### ISSUE TITLE
Populærvitenskap og populærlitteratur

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#30]
Begge formene finnes.

**Comment by bibliomari** [comment]
Beholder begge to foreløpig, legger på definisjon/bruksnote (= unngå bruk av populærlitteratur). Eks. på populærlitteratur er "gled deg med fuglene",  sjøormjakt og alt du trenger å vite om hestens helse.  Populærlitteratur: fag-/faktabøker med praktisk/erfaringsbasert informasjon... Vanskelig med definisjon. Rydde mest mulig over til populærvitenskap og se hvilke behov som står igjen...

**Comment by bibliomari** [comment]
Gjort.
