### ISSUE TITLE
Ants

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#300]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL006508?view=nn&q=has:editorialNote,graph:local)

> Kva er dette?

Fra [bruken](https://katapi.biblionaut.net/documents?q=real:Ants) ser det som en forkortelse for Algorithmic number theory symposium. Det skal nok ikke være et emneord :)

**Comment by bibliomari** [comment]
Fjernet.
