### ISSUE TITLE
Basement

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#301]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL010916?view=nn&q=has:editorialNote,graph:local)

> Kva er dette? Kjeller?

Bruk: http://ask.bibsys.no/ask/action/result?cql=%28bs.lokoeo-frase+%3D+%22Basement%22%29++AND+%28bs.avdeling+%3D+%22ureal?%22%29&aktivKilde=biblio%3AUBO

Ser ut som det er https://en.wikipedia.org/wiki/Basement_(geology) , altså Grunnfjell på norsk?

**Comment by mittinatten** [comment]
Virker jo sånn, klikker en på Bokmål fra den engelske wiki-siden kommer en til Grunnfjell, og på beskrivelsen høres det også sånn ut. Hva sier geofysikeren @mzyg?

**Comment by mzyg** [comment]
Enig har og.

**Comment by bibliomari** [comment]
Da har jeg opprettet termen Grunnfjell, med EN Basement, høres det greit ut eller er det et mangelfullt og rart emneord, @mzyg ?

**Comment by danmichaelo** [comment]
Lukker saken. Skrik ut hvis du er uenig, @mzyg
