### ISSUE TITLE
Beslutningsstøttesystemer

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#302]
Kommentar fra nynorsk-oversetterne:

> Kva er dette? Må vita for å omsetja rett (støtte/stønad)

Kan du se på om det ser greit ut, @knuthe ?

http://trans.biblionaut.net/concepts/REAL006718?view=nn&q=has:editorialNote,graph:local

Evt. legge inn definisjon i Sonja.

**Comment by knuthe** [comment]
Jeg har lagt inn en definisjon.

Se også:

https://en.wikipedia.org/wiki/Decision_support_system
https://no.wikipedia.org/wiki/Beslutningsst%C3%B8tteverkt%C3%B8y

Kunne jeg skrevet direkte inn som kommentar i det skjemaet du lenket til?

Hvor langt er de kommet?

Knut


Dan Michael O. Heggø wrote on 08/07/2015 01:26 PM:

**Comment by danmichaelo** [comment]
De har oversatt rundt 10 000 begreper, og ikke begynt på kvalitetskontrollen enda:

https://github.com/realfagstermer/prosjekt-nynorsk/blob/master/status.json

**Comment by danmichaelo** [comment]
Du *kunne* skrevet inn i skjemaet, men det skiller ikke mellom hvem som skriver, så det kan bli litt rotete. Jeg har begynt å indentere kommentarer jeg har "behandlet" med "> ". Og så legger jeg inn lenke til github-saken der det finnes

**Comment by danmichaelo** [comment]
Knut har lagt inn definisjon, så da er denne ferdig.
