### ISSUE TITLE
Bildende kunst

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#303]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL009830?view=nn&q=has:editorialNote,graph:local)

> Dette vert det same nn-oppslaget som for nb "Bildekunst". Bildende kunst og bildekunst vert i praksis synonymt.

Hm, hvordan er det på bokmål egentlig? Er Bildende kunst og Bildekunst forskjellige ting?

--
URI: http://data.ub.uio.no/realfagstermer/c009830
Bruk: https://katapi.biblionaut.net/documents?q=real:Bildende%20kunst

**Comment by Hypsibius** [comment]
Kva seier Humord?

**Comment by bibliomari** [comment]
Takk, @Hypsibius , har gjort som Humord og slått sammen.
