### ISSUE TITLE
Slå sammen Dokosaheksaensyre og Docosaheksaensyre

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#304]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL010198?view=nn&q=has:editorialNote,graph:local)

> Kan me slå saman dette oppslaget med "Docosaheksaensyre"?

Ja, det kan vi :) k-formen som foretrukket: https://sml.snl.no/dokosaheksaensyre

**Comment by bibliomari** [comment]
Ser ut som denne er gjort allerede.
