### ISSUE TITLE
Dyrebeskyttelse

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#305]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL005377?view=nn&q=has:editorialNote,graph:local)

> Korleis løysa denne når "Dyrevern" er eit eige oppslag?

Tja, trenger vi begge?

* https://katapi.biblionaut.net/documents?q=real:Dyrebeskyttelse
* https://katapi.biblionaut.net/documents?q=real:Dyrevern

**Comment by Hypsibius** [comment]
Nope, synest vi klarer oss med ein. Foreslår dyrevern BF dyrebeskyttelse

**Comment by BioHeidi** [comment]
På Dyrevern lå det en del poster som omhandlet bevaring og forvaltning (truede arter etc).
Og så har vi termen Dyrevelferd. Og Forsøksdyr : Etikk. Mye av de samme titlene her, jeg skal rydde og slå sammen litt.
Foreslår at vi beholder: 
Forsøksdyr : Etikk
Dyrevern BF Dyrebeskyttelse BF Dyrevelferd (for dyr som ikke er forsøksdyr)
Og så er det noen egne termer for Bevaringsbiologi og noe sånt...

**Comment by bibliomari** [comment]
Jeg har lagt Dyrebeskyttelse og Dyrevelferd som BF til Dyrevern.
