### ISSUE TITLE
Slå sammen Eklipser og Formørkelser

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#306]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL003149?view=nn&q=has:editorialNote,graph:local)

> Både "Eklipser" og "Formørkelser" er oppslag. Kan me slå dei saman?

Det er vel inge dum idé? @superLine

**Comment by superLine** [comment]
Det kan vi gjøre, jeg tipper at postene med de opprinnelige frie emneordene gjerne har begge termer tilknyttet i tillegg til solformørkelser og måneformørkelser...

**Comment by bibliomari** [comment]
Sikker på at det ikke skal være fôrmørkelser? 

Hoho. Jeg har slått sammen, og dessuten laget SO-henvisninger til Solformørkelser, Måneformørkelser og Stjerneformørkelser. Antagelig kan den ryddes, eller til og med slettes (crazy?), for som @superLine sier ser det ut som den gjerne forekommer i tillegg til f.eks. Solformørkelser. Men iallfall litt ryddet nå da.
