### ISSUE TITLE
Slå sammen Fjellsprengingsteknikk og Fjellsprengningsteknikk

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#307]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL000650?view=nn&q=has:editorialNote,graph:local)

> Treng "Fjellsprenging" og "Fjellsprengning" på BM å vera to ulike oppslag?

Nei, ferdig diskutert :)

**Comment by bibliomari** [comment]
Hehe. Gjort.
