### ISSUE TITLE
Fordyrking

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#308]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL008379?view=nn&q=has:editorialNote,graph:local)

> "Fôrdyrking"?

**Comment by bibliomari** [comment]
Jeg får ikke slippe inn i kommentaren. Har lagt det inn som BF-term foreløpig, må sjekke spesialtegna i BIBSYS...

**Comment by Hypsibius** [comment]
Slepp heller ikkje inn, men må då vere Fôrdyrking? Kan på ingen måte vere snakk om førehands-dyrking ;-P

**Comment by danmichaelo** [comment]
@Hypsibius Hvis du har en google-konto kan du trykke Logg inn, autentisér osv. *Etterpå* må jeg manuelt legge deg til i en gruppe (ellers hadde alle med google-konto fått tilgang :)). Ordnet det akkurat for Mari og Simon

**Comment by bibliomari** [comment]
@knuthe er det mulig å ha fôrdyrking?
