### ISSUE TITLE
Diffusjonsligninger

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#318]
Ifølge Wikipedia er diffusion equation en (type) partiell differensialligning. 

Hvis dette fortsatt skal være eget emneord: Bør den ha 

Diffusjonsligninger
SO Partielle differensialligninger

?

@danmichaelo @TorgunnKarolineMoe

**Comment by mittinatten** [comment]
Jeg skulle si at en diffusjonsligning er en partiell differensialligning på samme måte som en fisk er et dyr, det vil si at SO er kanskje ikke helt motivert?

**Comment by danmichaelo** [comment]
Enig i at fisk er dyr! :) Også enig i at vi ikke trenger SO her. Men usikker på om `Diffusjonsligninger` er en god term.. Jeg merker ihvertfall at jeg blir i tvil om det er snakk om løsninger av den generelle ligningen som gjerne kalles `Diffusjonsligningen`, eller om det omfatter mer spesialiserte modeller/ligninger som beskriver diffusjon.. Det er litt fristende å løse det ved å bare flette `Diffusjonsligninger` inn i `Diffusjon`... eller skal vi la det være som det er? Isåfall kan vi jo legge på en SO fra `Diffusjon`.

**Comment by mittinatten** [comment]
Hvis vi beholder det som separat term må det i hvert fall være bestemt form entall.

**Comment by danmichaelo** [comment]
Hm, én av bøkene vi har handler om "reaction-diffusion equation", som er diffusjonsligningen pluss et ledd som beskriver en kjemisk reaksjon… Den kan vi vel ikke kalle "Diffusjonsligningen"?

**Comment by danmichaelo** [comment]
Samtidig skurrer "Diffusjonsligninger"…

**Comment by mittinatten** [comment]
Hmm, det gjør det jo litt vanskeligere. En måte å løse det på er jo å lage en separat term for reaction-diffussion (Reaksjon-diffusjon? Ikke nødvendig med -ligninger?), det er jo en vel etablert term/modell. Men det finnes kanskje mange lignende eksempler? Kan en si at forholdet mellom reaction-diffusion-ligninger og diffusjonsligningen er mer 'has-a' enn 'is-a'? Altså diffusjonsligningen er en komponent i r-d-ligninger enn det er en overordnet kategori? (Gjør det noen forskjell for hvordan en skal håndtere dette?)

**Comment by danmichaelo** [comment]
I sommerheten slo jeg de like godt sammen, siden det bare var to dokumenter om "Diffusjonsligninger", og ikke altfor mange om "Diffusjon" (60) til at de druknet. Endret samtidig til bestemt entall.
