### ISSUE TITLE
Sitrusfrukter (eller Sitron?)

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#319]
@realfagstermer/biologer ,

Skal vi opprette `Sitrusfrukter`? For denne:

http://ask.bibsys.no/ask/action/show?pid=092472885&kid=biblio

**Comment by Hypsibius** [comment]
Stemmer for.

**Comment by bibliomari** [comment]
Vi har Citrus fra før, brukt i to farmasioppgaver. Skal jeg satse på at den er lik nok til å innlemmes i Sitrusfrukter?

Altså:

Sitrusfrukter
NN Sitrusfrukt
EN Citrus 
Def fellesbetegnelse for frukter av arter i slekten Citrus

?

**Comment by danmichaelo** [comment]
Ser sånn ut, ja. De to dokumentene om Citrus:

* Isolering og identifisering av komponenter i **grapefrukt** som inhiberer isoenzymet CYP3A4 (2001)
 noubomn: Citrus Farmakognosi Farmasi Interaksjoner
* Flavonoider fra Pericarpium **citrus sinensii** : isolation, struktur og aktivitet (1996)

**Comment by bibliomari** [comment]
Gjort.

**Comment by BioHeidi** [comment]
Jeg åpner denne igjen. Her vil jeg ha termen Sitrus, EN Citrus, LA Citrus, BF Sitrusfrukter. For "sitrusfrukter" er en ikkefaglig betegnelse på planten i sitrusslekten. Frukten er jo bare frukten...

(Det betyr ikke at jeg vil endre Stikkelsbær til Stikkels, om vi skulle komme borti det.)

**Comment by Hypsibius** [comment]
Tenkte det same v lokar i dag. Og tenkte å ikkje trøble. Men når først @BioHeidi tar det opp....

**Comment by BioHeidi** [comment]
Jeg er kjent for å trøble.

**Comment by Hypsibius** [comment]
DET er forsåvidt eg og :-P

**Comment by bibliomari** [comment]
Bare fint at dere trøbler. Gjort.
