### ISSUE TITLE
Illustrasjoner, vitenskapelige illustrasjoner, matematiske illustrasjoner

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#32]
Disse er emneord (brukes altså ikke om det som ER illustrasjoner, men skal være reservert litteratur som handler om dette). Vitenskapelige illustrasjoner er bare brukt to ganger. Jeg lurer på om vi kan slå sammen de to første, som Vitenskapelige illustrasjoner BF Illustrasjoner eller omvendt. 

Et emneord vi kanskje burde ha, er botaniske illustrasjoner, alternativt strengen

Botanikk : Illustrasjoner

Vi har også fått forslaget 

Astronomi : Illustrasjoner. 

(I så fall bør vi kanskje omgjøre Matematiske illustrasjoner til Matematikk : Illustrasjoner? jeg skulle gjerne gjort alt likt, men Astronomiske illustrasjoner høres litt feil ut)

Synsing? Særlig til @Violabibaluba og @BioHeidi, dessuten gjerne @superLine

**Comment by BioHeidi** [comment]
Peker til #210.
Vi har akkurat hatt en liten diskusjon om Illustrasjoner og Bildeverk. Mye av det som ligger på Illustrasjoner er egentlig bildeverk. Rydde? Noten på illustrasjoner er på plass. Men jeg skjønner ikke helt forskjellen mellom Illustrering og Illustrasjoner da, hvis illustrasjoner skal handle om å illustrere.

Samtidig:
Bildebøker er stort sett barnelitteratur, kan vi slå sammen de to termene? For å ikke skape forvirring.

**Comment by superLine** [comment]
illustrering av fenomener! Altså som metode. Må vel skille de?

**Comment by Caroline-A** [comment]
> Peker til #210.
> Vi har akkurat hatt en liten diskusjon om Illustrasjoner og Bildeverk. Mye av det som ligger på Illustrasjoner er egentlig bildeverk. Rydde? Noten på illustrasjoner er på plass. Men jeg skjønner ikke helt forskjellen mellom Illustrering og Illustrasjoner da, hvis illustrasjoner skal handle om å illustrere.
> 
> Samtidig:
> Bildebøker er stort sett barnelitteratur, kan vi slå sammen de to termene? For å ikke skape forvirring.

Gammelt tråd, men fant den fordi jeg er litt forvirret over bildeverk osv.  - For eks. jeg har en bok her nå som inneholder mange foto av fugl. Skal den under bildeverk, bildebøker eller fotografier?

**Comment by superLine** [comment]
Jeg ville ha satt bildeverk. Tenker dokument med "overvekt av bilder av pene ting i naturen".

**Comment by grosyn** [comment]
I samband med at Realfagstermer no skal bruka NTSF [https://www.nb.no/nbvok/ntsf/nb/](url), blir vårt emneord Bildeverk erstatta med Illustrerte verk. Bildeverk ligg inne som henvisningsterm.
