### ISSUE TITLE
Flette: Sovjet dobbelt opp

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#320]
Vi har både *emnet* "Union of Soviet Socialist Republics" og *stedet* "Sovjetunionen"

**Comment by Hypsibius** [comment]
Men er dette ein logisk stadsterm no? Vi kan ikkje forvente at om nokon leitar etter russiske fiskeartar, skal dei tenke på om boka evt var publisert i sovjettida eller ikkje? Akkurat som eg ikkje for å finne ut noko om fisk i akerselva burde vere nødt til å søke både stadterm Oslo og Christiania?

**Comment by Hypsibius** [comment]
Altså, det eg meinte å seie, er at om ei bok omhandlar epoken (og eksempelvis ichthyologiske studiar i sovjettida) vil det vere rimeleg med ein term som viser til dette. Om det er ei biogeografisk (eller geologisk) tilnærming, vil eg hatt no gjeldande namn på geografiske område.

**Comment by bibliomari** [comment]
Slettet/ryddet emnet, vi hadde bare brukt det på tre soppbøker, som jeg har rettet til Russland (og ble det logisk?). For langt til lokarering!
