### ISSUE TITLE
Middelalder -> Middelalderen

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#321]
Bestemt form

**Comment by Hypsibius** [comment]
!

**Comment by bibliomari** [comment]
OK, MEN @danmichaelo: Vi får ikke rettet i 648, bare i "dubletten" i 687. Skal jeg likevel rette nå (og trenge fiskehjelp fra deg kanskje siden?) eller vente på O Alma?

**Comment by danmichaelo** [comment]
Ah, det var det, ja… Nei, vi kan godt la den ligge til O Alma :)

**Comment by danmichaelo** [comment]
Lokar ferdig, venter på Sonja
