### ISSUE TITLE
Gyldne snitt -> Det gylne snitt

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#322]
Usikker på om "gyldne" også er lov eller ikke. Ordboka gir treff på "gyllen", men ikke "gylden"

**Comment by mittinatten** [comment]
Usikker på rettskrivingen, men enig i at det bare finnes ett.

**Comment by Hypsibius** [comment]
Mulig det finst i riksmålsordboka, men i bokmåls- og nynorskytgåva er 'gylden' noko anna http://www.nob-ordbok.uio.no/perl/ordbok.cgi?OPP=+gylden&ant_bokmaal=5&ant_nynorsk=5&begge=+&ordbok=begge ;-)

**Comment by bibliomari** [comment]
Gjort
