### ISSUE TITLE
Artssammensetning

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#330]
Kjenner behov for ny term 'Artssammensetning' NY Artssamansetjing En Species composition

SO-term: Biodiversity

Men innfallsvinkelen er ulik: I nokre tilfelle (biodiversitet) er fokus på bevaring av diversitet. I andre tilfelle, eksempelvis ved organiske utslipp, kan auka diversitet vere ein indikasjon på forstyrring/eutrofiering. Samansetjinga (antal artar, forekomst av nøkkelartar) er dermed noko separat frå diversitet, og brukast som eit mål på 'helse'

Artssammensetning hos artsdatabanken: http://data.artsdatabanken.no/Pages/179953

I resipientanalyser her ved UiB er samansetninga representert på annan måte (ikkje binært, med fråvær/nærvær, men som antal artar med 1, 2 , 4 etc individ representert). 

Aktuelt dokument: 

http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS132747413&vid=UBB

**Comment by BioHeidi** [comment]
Gjort.
