### ISSUE TITLE
Slå sammen 'Nanomaterialer' og 'Nanostrukturer'

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#332]
I prinsippet er jo `Nanostrukturer` breiere, siden det også kan dekke naturlige nanostrukturer som ikke har materialtekniske anvendelser, men i praksis tror jeg vi klarer oss med `Nanomaterialer` (BF Nanostrukturerte materialer). Alle bøkene som er indeksert med `Nanostrukturer` i dag ser ut til å kunne klart seg fint med `Nanomaterialer`, og på nye bøker blir det fort til at jeg slenger på begge termene.

Oppdaget også at biologene har sitt eget begrep: `Ultrastrukturer`

Foreslår at `Nanomaterialer` beholdes siden jeg tror det er en mer innarbeida term, men åpen for å diskutere det :)

Ping @mittinatten

**Comment by mittinatten** [comment]
Ingen innvendinger fra meg!

**Comment by bibliomari** [comment]
Gjort
