### ISSUE TITLE
Metabolisme og Energistoffskifte

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#334]
Vi har desse termane: 
Metabolisme (REAL013661)
  BF Metabolismen
     Stoffskifte

Energistoffskiftet (REAL005329)

Foreslår: Stoffskifte BF Metabolisme, energiomsetning

Stryk resten?

Altså, fokus blir litt forskjellig etter om vi fokuserer på involverte stoff eller energien, men reaksjonane burde vel vere dei same?

**Comment by bibliomari** [comment]
@BioHeidi

**Comment by BioHeidi** [comment]
Enig.

**Comment by bibliomari** [comment]
Energiomsetning er allerede BF til energiproduksjon. Ellers har jeg fulgt forslaget.

**Comment by BioHeidi** [comment]
Og jeg fant Bioenergetikk, som vi godt kan ha en SO på.

**Comment by bibliomari** [comment]
Det høres fornuftig ut for meg. @Hypsibius ?
