### ISSUE TITLE
Slå sammen 'Feilanalyse', 'Feilteori' og 'Feilregning'?

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#335]
Jeg tenker på feilteori, feillære, feilanalyse og feilregning som det samme (men ikke "feil teori" osv. :D).

LCSH [har](http://id.loc.gov/authorities/subjects/sh85044724.html) "Errors, Theory of" som variant av "Error analysis (Mathematics)".

Basert på bruk burde `Feilanalyse` være foretrukket term hvis vi slår sammen.

Enig? Uenig? @TorgunnKarolineMoe @knuthe @mittinatten

**Comment by mittinatten** [comment]
Høres bra ut, og enig i at Feilanalyse er den beste termen.

**Comment by knuthe** [comment]
Jeg studerte en gang numerisk analyse, kan jeg få tenke litt over saken?

Den 22/09/15 16:23, skrev Simon Mitternacht:

**Comment by knuthe** [comment]
Har nå tenkt litt og er enig med Dan Michael og Simon. "Feilanalyse" (det er brukt både i numeriske metoder og hardware-relaterte ting, men det gjør ikke noe. Kategori vil framgå av klassifikasjonen).

**Comment by danmichaelo** [comment]
Fint, da er det bare for noen med LOKAR å fikse :)

**Comment by bibliomari** [comment]
Gjort
