### ISSUE TITLE
Stoffomsetning, ikke narkotika...

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#337]
EMneordet stoffomsetning gir mange morsomme treff i BIBSYS, vi har heldigvis bare brukt det i en betydning, ser det ut til. Men kan biologene hjelpe meg? @Hypsibius @BioHeidi, er det det samme som metabolisme og kan slås sammen med det, eller er det noe annet?

Hvis ikke skal slås sammen med annet: Jeg ønsker meg en definisjon, for å slippe narkotika :)

**Comment by Hypsibius** [comment]
Kan vi ikkje smeise den saman med dette? https://github.com/realfagstermer/realfagstermer/issues/334

**Comment by bibliomari** [comment]
Gjort.
