### ISSUE TITLE
Svømmeblæren

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#338]
Foreslår ny term: Svømmeblæren NN Svømmeblæra BF Symjeblæra EN Swim bladder

Sikkert ikkje nødvendig med nærare intro, men til bruk på eksempelvis dette dokumentet: 

http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS151310998&vid=UBB

**Comment by danmichaelo** [comment]
Usikker på om det skal være entall eller flertall, overlater den til @bibliomari eller @BioHeidi

**Comment by bibliomari** [comment]
Gjort

**Comment by Hypsibius** [comment]
For organ brukast eintal, jf urinblæren, hjertet..
