### ISSUE TITLE
Fiskeansamlingsinretning

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#339]
Foreslår (under tvil) ny term Fiskeansamlingsinretning EN Fish aggregating device EN FAD 

Skulle gjerne ha ein betre term, men denne er i det minste brukt nokre gongar, finst på Wikipedia og eg får treff hos Miljødirektoratet. 

Skulle hatt veldig lyst til å kalle det fiskesamlingsinretning eller fiskesamlar på nynorsk, men veit ikkje heilt. 

https://no.wikipedia.org/wiki/Fiskeansamlingsinnretning

aktuelt dokument:  http://hdl.handle.net/1956/10395

**Comment by danmichaelo** [comment]
Opprettet sporenstreks :D
