### ISSUE TITLE
Gytebestand

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#341]
Foreslår ny term: Gytebestand NN Gytebestand EN Spawning stock

Termen Brukast gjentatte gongar i SNL, utan å ha eigen innførsel: https://snl.no/.search?query=gytebestand&x=0&y=0

Aktuelt dokument: http://hdl.handle.net/1956/10408

**Comment by danmichaelo** [comment]
Har du en kort definisjon?

**Comment by Hypsibius** [comment]
Oj, prøver meg på ei omsetjing frå Fishbase, det må vere det tryggaste: 'Andelen av en bestand som er kjønnsmoden og som gyter, det vil si antallet eller biomassen av all fisk som er over aldersklassen eller størrelsesklassen der 50% av individene er kjønnsmodne.

**Comment by Hypsibius** [comment]
'som er over'? Høyrest rart ut. Betre forslag, @BioHeidi

**Comment by BioHeidi** [comment]
Nei det høres helt forståelig ut.

**Comment by bibliomari** [comment]
Opprettet.
