### ISSUE TITLE
Oppvekstområde

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#342]
Foreslår ny term Oppveksområder BF Oppveksthabitat EN Nursery habitat BF Nursery areas

Gir mett med treff på HI sine sider: http://www.imr.no/sok/nb-no?searchString%3Autf8%3Austring=oppvekstomr%C3%A5de

Aktuelt dokument http://hdl.handle.net/1956/10408

**Comment by danmichaelo** [comment]
Gjelder dette bare fisk? En kort definisjon hadde sikkert vært lurt her også.

**Comment by Hypsibius** [comment]
Neida, ikkje berre fisk- Det kan i prinsipp gjelde kva som helst, men nokre artar med planktoniske stadiar har vanskelegare for å flytte rundtpå seg etter botnslåing. Men definisjon - ser fiskreriforvaltning har ei heilt anna fokus enn meg som meir marinøkolog. Må tygge på om eg finn ein grei, samla definisjon som funkar for begge grupper.

**Comment by bibliomari** [comment]
Opprettet.
