### ISSUE TITLE
Teiner

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#343]
Teiner EN Fish pots (jf Ordnett.no)

https://snl.no/teine

Aktuelt dokument: http://hdl.handle.net/1956/10415

**Comment by danmichaelo** [comment]
Oppretta. La på BF Fisketeiner, Hummerteiner, Ruser EN Fish Pots, Lobster pots, Lobster Traps

P.S. masteroppgaven har fått emne "Torskefiskser" ;) Det må da være mulig å få til autoritetskontroll i DSpace..
