### ISSUE TITLE
Sannsynlighetsregning og Sannsynlighetsteori : slå sammen?

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#344]
Tekord har bare `Sannsynlighetsregning`, Nowiki omdirigerer `Sannsynlighetsregning` til `Sannsynlighetsteori`, SNL har begge, men ser ikke helt ut til å klare å skille de fra hverandre: "Sannsynlighetsteori, teorien for statistisk sannsynlighet (jfr. sannsynlighetsregning)".

@TorgunnKarolineMoe @mittinatten ?

**Comment by mittinatten** [comment]
Jeg har alltid syntes skillet er umotivert, så kan gjerne slås sammen for min del. Sannsynlighetsteori er bredere så jeg foreslår det som foretrukket.

**Comment by danmichaelo** [comment]
Slått sammen, `Sannsynlighetsteori` som foretrukket.
