### ISSUE TITLE
Immunoblot(t)

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#345]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL008362?view=nn&q=has:editorialNote,graph:local)

> Denne ser ut til å vera stava med ein t på nettet. Sjekk opp termen både på BM og NN.

Er det denne betydningen, mon tro? https://en.wikipedia.org/wiki/Western_blot
Ser ut som det er én t på norsk også, ja: http://labhandbok.no/tag/immunoblot/

@realfagstermer/biologi

**Comment by bibliomari** [comment]
Trenger vi denne, @Hypsibius og @BioHeidi ?

**Comment by mittinatten** [comment]
Western blot er en veldig populær metode (for eksempel 167 treff i [BORA](https://bora.uib.no/discover?scope=%2F&query=%22western+blot%22&submit=)). Så hvis det virkelig er det som menes i det ene treffet så trengs termen, og litt rart at den ikke har blitt indeksert i høyere grad. Jeg får 11 treff i [bibsys](http://ask.bibsys.no/ask/action/result?cmd=&kilde=biblio&fid=emne&term=western+blot%3F&op=and&fid=alle&term=&bibliografi=&arstall=&sortering=sortdate-&treffPrSide=10) på emne 'western blot?', en del i Oslo, så kanskje denne bare ikke ble fanget opp når termene ble laget?

**Comment by mittinatten** [comment]
Kanskje det er fordi det sees som en av mange standardmetoder i mange av treffene som det ikke er blitt emneord.

**Comment by BioHeidi** [comment]
Western blot og immunoblot er vel synonymer, ja. Men jeg synes ikke vi trenger termen med mindre det er dokumenter som handler om selve metoden, det blir litt feil å bruke det som emneord der metoden bare er en måte å komme frem til resultatet på.

Et eksempel på dokument som kunne hatt western blot / Immunoblot som term:
http://ask.bibsys.no/ask/action/show?pid=121656233&kid=biblio

**Comment by Hypsibius** [comment]
Slit fortsatt med termen, bloting synest avleggs. Men er det ingen betre, så....

**Comment by BioHeidi** [comment]
Hverken bloting eller blotting er greit!

**Comment by bibliomari** [comment]
Endret til immunoblot, lagt til engelsk.
