### ISSUE TITLE
Slå "Kikkerter" inn i "Stjernekikkerter"

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#347]
Alle bøkene våre indeksert med `Kikkerter` ser ut til å handle om `Stjernekikkerter`

(Opprinnelig et spørsmål om Kikerter vs Kikkerter fra http://trans.biblionaut.net/concepts/REAL010900?view=nn&q=has:editorialNote,graph:local)

**Comment by bibliomari** [comment]
Gjort. @superLine kan kanskje kaste lys over hva astronomiske kikkerter er, og om vi trenger både dem og Stjernekikkerter? Hvis ja, bør det være en SE OGSÅ mellom dem?

**Comment by Hypsibius** [comment]
Relativt stor forskjell: https://snl.no/hummus PS: lærte forøvrig at på arabisk betyr hummus berre kikerter, dei heiter hummus også om dei ikkje er most/puré-ert...

**Comment by danmichaelo** [comment]
Men `Astronomiske kikerter` har vi ikke enda!

**Comment by Hypsibius** [comment]
Gastronomiske, då?

**Comment by superLine** [comment]
Innspill fra hun med hjernen i almaland: har googlet hos kikkertspesialisten. de har kategori både for stjernekikkerter og alle de andre variantene.. så om det bare er astro som har kikkerter så kan de hete stjernekikkerter

**Comment by bibliomari** [comment]
Synd å lukke disse trådene hvor dere er så himla morsomme, men jeg må bare gjøre det :8ball:
