### ISSUE TITLE
Naiader -> Najader

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#349]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL002722?view=nn&q=has:editorialNote,graph:local)

> BM skal vera "najader"

**Comment by bibliomari** [comment]
Gjort. Men før jeg tar helt av med gresk mytologi og havfruer og sånn... Kan dette egentlig slås sammen med Nymfer, @BioHeidi og @Hypsibius ?? 

Alle våre poster med Naiader har også *691**$amollusca najades

**Comment by BioHeidi** [comment]
Heh. Her var det en liten nøtt! Najader-emneordet bragte meg inn i både seriøs forskning og kaninegg. Så den må jeg se litt mer på, og pusse på tysken. Men nymfer må vi holde utenfor. Den kan sikkert presiseres mer, for det er jo veldig mange insekter som har nymfestadie.

**Comment by Hypsibius** [comment]
Oj, dette låg aller lengst bak i skallen. Har aldri høyrt om najader i forbindelse med molluskar, så det må vel vere ei tilfeldigheit eller ein feil? La oss halde molluskane utanfor. Og kva er 'amollusca'?

Korriger meg gjerne, men eg har oppfatta det slik at ungstadiar av hemimetabole insekt (som ikkje har fullstendig metamorfose) er nymfer, men at nymfer også KAN brukast om ungstadiar av andre dyr. Najadar er ung-stadiar av hemimetabole AKVATISKE insekt. Om eg har oppfatta rett, er då alle najadar nymfer, men ikkje alle nymfer er najadar. For meg held dette for å seie nymfer BF najader

Atterhald: Har tatt kurset 'B 291 Evertebrater UTEN insekter', så er kanskje diskvalifisert....

**Comment by BioHeidi** [comment]
Men er najader ikke en fryktelig forkullet term? Brukes den fortsatt?

**Comment by Hypsibius** [comment]
Ingen treff hos oss på norsk, men den engelske termen brukast jo, og då blir det fort smitte tilbake, og det studentane søker etter... 
![najader](https://cloud.githubusercontent.com/assets/9350370/10388161/e2de47c6-6e67-11e5-8d5a-8c9774f9b813.PNG)

**Comment by Hypsibius** [comment]
PS: kan ikkje dy meg, her må eg jo lenke inn denne: http://sfxeu09.hosted.exlibrisgroup.com/sfx_ubb?frbrVersion=5&ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&ctx_tim=2015-10-09T09%3A31%3A52IST&url_ver=Z39.88-2004&url_ctx_fmt=infofi/fmt:kev:mtx:ctx&rfr_id=info:sid/primo.exlibrisgroup.com:primo3-Article-wj&rft_val_fmt=info:ofi/fmt:kev:mtx:&rft.genre=article&rft.atitle=Mermaids%E2%80%90+their+biology%2C+culture.+and+demise+1&rft.jtitle=Limnology+and+Oceanography&rft.btitle=&rft.aulast=Banse&rft.auinit=&rft.auinit1=&rft.auinitm=&rft.ausuffix=&rft.au=Banse%2C+Karl&rft.aucorp=&rft.date=199001&rft.volume=35&rft.issue=1&rft.part=&rft.quarter=&rft.ssn=&rft.spage=148&rft.epage=153&rft.pages=&rft.artnum=&rft.issn=0024-3590&rft.eissn=1939-5590&rft.isbn=&rft.sici=&rft.coden=&rft_id=info:doi/10.4319%2Flo.1990.35.1.0148&rft.object_id=&svc_val_fmt=info:ofi/fmt:kev:mtx:sch_svc&rft_dat=%3Cwj%3E10.4319%2Flo.1990.35.1.0148%3C/wj%3E%3Cgrp_id%3E5318499346068634976%3C/grp_id%3E%3Coa%3E%3C/oa%3E&rft.eisbn=&rft_id=info:oai/&req.language=nor

**Comment by Hypsibius** [comment]
Kan ikkje dy meg, må ha med denne:http://www.jstor.org/stable/2837348?seq=1#page_scan_tab_contents

**Comment by bibliomari** [comment]
Knegg :dancer: 

Så... hva blir termen? @BioHeidi @Hypsibius

**Comment by BioHeidi** [comment]
Det er greit med najader for meg. Var ikke klar over at naiads var en gangbar engelsk term! Så får vi heller rydde i nymfer ved bedre tider.

**Comment by Hypsibius** [comment]
Men nymfer BF najader, ville ikkje det funke?

**Comment by BioHeidi** [comment]
Jo! Det funker.

**Comment by bibliomari** [comment]
Gjort.
