### ISSUE TITLE
Ostracoder og Muslingkreps

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#352]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL002334?view=nn&q=has:editorialNote,graph:local)

> "Muslingkreps" bør òg vera med på BM.

*Men* vi har allerede Muslingkreps som frittstående term. Kan de slås sammen? @realfagstermer/biologi

**Comment by Hypsibius** [comment]
Indeed!

**Comment by BioHeidi** [comment]
Jepp. På Muslingkreps ligger allerede latin Ostracoda, så legg gjerne inn BF Ostracoder.
