### ISSUE TITLE
Sekkdyr eller sekkedyr

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#355]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL004131?view=nn&q=has:editorialNote,graph:local og http://trans.biblionaut.net/concepts/REAL010184?view=nn&q=has:editorialNote,graph:local)

> Sekkdyr eller sekkedyr? Sjekk for konsekvens.

@realfagstermer/biologi

**Comment by Hypsibius** [comment]
Ojda, både SNL, Allkunne.no og Artsdatabanken går for sekkdyr! Då må nesten vi gjere det same, og heller ha ein BF for Sekkedyr. Sjølv ome g aldri har høyrt noko anna brukt. 

Ei anna sak:  var det sånn at eg måtte gå inn og autentisere meg, og så måtte du autorisere meg? Inbiller meg no autentisert, men får framleis ikkje tilgang til noko der over!

**Comment by BioHeidi** [comment]
Høh. Sekkdyr. Høres rart ut, men jeg bøyer meg for allkunne og @Hypsibius .

**Comment by Hypsibius** [comment]
Skrekkeleg rart. Men sånn er det altså

**Comment by danmichaelo** [comment]
@Hypsibius Du var autentisert, men hadde ikke fått tilganger. Men nå har du det :zap:

**Comment by Hypsibius** [comment]
Juhu!

**Comment by bibliomari** [comment]
Gjort

**Comment by mariaksv** [comment]
Vebjørn seier at den e-en er ein fuge-e som me nyttar munnleg. Litt same fenomen som når folk seier "flyktning-e-krisa", osb. Men denne skal ikkje vera med når me skriv. Maria
