### ISSUE TITLE
Polymerase Chain Reaction -> Polymerase kjedereaksjon

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#356]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL009593?view=nn&q=has:editorialNote,graph:local)

> "PCR" bør stå som tillegg i båe versjonane, og "polymerase kjedereaksjon" kan brukast på norsk.

**Comment by bibliomari** [comment]
Gjort

**Comment by Hypsibius** [comment]
Litt tvilande til formen på dette (men har trufast utført lokar, dog utan napp)

Trudde det var eit prinsipp i norsk at to substantiv ikkje kunne stå fritt etter kvarandre, men måtte byggast saman? Og då er spørsmålet, er det i så fall polymerase-kjedereaksjon eller polymerasekjede-reaksjon? Ein polymerasekjede som reagerer eller ein polymerase som kjedereagerer?

**Comment by bibliomari** [comment]
@Violabibaluba @bibliomari

**Comment by danmichaelo** [comment]
SML har smelt til med https://sml.snl.no/polymerasekjedereaksjon

**Comment by BioHeidi** [comment]
Det er en kjedereaksjon katalysert av en polymerase, så hvis vi skal ha bindestrek blir det polymerase-kjedereaksjon, men det er egentlig mest riktig å skrive uten bindestrek, men i ett ord. Som SNL og Wikipedia: https://no.wikipedia.org/wiki/PCR

**Comment by Hypsibius** [comment]
Langt, men korrekt! Sånn skal det vere!

**Comment by bibliomari** [comment]
Absolutt. JEG RØDMER DYPT I SKAM!!!
