### ISSUE TITLE
Renframstilling

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#358]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL013275?view=nn&q=has:editorialNote,graph:local)

> Kva er dette? Framstilling av reine stoff? Kan me berre gjera "ren" til "rein", eller er det nokofast uttrykk her?

Usikker på om dette er noen god term å bruke som emneord. Kan spørre Tone.

**Comment by bibliomari** [comment]
Har du spurt, @danmichaelo ?

**Comment by Hypsibius** [comment]
Kva fagområde er dette? Kjemi/prossesskjemi?  @bubir

**Comment by danmichaelo** [comment]
NÅ har jeg spurt  Tone :D Hun synes det var greit å slette den, så da gjorde jeg det :)
