### ISSUE TITLE
Scanning mikroskopering

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#359]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL011192?view=nn&q=has:editorialNote,graph:local)

> Har me noko meir norskt i tillegg?

Vi oversatte jo `Scanning electron micrscopy` som `Sveipelektronmikroskopi`, så `Sveipmikroskopi` burde vel funke? Den ene boka vi har om emnet handler om https://en.wikipedia.org/wiki/Confocal_microscopy , som er en form for optisk mikroskopi, ikke elektronmikroskopi, så det er nok ikke riktig å slå den sammen med `Sveipelektronmikroskopi`, som jeg først tenkte kanskje var en mulighet.

**Comment by bibliomari** [comment]
Gjort. Fint ord :+1: 

Noen forslag til engelsk term?

**Comment by danmichaelo** [comment]
`Scanning microscopy` da vel ;)

**Comment by bibliomari** [comment]
Hehe. Gjort.

**Comment by mittinatten** [comment]
Sveipmikroskopi burde være samlenavn for alle former: Atomic Force Microscopy, Scanning Tunneling Microscopy, Scanning Electronic Microscopy, Confocal laser scanning microscopy, [etc](https://en.wikipedia.org/w/index.php?search=Scanning+microscopy&title=Special%3ASearch&go=Go). Det er jo mulig det likevel er mest logisk å bruke sveipmikroskopi for dette ene objektet, men vi burde legge til

    Sveipmikroskopi
    UT/SO Atomic force microscopy
    UT/SO Sveipelektronmikroskopi
    UT/SO Flere?

i hvert fall. (Og prøve å finne en god norsk term for AFM).

**Comment by danmichaelo** [comment]
God idé, jeg skyndet meg å legge inn de hierarkiske relasjonene før noen protesterte :)

Vi hadde LVSEM også.

AFM, ja.. Atomkraftmikroskopi er en mulighet, men atomkraft gir veldig assosiasjoner til kjernekraft på norsk…

**Comment by danmichaelo** [comment]
[atomærkraftmikroskopi](http://www.uio.no/studier/emner/matnat/fys/UNIK4470/) BF atomkraftmikroskopi kanskje?

**Comment by mittinatten** [comment]
Wikipedia sier at Scanning Force Microscopy er en synonym, hva med Sveipkraftmikroskop (eller bare Kraftmikroskop)?

På dansk brukes [Atomisk kraft mikroskop](http://fysikleksikon.nbi.ku.dk/A/afm/) og [Atomar kraftmikroskop](https://da.wikipedia.org/wiki/Atomar_kraftmikroskop), på svensk [Atomkraftsmikroskopi](https://sv.wikipedia.org/wiki/Atomkraftsmikroskopi), på tysk [Rasterkraftmikroskop](https://de.wikipedia.org/wiki/Rasterkraftmikroskop) (og Atomares kraftmikroskop og Atomkraftmikroskop nevnes i wikipedia), på bokmåls-wikipedia [Atomkraftmikroskop](https://no.wikipedia.org/wiki/Atomkraftmikroskop).

Like Rasterkraftmikroskop, men vet ikke om vi burde bare finne på at det er det som skal brukes på norsk. Siden du fant belegg for Atomærkraftmikroskopi kanskje jeg kan si meg enig i at det er best (selv om jeg ikke syns atomkraftsforvirringen er et stort problem).

**Comment by danmichaelo** [comment]
Haha, jeg så også *Rasterkraftmikroskopi* og tenkte at hmm, *den* var ikke dum :)

Men det mest gjenkjennbare er nok Atomkraftmikroskopi eller Atomærkraftmikroskopi. Kanskje vi bare skal gå for [Atomkraftmikroskopi](https://www.idunn.no/natur/2012/03/atomkraftmikroskopi_afm_en_viktig_metode_i_nanomedisins), siden den er mest i bruk? (jeg tror jeg vippet tilbake)

På http://www.uib.no/emne/NANO161 fant jeg både atomkraftmikroskopi og sveiptunnellmikroskopi :) STM har vi faktisk ikke som emneord, det er litt overraskende.

**Comment by danmichaelo** [comment]
(Aha, vi har `Tunnelmikroskopi` som dekker STM)

Men nå oppdaget jeg forresten at vi også har `Rastermikroskopi`… som nok bør slås sammen `Sveipmikroskopi`

**Comment by mittinatten** [comment]
Høres ut som vi har en løsning! (legge til `BF Sveipkraftmikroskopi BF Rasterkraftmikroskopi`?)

**Comment by danmichaelo** [comment]
Ja, så da er det egentlig to ting som må gjøres:

1) Omdøpe `Atomic force microscopy` til `Atomkraftmikroskopi BF Atomærkraftmikroskopi BF Rasterkraftmikroskopi BF Sveipkraftmikroskopi EN Atomic-force microscopy EN Scanning-force microscopy` (selv om jeg er usikker på om noen *noensinne* kommer til å søke etter sveipkraftmikroskopi :P)
2) Flette `Rastermikroskopi` inn i `Sveipmikroskopi` (og så lurer jeg på om jeg skal ta en liten manuell gjennomgang av postene våre, mange kan nok omklasses til STM, AFM eller SEM)

**Comment by bibliomari** [comment]
Puh! Gjort.

**Comment by danmichaelo** [comment]
Men heisann, vi hadde visst også `Atomkraftmikroskop` :smile:  Kan vi slå den inn i `Atomkraftmikroskopi`? Vi trenger kanskje ikke engang beholde termen..?

**Comment by bibliomari** [comment]
Slo sammen og visket bort Atomkraftmikroskop...
