### ISSUE TITLE
Stohastiske modeller

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#360]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL012099?view=nn&q=has:editorialNote,graph:local)

> Er det verkeleg noko som heiter "Stohastisk"? I den eine oppførte katalogposten står det "Stochastic" på EN, men dette er omsett "Stohastisk" på BM. Eg vil tru det er ei feilstaving, om ikkje det er noko obskrønt fysikarane har funne på. Jørgen?

Selv om h ikke er helt nabo med k på tastaturet er det nok en feilstaving :see_no_evil:

**Comment by bibliomari** [comment]
Rettet
