### ISSUE TITLE
Slå sammen Nettbasert undervisning og Web-basert undervisning

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#362]
Kommentar fra nynorsk-oversetterne: (http://trans.biblionaut.net/concepts/REAL004573?view=nn&q=has:editorialNote,graph:local)

> Kan oppslaga "Nettbasert undervisning" og "Web-basert undervisning" slåast saman?

Antar det. @knuthe ?

**Comment by Hypsibius** [comment]
Skulle ein tru!
