### ISSUE TITLE
Elektronisk dagbok -> Blogging

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#363]
Blogging er veletablert som egen term i dag. Ferdig diskutert, nei?

Trengs til Safaribok : http://ask.bibsys.no/ask/action/show?kid=biblio&pid=123235855

@knuthe @bibliomari

**Comment by bibliomari** [comment]
Høhø. Vi har jo elektronisk dagbok (!) for fenomenet blogg, holder det eller vil du ha et eget emneord for aktiviteten?

**Comment by danmichaelo** [comment]
Beklager uklarhet. Forslaget mitt var at "elektronisk dagbok" burde omdøpes til "blogging". Tenker på "Dagbok" som noe personlig, mens blogging er noe offentlig.

**Comment by danmichaelo** [comment]
Språkrådet har riktignok ikke blogg som oppslagsord, men de snakker om blogger under oppslagsordet bloggsfære: http://www.sprakradet.no/sprakhjelp/Skriverad/Ordlister/Datatermar/

**Comment by bibliomari** [comment]
Det er jo ikke mye brukt, men mener du at vi skal endre emneordet fra å betegne "blogger" til å betegne "blogging"?

Altså:

Blogging BF Blogg, Blogger, Elektronisk dagbok osv osv

?

**Comment by danmichaelo** [comment]
Ja, fra titlene som allerede har emneordet synes jeg Blogging (fenomenet / mediet) virker mer beskrivende enn Blogger.

**Comment by danmichaelo** [comment]
Men det går sikkert an å argumentere for Blogger også :)

**Comment by bibliomari** [comment]
Gjort

**Comment by knuthe** [comment]
Elektronisk dagbok ble vel innført på et tidspunkt der blogging ikke var 
etablert. Jeg følger ikke så mange blogger og mitt inntrykk er at de 
ofte er både private og offentlige :-)

"Ja" til "blogging".

(gjerne med definisjon: Elektronisk nettbasert, offentlig dagbok" eller 
noe sånt. Sjekk evt språkrådet på dette punktet.

Knut

Den 05/10/15 11:22, skrev Dan Michael O. Heggø:
