### ISSUE TITLE
Tunnelmikroskopi

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#364]
Utskilt fra #359 :  

Foreslår at `Tunnelmikrokopi` omdøpes til `Sveiptunnelmikrokopi`, og at `Tunnelmikroskop` flettes inn i denne.

Engelsk `Scanning Tunneling Microscopy` AK `STM`

**Comment by mittinatten** [comment]
Jepp, det er bedre.

**Comment by bibliomari** [comment]
Gjort.

Skal da Tunnelmikroskop omdøpes til Sveiptunnelmikroskop?

**Comment by danmichaelo** [comment]
Ja, hvis vi trenger termen kan vi godt det. Men da bør det vel være flertall hvis vi snakker om tingen?

**Comment by mittinatten** [comment]
Bare for å klargjøre, vi snakker vel ikke om å ha termer for både mikroskop og mikroskopi?

**Comment by bibliomari** [comment]
Jeg ser ikke noe galt i det, eller hva @Violabibaluba ? Det er forskjell på tingen og bruk av tingen. Men det er dere som kjenner samlingene. Hvis vi har bøker som handler om mikroskop som gjenstander synes jeg mikroskop er et helt topp emneord. Hvis bøkene handler om bruken av disse gjenstandene går jeg for mikroskopi. 

Hvis dere som sitter på bøkene synes det virker helt fjernt å dele det, så ok. Jeg skjønner at det kan bli veeldig sært når dere absolutt skal ha så mange ulike typer mikroskop :) Kanskje vi heller burde hatt strenger... Med TYPE MIKROSKOP : MIKROSKOPI ...

**Comment by Violabibaluba** [comment]
Jeg synes det blir riktig med begge termene (ting og bruk), men det avhenger av at bøkene faktisk handler om enten det ene eller andra da...

**Comment by danmichaelo** [comment]
Hmmmjaa, jeg ser på disse som "metoder" og har tenkt at det holder med "*mikroskopi"-formene, men jeg er sikkert litt farget av materialvitenskapbakgrunnen min. Tror allikevel samlingene våre generelt er mest om "bruk av tingen". Forhåpentligvis har vi også ett og annet verk om "historien bak tingen", men for mange av de litt mer "særere" mikroskopene har vi nok ikke det.

Når det gjelder [det ene dokumentet](http://ask.bibsys.no/ask/action/show?pid=910229228&kid=biblio) vi har om `Tunnelmikroskop`, kunne ikke det like godt vært under `(Sveip)tunnelmikroskopi`?

**Comment by mittinatten** [comment]
Ja, ser på AFM, STM, etc mer som metoder enn objekter, så tror det er veldig lite bruk for en term for objektet. For vanlige optiske mikroskoper, som er noe som har funnets i 4-500 år, produserers i industriell skala, finnes i alle skolelab, etc, etc, er det kanskje motivert å skille de to i klassifisering. Men tviler på at vi kommer å ha dokumentgrunnlag for et skille når det gjelder disse mer spesialiserte maskinene, innen de nærmeste 100 årene :)

**Comment by bibliomari** [comment]
Gjort.
