### ISSUE TITLE
Slette 'Hull'

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#366]
Ser ut som alle bøkene handler om `Svarte hull`, så jeg tror dette er en feil fra konverteringen.

http://ask.bibsys.no/ask/action/result?cmd=&kilde=biblio&cql=bs.lokoeo-frase+%3D+%22Hull%22%20AND%20bs.bibkode=%22k%22&sortering=sortdate-&treffPrSide=50

**Comment by BioHeidi** [comment]
Gjort. Ryddet på postene.
