### ISSUE TITLE
Havbruk og Akvakultur

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#367]
Kan de slåes sammen?

Ref https://snl.no/havbruk

ping @realfagstermer/biologi

**Comment by BioHeidi** [comment]
Nei, ikke uten videre. Vi har brukt de forskjellig (stort sett, ser det kunne ha vært ryddet litt), habruk i betydningen havbeite, akvakultur i betydningen tradisjonelt (fiske)oppdrett. @Hypsibius , vil du komme med definisjoner? Forslag til endringer av termer?

**Comment by Hypsibius** [comment]
Enig med siste talar. Må tygge litt på definisjonar.

**Comment by bibliomari** [comment]
Jeg la inn en SO mellom Akvakultur og Havbruk enn så lenge, så er det et hint i Sonja om at de ikke skal slås sammen uten videre.

**Comment by danmichaelo** [comment]
Noe sier meg at vi bør slette mappingen mellom Akvakultur i Realfagstermer og Havbruk i Tekord nå :D 

![skjermbilde 2015-11-19 kl 18 52 28](https://cloud.githubusercontent.com/assets/434495/11279084/bb60cb9a-8eee-11e5-8205-48a9ed89cd30.png)

http://data.ub.uio.no/lodlive/?http://data.ub.uio.no/realfagstermer/c013800

**Comment by danmichaelo** [comment]
Hvordan skal Havbruk oversettes til engelsk hvis vi skal beholde det som egen term?

http://ub-soksed.uio.no/concepts/REAL004840

**Comment by Hypsibius** [comment]
For havbruk kan vi bruke En Sea farming, jf innf i FishBase: 

http://www.fishbase.org/glossary/Glossary.php?q=sea+farming

Der er jo et element av at det i eit hav skal finnast salt, så vi har avgrensa til det marine.

**Comment by danmichaelo** [comment]
Takk! Men definisjonen "Mariculture, marine cultivation or aquaculture of organisms *in tanks, pens, ponds or cages or net enclosed areas* in the open sea." passer ikke helt med det @BioHeidi sa tidl. om at vi har brukt havbruk om havbeite? Kan det være at havbeite skulle vært en del av akvakultur i stedet? Hilsen lett forvirret landkrabbe.

**Comment by Hypsibius** [comment]
Ikkje rart du er forvirra. Eg veit at miljøet rundt Havorskinga har skilt mellom intensivt (innramma) havbruk og ekstensivt (havbeite).  Kan vi spesifisere?

**Comment by Hypsibius** [comment]
Encyclopedia of Marine Sciences
redigert av Hanneke J.G. Baretta-Bekker,Egbert K. Duursma,Bouwe R. Kuipers: 

![image](https://user-images.githubusercontent.com/9350370/39116213-22ef0d30-46e4-11e8-99fc-9d9d73c6dc4c.png)

**Comment by kyrretl** [comment]
Prøver å ta opp denne igjen. Jobber med å oversette Havbruk til engelsk og har landet på Mariculture BF Sea farming. Skrik ut om dere ikke er enige.

Aquaculture/Akvakultur virker som et overordnet begrep som dekker ferskvann også.
Alle bøkene som har Havbruk som emneord (med unntak av en håndfull) har også Akvakultur som emneord, men det er fler som har Akvakultur som emneord (mer enn tre ganger så mange), så dette virker lovende mhp. å kunne ha Akvakultur som overordnet term til Havbruk.

MEN, når det gjelder Havbeite og Havbruk-skillet: Vi har (sannsynligvis for mange år siden) slått sammen Havbruk og Havbeite med Havbruk som hovedterm. Da mistet vi dessverre Havbeite og også distinksjonen på postene (gitt at emneordene ble satt riktig i første omgang). 

Vi kan ta en skikkelig dugnad og gå gjennom alle bøker som har Havbruk og Akvakultur som emneord og skille ut de som burde ha Havbeite fra Havbruk og innføre Havbeite som egen term igjen.

Men jeg syns at vi bør beholde Akvakultur som eget emneord og ikke slå det sammen med Havbruk!

**Comment by Caroline-A** [comment]
Jeg har tenkt litt over engelske termer. Jeg har intrykk av:
Havbeite = sea ranching, extensive sea farming. Den er en type havbruk/akvakultur.
Havbruk = mariculture, sea farming [som foreslått]. Den er en type akvakultur.
Akvakultur = aquaculture (jeg er enig i at den er overordnet pga at ferskvann er inkludert) 

Det eneste reservasjon jeg har mot denne oversettelsen er at, på den pragmatiske siden, synes jeg at aquaculture er mer brukt på engelsk enn mariculture eller sea farming. For eksempel, alle UiB kurs med "havbruk" i tittlen er oversatt som "aquaculture". Er det mulig med termer som "Aquaculture (marine)", som kunne brukes på havbruk?

_Forklaring av oversettlesen:_
Sea ranching (e.g. [her](http://en.aquaculture.ifremer.fr/World-statistics/Fish-farming/World-production/Salmon-production/Sea-ranching), [her](https://www.business.qld.gov.au/industries/farms-fishing-forestry/fisheries/aquaculture/site-selection-production/production-systems/sea-ranching-systems)) kan falle under aquaculture, men noen ganger fisheries management (e.g. [her](http://www.searanching.org/)). Jeg snublet over [en artikkel](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4981686/) som beskrev det sånn: "[...] when wild populations of marine species are declining but not extinct, [...], the mass release of cultivated individuals aims at increasing population size (sea ranching) and/or improving wild recruitment (stock enhancement).". [Dette norske selskapet](http://www.aegirhavbruk.no/index.html) beskriver havbruk og lobsterbeite som sea ranching. 

"extensive [sea] farming" høres også ut som havbeite (if. Heges definisjon) - extensive [...] farming er regnet som et type aquaculture [på EUs sider](https://ec.europa.eu/fisheries/cfp/aquaculture/aquaculture_methods_en).

**Comment by danmichaelo** [comment]
Ok, begynner omsider å skjønne at Havbruk og Havbeite nok aldri burde vært slått sammen. Har nå skilt ut Havbeite. Se om det ser greit ut (i morgen):

* [Akvakultur](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc013800)
  * [Havbruk](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc004840)
    * [Havbeite](https://app.uio.no/ub/emnesok/realfagstermer/search?uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc032080)
    * [Lakseoppdrett](https://app.uio.no/ub/emnesok/realfagstermer/search?lang=nb&uri=http:%2F%2Fdata.ub.uio.no%2Frealfagstermer%2Fc012515)

Når vi er ferdige med å flytte katalogposter over til Havbeite *kan* det kanskje også være vi skulle vurdert sammenslåing av Akvakultur og Havbruk igjen hvis overvekten av Akvakultur-materialet er knytta til havet og mtp. at begrepene brukes så mye om hverandre? Men vi kan godt la det ligge og modne seg litt.

![digiimagepage aspx](https://user-images.githubusercontent.com/434495/53107130-b1426200-3534-11e9-9915-4f996dde8d7c.jpg)

**Comment by kyrretl** [comment]
Foreslår også at vi ikke har Akvakultur BF Fiskeoppdrett

jmf: #1332

Siden vi foreslår at vi går gjennom alle akvakultur-bøker uansett, kan vi skille ut Fiskeoppdrett som egen term. 
Et snevert søk på 'inneholder' oppdrett i emnesøket gir:

* Blåskjelloppdrett (5)
* Kamskjelloppdrett (4)
* Muslingoppdrett (9)
* Østersoppdrett (4)

Foreslår at vi tar Muslingoppdrett BF Blåskjelloppdrett BF Kamskjelloppdrett BF Østersoppdrett.

Og så har vi:

* Lakseoppdrett (27)
* Ørretoppdrett (7)

Vi kan da også legge til i Lakseoppdrett og Ørretoppdrett i tillegg når vi går gjennom Akvakultur for å skille ut Fiskeoppdrett

**Comment by Hypsibius** [comment]
Istemmer, @kyrretl

**Comment by Caroline-A** [comment]
En kommentar på engelsk - Lakseoppdrett har ikke en oversettelse og ørretoppdrett har "Trout selective breeding" "Trout artificial selection"; begge to er låst i soksed. Jeg tror at dette bør endres. Tenkte at vi kunne bruke farming, i.e. salmon farming, trout farming? Det er også "[aquaculture of salmonids](https://en.wikipedia.org/wiki/Aquaculture_of_salmonids)".

**Comment by danmichaelo** [comment]
Har fisket ;)

(Hvis du kommer over begreper som er låst uten engelsktermer er det fordi synkroniseringen med Sonja har feilet og låsen blitt hengende igjen. Jeg har et script som fikser dette, men foreløpig har jeg bare kjørt det manuelt i ny og ne fremfor å sette det opp til å kjøre automatisk)
