### ISSUE TITLE
Elementer

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#368]
må ryddes. I stor grad brukt om `Grunnstoffer`, men også innslag av alt fra `Elementmetoden` til `Transgene elementer` og jeg vet ikke hva :)

https://katapi.biblionaut.net/documents?q=real:Elementer&show=sh

**Comment by danmichaelo** [comment]
Klar til sletting. Har gått gjennom katalogpostene, og på nesten alle fantes det allerede mer presise emneord fra før.

**Comment by bibliomari** [comment]
Gjort
