### ISSUE TITLE
Efemerider = Nautiske almanakker?

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#370]
Vi har formemnet Nautiske almanakker, og emneordet Efemerider. Kan disse slås sammen?

@superLine @mittinatten @danmichaelo

**Comment by Hypsibius** [comment]
Ikkje om nokon av dei handlar om desse? https://en.wikipedia.org/wiki/Ephemeridae

**Comment by bibliomari** [comment]
Det gjør de ei :)

**Comment by Hypsibius** [comment]
Nei, såg det når eg endeleg får somla meg til å søke. Skulle såklart dobbeltsjekka først....

**Comment by superLine** [comment]
snl forklarer efemerider med astronomiske årbøker. Nautiske almanakker er en undergruppe av almanakker.
astrothesaurus.org sier:
Almanacs 
Broader Term(s):
    Astronomical reference materials
Narrower Term(s):
    Nautical almanacs
Use For:
    Almanachs

**Comment by superLine** [comment]
Ephemerides

Broader Term(s):
    Astronomical reference materials

**Comment by danmichaelo** [comment]
Hm.. så da beholder vi begge som de er? Eller skulle `Efemerider` vært form-emne? Og trengs en SO mellom dem?

**Comment by bibliomari** [comment]
Endret til form. Muligens på en klønete måte.
