### ISSUE TITLE
Brukerveiledning: er vel en form-term?

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#377]
Får kanskje ikke brukt LOKAR, men kun brukt på tre bøker: https://okapi.biblionaut.net/documents?q=real:Brukerveiledning&show=sh , hvorav to *er* brukerveiledninger, mens den siste handler om det. Skal jeg bare fikse, @bibliomari ?

**Comment by bibliomari** [comment]
Jatakk @danmichaelo

**Comment by danmichaelo** [comment]
Gjort
