### ISSUE TITLE
Slå sammen 'Kraftforsyning' og 'Kraftproduksjon'

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#378]
'Kraftproduksjon' er vel egentlig en *del av*  'Kraftforsyning', men tenker at vi ikke trenger den spesifisiteten. Det meste om kraftproduksjon er vel dessuten spesifikt hvor hver type kraftverk (vannkraft, kullkraft, ...).

**Comment by mittinatten** [comment]
'Energiproduksjon' har vi også. Det er vel det man mener med 'Kraftproduksjon', men 'Energi-' er bedre. 'Energiforsyning' er ikke en term, men hvis vi skal gruppere burde vi kanskje lage den og legge de tre andre som BF. Termen 'Elektrisitetsproduksjon' burde også kunne legges som BF.

**Comment by bibliomari** [comment]
Mener dere altså: 

Kraftforsyning 
BF
Kraftproduksjon
Energiproduksjon
Energiforsyning
Elektrisitetsproduksjon

?

@danmichaelo @mittinatten 
@BioHeidi Du kan jo også ta en titt på denne, jf vår prat om Metabolisme.

**Comment by mittinatten** [comment]
Ja, men med Energiforsyning som foretrukket, siden "kraft-" er litt rar bruk av det fysikalske begrepet kraft. Mener jeg i hvert fall :)

**Comment by danmichaelo** [comment]
Hehe, ja, enig :)

**Comment by Hypsibius** [comment]
Enig med Simon

**Comment by bibliomari** [comment]
Gjort.
