### ISSUE TITLE
Services BF Tjenesteyting

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#379]
Denne er litt underlig. Oppdaget av nynorskoversetterne: http://trans.biblionaut.net/concepts/REAL007906?view=nn&q=has:editorialNote,graph:local

Tenkte først på å bytte om på foretrukket og ikke-foretrukket term, men det ser ikke ut som den egentlig er i bruk, så da kan vi kanskje bare slette den?

**Comment by bibliomari** [comment]
Slettet.
