### ISSUE TITLE
Storfe, Kuer og Kyr

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#381]
Kommentar fra nynorsk-oversetterne på [Kyr](http://trans.biblionaut.net/concepts/REAL005306?view=nn&q=has:editorialNote,graph:local):

> Kyr (BM, NN) er synonymt med kuer (BM), so dette oppslaget skal nok vera "Storfe". "Kuer" er allereie eit BM-oppslag der den nynorske omsetjinga vert "Kyr".

**Comment by bibliomari** [comment]
Gjort. @bioheidi tar Oksefamilien

**Comment by Hypsibius** [comment]
Glimrande!Så legg vi til evt BF-termar ved mehov (typ kviger etc...?

**Comment by BioHeidi** [comment]
Ja. Ved møhov.

**Comment by Hypsibius** [comment]
Mø-klov!

**Comment by BioHeidi** [comment]
hahaha
