### ISSUE TITLE
Bergverk, Bergverksdrift, Bergvesen, osv…

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#385]
Vi har `Bergverk`, `Bergverksdrift` og `Bergvesen`: Disse bør vel kunne slås sammen i ett begrep: `Bergverk` eller `Bergverksdrift` ?

Tekord har videre slått sammen `Gruvedrift` og `Bergverk`, men det ønsker kanskje ikke vi, eller? @kristinran ? Jeg er ikke sikker på forskjellen selv, men fra Wikipedia ser det litt ut som bergverk omfatter både Gruver og Steinbrudd...?

Okapi: [Gruvedrift](https://okapi.biblionaut.net/documents?q=real:Gruvedrift), [Bergverk](https://okapi.biblionaut.net/documents?q=real:Bergverk)

**Comment by kristinran** [comment]
Bergverk kan brukes både om gruver og dagbrudd. Det er en forskjell på de tre begrepene: Bergverk kan for eksempel handle om historiske brudd og gruver (uttak av heller, brynesteiner, gamle jerngruver, klebersteinsbrudd etc). bergverksdrift vil omfatte teknologi, driftsformer, utstyr, metoder. Bergvesen er vel mer politikk og samfunnsgeografi?? Har også en historisk side, om utviklingen av bergindustrien

**Comment by danmichaelo** [comment]
Tja, da lar vi de være.

**Comment by BioHeidi** [comment]
For letthets skyld gjenåpner jeg denne og spør om vi kan slå sammen `Gruver` og `Gruvedrift`? Eller er det tenkt at gruver skal forbeholdes spesifikke gruver? Da må det isåfall ryddes litt.

Og ja, i dag er jeg på G...

**Comment by kristinran** [comment]
Det er vel forskjell på gruver og gruvedrift: gruver er igjen historiske og nåværende, kan være om geologien, produktene etc. Mens gruvedrift ville jeg brukt om det tekniske/ingeniørmessige ved selve driften. eventuelt også med økonomi tilknyttet industrien.

**Comment by BioHeidi** [comment]
Takk Kristin! Da beholder vi begge, og jeg ser om jeg klarer å rydde.
