### ISSUE TITLE
Kjernekraft, kjernefysikk, atomfysikk

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#386]
Stemmer det at disse tre er hvert sitt emneord? 

@mittinatten @danmichaelo

**Comment by bibliomari** [comment]
Altså: Kan de ryddes, få noen SO eller slås sammen på noen måte? Vi har også Kjernekjemi, Kjernefusjon.

**Comment by mittinatten** [comment]
Kjernekraft, kjernefysikk og atomfysikk er tre forskjellig ting, ja.

Kjernefusjon kan slås sammen med Fusjon. Fusjon foretrukket. SO til Fisjon.

Kjernekjemi kan vi beholde.

**Comment by bibliomari** [comment]
Takk :) Gjort.
