### ISSUE TITLE
Bevegelighet

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#389]
Kommentar fra nynorsk-oversetterne på [Bevegelighet](https://trans.biblionaut.net/concepts/REAL005957?view=nn&q=has:editorialNote,graph:local):

> Dette er veldig generelle søkjetermar. Sikre på at de vil bruka dei slik når det dreier seg om éin katalogpost?

**Comment by Hypsibius** [comment]
Ser forøvrig for meg to bruksområde, som begge er klart spesifikke. Det eine er som motsetning til sessil livsstil eller sessile stadiar (rurlarve kontra fastsittande voksen), det andre eksempelvis brukt om ledd, der ein anten kan redusere rørlegheit som konskekvens av skade eller av evolusjon. 

Om det er det beste emneordet for denne posten? Tvilande. Så for meg kan den slettast, og så tar vi termen når det kjem eit betre eksempel....

**Comment by danmichaelo** [comment]
Slettet
