### ISSUE TITLE
Bioovervåking

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#391]
Kommentar fra nynorsk-oversetterne på [Bioovervåking](https://trans.biblionaut.net/concepts/REAL012767?view=nn&q=has:editorialNote,graph:local):

> "Biologisk overvåkning"-forma burde vera med på BM.

@realfagstermer/biovitenskap

**Comment by Hypsibius** [comment]
Og kva er det? Kamera over alt på Kristine Bonnevies hus?

**Comment by BioHeidi** [comment]
Heheh!
Men ja.
