### ISSUE TITLE
Blodfarvestoffer

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#392]
Kommentar fra nynorsk-oversetterne på [Blodfarvestoffer](https://trans.biblionaut.net/concepts/REAL003708?view=nn&q=has:editorialNote,graph:local):

> Burde BM ha forma "Blodfargestoff" i tillegg?

Det burde kanskje til og med være foretrukken term?

**Comment by Hypsibius** [comment]
Jepp!

**Comment by BioHeidi** [comment]
Heme

**Comment by BioHeidi** [comment]
Og kanskje porfyrin?

**Comment by Hypsibius** [comment]
I staden for? Eller BH? Det finst jo fleire, i andre dyregrupper

**Comment by BioHeidi** [comment]
Tenkte BF, og de mest vanlige. Kan sikkert ta med flere, jeg kommer ikke på noen.

**Comment by Hypsibius** [comment]
Litt usikker på vka som er fargestoffet i hemocyanin? Hemerythrin?

**Comment by danmichaelo** [comment]
Nå fiksa jeg 

```
Blodfargestoff
BF Blodfarvestoffer
BF Hemokromer
BF Heme
EN Coloring matter of blood
EN Hemochromes
EN Heme
EN Haem
```

Bare å legge til flere BF-er! Hvis noen har en bedre foretrukket engelsk term tas det også imot med takk!
