### ISSUE TITLE
Cascading style sheet

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#393]
Kommentar fra nynorsk-oversetterne på [Cascading style sheet](https://trans.biblionaut.net/concepts/REAL012162?view=nn&q=has:editorialNote,graph:local):

> JEM: Det ser ut som standardtermen er i fleirtal: "Cascading style sheets". Bruke på BM òg?

Og kanskje CSS burde være foretrukken term her?

**Comment by mittinatten** [comment]
Enig, CSS burde være foretrukken term og det burde være fleirtal.

**Comment by bibliomari** [comment]
gjort
