### ISSUE TITLE
Deep space og deep-space

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#395]
Kommentar fra nynorsk-oversetterne på [Deep space](https://trans.biblionaut.net/concepts/REAL001946?view=nn&q=has:editorialNote,graph:local):

> Slå saman med Deep-space? Dessutan: "Ytre rom" på BM og?

På WP er "Ytre rom" koblet til "Outer space". Usikker på om "Deep space" er en veldefinert term. Astrotesaurusen har ikke oppslag på "Deep space", kun [Deep space probes](http://www.altbibl.io/astrothesaurus/uat/termrecords/Deep+space+probes.html). Men det ser ut som "Ytre rom" også kan være ok på disse postene, men . Ihvertfall en av bøkene handler om [NASA Deep Space Network](https://en.wikipedia.org/wiki/NASA_Deep_Space_Network).

@superLine

**Comment by mittinatten** [comment]
Også usikker på om dette er en meningsfull term. Før jeg åpnet lenkene trodde jeg det var det samme som [Deep Field](https://en.wikipedia.org/wiki/Hubble_Deep_Field), som noe helt annet. *Deep* har litt samme kvalitet som *ny*, i at det fort finnes noe annet som er nyere og/eller dypere.

**Comment by danmichaelo** [comment]
Godt poeng :)

**Comment by danmichaelo** [comment]
Slettet
