### ISSUE TITLE
Rokker

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#399]
Kommentar fra nynorsk-oversetterne på [Rokker](https://trans.biblionaut.net/concepts/REAL011461?view=nn&q=-exists:prefLabel@nn):

> Halla, bibsys-gjengen! Dette omgrepet bør leggjast inn som ei alternativ bokmålsform under omgrepet «skater».

@realfagstermer/biovitenskap

**Comment by BioHeidi** [comment]
Kan vi gjøre noe nå da?

**Comment by danmichaelo** [comment]
Nope, men vi kan jo bestemme oss for hva vi skal gjøre når vi kan gjøre noe igjen ;)

**Comment by Hypsibius** [comment]
Ja, det synest eg det er greitt å gjere, etter å ha våre på emneordsAlmakurs :-) Vi må anta at det finst eit liv etter dette. Måtte gå litt tilbake og sjekke systematikk her, for alt er ikkje som det var då eg tok Ichthyologikurs:

Vår salige professor omtalte overorden Batoidea (ikkje gyldig term - lenger?!?) som 'skater', men berre fam. Rajidae (valid term) som ekte skater.  

Alle familiane i orden Myliobatiformes (Valid term) omtalar han som rokker. 

Eg har derfor oppfatta det slik at termane ikkje er heilt utbyttbare?

**Comment by Hypsibius** [comment]
ITIS ikkje hundre prosent på linje, på engelsk heiter det skates og rays litt meir om kvarandre: 

http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=649685

'Skates' og 'rays'

http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=160806

(Berre 'rays')

**Comment by danmichaelo** [comment]
så...?

**Comment by Hypsibius** [comment]
Det vil gjerne seie at skates/rays ikkje korresponderer fullstendig med hhv skater/rokker. Vi kunne late som om engelsk ikkje er eit moment her, sidan norsk inndeling i hovudsak følgjer stystematisk inndeling. Eller vi kan berre legge skater BF rokker EN Skates EN Rays. Kva seier @BioHeidi ? Eit argument for dette, er at dei fleste bøkene eg får treff på (på begge) omhadnlar bruskfisk generelt, og at det derfor blir unødig spesifikt å dele. Resten av bokene handlar om spinning...

Så sulla ho mor på rokken sin....

**Comment by danmichaelo** [comment]
suddelidi suddelida…

**Comment by Caroline-A** [comment]
Jeg kom til å lage en post om å sammenslå skater og rokker akkurat som du har foreslått, @Hypsibius @danmichaelo . Så på soksed at begge to var mappet til det samme (https://en.wikipedia.org/wiki/Batoidea), og begge to var oversatt som EN Rays. Så jeg vil få EN skates med. Å sammenslå kunne gjør det enklere på begge språk, men jeg vet ikke hva skjer med Batoidea som LA term - [på WORMS er den ikke sjekket](http://www.marinespecies.org/aphia.php?p=taxdetails&id=10193).

**Comment by danmichaelo** [comment]
Bare for å være helt sikker: Vi slår de sammen slik?

```
Skater
BF Rokker
EN Skates
EN Rays
LA Batoidea (inntil videre)
```

**Comment by Hypsibius** [comment]
Ok, la Batoidea stå inntil vidare. Det er mogeleg vi heller skulle bruke LA Rajiformes, men vi avventar!

**Comment by BioHeidi** [comment]
Gjort, og la på latin Rajiformes som foretrukken, Batoidea (gammel form) som BF
