### ISSUE TITLE
Fjordforurensning (og alle de andre vannforurensningene)

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#401]
Er det en glipp at fjordforurensning er beholdt som emneord? 1 treff i BIBSYS. 

Vi har også: 

Vannforurensning
Ferskvannsforurensning
Marin forurensning 
Grunnvannsforurensning
Akvatisk toksikologi

... og det ser ut som det er ryddet i disse.

**Comment by bibliomari** [comment]
(Hjelpes, er det meningen at Rydde-labelen er borte, @danmichaelo ?)

**Comment by bibliomari** [comment]
@BioHeidi @Hypsibius

**Comment by danmichaelo** [comment]
(Eh, ja, jeg omdøpte den til "trenger katalogrydding", vi kan evt. diskutere det videre i #281 :))

**Comment by BioHeidi** [comment]
Ja det er nok en glipp. Vi kan fjerne emneordet på posten og i roald, evt legge det inn som BF under Vannforurensning.

**Comment by danmichaelo** [comment]
Gjort: `Marin forurensning BF Fjordforurensning`
