### ISSUE TITLE
Mobilantenner?

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#403]
Jeg savner noe for det engelske *Cell tower*. Brukte `Antenner` og `Mobil kommunikasjon` på denne, men hadde vært bedre med en egen term: https://bora.uib.no/handle/1956/10302

`Mobilantenner` kan kanskje tolkes som både antennen i telefonen og på stasjonen, er `Mobilmaster` bedre?

**Comment by danmichaelo** [comment]
Kan `Basestasjoner` funke?

**Comment by mittinatten** [comment]
Ja, det er bedre. Kanskje med `BF Mobilmaster`, så blir det tydelig at dreier sig om basestasjoner for mobiltelefoni. Og/eller med en definisjon.

**Comment by danmichaelo** [comment]
Gjerne med `BF Mobilmaster`, ja. SNL nevner også `Basisstasjon` som en alternativ term vi kan ta med.

**Comment by bibliomari** [comment]
Lagt til.
