### ISSUE TITLE
Glimt og utbrudd

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#404]
Vi har `Gammaglimt`, `Terrestriske gammaglimt` og `Gammastråleutbrudd`. Jeg regner med utbrudd kommer fra engelske *burst* (angitt som EN i termen) og glimt fra *flash*. Wikipedia skiller ikke på burst og flash (redirect mellom de). Har søkt i våre andre leksika, men finner ingen annen artikel som snakker om forskjeller mellom de to. SNL bruker Gammaglimt. Så jeg foreslår

      Gammaglimt
      BF Gammastråleutbrudd
      EN Gamma-ray bursts
      EN Gamma-ray flashes
      SO Terrestriske gammaglimt

Tror ikke vi trenger definisjoner for å skille mellom terretriske og ikke-terrestriske (?). 
@superLine @danmichaelo

**Comment by mittinatten** [comment]
Nå så jeg at det er en skrivefeil i "Terr*i*striske gammaglimt"

**Comment by superLine** [comment]
Høres veldig fornuftig ut! astrothesaurus og "dictionary of astronomy" bruker bare gamma-ray bursts

**Comment by danmichaelo** [comment]
Gjort! Også fiksing av skrivefeilen  "Terristriske gammaglimt"
