### ISSUE TITLE
Atmosfæriske elver

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#405]
Gir det mening å innføre termen `Atmosfæriske elver`?

https://en.wikipedia.org/wiki/Atmospheric_river

Belegg: https://bora.uib.no/handle/1956/10335

@mzyg @kristinran

**Comment by mzyg** [comment]
Jeg har faktisk ikke hørt så mye om dette tidligere men det har blitt ganske populært i det siste :-). Jeg antar at det kommer flere publikasjoner om dette (også her fra Bergen) og vi kan gjerne innføre en ny term.

**Comment by bibliomari** [comment]
Lagt til.
