### ISSUE TITLE
Radiobrikker og Radiofrekvensidentifikasjon

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#406]
Vil dere ha begge disse emneordene? Som vanlig synes nok jeg det er helt ok (tror jeg foretrekker det), men jeg har lyst på en SE OGSÅ mellom dem. Også tenkte jeg kanskje noen syntes det var like greit å slå sammen, OG at litteraturen vår sannsynligvis handler om teknologien snarere enn om de konkrete dingsene? 

Men det er vel altså hhv en teknologi og noen dingser som utnytter denne teknologien.

**Comment by mittinatten** [comment]
Uten å være ekspert på teknologien har jeg vanskelig å se for meg bøker som bare handler om det ene men ikke det andre. Så jeg stemmer for sammenslåing, og legge til BF RFID hvis det ikke er der allerede.

**Comment by danmichaelo** [comment]
Slått sammen. Landet på `Radiofrekvensidentifikasjon` som foretrukket term.
