### ISSUE TITLE
Plantevernmidler vs. pesticider

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#407]
Hva er forholdet mellom plantevernmidler og pesticider, @BioHeidi og @Hypsibius ? Vi har begge emneordene. Vi har også herbicider og biocider, hvis det har noen betydning for dette. 

Ønsker meg gjerne en forklaring, og eventuelt SE OGSÅ hvis det er på sin plass.

**Comment by BioHeidi** [comment]
[SNL] (https://snl.no/plantevernmidler) definerer det ganske bra:
>Plantevernmidler, kjemiske midler som brukes mot skadegjørere (plantesykdommer, skadedyr og ugress) på planter. De inngår (sammen med kjemiske midler mot skadelige organismer i hus og hjem, lager, tekstiler, mot helsefarlige insekter osv.) i hovedbetegnelsen pesticider. Etter de organismer plantevernmidlene er rettet mot, inndeles de gjerne i følgende grupper (de internasjonale betegnelsene i parentes): soppmidler (fungicider), ugressmidler (herbicider), insektmidler (insekticider), middmidler (akaricider), nematodemidler (nematicider), sneglemidler (molluskicider) og gnagermidler (rodenticider). De fem siste er skadedyrmidler.

**Comment by bibliomari** [comment]
Av det slutter jeg:

Pesticider 
DE Kjemiske midler mot skadelige organismer som griper forstyrrende inn i våre omgivelser (på planter, i hus og hjem, lager, tekstiler osv.), eller som er ytre parasitter på mennesker og husdyr. (SNL)
SO Plantevernmidler
SO Herbicider 
SO Insektmidler

Plantevernmidler
DE Kjemiske midler som brukes mot skadegjørere (plantesykdommer, skadedyr og ugress) på planter. (SNL)

Vi har også Sprøytemidler, det er antagelig en blanding av de over? Jeg har dessuten lyst til å gjøre om Herbicider BF Ugressmidler til Ugressmidler BF Herbicider. 

Og til slutt: 

Ugressmidler
SO Ugressbekjempelse
SO Pesticider

?

**Comment by BioHeidi** [comment]
Sprøytemidler ser ut til å være hovedsakelig brukt om plantevernmidler i trefflisten, men ikke 100% konsekvent. Bra nok, kanskje. Slå sammen.
Synes egentlig at termen Ugressbekjempelse er litt overflødig, legg heller den inn som BF Ugressmidler.

Ellers ok.

**Comment by Hypsibius** [comment]
Enig med @BioHeidi

**Comment by danmichaelo** [comment]
Slo sammen Plantevernmidler BF Sprøytemidler
