### ISSUE TITLE
Sosial økologi slås sammen med Sosialøkologi?

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#408]
Ja, disse to kan vel slås sammen, @BioHeidi ? Hva er forholdet til Humanøkologi?

**Comment by BioHeidi** [comment]
Ja det kan de. Sosialøkologi er en underinndeling av Humanøkologi. Vi kan også slå Sosial økopolitikk sammen med Sosialøkologi. Greit å beholde både Humanøkologi og Sosialøkologi.

**Comment by bibliomari** [comment]
Da blir det:

Humanøkologi 
SO Sosialøkologi

Sosialøkologi
BF Sosial økologi 
BF Sosial økopolitikk
SO Humanøkologi

**Comment by BioHeidi** [comment]
Men trenger vi SO? Skal vi ikke heller lege inn hierarkisk kobling? Nå er jo det mulig som et prøveprosjekt i Roald.

**Comment by bibliomari** [comment]
Gjerne legge inn den hierarkiske koblingen, men SO må uansett med (mener jeg). Som du sier, hierarkiet er jo på prøvestadiet.

**Comment by Hypsibius** [comment]
Høyrest bra ut. Litt spent på det herarkiet

**Comment by bibliomari** [comment]
gjort sånn ca
