### ISSUE TITLE
Botanisk nomenklatur og Plantenavn slås sammen?

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#410]
Ja, disse kan vel slås sammen, @BioHeidi og @Hypsibius ?

**Comment by BioHeidi** [comment]
Ja. Plantenavn som foretrukken term, så trenger vi ikke å lage definisjon...

**Comment by Hypsibius** [comment]
I'm in!

**Comment by danmichaelo** [comment]
Gjort! Plantenavn som foretrukken term
