### ISSUE TITLE
Teknisk skriving

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#413]
Jeg ønsker meg Teknisk skriving EN Technical writing. F.eks. denne boka: 

http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS114167257&vid=UBO

Jeg har latt meg fortelle at dette er en egen ferdighet som ikke bør sauses sammen med "vanlig skriving", faglig forfatterskap.

**Comment by Hypsibius** [comment]
Høyrest tilforlateleg ut.

**Comment by bibliomari** [comment]
Gjort
