### ISSUE TITLE
Statsforvaltning og Statsforvaltningen

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#414]
Disse to kan sikkert slås sammen. Se også på om Sentralforvaltningen kan få være med (jf humord).

**Comment by Hypsibius** [comment]
Er Statsforvaltningen i dette tilfelle å sjå som ein institusjon?

**Comment by danmichaelo** [comment]
eller en type institusjon? Slo sammen som `Statsforvaltning BF Statsforvaltningen`

**Comment by danmichaelo** [comment]
Stoler på Humord her, så nå har vi: `Sentralforvaltning BF Sentraladministrasjon BF Statsforvaltning BF Statsforvaltningen`
