### ISSUE TITLE
Resirkulering vs. gjenvinning

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#417]
Ser ut som disse kan slås sammen. Protester/kommentarer? Mye skummelt avfall her, så jeg spør særlig @danmichaelo og @mittinatten tror jeg.

**Comment by Hypsibius** [comment]
Slå saman!

**Comment by danmichaelo** [comment]
Gjort. Jeg brukte gjenvinning som foretrukket, siden gjenvinning inkluderer energigjenvinning. Og la til UT (snikhierarkisering!)
