### ISSUE TITLE
Samfunnsendringer = Samfunnsutvikling?

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#419]
(Maris huskeliste. Sjekk om disse kan/bør slås sammen)

**Comment by bibliomari** [comment]
Og evt Sosial endring (jf Humord)

**Comment by Hypsibius** [comment]
Skulle meine det. Sjølv om 'utvikling' ser ut til å få folk til å tenke at det går i ei spesiell retning

**Comment by mittinatten** [comment]
Det problemet har vi med evolusjon også...

**Comment by Hypsibius** [comment]
Jepp!

**Comment by danmichaelo** [comment]
Slo sammen alle tre. Stoler på at Humord-folket også har tenkt litt på dette.
