### ISSUE TITLE
Læringsprosesser

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#422]
Brukt to ganger. Jeg mener det kan slås sammen med Læring, eller slettes.

**Comment by BioHeidi** [comment]
Jeg tenkte først at det kanskje var en litt sær biologiterm, som pavlovsk eller operant læring eller noe med sosiale insekter og sånt, men ser på trefflisten at det ikke er det. Stemmer for sletting.

**Comment by Hypsibius** [comment]
Me too!

**Comment by danmichaelo** [comment]
Slettet! (ikke gjenvunnet)
