### ISSUE TITLE
Leker

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#429]
Leker kan slettes; forekommer (iflg Okapi) bare en gang, og da på et dokument som også har Olympiske leker.

**Comment by Hypsibius** [comment]
Istemmer!

**Comment by bibliomari** [comment]
Gjort

**Comment by danmichaelo** [comment]
Gjenåpner saken så jeg ikke glemmer at LOKAR feilet for denne. Kom over en post som ikke lot seg redigere via API-et, og må finne ut hvorfor.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<web_service_result xmlns="http://com/exlibris/urm/general/xmlbeans">
	<errorsExist>true</errorsExist>
	<errorList>
		<error>
			<errorCode>402203</errorCode>
			<errorMessage>Input parameters mmsId 999519317504702201 is not valid.</errorMessage>
			<trackingId>E01-2405183646-TDPEP-AWAE1141183604</trackingId>
		</error>
	</errorList>
</web_service_result>
```

**Comment by BioHeidi** [comment]
Det er fordi errors exist. True?

**Comment by danmichaelo** [comment]
Very much so :D Men innholdet i `<errorMessage>` er mer på viddene... Det virker som det er en catch-all-feilmelding som  egentlig burde hatt ordlyden "An unknown error has occured" :/

Når jeg prøvde på nytt en uke senere funka det, så det må ha vært et sandkorn i maskineriet som blåste vekk.

**Comment by BioHeidi** [comment]
Regnet vekk, mener du vel.

**Comment by danmichaelo** [comment]
> Regnet vekk, mener du vel.

Vet ikke helt, maskineriet er tross alt i Israel. Det regner riktignok der også, men ikke så mye som her ;)
