### ISSUE TITLE
Biografistrengene

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#43]
Oppdaget at vi hadde både `Fysikk : Biografier` og `Fysikere : biografier`, og husket ikke helt hvilken form som er anbefalt.. Fant en epost fra @bibliomari fra 14. februar med emnet "Faget og dets utøvere":

> Berit minnet meg om dette som vi diskuterte i fjor: Skal fagets utøvere ha eget emneord (fysikere) eller skal vi bruke f.eks. Fysikk : Biografier.
> 
> Vi valgte visst det siste, men jeg angrer og rydder! Både Humord og LC har egne emneord for utøverne, som Dan Michael da også meget klokt påpekte.
> 
> Jeg kommer til å lage et eksempel om dette i retningslinjene; skrik ut hvis dere er helt uenige.

Men hva som skjedde etterpå vet jeg ikke. Situasjonen er ihvertfall fortsatt uoversiktlig. Hvis vi deler opp i "utøvere" og "fag" har vi følgende strenger med "utøvere":
- Amerikanske matematikere : Biografier _(Bør vel deles opp i Matemateikere : USA : Biografier hvis vi skal ha slik inndeling)_
- Astrofysikere : Biografier
- Astronomer : Biografier
- Biologer : Biografier
- Botanikere : Biografier
- Ektefeller : Biografier
- Farmasøyter : Biografier
- Fysikere : 1600-tallet : Biografier
- Fysikere : Biografier
- Geokjemikere : Biografier
- Havforskere : Biografier
- Instrumentmakere : Biografier
- Kjemikere : Biografier
- Krystallografer : Biografier
- Kvinner : Biografier _(Vitenskapskvinner? Det bør vi kanskje ta i en sak for seg)_
- Leger : Biografier
- Matematikere : 1700-tallet : Biografier
- Matematikere : Biografier
- Matematikere : Norge : 1800-tallet : Biografier
- Naturforskere : Biografier
- Nobelprisvinnere : Biografier
- Oppfinnere : England : Biografier
- Ornitologer : Biografier
- Vitenskapelig personale : Biografier
- Vitenskapsmenn : 1600-tallet : Biografier
- Vitenskapsmenn : Biografier
- Zoologer : Biografier

og følgende med "fag":
- Alger : Biografier
- Alkymi : Biografier
- Anvendelser : Biografier
- Apotek : Biografier
- Apotekere : Biografier
- Arvelære : Biografier
- Astrobiologi : Biografier
- Astrofysikk : Biografier
- Astrometri : Biografier
- Astronauter : Biografier
- Astronomi : Biografier
- Astronomihistorie : Biografier
- Atferd : Biografier
- Atomfysikk : Biografier
- Atomvåpen : Biografier
- Bergensskolen : Biografier
- Bevaringsbiologi : Biografier
- Biokjemi : Biografier
- Biologi : Biografier
- Biomedisin : Biografier
- Biometri : Biografier
- Bløtdyr : Biografier
- Botanikk : Biografier
- Bølgemekanikk : Biografier
- Cray : Biografier
- Darwinismen : Biografier
- Datahistorie : Biografier
- Differensialgeometri : Biografier
- Dna : Biografier
- Dyr : Biografier
- Ekspedisjoner : Biografier
- Elektrisitet : Biografier
- Elektrokjemi : Biografier
- Elektromagnetisme : Biografier
- Elektronikk : Biografier
- Entomologer : Biografier
- Etnografi : Biografier
- Etologi : Biografier
- Evolusjon : Biografier
- Evolusjonsteorien : Biografier
- Fargestoffer : Biografier
- Farmasi : Biografier
- Farmasihistorie : Biografier
- Filosofi : Biografier
- Form : Biografier
- Forskere : Biografier
- Forskning : Biografier
- Fosfor : Biografier
- Fotometri : Biografier
- Foucaults pendel : Biografier
- Fugler : Biografier
- Fysikalsk kjemi : Biografier
- Fysikk : 1900-tallet : Biografier
- Fysikk : Biografier
- Fysikkhistorie : Biografier
- Galakser : Biografier
- Genetikk : Biografier
- Geofag : Biografier
- Geofysikk : Biografier
- Geografi : Biografier
- Geokjemi : Biografier
- Geologer : Biografier
- Geologi : Biografier
- Geologiens historie : Biografier
- Geometri : Biografier
- Geovitenskap : Biografier
- Gödels teorem : Biografier
- Hager : Biografier
- Havforskning : Biografier
- Hvalfangst : Biografier
- Ibm : Biografier
- Illustrering : Biografier
- Informasjonssystemer : Biografier
- Informasjonsteknologi : Biografier
- Informatikk : Biografier
- Ingeniørfag : Biografier
- Instrumenter : Biografier
- Internett : Biografier
- Jord-måne-systemet : Romfart : Biografier
- Kaosteori : Biografier
- Karriere : Biografier
- Kirker : Biografier
- Kjemi : Biografier
- Kjemihistorie : Biografier
- Kjemiteknikk : Biografier
- Kjernefysikk : Biografier
- Kjernekjemi : Biografier
- Kosmogoni : Biografier
- Kosmologi : Biografier
- Kronologi : Biografier
- Krystallografi : Biografier
- Kunstig intelligens : Biografier
- Kvantefysikk : Biografier
- Kvantegravitasjon : Biografier
- Kvantemekanikk : Biografier
- Kvanteteori : Biografier
- Kybernetikk : Biografier
- Laboratorier : Biografier
- Lamarckisme : Biografier
- Lasere : Biografier
- Lie-grupper : Biografier
- Logikk : Biografier
- Lyell : Biografier
- Mac os : Biografier
- Matematikk : Biografier
- Matematikkhistorie : Biografier
- Medisin : Biografier
- Medisiner : Biografier
- Meteorologi : Biografier
- Miljø : Biografier
- Miljøbevegelser : Biografier
- Miljøvern : Biografier
- Molekylærbiologi : Biografier
- Museer : Biografier
- Muslinger : Biografier
- Naturhistorie : Biografier
- Naturvern : Biografier
- Naturvitenskap : Biografier
- Nevrofysiologi : Biografier
- Nobelprisen : Biografier
- Nordlys : Biografier
- Nøytroner : Biografier
- Optikk : Biografier
- Organisk kjemi : Biografier
- Ornitologi : Biografier
- Oseanografi : Biografier
- Paleobotanikk : Biografier
- Paleontologi : Biografier
- Partikkelakseleratorer : Biografier
- Partikkelfysikk : Biografier
- Planeter : Biografier
- Plantegeografi : Biografier
- Planteøkologi : Biografier
- Polarekspedisjoner : Biografier
- Portretter : Biografier
- Radioaktivitet : Biografier
- Radioastronomi : Biografier
- Radiokjemi : Biografier
- Realfag : Biografier
- Reiser : Biografier
- Relativitetsteorien : Biografier
- Romfart : Biografier
- Romforskning : Biografier
- Røntgenkrystallografi : Biografier
- Samfunn : Biografier
- Samlinger : Biografier
- Science fiction : Biografier
- Solfysikk : Biografier
- Solsystemet : Biografier
- Sorte hull : Biografier
- Sosialantropologi : Biografier
- Spillteori : Biografier
- Spionasje : Biografier
- Stater : Biografier
- Statistikk : Biografier
- Stjerner : Biografier
- Superdatamaskiner : Biografier
- Systemteori : Biografier
- Teknologi : Biografier
- Teleskoper : Biografier
- Teoretisk fysikk : Biografier
- Tex : Biografier
- Tid : Biografier
- Tidsbegrepet : Biografier
- Transistorer : Biografier
- Ufullstendighetsteoremer : Biografier
- Universiteter : Biografier
- Utstillinger : Biografier
- Venuspassasjer : Biografier
- Vitenskap : Biografier
- Vitenskapsfilosofi : Biografier
- Vitenskapshistorie : Biografier
- Zoologi : Biografier
- Økologi : Biografier
- Økonomi : Biografier

Mye å ta tak i her.. men er det enighet om at vi primært bruker utøverformen, og at vi dermed omskriver f.eks. "Økonomi : Biografier" → "Økonomer : Biografier"? Isåfall kan vi jo f.eks. begynne med å lage en liste over de strengene som er trivielle å omskrive? Sletter vi så "Matematikk : Biografier", "Fysikk : Biografier", osv.?

**Comment by BioHeidi** [comment]
Før jeg fortsetter å gjøre noe feil (eller rett): @bibliomari , er det en konklusjon et sted, er retnningslinjene oppdaterte, og er det ferdig ryddet i Roald?

**Comment by Hypsibius** [comment]
Meinar også at om ein snakkar om biologar framfor biologi, så er det element ved biologens liv (eksempelvis forskerliv) som er i fokus, og ikkje faget som så. Dermed synest biologer: biografier som smør på flesk for meg. 

Som Heidi seier over, er den logiske framgangsmåten Biologi: biografier BF Biologer. 

Kan det løysast med at alle Biografier får SO og så lista, og vise versa Biologer, SO Biografier?

Og så kan vi konsekvent kvitte oss med <Profesjon>: Biografier?

**Comment by grosyn** [comment]
Alle strenger er no sletta, så difor lukkar eg denne diskusjonen.
