### ISSUE TITLE
Skogbruk = Skogsdrift?

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#430]
Jeg slår sammen disse to hvis vi en gang får en ny lokar (JEG SAVNER DEN SÅNN!!!), dere har sikkert rikelig tid til å protestere....

**Comment by Hypsibius** [comment]
Ja, men det har ikkje eg planar om...

**Comment by danmichaelo** [comment]
Ha, jeg kom deg i forkjøpet! Slått sammen
