### ISSUE TITLE
Naturressurser = Naturverdier?

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#431]
Foreslår å slå sammen disse to hvis ikke noen hopper høyt i stolen.

**Comment by Hypsibius** [comment]
Hoppa bittelitt, men mest fordi eg er usikker på bruken av 'naturverdier'. Verdi i konkret eller etisk forstand?

**Comment by mittinatten** [comment]
Ser jo ut som det ikker i økonomisk forstand i hvert fall: https://okapi.biblionaut.net/documents?q=real:Naturverdier&continue=1&show=sh

**Comment by BioHeidi** [comment]
Naturverdier kan slettes, men da vil jeg først legge på ordentlige emneord for de postene om biodiversitet *kremt* biologisk mangfold. Da skal jeg la være å hoppe.
