### ISSUE TITLE
Miljøvernpolitikk høres litt mye ut?

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#433]
Skal tro om det egentlig er det samme som Miljøpolitikk? ELLER som Miljøvern?

@BioHeidi @Hypsibius

**Comment by bibliomari** [comment]
Og hva med Økopolitikk?

(Hvis man lurer på hvorfor jeg er så aktiv nå: Jeg går gjennom emneord som er tekstlike i Realfagstermer og Humord, og oppdager mye på veien, for eksempel at vi i flere tilfeller bruker to eller flere emneord der Humord bruker ett med BF på. Noen ganger skjønner jeg hvorfor vi gjør som vi gjør, andre ganger skjønner jeg det ikke)

**Comment by BioHeidi** [comment]
Jeg vil gjerne ha muligheten til å skille Miljøpolitikk og Miljøvern, men det ser ut som om vi fint kan slå sammen Miljøvernpolitikk og Miljøpolitikk, og også Økonomisk miljøpolitikk (den kan vel bare slettes, sette Miljøpolitikk på istedet).

Miljøpolitikk er vel strengt tatt litt videre begrep enn Miljøvernpolitikk, men jeg synes det ser ut som om vi har brukt det likt - altså om miljøvernpolitikk, men jeg synes ikke miljøvernpolitikk er en like god term, den brukes vel ikke så mye i dagligtale heller.

Økopolitikk kan slås sammen med Miljøpolitikk, og Sosial økopolitikk kan slettes (der finnes allerede Økofilosofi på postene, mer dekkende).

Så oppsummert:
Miljøpolitikk BF Miljøvernpolitikk, Økopolitikk

Lokar Økonomisk miljøpolitikk -> Miljøpolitikk, slette Økonomisk miljøpolitikk
Lokar Sosial økopolitikk -> * , slette Sosial økopolitikk

**Comment by danmichaelo** [comment]
Slått sammen `Miljøpolitikk BF Miljøvernpolitikk BF Økopolitikk`, fjernet `Økonomisk miljøpolitikk` og `Sosial økopolitikk`
