### ISSUE TITLE
Very Long Baseline Interferometry

### ISSUE THREAD

**Issue by kyrretl** [realfagstermer/realfagstermer#434]
Denne eksisterer som 

Very Long Baseline Interferometry (VLBI)
og 
Very Long Baseline Interferometry

Altså to like der den første har (VLBI) hardkodet inn i termen og den andre har VLBI som akronym.
Foreslår å slette den første

**Comment by kyrretl** [comment]
Men Very Long Baseline Interferometry (VLBI) finnes også på poster. Og nå finnes jo ikke bibsys lenger så vi bør vente....

**Comment by danmichaelo** [comment]
Gjort
