### ISSUE TITLE
Molekylær cellebiologi

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#435]
Trenger vi denne? Isåfall kan alle dokumenter som har denne på få lokarert bort "Cellebiologi" (sjekket hos oss, alle har begge).

**Comment by Hypsibius** [comment]
Om vi treng den, treng vi som du seier i alle fall ikkje dobbelt. Litt usikker, då. Noko meining om det, @bubir ?

**Comment by Hypsibius** [comment]
Ingunn og eg gjorde eit kjapt søk, og det ser ut som om termen 'molekylær cellebiologi' vert brukt på kurs vd dei fleste universiteta (gamle og nye)
