### ISSUE TITLE
Intelligens vs Naturlig intelligens

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#436]
Er det nødvendig å ha to ulike emneord for dette - hva er forskjellen? Jeg ser at vi også har Kunstig intelligens m.m., så jeg antar at Naturlig og Kunstig intelligens er selvforklarende, men hvordan forholder vi oss til den løsaktige Intelligens...?

**Comment by BioHeidi** [comment]
Har aldri hørt begrepet "naturlig intelligens", må være datababbel.

**Comment by Hypsibius** [comment]
Slå'rem sammen!

**Comment by bibliomari** [comment]
@knuthe Enig i at jeg kan slå sammen Intelligens og Naturlig intelligens?

**Comment by knuthe** [comment]
har du sett på litteraturtilfanget? (snevert) Ellers er det OK.

Mari Lundevall wrote on 15. juni 2016 10:21:

**Comment by bibliomari** [comment]
Det var veldig snevert. Det naturlige, altså.

**Comment by bibliomari** [comment]
Gjort
