### ISSUE TITLE
Innvandring vs Migrasjon

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#437]
Hei biologer, @BioHeidi @Hypsibius : Hvordan forholder Migrasjon seg til Innvandring - er emneordet Migrasjon forbeholdt ikke-mennesker? Hvis det kan brukes om både folk og fe kan vi vel ha en SE OGSÅ mellom de to, hvis ikke lurer jeg på om vi kan spesifisere noe mer?

**Comment by BioHeidi** [comment]
Jeg mener vi kan bruke migrasjon på all inn- og utvandring av alle slags vesner. Altså er forskjellen mellom migrasjon og innvandring ikke på folk eller fe, men på retning. Migrasjon er både inn og ut.

**Comment by Hypsibius** [comment]
What she said!

**Comment by bibliomari** [comment]
Kan vi legge til brukt for Human migration / brukt for Animal migration? Evt også Bird migration? @BioHeidi @Hypsibius

**Comment by Hypsibius** [comment]
I alle fall dei to siste. Og når mennesket behandlast som oppreiste, glissen-pelsa pattedyr. Litt usikker på kor ofte vi har behov for å bruke det annleis.

**Comment by danmichaelo** [comment]
Sånn, da har vi

```
Migrasjon
BF Vandringer
BF Innvandring
osv...
```
