### ISSUE TITLE
Grotter og Huler

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#438]
Kan jeg slå sammen grotter og huler, eller er det et poeng at det er forskjell?

Forslag til engelsk: Caves.

**Comment by BioHeidi** [comment]
@kristinran @mzyg

**Comment by kristinran** [comment]
Det kan være at man med huler også tenke på menneskeskapte, i hvert fall menneskemodifiserte (som for eksempel Mikaelshula ved Norsjø i Telemark), mens grotter tenker jeg på som bare de naturlige. Men innenfor realfagstermer ser jeg ikke noe stort problem ved å slå sammen. Hva synes @mzyg ?

**Comment by mzyg** [comment]
Syns det er helt greit å slå de sammen!

**Comment by bibliomari** [comment]
gjort
