### ISSUE TITLE
Dyr : atferd, Atferd : dyr

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#44]
Vi trenger vel ikke begge strengene? @Hypsibius @BioHeidi

**Comment by BioHeidi** [comment]
Jeg husker ikke helt hvorfor vi ikke har science fiction som formterm på scifisamlingen vår? Det må vi kunne ha. Da er strengingen grei. Og det jeg mente var ikke metalitteratur som Mari skriver, om scifi, men bøkene fra scifisamlingen som har geologi som et eller annet tema. F.eks. jordskjelv og naturkatastrofer innleder en dystopisk verden hvor alle må flytte under bakken og leve av noe aliengreier de tilfeldigvis finner nedgravd.

**Comment by BioHeidi** [comment]
Og denne diskusjonen går videre: Kan man slå sammen strenger på noen enkel måte?

**Comment by Hypsibius** [comment]
Men atferd:dyr gir inga meining?

Studerer vi åtferd, studerer vi jamt over dyr (inkl menneske). 

Studerer vi dyr, gir det derimot meining å spesifisere at akkurat no er det åtferd vi ser på. Mao Dyr: åtferd gir meining, den andre ikkje.

**Comment by grosyn** [comment]
Sidan denne tråden handlar om strenger, som jo ikkje lenger finst, lukkar eg diskusjonen.
