### ISSUE TITLE
Fornybare ressurser, Fornybare naturressurser

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#442]
Det ser ut som disse kan slås sammen: Fornybare naturressurser er bare brukt på ett dokument, og da er også Fornybare ressurser brukt. Jeg foreslår:

Fornybare ressurser
BF Fornybare naturressurser

**Comment by BioHeidi** [comment]
Enig.

**Comment by Hypsibius** [comment]
Einig!

**Comment by bibliomari** [comment]
Tar opp denne igjen, da vi også har:

Fornybare kilder
Fornybare materialer

Få treff på begge to, jeg synes det ser ut osm de også kan slås inn under Fornybare ressurser:

Fornybare ressurser
BF Fornybare naturressurser
BF Fornybare materialer
BF Fornybare kilder

**Comment by danmichaelo** [comment]
Enig. Og gjort!
