### ISSUE TITLE
Feministisk filosofi SE OGSÅ Kvinnesak

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#443]
Ja, en SE OGSÅ her, bør vi vel minst ha. For ikke å si slå sammen... ? Men dette må jeg tenke litt på, og se på humord.

**Comment by mittinatten** [comment]
Det er ganske forskjellige ting, jeg stemmer for se også

**Comment by Hypsibius** [comment]
Der røk slagord som Kvinnersak = Mannssak? ;-) Vi har også termen Likestilling...

**Comment by danmichaelo** [comment]
Lagt inn SO-er
