### ISSUE TITLE
Forvirra

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#445]
650 el 651?
 
noubomn eller no-ubo-mn?

![roaldogalma](https://cloud.githubusercontent.com/assets/9350370/11951288/14ebb03e-a890-11e5-914f-396cf8ecfa6f.jpg)

**Comment by bibliomari** [comment]
no-ubo-mn er en feilkonvertering, den er meldt inn. Veldig uheldig at det ikke er rettet før realfagstermene kom inn i Alma. Jeg skal purre.

**Comment by Hypsibius** [comment]
Ah, Men feltbruk då? Forsøker å sitte på hendene mine til @mittinatten og andre er tilbake frå ferie .-)

**Comment by bibliomari** [comment]
OBS OGSÅ AT REALFAGSTERMENE IKKE KAN AUTORISERES MED F3 ENNÅ!

Unnskyld skrikinga, men jeg blir så urolig av det :)

**Comment by bibliomari** [comment]
Ser ut som det kan brukes. Og du får en nedtrekksmeny i 651 $$2, da med riktig verdi: noubomn. Får du også denne nedtrekksmenyen eller kan du skrive fritt i feltet?

**Comment by Hypsibius** [comment]
*sjekkar*

**Comment by Hypsibius** [comment]
Får menyen. Det er då noko ;-)

**Comment by bibliomari** [comment]
Vi må visst være fornøyd med smuler :) Står det noubomn i menyen?

**Comment by Hypsibius** [comment]
Jepp! Men klarer ikkje finne att prosedyrebeskrivelsen eg brukte før jul :-/

**Comment by bibliomari** [comment]
Beskrivelse for hva, for Roald+Alma?

**Comment by Hypsibius** [comment]
Jepp!

**Comment by bibliomari** [comment]
Hjelper det med side 3 her:
http://app.uio.no/ub/emnesok/data/ureal/distribusjon/roald2dokumentasjon.pdf

**Comment by Hypsibius** [comment]
Jess! Og no bokmerka også!
