### ISSUE TITLE
Datadrevet modellering

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#447]
Jeg foreslår termen
~~~
Datadrevet modellering
EN Data-driven modeling
EN Data-driven modelling
SO Datastøttet modellering
~~~
Belegg: http://bibsys-almaprimo.hosted.exlibrisgroup.com/UBB:blended_scope:BIBSYS_ILS71532283690002201

**Comment by bibliomari** [comment]
Gjort. Funderer på nynorsken.

**Comment by Hypsibius** [comment]
NN Datadriven modellering, vel?

**Comment by mittinatten** [comment]
Og termen allerede på plass, flott! Første gangen jeg opplever at noe er blitt enklere i Alma (på allvor).
