### ISSUE TITLE
Hyperbolske mengder

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#448]
Foreslår termen:
~~~
Hyperbolske mengder
NN Samme?
BF Hyperbolsk dynamikk
EN Hyperbolic sets
EN Hyperbolic dynamics
~~~
Belegg: http://bibsys-almaprimo.hosted.exlibrisgroup.com/UBB:blended_scope:BIBSYS_ILS71462484010002201
Wikipedia: https://en.wikipedia.org/wiki/Hyperbolic_set

**Comment by bibliomari** [comment]
Gjort
