### ISSUE TITLE
Selje - spesifisering av treet

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#449]
Hei biologer, kan dere ved leilighet gi noen passende ekstraopplysninger om "Selje", altså om det finnes et vitenskapelig navn, for eksempel? Og engelsk. Jeg finner Goat willow i wikipedia, men det aner meg at det ikke er så enkelt? @BioHeidi @Hypsibius

**Comment by BioHeidi** [comment]
Er det på grunn av MF Selje? Fjord1 baby!

Men mer passende opplysninger kommer her:
Arten heter *Salix caprea* på latin, og goat willow på engelsk.

Så enkelt var det denne gangen!

**Comment by Hypsibius** [comment]
At den kan vere lett å forveksle med svartvier og andre salix-artar er ei heilt anna sak ;-) Kvar Går MF Selje for tida? Trur det er ei av mine kjenningar

**Comment by bibliomari** [comment]
Takk, folkens :) Gjort.
