### ISSUE TITLE
Steinsopper Boletus sp.

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#452]
Nytermforslag til denne boken:
ISBN 9788293187196

Er det sånn at vi kan bruke Sonja nå til sånne ting som ikke krever Lokar?

**Comment by bibliomari** [comment]
Ja, nå kan vi gjøre alt i Sonja, så lenge det ikke innebærer endring av foretrukken term. I TILFELLE @danmichaelo tenker alternativt, roper jeg: @danmichaelo !

**Comment by danmichaelo** [comment]
Nei, jeg tenker utelukkende konformt!

**Comment by bibliomari** [comment]
Laget.
