### ISSUE TITLE
Kopper vs Kobber

### ISSUE THREAD

**Issue by kyrretl** [realfagstermer/realfagstermer#453]
Jeg foreslår at vi endrer 'Kopper (grunnstoff)' til 'Kobber (grunnstoff)'.
Kobber er standard i Wikipedia, SNL og Periodesystemet for grunnstoffet.

http://www.mn.uio.no/kjemi/tjenester/kunnskap/periodesystemet/vis.php?e=Cu&id=49
https://no.wikipedia.org/wiki/Kobber
https://snl.no/kobber
https://snl.no/kopper

**Comment by bibliomari** [comment]
Gjerne for meg, men alle endringer av foretrukken term må vente til vi kan gjennomføre dem i Alma.

**Comment by Hypsibius** [comment]
Så lenge vi beheld 'steinkobber' ;-)

**Comment by danmichaelo** [comment]
Gjort :)
