### ISSUE TITLE
Flervariabel analyse

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#455]
Foreslår

    Flervariabel analyse
    NN Samme
    BF Multivariabel analyse
    BF Flervariabelanalyse
    BF Analyse i flere variabler
    UT Vektoranalyse
    EN Multivariable Calculus
    SO Multivariat analyse

Belegg http://bibsys-almaprimo.hosted.exlibrisgroup.com/UBB:blended_scope:BIBSYS_ILS71479532860002201

Det vil si, det er nesten litt rart at denne ikke fantes fra før av, så kanskje det er en åpenbar synonym jeg ikke har funnet

**Comment by mittinatten** [comment]
Det er mulig det er bedre med `Flervariabelanalyse` som foretrukket?

**Comment by BioHeidi** [comment]
Huff. Søk på Multivar. Se det sammensuriumet.

**Comment by mittinatten** [comment]
Lucker denne saken og fortsetter diskusjonen i #457
