### ISSUE TITLE
Probabilistisk logikk

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#456]
Forslag

```
Probabilistisk logikk
BF Sannsynlighetslogikk?
NN samme
EN Probabilistic logic
EN Probability logic
SO Fuzzy logikk
```

https://en.wikipedia.org/wiki/Probabilistic_logic

Belegg: http://bibsys-almaprimo.hosted.exlibrisgroup.com/UBB:blended_scope:BIBSYS_ILS71466651170002201

Innspill @knuthe ?

**Comment by danmichaelo** [comment]
Oppretta den siden den har ligget så lenge. @knuthe kan fikse hvis han ser noe som fikses bør.
