### ISSUE TITLE
Tidevann*

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#459]
Jeg strevde litt med å velge blant alle tidevannstermene. 
- Vi har én bok om `Tidevannsbølger`. Kanskje den kan inngå som BF i `Tidevann`?
- `Tidevannsflater` og `Tidevannsprosesser` ser ut til å overlappe veldig og kan kanskje slås sammen? (jeg holdt på å sette `Tidevannsprosesser` på havdynamikk-boka mi før jeg så at det var et geo-begrep)

**Comment by Hypsibius** [comment]
Går utover det eg har formeining om ang tidevatn, kva seier @mzyg ?

**Comment by danmichaelo** [comment]
Siden den ene boka vi hadde om `Tidevannsbølger` også hadde emneordet `Tidevann`, og vi generelt skal bruke det mest generelle emnet, slo jeg `Tidevannsbølger` inn i `Tidevann`. Går an å gjøre om hvis vi skulle finne mye litteratur om bølgene i fremtiden.

Slettet `Tidevannsprosesser` siden den var brukt på tre dokumenter som alle også hadde `Tidevannsflater`, og fordi jeg *tror* `Sedimentære prosesser` var mer beskrivende for dem.

**Comment by BioHeidi** [comment]
Gjenoppretter Tidevannsprosesser etter påtrykk fra Edina :)
