### ISSUE TITLE
Schramm-Löwner

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#46]
Jeg syns vi skal opprette termer for Löwners ligning (Loewner equation) og Schramm-Löwners ligning (Schramm-Loewner equation/evolution`) med SO mellom de. De er tema for en ny doktorgrad ved UiB, og virker som et viktig nytt tema. 

Jeg er litt usikker på hva som er beste norske term. Pressemelding fra UiB bruker "Schramm-Löwner evolusjon" (her mangler i hvert fall et bindestrek). Alternative former kunne være Löwnerligingen resp. Schramm-Löwner-ligningen, men her er jeg veldig usikker, har vi noen praksis når ting har fått navn etter en person? 

Jeg foreslår følgende som utgangspunkt for diskusjon:

    Löwners ligning
    SO Schramm-Löwner-evolusjon
    BF Löwnerligningen (?)
    EN Loewner equation

Wikipedia: https://en.wikipedia.org/wiki/Loewner_differential_equation

    Schramm-Löwner-evolusjon
    SO Löwners ligning
    BF Schramm-Löwner-ligningen (?)
    BF Schramm-Löwners ligning (?)
    EN Schramm-Loewner evolution
    EN Schramm-Loewner equation

Wikipedia: https://en.wikipedia.org/wiki/Schramm%E2%80%93Loewner_evolution

Jeg kan ikke koden for akronymer, men SLE skal nok med på den siste også. Jeg tror både "oe" og "ö" brukes på engelsk (oe på wikipedia).

Gir det mening å ha så mange BF-varianter?

**Comment by danmichaelo** [comment]
@knuthe, denne gir fortsatt ikke treff i BIBSYS Ask

**Comment by knuthe** [comment]
Kan @mittinatten kikke på objektid 144139782 i blå-skjermen og sende meg et klipp av 687d-feltene der? Så vidt jeg kan bedømme er dette den eneste posten der Löwner-ligning og Schramm-Löwner-evolusjon forekommer.

Men det kan selvsagt hende at dette er et generelt umlaut/aksent-problem. Gammel BIBSYS-koding. Jeg ser for meg at BIBSYS på et tidspunkt har konvertert hele basen og prosedyrene i I/O de har kontroll over. Mens Roald har sendt gammel koding.

Jeg testfjernet den spesielle on-the-flytegnkonverteringen som gjøres fra Roald til blåskjermen og da fikk jeg treff både på ovennevnte post og testposten fra Roald og Ask. 

Hva med deg, @danmichaelo ?

**Comment by mittinatten** [comment]
Slik ser det fremdeles ut

    687 Löwnerligningen $2 no-ubo-mn
    687 Schramm-L#"owner-evolusjon $2 no-ubo-mn
    687 Tilfeldig gang $2 no-ubo-mn

De er altså bevisst forskjell på ö-en

**Comment by knuthe** [comment]
Kan du være snill og håndrette den ekle #"o-en til ö.

Så skal jeg legge ut ny versjon av Roald uten den gamle kodingen av bibsys-diakriter.

**Comment by mittinatten** [comment]
Rettet

**Comment by knuthe** [comment]
og jeg har lagt ut ny versjon av Roald2.
