### ISSUE TITLE
Fiskefartøy

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#462]
BF fiskefartøyer BF fiskebåter NN fiskefartøy NN fiskarfarty NN trålarar NN Snurparar EN Fishing vessels EN Fishing boats BF Trålere BF snurpere BF trålere and the list goes on....

Belegg: 

http://bibsys-almaprimo.hosted.exlibrisgroup.com/UBB:default_scope:BIBSYS_ILS71532829410002201

http://bibsys-almaprimo.hosted.exlibrisgroup.com/UBB:default_scope:BIBSYS_ILS71479816050002201

**Comment by bibliomari** [comment]
Vi hadde fiskebåter fra før, men jeg har flesket den grådig ut.

**Comment by Hypsibius** [comment]
Takkar og bukkar!
