### ISSUE TITLE
Polarområde vs polarområdene  - inkonsistens

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#463]
Merk inkonsistens mellom det som ligg i Alma og det Roald foreslår for 651. Kva har skjedd her? Manglande lokar på eit tidspunkt?
![polar](https://cloud.githubusercontent.com/assets/9350370/13010488/620bd5f2-d1a2-11e5-9c52-557e9977057e.PNG)

**Comment by BioHeidi** [comment]
Vi har både Polarområder og Polarområdene. Men hva skjer hos deg, det skal ikke være "null", det skal stå en kode for emneordssystemet? Hos meg "NO-TrBIB".

**Comment by mittinatten** [comment]
Jeg har tenkt at den koden så litt rar ut men sikker var riktig, men ser nå at også i manualen er den annerledes (altså med No-TrBIB). Sånn har det vært siden vi begynte med Alma (altså null...).

Bugg i Roald @knuthe?

**Comment by bibliomari** [comment]
Er det et ønske at vi har både polarområder og polarområdene, @BioHeidi ? I så fall kan jeg kanskje legge til en SO?

**Comment by BioHeidi** [comment]
Nei, jeg ønsker ikke begge.

**Comment by Hypsibius** [comment]
Einig, vi treng ikkje begge. Er gladeleg med på polarområdene Og lurte også på kva den nullen betydde, men det er så mange andre ting eg heller ikkje forstår, såeh, plystrar lit tog latar som ingenting...

**Comment by knuthe** [comment]
Jeg har ikke så gode ører at jeg kan høre plystringa og dermed får jeg ikke gjort noe.

Dette begriper jeg ikke. Det skal virke likt for Oslo og Bergen iflg programkoden, men jeg har ikke anledning til å komme vestover for å sjekke.

1)  Står det "Roald2 - versjon 2016-02-04" øverst til venstre i Roald-vinduet til dere i Bergen?
2)  Er det noen i Oslo som ser "null" i $$0-delfeltet?

Jeg vil avholde meg fra å anbefale lesing av bruksanvisningen for Roald2 for å få innblikk i virkemåten fordi jeg vet det sjelden har effekt. Jeg har mest skrevet den for innvortes bruk for å huske hvordan ting er ment å fungere. Da kan jeg sammenlikne med den virkelige funksjonaliteten. ;-)

**Comment by mittinatten** [comment]
Riktig versjon her.

**Comment by knuthe** [comment]
Se figur 8 og 9 i  bruksanvisningen (side 7). Figur 8: I ramma "Valg fra treffliste" står det "Fjernundervisning (REAL010361)". Det som står i parentesen er identifikatoren til termen. Velger du termen, skal den id-en følge med ned i oppsamlingsvinduet og være plassert i $$0-delfeltet slik det vises i figur 9.

Gjør den ikke det hos dere? Hva står det hos dere?

**Comment by mittinatten** [comment]
Slik ser det ut:
![capture](https://cloud.githubusercontent.com/assets/2842140/13146458/36907424-d656-11e5-9c8d-772bb5d048d6.PNG)
Vi har altså "null" i stedet for "(NO-TrBIB)" foran koden, som i Heges screencap.

**Comment by knuthe** [comment]
Det har jeg kommet til at det må stå også. Ny versjon kommer straks.

**Comment by knuthe** [comment]
Da håper jeg at dagens versjon av Roald2 har fjernet alle forekomster av bokstavkombinasjonen "null" og håper på rask melding dersom den skulle dukke opp opp på ny. Også skal jeg lese hele tråden før jeg maser for mye om bruksanvisninger. Sorry.

**Comment by mittinatten** [comment]
Ja, nå funker det som det skal. Men null-varianten er blitt registrert på et ganske stort antall titler allerede. Er det vanskelig å få bibsys å kjøre en batch-jobb her?

**Comment by bibliomari** [comment]
Vi prøver oss med Almatrylling selv først, @mittinatten . Eller hva, @danmichaelo ?

**Comment by knuthe** [comment]
1) Det blir erstatt "$$0 nullREAL" med "$$0 (NO-TrBIB)REAL" i de fire emnefeltene (648, 650, 651, 655).

2) Det fins en del med "null" som identifikator også "$$0 (NO-TrBIB)null". De bør i det minste kartlegges. 

3) Ellers er jo alle termer som ble importert fra BlåBibsys uten identifikator, så det vil kreve en  batchjobb i tillegg. 

Kanskje kan alle disse tre ta i samme slengen.

**Comment by bibliomari** [comment]
Jeg er ganske sikker på at vi kan gjøre alt dette selv, tester med Dan
Michael i dag.
Den 19. feb. 2016 07:18 skrev "Knut Hegna" <notifications@github.com>
følgende:

**Comment by bibliomari** [comment]
Gjort

**Comment by danmichaelo** [comment]
```
$ python lokar.py -e nz_prod -t 651 'Polarområder' 'Polarområdene'
[2016-05-24 14:02:29 INFO] ============================ Starter jobb ============================
[2016-05-24 14:02:29 INFO] [ Miljø: nz_prod ] [ Vokabular: noubomn ] [ Bruker: meg] [ Tørrkjøring? NEI ]
[2016-05-24 14:02:29 INFO] Termen "Polarområder" ble autorisert med ID 031026
[2016-05-24 14:02:29 INFO] Termen "Polarområdene" ble autorisert med ID 030576
[2016-05-24 14:02:29 INFO] Erstatter "Polarområder" med "Polarområdene" i $a og $x i 651-felt som har $2 noubomn
[2016-05-24 14:02:37 INFO] [  1/  2] 991517761804702201
[2016-05-24 14:02:40 INFO] [  2/  2] 998530504494702201
[2016-05-24 14:02:40 INFO] Fjerner duplikat emnefelt: "651 : Polarområdene"
[2016-05-24 14:02:42 INFO] ============================ Jobb ferdig =============================
```
