### ISSUE TITLE
Windows phone

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#466]
Legge til `BF Windows phone` på `Windows` eller lage egen term?

**Comment by danmichaelo** [comment]
Windows Phone var jo et eget OS, så det kan godt være en egen term for det. Jeg oppretta den nå, sorry at det tok så lang tid.

Litt forvirrende at de har gått vekk fra å kalle det Windows Phone i siste utgave, men det er en annen sak. Windows Phone har jo eksistert i noen år.

**Comment by mittinatten** [comment]
Nå ønsker jeg jeg hadde lagt til belegg så jeg visste hvor jeg skulle legge til termen...
