### ISSUE TITLE
Miljøvern = Naturvern?

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#467]
Vi har begge, med SO mellom. Nå husker jeg ikke i farten hvorfor vi ikke slo dem sammen. SNL bruker natur- og miljøvern i [sin artikkel](https://snl.no/natur-_og_milj%C3%B8vern). Noen sier miljøvern inkluderer kulturlandskap, naturvern bare det naturlige miljøet, men jeg tror ikke det er brukt sånn hos oss.

Jeg har lyst til å slå sammen. Og så heller bruke noen mer spesifikke termer fremover der det er mulig.

**Comment by Hypsibius** [comment]
Enig!

**Comment by danmichaelo** [comment]
Fra den offentlige debatten kan man jo få inntrykk av at vindmøller er miljøvern, men ikke naturvern :) Men jeg synes det virker lurt å slå dem sammen, vanskelig å avgjøre hvilken term man skal velge, og det blir sikkert litt vilkårlig. Miljøvern som foretrukket term?

**Comment by Hypsibius** [comment]
Ja, altså, er miljøet verna om ein ikkje vernar naturen? Er habitatsfragmentering eksempelvis ikkje eit miljøproblem, berre eit naturvernproblem?

**Comment by BioHeidi** [comment]
Ja det blir en metadiskusjon. Vi slår de sammen, Miljøvern BF Naturvern stemmer jeg for.

**Comment by bibliomari** [comment]
Gjort.
