### ISSUE TITLE
Konstruktiv matematikk

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#468]
Foreslår 
~~~
Konstruktiv matematikk
EN Constructive mathematics
NN samme?
BF Matematisk konstruktivisme
OT Konstruktivisme
~~~

Belegg: http://bibsys-almaprimo.hosted.exlibrisgroup.com/UBB:blended_scope:BIBSYS_ILS71534255120002201
Wikipedia: https://en.wikipedia.org/wiki/Constructivism_%28mathematics%29

Forfatteren av denne doktoravhandlingen skriver:

> Konstruktiv matematikk er en gren av matematikk hvor beviser korresponderer med algoritmer, og ved å studere konsepter som endelighet konstruktivt får vi resultater som vi kan tilbakeføre til datamaskinen.

Det er også et videre filosofisk konsept, vet ikke helt hvor en burde dra skillelinjene her. Noen innspill @TorgunnKarolineMoe @danmichaelo @knuthe?

**Comment by danmichaelo** [comment]
Kjenner ikke begrepet fra før, men tror ikke jeg ville tatt sjansen på `OT Konstruktivisme` når vi mangler definisjon på `Konstruktivisme`.

Ellers ser det ok ut fra mitt fra mitt lekmannssyn. I MSC fant jeg Konstruktiv matematikk sammen med Bevisteori:

http://www.ams.org/msc/msc2010.html?t=03Fxx&btn=Current

**Comment by bibliomari** [comment]
Gjort.
