### ISSUE TITLE
Kvantesammenfiltring

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#470]
Foreslår
~~~
Kvantesammenfiltring
NN Kvantesamanfiltring
EN Quantum entanglement
~~~
Belegg: http://bibsys-almaprimo.hosted.exlibrisgroup.com/UBB:blended_scope:BIBSYS_ILS71506453840002201

Wikipedia: https://nn.wikipedia.org/wiki/Kvantesamanfiltring
SNL: https://snl.no/Sammenfiltrede_fotoner

**Comment by bibliomari** [comment]
Gjort.
