### ISSUE TITLE
Oppvekstområder

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#473]
Denne har fått NN Nursery habitat og Nursery areas. Er vel bare lagt inn feil, skulle ha vært på EN. Men jeg lurer på om det trengs litt rydding i bruken. Termen ser ut til å være nyttig for å spesifisere habitater (som er en veldig bred term, brukt masse), men er ikke brukt på UREAL. Hva tenker dere i Bergen?

**Comment by Hypsibius** [comment]
Obviousl. EN Nursery habitat EN nursery areas. Brukast gjerne i fiskerisamanheng, om gruntvassområde/ålegrasenger/korallrev etc. om område der  larvar/juvenilar oppheld seg, anten det gjeld fisk, krepsdy eller tilsvarande. 

Ser kun ni dokument med dette, og alle brukar dokumentet heilt i tråd med slik eg tenkjer. Termen brukast gjerne når ein snakkar om habitat av spesiel sårbarheit (typ Baretnshavet). Dette er område ein gjerne er spesielt merksame på i samband med regulering av inngrep/fiske, sidan

**Comment by BioHeidi** [comment]
Ok, da vet jeg ikke hva jeg har sett. :D
