### ISSUE TITLE
Neste generasjons sekvensering

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#474]
Eller neste generasjons sekvenseringsmetoder? Tror jeg vil gå for termen uten "metoder" på.
Innspill?
Belegg: k16004705, ISBN: 9783874294928

**Comment by mittinatten** [comment]
Dette er en mye brukt term, men det blir likevel litt rart. Snart er det forrige generasjons. Men vi må kanskje bare forholde oss til fagets ordbruk. Stemmer for å ikke inkludere -metoder.

**Comment by bibliomari** [comment]
Ja, gammelgenerasjons ser det ut som i Wikipedia: https://en.wikipedia.org/wiki/DNA_sequencing#Next-generation_sequencing_methods

Jeg har lagt den til, men fint om dere kan se hva dere synes om manifesteringen i Roald. Skulle vi hatt med en definisjon? Det fremgår jo ikke at dette handler om DNA og gener og sånn. @mittinatten @BioHeidi

**Comment by mittinatten** [comment]
Det skal i hvert fall være c i 'sequencing' på engelsk.

Siden det er et litt vagt begrep (og jeg er ikke ekspert), vet jeg ikke helt hva definisjonen skulle være, men burde inneholde noe med
* Automatisk DNA-sekvensering
* Bruker PCR (tredje generasjonen gjør det ikke)
* Parallel lesing av mange sekvenser
* Metoder fra sent 90-tall og 00-tallet, "nyere enn Sanger, eldre enn nanoporer, etc"

Kanskje: "Parallelle PCR-baserte metoder for DNA-sekvensering". Siden det ikke er en vel-definert term, kan der sikkert være noen metoder som faller utenfor den definisjonen som også ved noen tilfeller er blitt kalt NGS.

Innspill @bubir?

**Comment by mittinatten** [comment]
Nature bruker følgende "definisjon"

> Next-generation sequencing refers to non-Sanger-based high-throughput DNA sequencing technologies. Millions or billions of DNA strands can be sequenced in parallel, yielding substantially more throughput and minimizing the need for the fragment-cloning methods that are often used in Sanger sequencing of genomes.

http://www.nature.com/subjects/next-generation-sequencing

Det vil si det definerende er at de er "nyere enn Sanger".

**Comment by bibliomari** [comment]
Takk for korrektur, har rettet :)

**Comment by danmichaelo** [comment]
Men, men, men.. *kan* vi unngå "neste generasjon" @BioHeidi ...? For gjenfinning, funker det ikke greit med bare `Sekvenseringsmetoder` og synkende datosortering? Da havner jo gammeldagsmetodene nederst :yum: Kanskje med `BF Nestegenerasjonssekvenseringsmetoder` (eller med mellomrom)?

**Comment by BioHeidi** [comment]
Jo... det kan vel funke. Skal se hvor mye vi isåfall får under den termen, tror ikke det blir kjemperotete. Hvordan vil det bli hos dere i Bergen?

**Comment by mittinatten** [comment]
Jeg syns @danmichaelo idé er god, å bare å ha termen `Sekvenseringsmetoder`, eller kanskje enda heller `DNA-sekvensering`.

**Comment by BioHeidi** [comment]
Men så er det noe som heter RNA-sekvensering som vi da utelater? Metodene er de samme, jeg tror det involverer et steg der RNA konverteres til DNA først. Så kanskje heller Sekvenseringsmetoder BF DAN-sekvensering, Neste generasjon sekvensering.

For det engelske Next-generation sequencing er definitivt en term det søkes på.

**Comment by mittinatten** [comment]
Ja godt poeng, vi bør ikke utelukke RNA.

**Comment by danmichaelo** [comment]
(DAN-sekvensering høres ut som noe for meg!)

**Comment by BioHeidi** [comment]
Jeg har fikset termen i Roald så den kan brukes:
Sekvenseringsmetoder BF Sekvensering, DNA-sekvensering, Neste generasjons sekvensering

Men, vi må huske å gjøre LOKAR på den siden det var en eksisterende term "Sekvensering" som ble omgjort til Sekvenseringsmetoder.

(Derfor ligger det også noen andre BF-termer på som jeg ikke turde å slette.)

**Comment by danmichaelo** [comment]
LOKAR gjort.
