### ISSUE TITLE
Ionekollisjoner

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#475]
Vi har `Atomkollisjoner`, `Ioner`, `Ionefysikk`, og `Tunge ioner` men føler likevel det hadde vært nyttig med 
~~~
Ionekollisjoner
BF Tungionekollisjoner
NN -ar
~~~
Muligens strengene `Tunge ioner : kollisjoner` og `Ioner : kollisjoner` kunne funket også, men tror jeg foretrekker den andre modellen.

Belegg: https://bora.uib.no/handle/1956/10359

**Comment by bibliomari** [comment]
Gjort
