### ISSUE TITLE
Menneskelige aspekter

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#478]
Termen `Menneskelige aspekter` gir lite mening, og trefflisten er mager, slettes?

**Comment by danmichaelo** [comment]
Enig :)

**Comment by Hypsibius** [comment]
Enig. der det er behov, har vi termar som humanevolusjon, humangeografi, humanøkologi

**Comment by bibliomari** [comment]
Slått sammen med sosiale aspekter.
