### ISSUE TITLE
Stress etc.

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#482]
![stress](https://cloud.githubusercontent.com/assets/9350370/13872618/27f78e0a-ecec-11e5-8fb0-b2275a84b311.PNG)

Her bør vi rydde litt. Klarer vi å på meiningsfylt vis snakke om stress utan å snakke om stresstoleranse? Om stresstoleranse utan å snakke om stressfaktorar? Og om 'stress' åleine handlar om fysiologisk/biokjemisk stress, burde ikkje det spesifiserast? Rom for samanslåing? Fleire manglar dessutan engelsk omsetjing/relevante BF-termer. Kjem gladeleg med desse (e.g. stressfaktorer BF stressorer) om vi først blir einige om kor mange termar vi treng ;-)

**Comment by BioHeidi** [comment]
Ja her er det rom for sammenslåing, og bio må samarbeide med fysikk.

**Comment by Hypsibius** [comment]
Jepp!

**Comment by mittinatten** [comment]
Jeg syns de fysikaliske ser greie ut, utenom `Deformasjoner EN Stresses and strains`, der holder det med `EN Deformations`.

Det er mulig stresstoleranse trenger innsnevring, men jeg kan ikke huske at jeg har sett det i fysikk/mekanikk (men jeg er heller ikke ingeniør), så hvis det er entydig i biologien kanskje den er grei som den er. (forvirring med psykologi?)

**Comment by Hypsibius** [comment]
Biologi og psykologi snakkar i alle fall i utgangspunktet om same sak, sjølv om psykologar gjerne tenderer til å snakke om eit utsnitt av mogelege stressorar, kun ein art og eit utsnitt av mogelege reaksjonar. Tenderer til å sjå dette sum eit subsett av biologisk stress. Men sidan vi driv med REALFAGStermar, og dei ikkje blir brukt av Psyk-folka, held vel det i lange baner hos oss? 
Wikipedia skil mellom psykologisk og biologisk stress, men artikkelen om biologisk stress, handlar no i stor grad om mennesket og psykologi lell ;-)

https://snl.no/stress
https://en.wikipedia.org/wiki/Stress_%28biology%29
https://en.wikipedia.org/wiki/Stress_%28psychological%29

**Comment by BioHeidi** [comment]
Jeg er åpen for sammenslåing av Stress, Stresstoleranse, Stressfaktorer, Stressorer. Men jeg ser at siden vi har Oksidativt stress og Cellestress, så jeg ser rom for katalogrydding også. En del av treffene kan få mer spesifikke termer.

**Comment by Hypsibius** [comment]
I'm with @BioHeidi !

**Comment by danmichaelo** [comment]
Hvis vi slår sammen kan jeg evt. rydde noen poster fra `Stress` til `Mekanisk stress`

**Comment by BioHeidi** [comment]
Ferdig ryddet @danmichaelo ?

**Comment by danmichaelo** [comment]
Ja, nå tror jeg ikke det er noe mekanikk-stress igjen i stress!
