### ISSUE TITLE
Drake-ligningen -Nyterm?  

### ISSUE THREAD

**Issue by superLine** [realfagstermer/realfagstermer#485]

**Comment by superLine** [comment]
Men hvilken form? https://no.m.wikipedia.org/wiki/Drakes_ligning

**Comment by mittinatten** [comment]
Av de få navngitte ligningene vi har fra før av virker det som vi har foretrukket bindestreks-former, så jeg stemmer for `Drake-ligningen` med `BF Drakes ligning`

**Comment by superLine** [comment]
Tommelopp!

**Comment by bibliomari** [comment]
Gjort.
