### ISSUE TITLE
Konferanser

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#486]
Vi har ingen eigen kategori for 'fleske ut', eller?

Vi har altså konferanser EN conferences. 

Kunne også tenkt meg BF møter NN møte BFsymposier NN symposiar EN symposia

**Comment by Hypsibius** [comment]
Altså, eg SA ikkje formterm, men meinte såklart det...

**Comment by bibliomari** [comment]
Flott ny kategori, jeg støtter den.

**Comment by bibliomari** [comment]
Gjort, bortsett fra "møter", som er i bruk på annen term (Møteteknikk)
