### ISSUE TITLE
Vitenskapsmenn/kvinner

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#487]
@kyrretl oppdaget at vi har `Vitenskapsmenn BF Vitenskapskvinner SO Forskere`.. Det ser vel litt rart ut at de ikke er likestilte?

https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013265

Men vet ikke om det finnes en kjønnsnøytral term.. Med mindre vi kan slå sammen vitenskapsmenn og forskere da? På engelsk skilles det jo mellom researchers, scholars og scientists, men på norsk er det _kanskje_ innafor å bruke "forskere" om alle..?

Og for å finne vitenskapskvinner/kvinnelige forskere, holder det da med kombisøk Kvinner + Forskere, eller trenger vi Vitenskapskvinner, Kvinner i vitenskapen, Kvinnelige forskere, eller noe sånt som egen term..?

@realfagstermer/alle

**Comment by mittinatten** [comment]
Jeg stemmer for sammenslåing og Forskere som foretrukket.

**Comment by Hypsibius** [comment]
Enig med @mittinatten

**Comment by bibliomari** [comment]
Humord har det samme opplegget: Vitenskapsmenn BF Vitenskapskvinner, SO Forskere. Jeg har det ikke så travelt med å slå sammen da, kjenner jeg.

**Comment by danmichaelo** [comment]
Flere som grubler på Vitenskapsmenn/-kvinner vs. forskere:
https://soundcloud.com/popkulturtantene/2015-06-popkulturtantene-kvinnelige-vitenskapskvinner-er-kvinnelige?in=popkulturtantene/sets/alle-episodene-av#t=57:26

Vitenskapere er kanskje litt for radikalt :D

**Comment by knuthe** [comment]
Popkulturtantene mente at "forskere" var byråkratisk og ga feil "konnotasjoner". Det er når jeg hører slikt at mine fordommer mot samfunns"viterne" slår ut i full blomst. Det var noen ord om at humaniora og samfunnsforskere ble utelatt om man brukte visse uttrykk. Men de områdene skaper jo ikke viten, uansett. Jeg går for 

Forskere
  BF vitenskapere
  SO/BF vitenskapsmenn
  SO/BF vitenskapskvinner

(dersom SO velges, så må selvsagt vitenskapsmenn og ditto kvinner inn som termer)

**Comment by Hypsibius** [comment]
Einig med @knuthe

**Comment by BioHeidi** [comment]
Er det da ok? Isåfall gjør jeg som Knut sa sist og DM og Kyrre sa først.

Vi har f.eks. Kvinnelige forskere også, som jeg da gjerne vil slå sammen med forskere, men vi mister en måte å definere det når dokumentet spesifikt handler om kjønnsroller/kjønnsmønster eller hva jeg skal kalle det. Vi kan lage streng med Kvinner eller med Kjønns-ettellerannet. 
Jeg hadde en biografi "Women scientists" spm jeg endte opp med å legge to strenger på:
Vitenskapsmenn : Biografier og Kvinner : Biografier. I tillegg får den jo H1 - 082 innbakt i deweynummeret på et vis (her ble det 509.252). Så jeg føler at kvinnen er ivaretatt.

**Comment by BioHeidi** [comment]
Som var det som DM foreslo ser jeg.

**Comment by BioHeidi** [comment]
Da var det endelig gjort!
