### ISSUE TITLE
filmtitler (science fiction selvfølgelig)

### ISSUE THREAD

**Issue by superLine** [realfagstermer/realfagstermer#488]
Hei, noen av de andre vokabularene har filmtitler (og da tenker jeg på de store - og selvfølgelig science fiction i min kontekst) - er det mulig å legge de til hos oss også? Star Wars f.eks.

**Comment by danmichaelo** [comment]
Tenker du at de skal føres inn som standardtitler (130)? Og at «Star Wars» *som emne* legges i [630](https://www.loc.gov/marc/bibliographic/bd630.html)? Eller som vanlige emneord?

LC har jo Star Wars i alle mulige former :) [Star Wars fiction](https://lccn.loc.gov/sh97006505) som form/sjanger, [Star Wars films](https://lccn.loc.gov/sh85127382) som vanlig emneord, + en haug standardtitler.

**Comment by BioHeidi** [comment]
Jeg vil ikke ha titler i emneord... Er det ikke egne felter for det?

**Comment by danmichaelo** [comment]
> Jeg vil ikke ha titler i emneord... Er det ikke egne felter for det?

Jo, standardtitler (630) kan vi ha som en egen kategori i tillegg til form, tid, sted. Eller vi kan bare bruke BARE :)

**Comment by bibliomari** [comment]
Dette hører vel med til en større diskusjon om Scifi-samlingen. Enn så lenge: Standardtitler kan opprettes som autoriteter i BARE ved behov, og legges i 630.
