### ISSUE TITLE
Medisinske avbildninger

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#489]
Foreslår `Medisinske avbildninger` endret til `Medisinsk avbildning` siden vi ikke er interessert i bestemte avbildninger, men prinsipper og teknikker.

**Comment by danmichaelo** [comment]
Vi må også vklare forholdet mellom `Bildediagnostikk` og `Medisinsk avbildning`. "Diagnostic imaging" omdirigerer til "Medical imaging" på en.wikipedia, så vi må ihvertfall ha en SO mellom dem, men kanskje også slå dem sammen. 

Fra bruk ([medisinsk avbildning](https://okapi.biblionaut.net/documents?q=bs.lokoeo-frase%3D%22Medisinske%20avbildninger%22%20AND%20bs.avdeling%3D%22ureal%3F%22&show=sh,c) / [bildediagnostikk](https://okapi.biblionaut.net/documents?q=bs.lokoeo-frase%3D%22Bildediagnostikk%22%20AND%20bs.avdeling%3D%22ureal%3F%22&show=sh,c)) synes jeg det ser ut som vi kan slå dem sammen, som `Medisinsk avbildning BF Bildediagnostikk`.

**Comment by mittinatten** [comment]
Ser ut som de er sammenslått i MeSH også http://www.ncbi.nlm.nih.gov/mesh/?term=medical+imaging (støtter vi lenking dit?)

**Comment by danmichaelo** [comment]
(nei, men det hadde ikke vært så dumt)

**Comment by danmichaelo** [comment]
Ok, da sier vi `Medisinsk avbildning BF Bildediagnostikk`. Og så legger vi må mapping til MeSH når vi får mulighet til det i fremtiden :)

**Comment by bibliomari** [comment]
Gjort. Klarer Nylokar dette, @danmichaelo? :dancers:
