### ISSUE TITLE
Pendel

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#491]
Belegg: http://bibsys-almaprimo.hosted.exlibrisgroup.com/UBO:default_scope:BIBSYS_ILS71497133260002201

De tre store har Pendel (GND), Pendulum (LCSH), Pendule (RAMEAU): http://d-nb.info/gnd/4173651-5

Jeg er litt usikker på form her. Kan vi opprette `Pendel`? `Pendler` synes jeg høres rart ut, siden det ikke er konkrete forekomster vi er interessert i, men (idealiserte) modeller. Pluss at det kan forveksles med pendlere.

En annen mulighet er `Pendelbevegelse`, som tydeliggjør at vi befinner oss innenfor mekanikken.

@mittinatten @bibliomari (for språkformråd)

**Comment by mittinatten** [comment]
I hvert fall ikke `Pendlerbevegelse` ;)

Dette var vanskelig, `Pendel` høres litt språklig forvirrende ut for meg, hva med `Pendler (mekanikk)`. 

`Pendelbevegelse` er ikke dumt heller.

**Comment by bibliomari** [comment]
Gjort

**Comment by mittinatten** [comment]
Hva ble det?

**Comment by danmichaelo** [comment]
Godt spørsmål :) 

`Pendelbevegelse BF Pendler (mekanikk)`
