### ISSUE TITLE
Streng Fluiddynamikk : numerisk analyse + mekanikk vs dynamikk

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#492]
Strengeforslag `Fluiddynamikk : numerisk analyse`, Dewey 532.0501518.

Muligens trenger vi å rydde i, slå sammen med `Fluidmekanikk : Beregningsorientert fysikk`, `Fluidmekanikk : Matematiske metoder`.

Jeg er ikke ekspert her, men fra hva jeg forstår fra Wikipedia brukes termen Fluidmekanikk for statikk og dynamikk til sammen, det vil si `Fluiddynamikk OT Fluidmekanikk`, slik er hierarkien i Dewey også. De fleste av strengene som begynner med `Fluidmekanikk` skulle nok ha vært -dynamikk (strømning, ledning, bølger, hydrodynamikk) 

(henger sammen med #282)

innspill? @danmichaelo @mzyg

**Comment by danmichaelo** [comment]
Hum, hum, hum… 

1. Jeg har nok tenkt "Beregningsorientert fysikk" som en litt vid sekk som omfatter "Numerisk analyse" også. Men du tenker kanskje at det er greit å skille mellom utvikling av algoritmer og anvendelse av dem?

2. `Fluid(mekanikk/dynamikk) : Matematiske metoder` kan vi godt flette inn i én av de andre strengene. Synes ikke det ser ut som den beskriver godt de dokumentene den er brukt på.

3. Når det gjelder mekanikkstrengene reagerer jeg egentlig ikke på det så lenge mekanikk omfavner dynamikk, men det blir jo ikke feil å endre det heller. Noen av strengene er rare. `Fluidmekanikk : Hydrodynamikk` f.eks. bør vel bare være `Hydrodynamikk`.

**Comment by mittinatten** [comment]
1. Jeg tenker `Fluiddynamikk : Numerisk analyse` er en form for beregningsorientert fysikk, det vil si er mer presist enn `Fluidmekanikk : Beregningsorientert fysikk`
3. Enig, strenger bør ikke inneholde OT-UT-par som med hydrodynamikk, nei.

**Comment by danmichaelo** [comment]
Hm, vi glemte helt av denne. Husker du om du tenkte å ha med Computation Fluid Dynamics (CFD) under `Fluiddynamikk : Numerisk analyse`? Savner mulighet for å legge på BF-termer på strenger..

**Comment by mittinatten** [comment]
Husker ikke, men det virker lurt :)

**Comment by danmichaelo** [comment]
Hehe, bra. Oppretta strengen ihvertfall. Kommer sikkert tilbake til fluiddynamikk senere mistenker jeg.
