### ISSUE TITLE
Skog og Skoger

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#493]
Kan de slås sammen? @realfagstermer/biovitenskap

**Comment by Hypsibius** [comment]
Tjjjjaaaaa? @BioHeidi ? Ville tru det...

**Comment by BioHeidi** [comment]
Ja. Den er nok bare glemt i sammenslåingen. Skog BF Skoger, så vises det at den inkluderer biotopen skog og bestemte skoger.

**Comment by BioHeidi** [comment]
Har jeg fått en laik? :D :D

**Comment by Hypsibius** [comment]
Indeed!

**Comment by danmichaelo** [comment]
:tada:

**Comment by bibliomari** [comment]
gjort
