### ISSUE TITLE
Menneske-maskin systemer

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#495]
En ting er at mangler en bindestrek, men jeg tror også dette er mer kjent som `Menneske-maskin-interaksjon EN Human-computer interaction`.

@knuthe

**Comment by knuthe** [comment]
Mulig jeg har vært inkonsistent i min emneordssetting her, men jeg mener m-m-systemer er litt videre enn m-m-interaksjon (samhandling).  Det siste er mer i retning brukergrensesnitt.

**Comment by danmichaelo** [comment]
Aha, det var derfor jeg ikke fikk treff på `Menneske-maskin-interaksjon` :D Jeg la inn `BF Menneske-maskin-interaksjon` på m-m-samhandling. Da har jeg ikke noe imot å beholde dem som to begreper.
