### ISSUE TITLE
Protister, protozoer og encellede organismer 

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#496]
Har vi. Ingen SO-termer. Treng vi alle? I så fall: SO-termar mellom?

**Comment by BioHeidi** [comment]
Ja vi bør i alle fall ha SO mellom. Protister omfatter Protozoer men ikke bare det, og Encellede organismer omfatter både Protister, Protozoer og Prokaryoter. Jeg tror termene er mindre brukt nå, de representerer til en viss grad forskjellige skoler av klassifisering så det er lett å bli forvirret.

Hvis vi skulle ha slått sammen noe må vi isåfall ta en større opprydding, så jeg tror heller vi beholder de gamle og er litt mer spesifikke ved videre klassifisering. Jeg ser at mange dokumenter som har flere av disse termene godt kunne klart seg uten.

**Comment by BioHeidi** [comment]
Fant den først ikke når jeg skulle legge inn SO, men ser at det står Encellete organismer (med t). Jeg la inn BF Encellede organismer også. Med d.

**Comment by bibliomari** [comment]
Dette ser ut som er fiksa nå.
