### ISSUE TITLE
Geokjemisk atlas

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#497]
Formterm.
Til dokid k16012597 og 75nw08867

Og det er ok å ha tre emneord i streng her
henholdsvis
Flomsedimenter : Geokjemisk atlas : Spitsbergen
Flomsedimenter : Geokjemisk atlas : Norge

Jeg er litt usikker på det med tre i streng! Hvor er strengekurset mitt?

**Comment by Hypsibius** [comment]
Hm, kan vi strenge inn alle eventualitetar, eller anta at brukarane søker litt boolsk for å vere spesifikke?

**Comment by bibliomari** [comment]
Opprettet.
