### ISSUE TITLE
Dyrking og beslektede termer

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#498]
Vi har en del "dyrking"-termer. Kan dere hjelpe meg å se på dem? Føler det er rom for sammenslåing med Hagebruk og Landbruk/Jordbruk noen steder.

Blomsterdyrking
Bærdyrking
Dyrking
Fordyrking
Fordyrking
Plantedyrking
Soppdyrking
Økologisk dyrking

Foreslår iallefall sammenslåing:
Økologisk landbruk BF Økologisk dyrking, Økologisk jordbruk (siste term finnes ikke men kan vel legges på likevel).

**Comment by Hypsibius** [comment]
Har vi verkeleg 2x fordyrking? Klarer oss med ein, vaffal, og endre til fôrdyrking?

**Comment by BioHeidi** [comment]
Må klare oss med en vaffel, ja.

Økologisk dyrking er slått sammen med Økologisk landbruk (sikkert jeg som gjorde det i 2016?)

Slettet Blomsterdyrking (alle treff hadde enten hagebruk eller andre relevante termer),
Slettet Bærdyrking ( --  " -- )
Slettet Plantedyrking (var allerede gjort)

Beholdt: 
Fôrdyrking (greit som emneord på det ene treffet)
Soppdyrking
Algedyrking
Fruktdyrking

Når jeg får almar til å virke igjen skal jeg rydde i Dyrking, en del kan over på de over. Skal også rydde i Fôrstoffer og Fôring.

**Comment by Hypsibius** [comment]
Altså, personleg har eg akkurat kjøpt nytt, dobbelt vaffeljarn, såeh...

Men hald fram som du stevnar, @BioHeidi
