### ISSUE TITLE
MSC-feil Kalkulus

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#499]
`Kalkulus` har MSC 26.20, burde være 26A06 (tror jeg). Denne klassen har ikke vært i bruk siden 1972. Generelt tror jeg man sluttet med klasser med punkt i 1972. Har funnet flere med "punkt-klasser" (for eksempel multivariabel analyse #457). Hvis det er sånn at UBO har samlinger som er oppstilt etter gamle MSC (det har vi), og det derfor må følge den gamle er det vel greit, men ellers tenker jeg vi ikke burde bruke utdaterte klasser.

**Comment by bibliomari** [comment]
Enig i prinsippet.... Men koblingene våre til MSC er gjort mot en gammel versjon, pga oppstilling, ja. Oppdatering er på min drømmeliste!
