### ISSUE TITLE
DDC i Roald2

### ISSUE THREAD

**Issue by knuthe** [realfagstermer/realfagstermer#50]
Når det gjelder innlegging av DDC her og der, trengs det en diskusjon. Vi har jo registrene til DDC i BIBSYS (UBO og UBB har hvert sitt). Hvordan skal forholdet til disse være, viss vi bygger om et nytt register fra emneordene?

**Comment by danmichaelo** [comment]
Det er vel egentlig avklart at vi ikke legger DDC i Roald, så lukker denne.
