### ISSUE TITLE
Museer og Museumsvesen

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#500]
Vi har ett dok på sistnevnte. Jeg føler for å slå disse to sammen. Med BF Museumsvirksomhet.

Og en SO til Museologi kanskje.

**Comment by danmichaelo** [comment]
Jau.. vi har riktignok `Bibliotekvirksomhet` som eget begrep, men bibliotek er jo mye viktigere enn museer :P Fra spøk til alvor, så lenge vi i praksis ikke har litteratur om det (det ene dokumentet er ABM-tidsskriftet).. så

Jeg slo de sammen. Men nå lurer jeg på om vi egentlig trenger "Museumsvesen" og "virksomhet" i det hele tatt.. tja, jeg lar det være. Du kan fjerne dem hvis du vil.
