### ISSUE TITLE
Arvelighet vs genetikk

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#502]
Hei biologer, er det noen god grunn til at vi har emneordet Arvelighet og emneordet Genetikk? Hvis vi skal ha begge to trenger vi en definisjon eller avgrenising på når det ene, når det andre. Hjelp?

@BioHeidi @Hypsibius

**Comment by bibliomari** [comment]
Jeg trekker sammenslåingsforslaget etter diskusjon og folkeopplysning på kammerset, men en gang i framtida kunne det være ok med en forklaring på arvelighet, jeg tror vi har *arvet* endel feil fra gamle frie nøkkelord.

**Comment by Hypsibius** [comment]
Heh! Men kan vi legge til arvelighet BF heritabilitet? Eit kjapt googlesøk avslører at det er ei danisme, men ikkje dess mindre er det blitt brukt på studiet ved UiB framfor 'heriditet'

**Comment by danmichaelo** [comment]
Lagt til `BF heritabilitet`. Det eneste som overgår danisme er danmichaelisme!
