### ISSUE TITLE
epidermis og huden

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#504]
Altså dette ER forskjellige ting og alt, men MÅ vi vere så spesifikke? Kunne vi seie Huden BF Overhuden BF epidermis BF lærhuden BF dermis BF underhuden BF subcutis? Eller skal vi sende ei SO til dei tre hudkategoriane? jf

https://sml.snl.no/huden

**Comment by BioHeidi** [comment]
Nei vi mååå ikke være så spesifikke. Vi er ikke noe medisinsk leksikon akkurat. Når MESH blir oppkjøpt av oss og omdøpt til Medisinsfagstermer kan vi utfleske det der.

(Les: Enig)

**Comment by danmichaelo** [comment]
Gjort! Og lol-ja til Medisinsfagstermer!
