### ISSUE TITLE
Slimhinner vs epiteler vs epitelceller

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#505]
DESSE kan vi vel slå saman. Men vent, kjem tilbake med meir! Må løpe til lunsj

**Comment by Hypsibius** [comment]
Beklager, her går eg i alldeles surr i forskjellane mellom epitel og epidermis. Iflg fiskeanatomiboka over alle fikseanatomibøker (Kryvi & Totland) er epidermis eit fleirlaga plateepitel, som hos fisk er ispedd kjertelceller som produserer slim. Dette til forskjell frå slimHINNER, som er 'fuktig hinne som kler en INDRE overflate av et organ, «innvollsrør» (bl.a. i luftveiene, spiserøret, urinveiene, kjønnsorganene, tarmene). IFLG Store medisinske leksikon. 

Vi bør uansett sjå termane i høve til kvarandre (og epidermis). 

I øyeblikket er eg mest opptatt av SLIMLAGET, og kunne tenke meg å foreslå ny term 

Slimlag. 

Eller hadde eg vore bedre tent med ganske enkelt Slim, BF mucus? @BioHeidi , kan du redde meg her? Er berre forvirra, eg. 

Belegg: https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71493720510002201

**Comment by bibliomari** [comment]
Ses i sammenheng med #504?

**Comment by BioHeidi** [comment]
Slim BF Slimlag, Mucus. Stemmer jeg for ja. Men hvis vi har belegg (heh) for det bør vi beholde Slimhinner separat fra Huden.

**Comment by BioHeidi** [comment]
Eller jeg ombestemte meg kanskje og vil heller ha Slimlag BF Slim, Mucus

**Comment by Hypsibius** [comment]
Ei halv stemme til kvar av @BioHeidi sine forslag. Eller, 0.75 på det første og 0.25 på detandre, ved nærare ettertanke...

**Comment by BioHeidi** [comment]
Tror jeg har gjort det riktig nå.
