### ISSUE TITLE
Mineralgjødsel = Kunstgjødsel?

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#506]
For en lekmann innen bondens kunst ser det ut til at Kunstgjødsel og Mineralgjødsel er det samme. Kan de slås sammen?

Med SE OGSÅ Gjødsel?

```
Mineralgjødsel
BF Kunstgjødsel
BF Nitrogengjødsel
NN Kunstgjødsel

SO Gjødsel
````

(Mari prøver markdown.... spent på hva som skjer...)

**Comment by Hypsibius** [comment]
Ja, ser ingen grunn til ikkje. Ser at SNL oppgir som synonym både kunstgjødsel og (o.O)  handelsgjødsel...

**Comment by danmichaelo** [comment]
Gjort!
