### ISSUE TITLE
Høyt blodtrykk = Hypertensjon?

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#507]
Vi har:

```
Blodtrykk
BF Høyt Blodtrykk
```
```
Hypertensjon
```
Jeg skjønner ikke om det er en forskjell på Høyt blodtrykk og Hypertensjon, men iallfall: Disse kan kanskje slås sammen? Hvis ikke, iallfall Se også mellom dem.

**Comment by Hypsibius** [comment]
Ser ikkje ut som nokon forskjell i Store Medisinske, vaffal. 

https://sml.snl.no/hypertensjon

PS: Er dette ein parallell til flo-fjøregreia, at det samla drøftast som 'tidevatn', eller kan vi her argumentere med at høgt og lågt blodtrykk omtalast vkar for seg?

**Comment by BioHeidi** [comment]
Siden vi ikke har veldig mange treff her synes jeg vi skal slå tammen til Blodtrykk, BF Høyt blodtrykk, Lavt blodtrykk, Hypertensjon, Hypotensjon.

Vi har også Blodtrykksmedisiner som kan slås sammen med Antihypertensiva.

**Comment by danmichaelo** [comment]
Flo og fjære, høyt og lavt blodtrykk, definitivt inne på samme spor!

Gjort:
```
Blodtrykk
BF Høyt blodtrykk
BF Hypertensjon
BF Lavt blodtrykk
BF Hypotensjon
```

og tilsv. nynorsk.

Samt slått sammen `Blodtrykksmedisiner BF Antihypertensiva`
