### ISSUE TITLE
Slakting

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#508]
Kan ikkje sjå at vi har nokon term for slakting(eller avliving). Litt i stuss om det mest hensiktsmessige kunne vere å velje _slaktemetoder_, eller _slakteprosedyrer_, men ut frå kor mange dokument vi har i basen som omhandlar dette, kan det bli unødig spesifikt. Trur eg går for 
Slakting NN slakting  EN Slaughter (-ing?)

https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71535568970002201

**Comment by bibliomari** [comment]
Gjort (fulgte wikipedia og skrev EN Animal slaughter)
