### ISSUE TITLE
Matauk

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#509]
Har det for meg at vi har ein relatert term. 'Ressursutnyttelse' er gjerne ikkle heilt spesifikt nok, og eg fann ingenting på selv-/sjølv-forsyning/-berging etc etc. Har eg oversett noko, så peik meg gjerne til rett emneord, om eg skulle ha oversett eitt ;-)

Wikipedia har eiga innførsle, SNL brukar termen både i samband med jakt og fritidsfiske. 

Aktuell bok: 
https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71534658470002201

**Comment by BioHeidi** [comment]
Vi har Næringssøk BF Furasjering, Næringsvalg, Fødevalg, Dietter, Matvaner

Kan det brukes?

Vi har også Kokebøker BF Matoppskrifter som form.

Og vi har termene Mat, Matnyttige arter, Matressurser, Mattilgang, Matvarer. Og Forstoffer.

**Comment by Hypsibius** [comment]
Matnyttige arter og Matressurser synest i augneblinen mest matnyttig. Bortsett frå laboratorieframstilte burgarar, er det mogeleg å tenke seg matressursar som ikkje kjem frå matnyttige artar? Aktuelt å slå desse saman? Og slenge på BF Matauk?

**Comment by Hypsibius** [comment]
#samanslåingshumør, liksom

**Comment by BioHeidi** [comment]
Ja. Kan gjerne ha Matressurser som foretrukken term da.

**Comment by bibliomari** [comment]
Gjort
