### ISSUE TITLE
Forkurs

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#510]
Vet ikke helt hvorfor vi har denne, et emneord er det ihvertfall ikke:

https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000892&lang=nb

Som søkehjelp tror jeg heller ikke det er særlig nyttig. "forkurs" står uansett i tittelen for disse bøkene, og vi har formtermen `Grunnbøker` vi kan bruke om innføringsbøker.

**Comment by Hypsibius** [comment]
!

**Comment by bibliomari** [comment]
gjort
