### ISSUE TITLE
Kondenserte fasers fysikk og Faststoffysikk

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#511]
Jeg oppdaget akkurat at vi mangler `Kondenserte fasers fysikk`, men vi har `Faststoffysikk` som ser ut som har vært brukt om begge. (https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013568&broad=false)

Foreslår å endre `Faststoffysikk` til `Kondenserte fasers fysikk BF Faststoffysikk`.

Hva tror du @mittinatten ?

**Comment by mittinatten** [comment]
Ja, og legg til `EN Solid-state physics` og `EN Condensed matter physics`.

Jeg har dog en følelse av at Faststoffysikk / Solid-state er mere brukt, og at det muligens blir rart å ikke ha Faststoffysikk som foretrukket/eller egen term, selv om den i teorien er underordnet? Bruker folk som forsker på væsker termen condensed matter for sitt fag? Har støtt på Soft condensed matter, men tror bare det er et dårlig ord for polymerfysikk. Og de som holder på med superledere sier nok at de driver med Solid-state (selv om det teknisk sett er en annen fase).

Er det verdt det å legge til `UT Superledere`, `UT Ferromagnetisme`, `UT Halvledere`, etc?

Kanskje er det bare fordi jeg bare har vært innom temaet på én kurs for over 10 år siden at jeg er forvirret over språkbruken, og fagskillene.

**Comment by danmichaelo** [comment]
Neida, ikke bare deg :) Kurs og bøker om kondenserte fasers fysikk er vel ofte mest faststoffysikk / periodiske krystaller, pluss litt om superledning på slutten hvis man har tid? 

Væske-folket bruker vel fluid... 

Og soft condensed matter forbinder jeg også med polymerfysikk.

Siden "kondenserte fasers" er overordnet tenker jeg at vi nesten må bruke den.. og den er jo ikke lite i bruk den heller, selv om faststoff kanskje er mer brukt.

**Comment by mittinatten** [comment]
Vi har også en asymmetri i at vi sier Kondenserte fasers _fysikk_ men bare Superledere og Halvledere (ikke superlederfysikk, etc). Høres det for rart ut å bruke termen `Kondenserte faser`? Fenomenet vs faget antar jeg, vi er kanskje ikke konsistente for andre fag heller.

**Comment by danmichaelo** [comment]
Ja, har også tenkt på dette med fenomen/begrep og fagfelt.. For `Kondenserte faser`s del tenker jeg at `Kondenserte fasers fysikk` er snevrere enn `Kondenserte faser` (som ihvertfall uten definisjon ville kunne dekket store deler av kjemien), og at det derfor blir rart å bruke sistnevnte. Og så er førstnevnte en etablert term på linje med `Kjernefysikk`, `Atomfysikk`, osv.. Men når vi snakker om `Halvledere` så har vi faktisk både `Halvlederfysikk` og `Halvledere` (og `Halvlederteknikk`)! Åpner en ny sak om det :)

**Comment by danmichaelo** [comment]
Ok, da gjorde jeg om til `Kondenserte fasers fysikk BF Faststoffysikk` (og slo sammen med `Fasttofflære`) og la på nynorsk og engelsk samt `SO Faststoffkjemi, Faststoffmekanikk`.
