### ISSUE TITLE
Halvlederfysikk, Halvlederteknikk og Halvledere

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#514]
Som nevnt i #511 : Trengs alle tre eller er det rom for sammenslåing?

**Comment by mittinatten** [comment]
Det ser ut som `Halvledere` og `Halvlederfysikk` er blitt brukt synonymt, selv om de har `SO` mellom seg, der kan vi slå sammen. `Halvlederteknikk` virker å handle mere om transistorer, tilvirkningsprosesser, etc, kan slås sammen med `Halvlederkomponenter`? `Halvledermaterialer` kanskje kan slås sammen med halvledere også (muligens litt katalogrydding her, noen passer bedre under -teknikk).

Foreslår
~~~~
Halvledere
BF Halvlederfysikk
BF Halvledermaterialer
(BF Halvlederkjemi??)
EN Semiconductors
EN Semiconductor physics
NN ... slå sammen
UT hente fra Halvledermaterialer
SO Halvlederteknikk
NO Brukes for beskrivelser av halvlederes fysikalske egenskaper, teoretiske verker, etc.
~~~~
og
~~~~
Halvlederteknikk
BF Halvlederteknologi
BF Halvlederkomponenter
EN Semiconductor technology (ikke techniques)
NN ... slå sammen
SO Halvledere
NO Brukes for beskrivelser av halvlederkomponenter, og bruk og produksjon av disse.
~~~~
(er det NO for note?)
På engelsk skriver en både `semi-conductor` og `semiconductor`, trenger vi å ha med begge?

Og hva med teknikk vs teknologi, har vi hatt den diskusjonen før?

**Comment by danmichaelo** [comment]
Tror det kan funke! Det blir ganske mange dokumenter i hver bolk, men med kombinert søk (som vi riktignok ikke har enda, men som vi vil ha en vakker dag) kan man jo avgrense videre på f.eks. materiale, eller form-ord som `Oversiktsverker` og `Grunnbøker`.

**Comment by danmichaelo** [comment]
Da har jeg omsider fiksa dette!

Vurderte å lage strengen `Halvledere : Materialvitenskap`. Mulig jeg gjør det i fremtiden :)
