### ISSUE TITLE
Romlig, romlige

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#516]
> Romlig analyse 
> Romlig erkjennelse 
> Romlig fordeling 
> Romlig orientering 
> Romlig statistikk 
> Romlig struktur 
> Romlig økologi 
> Romlige analyser 
> Romlige mønstre 
> Romlige prosesser 

Her kan det nok ryddes litt. Foreslår:
Romlig statistikk BF Romlig analyse, Romlige analyser
Romlig erkjennelse BF Romlig orientering (basert på belegg for Romlig orientering)
Romlig fordeling BF Romlig struktur (basert på belegg for Romlig struktur)
Romlig økologi: Slettes (evt erstattes med Romlig statistikk eller Romlig fordeling)
Romlige mønstre: Slettes (evt erstattes med Romlig statistikk eller Romlig fordeling)
Beholde som den er: Romlige prosesser

**Comment by mittinatten** [comment]
Sleng gjerne på `EN Spatial statistics` og `EN Spatial analysis` på `Romlig statistikk`

**Comment by Hypsibius** [comment]
Er også meir fortruleg med 'romlig fordeling' enn 'romlig økologi', men i økologisk samanheng bør vigjerne også sjå denne i samband med habitatstermane våre. 
![habitat](https://cloud.githubusercontent.com/assets/9350370/16261039/46817cd6-386a-11e6-9ef0-96c93fb32873.PNG)

**Comment by Hypsibius** [comment]
Tenkjer særleg på termar som Habitater, Mikrohabitater, Habitatfragmentering. Vi har i augneblinken ingen term for 'habitatbruk',men kan få behov for det.

**Comment by bibliomari** [comment]
Jeg har endret som @BioHeidi foreslo.

**Comment by Hypsibius** [comment]
Treng vi ein SO habitatfragmentering?
