### ISSUE TITLE
Trofisk

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#517]
Vi har:
Trofiske interaksjoner
Trofiske systemer
Trofiske nivåer
Trofiske relasjoner

Jeg vil gjerne samle dem alle under Trofiske interaksjoner. OK? Vet ikke om websøket feiler her, for jeg får bare treff på Trofiske interaksjoner.

**Comment by danmichaelo** [comment]
>  Vet ikke om websøket feiler her, for jeg får bare treff på Trofiske interaksjoner.

Jeg får alle fire når jeg skriver "Trofiske". Kan du prøve igjen?

**Comment by bibliomari** [comment]
gjort

**Comment by Hypsibius** [comment]
'Gjort' som i 'søkt' eller gjort som i 'samla'? Er uansett for :-)
