### ISSUE TITLE
Dewey for datalingvistikk

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#518]
Kan vi legge til 006.35 på `Datalingvistikk`?

**Comment by bibliomari** [comment]
Nei. Vil ikke ha med deweynummer her inne, men @danmichaelo mapper den nå

**Comment by danmichaelo** [comment]
Nei, @bibliomari , du må mappe den, jeg kjenner retningslinjene for dårlig… Men her er den:
https://lambda.biblionaut.net/relationships/65800

**Comment by mittinatten** [comment]
Så hva er prinsippene for Dewey-nummer og Realfagstermer?

**Comment by bibliomari** [comment]
Matematikken får ha deweynummer av praktiskhistoriske grunner, som du vet... Men hovedsaklig nøyer vi oss ellers med å mappe dewey til emneord utenfor emneverktøyet, for ikke å mislede de som setter emneord til å hente deweynummer rett fra Roald. De kan være utdatert, eller de kan være feil for det dokumentet man har i hånda for øyeblikket.

**Comment by bibliomari** [comment]
Så ikke at du skrev, det vakke meninga å smekke den igjen. Si fra hvis svaret ikke var forståelig.

**Comment by mittinatten** [comment]
Joda, det gir mening :)
