### ISSUE TITLE
Modellbasert programmering

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#520]
Kan vi legge til `Modellbasert programmering` som synonym til `Modelldrevet arkitektur`, og kanskje endre foretrukket til `Modelldrevet utvikling`? Høres litt rart ut at en arkitektur er drevet, passer bedre på en prosess (som utvikling eller programmering)?

Belegg: http://www.uib.no/nye-doktorgrader/98524/kan-du-forestille-deg-automatisk-framstilt-programvare

**Comment by bibliomari** [comment]
gjort
