### ISSUE TITLE
Kamuflasje vs. Mimikry

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#524]
Biologer, kan Kamuflasje forholde seg til Mimikry på noen måte, f.eks. som SE OGSÅ? 

@BioHeidi @Hypsibius

**Comment by BioHeidi** [comment]
Ja, Se også. Det er to forskjellige ting, men de ligner. Legge på definisjon på mimikry, f.eks. "Etteraping hvor en organisme drar nytte av likheten til noe annet som har en annen oppgave eller funksjon." (fra IBV sitt plantefysleksikon). Klassikeren er blomsterfluer med aposematisme, eller Bates mimikry (ligner veps). Kamuflasje kan være fysisk kamuflasje også (eks grave seg ned).

**Comment by bibliomari** [comment]
Gjort

**Comment by Hypsibius** [comment]
Mimicry kamuflert som kamuflasje: http://2ap93t1x1l6e2f6gfo3ag4vw.wpengine.netdna-cdn.com/wp-content/uploads/2016/02/Leafy-Sea-Dragon-natgeo-hirz-4tlr.jpg

**Comment by BioHeidi** [comment]
Å, vakker!
