### ISSUE TITLE
Feltarbeid vs. Feltstudier

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#526]
Kan noen forklare meg forskjellen på Feltarbeid og Feltstudier? Hvis vi skal ha begge emneordene, ønsker jeg meg en definisjon på dem. 

Vi har også Feltmetoder (og Innsamlingsmetoder og Prøvetaking), men det ser ut som det skal få bestå alene. 

Tror dette er mest til biologene @Hypsibius og @BioHeidi (vi har da også Feltbiologi og Feltornitologi), og selvsagt til steinsamlerne blant oss.

**Comment by bibliomari** [comment]
Til inspirasjon (?): Humord har 

Feltarbeid
BF Feltstudier
Note:  Innsamling av vitenskapelig (kilde)materiale ute i felten

**Comment by BioHeidi** [comment]
Går for Humord her.

**Comment by BioHeidi** [comment]
Og så synes jeg Feltbiologi og Feltornitologi er dårlige termer. Ville heller hatt Feltarbeid : Biologi da isåfall (men jeg er jo strengofil)

**Comment by bibliomari** [comment]
Har slått sammen Feltarbeid og -studier

**Comment by Hypsibius** [comment]
Kva er eg då om eg foretrekk å tenke at folk køyrer eit boolsk søk? Boolehue? 

Men som tidlegare feltarbeidar har eg ikkje problem med Feltarbeid BF Feltstudier. Og sluttar meg til at feltbiologi og særleg feltornitologi  er unødig spesifikt. Særleg sidan den siste ser ut til å bli brukt for 'Bird watching' generelt, utan at ein nødvendigvis tar boka heile vegen opp i dei ornitologiske sfærer

Frøvri har vi inkludert fuglekikking/fugletitting som bf-termar for ornitologi. 

Nokon som har sjekka https://www.nrk.no/piip/, forresten? Har det så einsamt i skranken i dag at eg måtte sette på nokre krykkjeskri (dog på laaaavt volum)

**Comment by danmichaelo** [comment]
Erstattet `Feltbiologi`→ `Feltarbeid : Biologi` og slo sammen `Feltornitologi` med `Ornitologi` fordi vi allerede hadde `Fugletitting` og `Fuglekikking` som henvisningstermer der. Kan være vi burde skille ut disse, men det får heller bli en ny diskusjon – nå har vi ihvertfall samlet alt rotet på ett sted :)
