### ISSUE TITLE
Elektronisk databehandling --> databehandling

### ISSUE THREAD

**Issue by knuthe** [realfagstermer/realfagstermer#528]
Er det noen som protesterer på den sammenslåingen? (det fins selvsagt ikke-elektronisk databehandling, men der har vi f.eks "mekaniske datamaskiner" til bruk.)

Sammenslåingen vil som bonus gi meg anledning til å sjekke noen prosedyrer i Sonja, så jeg vil helst utføre det selv.

Knut

**Comment by mittinatten** [comment]
Ingen protester fra meg

**Comment by BioHeidi** [comment]
Ikke her heller

**Comment by knuthe** [comment]
Utført
