### ISSUE TITLE
Lokalmiljø = Nærmiljø

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#529]
Disse to er vel etterlevninger fra 691-feltet, og brukt 3 ganger til sammen. Slå sammen:

Lokalmiljø
BF Nærmiljø

Protester?

**Comment by BioHeidi** [comment]
Nei

**Comment by Hypsibius** [comment]
Go ahead!

**Comment by bibliomari** [comment]
Gjort
