### ISSUE TITLE
Emergens

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#53]
Mye klassifisering på meg disse dagene, og da oppdager en ting en trenger :)

Jeg foreslår følgende

     Emergens
     EN Emergent behavior
     EN Emergent behaviour
     EN Emergence
     NN Emergens

Bokmål wikipedia: https://no.wikipedia.org/wiki/Emergens
Nynorsk wikipedia: https://nn.wikipedia.org/wiki/Emergens
Engelsk wikipedia: https://en.wikipedia.org/wiki/Emergence

Belegg http://ask.bibsys.no/ask/action/show?kid=biblio&cmd=reload&pid=123791960

**Comment by bibliomari** [comment]
Gjort.
