### ISSUE TITLE
Transitivitet - vil vi ha det?

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#530]
Hva er det for noe? Det ser nemlig ikke ut som vi har noen dokumenter med det emnet, og hvis ingen forteller meg hva det er for noe har jeg kjempelyst til å slette det.

**Comment by BioHeidi** [comment]
Mener det er en matteterm...?

**Comment by bibliomari** [comment]
Har vi noen mattehoder her, da? @mittinatten

**Comment by Hypsibius** [comment]
For verb driv ikkje vi med...

**Comment by ewinge** [comment]
In mathematics, a binary relation R over a set X is transitive if whenever an element a is related to an element b, and b is in turn related to an element c, then a is also related to c. Transitivity is a key property of both partial order relations and equivalence relations.
https://en.wikipedia.org/wiki/Transitive_relation

**Comment by danmichaelo** [comment]
Oi, hei @ewinge !

Det er én (sannsynlig) mulighet. Det *kan* også være en feilskriving av Trans*m*itivitet :) Men ja, uansett, når vi ikke har litteratur om det, og ikke er helt sikker på hvilken mening som er tiltenkt så synes jeg ikke det er noe å beholde. Vi oppretter den jo bare igjen hvis vi trenger den. Jeg sletter.
