### ISSUE TITLE
Slå saman Hvaler og Cetacea

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#532]
![hvaler](https://cloud.githubusercontent.com/assets/9350370/16228371/e88ef30a-37b6-11e6-8330-d763ddefc705.PNG)

![cetacea](https://cloud.githubusercontent.com/assets/9350370/16228364/dd5a7324-37b6-11e6-95a8-a73177429ac7.PNG)

Dette er ikkje ein del av kommunesamanslåingsdebatten, så held enn så lenge min fødeby Fredrikstad utanom ;-)

**Comment by bibliomari** [comment]
Gjort, tok med etpar andre minre betydelige kommuner.
