### ISSUE TITLE
Marin eller marint plankton?

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#533]
I Roald har vi Marin plankton. Gitt at plankton er inkjekjønnsord, kling det rart, Skulel det ikkje heite marinT plantkon?

Hege

**Comment by bibliomari** [comment]
Enig!

**Comment by bibliomari** [comment]
Hm, vi hadde faktisk også Marine plankton BF Marint plankton, haha. Jeg har slått dem sammen. 
SE OGSÅ Ferskvannsplankton???

**Comment by Hypsibius** [comment]
Ja, SO-term på sin plass!

**Comment by danmichaelo** [comment]
Gjort
