### ISSUE TITLE
Økofilosofi = Økosofi, ikke sant?

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#534]
Jeg vil så gjerne slå dem sammen. @BioHeidi ? @Hypsibius ?

**Comment by bibliomari** [comment]
Eller nei, Store norske leksikon sier:
 "Økosofi blir da, i motsetning til økofilosofi, en normativ eller normgivende disiplin." Det var jo ikke akkurat det som sto i Wikipedia. Da prøver jeg meg i stedet med noen andre sammenslåinger av emneord vi allerede har:

Økosofi
BF Naturetikk
BF Miljøetikk 
EN Ecosophy
SO Økofilosofi
DEF: Økosofi, filosofisk system som setter økologisk likevekt som grunnverdi, eller et filosofisk system som behandler naturen under mangfoldets perspektiv slik at menneskene blir deler av naturen, og naturrettsnormene utvides til å gjelde all natur; begrep utledet av Arne Næss. (SNL)

Økofilosofi
BF: Miljøfilosofi
EN: Environmental philosophy
SO Økosofi
DEF: Økofilosofi, økologiens filosofi, type vitenskapsfilosofi i analogi med for eksempel fysikkens vitenskapsfilosofi.(SNL)

... og så fjerne de to strengene Økologi : Etikk og Økologi : Filosofi, siden disse dekkes av begrepene over.

**Comment by bibliomari** [comment]
...eller er jeg helt uvitenskapsfilosofisk når jeg blander etikk og filosofi??? @BioHeidi, I'm coming over!

**Comment by Hypsibius** [comment]
Keep me posted :-)

**Comment by danmichaelo** [comment]
Dette er jo litt moro. [Her](https://www.nb.no/nbsok/nb/e112d28f783be10b1f105ad4f4876c27?index=2#63) er Næss sin forklaring, som @bibliomari sin inndeling ser ut til å være i tråd med.

Men hva sier de utenfor Norge? Stanford Encyclopedia of Philosophy har omtalt *Ecosophy T* under *Deep ecology* i artikkelen om *[Environmental Ethics](https://plato.stanford.edu/entries/ethics-environmental/)*, mens *Philosophy of Ecology and Conservation Biology* er omtalt under [Philosophy of Biology](https://plato.stanford.edu/entries/biology-philosophy/#7).

Kanskje vi skal beholde `Miljøetikk <brukt for> Naturetikk` som eget begrep, siden det virker som det er mer generelt enn økosofi? Hvis vi regner økosofi som synonymt med Næss sin "økosofi T" da :) 

Hey, kanskje @hgsl mener noe om dette! Vi er jo litt i Realfagstermers ytterkanter her.

**Comment by hgsl** [comment]
I Realfagstermers ytterkanter, i filosofiens kjerne!

Sånn på helt generell basis: Filosofi og etikk er ikke synonymt med hverandre. Etikk regnes vanligvis bare som én av flere sentrale pillarer av filosofien, I tillegg kommer områder som metafysikk, epistemologi, vitenskapsfilosofi, politisk filosofi, osv. osv.

Når det gjelder miljøetikk/miljøfilosofi/økologiens filosofi vs. økosofi mener jeg også man bør skille mellom disse. Førstnevnte er mer generelt. Økosofien er betegnelsen på den etiske skoleretningen Næss i sin tid dannet (inspirert av Spinozas etikk), mens økofilosofi/økologiens filosofi betegner en avgrensning av vitenskapsfilosofi/biologiens filosofi hvor det sentrale er at man foretar en filosofisk granskning av vitenskapen økologi.

Jeg tror også DM har rett i at miljøetikk er mer generelt enn økosofi, siden økosofien som nevnt betegner en konkret skoleretning/konkret verdisyn, mens miljøetikk er et generelt område av etikken hvor det kan finnes rom for ulike verdisyn og retninger.

Ingen av disse områdene er forresten mine spesialfelt, så jeg er definitivt åpen for motargumenter. :)

**Comment by danmichaelo** [comment]
Takk @hgsl ! Mens vi venter på at noen kommer med kløktige motargumenter har jeg ihvertfall lagt inn noen definisjoner og henvisninger nå, siden det ser ut som vi beholder Økofilosofi/Mijøfillosofi/Økologiens filosofi, Økosofi og Miljøetikk/Naturetikk.

Nå mangler vi bare `Biologiens filosofi`! Eller, nei, vi har jo faktisk [Biologi : Filosofi] som streng. Kanskje vi skulle gjort om på den, @BioHeidi ? Eller så kan vi vente til vi får lagt inn se-henvisninger på strenger...

**Comment by BioHeidi** [comment]
Satser på se-henvisninger, for det trenger vi i så mange mange sammenhenger!

Ellers godt jobbet!

**Comment by danmichaelo** [comment]
Hah, vi *kan* faktisk legge inn se-henv. på strenger! Spre det glade budskap! https://app.uio.no/ub/emnesok/realfagstermer/search?id=c028380
