### ISSUE TITLE
Forørkning vs Ørkenspredning

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#535]
Vil vi ha disse hver for seg? I så fall vil jeg sette SE OGSÅ mellom, men først vil jeg ha et ørkenfaglig synspunkt på eventuell sammenslåing.

**Comment by Hypsibius** [comment]
Synest den siste termen er meir forklarande og språkleg ajour som hovudinnførsel, slå saman i veg!

**Comment by danmichaelo** [comment]
Slått sammen: Ørkenspredning BF Forørkning
