### ISSUE TITLE
Automatisk resonnering (innflesking)

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#536]
Automatisk resonnering har BF Resonnering, den har jeg lyst til å slette, for det er forvirrende. 

OK, @knuthe? Trefflista ser ut som det er helt ok, muligens med unntak av The web of belief.

**Comment by knuthe** [comment]
Ja, OK. (innflesking?)

**Comment by bibliomari** [comment]
Gjort
