### ISSUE TITLE
Biomatematikk vs Matematisk biologi

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#537]
I dag har vi begge emnene, med SE OGSÅ mellom. Stemmer det, eller er det et kunstig skille? Hvis vi ønsker å opprettholde skillet hadde det vært fint med definisjoner. @BioHeidi @Hypsibius

**Comment by Hypsibius** [comment]
Sanneleg om eg veit. Vi snakkar om biomatematikk for all matematikk anvendt i biologi, kanskje matematisk biologi meir er sånt som matematikarar likar å sjå på? Lovmessigheiter? Fibonacci? @mittinatten ?

**Comment by BioHeidi** [comment]
Kan egentlig ikke se noe skille.

**Comment by danmichaelo** [comment]
Vi slo sammen `Biomatematikk BF Matematisk biologi`
