### ISSUE TITLE
Taksering, hva er det for oss?

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#539]
Noen som vil våge seg på å forklare betydningen av Taksering i Realfagstermer, basert på de tre forekomstene av emnet i søk?

https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006114&broad=false 

Det øverste ser ut som verdiberegning for meg, men de to nederste? @BioHeidi @Hypsibius

**Comment by BioHeidi** [comment]
Heh. En forvanskning av taksonomi, ser det ut til. Jeg rydder og sletter.

**Comment by BioHeidi** [comment]
Nå har vi `Skogtaksering`. og vi har `Taksering` (på ett dokument som handler om skogtaksering).

**Comment by Hypsibius** [comment]
Ja, men taksering i økologi (t.d. fugl) er vel det å lage ei inventering, ei oversikt over kva som finst? 
Jf transektanalyse?

Jf desse: https://snl.no/%25C3%25A5rets_fugl

http://www.nesk.no/nyheter/1346-lyst-til-a-taksere-fugl-eller-utdanne-deg-til-aversjonsinstruktor

http://www.fefo.no/no/jakt/Sider/Takseringsresultat-smaavilt.aspx

**Comment by BioHeidi** [comment]
Ja det er det vel. Men har vi ikke at annet ord for det?

**Comment by Hypsibius** [comment]
Joeh, men eg kjem ikkje på i farta (tenketenke)

**Comment by BioHeidi** [comment]
Fant kanskje noe, vi har Bestandsanalyse, Bestandsutvikling, Populasjonstetthet, Populasjonsdynamikk, Fugletellinger, Fisketelling, og bare Telling - som alle er brukt paa dokumenter som omhandler taksering i den forstand. Noen av disse emneordene er brukt litt bredere i tillegg.

**Comment by danmichaelo** [comment]
Flyttet den ene dokumentet over til `Skogtaksering` og slettet `Taksering`.

`Telling`... *grøss*
