### ISSUE TITLE
Melkesyrebakterier

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#540]
`Melkesyrebakterier BF Probiotika, Prebiotika, Laktobakterier`

Det var nok et forsøk på å lage sekkepost på et tidspunkt hvor dette med pre- og probiotika var relativt nytt i litteraturen, men nå har jeg veldig behov for å splitte.

Foreslår nå splitting i tre emneord:
Probiotika
Prebiotika
Melkesyrebakterier BF Laktobakterier

De fleste dokumenter foreløpig vil få både Pre- og Pro-, men det vil nok komme behov for et skille senere. Pre- er ikke bakterier, mens Pro- er det. Melkesyrebakterier er en taksonomisk enhet, de to andre er det ikke.

**Comment by BioHeidi** [comment]
Og om forslaget blir nedstemt vil jeg iallefall snu på det og ha Probiotika som BF.

**Comment by bibliomari** [comment]
Høres fornuftig ut å splitte!

**Comment by Hypsibius** [comment]
Istemmer!

**Comment by BioHeidi** [comment]
Gjort. Og ryddet i katalogpostene våre, kanskje du vil gjøre det samme, @Hypsibius ? Søk på melkesyrebakterier og se hvilke av deres som heller burde ha pre/pro. Jeg så en som ikke vi hadde, men turde ikke å gjøre noe med den:
Aquaculture nutrition : gut health, probiotics and prebiotics (2014)

**Comment by Hypsibius** [comment]
Done!

**Comment by bibliomari** [comment]
Yesdone
