### ISSUE TITLE
Historikere? Nytt forslag trureg

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#541]
Trenger emneord til denne biografien:
Samfunnsborgeren : Erik Rudeng 70 år 
ISBN 9788253038803

Har lyst til å ha strengen Historikere: Biografier 
Evt Historie: Biografier men det tror jeg ikke jeg får lov til å bygge i Roald?

**Comment by bibliomari** [comment]
Tror du skal kunne bygge den strengen, eller opprett historikere, det
passer vel inn?
14. jul. 2016 10.37 a.m. skrev "Heidi Konestabo" <notifications@github.com>:

**Comment by BioHeidi** [comment]
Ja, er vi landet på det? At vi beholder fysikere? (jfr tidligere diskusjoner om biografier)

**Comment by BioHeidi** [comment]
Og du har ferie!

**Comment by bibliomari** [comment]
Jeg minnes vagt en sånn diskusjon, kan du forfriske meg? Humord har en lang liste med personer etter yrke, det er fristende å gjøre som dem, altså godta både Historikere og Fysikere osv osv osv.

**Comment by Violabibaluba** [comment]
Vi godtar historikere-biografier og lager strengen. Resten av diskusjonen  #43 grunner vi litt på....
