### ISSUE TITLE
Dinocyster & Dinoflagellatcyster

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#543]
Vi har begge i Roald. Kan ikkje forstå anna enn at det er det same?

![dinocyster](https://cloud.githubusercontent.com/assets/9350370/17548338/bcfa6772-5eeb-11e6-8de9-59927aa0aaca.PNG)

Kva som bør vere fortrukken term? Tja. Dinoflagellatcyster er meir sjølvforklarande (skjønt, ingen trur vel vi snakkar om dinosaurar) og gir ca 10x så mange treff på Google. Dinocyster har eiga innførsle i norsk geologisk ordbok...

![dino](https://cloud.githubusercontent.com/assets/9350370/17548722/6aed6590-5eed-11e6-93d5-c49c90717a2a.JPG)

**Comment by bibliomari** [comment]
Yesdone
