### ISSUE TITLE
Integrasjon vs integrasjonsteori

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#544]
Vårt emneord Integrasjon kom inn via MSC. Dvs matematisk bibliotek brukte Integrasjon, med  msc-nummeret 28. Det er på et tidspunkt koblet til ddc 515.42, hvis klassebetegnelse er Måle- og integrasjonsteori.

Da er det jammen fristende å slå sammen Integrasjon og Integrasjonsteori, som begge er emneord hos oss. Protester? Jubel?

**Comment by mittinatten** [comment]
Ingen protester her. `Integrasjon (matematikk)` som foretrukket?

**Comment by bibliomari** [comment]
Jepp, takk!
