### ISSUE TITLE
Diskriminering = Diskriminantanalyse?

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#545]
Overlapper disse i betydning, slik at jeg kan slå sammen disse? Få treff. Diskriminering er knyttet til MSC70 62.41. @mittinatten

**Comment by mittinatten** [comment]
Ja, har aldri hørt det kalles diskriminering, men det ser ut som at det er detsamme, og MSC bruker det fremdeles i 62H30. Hadde gjerne lagt Diskriminantanalyse som foretrukket og fjernet lenkene til feil wikipedia-side under diskriminering. Snevert emnesøk på diskriminering gir bare tre treff, og de ser alle ut som diskriminantanalyse.

**Comment by danmichaelo** [comment]
Slått sammen som `Diskriminantanalyse BF Diskriminering `
