### ISSUE TITLE
Populærvitenskap

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#546]
Hei,
Jeg har nettopp begynt å jobbe med realfagstermer for geofagsamlingen ved UBB. Systemet er altså helt nytt for meg så det kan hende at jeg har foreløpig ganske mange spørsmål...
For andre boken jeg skal klassifisere ( ISBN: 9780307379092 ), hadde jeg gjerne brukt:

> 650_7 > Naturkatastrofer $$0 (NoOU)REAL011087 $$2 noubomn
> 655 _7 > Populærvitenskap $$0 (NoOU)REAL030121 $$2 noubomn

men for termen populærvitenskap er det notert:

> Populærvitenskap (REAL030121)
>   NO Unngå å bruke denne! Vi rydder.... for å skille den fra Populærvitenskap. Hvis du virkelig mener at du trenger den, send søknad i fire eksemplarer til emneredaksjonen... ML 5.6.15

Samtidig finnes det mange forskjellige termer som f.eks.:

> populærastronomi
> populærfysikk
> populærkjemi
> populærmatematikk

Så jeg lurer på om jeg kan bruke termen populærvitenskap eller ikke?
Hadde det ellers vært logisk å slå sammen de forskjellige termene og bruke strenger som f.eks.

> Populærvitenskap : astronomi 

Takk for hjelpen på forhånd!
Johannes

**Comment by bibliomari** [comment]
Velkommen til Realfagstermer, @jw-geo, og takk for engasjement! Dette ser jo ikke logisk ut, og forklaringen er at etter at vi skrev denne noten om unngå bruk, har vi slått sammen "populærvitenskap" og "populærlitteratur". Jeg skal fjerne noten, bare bruk termen. 

Inkonsekvent bruk av strenger/sammensatte termer: Et sårt punkt, som vi forsøker å rydde opp i litt innimellom. Jeg ser jo at vi har mange flere treff på strengen Astronomi : Populærvitenskap enn på Populærastronomi, så velg gjerne strengen, så rydder "man" når ånden kommer over en.

**Comment by bibliomari** [comment]
... men allerede ser jeg at vi har over 400 treff for Populærfysikk. Hva synes du, @danmichaelo , vil du ha Populærfysikk eller Fysikk : Populærvitenskap?

**Comment by danmichaelo** [comment]
Velkommen @jw-geo !

Dette har plaget meg også, men jeg har ikke fått ånden over meg til å ta tak i det. Har sikkert brukt Populærfysikk litt fordi den finnes, men tror kanskje jeg foretrekker Fysikk : Populærvitenskap, siden vi da skiller emne og form.

**Comment by jw-geo** [comment]
Takk for tilbakemeldingen. Jeg synes at klassifiseringen i strenger (f.eks. Geovitenskap : Populærvitenskap) er generell mer praktisk.

**Comment by bibliomari** [comment]
Da er det bare å lære Lokar å erstatte emner med strenger, @danmichaelo ... :cake:

**Comment by danmichaelo** [comment]
> Da er det bare å lære Lokar å erstatte emner med strenger, @danmichaelo ... :cake: 

Betyr det at jeg får kake hvis jeg fikser det?

**Comment by bibliomari** [comment]
Ja, det må jo være det det betyr??? Det er Github som har bestemt det!

**Comment by danmichaelo** [comment]
https://github.com/scriptotek/lokar/issues/4#issuecomment-249899918

**Comment by grosyn** [comment]
Eg ser på formtermene våre, og lurer på kvifor Populærvitenskap ikkje er innhaldsbeskrivande. Populærastronomi, Populærfysikk osv (som no, etter at strengane har forsvunne, virkar meir tilforlatelege enn før) er jo innhaldsbeskrivane. Og Humord har Populærvitenskap som innhaldsbeskrivande. 
Får eg store protestar om eg flyttar Populærvitenskap frå form- til emneterm?

@BioHeidi @kyrretl @superLine @haraldse @TorgunnKarolineMoe @edinab

**Comment by TorgunnKarolineMoe** [comment]
Ingen motforestillinger her, men jeg føyer meg etter Heidi og Line!


Karoline Moe

Førstebibliotekar / Matematikk



Universitetet i Oslo

Bibliotek for medisin og realfag

E-post: ***@***.******@***.***>***@***.***>***@***.***>***@***.***>




________________________________
