### ISSUE TITLE
geofysikk = jordas geofysikk

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#549]
Wikipedia: 

> Geofysikk er læren om jordens fysikk

Derfor synes jeg 'jordas geofysikk' trenges ikke som term.

**Comment by bibliomari** [comment]
Det høres fornuftig ut. Men denne plager meg:

https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBO:bibsys_ils:BIBSYS_ILS71480071120002201

Eller hva, @superLine og @danmichaelo ?

**Comment by superLine** [comment]
Det er kanskje lurt å lage strenger på de som ikke har med jorda å gjøre? Månen har forresten sin selenografi (fine ordet)

 559.9Earth sciences of extraterrestrial worlds
  559.9092Astrogeologists
  559/.91Moon--earth sciences
  559.9/23Mars (Planet)--earth sciences

**Comment by danmichaelo** [comment]
Enig. Vi kan la jorda være default, og bruke strenger for andre planeter.

(Ser ut som definisjonen på nowiki er litt for snever :))

**Comment by danmichaelo** [comment]
Slo de sammen.

Vi hadde allerede [Geofysikk : Mars](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c019286)
