### ISSUE TITLE
Biologi/Biovitenskap/Livsvitenskaper

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#55]
Vi har termene Biologi, Biovitenskap og Livsvitenskaper. I DDC-23 ligger alle under 570 Biologi. Jeg foreslår (men diskuterer med den andre biologen hos oss) at vi beholder termen Livsvitenskaper, da forbeholdt tverrfaglige ting som omfatter biologi, kjemi, farmasi og medisin. Hvor det havner i DDC får avgjøres i hvert enkelt tilfelle. Vi kan legge inn på Livsvitenskaper en se-også-henvisning til Biologi.

Jeg foreslår også at termen Biovitenskap legges inn under Biologi, (Biologi BF Biovitenskap), og at emnet Farmasøytisk biovitenskap endres til Farmasøytisk biologi BF Farmasøytisk biovitenskap.

Hva synes du @Hypsibius ?

**Comment by BioHeidi** [comment]
Jeg fikser denne om ingen protesterer.

**Comment by Hypsibius** [comment]
Ingen protester :-)

**Comment by bibliomari** [comment]
Hurra!!
