### ISSUE TITLE
Petroleumsforekomster vs. Petroleumsfelt

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#550]
Jeg foreslår følgende klassifiseringen:
### Petroleumsforekomster

BF Petroleumsreservoarer
BF Hydrokarbonreservoarer
BF Hydrokarbonforekomster
BF Hydrokarbonavsetninger
BF Oljeforekomster
BF Gassforekomster 
EN Petroleum reservoir
EN Oil and gas reservoir
EN Hydrocarbon reservoir
SO Petroleumsfelt
DE En ansamling av petroleum i en geologisk enhet i undergrunnen, påvist ved boring. Petroleumsforekomster kan unntaksvis også finnes på overflaten. (Norsk geologisk ordbok)
### Petroleumsfelt

BF Oljefelt
BF Gassfelt
EN Petroleum field
EN Hydrocarbon field
EN Oil field
EN Gass field
DE Petroleumsforekomst som har en godkjent «Plan for Utbygging og Drift (PUD)» eller som er innvilget fritak for PUD av myndighetene. (Norsk geologisk ordbok

Eller synes dere at Olje-/Gassfelt burde være selvstendige termer?

**Comment by bibliomari** [comment]
@kristinran ønsket å holde disse hver for seg, mener jeg. Her må vi nok tenke høyt noen runder. Forøvrig er hele Realfagsbiblioteket på seminar langt unna norske oljeforekomster denne uka, derfor litt lav diskusjonstakt :-)

**Comment by BioHeidi** [comment]
Pling til @kristinran igjen!

**Comment by kristinran** [comment]
Petroleum igjen? Skal jeg svare igjen på github?



Kristin

________________________________
Fra: Heidi Konestabo <notifications@github.com>
Sendt: 5. desember 2016 15:45
Til: realfagstermer/realfagstermer
Kopi: Kristin Rangnes; Mention
Emne: Re: [realfagstermer/realfagstermer] Petroleumsforekomster vs. Petroleumsfelt (#550)


Pling til @kristinran<https://github.com/kristinran> igjen!

-

**Comment by kristinran** [comment]
og da kom den melding også her! Sånn er det når man sitter langt borte. Jeg mener fortsatt at petroleumsforekomster dekker "alt"; geologi, volum av forekomster etc.  mens petroleumsfelt dekker mer info om de enkelte felt. Synes BF og DE feltene viser at dette er meningsfullt.

**Comment by BioHeidi** [comment]
Forstår jeg deg riktig som at du da godkjenner sammenslåingen som foreslått over? Må bare spørre en gang til siden Mari skriver at du ville holde dem separat.

**Comment by kristinran** [comment]
Egentlig mener jeg motsatt, men det er kanskje ikke så veldig viktig. Hvis det er en bok som handler om Osebergfeltet i et historisk perspektiv, kommer den på Petroleumsforekomster, men får  ikke som Oljefelt, som mange utenfor realfagsmiljøet kanskje ville bruke.





________________________________
Fra: Heidi Konestabo <notifications@github.com>
Sendt: 6. desember 2016 11:59
Til: realfagstermer/realfagstermer
Kopi: Kristin Rangnes; Mention
Emne: Re: [realfagstermer/realfagstermer] Petroleumsforekomster vs. Petroleumsfelt (#550)


Forstår jeg deg riktig som at du da godkjenner sammenslåingen som foreslått over? Må bare spørre en gang til siden Mari skriver at du ville holde dem separat.

-

**Comment by BioHeidi** [comment]
Ok, skjoenner. Troesten faar vaere at hvis de soeker paa Oljefelt vil de faa treff paa Petroleumsfelt, og vi kan ha en SO (se ogsaa) som peker til Petroleumsforekomster. Saa finner de kanskje frem den veien.

**Comment by danmichaelo** [comment]
Da tok jeg sjansen på å gjennomføre forslaget til @jw-geo , og la inn SO mellom de to termene.
