### ISSUE TITLE
Liste med engelske termer

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#558]
Her er en alfabetisk liste med forslag til en rekke engelske realfagstermer:

Anvendt geofysikk -> exploration geophysics, applied geophysics
Biogeokjemisk syklus -> biogeochemical cycle
Fast jords geofysikk -> solid earth geophysics
Flyfoto -> Aerial photography
Fossiler -> fossils
Geobiologi -> geobiology
Geofysikk -> geophysics
Geofysiske metoder -> geophysical methods
Geofysiske prosesser -> geophysical processes
Geomorfologi -> geomorphology
Geovitenskap -> geoscience, earth science
Geoøkologi -> geoecology
Havnivå -> sea level
Historisk geologi -> historical geology
Jordrotasjon -> earth’s rotation
Jordskjelv -> earthquake
Karbondioksid -> carbon dioxide
Miljøgeologi -> environmental geology
Periglasial geomorfologi -> periglacial geomorphology
Petroleumsgeologi -> petroleum geology
Satellittbilder -> satellite imagery
Solformørkelser -> solar eclipse
Tidevann -> tide
Tyngdebølger -> gravity waves

**Comment by danmichaelo** [comment]
Lagt til!
