### ISSUE TITLE
Statistisk mekanikk = Statistisk fysikk?

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#559]
Det sier Wikipedia. Kan de slås sammen? 

Og hvilket forhold har Perkolasjon til Statistisk fysikk? Ser at de henger sammen, men tett nok tilo sammenslåing eller Se også?

@danmichaelo

**Comment by mittinatten** [comment]
Tenker denne er ekvivalent med #68. Statistisk mekanikk som foretrukket foreslår jeg.

Perkolasjon er et fenomen som studeres innenfor statistisk mekanikk. Der er nok treff på bredt søk at jeg syns den fortjener en egen term.

**Comment by mittinatten** [comment]
På samme måte kan sikkert `Væskefysikk` slås sammen med `Fluidmekanikk`. Kanskje vi har flere med både -fysikk/-mekanikk.

**Comment by danmichaelo** [comment]
Støtter alt! Altså 

- `Statistisk mekanikk BF Statistisk fysikk` 
- `Perkolasjon` som eget emne
- `Fluidmekanikk BF Væskefysikk SO Fluiddynamikk`

**Comment by Violabibaluba** [comment]
Gjort!
