### ISSUE TITLE
Atlanterhavsryggen

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#561]
Eit par spørsmål om denne: Er det rett at denne skal vere emneterm og ikkje stadterm?

Kan vi få ein BF Den Midtatlantiske Rygg(en) (jf Wikipedia og SLN?) EN Mid-Atlatic Ridge

**Comment by jw-geo** [comment]
Den overordnete termen er Midthavsrygger (mid-ocean ridge). Atlanterhavsryggen er sånn sett bare en lokal versjon i Atlanterhavet. Men jeg er enig, at termen er heller ikke riktig som stedterm.
Kanskje vi kunne heller bruke strenger f.eks. med Atlanterhavet som stedsterm og:

Midthavsrygger
 BF Den Midtatlantiske Ryggen
 BF Atlanterhavsryggen
 En Mid-ocean ridge

**Comment by BioHeidi** [comment]
@Violabibaluba

**Comment by danmichaelo** [comment]
La til `BF Den midtatlantiske ryggen` på `Atlanterhavsryggen`.

`Atlanterhavsryggen`  er vel en forekomst av `midthavsrygg` på samme måte som `Pyreneene` er en forekomst  av `fjellkjede`? Tror også at det burde vært en stedterm.

**Comment by Violabibaluba** [comment]
Vi oppretter Atlaterhavsryggen som stedterm, Vi har Midthavsrygger som emne. Den kan kombineres i streng, f.eks. Midthavsrygger: Indiske hav. Men siden Atlanterhavsryggen er en vanlig benevnelse på en midthavsrygg i Atlanterhavet så er det mest hensiktsmessig å bruke det, istedet for å si Midthavsrygger : Atlanterhavet.
