### ISSUE TITLE
Sammenslåing: Beregningskjemi og Beregningsorientert kjemi

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#562]
Med Beregningskjemi som foretrukket tror jeg.

For fysikk tror jeg egentlig "beregningsorientert fysikk" er mer i bruk enn "beregningsfysikk", men for konsistens kunne vi sikkert hatt Beregningsfysikk som foretrukket term. Eller hva tror @mittinatten ?

Og [Beregningsbiologi](http://www.uib.no/mbi/54298/beregningsbiologi-computational-biology) er vel ok, @BioHeidi ?

**Comment by mittinatten** [comment]
Beregninsfysikk høres ok ut! (men det kanskje jeg bare syns fordi det heter "beräkningsfysik" på svensk)

**Comment by danmichaelo** [comment]
Hehe.

Men da slo jeg de sammen, og gjorde om fys til `Beregningsfysikk BF Beregningsorientert fysikk`. Siden @BioHeidi ga taust samtykke endret jeg tilsv. for bio.
