### ISSUE TITLE
Sammenslåing: Fjernanalyse og Fjernmåling

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#563]
Er det viktig å skille mellom de to?

**Comment by danmichaelo** [comment]
Nei, det tror jeg ikke når jeg leser http://www.mn.uio.no/geo/forskning/vi-forsker-pa/fjernanalyse/ : "Begrepene 'fjernanalyse' og 'fjernmåling' brukes om hverandre".

Har du noe ønske om hvilken som bør være foretrukket term? Fjernmåling?

**Comment by jw-geo** [comment]
Etter jeg har lest teksten i lenken din ville jeg ta Fjernanalyse som foretrukket term.

**Comment by danmichaelo** [comment]
Da slo jeg de sammen med Fjernanalyse som foretrukket term. Det er forøvrig enkelt å bytte om senere hvis vi skulle ombestemme oss.
