### ISSUE TITLE
Slå sammen gravitasjon og tyngdekraft

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#564]
Foretrukket term: Gravitasjon (fordi "kraft" gir assosiasjoner til klassisk fysikk)

Enig, @mittinatten ?

**Comment by mittinatten** [comment]
Enig

**Comment by danmichaelo** [comment]
Done!

**Comment by danmichaelo** [comment]
Tok `Tyngdebølger` og `Gravitasjonsbølger` også :)
