### ISSUE TITLE
Fast jords fysikk og Fast jords geofysikk

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#565]
Trengs begge, mon tro?

* https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006262&broad=false
* https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007559&broad=false

Hvis de skal slås sammen, hvilken bør beholdes? Og kunne `Fastjordsfysikk` vært en ok term? 

@realfagstermer/geofag

**Comment by danmichaelo** [comment]
(ser at denne er litt relartert til #549)

**Comment by jw-geo** [comment]
Jeg synes at det holder med `Fast jords fysikk`. 
`Fastjordsfysikk` har jeg aldri sett, så jeg synes ikke at vi burde bruke den som term.

**Comment by danmichaelo** [comment]
Slått sammen, med `Fast jords fysikk` som foretrukken term.

**Comment by Hypsibius** [comment]
Ser at fastjodsfysikk har ein del treff, også på Wikipedia og på UIB-nettsider, så den bør vere med som BF-term

**Comment by danmichaelo** [comment]
> Ser at fastjodsfysikk har ein del treff, også på Wikipedia og på UIB-nettsider, så den bør vere med som BF-term

Lagt til (*uten* skrivefeil ;))
