### ISSUE TITLE
Chert

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#570]
Trenger vi som term.

Chert
  BF Kiselstein
  DE Sedimentær bergart eller mineralmasse sammensatt av meget finkornet kvarts. (SNL)

**Comment by Violabibaluba** [comment]
Vi velger den mest slvforklarende norske termen som foretrukken. Opprettet.

**Comment by danmichaelo** [comment]
altså kiselstein :) http://data.ub.uio.no/realfagstermer/c031754
