### ISSUE TITLE
Seismiske grunnundersøkelser

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#571]
Vi har en del forskjellige termer for seismiske undersøkelser som er veldig lignende. Jeg kunne tenke meg at der er bedre hvis vi slå sammen noen av dem og bruker to forskjellige termer:`Seismisk grunnundersøkelser`og `Seismisk oljeleting`.

Det kunne se slikt ut:

Seismiske grunnundersøkelser 
BF Seismiske undersøkelser
BF Seismisk kartlegging
EN Seismic surveys
SO Seismisk oljeleting

Seismisk oljeleting
BF Seismisk prospektering
EN Seismic hydrocarbon exploration
SO Seismiske grunnundersøkelser

**Comment by danmichaelo** [comment]
Lurte først litt på om `Seismisk prospektering` kunne inkludere leting etter annet enn olje, men i praksis gjør det vel kanskje ikke det?

Har du tenkt noe mer i mellomtiden? Hvis ikke foreslår jeg at vi bare gjennomfører forslaget ditt.

**Comment by jw-geo** [comment]
Du har en god poeng der. Generellt stemmer det sikker men jeg tror og at det ikke gjør noen forskjell i praksis. Jeg har i alle fall ingen bedre forslag...

**Comment by danmichaelo** [comment]
Da gjennomførte jeg endringen!
