### ISSUE TITLE
Variasjonsmetoden og Variasjonsregning

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#572]
Kan vi slå sammen: `Variasjonsmetoden` og `Variasjonsregning`?

Finner at Variasjonsmetoden er brukt for 2 og Variasjonsregning for 446 dokumenter.

**Comment by mittinatten** [comment]
Innstemmer

**Comment by danmichaelo** [comment]
`Variasjonsmetoden` er nok ment å vise til https://en.wikipedia.org/wiki/Variational_method_(quantum_mechanics), som riktignok er anvendt variasjonsregning, men kanskje greit å beholde som eget begrep med definisjon?

Jeg la inn "Approksimasjonsmetode i kvantemekanikk for å finne en øvre grense for egenverdier til en kvantemekanisk observabel med et diskret spektrum" basert på tysk wikipedia

**Comment by mittinatten** [comment]
Ok, da med SO antar jeg?

**Comment by jw-geo** [comment]
Ok, da har jeg lært noe nytt ;)
