### ISSUE TITLE
Ny liste med engelske termer

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#574]
Atmosfærefysikk -> Atmospheric physics
Atmosfæredynamikk -> Atmosphere dynamics
Biostratigrafi -> Biostratigraphy
Deltaavsetninger -> Delta sediments
Diagenese -> Diagenesis
Elektromagnetiske bølger -> Electromagnetic waves
Fluiddynamikk -> Fluid dynamics
Geokronologi  -> Geochronology
Grunnvann -> Groundwater
Hydraulikk -> Hydraulics
Karbon (tidsavsnitt) -> Carboniferous
Kjemiske sedimenter -> Chemical sediments
Klimatologi -> Climatology
Kvartær -> Quaternary
Litostratigrafi -> Litostratigraphy
Oljeleting -> Hydrocarbon exploration
Oseanografi -> Oceanography
Paleoklimatologi -> Paleoclimatology
Paleontologi -> Paleontology, Palaeontology
Porøsitet -> Porosity
Sandsteiner -> Sandstones
Sedimentasjonsmiljøer -> Depositional environments, Sedimentary facies
Sekvensstratigrafi  -> Sequence stratigraphy
Skyer -> Clouds
Speleologi -> Speleology
Sprekker -> Fractures
Stratigrafi -> Stratigraphy
Økonomisk geologi -> Economic geology

**Comment by danmichaelo** [comment]
Lagt inn!

 Ser forresten at vi har både "Sprekker" og "Fjellsprekker"... hva synes du om det, @jw-geo ? Er det et poeng å ha begge? Og hvordan er forholdet mellom Sprekker og Brudd ?

**Comment by jw-geo** [comment]
Takk skal du har. Det ser ut som "Fjellsprekker" er hovedsakelig brukt i aviser og ikke egentlig som faglig term, så jeg synes at det er nok med "Sprekker".

Forholdet mellom "Sprekker" og "Brudd" er vanskelig, fordi de blir nesten brukt som synomymer med det er de egentlig ikke. 
"Brudd" er den mer generelle term som kommer fra mekanikken. Definisjon ifølge Norsk Geologisk Ordbok: 

> Allmen betegnelse for en oppbryting som skyldes mekaniske spenninger i berggrunnen.

"Sprekker" er 

> bruddflater hvor det ikke har foregått synlig forskyving langs flaten.

(NGO)

Så jeg tror vi trenger begge termer sikkert best med SO. Entydige engelske oversettelser er dessverre vanskelig men det passer best med:

Brudd -> Fractures
Sprekker -> Joints, Tensile fractures

**Comment by BioHeidi** [comment]
Gjort!
