### ISSUE TITLE
Strengeforslag: Statistiske Metoder : Geovitenskap eller Geovitenskap : Statistiske Metoder??

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#577]
Det finnes flere bøker om statistiske metoder for geovitenskap.
Kan vi bruke strengen: `Statistiske Metoder : Geovitenskap`?

**Comment by jw-geo** [comment]
Jeg ser nå at vi har Statistikk : Geovitenskap.
Lurer bare på om det ikke hadde vært bedre med Geovitenskap : Statistikk eller Geovitenskap : Statistiske Metoder.
Trenger litt hjelp her, er fortsatt litt usikker med bruket av strenger.

**Comment by BioHeidi** [comment]
Akk ja, de strengene. Jeg tror vi har landet paa at det egentlig ikke er saa viktig hvilken vei strengene staar, saa lenge det gir mening. 

Vi har jo en del statistikkstrenger, saa det er kanskje lurt aa vaere konsekvent paa naar vi bruker statistikk og naar vi bruker statistiske metoder. Og gjerne fag foerst, og statistikktermen etterpaa, saa lenge det ikke handler om faget statistikk.

Hjalp det?

**Comment by jw-geo** [comment]
Det hjalp! Da synes jeg vi burde ha:

Geovitenskap : Statistiske Metoder

**Comment by grosyn** [comment]
Denne lukker eg sidan strengane er eit avslutta kapittel.
