### ISSUE TITLE
Ny term: Geoinformatikk 

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#578]
Geoinformatikk
EN Geoinformatics

https://en.wikipedia.org/wiki/Geoinformatics

**Comment by Violabibaluba** [comment]
Oppretter ny term. Heter det det samme på nynorsk?

**Comment by jw-geo** [comment]
Ja, det er det samme.

**Comment by danmichaelo** [comment]
La til nynorsk
