### ISSUE TITLE
Go - feil wikiside

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#579]
Termen for programmeringsspråket `Go` har lenke til Wikipedia-siden for brettspillet med samme navn.

**Comment by danmichaelo** [comment]
Jupps, disse slåes jo opp on-the-fly, så foreløpig har vi ikke noen måte for å markere om et oppslag er riktig eller ei, men det bør vi få i fremtiden.

SO https://github.com/scriptotek/emnesok/issues/102

**Comment by danmichaelo** [comment]
Har lagt inn riktig mapping i https://soksed.biblionaut.net/concepts/REAL031581 , så da er det bare å legge til generell støtte for å lese mappingdataene i Emnesøk, men det er en annen sak...
