### ISSUE TITLE
Science literacy el scientific literacy på norsk? 

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#583]
Mogeleg vi har ein term, som ikkje eg kjem på. Ingen norsk artikkel kopla til den engelske på Wikipedia, og sidan eg er uviss på kva det er på norsk, klarer eg heller ikkje finne noko på SNL. Forlsag?

https://en.wikipedia.org/wiki/Scientific_literacy

Kunne vere aktuelt på: 

https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71539938570002201

**Comment by danmichaelo** [comment]
Vitenskapsforståelse..? Nei, jeg vet ikke, synes literacy-begrepet er vanskelig å fange..

- http://www.sprakradet.no/svardatabase/sporsmal-og-svar/literacy/
- https://norskdidaktisk.wordpress.com/literacy/

Fra en rask titt på posten (med forbehold osv..) ville jeg tenkt at Undervisningsmetoder, Naturfagdidaktikk, e.l. holdt.

**Comment by Hypsibius** [comment]
Mtja, det var jo det eg tenkte å bruke, men synest boka går litt lengre inn i sjølve forskningsforståelsen. Dette med å ha ein slags ide om den vitskaplege metode, kva det vil seie at ein har vitskapleg belegg for noko.  

Eg veit dette er eit tilbakevendande tema for forskerar eg følgjer på SoMe kvar gong PEW viser kor dårleg det står til med Science Literacy og forståelsen for utviklingsTEORIEN etc (det er jo berre ein teori, sant? Ikkje fakta). Oppfattar det som eit fokus også her. 

Hege

**Comment by danmichaelo** [comment]
Forskningsforståelse BF Forskningslitterasitet BF Vitenskapsforståelse BF Vitenskapslitterasitet ?

**Comment by Hypsibius** [comment]
Vi kan kanskje skippe litterasiteten? Ingen av litterasitetstermane ga treff i google ;-)

Forståelsen, derimot. Godt det!

**Comment by BioHeidi** [comment]
Nynorsk?

**Comment by Hypsibius** [comment]
-Forståing. Kvir meg framleis på -literasiteten

**Comment by BioHeidi** [comment]
Tok med nynorsk men ikke literasitet.
