### ISSUE TITLE
Nytermer: Manteldiapirer og Varmefelt

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#585]
Manteldiapirer
EN Mantel plume
DE Varmt, plastisk mantelmateriale som stiger opp gjennom omkringliggende mantel på grunn av tetthetsforskjellen. (Norsk Geologisk Ordbok)
SO Varmefelt

Varmefelt
BF Varmepunkter
EN Hotspot
DE Vulkansk området med bredde 100-200 km hvor det har vær vulkansk aktivitet gjennom minst et titalls millioner år. Vulkanismen skyldes antakelig at vulkanfeltet ligger oven en manteldiapir [...]. (Norsk Geologisk Ordbok)
SO Manteldiapirer

**Comment by danmichaelo** [comment]
Supert med gode definisjoner! Lagt til begge
