### ISSUE TITLE
Foreslår Elektrofiske

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#587]
jf bruk: Rådgivende biologer

http://www.radgivende-biologer.no/default.aspx?pageId=78

Aktuelt dokument: 

https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71473126270002201

**Comment by BioHeidi** [comment]
Opprettet!
