### ISSUE TITLE
Graphite furnace atomic absorption spectroscopy

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#588]
Den har fått en veldig fin nynorsk oversettelse. Men ikke bokmål. Hva tenker dere?

Vi har emneordet Grafittovner.

**Comment by danmichaelo** [comment]
Fristende å erstatte med `Atomabsorpsjonsspektroskopi` + `Grafittovner`.. selv om det selvfølgelig ikke er helt presist å si at disse dokumentene "handler om grafittovner".

`Grafittovn atomabsorpsjonsspektroskopi` er jo en mulighet, men det roper særskrivingsfeil. Og `Atomabsorpsjonsspektroskopi i grafittovn` blir vel for klønete?

**Comment by danmichaelo** [comment]
"Juksa" litt og brukte GF-AAS som foretrukket term, med `BF Grafittovn atomabsorpsjonsspektroskopi BF Atomabsorpsjonsspektroskopi i grafittovn`.
