### ISSUE TITLE
Mantelen = Jordas mantel?

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#589]
Alle dokumenter som bruker `Mantelen` er tilknyttet jorden. Dessuten bruker vi `Jordas kjerne` og `Jordskorpen` som termer. Jeg synes det hadde vært mer ryddig at vi endrer `Mantelen` til `Jordas mantel` og oppretter `Mantel` som ny term i tilfelle det skulle være behov for termen for andre planeter.

**Comment by danmichaelo** [comment]
Tror ihvertfall vi skal slette `Mantelen : Tyskland` :D 

Enig i resten også. Vi kan jo vente med å opprette "Mantel" til behovet dukker opp.

**Comment by jw-geo** [comment]
Det er jeg enig i ;)

**Comment by danmichaelo** [comment]
Da endret jeg til

    Jordas mantel
    BF Mantelen

og slettet strengene
