### ISSUE TITLE
Gitter i mange farger

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#590]
(Nei, ikke glitter)

Noen som føler seg kallet til å mene noe om disse? Kan noe sammenslås?
`Latticer`, `Gittere`, `Gitterdynamikk`, `Gitterfeltteori`, `Gitterteori`, `Krystallgitter`, `Ikke-lineære krystallgitter`, ser ut til å ha mye av de samme typer bøker i trefflistene.

Mens disse ser ut til å være mer avgrenset:
`Gittersystemer`
`Gitterdatabaser`
`Multigridmetoder`
`Zirconiumgitter`

**Comment by danmichaelo** [comment]
:christmas_tree:  Jeg føler meg kallet til å føle noe om dette, nei, mene noe mener jeg

- `Gittere`, `Latticer` og `Lattice theory`: slåes sammen, med note om avgrensning til matematikk (https://sv.wikipedia.org/wiki/Gitter_(ordning))?

- `Krystallgitter` (faststoffysikk): beholdes, men skulle kanskje vært "gitre?" Og `BF Gitterstruktur BF Krystallinsk struktur` (kanskje til og med sistnevnte skulle vært foretrukket term, ja, jeg heller mot det)

-  `Ikke lineære krystallgitter`: tja.. jeg synes det virker som denne termen er litt for sterkt knyttet mot én bestemt bok. Stemmer for slett. "Solitonteori" (eller "Solitoner") er antakelig et bedre emneord på denne boka (som den allerede hadde).

**Comment by BioHeidi** [comment]
Har ordnet som best jeg kunne, greit om "noen" ser over.

**Comment by danmichaelo** [comment]
Sikker på at det blir riktig med "Grid theory" på engelsk? Så ellers fint ut!

**Comment by BioHeidi** [comment]
Husker ikke helt hvor Grid theory kom fra, kan den ha ligget på en av de termene jeg slo sammen? Kan slette den for å ikke skape forvirring.

**Comment by danmichaelo** [comment]
Det kan være. Jeg fjerna den, jeg.
