### ISSUE TITLE
Jordskorpen

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#593]
Jordskorpen og Kontinentalskorpe finnes som term, jeg foreslå Havbunnsskorpe som ny term (https://no.wikipedia.org/wiki/Havbunnsskorpe). Det kunne se sånt ut:

Jordskorpen
EN Earth's crust
SO Kontinentalskorpe
SO Havbunnsskorpe

Kontinentalskorpe
EN Continental crust
SO Jordskorpen

Havbunnsskorpe
EN Oceanic crust
SO Jordskorpen

**Comment by danmichaelo** [comment]
Ser bra ut, lagt inn!

**Comment by jw-geo** [comment]
Takk skal du ha. Jeg så nettopp at vi har faktisk:

Havbunnsgeologi
BF Havbunnskorpe

Jeg synes uansett at Havbunnskorpe burde være en egen term. Så kanskje du kan fjerne BF?

**Comment by BioHeidi** [comment]
Gjort! :)
