### ISSUE TITLE
Kontinentalmarginer

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#595]
Vi har:
- Kontinentalmarginer
- Kontintentale marginer
- Marginer
- Passive Marginer

Jeg foreslå å slå sammen de første tre, altså:

Kontinentalmarginer
DE Havbunnen som ligger mellom landområdene og dyphavet (wikipedia)
EN Continental margins
BF Kontinentale marginer
BF Marginer
BF Kontinentrand
BF Kontinentmargin
SO Passive marginer

Passive marginer
EN Passive margins
EN Passive continental margins
SO Kontinentalmarginer

**Comment by danmichaelo** [comment]
Gjort! (fiksa litt på flertallsformene)
