### ISSUE TITLE
Subduksjonssoner

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#596]
Vi har `Subduksjon` som term, men jeg synes det ville være bedre å bruke `Subduksjonssoner`.

Da kunne vi har:

Subduksjonssoner
EN Subduction zones
EN Active continental margins
EN Convergent plate boundaries
BF Subduksjon
BF Aktive kontinentalmarginer
BF Konvergente plategrenser
BF Kollisjonsgrenser

**Comment by danmichaelo** [comment]
Bare for å være helt sikker: Siden du har tatt med `BF Subduksjon` så mener du at vi ikke trenger `Subduksjonssoner` og `Subduksjon` som to forskjellige emneord, men at det holder med `Subduksjonssoner`, right?

**Comment by jw-geo** [comment]
Ja, jeg synes det.

**Comment by BioHeidi** [comment]
Skal jeg vente med å gjøre noe her til noen har ryddet i katalogen?

**Comment by danmichaelo** [comment]
Tror ikke det trengs katalogrydding her
