### ISSUE TITLE
Nyterm: Kontraksjonstektonikk

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#598]
Vi har Ekstensjonstektonikk men mangler Kontraksjonstektonikk på motsatt side.

Kontraksjonstektonikk
DE Tektoniske prosesser som fører til at jordskorpen blir fortykket
EN Contractional tectonics
EN Thrust tectonics
EN Collision tectonics
SO Fjellkjededannelse

https://en.wikipedia.org/wiki/Thrust_tectonics

Ekstensjonstektonikk
DE Tektoniske prosesser som fører til at jordskorpen blir fortynnet.
EN Extensional tectonics

**Comment by danmichaelo** [comment]
Lagt inn, takk!
