### ISSUE TITLE
Hydrozoa og småmaneter

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#599]
Foreslår å slå saman til 

småmeneter LA Hydrozoa

**Comment by BioHeidi** [comment]
Gjort!

**Comment by Hypsibius** [comment]
Forhåpentleg ikkje MED min skrivefeil ;-)

**Comment by BioHeidi** [comment]
Haha nei den så jeg! (Men sjekk Svamper...)

**Comment by Hypsibius** [comment]
Firkant....

**Comment by Hypsibius** [comment]
Kan Wolfram Alhpa, kan vi....
