### ISSUE TITLE
Formterm for flash cards, faktakort, eller hva?

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#600]
Jeg trenger å få definert at et dokument er "flash cards", har vi en god emneterm som kan brukes? Eller lage en ny? Læremateriell? Forslag? Jeg er litt blank i dag. Vet ikke om det finnes en god norsk oversettelse av flash cards heller.

[Til denne posten](https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo_library/libweb/action/display.do?tabs=detailsTab&ct=display&fn=search&doc=BIBSYS_ILS71539793370002201&indx=1&recIds=BIBSYS_ILS71539793370002201&recIdxs=0&elementId=0&renderMode=poppedOut&displayMode=full&frbrVersion=&frbg=&&dscnt=0&scp.scps=scope%3A%28SC_OPEN_ACCESS%29%2Cscope%3A%28DUO%29%2Cscope%3A%28%22UBO%22%29%2Cprimo_central_multiple_fe&tb=t&mode=Basic&vid=UBO&srt=rank&tab=default_tab&dum=true&vl(freeText0)=Flash%20Cards%3A%20Biochemistry%20&dstmp=1480941902483)

**Comment by Violabibaluba** [comment]
Vi har opprettet en fantastisk ny term. Ikke slett den da :-) 
Ny term: Memokort
@grosyn vil du sjekke nynorsken i Roald?
