### ISSUE TITLE
Nyterm: Vulkanske øybuer

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#601]
Vulkanske øybuer
BF Vulkanbuer
EN Island arcs
EN Volcanic arcs
SO Subduksjonssoner

https://no.wikipedia.org/wiki/Vulkansk_%C3%B8ybue

**Comment by danmichaelo** [comment]
Lagt til. Men er det en grunn til at "Island arcs" er med på engelsk, men ikke "Øybuer" på norsk? Og finnes det øybuer som ikke er av vulkansk opphav, eller kunne "Øybuer" til og med vært foretrukket term, med `BF Vulkanske øybuer BF Vulkanbuer`? Hvis det er en term som er mer brukt i fagmiljøene bør vi selvfølgelig bruke den som foretrukket.

**Comment by jw-geo** [comment]
Takk for viktig tilbalemelding. Jeg var litt rask og unøyaktig her. Nå fant jeg ut at man skiller generellt mellom Øybuer (Island arcs) og Vulkanbuer (Volcanic arcs). De fleste Øybuer er dannet gjennom vulkansk aktivitet (Vulkanske øybuer/ havbuer). Vulkanbuer (Volcanic arcs) kan enten være Havbuer eller Kontinentalbuer. Fra en geologisk perspektiv tror jeg ikke at vi trenger Øybuer som egen term. Jeg foreslår at vi bruker Vulkanbuer som foretrukket term.

Vulkanbuer
BF Vulkanske øybuer
BF Øybuer
BF Kontinentalbuer
BF Havbuer
EN Volcanic arcs
EN Island arcs
EN Continental arcs
EN Oceanic arcs
SO Subduksjonssoner

**Comment by BioHeidi** [comment]
Og så er det vel viktig å se hvilke dokumenter vi har om emnet, vi trenger ikke å opprette begge om vi ikke har så mange bøker på det. Det er sikkert ok å slå sammen.

**Comment by danmichaelo** [comment]
Supert! Jeg endra den til det siste forslaget ditt (altså med `Vulkanbuer` som foretrukket term) og la til nynorsk
