### ISSUE TITLE
Definisjoner: Kontinentaldrift og Platetektonikk

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#602]
Jeg synes vi burde har SO for begge termene:

Kontinentaldrift
DE Teori om forskyvning av landområdene på Jorden i forhold til hverandre og til polene. (Norsk geologisk ordbok)
EN Continental drift
SO Platetektonikk

Platetektonikk
DE Teori der Jordens ytre, stive steinskall (litosfæren) er delt opp i jordplater som beveger seg i forhold til hverandre. (Norsk geologisk ordbok)
EN Plate tectonics
SO Kontinentaldrift

**Comment by BioHeidi** [comment]
Gjort!
