### ISSUE TITLE
Nyterm: Kontinenttilvekst

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#607]
Kontinenttilvekst
DE Tilvekst til kontinentskorpen ved magmatiske og tektoniske prosseser.
BF Tilvekstkile
EN Continental accretion
EN Accretionary wedge
EN Accretionary prism
SO Subduksjonssoner
SO Kontraksjonstektonikk

https://en.wikipedia.org/wiki/Accretion_%28geology%29

**Comment by danmichaelo** [comment]
Lagt til:

```
Kontinenttilvekst
DE Tilvekst til kontinentskorpen ved magmatiske og tektoniske prosseser.
BF Tilvekstkiler
NN Kontinenttilvekst
NN Tilvekstkilar
EN Continental accretion
EN Accretionary wedges
EN Accretionary prisms
SO Subduksjonssoner
SO Kontraksjonstektonikk
```
