### ISSUE TITLE
Astroseismologi og Asteroseismologi

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#609]
[Astroseismologi](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007360)
[Asteroseismologi](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000920)
Jeg tror dette er det samme, men er ikke sikker.

**Comment by danmichaelo** [comment]
Ai, tipper den første er en skrivefeil. Enig, @superLine ?

**Comment by danmichaelo** [comment]
Hun var enig. Sletta Astroseismologi.
