### ISSUE TITLE
Atferdsbiologi og etologi

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#610]
[Atferdsbiologi](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Atferdsbiologi) og [Etologi](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013953) er såvidt jeg kan forstå det samme? Eller er Atferdsbiologi en del av Etologi?

@BioHeidi kan du gjøre meg klokere?

**Comment by BioHeidi** [comment]
Det er det samme. Jeg slår de sammen, atferdsbiologi som foretrukken.
