### ISSUE TITLE
Ryddeliste/Sletteforslag 22.12.16

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#615]
[Augerspektra](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c013012)
[Autocode](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c031369)
[Automatisk derivering](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008239)
[Automatisk klassifikasjon](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c001455)
[Automatisk kontroll](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009881) Basert på litt.belegget ser det litt for tvetydig/generelt ut til at det kan brukes konsistent?
[Automatisk regulering](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004579) Evt. slås sammen med Automatisk kontroll?
[Automatisk ruting](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006420)
[Automatiske målestasjoner](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007353)
[Autorisering](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c012710) Trenger evt. definisjon eller tydeliggjøring
[Autotrofe bakterier](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008769)
[Auxiner](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003971)
[Avbildninger](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005010) Har ganske mange dok. men det virker så tvetydig? Tror også det er brukt som både emne og form?
[Avblading](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000606)
[Avisingsvæske](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004408)
[Avlytting](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011904) Dekkes av [Overvåking](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c012764)
[Avskjæring](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003097) Trenger evt. definisjon?
[Avskyting](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c007887) Ingen dok.
[Avsmalning](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000654)

**Comment by BioHeidi** [comment]
Mange av disse har dokumenter, selv om det er få dokumenter er det vel fortsatt sånn at vi ønsker de spesifikke emneordene. F.eks. autotrofe bakterier, auxiner, avisingsvæske.
 Mens f.eks. avblading kan slettes, det er et spesifikt emneord brukt på et generelt dokument.

**Comment by BioHeidi** [comment]
Neida, bare kom med forslag! Måtte bare si det sånn at alle er obs på at det kan være aktuelt å beholde emneord med bare ett eller få dokumenter på. Jeg mener ikke at du nødvendigvis skal ta den avgjørelsen.

**Comment by BioHeidi** [comment]
Augerspektra - Slettet, lagt til som BF på Augerelektronspektroskopi.
Autocode - beholdes, brukes for å finne bøker om tidlige programmerbare datamaskiner og tidlige programmeringsspråk. Kunne sikkert vært brukt på flere dok.
Automatisk derivering - beholdes.
Automatisk kontroll - slås sammen med Automatisk regulering
Automatisk regulering - slås sammen med Automatisk kontroll. @danmichaelo kan evt finne bedre term eller legge på definisjon?
Automatisk ruting - @knuthe ? Kan det slås sammen med noe?
Automatiske målestasjoner - slettes eller slås sammen med Måleteknikk?

**Comment by danmichaelo** [comment]
> *Automatisk regulering* - slås sammen med *Automatisk kontroll*. @danmichaelo kan evt finne bedre term eller legge på definisjon?

Slått sammen som *Automatisk regulering*, men klarer ikke komme opp med noe annet enn god-dag-mann-økseskaft-definisjonen "reguleringssystemer som ikke er manuelle", så jeg dropper det. 

Mistenker at mange av bøkene like godt kunne hatt Reguleringsteknikk som emneord som Automatisk regulering, men tar ikke sjansen på å slå de sammen når jeg ikke har bøkene foran meg og det er et fagfelt utenfor komfortsonen min.

Titta på TEKORD: De har både Reguleringsteori (1021 dok), Automatisk regulering (615) og Reguleringsteknikk (34). (Men ikke Manuell regulering :)) Jaja, jeg trekker meg forsiktig ut av automatiseringsfeltet for denne gang.

**Comment by danmichaelo** [comment]
@knuthe sier på epost at han vil beholde `Avskjæring`, `Autorisering` og `Automatisk ruting`. Og at

> Avskjæring er en algoritmeteknikk. Man stopper en prosess fordi "man" skjønner at "man" er inne på et spor som ikke fører fram, går tilbake og prøver et annet spor.
