### ISSUE TITLE
Avtrykk som fornorsking av hash

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#616]
Gisle Hannemyr har en super oversettelse av [hashing](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005666) i et [blogginnlegg](https://titan.uio.no/node/1978):

> En avtrykksalgoritme (engelsk: hash algorithm) er en algoritme som tar inn en tekst av vilkårlig lengde og transformerer dette til et resultat av fast lengde.  Samme tekst vil alltid resultere i samme avtrykk.

Hva med

```
Avtrykksalgoritmer
BF Avtrykksfunksjoner
BF Sjekksumalgoritmer
BF Sjekksumfunksjoner
BF Hashalgoritmer
BF Hashfunksjoner
DE En avtrykksalgoritme (engelsk: hash algorithm) er en algoritme som tar inn en tekst av vilkårlig lengde og transformerer dette til et resultat av fast lengde.  Samme tekst vil alltid resultere i samme avtrykk.
NN ...funksjonar
NN ...algoritmar
EN Hash algorithms
EN Hash functions
```

@knuthe ?

**Comment by knuthe** [comment]
God oversettelse! Og samsvarer godt med andre identifikasjonsavtrykk (e.g. fingeravtrykk)

**Comment by danmichaelo** [comment]
Lagt inn!
