### ISSUE TITLE
Litteratur (emne)

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#619]
Kan vi slette den?

**Comment by danmichaelo** [comment]
Ja! (Får holde med [kanonene](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006900) :D)

Det er lite antall skjønnlitterære bøker som får null realfagstermer hvis vi sletter. Vi kan jo legge på 655 skjønnlitteratur e.l. og evt. et emneord eller to på disse først.
