### ISSUE TITLE
Grunnområder, grunt vann 

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#62]
Ja, begge disse er i bruk en gang hver. Har noen et forslag til hva det bør hete, og stemmer det at engelsk kan være Shallow water? 

Wikipedia samler "waves and shallow water".

**Comment by Hypsibius** [comment]
I naturforvaltning og blant bentosbiologiar snakkast det ofte om 'gruntvannsområder', så det begrepet må også med, jf bruken her: http://faktaark.naturbase.no/Vern?id=VV00000049

**Comment by kristinran** [comment]
Det er absolutt spesielle geologiske prosesser (avsetning) som skjer i gruntvannsområder i motsetning til for eksempet i dyphavet, så det må være med.



KristinR



________________________________

**Comment by bibliomari** [comment]
Jeg har slått sammen til: Gruntvannsområder BF Grunt vann EN Shallow water. Det er fristende å gi matematikken noe eget, eller hva tror @TorgunnKarolineMoe ? Kan denne boka f.eks. ha Gruntvannsområder og Bølgeteori eller trenger den noe annet? 

http://ask.bibsys.no/ask/action/show?pid=950042102&kid=biblio

**Comment by TorgunnKarolineMoe** [comment]
Ser greit ut, synes jeg.


Hilsen Karoline

________________________________
