### ISSUE TITLE
Forslag til sammenslåing 02.01.17

### ISSUE THREAD

**Issue by HegeNenseth** [realfagstermer/realfagstermer#620]
Hei!

Kanskje disse kan slås sammen?
[Dispersjon](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003115&broad=false)
[Dispersjoner](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009304&broad=false)

Og disse:
[Dos](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002797&broad=false)
[Disk operating system](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002542&broad=false)

**Comment by danmichaelo** [comment]
> Kanskje disse kan slås sammen?
> [Dispersjon](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003115&broad=false)
> [Dispersjoner](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009304&broad=false)

I utg. pkt. ville jeg tenkt at "dispersjon" viste til optisk dispersjon ([slik](https://en.wikipedia.org/wiki/Dispersion_(optics))), mens "dispersjoner" viste til melk og sånn ([dispersjon i kjemi](https://en.wikipedia.org/wiki/Dispersion_(chemistry))). Kan legge på definisjoner så det blir lettere å skille dem.

> Og disse:
> [Dos](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002797&broad=false)
> [Disk operating system](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002542&broad=false)

Ja! Ser også ut som alle bøkene enten handler om MS-DOS eller PC-DOS, så tror egentlig vi kan slette den.

**Comment by mittinatten** [comment]
> Ja! Ser også ut som alle bøkene enten handler om MS-DOS eller PC-DOS, så tror egentlig vi kan slette dem.

Fordi vi vil late som at den pinlige episoden aldri har skjedd?

**Comment by danmichaelo** [comment]
Tror jeg uttrykte meg litt uklart. Mente bare å slette "DOS" og "Disk operating system", ikke "MS-DOS" og "PC-DOS" altså :D 

Problemet med termen DOS er at definisjonen på *et DOS* egentlig dekker alle moderne OS (alt som kan jobbe med en disk), men samtidig i praksis ikke brukes om dem, men bare om MS-DOS (og kanskje noen andre varianter blant dem som er eldre enn meg)

**Comment by danmichaelo** [comment]
La på definisjoner på `Dispersjon` og `Dispersjoner`, og sletta `Dos`.
