### ISSUE TITLE
Starburst

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#622]
Oppdaget at `Stjernedanning` er foretrukket term på nynorsk for både [Starburst](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003247) og [Stjernedannelse](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c001718). Tror vi må ta den vekk fra `Starburst`, men må vi leve med den engelske termen eller har vi noen norsk term? `Stjernefødestuer`? :D @superLine

**Comment by superLine** [comment]
Argh wikipedia sier starburstgalakse - jeg tipser @astromaria - stjernedannende galakser er jo nærliggende???

**Comment by superLine** [comment]
astromaria sier: Den må jeg nesten diskutere med referansegruppen. Alle galakser danner jo stjerner i en eller annen grad, men starburst-galakser danner veldig mange over veldig kort tid, så navnet skal jo helt reflektere det (derfor "burst") … 🙂

hun kan gjerne være med i diskusjonene sier hun!

**Comment by superLine** [comment]
Maria heter @mariahammerstrom på git - kan vi legge henne til? Mappe fagtermwiki ???

**Comment by danmichaelo** [comment]
Supert, har invitert henne! @mariahammerstrom , er det greit for deg om vi pinger deg innimellom når vi diskuterer astrotermer? Du må selvfølgelig ikke svare selv om vi pinger deg!

**Comment by mariahammerstrom** [comment]
Ping i vei :)

**Comment by mariahammerstrom** [comment]
Oppdaget at jeg egentlig kan svare litt mer på denne :) 

"Starburst" brukes ikke som et ord alene, så vidt jeg vet. Som Line påpeker, refererer det til "starburst galaxy", som galaksefolk ofte er slapphendt med og bare refererer til som "starbursts" (a.k.a. "starburst galaxies"). "Starburst" er ikke et ord som brukes om stjernedannelse generelt, så dere bør gjøre som Dan Michael foreslår og ta bort "starburst" fra "stjernedannelse".

**Comment by danmichaelo** [comment]
Da tok jeg vekk "stjernedannelse" og la til "starburstgalakser" som foretrukket term (inntil vi evt. finner på noe bedre) + engelsk.
