### ISSUE TITLE
Petrogenese og Bergartsdannelse

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#623]
[Bergartsdannelse](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Bergartsdannelse)
[Petrogenese](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004673)

Dette ser for meg ut som (nesten) det samme?

**Comment by kaalrust** [comment]
Det samme gjelder [Bergartslære](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Bergartsl%C3%A6re) og [Petrologi](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008955)

**Comment by jw-geo** [comment]
Jeg er enig. Kanskje vi kan bruke de norske termene som hovedterm?

**Comment by edinab** [comment]
Bergartsdannelse og Petrogenese kan slås sammen og Bergartsdannelse er foretrukken term.
Bergartslære og Petrologi skal ikke slås sammen. Bergartlære kan brukes for Petrografi også, men Petrologi og Petrografi er forskjellige. 
Foreslår at Petrologi og Petrografi beholdes separate og Bergartslære bare brukes i tilfeller der både Petrografi og Petrologi ville blitt brukt.
Legg på 'Se også'/SO mellom Bergartslære og Petrografi og mellom Bergartslære og Petrologi. Legg også på invers relasjon, men ikke mellom Petrologi og Petrografi.
Jeg rydder på Bergartslære.

**Comment by danmichaelo** [comment]
Bergartsdannelse og Petrogenese slått sammen.

Beholdt de andre og la på SO-er som foreslått.
