### ISSUE TITLE
Drammensgranitten: sted eller stein?

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#624]
Emneordet [Drammensgranitten](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Drammensgranitten) er bare brukt på en masteroppgave, og sånn sett lurer jeg på om det kanskje kunne slettes, men jeg lurer også på (hvis det ikke skal slettes) om det gjelder steintypen [drammensgranitt (SNL)](https://snl.no/drammensgranitt) eller om det er snakk om en stor klump med granitt i Drammen?

**Comment by danmichaelo** [comment]
Det er nok bergarten :) Virker som et greit emneord på det éne dokumentet, men endrer til `Drammensgranitt` (formelt sett er det sikkert liten D også, men vi bruker jo alltid stor forbokstav av historiske årsaker..)

**Comment by danmichaelo** [comment]
La til en definisjon også
