### ISSUE TITLE
Død og Døden (og Dødelighet)

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#627]
[Døden](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009406) og [Død](https://app.uio.no/ub/emnesok/realfagstermer/search?term=D%C3%B8d) kan vel sies å være noe overlappende? Det samme gjelder forsåvidt også [Dødelighet](https://app.uio.no/ub/emnesok/realfagstermer/search?term=D%C3%B8delighet), men det er jo noe litt annet.

**Comment by danmichaelo** [comment]
Slo sammen som `Død BF Døden`, lot `Dødelighet` stå :skull:
