### ISSUE TITLE
C-vitaminer og Askorbinsyre

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#628]
[C-vitaminer](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000775)
[Askorbinsyre](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010147)

**Comment by danmichaelo** [comment]
Sannelig hadde vi ikke `Vitamin-c` også :S 

Slått sammen, [Vitamin C](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000775) som foretrukken term.
