### ISSUE TITLE
Elektrokjemisk analyse

### ISSUE THREAD

**Issue by HegeNenseth** [realfagstermer/realfagstermer#629]
Foreslår å slå [Elektro-kjemisk analyse](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006147) sammen med [Elektrokjemisk analyse](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006663)

I tillegg lurer jeg på om kanskje [Elektroanalyse](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004015) og [Elektroanalystisk kjemi](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011920) egentlig innebærer det samme som Elektrokjemisk analyse? Jeg er iallefall lettere forvirra.

**Comment by danmichaelo** [comment]
Takk :+1: Slo sammen alle tre, pluss `Elektroanalytisk kjemi` og `Elektrokjemiske metoder`. Mener alle er dekket av http://purl.obolibrary.org/obo/CHMO_0000003
