### ISSUE TITLE
Aktive galactic nuclei/galaksekjerner

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#63]
Termen active galactic nuclei har vi bare på engelsk, jeg vil selvsagt ha den på norsk: Aktive galaksekjerner. Da er spørsmålet @superLine: Kan vi slå den sammen med "galaksekjerner" som vi allerede har? Den er bare brukt to ganger, og mitt lekmannsøye tror det like gjerne kunne stått "aktive" foran. 

Og så ser jeg av wikipedia at jeg får lyst til å lage SE OGSÅ Kvasarer, Seyfertgalakser, Radiogalakser, Lacertae-objekter. Hva sier du til det?

**Comment by superLine** [comment]
vi bør iallfal si "aktive galaksekjerner". Ser i engelsk wikipedia at de bruker "active galactic nuclei", men så skriver de "core" om det som vi kaller "kjerne", men som ikke omtales i sammenheng med aktiv...  (men nå snegler bibsys og primo... får søke mer i morgen)

**Comment by bibliomari** [comment]
Done
