### ISSUE TITLE
Logikkprogrammering og logisk programmering

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#632]
[Logisk programmering](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006597)
[Logikkprogrammering](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009516)

Tidligere nevnt og glemt i en e-post fra 17. august: til bl.a. @danmichaelo og @knuthe 

Er dette to forskjellige ting, og hva er i så fall forskjellen?

**Comment by knuthe** [comment]
Tror nok at "Logisk programmering" er nok en tjue år gammel misforståelse og kan byttes ut med "Logikkprogrammering"

**Comment by danmichaelo** [comment]
Endra `Induktiv logisk programmering` til `Induktiv logikkprogrammering` samtidig
