### ISSUE TITLE
Elektronisk datautveksling

### ISSUE THREAD

**Issue by HegeNenseth** [realfagstermer/realfagstermer#634]
Emnet [Elektronisk datutveksling](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Elektronisk%20datautveksling) ligger også som nynorskterm på emnet [Electronic data interchange ](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Electronic%20data%20interchange)

**Comment by danmichaelo** [comment]
@knuthe , har du hatt noen tanker med dette skillet? For meg ser det umiddelbart ut som de slås sammen, men kan være noen nyanser her..

**Comment by knuthe** [comment]
Det er EDI det går på og jeg hadde vel en ide en gang om at det på bokmål skulle ekspanderes på riktig språk. Kan nok slås sammen.

**Comment by danmichaelo** [comment]
Lyst å fikse? Eller har du trukket deg helt tilbake fra Sonja-arbeid?

**Comment by knuthe** [comment]
Jeg forsøker jo det så godt jeg kan, men tar denne.

**Comment by knuthe** [comment]
Så får vi se hvordan det gikk.
