### ISSUE TITLE
Samfunnsmessige påvirkninger

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#638]
Jeg laget nettopp en streng `Klimaendringer : Samfunnsmessige påvirkninger`. 
Fra før finnes `Samfunnsmessige påvirkninger` som frittstående emneord, samt strengene 
`Internett : Samfunnsmessige påvirkninger` og
`Samfunnsmessige påvirkninger : Historie`.

Jeg vet ikke helt om jeg liker emneordet, forslag til endring eller sammenslåing? Eller er det greit sånn?

**Comment by iloveyellow** [comment]
Jeg syns det er bra!

**Comment by mittinatten** [comment]
Kanskje sammenslåing med Samfunnsendringer? #419 

Vil huske der er flere av den typen: termer som bare gir mening i strenger. Finner ingen eksempler nå på Github, men mener noe lignende har vært oppe til diskusjon tidligere.

**Comment by danmichaelo** [comment]
Mm, [Modeller](http://data.ub.uio.no/skosmos/realfagstermer/nn/page/c000426?clang=nb) og [Medisinske effekter](http://data.ub.uio.no/skosmos/realfagstermer/nn/page/c009757?clang=nb) har noter om at de ikke skal brukes alene (Hvis vi får flere sånne kunne vi jo kodet det på en mer standardisert måte).

**Comment by BioHeidi** [comment]
Slo sammen med Sosial endring som er BF Samfunnsendringer, og la på intern note om streng.
