### ISSUE TITLE
Effekt/effekter

### ISSUE THREAD

**Issue by HegeNenseth** [realfagstermer/realfagstermer#639]
Kan [Effekter](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c006797) og [Effekt](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c001634) slås sammen?

Foreslår å slette [Digitale byer](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010114) og [Elektroreseptorer](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Elektroreseptorer)

**Comment by Hypsibius** [comment]
Har vi så lite bruskfisklitteratur, altså? Men får evt gjeninnføre v behov :-)

**Comment by BioHeidi** [comment]
Hehe, vi har vel litt på dem, men visstnok ikke nok sansegreier. Det vil si vi kunne vel bladd gjennom Sensorer og Reseptorer og sett om vi fant noe. En gang.

**Comment by danmichaelo** [comment]
Slettet `Effekt` og `Effekter` -- det gjorde godt! Ryddet litt i katalogen først

Sletta Elektroreseptorer også.
