### ISSUE TITLE
Bl lac-objekter, lacertae-objekter, lacertae

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#64]
@superLine @mittinatten kan disse slås sammen til ett?

**Comment by BioHeidi** [comment]
Dere kan få bruke det på stjernebildet hvis dere ikke bruker Lacerta, som er latinsk slektsnavn på masse vanlige firfisler, bl.a. markfirfisle som finnes nord til Sverige (og kanskje i Norge), og som vi har som emneord. Kanskje jeg bare skal skynde meg å legge til latin på den for å forhindre dere? Firfislen, Øgla og Firfisla kan dere få, siden de er i bestemt form entall.

**Comment by mittinatten** [comment]
Godt poeng, tenkte ikke en gang på at det kunne bli konflikt med biologien her. Men litt usikker om stjernebilder bør være i registeret uansett?

**Comment by superLine** [comment]
Men har biologien hevd på latinen ? ;-) - og da kommer vi vel til en typisk valgsituasjon: hvordan vise fra latinsk term til to fagtermer?

**Comment by Hypsibius** [comment]
Det same gjeld termen 'congener', som nemnt i e-post

**Comment by knuthe** [comment]
Latinen blir lagt inn som latin på begge fagtermene og søker du på latinen, får du to treff. Så blir det opp til biologen (eller astronomen) å velge "sin" fagterm. Blir det ikke slik da? (Tillater Sonja det, mon tro?)

**Comment by Hypsibius** [comment]
Om vi tenker som DDC eller Wikipedia Disambiguation, så spesifiserer ein jo disiplin/subdisiplin for termen. Er ikkje det mogeleg her? Pisces (Biologi) blir då noko anna enn Pisces (Astronomi)....

http://en.wikipedia.org/wiki/Congener

**Comment by knuthe** [comment]
Mulig jeg misforsto. Vi har allerede "kopper (grunnstoff)" og "kopper (sykdom)", så det er ikke noe i veien for å gjøre som Hege foreslår.

**Comment by BioHeidi** [comment]
Jeg mener det ikke er mulig å ha samme latinske betegnelse på to termer, det tillater ikke Strenge Sonja. Men med spesifikasjon i parentes blir det sikkert greit.

**Comment by Hypsibius** [comment]
Synest også det er viktig å tenke på korleis dette ser ut i søk for sluttbrukaren. Ved å bruke parentes, kan dei umiddelbart sjå kva som er forskjellen på dei to termane. Viss ikkje, blir dette først synleg ved søk. Det er berre vi som brukar Roald som kan gå inn og sjå alle BF-termar, engelsk og nynorsk etc....

**Comment by bibliomari** [comment]
Bruker simons forslag 2 og slår sammen de tre.
