### ISSUE TITLE
Ytre geologiske prosesser

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#642]
Ytre geologiske prosesser
DE Fellesbetegnelse på prosesser som har sitt opphav på eller nær på jordoverflaten (NGO).
BF Eksogene prosesser
BF Overflateprosesser
BF Eksogen geologi
EN Surface processes
EN Exogenetic processes
EN Exogenous processes

**Comment by danmichaelo** [comment]
Supert  :+1:  Har fiksa
