### ISSUE TITLE
Restavsetninger

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#644]
Restavsetninger
DE Avsetning dannet på stedet ved forvitring (NGO).
BF Residiualavleiringer
EN Residual deposits

**Comment by jw-geo** [comment]
Fant at vi har termen Forvitringsjord. Så jeg foreslå:

Forvitringsjord
DE Avsettning dannet ved forvitring av den faste berggrunnen på stedet, uten at den har vært transportert.
BF Residiualavleiringer
BF Restavsetninger
BF Lateritt
BF Bauxitt
EN Residual deposits
EN Residual soil

**Comment by jw-geo** [comment]
Fant at vi har termen Forvitringsjord. Så jeg foreslå heller:

Forvitringsjord
DE Avsetning dannet ved forvitring av den faste berggrunnen på stedet, uten at den har vært transportert.
BF Restavsetninger
BF Residiualavleiringer
BF Lateritt
BF Bauxitt
EN Residual deposits
EN Residual soil

**Comment by danmichaelo** [comment]
Gjort! Litt usikker på om vi burde beholdt Bauxitt som eget emneord til tross for lite litteraturbelegg (ett dok.), dog. Si fra hvis du ombestemmer deg :)
