### ISSUE TITLE
Galaksesystemer og Galaksehoper

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#646]
Slås sammen?

**Comment by mariahammerstrom** [comment]
Jeg vil si nei, for dette er ikke snakk om helt det samme. En galaksehop er en samling galakser som er gravitasjonelt bundet til hverandre, mens et galaksesystem er når man for eksempel ser på to galakser som interagerer med hverandre (som kan skje innad i en galaksehop).

**Comment by BioHeidi** [comment]
Hei Maria! :)

**Comment by mariahammerstrom** [comment]
Hei Heidi! Nå er jeg også litt med her :)

**Comment by BioHeidi** [comment]
Er Galactic clusters en oversettelse av galaksehoper? Isåfall trengs heller ikke katalogrydding.

**Comment by mariahammerstrom** [comment]
Ja, det er det! :)

**Comment by superLine** [comment]
Fantastisk med @mariahammerstrom med på laget her - for det er galakser i masteroppgaven din sant?
