### ISSUE TITLE
Gamma

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#647]
Som enestående emneord er det noe diffust, se på [bruk](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Gamma). 
Noen som føler seg kallet til opprydding?

Og så må de to termene `Compton Gamma-Ray Observatory` og `Gamma-Ray Observatory` over i korporasjon og slettes fra Realfagstermer.  @superLine ?

**Comment by danmichaelo** [comment]
Ryddet og fikset 610-innførsler for "Compton Gamma-Ray Observatory" mot BARE

Men en fin bokstav er det!
