### ISSUE TITLE
Eoliske prosesser

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#648]
Alle utenom Eoliske sedimenter (7) har bare en treff, så synes vi kan slå de sammen:

Eoliske prosesser
BF Eolisk transport
BF Eoliske landsformer
EN Aeolian processes
EN Aeolian transport
EN Aeolian landforms

Eoliske sedimenter
BF Eolisk sedimentasjon
EN Aeolian sediments
EN Aeolian sedimentation

Burde vi beholde den som ekstra term??

@realfagstermer/geo

**Comment by edinab** [comment]
Eoliske landformer bør stå for seg selv, men eoliske prosesser og eoliske transport kan slås sammen.

**Comment by edinab** [comment]
Eoliske sedimenter kan beholdes som egen term.

**Comment by danmichaelo** [comment]
Ok, da har jeg bare slått sammen `Eoliske prosesser BF Eolisk transport` og lagt på engelsk.

Lukker saken, men bare gjenåpne den igjen hvis du er uenig, @jw-geo ! Det er alltid lov å være uenig :)
