### ISSUE TITLE
Nytermforslag Skarver

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#649]
Skarver NN skarvar LA Phalacrocoracidae EN cormorants EN (tør vi?) shags

Aktuelt dokument: https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71541217310002201

**Comment by danmichaelo** [comment]
Opprettet med hele pakka!
