### ISSUE TITLE
 Nytermforslag: Bifangst

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#651]
Jf Wikipedia https://no.wikipedia.org/wiki/Bifangst

SNL har ikkje eiga innførsel, men ordet gir treff i andre innførslar. 

Foreslår Bifangst NN Bifangst EN Bycatch

Aktuelt dokument: https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71541179970002201

**Comment by danmichaelo** [comment]
Jeg leste først "Biefangst" :bee: :bee: 

Opprettet!
