### ISSUE TITLE
Skred

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#653]
Bare litt rydding her:

Skred
DE Gravitasjonsbetinget masseforflytning av stein, jord, leire eller snø (SNL).
BF Massebevegelser (<-- foreslår sammenlåing)
BF Ras
BF Lavine
EN Landslides
EN Mass movements
EN Mass wasting
EN Avalanches
SO Fjellskred
SO Snøskred
SO Leirskred
SO Jordskred
SO Undersjøiske skred
SO Skredfare

Fjellskred
DE Massebevegelse hvor store bergmasser styrter ut fra et fjell
BF Steinras
EN Rockfall
EN Rockslide
EN Rock avalanche

**Comment by danmichaelo** [comment]
Glimrende! Har lagt inn. Bare et lite spørsmål: Brukes ikke Avalanches bare om snøskred? Bør den ligge på Skred? Kunne du tatt for deg Snøskred, Jordskred og Leirskred også for systematikkens skyld?

**Comment by jw-geo** [comment]
Etter Merriam-Webster:
Avalanche - a large mass of snow, ice, earth, rock, or other material in swift motion down a mountainside or over a precipice.
Men de fleste bruker den sikker bare om snøskred.

Leirskred
DE Utflytting av større masse av leire.
EN Clay slide
SO Skred
SO Jordskred
SO Undersjøiske skred
> jeg synes vi kan fjerne her SO Fjellskred og Snøskred

Jordskred
DE Utflytting av større masse av jord eller andre løsmasser.
BF Jordras
BF Flomskred
BF Jordlaup
BF Landlaup
BF Bløtjordskred
BF Slamstrømmer
BF Massestrømmer
EN Earthflows
EN Soil flows
EN Mud flows
EN Debris flows
SO Leirskred
SO Undersjøiske skred
SO Turbiditter

> Burde Massestrøm være en egen term? Her er jeg litt usikker...


Jeg foreslår at vi forander Undersjøiske skred til Undervannskred etter Norges Geologiske Ordbok bruker termen.

Undervannskred
DE Utrasning under vann.
EN Submarine slide
EN Marine landslide
BF Undersjøiske skred
SO Turbiditter
SO Jordskred

Snøskred
DE Utrasning av store snømasser som sammenhengende flak av tørr eller våt snø.
EN Snow avalanche
EN Snowslide
BF Mjellskred
BF Kramskred
BF Sørpeskred


Turbiditter
DE Sedimentær avleiring avsatt fra turbidittstrømmer.
EN Turbidites
EN Turbidity currents
BF Turbidittstrømmer
BF Turbulente slamstrømmer
SO Undervannskred
SO Jordskred

**Comment by danmichaelo** [comment]
Glimrende, har lagt inn endringene, men venter med å lukke i tilfelle @edinab eller andre vil ha `Massestrømmer`  som egen term.

**Comment by edinab** [comment]
Dette ser bra ut.
Avalanches: Ja, det er Rock Avalanches som er mye brukt I faglitteratur, ikke bare snø.

Massestrømmer: nyterm = Ok.

**Comment by danmichaelo** [comment]
@edinab : Har du en bok som kan få termen `Massestrømmer`? Hvis ikke kan vi vente med å opprette den til vi har en bok

**Comment by edinab** [comment]
Jeg har ikke I dag. Men det er mange bøker som venter I kø her ;-)
Vi kan godt opprette det senere når det trengs.

**Comment by danmichaelo** [comment]
Ok, men hvis det kommer "snart" så oppretter jeg den bare nå :)

**Comment by edinab** [comment]
EN mass wasting
