### ISSUE TITLE
Landhevning

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#655]
Landhevning
DE Langsom hevning av landjorden i forhold til havnivået.
BF Isostatisk kompensasjon
EN Isostatic ulift
SO Havnivå

**Comment by danmichaelo** [comment]
Utflesking utført! Termen var forresten `Landheving`, så jeg la på `BF Landhevning` også

**Comment by danmichaelo** [comment]
(og "uplift", ikke "ulift")
