### ISSUE TITLE
Nedising = Avsmelting??

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#657]
Jeg foreslår:

Avsmelting
BF Nedising
EN Deglaciation

**Comment by Hypsibius** [comment]
Brukast dette slik i geofag? Når ein snakkar om nedising på fartøy eller fly er det snakk om akkumulasjon av is, ikkje avsmelting?

**Comment by jw-geo** [comment]
Da forstodde jeg vel noe feil. Jeg gikk ut fra det fordi den eneste bokem som er klassifisert med `Nedising` handler om `Avsmelting` av innlandsis. Da er det naturligvis ikke det samme men spørsmålet er kanskje om vi trenger `Nedising` i det hele tatt?

**Comment by danmichaelo** [comment]
Ingen vits å spare på dårlige termer. Jeg sletta den :wastebasket: 

Og la på EN på Avsmelting
