### ISSUE TITLE
Mangelegemeproblemer

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#66]
Legger inn denne som en huskelapp til meg selv foreløpig. Vi har 
```
Flerlegemeproblemet
Fålegemeproblemer
Mangelegemeproblemer
Mangelegemeproblemet
Tolegemeproblemet
Trelegemeproblemet
```
Tror `Mangelegemeproblemer`, `Mangelegemeproblemet` og `Flerlegemeproblemet` kan slås sammen, men må sjekke litteraturgrunnlaget. Et mulig skille kan være mellom problemet i klassisk mekanikk og kvantemekanikk.

**Comment by danmichaelo** [comment]
Hva er konklusjonen? Mari spør;)

**Comment by mittinatten** [comment]
Mangelegemeproblemer
   BF Flerlegemeprobleme(t/r)

   BF Mangelegemeproblemet
   BF n-legemeproblemer
   SO Trelegemeproblemer

og

   Trelegemeproblemer
   BF Trelegemeproblemet
   SO Mangelegemeproblemet

Stryke `Tolegemproblemet` ? (det er vel strengt tatt ikke et problem?) Fålegemeproblemer, er det 4-6 legemer elller noe? (kan nok strykes, bare en konferanse som den er brukt på)

Mulig det er mer logisk å snu på plural/bestemt form. Her har jeg ingen sterk mening.

**Comment by danmichaelo** [comment]
(sånn går det når man glemmer å logge av :))

Tja, jo.. men jeg sjekka bruken nå. Den fordeler seg omtrent (sjekka litt raskt) slik:

Tolegemeproblemet - celestmekanikk (3)
Fålegemeproblemer - celestmekanikk (1)
Mangelegemeproblemer - kvantefysikk (29) celestmekanikk (6)
Mangelegemeproblemet - celestmekanikk (2)
Tolegemeproblemet - celestmekanikk (3)
Trelegemeproblemet - celestmekanikk (4)

Mangelegemeprobleme(r/t) er vrien fordi den brukes i begge betydninger. Her skulle vi egentlig hatt en disambigueringsløsning slik at termen kunne peke til begge de to mulighetene. Inntil vi evt. får det er jeg rett og slett fristet til å unngå å bruke termen som indeksterm. Forslag:

```
Trelegemeproblemet
SO n-legemeproblemet
```
(entall siden problemet er veldefinert)

```
n-legemeproblemet
BF Flerlegemeproblemer
BF Fålegemeproblemer
SO Trelegemeproblemer
DEF "problemet innen klassisk mekanikk med å beregne de enkelte bevegelsene til en gruppe av himmellegemer som gravitasjonelt påvirker hverandre"
SO Mangepartikkelteori
SO Trelegemeproblemet
```
(entall siden problemet er veldefinert)

```
Mangepartikkelteori
BF Mangelegemeproblemer
BF Mangelegemeproblemet
DEF Kvantemekaniske teorier for beregning av egenskaper knyttet til mange (3 eller flere) vekselvirkende partikler.
SO n-legemeproblemet
```
("partikkel" er egentlig mye klarere enn "legeme". Mindre sikker på om "teori" eller " problemer" skal være foretrukket, men det er kanskje ikke så farlig. SO fra Mangepartikkelteori til Trelegemeproblemet er ikke nødv.)

Ser at vi må rydde litt i katalogen når det gjelder `Mangelegemeproblemer` først. Jeg kan godt hjelpe til med det, men venter noen dager i tilfelle det er innvendinger. Hva synes du @mittinatten ?

Enig i sletting av Tolegemeproblemet. Det er jo forsåvidt et veldefinert problem i klassiske mekanikk, men når jeg ser på bøkene som [har fått](http://katapi.biblionaut.net/documents?q=real:Tolegemeproblemet&show=sh) dette emneordet så virker det litt maplassert og tilsynelatende unødvendig.

**Comment by mittinatten** [comment]
Stort sett enig!

I praksis er det kanskje alltid celest mekanikk en taler om i klassiske flerlegemeproblemer, men problemstillingen er mer generell enn det. Foreslår enn litt mer allmenn definisjon: "Problemet med å løse bevegelsesligningene i klassisk mekanikk for et system med fler enn to legemer".

I kvantemekanikken ville jeg foretrukket Mangelegemeproblemer siden det tydeligere viser analogien med klassisk mekanikk. Helium-atomen er det mest klassiske eksempelet på trelegemeproblemet innen kvantemekanikk, og termen `Mangepartikkelteori` får meg å tenke mer på Feynman-diagram og lignende enn på atomfysikk (selv om det er korrekt i prinsipp).

**Comment by danmichaelo** [comment]
Jooooooo, meeeeen...

> I praksis er det kanskje alltid celest mekanikk en taler om i klassiske flerlegemeproblemer, men problemstillingen er mer generell enn det. Foreslår enn litt mer allmenn definisjon: "Problemet med å løse bevegelsesligningene i klassisk mekanikk for et system med fler enn to legemer".

Jeg mener (lov å være uenig) at vi ikke nødv. trenger å definere begreper helt generelt, siden vi først og fremst forholder oss til samlingene (selv om de selvfølgelig ikke er en fast størrelse). Og f.eks. en bibliotekar uten særlig fagkunnskap som sitter med en bok som "har noe med astro å gjøre" kan kanskje enklere nyttiggjøre seg en definisjon som også "har noe med astro å gjøre". Ellers ser jeg at selv Wikipedia (på tysk og engelsk ihvertfall) har begrenset seg til himmelmekanikk. Så lenge alt vi har (og antakelig kommer til å ha i fremtiden) omhandler himmellegemer synes jeg vi kan innsnevre definisjonen. Men noe annet jeg kom på er at def. kanskje ikke bør begrense seg til klassisk mekanikk mtp. relativistiske løsninger..?
 * Hva med "Problemet innen himmelmekanikk med å beregne banene til flere enn to legemer som gravitasjonelt påvirker hverandre."

> I kvantemekanikken ville jeg foretrukket Mangelegemeproblemer siden det tydeligere viser analogien med klassisk mekanikk. Helium-atomen er det mest klassiske eksempelet på trelegemeproblemet innen kvantemekanikk, og termen Mangepartikkelteori får meg å tenke mer på Feynman-diagram og lignende enn på atomfysikk (selv om det er korrekt i prinsipp).

Å beholde analogien synes jeg egentlig er mindre viktig enn å prøve å definere et skille mellom begrepene. Kanskje `Mangepartikkelproblemer` som et kompromiss? Jeg synes bruken av partikkel gjør det tydelig at man befinner seg omtrent på rett sted (på partikkelnivået, ikke himmellegemenivået), selv om det er et "kunstig" skille mtp. at punktpartikler gjerne brukes som modell for legemer i klassisk mekanikk.

**Comment by mittinatten** [comment]
Jeg skjønner ditt poeng og tenker vi kan gå for `Mangepartikkelproblemer`.

Den andre syns jeg er vanskeligere. Har vi retningslinjer for hvor "korrekte" vs tilgjengelige våre definisjoner skal være? Tenker at et bibliotek som har bøker om celest mekanikk også har personale som vet noe om bevegelsesligninger (eller?). Hva med `SO Celest mekanikk`?

I min verden går skillet mellom klassisk og ikke-klassisk ved kvantemekanikk, relativistisk mekanikk teller fremdeles som klassisk. Men her kan det være kulturforskjeller kan jeg tenke meg.

En annen måte å dekke begge behovene kunne vært noe i denne duren: "Problemet med å beregne baner for et klassisk system med fler enn to legemer - oftest for himmellegemer innen celest mekanikk" (vi har `Celest mekanikk BF Himmelmekanikk`). Eller "Problemet med å løse bevegelsesligningene for et system med fler enn to legemer. For eksempel flere himmellegemer som gravitasjonelt påvirker hverandre." Eller en variant av desse.

**Comment by danmichaelo** [comment]
Mjo, når jeg tenker etter tror jeg skillet mellom klassisk-ikke klassisk er det samme i min verden :)

Begge de siste definisjonene er fine synes jeg!

--- 
Da mangler vi bare en definisjon av `Mangepartikkelproblemer`... Sliter litt med denne, men kanskje

> Problemer knyttet til beregning av egenskaper for kvantemekaniske systemer av 3 eller flere vekselvirkende partikler.

Men høres det ikke rart ut? Nå begynner jeg å lure på om det er bedre med entall.

> [Mangepartikkelproblemet]
> Problemet med beregning av egenskaper for kvantemekaniske systemer av 3 eller flere vekselvirkende partikler. Inkluderer mangepartikkelteori.

eller bare

> Beregning av egenskaper for kvantemekaniske systemer av 3 eller flere vekselvirkende partikler.

eller hm....

**Comment by mittinatten** [comment]
Den siste definisjonen er  bra, og da burde det funke med både entall og flertall.

**Comment by mittinatten** [comment]
Konklusjonen er altså 

    Mangepartikkelproblemer
    BF Mangelegemeproblemer
    BF Mangepartikkelteori
    BF Mangepartikkelproblemet
    SO n-legemeproblemet
    DE Beregning av egenskaper for kvantemekaniske systemer av tre eller flere vekselvirkende partikler.

...og 

     n-legemeproblemet
     BF Flerlegemeprobleme(r/t)
     BF Fålegemeproblemer
     SO Trelegemeproblemet
     SO Mangepartikkelproblemer
     SO Celest mekanikk (?)
     DE Problemet med å løse bevegelsesligningene for et system med fler enn to legemer. For eksempel flere himmellegemer som gravitasjonelt påvirker hverandre.

og sist

     Trelegemeproblemet
     SO n-legemeproblemet

**Comment by danmichaelo** [comment]
:+1: Bare en liten ting: Skal vi endre "for et system" til "for et *klassisk* system" i den siste definisjonen?

**Comment by mittinatten** [comment]
Ja, det kan jo ikke skade :)

**Comment by danmichaelo** [comment]
Omsider gjort! Et lite hår i suppa er at "n-legemeproblemet" ble "N-legemeproblemet" fordi vi fortsatt normaliserer første bokstav som stor. Forhåpentligvis kan vi endre det en vakker dag i fremtiden.

**Comment by danmichaelo** [comment]
Hm, når jeg skulle søke etter Mangepartikkelteori i Roald nå ble jeg litt irritert over at Mangepartikkelproblemer var foretrukket term.. Hva tror du om å byte om på de, @mittinatten ?

**Comment by mittinatten** [comment]
Det går sikkert fint!

**Comment by danmichaelo** [comment]
✅  Gjort
