### ISSUE TITLE
Periglasial

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#660]
Vi har `Periglasial permafrost` og `Periglasial geomorfologi`. Jeg foreslår å slå de sammen til:

Periglasial
DE Klima, landformer og prosesser ved randen av dagens eller tidligere tiders isbreer. Betegner også mer generelt forholdene i områder hvor frostprosesser er aktive. (SNL)
BF Periglasiale miljøer
BF Periglasial geomorfologi
BF Periglasial permafrost
EN Periglacial
EN Periglacial environments
SO Permafrost

https://snl.no/periglasial

**Comment by danmichaelo** [comment]
`Periglasial` henger liksom litt i luften, men får ingen treff på `Periglasiasjon`, så jeg opprettet Periglasial.

[REAL012575](http://data.ub.uio.no/realfagstermer/c012575)
