### ISSUE TITLE
Glasial...

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#661]
### Sammenslåing

- [x] Glasial
DE Brukt om former eller prosesser som har tilknytning til en istid eller isbre. (NGO)
BF Glasiale miljøer
BF Bremiljøer
EN Glacial
SO Glasiale sedimenter
SO Glasifluvial
SO Glasilakustrin
SO Periglasial

- [x] Glasial geomorfologi  (<-- Nyterm)
BF Glasialmorfologi
BF Glasial geomorfologi
BF Drumliner
BF Glasiale landformer
BF Morenelandskap
BF Glasial erosjon
BF Breerosjon
EN Glacial geomorphology
EN Glacial landforms
EN Glacial erosion
SO Glasial

- [x] Glasiologi
DE Læren om is, egentlig læren om alle former for is i naturen, men mest brukt i betydningen læren om isbreer (breforskning). (SNL)
BF Glasialgeologi
BF Brelære
EN Glaciology
EN Glacial geology

- [x] Istider
DE Periode i Jordens historie da temperaturen på Jorden var vesentlig lavere enn i dag, og da store deler av landområdene var dekket av tykk innlandsis og breer, mens verdenshavene hadde lavere vannstand. (SNL)
BF Glasialer
BF Glasiale periode[r] (<-- `Glasiale periode`  eksisterer som term)
BF Glasialtider
EN Ice ages
EN Glacials

- [x] Glasiale sedimenter
BF Morener
BF Isavsetninger
BF Isbreavsetninger
BF Glasigene avsetninger
EN Glacial sediments
EN Glacial deposits
EN Glacigenic sediments
EN Moraines
SO Glasifluvial
SO Glasilakustrin
SO Glasimarine sedimenter

### Forandring av eksisterende termer:

- [x] Glasifluvial
DE Former, prosesser eller materiale som har tilknytning til breelver. (NGO)
BF Glasifluviale sedimenter
BF Breelvavsetninger
SO Glasiale sedimenter

- [x] Glasimarine sedimenter
DE Avsetninger som er fraktet ut til havet av en bre eller av breelver (NGO).
BF Glasiomarine prosesser
BF Brenærete havavsetninger
BF Glasimarin
EN Glaciomarine sediments
EN Glacial marine sediments
SO Glasiale sedimenter

- [x] Isbreer
DE Ismasse dannet ved snøfall og rim, som under tyngdens påvirkning beveger seg langsomt nedover, lik en seig, plastisk masse. (SNL)
EN Glaciers
SO Innlandsis
SO Kryosfære

- [x] Innlandsis
DE Bre som dekker et stort område og er så tykk at underlagets topografi ikke vises på overflaten. (SNL)
BF Isdekke
EN Ice sheets
EN Continental glaciers
SO Isbreer
SO Kryosfære

- [x] Havis
DE  Frosset sjøvann som dekker store havområder, både nord og sør på jordkloden. (wikipedia)
BF Sjøis
BF Drivis
BF Pakkis
EN Sea ice
EN Drift ice
SO Kryosfære

### Nyterm

- [x] Glasilakustrin
DE Former, prosesser eller materiale som har tilknytning til bresjøer. (NGO)
BF Bresjøer
BF Glasiolakustrin
EN Glaciolacustrine
SO Glasiale sedimenter

### Sletting

- [x] Brevariasjoner

**Comment by danmichaelo** [comment]
ping @realfagstermer/geo

**Comment by edinab** [comment]
1. Glasial = ok
2. Glasial geomorfologi (<-- Nyterm) = ok
3. Glasiologi: du skriver at BF galsialgeologi men også som nyterm. ?
4. Istider = ok.
5. Glasiale sedimenter = ok.

**Forandring av eksisterende termer:**
6. Glasifluvial = ok.

7. Glasimarine sedimenter = her skulle man kanskje heller organisere termene som ved Glasifuvial; altså ikke Glasimarine sedimenter (for de er ikke prosesser), men:
Glasimarin
 BF Glasiomarine prosesser
 BF Brenærete havavsetninger
 BF Glasimarine sedimenter
 
8. Isbreer = ok.

9. Innlandsis = ok

10. Havis = ok.

**Nyterm**
11. Glasilakustrin = ok. 

**Sletting**
Brevariasjoner = ok. Men jeg fikk ikke slå opp den I emneordsøk, det funket ikke "OBS: Resultatlisten for Humord er for tiden ufullstendig på grunn av en feil i Oria-indekseringen. For status, se Bibsys OTRS 20170320107262."

**Comment by danmichaelo** [comment]
Gjort :sweat_smile:

@edinab : 
Brevariasjoner: Humord-feilen påvirker ikke Realfagstermer. Bredt søk ga [et treff](https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBO:default_scope:BIBSYS_ILS71499144290002201), mulig den ikke har blitt konvertert riktig. Slettet uansett termen.

Jeg la inn forslaget ditt : `Glasimarin` som foretrukket term + definisjon syntetisert fra SNL og NGO: "som angår havet eller havbunnen utenfor eller under en isbre (SNL), inkl. avsetninger som er fraktet ut til havet av en bre eller av breelver (NGO)". Bare si fra hvis du har et bedre forslag
