### ISSUE TITLE
Nyterm: Merder

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#663]
Hadde vi ikkje Merder liggande inne, då? Ei heller oppdrettsanlegg? 

Foreslår: Oppdrettsanlegg BF Merder EN Sea cages EN Cage culture 

Aktuelt dokument:

https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71479320510002201

**Comment by danmichaelo** [comment]
Bare [Lukkede oppdrettsanlegg](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009179) !

Opprettet `Oppdrettsanlegg` og slo sammen med de lukkede.
