### ISSUE TITLE
Forhistoriske mennesker

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#667]
Forhistoriske mennesker
Fossile mennesker
Apemennesker
Hominider
Humanevolusjon
Paleoantropologi
Mennesket : Evolusjon

Disse er brukt om hverandre. Kan vi enes om en eller to så kan jeg rydde?

**Comment by Hypsibius** [comment]
Har generelt ein forkjærleik for norske omgrep, men meinar hominider (som inkluderar mennesket) er meir presist enn _forhistoriske mennesker_ og _fossile mennesker_ (parafyletiske grupper). Og begrepet _apemennesker_ har eg aldri likt. 

Foreslår dermed å samle til: 
Hominider EN Hominids EN Paleoanthropology LA Hominidae BF Forhistoriske mennesker BF Fossile mennesker BF Apemennesker BF Paleoantrolpologi

Dessutan 
Humanevolusjon BF Mennesket: Evolusjon

(men på det siste kan eg glatt overtalast til å gjere det motsett...

**Comment by BioHeidi** [comment]
Vi får ikke til å ha strenger som BF, eller å ha BF på en streng! Eller har du fikset det, @danmichaelo ?

Jeg har ellers slått sammen som du skrev, med Hominider som foretrukken. Takk for hjelpen!

**Comment by danmichaelo** [comment]
Nei, diverre. Jeg er fortsatt i "Shit, Knut slutter *faktisk*"-fasen
