### ISSUE TITLE
Adaptive teknikker

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#669]
Mulig utdatert ord

--
URI: http://data.ub.uio.no/realfagstermer/c000229
Bruk: https://app.uio.no/ub/emnesok/realfagstermer/search?term=Adaptive teknikker

**Comment by danmichaelo** [comment]
Dårlig term, sletter denne. Den ene boka vi hadde handlet om [Adaptive mesh refinement](https://en.wikipedia.org/wiki/Adaptive_mesh_refinement), som kunne vært en ok term, men hva blir det på norsk, mon tro...

**Comment by danmichaelo** [comment]
Tror ikke jeg bør bruke mye tid på å tenke ut en norsk term ingen kommer til å søke etter, så lukker :)

**Comment by BioHeidi** [comment]
Men vi har emneordet Adaptive Mesh Refinement. Jeg har mappet det til 518.2 foreløpig mens jeg venter på svar fra @TorgunnKarolineMoe
