### ISSUE TITLE
kryptografi

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#67]
Foreslår termen `krypteringsalgoritmer` eller `kryptografiske algoritmer` (eller streng `kryptografi : algoritmer`). I tillegg `symmetrisk kryptografi`.

belegg http://ask.bibsys.no/ask/action/show?kid=biblio&cmd=reload&pid=144343835

**Comment by danmichaelo** [comment]
Da la jeg like godt inn `Symmetrisk kryptering` og `Kommunikasjonssikkerhet` også

**Comment by danmichaelo** [comment]
Drøsset på litt SO-henvisninger
