### ISSUE TITLE
Antarktisk geofysikk

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#670]
Har ikke wikiside

--
URI: http://data.ub.uio.no/realfagstermer/c000621
Bruk: https://app.uio.no/ub/emnesok/realfagstermer/search?term=Antarktisk geofysikk

**Comment by danmichaelo** [comment]
Det trenger du ikke melde fra om. Ideelt sett skulle det vært en mulighet for å markere i verktøyet at man har sjekka, men ikke funnet noe, men det er det ikke. Så bare hopp videre når du ikke finner en wikiside.
