### ISSUE TITLE
Elektrofysikk

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#672]
Av søk på Google virker det som at dette er et noe utdatert ord

--
URI: http://data.ub.uio.no/realfagstermer/c010890
Bruk: https://app.uio.no/ub/emnesok/realfagstermer/search?term=Elektrofysikk

**Comment by mittinatten** [comment]
Ser ut som den kan slås sammen med `Elektronfysikk`, men kanskje begge bare rett og slett skal slettes? @danmichaelo

**Comment by olavbje** [comment]
Jeg ville heller knyttet elektrofysikk til elektronikk. Elektronfysikk ville jeg kalt en underkategori av partikkelfysikk. Personlig synes jeg ikke elektronfysikk er et godt ord det heller. Ved å søke på "elektron" og anvendelsen på elektronet du er ute etter, finner man stort sett frem. Vil tro det er veldig få som søker med "elektronfysikk".

**Comment by mittinatten** [comment]
Jeg tenkte på at de to bøkene termen var brukt på handlet om "Elektronenphysik"

**Comment by olavbje** [comment]
Aha, det sjekket jeg ikke, men da er jeg enig med deg.

**Comment by danmichaelo** [comment]
Enig og enig. Sletta like godt begge. OBS: Soksed henter dataoppdateringer nattlig, så det forsvinner ikke derfra før i morgen.
