### ISSUE TITLE
Biologisk kjemi og Biokjemi

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#673]
Kan slås sammen, @realfagstermer/bio ?

--
URI: http://data.ub.uio.no/realfagstermer/c003080
Bruk: https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biologisk kjemi
Soksed: https://soksed.biblionaut.net/concepts/REAL003080

**Comment by Hypsibius** [comment]
Kan gjerne sjekke med kjemikarane @bir også, men eg ser ingen grunn til å halde dei separate...

**Comment by BioHeidi** [comment]
Slå.

**Comment by danmichaelo** [comment]
Slo, har slått!
