### ISSUE TITLE
Biologisk styrkebestemmelse og Bioassays

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#674]
Kan slås sammen?

https://en.wikipedia.org/wiki/Bioassay

--
URI: http://data.ub.uio.no/realfagstermer/c010544
Bruk: https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biologisk%20styrkebestemmelse
Soksed: https://soksed.biblionaut.net/concepts/REAL010544

**Comment by Hypsibius** [comment]
Styrkebestemmelse?

**Comment by danmichaelo** [comment]
Kom over de fordi "Bioassay" ble foreslått som oversettelse av [Biologisk styrkebestemmelse](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010544) i [prosjekt Kinderegg](https://github.com/realfagstermer/prosjekt-kinderegg), men usikker på om bioassay kan ha flere betydninger.

Katalogbruken vår: [Bioassays](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c011793)

**Comment by BioHeidi** [comment]
Har lyst til å beholde Bioassays fordi det er et så innarbeidet begrep. Det står også i SNL uten oversatt term.

**Comment by danmichaelo** [comment]
Gjort!
