### ISSUE TITLE
Tikk takk

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#676]
Trengs alle? @realfagstermer/bio 

* [Biologiske klokker](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biologiske%20klokker)
* [Biorytmer](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biorytmer)
* [Biologiske rytmer](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biologiske%20rytmer)
* [Kronobiologi](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Kronobiologi)

**Comment by mittinatten** [comment]
her mangler også SO/UT/OT til/fra cirkadisk rytme

**Comment by danmichaelo** [comment]
Ser dette ok ut for @realfagstermer/bio ?

```
Kronobiologi
BF Biologiske klokker
BF Biorytmer
BF Biologiske rytmer
BF Kronobiologi
BF Cirkadiske rytmer
BF Døgnrytme
```

**Comment by Hypsibius** [comment]
Biorytmar fjernar vi. 

Pseudovitskap: 
https://en.wikipedia.org/wiki/Biorhythm
https://snl.no/biorytme_-_p%C3%A5st%C3%A5tt_syklus

**Comment by danmichaelo** [comment]
Gjort! :sun_behind_large_cloud:  La på mer engelsk også
