### ISSUE TITLE
Strålebiologi og Radiobiologi

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#677]
kan vel slås sammen, @realfagstermer/bio ?

--
URI: http://data.ub.uio.no/realfagstermer/c006137
Bruk: https://app.uio.no/ub/emnesok/realfagstermer/search?term=Strålebiologi
Soksed: https://soksed.biblionaut.net/concepts/REAL006137

**Comment by Hypsibius** [comment]
Ja, det kan det vel, @BioHeidi ?

**Comment by BioHeidi** [comment]
Ja. Strålebiologi BF Radiobiologi

**Comment by danmichaelo** [comment]
Gjort!
