### ISSUE TITLE
Teoretisk biofysikk og Biofysikk

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#678]
Noen innvendinger mot å slå sammen?

--
URI: http://data.ub.uio.no/realfagstermer/c005554
Bruk: https://app.uio.no/ub/emnesok/realfagstermer/search?term=Teoretisk%20biofysikk
Soksed: https://soksed.biblionaut.net/concepts/REAL005554

**Comment by mittinatten** [comment]
Siden det står "Teoretisk biofysik" på doktorgraden tar det litt i mot å ta vekk termen :)

Men, tror det gir mening å slå de sammen, vanskelig å se for meg at vi noensinne kommer å ha et litteraturgrunnlag for å skille mellom de. Hvis en har en tittel som fremst handler om teoretiske aspekter av biofysikk er det sannsynligvis nyttigere å komplettere med en term som for eksempel `statistisk mekanikk` eller hva det nå må være.

**Comment by Hypsibius** [comment]
Anser @mittinatten som eksperten på denne :-)

**Comment by danmichaelo** [comment]
Ok, slo dem sammen. @mittinatten : Gi beskjed i løpet av dagen hvis du angrer og vil beholde Teoretisk biofysikk :)
