### ISSUE TITLE
Økonomisk bevaringsbiologi

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#679]
Trengs denne, @realfagstermer/bio ?

--
URI: http://data.ub.uio.no/realfagstermer/c005173
Bruk: https://app.uio.no/ub/emnesok/realfagstermer/search?term=Økonomisk%20bevaringsbiologi
Soksed: https://soksed.biblionaut.net/concepts/REAL005173

**Comment by Hypsibius** [comment]
Nei, dette er ein term eg vanskeleg kan tenkje meg folk søker på. Bevaringsbiologi får stå for seg sjølv, og så får vi evt legge til ein ekstra term på 'drivverdige' eller 'harvestable' artar, om det skulle vere behov for det. I fiskebøker pleier det å vere ein igen heading med 'økonomisk betydning'

**Comment by danmichaelo** [comment]
Takk! Slettet
