### ISSUE TITLE
Biocider og Pesticider

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#680]
Kan de slås sammen? @realfagstermer/bio 

--
URI: http://data.ub.uio.no/realfagstermer/c005782
Bruk: https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biocider
Soksed: https://soksed.biblionaut.net/concepts/REAL005782

**Comment by BioHeidi** [comment]
Nei, det er en forskjell i begrepene, men de er kanskje ikke brukt konsekvent. Jeg legger inn definisjoner på dem, så blir de forhåpentligvis brukt riktig fremover. Kanskje noen vil rydde en dag også...

**Comment by danmichaelo** [comment]
:+1: Lukker nå da
