### ISSUE TITLE
Ørretrydding?

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#681]
Her var det eit sant sammensurium!

![trout](https://cloud.githubusercontent.com/assets/9350370/23159205/2c8b8fce-f822-11e6-928e-ad70040a14ec.PNG)

Vi kan teoretisk behalde ein term 'ørreter', men fleirtalsforma brukar vi berre når vi snakkar om grupper av artar, så då kan vi ikkje knytte rett til _Salmo trutta_. Iflg ITIS er dette også ein god art (enn så lenge), så oppdeling i mogelege underartar er litt overkill. 

Mitt forslag er at ein slik oveordna term opprettar vi v evt behov. 

Her og no: Ørret LA Salmo trutta EN brown trout BF Fjellørret BF Sjøørret (NB: eintalsform!)

**Comment by BioHeidi** [comment]
Jepp! Overkill foreløpig, så jeg har gjort som du foreslo.
