### ISSUE TITLE
plankton: flora

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#682]
Foreslår å slette denne strengen, etter forslag frå  @apaus 

Kun eitt dokument, og termen oppmuntrar til slurv, der det er dyreplankton eller heterotrofe former er det ikkje romeleg å snakke om ein flora. Sjølv vil eg heller ikkje overforbruke strengar, og ville på det aktuelle dokumentet lagt inn to separate termar, Planteplankton og format: Bestemmelseslitteratur

**Comment by Hypsibius** [comment]
Romeleg. Eller rimeleg...

**Comment by danmichaelo** [comment]
Enig, slettet! @BioHeidi : Hvis du vil gjøre noe med den aktuelle boka, så er det denne: https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBO:default_scope:BIBSYS_ILS71466492360002201

**Comment by Hypsibius** [comment]
@BioHeidi Lurer på om @apaus alt endra emneord for denne?

**Comment by BioHeidi** [comment]
Veldig fint at dere rydder i alt som har fått flora-strenger. Der er det MYE rot.
