### ISSUE TITLE
Faktorer

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#683]
Veldig generell term som antakelig ikke egner seg som emneord. Med mindre den har en bestemt betydning innen bio? @realfagstermer/bio 

--
URI: http://data.ub.uio.no/realfagstermer/c000211
Bruk: https://app.uio.no/ub/emnesok/realfagstermer/search?id=c000211
Soksed: https://soksed.biblionaut.net/concepts/REAL000211

**Comment by Hypsibius** [comment]
Ville nok uansett spesifisert faktorar/parametrar

**Comment by BioHeidi** [comment]
slett

**Comment by danmichaelo** [comment]
Slettet
