### ISSUE TITLE
Fordeling

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#684]
Det første jeg tenkte på da jeg så denne termen var økonomisk fordeling, men det ser ut som den er brukt om mange typer fordelinger, og vi har mange spissere termer vi kan bruke i stedet. Slette? Jeg tror nesten ikke katalogrydding er nødvendig engang, men kan se litt nøyere på det.

--
URI: http://data.ub.uio.no/realfagstermer/c003439
Bruk: https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003439
Soksed: https://soksed.biblionaut.net/concepts/REAL003439

**Comment by Hypsibius** [comment]
I økologisk samanheng har vi Romlig fordeling, det tenkjer eg held. 

Forøvrig viktig å ikkje blande saman Ideell fri fordeling med Ideell fri fôr-deling, sjølv om predikert mønster truleg blir det same? Kan ein kjenne seg fôrfordelt?

**Comment by mittinatten** [comment]
Ja, og så har vi de forskjellige sannsynlighetsfordelingerne. Slettes.

**Comment by danmichaelo** [comment]
Slettet
