### ISSUE TITLE
Væsker vs. fluider i geologi

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#688]
Jeg synes vi burde skille mellom `Væsker` for generell bruk i mekanikk og kjemi og `Fluider ` i sammenheng med geologiske prosesser.

Det ser ut for meg som de termene Fluider, Væskestrøm og Væskestrømning er flest brukt for den geologiske meningen, så jeg foreslår at vi slår de sammen til:

Fluider (geologi)
DE Brukt for væsker eller blandinger av væske og gass i sammenheng med geologiske prosesser
BF Væskestrømning
BF Væskestrøm
SO Væsker
EN Geological fluids
EN Fluid flow

@realfagstermer/geo

**Comment by danmichaelo** [comment]
God idé, slått sammen! Fysikk har jo `Fluidmekanikk`, `Kondenserte fasers fysikk` osv...
