### ISSUE TITLE
Ny liste med engelske termer

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#690]
Alluviale sedimenter -> Alluvial sediments, Alluvium
Alluviale vifter -> Alluvial fans
Anvendt geologi -> Applied geology
Fanerozoikum -> Phanerozoic
Fluviale prosesser -> Fluvial processes
Fysisk geologi -> Physical geology
Geologisk historie -> History of geology
Hydrotermale avsetninger -> Hydrothermal sediments
Hydrotermale malmforekomster -> Hydrothermal ore deposits, Hydrothermal mineral resources
Hydrotermale prosesser -> Hydrothermal processes
Ingeniørgeologi -> Engineering geology
Jordas struktur -> Structure of the Earth
Jordas dannelse -> Formation of the Earth
Jordskorpen -> Earth's crust
Kambrium -> Cambrian
Klastiske sedimenter -> Clastic sediments
Litosfæren -> Lithosphere
Mantelen -> Mantle
Metasomatose -> Metasomatism
Midthavsrygger -> Mid-ocean ridges, Oceanic spreading centers, Seafloor spreading centers
Neotektonikk -> Neotectonics, Active tectonics
Passive marginer -> Passive margins
Prekambrium -> Precambrian
Sedimentasjon -> Sedimentation
Stillehavet -> Pacific ocean
Tektonikk -> Tectonics
Undersjøiske skred -> Submarine landslides

**Comment by danmichaelo** [comment]
@jw-geo : Vi har nå omsider fått oversettingsverktøyet på plass, så du kan godt begynne å bruke det. Det lever på https://soksed.biblionaut.net/ , velg "2017: Engelsk + kategorisering + Wikidata". Bare tips meg når du har autentisert deg der, så gir jeg deg tilgang. Vi prøver også å få hjelp av studentbetjenter her til å oversette i [Prosjekt Kinderegg](https://docs.google.com/document/d/1LdbfXSOSQ4Dfum25-JGRMGRQxBordqmzL52GbTwRpZo)

**Comment by jw-geo** [comment]
Ok, det skal jeg gjøre. Har autentisert meg...

**Comment by danmichaelo** [comment]
Sånn, nå skal du ha tilgang! (Last siden på nytt hvis ikke :))

Du finner mer informasjon i [dette google docs-dokumentet](https://docs.google.com/document/d/1LdbfXSOSQ4Dfum25-JGRMGRQxBordqmzL52GbTwRpZo).

Legg gjerne på "geo"-kategorien når du er i gang. Om du vil prøve å finne wikidata-mappinger også er det supert, men det går fint an å bare legge inn oversettelsene og la mappingene ligge til noen andre får  sett på dem.

**Comment by jw-geo** [comment]
Takk for hjelpen @danmichaelo ! Da har jeg lagt inn de engelske termene.
Men jeg har en stedsterm (Stillehavet) som jeg ikke finner i soksed...

**Comment by danmichaelo** [comment]
Supert @jw-geo ! Det var et filter på begrepstype som jeg har deaktivert nå. Fikset også

https://soksed.biblionaut.net/concepts/REAL030241?view=mapping&q=Stillehavet,
