### ISSUE TITLE
Nyterm: Kaledonske fjellkjede

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#696]
https://snl.no/Kaledonske_fjellkjede

Kaledonske fjellkjede
BF Kaledonidene
BF Kaledonske fjellkjededannelse
EN Caledonian mountain belt
EN Caledonides
EN Caledonian orogeny

**Comment by edinab** [comment]
Kaledonske fjellkjede er den ordentlige navnet på norsk. Det er ett godt forslag. Samtidig jeg vet ikke om det er nødvendig. Kaledonidene burde nesten rekke. De fleste fagfolk bruker bare det eller Kaledonske fjellkjedefoldning. På engelsk Caledonian mountain belt er kanskje unødvendig å ha. Det er jo det samme som Caledonian orogen (fjellkjede), og orogeny (fjellkjedefoldning/dannelse) er brukt veldig ofte I litteraturen. På nork jeg ville hatt: Kaledonidene og Kaledonske fjellkjedefoldning. På engelsk: Caledonides or Caledonian orogeny og Caledonian orogeny.

**Comment by danmichaelo** [comment]
[Kaledonidene](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c030456) har vi fra før, så da er vel spørsmålet egentlig bare hvilken term som skal være hovedterm. @jw-geo : Ok å beholde `Kaledonidene` som hovedterm, og så bare legge på `BF Kaledonske fjellkjede` og `BF Kaledonske fjellkjededannelse` og engelsk?

**Comment by jw-geo** [comment]
Takk for innspillet, jeg fant ikke `Kaledonidene` fordi det er en stedsterm. Jeg synes vi kan godt beholde `Kaledonidene` som hovedterm men jeg synes egentlig at det burde heller være emne enn sted.

**Comment by edinab** [comment]
Jeg kan ikke tenke meg at noen skulle søke på fjelkjededannelse. Ordet er korrekt, men vi altid snakker om Kaledonske fjellkjedefoldning.
Engelsk: Caledinides & Caledonian Orogeny

**Comment by edinab** [comment]
mente: Caledonides

**Comment by jw-geo** [comment]
Jeg foreslår emneterm: 

Kaledonidene
BF Kaledonske fjellkjedefoldning
BF Kaledonske orogenese
EN Caledonides
EN Caledonian Orogeny

**Comment by jw-geo** [comment]
Er dere enig at vi forandre termen fra stedsterm til emneterm?

**Comment by danmichaelo** [comment]
Enig. Men lurer på om @knuthe ikke har lagt til støtte i Sonja for å endre termtype :D Men det kan fikses med litt forsiktig tukling med kildefilene.. Og så må jeg oppdatere [lokar](https://github.com/scriptotek/lokar).

**Comment by jw-geo** [comment]
Det var ikke meningen å gjøre livet vanskelig for deg ;)

**Comment by knuthe** [comment]
Om ikke annet: slett stedet og lag nytt emne :-) men forsiktighet må utvises: ta vare på dokid på poster der sted fjernes og legg til nytt emne manuelt på disse postene ...

**Comment by danmichaelo** [comment]
Gjort. Nå har lokar også fått støtte for å flytte emner mellom MARC-felt
