### ISSUE TITLE
Versjonskontroll

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#70]
På termen Versjonskontroll har vi `BF Git`, `BF Subversion` men `SO Cvs`. Jeg mener Git og Subversion bør behandles på lik linje med Cvs. Vi kan gjerne legge til termer for Git og Subversion. For alle tre er overordnet term Versjonskontroll, vet ikke om vi bør bruke Se også for underordnet/overordnet?
@knuthe

**Comment by danmichaelo** [comment]
Skal vi bare sette CVS som BF under "Versjonskontroll" @knuthe? Eller innføre hierarki? Begge deler er OK for meg

**Comment by knuthe** [comment]
Vi har,  - så vidt jeg husker, men det er ikke langt - hatt dette oppe tidligere. @mittinatten reiste spørsmålet, eller kanskje det var deg? I forbindelse med diskusjonen om OT/UT. Det er jo flere slike versjonskontrollsystemer. Det er vel naturlig med UT? Men har vi diskutert ferdig dette med OT/UT @bibliomari ? Får vi lov?

**Comment by danmichaelo** [comment]
Svarte du direkte per epost? Hvis ja, se gjerne https://github.com/realfagstermer/realfagstermer/issues/70

**Comment by knuthe** [comment]
Nei, jeg er bare formørket av formørkelsen. Innså ikke at jeg kunne skrolle oppover. Jeg er for OT/UT på dette, men det er ikke ferdig diskutert i redaksjonen, tror jeg. Programmet er ferdig (selv om det ikke lå under juletreet).

**Comment by mittinatten** [comment]
Jeg syns det er et vanskelig spørsmål. Som @danmichaelo sa tidligere er den som er interessert av versjonskontroll sannsynligvis ute etter en manual for et spesifikt verktøy, git/subversion/mercurial/etc. RCS/CVS/etc har nok mest historisk interesse (jeg håper ingen fremdeles bruker dem), og da er det logisk at en søker på versjonskontroll. Det som hadde vært nyttig er hvis en uinformert person prøver å finne en CVS-manual, får masse treff på Git, og da bestemmer seg for å prøve Git ut i stedet. (kanskje ikke et særlig vanlig usecase).

Rent pragmatisk så har vel alle relevante dokument programmets navn i tittelen, altså ikke vanskelige å finne, og termen versjonskontroll gir oversikt over alle versjonskontrolldokumenter. Regner med der er veldig få titler som omhandler mer enn ett versjonskontrollsystem i særlig dybde (muligens titler av typen "introduction to unix programming").

Så min konklusjon er at det kanskje holder med bare `Versjonskontroll`, men jeg er åpen for det andre alternativet også.

**Comment by danmichaelo** [comment]
Jeg heller mer og mer mot den samme konklusjonen basert på samme argumentasjon.

Kanskje også omdøpe til `Versjonskontrollsystemer`

**Comment by danmichaelo** [comment]
Ok, da ble det sammenslåing av `Versjonskontroll` og `Cvs`, slik at vi nå har `Versjonskontroll BF Git BF Subversion BF CVS BF VCS` og tilsv. nynorsk og engelsk.
