### ISSUE TITLE
Gauge-teorier

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#700]
Kan det slås sammen med Gauge-felter og Gauge-symmetri?

**Comment by mittinatten** [comment]
Ja. Lurer på om det burde være entallsform? `Gauge-teori BF Gauge-...`

**Comment by mittinatten** [comment]
Bokmålswikipedia skriver uten bindestrek https://no.wikipedia.org/wiki/Gaugeteori

**Comment by danmichaelo** [comment]
Slått sammen. Man skriver vel vanligvis gaugeteori med liten forbokstav, så da skal det ikke være bindestrek.
