### ISSUE TITLE
Plantebiologi og Botanikk

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#702]
WP har slått de sammen: *[Botany](https://en.wikipedia.org/wiki/Botany), also called plant science(s), plant biology or phytology, is the science of plant life and a branch of biology.*

Ønsker vi å gjøre det samme, eller vil vi beholde skillet? @realfagstermer/bio

**Comment by Hypsibius** [comment]
SNL ser ut til å bruke plantebiologi meir eller mindre synonymt med botanikk. Bokmålswikipedia  omdirigerer plantebiologi til botanikk, nynorskwikipedia har inga innførsle for plantebiologi. Og om eg oppfattar betoninga av dei to littegrann forskjellig, klarer eg ikkje med mi beste vilje å uttrykke kva forskjellen består i. Så eg tenkjer det er berre å slå saman! Og PS: 'plantebiologi' finst verken i nynorsk- eller bokmålsordboka ;-)

**Comment by danmichaelo** [comment]
Enig, @BioHeidi ?

**Comment by BioHeidi** [comment]
Ja, har vi ikke gjort dette allerede altså?
Botanikk BF Plantebiologi.

**Comment by danmichaelo** [comment]
NÅ er det gjort
