### ISSUE TITLE
Determinisme og Biologisk determinisme

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#706]
[Biologisk determinisme](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biologisk%20determinisme)
[Determinisme](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010499)
Ikke egentlig det samme, men flere av dokumentene handler om (nesten) det samme?
Kanskje dette er en ryddesak og ikke en sammenslåing.

**Comment by Hypsibius** [comment]
Tenker at det essensielle her er Determinisme som term, og så får vi legge på andre termar (e.g. genetikk) for  å belyse spesifikt kva mekanismar det er, Tenker at på det viset bringer ikkje Biologisk Determinisme meg særlg mykje lenger.

**Comment by danmichaelo** [comment]
Enig. Jeg beholdt `Determinisme`.
