### ISSUE TITLE
Biomaterialer og Biomedisinske materialer

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#707]
[Biomaterialer ](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004713)
[Biomedisinske materialer](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biomedisinske%20materialer)

**Comment by BioHeidi** [comment]
Jepp. Det er synonymer.

**Comment by danmichaelo** [comment]
Slått sammen
