### ISSUE TITLE
Biomineraler og Biomineralisering

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#708]
[Biomineraler](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biomineraler)
[Biomineralisering](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002023)

**Comment by Hypsibius** [comment]
Greit for meg

**Comment by danmichaelo** [comment]
Slått sammen
