### ISSUE TITLE
Nyterm Øresund

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#710]
Fanst pussig nok ikkje. 

Foreslår Stadterm Øresund

https://snl.no/%C3%98resund

Aktuelt dokument: https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71479008510002201
 Og det reiser eit spørsmål (garantert besvart før): Korleis handterer Realfagstermar Ø vs Ö? Norsk og dansk staving er Øresund, Svensk Öresund, engelsk tillet tydelegvis begge?

**Comment by danmichaelo** [comment]
Lagt til!

Per i dag er vi ganske strikte på at `Ø != Ö`, så jeg la inn `Øresund BF Öresund`. I Emnesøk burde det nok i fremtiden være slik at man får treff på ø ved søk på ö og vice versa.

Noe annet er at vi burde kunne hente stedsnavn fra Geonames eller annet fremfor å vedlikeholde en lokal liste, men det er også noe for fremtiden :)
