### ISSUE TITLE
System on a chip

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#712]
Svensk wikipedia har "systemkrets" og "systemchip" som alternative termer., men er usikker på om disse termene er entydige nok til å fungere som foretrukken term, så jeg heller mot å bare "system on a chip"  som foretrukket term..

Dokument: https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBO:default_scope:BIBSYS_ILS71542229210002201

@mittinatten

**Comment by mittinatten** [comment]
hmm, har ingen sterke meninger her, men heller vel mot samme konklusjon som deg tror jeg.

**Comment by danmichaelo** [comment]
Det ser ut som @knuthe har brukt `Innebygde systemer` tidligere, så inntil videre la jeg bare til `System on a chip` og `Systemkrets` som BF på den, men det er ikke helt ideelt. Det virker også som `System on a a chip` er en term som er vanskelig å definere, og som har stort overlapp med `Mikrokontrollere`.

SO [microcontroller vs. System on chip](http://electronics.stackexchange.com/questions/16828/microcontroller-vs-system-on-chip). Liker "System On a Chip (or SoC) is a catch-all phrase that marketing people use and doesn't really mean much." :)
