### ISSUE TITLE
Bergartsmagnetisme

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#714]
Bergartsmagnetisme
BF Magnetiske bergarter
EN Rock magnetism
SO Petrofysikk

https://en.wikipedia.org/wiki/Rock_magnetism

**Comment by danmichaelo** [comment]
Ok, endret "Magnetiske bergarter" til "Bergartsmagnetisme" og beholdt førstnevnte som BF.

https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003038
