### ISSUE TITLE
Granitt og Granitter

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#716]
Jeg forslår at vi slår de sammen med `Granitt` som foretrukket term samsvarende med andre bergartstermer som er i entall.

@realfagstermer/geo

**Comment by jw-geo** [comment]
Jeg ser at flertall blir brukt for de fleste bergarter. 
Så vi bare trenger forandre

Granit -> Granitter (sammenslåing)
Andesitt -> Andesitter
Boninitt -> Boninitter (vi har bare en bok tilknyttet denne termen; kanskje vi kan slå den sammen med Andesitter??)

**Comment by edinab** [comment]
Det er greit å endre til: Granitt, Andesitt og Boninitt.
Men Boninitt er IKKE andesitt (evenom det forekommer i litteraturen som f.eks. high-Mg andesite, primitive andesite, men også som low-Ti ophiolitic basalt, komatiitic basalt etc...): så de to kan ikke slås sammen.

**Comment by danmichaelo** [comment]
Men antar vi fortsatt kan endre `Boninitt` til `Boninitter` og `Andesitt` til `Andesitter`?

**Comment by edinab** [comment]
Ja! Det er det jeg mente også.

**Comment by danmichaelo** [comment]
Gjort
