### ISSUE TITLE
Bergarter, Steiner, Steinarter og Stein

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#717]
Jeg forslår sammenslåing:

Bergarter
BF Steiner
BF Steinarter
EN Rocks
EN Rock types
SO Stein (byggematerial)

I tillegg har vi `Stein` som blir mer brukt for stein som byggematerial eller lignende, så den burde skilles.

Jeg forslår vi forandrer den til:

Stein (byggematerial)
EN Stone (construction material)
SO Bergarter

@realfagstermer/geo

**Comment by danmichaelo** [comment]
Ser ut som et steinbra forslag!

**Comment by edinab** [comment]
For å slippe å rydde, sletter vi stein.

**Comment by danmichaelo** [comment]
Gjort! Jeg utvidet byggemateriale-termen litt videre:

```
Stein (materiale)
BF Stein (byggemateriale)
BF Bygningsstein
BF Naturstein (materiale)
```
