### ISSUE TITLE
Magmatiske bergarter og Eruptive bergarter

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#718]
SNL sier at Eruptive bergarter mener det samme som Magmatiske bergarter. Kan vi slå de sammen @realfagstermer/geo ?

Magmatiske bergarter
BF Eruptive bergarter

**Comment by edinab** [comment]
Magmatiske bergarter = Dypbergarter (Intrusive), Gangbergarter (Intrusive) og Dagbergarter (Eruptive).
Vi kan ikke bruke Magmatiske bergarter bare for Eruptive.

**Comment by danmichaelo** [comment]
Vi manglet faktisk `Dagbergarter`, så endret `Eruptive bergarter` til `Dagbergarter BF Eruptive bergarter`. Og la til:

```
Magmatisk bergarter
UT Dagbergarter
UT Gangbergarter
UT Dypbergarter
```
