### ISSUE TITLE
Magma, Magmatiske prosesser, Magmatisme

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#720]
For meg ser det ut som disse termene blir brukt for det samme.
Kan vi slå de sammen? @realfagstermer/geo 

F. eks.:

Magmatisme
BF Magmatiske prosesser
BF Mama

**Comment by danmichaelo** [comment]
Gjort, men vi valgte "Magma", ikke "Mamma" ;)
