### ISSUE TITLE
Nyterm: Gangbergarter

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#721]
https://snl.no/gangbergart

Gangbergarter
DE Magmatiskr bergarter, dannet ved at et magma størkner i spalter eller sprekker i jordskorpen.
EN Intrusive rocks <-- (etter Norsk Geologisk Ordbok)
SO Ganger (geologi)

https://snl.no/gang_-_geologi

Ganger (geologi)
DE Tavleformet bergartsmasse, malm eller mineral, som fyller en sprekk eller spalte i berggrunnen.
EN Dykes
EN Dikes
EN Sills

**Comment by danmichaelo** [comment]
Opprettet begge: REAL031852 og REAL031853
