### ISSUE TITLE
Geologisk datering og Geokronologi

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#723]
[Geologisk datering](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004887) og [Geokronologi](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005149) : kan de slås sammen eller trengs begge?

Bakgrunn: "Geochronology" ble foreslått som engelsk oversettelse i [Prosjekt Kinderegg](https://soksed.biblionaut.net/concepts/REAL004887)

@realfagstermer/geo

**Comment by jw-geo** [comment]
Jeg synes de kan slås sammen

**Comment by BioHeidi** [comment]
Gjort! Hadde tenkt å foreslå det selv, da jeg kom over de to termene i mappingen i går :)
