### ISSUE TITLE
Basiske bergarter, Ultrabasiske bergarter og Sure bergarter

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#725]
Vi har Basiske bergarter, termen mangler bare BF og EN

Basiske bergarter
BF Mafiske bergarter
EN Basic rocks
https://snl.no/basiske_bergarter

Jeg synes vi trenger to nytermer:

Ultrabasiske bergarter
BF Ultramafiske bergarter
BF Mantelbergarter
BF Peridotitter
EN Ultrabasic rocks
EN Ultramafic rocks

Sure bergarter
BF Felsiske bergarter
BF Saliske bergarter
EN Acidic rocks
EN Felsic rocks
https://snl.no/sure_bergarter

@realfagstermer/geo

**Comment by edinab** [comment]
De foretrukne termene bør være Mafiske, Ultramafiske og Felsiske bergarter. Basiske bergarter er mindre og mindre brukt i litteraturen. Ellers enig :-)

**Comment by danmichaelo** [comment]
Da har vi
* `Mafiske bergarter BF Basiske bergarter ...`
* `Ultramafiske bergarter ...`
* `Felsiske bergarter ...`

Ok, @jw-geo ?
