### ISSUE TITLE
Serpentin og Serpentinitter

### ISSUE THREAD

**Issue by jw-geo** [realfagstermer/realfagstermer#726]
Vi har en term for mineralen Serpentin som er brukt for en bok.
Skal vi bruke den termen også for bergarten Serpentinitt (med BF) eller skal den være en egen term @realfagstermer/geo ?

Jeg synes vi burde i alle fall har SO Ultrabasiske bergarter, når den termen har blitt opprettet.

**Comment by edinab** [comment]
Serpentinitt bør være en egen term. De to bøkene vi har med Serpentin som term kunne hatt Serpentinitt istedet. Dersom vi får en bok som handler om Serpentin kan vi heller opprette det igjen som term.

**Comment by danmichaelo** [comment]
Gjort `Serpentinitter BF Serpentin`. Så deler vi det bare hvis det blir behov for det.
