### ISSUE TITLE
Sletteforslag 23.03.17: Bio* spesial

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#728]
- [ ] [Biofacies](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biofacies)
- [ ] [Biogeometri](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biogeometri)
- [ ] [Biokjemiske metoder](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biokjemiske%20metoder) Evt. slås sammen med Biokjemi : metoder?
- [ ] [Biologisk analyse](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biologisk%20analyse)
- [ ] [Biologiske data](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biologiske%20data) Evt. slås sammen med Bioinformatikk?
- [ ] [Biologiske databaser](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biologiske%20databaser)
- [ ] [Biologiske funksjoner](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biologiske%20funksjoner)
- [x] [Biologiske metoder](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biologiske%20metoder)
- [x] [Biopati](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biopati)
- [ ] [Biosonering](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Biosonering)

**Comment by Hypsibius** [comment]
'Biologiske data' er ein altfor vid term til å kunne vere nyttig på nokon måte (må jo inkludere alle former for biometri, men også bestandsdata, artsfordelingar etc., grovt sett alt som er biologi og har data). Dei dokumenta som har termen, skal heilt klart ha Biometri i staden! Berre slett!

**Comment by Hypsibius** [comment]
Lurer på termen biosonering, som tydeleg ikkje har nokon ting med det eg forbinder med sonering å gjere. Kan godt slettast for meg, men har vi altså aldri kjent på behovet for sonering som eigen term? Det har vi nemleg ikkje! jf http://kosmossf.cappelendamm.no/c35918/artikkel/vis.html?tid=80531&within_tid=78411

**Comment by BioHeidi** [comment]
Biofacies: @realfagstermer/geo 
Biokjemiske metoder: Først trenger vi en løsning på BF til strenger. 
Biosonering kan slås sammen med Biostratigrafi.

Klikket av på alle som bare kan slettes uten videre.

**Comment by grosyn** [comment]
Har no slått saman Biosonering med Biostratigrafi.

**Comment by grosyn** [comment]
Av dei som er huka av, gjenstår kun Biologiske metoder og Biopati.
