### ISSUE TITLE
Spørsmål om bruk: Algekulturer

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#730]
Reint intuitivt oppfattar eg 'algekultur' som ein planktonalgekultur (dobbeltsjekka med Ana, som har jobba med mikroalgar). Om vi tenkjer engelsk, så oppfattar eg culturing algae som om det omfattar både dyrking av mikroalgar og makroalgar. 

Eg lurer derfor på om vi kan erstatte termen med 'algedyrking', som eg på norsk oppfattar som dyrking av både mikro- og makroalgar, med ein BF algekulturer (jf andre termar der vi har slått saman prossess med produkt). Eller treng vi rett og slett separate termar for spirulina-dyrking og taredyrking? Eller for labdyrking mot industriell mat- eller fôrproduksjon?

I fanget har eg ei bok som mellom anna tar for seg makroalgedyrking....

**Comment by BioHeidi** [comment]
Jeg gjorde som du sa. Det blir nå Algedyrking BF Algekultur NN Algedyrking, Algekultur EN Algal culture, men finnes det en egen engelsk term som definerer algedyrking som ikke er algekultur?

**Comment by Hypsibius** [comment]
Ser no at Wikipedia brukar Algaculture i eitt ord på engelsk. Får også treff på alga farming, men det ser ut tilå vere mindre brukt.

**Comment by BioHeidi** [comment]
Slang på en hel haug engelske varianter :)
