### ISSUE TITLE
nyterm: hemichordater

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#731]
Nyterm: Hemichordater NN Hemichordatar La Hemichordata EN Hemichordates

Meeen, SNL/Lauritz Sømme er ikkje heilt samd med seg sjølv. Søk på Hemichordater viser til hemiKORdater, klikk på lenka tar oss til ny side med hemiCHORdater. Go figure. 

![hemik](https://cloud.githubusercontent.com/assets/9350370/24695933/08665ad8-19e8-11e7-9c83-ff66ead56bdb.PNG)
![hemich](https://cloud.githubusercontent.com/assets/9350370/24695941/0cef780a-19e8-11e7-975b-74ed206d1741.PNG)

**Comment by Hypsibius** [comment]
Og for å forvanske ytterlegare, viser SNL til hemichordatar som snabelormar, som vi har brukt for sipunkulider. 

Aktuelt verk: https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71512395050002201

**Comment by danmichaelo** [comment]
Overlater denne til @BioHeidi  :)

**Comment by BioHeidi** [comment]
Beklager forsinkelsen, den er nå opprettet med foretrukken term Hemikordater.

**Comment by danmichaelo** [comment]
@Hypsibius , vil du legge den på den aktuelle boka?

**Comment by Hypsibius** [comment]
Done!
