### ISSUE TITLE
Datadrevet vitenskap / data science

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#733]
Begynte lure på om vi trengte denne da jeg jobbet med https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBO:default_scope:BIBSYS_ILS71535695940002201

Men det er jo tidenes buzzord som kan dekke utrolig mye forskjellig, så jeg er litt usikker på om vi vil ha det som emneord. Vi har jo mange andre termer som ofte kan brukes som `Dataanalyse`, `Stordata`, `Datautvinning`, `Anvendt statistikk` osv.

**Comment by mittinatten** [comment]
Stemmer for å heller bruke mer spesifikke termer. Alle naturvitenskaper bruker vel empiriske data i noen forstand (utenom strengteoretikere og multivers-hysterikere)?

**Comment by danmichaelo** [comment]
Jeg endte opp på den samme konklusjonen. Ikke opprettet.

**Comment by danmichaelo** [comment]
Jake VanderPlas prøver seg på en definisjon i [Python data science handbook](https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBO:default_scope:BIBSYS_ILS71542119650002201):

> Data science, despite its hypeladen veener, is perhaps the best label we have for the cross-disciplinary set of skills that are becoming increasingly important in many applications across industry and academia. [...] Data science comprises three distinct and overlapping areas: the skills of a *statistician* who knows how to model and summarize datasets; the skills of a *computer scientists* who can design and use algorithms to efficiently store, process and visualize the data; and the *domain expertise* - what we might think of as "classical" training in a subject

og viser til [denne figuren](http://drewconway.com/zia/2013/3/26/the-data-science-venn-diagram). Synes fortsatt det er ullent :)

**Comment by danmichaelo** [comment]
Aldri for sent å snu. Oppdaget at vi allerede hadde `Datadrevet modellering`, så jeg endret denne til `Datavitenskap BF Datadrevet vitenskap, Datadrevet modellering`. Og la inn en liten note om at en må huske å sjekke andre termer som Dataanalyse, Stordata, Datautvinning, Anvendt statistikk osv.
