### ISSUE TITLE
Samanslåing: Hjuldyr og rotatorier

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#734]
Foreslår: 

Hjuldyr BF Rotatorier NNHjuldyr NN RotatoriUM??? (der står så, Mållaget...) LA Rotifera EN Rotifers

**Comment by Hypsibius** [comment]
![hjuldyr](https://cloud.githubusercontent.com/assets/9350370/24698833/5378b6ba-19f2-11e7-86da-2598c2bde5da.PNG)
![rotatoria](https://cloud.githubusercontent.com/assets/9350370/24698840/578bd066-19f2-11e7-9a7e-5a03d29f633b.PNG)

**Comment by danmichaelo** [comment]
Slått sammen og utflesket

(ekspressbehandling :zap: )
