### ISSUE TITLE
Bistandsarbeid og Utviklingshjelp

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#735]
[Bistandsarbeid](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Bistandsarbeid)
[Utviklingshjelp](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c009188)

Foreslår Bistandsarbeid som foretrukket term, wikipediaartikkelen om Bistand sier "Tidligere ble dette kalt utviklingshjelp, eller u-hjelp."
Kanskje påspandere en BF Bistand også?

(Påminnelse til meg selv: hvis Bistandsarbeid blir foretrukket må den få =EQ til Hume:Utviklingshjelp)

**Comment by danmichaelo** [comment]
Tenker vi tar [Internasjonal utviklingshjelp](https://app.uio.no/ub/emnesok/realfagstermer/search?term=Internasjonal%20utviklingshjelp) i samme slengen :)

**Comment by danmichaelo** [comment]
Bistandsarbeid
BF Bistand
BF Utviklingshjelp
BF Internasjonal utviklingshjelp
BF Utviklingssamarbeid
NN Bistandsarbeid
NN Utviklingshjelp
NN Internasjonal utviklingshjelp
NN Bistand
NN Utviklingssamarbeid
EN Development aid
EN Development cooperation
EN Development assistance
