### ISSUE TITLE
Elektromagnetisk stråling / bølger

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#736]
Ingen [stråling](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004705) uten [bølger](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c004995) (ihvertfall i klassisk fysikk) og vice versa. Skal vi slå de sammen @mittinatten ? Med stråling som foretrukket term?

**Comment by mittinatten** [comment]
Enig, stråling foretrukket

**Comment by danmichaelo** [comment]
Gjort!
