### ISSUE TITLE
Nyterm: Fløyelsdyr

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#737]
Foreslår: 

Fløyelsdyr BF Fløyelsormer NN Fløyelsdyr NN Fløyelsormar EN Velvet Worms LA Onychophora  

https://snl.no/fl%C3%B8yelsdyr

https://no.wikipedia.org/wiki/Fl%C3%B8yelsdyr

https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=154431#null

Aktuelt dokument https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71512396470002201

**Comment by danmichaelo** [comment]
Oppretta!
