### ISSUE TITLE
Foreslår nyterm: Bjørnedyr

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#738]
Foreslår: Bjørnedyr NN Bjørnedyr LA Tardigrada EN Tardigrads EN Water bears

https://snl.no/bj%C3%B8rnedyr

https://no.wikipedia.org/wiki/Bj%C3%B8rnedyr

Aktuelt dokument: https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71512397030002201

**Comment by danmichaelo** [comment]
Oppretta REAL031873! Beklager at det går litt treigt i redaksjonen for tiden!

**Comment by Hypsibius** [comment]
Antok dokke har andre oppgåver også :-)
