### ISSUE TITLE
Blodkar og blodårer

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#742]
Jeg kan ikke se at det er noen nevneverdig forskjell på [Blodkar](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005156) og [Blodårer](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002832)? Hvis de ikke skal slås sammen foreslår jeg å slette Blodkar.

**Comment by Hypsibius** [comment]
Slå saman!

**Comment by danmichaelo** [comment]
Slått sammen
