### ISSUE TITLE
Nyterm Størfamilien

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#746]
Foreslår Nyterm Størfamilien BF Stører NY Størar NY Størfamilien LA Acipenseridae

Brukast i SNL, men ingen eigen innførsel. 

Wikipedia brukar 'Stører', Pethon brukar 'Størfamilien'

Aktuelt dokument: https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71484636840002201

**Comment by danmichaelo** [comment]
Oppretta! REAL031874
