### ISSUE TITLE
Nyterm: Vassildfamilien

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#747]
Foreslår nyterm Vassild NY Vassild LA Argentinidae

jf SNL https://snl.no/vassildfamilien

Aktuell bok: https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71484690810002201

**Comment by danmichaelo** [comment]
Oppretta. Det skulle være `Vassildfamilien BF Vassild`, right?

**Comment by Hypsibius** [comment]
Duh! Sorry! Av og til surrar eg veldig!

**Comment by danmichaelo** [comment]
Du er ikke alene om det!
