### ISSUE TITLE
Nyterm øglefisker 

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#750]
Øglefisker NN Øglefiskar LA Synodontidae EN Lizardfishes

https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=162374#null

aktuelt dokument https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71484650130002201

**Comment by danmichaelo** [comment]
Oppretta. REAL031876 

Er "familie av egentlige beinfisker" en OK def?

**Comment by Hypsibius** [comment]
Skal vi sjå, vil gjerne ha med eit par opplysningar til: 

Foreslår:
Familie av grunntvannslevende rovfisker, tilhørende de egentlige beinfiskene

**Comment by danmichaelo** [comment]
Lagt  inn
