### ISSUE TITLE
Ny term: Mesopelagisk sone

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#751]
Foreslår Mesopelagisk sone BF Mesopelagialen BF Mesopelagialsonen NN Mesopelagisk sone EN Mesopelagic Zone

Litt i tvil om formen: Vi har Littoralsonen, abyssalsonen. Vi skulle såleis også kunne bruke mesopelagialsonen som foretrukken term 

Den svenske Nasjonalencyclopedin brukar 'Mesopelagialen'. 

http://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/mesopelagialen

Havforskinga har nokre dokument på 'Mesopelagisk sone', og snakkar breidt om mesopelagisk fisk etc. Ingen treff på andre former. 

Uio har dette dokumentet: 

http://www.mn.uio.no/ibv/tjenester/kunnskap/plantefys/leksikon/s/stratifisering.html

mesopelagisk (men kva då? mesopelagisk sone? Ellers skulle det vel vere mesopelagialen?)

Aktuelt dokument: https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71475485200002201

**Comment by danmichaelo** [comment]
Oppretta: REAL031877

Jeg synes "Mesopelagialsonen" fløt best (hehe), så jeg tok det som foretrukket term, men bare si fra hvis du heller vil ha "Mesopelagisk sone", så endrer jeg.

La til "Skumringssonen" som BF inspirert av https://sv.wikipedia.org/wiki/Mesopelagiska_zonen :) Fant termen på norsk også: http://evertebrat.b.uib.no/tag/bioluminisens/

**Comment by Hypsibius** [comment]
Meeen vi bør kanskje unngå Twilight Zone på EN?
