### ISSUE TITLE
Påvekst

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#752]
Vi har: 
![image](https://cloud.githubusercontent.com/assets/9350370/25947020/f8f9dd9a-364d-11e7-9dca-06df54cf8e67.png)

Foreslår å legge til: 

BF Begroing EN Biofouling

**Comment by danmichaelo** [comment]
Lagt til. Er "akkumulering av mikroorganismer, planter, alger eller dyr på fuktige overflater" en ok def? Fritt etter engelsk wikipedia

**Comment by Hypsibius** [comment]
Ikkje heilt. Kan vi bytte 'akkumulering' med 'vekst'? Litt uviss på kor mykje som skal til av rur, tarmgrønske eller sekkedyr for eksempel før ein kallar det ei akkumulering

**Comment by danmichaelo** [comment]
det hørtes bedre ut, ja :) Fiksa
