### ISSUE TITLE
Abborer

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#754]
Det er vel ikke nødvendig å ha både abbor og abborer?

--
URI: http://data.ub.uio.no/realfagstermer/c031689
Bruk: https://app.uio.no/ub/emnesok/realfagstermer/search?id=c031689
Soksed: https://soksed.biblionaut.net/concepts/REAL031689

**Comment by Hypsibius** [comment]
Dette er to ulike ting: 

'Abbor' er arten abbor, _Perca fluviatilis_

'Abborer' er slekta Perca, som også inkluderer den amerikanske gulabboren, i tillegg til vår europeiske

Vi har til og med 'Abborfisker' som er ein heil underorden

**Comment by olavbje** [comment]
Det var nytt for meg!

**Comment by Hypsibius** [comment]
Vi følgjer same prinsipp for andre artar/slekter :-)
