### ISSUE TITLE
Agnfiske

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#756]
Usikker på om dette er et godt begrep? 
Det applerer til sportsfiskere, men om det bør brukes som en term kan noen andre vurdere :)

--
URI: http://data.ub.uio.no/realfagstermer/c008312
Bruk: https://app.uio.no/ub/emnesok/realfagstermer/search?id=c008312
Soksed: https://soksed.biblionaut.net/concepts/REAL008312

**Comment by Hypsibius** [comment]
Fint begrep, og den hyggelegaste formen for fiske. Hvitting på rek er min favoritt ;-)

**Comment by olavbje** [comment]
Da er den tatt med!
