### ISSUE TITLE
Aktiv læring

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#757]
Her er det ingen dokumenter i katalogen

--
URI: http://data.ub.uio.no/realfagstermer/c005309
Bruk: https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005309
Soksed: https://soksed.biblionaut.net/concepts/REAL005309

**Comment by danmichaelo** [comment]
Slettet

**Comment by Hypsibius** [comment]
Kan ikkje dy meg, betyr det at det var den passive læringa som vann?
