### ISSUE TITLE
Proposisjonslogikk

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#760]
Foreslår

    Proposisjonslogikk
    EN Propositional logic
    EN Propositional calculculus
    EN Zeroth-order logic

(BF? NN?)

Belegg: http://bora.uib.no/handle/1956/12644

**Comment by danmichaelo** [comment]
Lagt inn. Tror det blir "Proposisjonslogikk" på NN også.

**Comment by danmichaelo** [comment]
Vent, vi hadde allerede `Utsagnslogikk`. Slår sammen.

**Comment by danmichaelo** [comment]
Da har vi 

```
Utsagnslogikk
BF Setningslogikk
BF Junktorlogikk
BF Proposisjonslogikk
EN ...
NN ..

```
