### ISSUE TITLE
Autøkologi

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#761]
Er det noen som har en god oversettelse til engelsk av dette uttrykket?

--
URI: http://data.ub.uio.no/realfagstermer/c001640
Bruk: https://app.uio.no/ub/emnesok/realfagstermer/search?id=c001640
Soksed: https://soksed.biblionaut.net/concepts/REAL001640

**Comment by Hypsibius** [comment]
Autecology 

https://www.britannica.com/science/autecology

**Comment by danmichaelo** [comment]
Wikipedia sier forresten "Population ecology or autecology is a sub-field..." Er det rom for sammenslåing?

**Comment by Hypsibius** [comment]
Mope!

**Comment by BioHeidi** [comment]
Nei, greit å ha autøkologi for seg, siden man der også snakker om individers samspill med omgivelsene, ikke bare populasjoner.
