### ISSUE TITLE
Kvinnelige forskere

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#763]
Se også #283 og #487.

Noen motforestillinger mot å omdøpe denne til `Kvinner i vitenskapen`?
Og legge inn SO-note fra Vitenskapsmenn/Vitenskapskvinner

**Comment by Hypsibius** [comment]
Eller 'forskere', som det også kalles ;-)

**Comment by BioHeidi** [comment]
Det ble forskere. Vi får lage strenger med kvinner som beskrevet i #487.
