### ISSUE TITLE
Dcb

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#764]
Her er det ingen poster i katalogen

--
URI: http://data.ub.uio.no/realfagstermer/c002300
Bruk: https://app.uio.no/ub/emnesok/realfagstermer/search?id=c002300
Soksed: https://soksed.biblionaut.net/concepts/REAL002300

**Comment by danmichaelo** [comment]
Det er en feil i Primo (vi henter data fra Primo API-et)... Det skal være ett dokument:

http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Dcb%22

Kan fikse lenke dit fra soksed
