### ISSUE TITLE
Flatormer

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#766]
Foreslår å legge til: EN Flatworms LA Platyhelminthes UT Bendelormer

Legge til for Bendelormer: OT Flatormer

Aktuelt dokument: https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71499896450002201

**Comment by danmichaelo** [comment]
Gjort :sun_behind_large_cloud: 

Legger man til UT sluttes OT automatisk forresten :)

**Comment by Hypsibius** [comment]
Ah. Det er jo logisk, klart dokke har tenkt på alt ;-)
