### ISSUE TITLE
Amazonas

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#768]
Ser ut som at dette emneordet både dekker elven og regnskogen. 

--
URI: http://data.ub.uio.no/realfagstermer/c030284
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer:"Amazonas"
Soksed: https://soksed.biblionaut.net/concepts/REAL030284

**Comment by Hypsibius** [comment]
Hm, om vi har dokument der det er behov for å dele, kan vi gjerne det. Ellers tenkjer eg på området som 'catchment' eller 'nedbørsfelt', altså område som drenerer inn i Amazonas: https://snl.no/nedb%C3%B8rsfelt

**Comment by danmichaelo** [comment]
Det gir mening. Tror vi beholder det som det er, slenger på definisjon og mapper til https://en.wikipedia.org/wiki/Amazon_basin
