### ISSUE TITLE
Akkvisisjon

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#769]
Kom over denne fordi den var feiltolket av oversetterne (som "datainnsamling"). Hva synes dere om å slå sammen med `Samlingsutvikling`? Eller slette? Synes det er greit å begrense antall bibliotekfagtermer litt.

--
URI: http://data.ub.uio.no/realfagstermer/c009501
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer:"Akkvisisjon"
Soksed: https://soksed.biblionaut.net/concepts/REAL009501

**Comment by Hypsibius** [comment]
Slå saman! Og dei bibliotekfagtermane vi ikkje blir kvitt, bør definerast

**Comment by danmichaelo** [comment]
Slått sammen
