### ISSUE TITLE
Avløp

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#771]
Dårlig emneord, slette? Eller omdøpe til `Avløpsvann` og legge på definisjon? (oppdatert: vi har allerede `Avløpsvann`, så sammenslåing er en mulighet)

--
URI: http://data.ub.uio.no/realfagstermer/c002753
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer:"Avløp"
Soksed: https://soksed.biblionaut.net/concepts/REAL002753

**Comment by Hypsibius** [comment]
Stemmer på omdøyping. Kan vi legge til BF Gråvann, sjølv om dette er ein snevrare term? https://snl.no/gr%C3%A5vann

**Comment by danmichaelo** [comment]
Voila (ikke Viola altså): `Avløpsvann BF Avløp BF Gråvann`
