### ISSUE TITLE
Bibliografisk verifisering

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#772]
Apropos #769. 

--
URI: http://data.ub.uio.no/realfagstermer/c005196
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer:"Bibliografisk verifisering"
Soksed: https://soksed.biblionaut.net/concepts/REAL005196

**Comment by Hypsibius** [comment]
Alt: Verifisering (Bibliotekfag) eller Verifisering (Informasjonsvitenskap)

**Comment by grosyn** [comment]
Sletter denne termen, då me bruker Humord for slike termar.
