### ISSUE TITLE
Akryllipider

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#773]
Er festet på "acyl lipids". Er akryl og acyl det samme?

--
URI: http://data.ub.uio.no/realfagstermer/c010679
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer:"Akryllipider"
Soksed: https://soksed.biblionaut.net/concepts/REAL010679

**Comment by danmichaelo** [comment]
Nei, det er jeg rimelig sikker på er en feil, fikser! Uansett et litt i overkant spisst emneord.
