### ISSUE TITLE
Aktivitetssykluser

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#774]
Foreslår å heller bruk "solar cycle" , ser ut som det er det de mener.

--
URI: http://data.ub.uio.no/realfagstermer/c005360
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer:"Aktivitetssykluser"
Soksed: https://soksed.biblionaut.net/concepts/REAL005360

**Comment by danmichaelo** [comment]
Jupp, enig! Endret den norske termen til "Solsykluser". Vi har jo også "Solaktivitet".

Husk forresten at det skal være flertallsform på engelsk der det er flertallsform på norsk.
