### ISSUE TITLE
Bøk

### ISSUE THREAD

**Issue by eirillsh** [realfagstermer/realfagstermer#775]
Vitenskapelig navn: Fagus sylvatica 

--
URI: http://data.ub.uio.no/realfagstermer/c001979
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer:"Bøk"
Soksed: https://soksed.biblionaut.net/concepts/REAL001979

**Comment by danmichaelo** [comment]
Lagt inn!
