### ISSUE TITLE
Sekkedyr

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#78]
Foreslår tillegg: bf kappedyr, tunikater Urochordata. eng: tunicates latin: Tunicata Dewey: 596.2

**Comment by bibliomari** [comment]
@BioHeidi sier at dere har konkludert, men jeg forstår ikke helt konklusjonen. Fikser du i Sonja, @BioHeidi, og lukker denne tråden?

**Comment by BioHeidi** [comment]
Ja vi slurvet litt begge to. Jeg har fikset i Sonja. Og så synes jeg dere må se dette fine bildet i wikipedia:
http://no.wikipedia.org/wiki/Kappedyr#mediaviewer/File:Salpenkette.jpg
Salper, en type kappedyr de også.
