### ISSUE TITLE
Calanider

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#780]
Et søk på Google med dette ordet gir bare henvisning til én artikkel og realfagstermer hos UiO. Det virker for meg som at dette er et konstruert/fornorsket ord. Bør det da være et emneord?

--
URI: http://data.ub.uio.no/realfagstermer/c005547
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer:"Calanider"
Soksed: https://soksed.biblionaut.net/concepts/REAL005547

**Comment by danmichaelo** [comment]
Jeg sletter. @BioHeidi : Rop ut hvis du er uenig! Brukt å ett dok: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Calanider%22

**Comment by Hypsibius** [comment]
Um, denne slomsa eg vist bort sist. Her på berget snakkar vi om calanoider eller calanoide copepodar/hoppekreps. Mistenkjer vi har masse litteratur som treng det som emneord, men får heller opprette på nytt v behov
