### ISSUE TITLE
Kryptogamer

### ISSUE THREAD

**Issue by eirillsh** [realfagstermer/realfagstermer#782]
Norsk synonym: Sporeplanter

--
URI: http://data.ub.uio.no/realfagstermer/c003173
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer:"Kryptogamer"
Soksed: https://soksed.biblionaut.net/concepts/REAL003173

**Comment by BioHeidi** [comment]
Slått sammen!
