### ISSUE TITLE
Hønsehauker

### ISSUE THREAD

**Issue by eirillsh** [realfagstermer/realfagstermer#784]
Vit. navn: Accipiter gentilis

--
URI: http://data.ub.uio.no/realfagstermer/c008547
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer:"Hønsehauker"
Soksed: https://soksed.biblionaut.net/concepts/REAL008547

**Comment by Hypsibius** [comment]
Liten korr: Skal vere eintal, sidan vi snakkar om art. Mao Hønsehauk NN Hønsehauk LA Accipiter gentilis EN Northern goshawk :-)

Fort å gå i surr, særleg no i sommarstid ;-)

**Comment by danmichaelo** [comment]
Fikset
