### ISSUE TITLE
Spurvehauker

### ISSUE THREAD

**Issue by eirillsh** [realfagstermer/realfagstermer#785]
Vit. navn: Accipiter nisus

--
URI: http://data.ub.uio.no/realfagstermer/c004218
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer:"Spurvehauker"
Soksed: https://soksed.biblionaut.net/concepts/REAL004218

**Comment by danmichaelo** [comment]
Gjort. Og rettet til entall

**Comment by Hypsibius** [comment]
EN Eurasian sparrowhawk

**Comment by Hypsibius** [comment]
EN Eurasian sparrowhawk

**Comment by danmichaelo** [comment]
Eirill har allerede lagt inn engelsk på https://soksed.biblionaut.net/concepts/REAL004218
