### ISSUE TITLE
Fjellryper

### ISSUE THREAD

**Issue by eirillsh** [realfagstermer/realfagstermer#786]
Vit. navn : Lagopus muta

--
URI: http://data.ub.uio.no/realfagstermer/c007267
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer:"Fjellryper"
Soksed: https://soksed.biblionaut.net/concepts/REAL007267

**Comment by Hypsibius** [comment]
Same korr som sist: 

Skal vere Fjellrype (eintal, vi snakkar om art)  LA  Lagopus muta EN Rock ptarmigan

Ser ut som vi har veldig mange av desse  fleirtalsformene for artar, vi får ordne etter kvart som vi oppdagar. Ser ikkje heilt korleis vi skal kunne sortere ut akkurat artasnamn for ein meir effektiv gjennomgang?

**Comment by danmichaelo** [comment]
Fikset denne nå ihvertfall.

Når alle er mappet til Wikidata kan vi liste ut emneord som er klassifisert som art der. Men for å mappe riktig til Wikidata må vi jo ta stilling til om det er en art eller noe annet, så det er litt høna og egget.. Antakelig må vi bare ordne fortløpende.

@eirillsh : Si gjerne fra når du kommer over arter som trenger retting på bokmål også.
