### ISSUE TITLE
Møre og Romsdal

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#787]
* [noubomn:"Møre" AND noubomn:"Romsdal"](http://ub-viz01.uio.no/okapi2/#/search?q=noubomn%3A%22M%C3%B8re%22%20AND%20noubomn%3A%22Romsdal%22) : 22 treff
* [noubomn:"Møre" NOT noubomn:"Romsdal"](http://ub-viz01.uio.no/okapi2/#/search?q=noubomn%3A%22M%C3%B8re%22%20NOT%20noubomn%3A%22Romsdal%22) : 1 treff
* [noubomn:"Romsdal" NOT noubomn:"Møre"](http://ub-viz01.uio.no/okapi2/#/search?q=noubomn%3A%22Romsdal%22%20NOT%20noubomn%3A%22M%C3%B8re%22) : 3 treff

Fristende å bare erstatte "Møre" og "Romsdal" med "Møre og Romsdal" siden det virker som det stort sett er det som er ment.

**Comment by Hypsibius** [comment]
Gogogo. Gjeld å forte seg før dei blir samanslått. MoR i real krise, når nordmøringane vil bli trønderar og Velstlendingane gjerne vil ha Sunnmøre ;-)

Folk austpå har ein tendens til å bruke Møre om heile greia. Folk (nord)vestpå: not so much ;-)
