### ISSUE TITLE
Eutrofiering og Eutrofe vann

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#789]
Trengs begge? @realfagstermer/bio

**Comment by Hypsibius** [comment]
Litt usikker på om vi treng spesifisere den siste. Den er også tvetydig, kan bety 'vassmassar' (med andre ord både ferskvatn og saltvatn), eller 'innsjøar'. 

Eutrofiering skjer jo i tillegg til i innsjøar både i elvar og i kystvatn. 

Og så har vi ingen dokument på det (som eg kunne finne). Berre slå saman!

**Comment by danmichaelo** [comment]
Mars-oppdateringen av Primo innførte en feil i indeksen som gjør at emnesøk ikke gir fullstendige resultater..  Asbjørn i mars:

> Dette er meldt med høy prioritet og det er lovet en fiks i juni-versjonen. Jeg prøver å pushe på for å få det raskere.

Asbjørn i juni:

> Dette er feilmeldt til Ex Libris (i begynnelsen av juni) og de har pr nå lovet en rettelse i løpet av Q4 2017. Jeg har kommentert at jeg synes det er lenge til og sagt at de må prøve å få det inn i Q3. Det er foreløpig status.

Sukk...

**Comment by danmichaelo** [comment]
Jeg har syslet litt med å hente data fra Alma istedetfor Primo, men det er ikke helt ferdig. Foreløpig bare UBO-data, men man ser ihvertfall at vi har 48 dok om `Eutrofiering`:

http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Eutrofiering%22

og ett om `Eutrofe vann`: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Eutrofe%20vann%22

**Comment by BioHeidi** [comment]
Jeg slo sammen.
