### ISSUE TITLE
Er Golfstrømmen et sted?

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#793]
[oppslag i Okapi her](http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Golfstr%C3%B8mmen%22)

@BioHeidi og jeg klarer ikke bestemme oss.

Dette er ikke ment som en eksistensiell diskusjon, men er mer av en praktisk art. Med utgangspunkt i mappinger: gir det mening å behandle Golfstrømmen som et sted, eller er det bedre å behandle det som bare en havstrøm? I utgangspunktet får alle steder relasjoner/mappinger til passende deweynummer i hjelpetabell 2, pluss et nummer underordnet geografi og et underordnet historie.. og det gir liksom ikke mening å peke brukerne til et guideboknummer for Golfstrømmen? På samme måte vil jeg tippe at de fleste dokumenter om Golfstrømmen havner på 551.462-noe under havsirkulasjon?

Dermed, to spørsmål:
1: burde Golfstrømmen være merket som sted i Realfagstermer?
2: burde Golfstrømmen mappes som et sted eller som en type havstrøm i mappingprosjektet?
(disse to tingene henger egentlig sammen, men vi kan alltids gjøre unntak)

Hvis noen kommer på noen andre naturfenomener som er på nøyaktig det samme stedet hele tiden, så hjelper det sikkert å sammenligne!

**Comment by BioHeidi** [comment]
Gardermoendeltaet, kanskje?

**Comment by Hypsibius** [comment]
Det næraste eg kan tenke på, er https://github.com/realfagstermer/realfagstermer/issues/561, men der er det kanskje meir openberrt at det skal vere ein stad? Har det for meg at vi har behandla andre parallellar tidlegare, men kjem ikkje heilt på kva

**Comment by Hypsibius** [comment]
Ah, også denne: https://github.com/realfagstermer/realfagstermer/issues/278

**Comment by danmichaelo** [comment]
Sant. Tipper vi formelt/filosofisk har vårt på det tørre om vi definerer strømmer som steder fordi de har geografisk utstrekning.. Praktisk er jeg mer usikker på om det gir mening å ha dem som fasetter på samme måte som andre steder. Vanligvis med steder vil jo ting befinne seg der og hendelser skje/inntreffe der. Søker man etter "Fisk i Akershus" vil "Fisk i Glomma" som forslag til geografisk innsnevring være greit, men søker man etter "X i Atlanterhavet", gir det mening å få opp "X i Golfstrømmen" som innsnevringsmulighet for noen X mon tro..?

**Comment by Hypsibius** [comment]
Tja, tjo, det er desse ålelarvane....

**Comment by Violabibaluba** [comment]
Enig i at det er et sted (egennavn). Vi peker vel ikke bare mot guidebøker ved å mappe som nevnt ovenfor.   Kan vel peke mot mange typer litteratur? Og lurt å følge LC. Den ligger som sted i Realfagstermer
