### ISSUE TITLE
Random matrix theory - ny term

### ISSUE THREAD

**Issue by beatekh** [realfagstermer/realfagstermer#794]
Hei,
eg er ny fagansvarleg for matematikk, informatikk og teoretisk fysikk i Bergen. Tek over for Simon. 

Ser av vi trenger en term for Random matrix (theory). 
Nokon som har forslag til oversetting? Blir Stokastisk matrise(teori) riktig? 

Belegg: https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBB:default_scope:BIBSYS_ILS71544589290002201

**Comment by Hypsibius** [comment]
Kjekt å sjå deg på GitHub :-)

**Comment by danmichaelo** [comment]
Hei og velkommen :) Alltid litt i tvil om "-teori" skal med eller ikke, men vi kan ta med begge deler som søketermer. Kanskje slik?

```
Stokastiske matriser
BF Tilfeldige matriser
DE Matrise hvis alle elementer er stokastiske variabler
BF Stokastisk matriseteori
EN Random matrices
EN Random matrix theory
NN ...
```

([hjelp til forkortelser](https://github.com/realfagstermer/realfagstermer/blob/master/CONTRIBUTING.md#forkortelser))

**Comment by mittinatten** [comment]
Virker som `Stochastic matrices` er brukt av og til på engelsk og (https://en.wikipedia.org/wiki/Random_matrix)

**Comment by beatekh** [comment]
Takk for det :)

Eg såg nettopp på om stochastic matrix og random matrix er det samme, men det kan sjå ut som random er meir generell, medan summen av radene og kolonnene i ei stokastisk matrise skal vere 1. Så det kan vere eg tok feil i det første forslaget mitt. Kva trur de? Skal vi ta Tilfeldige matriser som hovedord?

**Comment by mittinatten** [comment]
Dere med norsk som morsmål må nesten avgjøre hvor rart `Tilfeldige matriser` høres ut :)

**Comment by danmichaelo** [comment]
Ja, det er to ulike begrep vi må holde fra hverandre her.. mistenker at de lett kan blandes på engelsk også. Det var derfor jeg la på definisjon. Men kan være det er mindre sjanse for misforståelse hvis vi bruker "Tilfeldige matriser" som foretrukket term, ja. Kanskje @TorgunnKarolineMoe har en preferanse for enten "stokastisk matrise" eller "tilfeldig matrise"?

**Comment by TorgunnKarolineMoe** [comment]
Hmm.... Er ikke statistiker, så har samme bakgrunn for å vurdere dette som dere.



Hilsen Karoline

________________________________

**Comment by danmichaelo** [comment]
Ok, oppretta den (REAL031883) med `Tilfeldige matriser` som hovedterm. Det går jo alltids an å ombestemme seg senere. La på et lite drøss se-henvisninger og definisjon.
