### ISSUE TITLE
Elementmetoder

### ISSUE THREAD

**Issue by beatekh** [realfagstermer/realfagstermer#798]
Mangler engelsk. Hadde vore fint å kunne søke på "Finite elements" og "finite element methods". Passer det å legge til "Finite volume method" i samme term?

**Comment by danmichaelo** [comment]
Sant, denne har plaget meg før. Jeg tror egentlig ikke det er riktig med flertall her siden det er en metode. Ser dette greit ut?

```
Elementmetoden
BF Endelige elementers metode
NN Elementmetoden
EN Finite element method
EN Finite element analysis
EN Finite elements
AK FEM
```

Kanskje "Finite volume method" som eget begrep med se også-henvisning mellom dem? Men hva blir det på norsk da.. "Endelig volummetode BF Volummetoden`..?

**Comment by danmichaelo** [comment]
Opprettet [Endelig volummetode](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c031889), trengte den til en bok selv også nå.
