### ISSUE TITLE
Slå sammen Ammoniumnitrifikasjon og Nitrifikasjon?

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#799]
@realfagstermer/bio ? Får inntrykk av at den første termen er litt smør på flesk, jfr. http://www.mn.uio.no/ibv/tjenester/kunnskap/plantefys/leksikon/n/nitrifikasjon.html

https://soksed.biblionaut.net/concepts/REAL000423?view=mapping&q=nitrifikasjon

**Comment by Hypsibius** [comment]
Ja, kan vi ikkje det?

**Comment by danmichaelo** [comment]
Gjort!
