### ISSUE TITLE
Definisjoner

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#800]
Denne er litt teit :)

--
URI: http://data.ub.uio.no/realfagstermer/c006808
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Definisjoner%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006808

**Comment by danmichaelo** [comment]
Teit indeed! Slettet
