### ISSUE TITLE
Diastereoselektiv

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#801]
Kan kanskje slås sammen med stereoselektiv, hør med Tone :)

--
URI: http://data.ub.uio.no/realfagstermer/c005626
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Diastereoselektiv%22
Soksed: https://soksed.biblionaut.net/concepts/REAL005626

**Comment by anjamaa** [comment]
@danmichaelo

**Comment by danmichaelo** [comment]
Slått sammen
