### ISSUE TITLE
Diazoacetat

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#802]
Bør denne være i flertall?

--
URI: http://data.ub.uio.no/realfagstermer/c011639
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Diazoacetat%22
Soksed: https://soksed.biblionaut.net/concepts/REAL011639

**Comment by danmichaelo** [comment]
Ja! Men slo den like godt sammen med `Diazoforbindelser`

**Comment by danmichaelo** [comment]
(forresten, "acetater" og "acetat" er faktisk likestilte flertallsformer ser jeg nå :))
