### ISSUE TITLE
Diffeomorphisms

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#803]
Ikke norsk ord :)

--
URI: http://data.ub.uio.no/realfagstermer/c003170
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Diffeomorphisms%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003170

**Comment by mittinatten** [comment]
Tror at Diffeomorfismer er ok. (Sånn heter det på svensk i alle fall)

**Comment by anjamaa** [comment]
Kanskje @TorgunnKarolineMoe har innspill?

**Comment by TorgunnKarolineMoe** [comment]
Vi sier vel Diffeomorfier på norsk. Har ikke noe bedre ord, og jeg har brukt det / hørt det brukt en hel del.

**Comment by anjamaa** [comment]
Spurte kusina mi som også har studert matte, hun sa "-morfi" var vanlig, så tipper det er det beste. Legger noen inn "Diffeomorfier" på norsk? :)

**Comment by danmichaelo** [comment]
Fiksa! Satser på at at det blir hankjønn på nynorsk jfr. andre morfiar
