### ISSUE TITLE
Digital rights management

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#804]
Har en norsk oversettelse :)

--
URI: http://data.ub.uio.no/realfagstermer/c009013
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Digital%20rights%20management%22
Soksed: https://soksed.biblionaut.net/concepts/REAL009013

**Comment by mittinatten** [comment]
Akronymen hadde vært bra å ha med også?

**Comment by danmichaelo** [comment]
Fiksa! Akronymet hadde vi
