### ISSUE TITLE
Dimensjoner

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#805]
Dårlig ord :)

--
URI: http://data.ub.uio.no/realfagstermer/c002762
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Dimensjoner%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002762

**Comment by danmichaelo** [comment]
Slettet. La på `Ekstra dimensjoner` på et dokument. `Dimensjonsanalyse` kunne vi forsåvidt også hatt som emneord, men opprettet det ikke nå.
