### ISSUE TITLE
Dispersjon

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#806]
Må rydde litt i denne posten (blanding av kjemi/fysikk/materialer) :)

--
URI: http://data.ub.uio.no/realfagstermer/c003115
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Dispersjon%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003115

**Comment by danmichaelo** [comment]
Gjorde et forsøk på rydding. Opprettet `Van der Waalske krefter BF Dispersjonskrefter` underveis i ryddingen, siden vi manglet det.
