### ISSUE TITLE
Dissosiasjonsenergier

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#807]
Burde kanskje vært i entall?

--
URI: http://data.ub.uio.no/realfagstermer/c006491
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Dissosiasjonsenergier%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006491

**Comment by mittinatten** [comment]
Dissosiasjons(fri)energier og -konstanter er vel det samme? $k \propto \exp(-\beta \Delta E)$

Så trenger i hvert fall ikke begge, sannsynligvis ingen av de

**Comment by danmichaelo** [comment]
Enig,. Slettet begge.
