### ISSUE TITLE
Dissosiasjonskonstanter

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#808]
Burde kanskje vært i entall?

--
URI: http://data.ub.uio.no/realfagstermer/c010806
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Dissosiasjonskonstanter%22
Soksed: https://soksed.biblionaut.net/concepts/REAL010806

**Comment by mittinatten** [comment]
Kanskje ikke nødvendig som emneord?

**Comment by danmichaelo** [comment]
SLettet
