### ISSUE TITLE
Document type definition

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#809]
Burde hatt versaler i alle ord :)

--
URI: http://data.ub.uio.no/realfagstermer/c003283
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Document%20type%20definition%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003283

**Comment by danmichaelo** [comment]
Fikset!
