### ISSUE TITLE
Durchmusterung

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#81]
Særlig til @superLine  og kanskje @mittinatten ? 

Vi har tre termer med Durchmusterung. Såvidt jeg forstår er dette stjernekataloger, så de hører ikke hjemme hos oss. Forslag til løsning: Kanskje kan Cape Photographic Durchmusterung og de andre legges til som standardtittel på de respektive postene, og samme poster får eventuelt en formterm (enten som emne, altså emne stjernekataloger, eller som form, dokumentet ER altså en stjernekatalog). 

Kommentarer? 

Vi har allerede formtermen Stjernekataloger, jeg kan eventuelt legge Durchmusterungen som BF (på norsk? Eller må Knut allerede nå legge til feltet for tysk?)

**Comment by danmichaelo** [comment]
@superLine Kom du noen vei med denne? :sparkles:

**Comment by superLine** [comment]
Ja, Durchmusterung er en type stjernekatalog. Per Lilje sa det nok holdt med stjernekataloger, så BF Durchmusterung? Men stjernekataloger er jo sånn dum form-term!

**Comment by danmichaelo** [comment]
Formtermer dumme?? Neeej :yum:

**Comment by bibliomari** [comment]
IKKE dumme :) Gjort.
