### ISSUE TITLE
Elektroforetisk analyse

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#811]
Kunne denne heller vært "elektroforese"?

--
URI: http://data.ub.uio.no/realfagstermer/c010246
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Elektroforetisk%20analyse%22
Soksed: https://soksed.biblionaut.net/concepts/REAL010246

**Comment by danmichaelo** [comment]
Enig. Slått sammen
