### ISSUE TITLE
Elektrondiffraksjon

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#812]
Legg inn "elektronavbøyning" også?

--
URI: http://data.ub.uio.no/realfagstermer/c008197
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Elektrondiffraksjon%22
Soksed: https://soksed.biblionaut.net/concepts/REAL008197

**Comment by danmichaelo** [comment]
Flyttet den norske Wikipedia-artikkelen i stedet :) Tror avbøyning blir for generelt.
