### ISSUE TITLE
Erfaringer

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#813]
Dårlig term? Har én oppføring om kriseprevensjon.

--
URI: http://data.ub.uio.no/realfagstermer/c000273
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Erfaringer%22
Soksed: https://soksed.biblionaut.net/concepts/REAL000273

**Comment by anjamaa** [comment]
Slette?

**Comment by danmichaelo** [comment]
Ja, den bare var så komisk at jeg nesten ikke fikk meg til å slette den :D
