### ISSUE TITLE
Exterior

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#814]
Engelsk ord på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c000889
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Exterior%22
Soksed: https://soksed.biblionaut.net/concepts/REAL000889

**Comment by mittinatten** [comment]
Termen burde kunne slettes

**Comment by danmichaelo** [comment]
Slettet
