### ISSUE TITLE
Eksamen

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#816]
Slette? Brukt på eksamenshefter, som ikke er *om* eksamen..

--
URI: http://data.ub.uio.no/realfagstermer/c005142
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Eksamen%22
Soksed: https://soksed.biblionaut.net/concepts/REAL005142

**Comment by Hypsibius** [comment]
Slette! V behov får vi heller legge til Eksamenshefter og/eller EksamenER (flt), i det fall vi får pedagogisk litteratur som omhandlar emnet.

**Comment by danmichaelo** [comment]
Slettet
