### ISSUE TITLE
geometrisk topologi

### ISSUE THREAD

**Issue by beatekh** [realfagstermer/realfagstermer#817]
Hei, 
1)
Treng ny term:
Geometrisk topologi
Geometric topology

2)
Eg ser også at vi har to overlappande termar som burde fiksast (har vore diskutert før):
Algebraisk topologi 
Kombinatorisk topologi (bør stå som SO, i følge innlegget under)

Her er eit innlegg eg fann om termane på MATHEMATICSmeta:
_The terminology "geometric topology" as far as I'm aware is a fairly recent historical phenomenon.

The words used by topologists to describe their areas has had a fair bit of flux over the years. Before the mid-40's, algebraic topology was called combinatorial topology. I think the urge to use the phrase geometric topology began sometime after the advent of the h-cobordism theorem, and the observation that high-dimensional manifold theory, via a rather elaborate formulation can be largely turned into elaborate algebraic problems.

So there was a desire to have a term that held-together all the aspects of topology where these techniques either don't apply, or were not used (or at least, not predominantly used). That's geometric topology. So 2, 3 and 4-dimensional manifold theory would be a big chunk of this area. But of course, even if high-dimensional manifold theory in principle reduces to algebra, that doesn't necessarily mean you want to use that reduction -- it may be too complicated to be useful. So there are higher-order type high-dimensional manifold theory problems that don't fit the traditional reductions. Like say Vassiliev's work on spaces of knots. So this would also be considered geometric topology.

Defining a subject by what it's not is kind of strange and artificial but all these subject-area definitions are kind of strange and artificial. I think the above-quoted blurbs also get at a key aspect of the area. Algebraic topology tends to be more focused on a broad set of tools. Geometric topology is focused more by the goals, things like the Poincare conjecture(s) and such. So the latter tends to have a more example-oriented culture._
(https://math.meta.stackexchange.com/questions/2840/what-is-geometric-topology)

Takk!

**Comment by danmichaelo** [comment]
Beklager at det tok litt tid.

1. Opprettet: http://data.ub.uio.no/realfagstermer/c031890

2. Slått sammen: http://data.ub.uio.no/realfagstermer/c012507
