### ISSUE TITLE
Løsninger

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#818]
Tja.. Vi må ihvertfall flytte noen dokumenter til `Kjemiske løsninger`. For resten av dokumentene, holder det kanskje med form:`Oppgavesamlinger`? Eller trenger vi `Løsninger` som emneord?

--
URI: http://data.ub.uio.no/realfagstermer/c002085
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22L%C3%B8sninger%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002085

**Comment by mittinatten** [comment]
Oppgavesamlinger og "løsningshefter" er vel ikke helt det samme, men burde i hvert fall være form.

**Comment by grosyn** [comment]
Her har [NTSF ](https://www.nb.no/nbvok/ntsf/nb/) Oppgavebøker og Fasiter. Dei har henvisning frå Oppgavesamlinger til Oppgavebøker. 
Eg skal be dei ta inn Løsningsforslag som henvisningsterm til Fasiter.
