### ISSUE TITLE
Analystisk ekstraksjon

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#819]
Analystisk? Skriveleif! :)

--
URI: http://data.ub.uio.no/realfagstermer/c002685
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Analystisk%20ekstraksjon%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002685

**Comment by danmichaelo** [comment]
Man blir så lystig av å ekstrahere!

**Comment by danmichaelo** [comment]
Feilen hadde til og med blitt kopiert til nynorsk uten at den ble lagt merke til av nynorskoversetterne :) Men fikset nå

**Comment by anjamaa** [comment]
Hahaha, gøy!
