### ISSUE TITLE
Planetdannelse vs Planeter : Utvikling

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#82]
@superLine @mittinatten  Jeg tror jeg kan slå sammen disse to, og bruke bare Planetdannelse. Protester?

**Comment by superLine** [comment]
Line har våknet...  (sort of)  vi har stjerner : utvikling med 121 poster tilknyttet... -men også galaksedannelse. Litt dumt å bruke kun wikipedia som norsk referanse, men mange gode skribenter, så det er jo et godt mål på utvikling av norsk terminologi på et marginalt område. 

For alle disse fenomenene gjelder vel at "dannelse" er prosessen fra mindre partikler til en egen "enhet", mens utvikling er "enhetens" liv og levnet? Tviler imidlertid sterkt på at de gamle emneordene ble satt med slike kriterier... 

så -uhm, vi lander på?

**Comment by mittinatten** [comment]
Jeg er enig i skillet mellom dannelse og utvikling. Men, planeter utvikles ikke så mye etter at de er dannet (ting som liv og geologi skjer jo, men det regner jeg som andre felt). Stjerner har bestemte livsløp, og det gir da større mening å ha en separat term for utvikling.

**Comment by bibliomari** [comment]
Yesdone
