### ISSUE TITLE
Atomspektroskopi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#820]
Spektroskopi og spektrometri er jo ikke helt det samme, men det er få poster knytta til termen (22). Skal vi derfor bare oversette til Atomic spectroscopy og Atomic spectrometry?

--
URI: http://data.ub.uio.no/realfagstermer/c003733
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Atomspektroskopi%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003733

**Comment by danmichaelo** [comment]
Spektroskopi og spektrometri er litt vriene, de kan jo defineres på ulike måter, men ender gjerne opp med å brukes om hverandre i praksis. Jeg har pleid å følge Chemical Methods Ontology: http://purl.obolibrary.org/obo/CHMO_0000233

**Comment by anjamaa** [comment]
Lol, jeg glemte at jeg hadde oppretta denne tråden og oversatte til begge nå. Kanskje Tone har noen innspill?

**Comment by danmichaelo** [comment]
Når RSC har slått de sammen så tenker jeg at vi kan gjøre det også.
