### ISSUE TITLE
Flavoner

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#821]
Kan denne kanskje slås sammen med "Flavonoider"?

--
URI: http://data.ub.uio.no/realfagstermer/c004445
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Flavoner%22
Soksed: https://soksed.biblionaut.net/concepts/REAL004445

**Comment by danmichaelo** [comment]
De var allerede slått sammen. Kan være jeg har gjort det selv, husker ikke helt. Uansett.
