### ISSUE TITLE
Hartree-fock

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#822]
Skal egentlig skrives "Hartree–Fock", dvs. både versal F og tankestrek istedenfor bindestrek.

--
URI: http://data.ub.uio.no/realfagstermer/c005368
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hartree-fock%22
Soksed: https://soksed.biblionaut.net/concepts/REAL005368

**Comment by danmichaelo** [comment]
Takk, fikset!

**Comment by danmichaelo** [comment]
Tankestrek/bindestrek, ja... der er det nok mange synder..
