### ISSUE TITLE
Mycobakterier

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#823]
"Mykobakterier" bør vel være det norske ordet?

--
URI: http://data.ub.uio.no/realfagstermer/c009710
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Mycobakterier%22
Soksed: https://soksed.biblionaut.net/concepts/REAL009710

**Comment by danmichaelo** [comment]
Fikset, takk!
