### ISSUE TITLE
Mødre

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#824]
Bør denne slettes? Har ingen poster knytta til seg.

--
URI: http://data.ub.uio.no/realfagstermer/c009278
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22M%C3%B8dre%22
Soksed: https://soksed.biblionaut.net/concepts/REAL009278

**Comment by danmichaelo** [comment]
Slettet.

(Fantes som fritt nøkkelord på én post, men skjønner ikke hvorfor den har endt opp som Realfagsterm: https://services.bibsys.no/services/html/marcPresentation.html?mms_id=990000189614702201)
