### ISSUE TITLE
Obstetrikk

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#825]
"Obstetrikk" og "Svangerskapskomplikasjoner" er ikke synonymer?

--
URI: http://data.ub.uio.no/realfagstermer/c013958
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Obstetrikk%22
Soksed: https://soksed.biblionaut.net/concepts/REAL013958

**Comment by Hypsibius** [comment]
nei, Ordnett omset det Obstetrics med Fødselsvitskap. Tenkjer slik at fødselen er berre ein del av svangerskapet, og komplikajsonar er og berre ein (mogeleg) del av eit svangerskap. Så sjølv om det er eit overlapp, er finst det obstetrikk som ikkje er svangerskapskomplikasjonar og omvendt.

**Comment by danmichaelo** [comment]
Denne er bare brukt én gang, i strengen `Obstetrikk : Legemidler` på boka

https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBO:default_scope:BIBSYS_ILS71481666400002201

Kanskje den kunne fått `Svangerskap : Legemidler` i stedet, og så kunne vi sletta `Obstetrikk`? Skal spørre Bente som klassifiserer farmasi

**Comment by Hypsibius** [comment]
Istemmer

**Comment by danmichaelo** [comment]
Fiksa!
