### ISSUE TITLE
Oda

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#826]
Skal vel være "ODA"?

--
URI: http://data.ub.uio.no/realfagstermer/c004885
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Oda%22
Soksed: https://soksed.biblionaut.net/concepts/REAL004885

**Comment by danmichaelo** [comment]
Takk, har fikset!

Historien: I riktig gamle dager var alt i bare små bokstaver. Og så, en vakker dag (fortsatt før min tid), fikk man støtte for store og små bokstaver, og første bokstav ble automatisk gjort stor for alle termene. Og siden har vi fikset etterhvert som vi har kommet over feil.
