### ISSUE TITLE
Oksygenelektroder

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#827]
Den har ingen poster, skal vi beholde den likevel? Isåfall er kanskje denne nyttig: http://www.mn.uio.no/ibv/tjenester/kunnskap/plantefys/leksikon/o/oksygenelektrode.html

--
URI: http://data.ub.uio.no/realfagstermer/c006094
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Oksygenelektroder%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006094

**Comment by danmichaelo** [comment]
Sletter, vi kan heller gjenopprette den ved behov
