### ISSUE TITLE
Havskilpadder

### ISSUE THREAD

**Issue by eirillsh** [realfagstermer/realfagstermer#828]
| Chelonioidea
-- | --

Dette er en superfamily, skal det vært flertall eller entall da? Jeg skrev engelsk i entall, men den står i flertall

--
URI: http://data.ub.uio.no/realfagstermer/c006725
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Havskilpadder%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006725

**Comment by BioHeidi** [comment]
Riktig som det står nå, engelsk i flertall!
