### ISSUE TITLE
Organic light-emitting diode

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#829]
Skal være "organisk lysdiode" på norsk :)

--
URI: http://data.ub.uio.no/realfagstermer/c000603
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Organic%20light-emitting%20diode%22
Soksed: https://soksed.biblionaut.net/concepts/REAL000603

**Comment by danmichaelo** [comment]
Fikset, takk! :bulb:

**Comment by anjamaa** [comment]
:D
