### ISSUE TITLE
Stjernedannelse, Stjerneevolusjon, Stjerner : Utvikling, Stjerneutvikling

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#83]
@superLine @mittinatten Kan jeg slå sammen disse 4? Eller er det en nyanseforskjell mellom dannelse og utvikling/evolusjon som vi da går glipp av (det er den samme usikkerheten jeg har om planetene).

**Comment by bibliomari** [comment]
@superLine har du noen protester/kommentarer til dette?

**Comment by superLine** [comment]
Er enig med oppdeling i to, er på mobilen nå, men burde vi sjekke om vi kan koble på de siste fasene som SO også?


Line Nybakk Akerholt, Hovedbibliotekar
Realfagsbiblioteket, UiO | Science Library, University of Oslo
Epost: l.n.akerholt@ub.uio.no<mailto:l.n.akerholt@ub.uio.no>
Mob.: +47 95880018<tel:+47%2095880018>



-------- Opprinnelig melding --------
Fra: Mari Lundevall <notifications@github.com>
Dato: 05.01.2015 11.24 (GMT+01:00)
Til: realfagstermer/realfagstermer <realfagstermer@noreply.github.com>
Ko: Line Nybakk Akerholt <l.n.akerholt@ub.uio.no>
Emne: Re: [realfagstermer] Stjernedannelse, Stjerneevolusjon, Stjerner : Utvikling, Stjerneutvikling (#83)



@superLine<https://github.com/superLine> har du noen protester/kommentarer til dette?

**Comment by mittinatten** [comment]
Den eneste termen jeg finner for senere faser i stjerneutvikling er `Supernovaer`. Gir det mening å ha den som SO? Gir det mening å ha med de andre delene av utviklingen: hovedserien, vite dverger, forskjellige kjemper, etc? (Det er bare vite dverger som finnes som term.) 

For Stjernedannelse tenker jeg `SO Protostjerner` kunne funket.

(Når jeg søkte på kjemper fant jeg `Kjempefamilen` - det må være skrivefeil. I følge wikipeida skal det være `Maskeblomstfamilien BF Kjempefamilien`.)

**Comment by mittinatten** [comment]
Slenger på `Stellar utvikling`, den skal være BF på Stjerneutvikling, ikke egen term.

**Comment by bibliomari** [comment]
Takk, utført.
