### ISSUE TITLE
Organiske kjemikalier

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#830]
Kan denne slås sammen med "Organiske forbindelser"? Eller blir det dumt?

--
URI: http://data.ub.uio.no/realfagstermer/c000134
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Organiske%20kjemikalier%22
Soksed: https://soksed.biblionaut.net/concepts/REAL000134

**Comment by danmichaelo** [comment]
Jo, kan det ikke det? Kjemikalier omfatter jo også elementer, men "organiske elementer" gir vel ikke mening gitt definisjonen av organisk kjemi :) Og så er det blandinger, men hvis en bok kun handler om blandinger av kjemiske forbindelser blir det ikke veldig feil å si at den handler om kjemiske forbindelser heller.

**Comment by anjamaa** [comment]
Elementer? Som i grunnstoffer? Enig i resonnementet!

"Kjemikalier" har jo en litt sånn negativ klang over seg ("kjemikalier er skumle!!!" etc.), så jeg er generelt lite gira på ordet ;P

**Comment by danmichaelo** [comment]
Slått sammen

```
Organiske forbindelser
BF Organiske kjemikalier
```

Illustrasjonsbilde? Eh, nei, kanskje ikke..

![](http://www.blr.com/html_email/images/WIR/SDA/sda_070214.jpg)
