### ISSUE TITLE
Sauer

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#831]
Litt usikker på hva denne skal være? Skal den være i entall eller flertall på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c003652
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Sauer%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003652

**Comment by Hypsibius** [comment]
Sauer (fleirtal), oppfattar eg som saueartar, ville og tamme, i slekta Ovis (jf https://en.wikipedia.org/wiki/Ovis ), sau (eintal) oppfattar eg som tamsau, Ovis aries. 

Ser ut som dei fleste postane under denne rettferdiggjer å rette til Sau (eintal), og fjerne spesifisere: 

BF Tamsau LA Ovis aries. Ved behov kan vi legge til ulike sauerasar som BF-termar, synest ikkje det er naturleg å opprette eigne termar for desse. Men kva ligg i grunnen under terme Fjellsauer (REAL008509)?

**Comment by BioHeidi** [comment]
Beholdt sauer som Ovis sp. og la til Fjellsauer under denne. Pragmatisk nok for de få dok. :dagger:
