### ISSUE TITLE
Partikkelastrofysikk

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#832]
Kan noen legge inn "Astropartikkelfysikk"? @superLine sier det er greit :)

--
URI: http://data.ub.uio.no/realfagstermer/c005143
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Partikkelastrofysikk%22
Soksed: https://soksed.biblionaut.net/concepts/REAL005143

**Comment by danmichaelo** [comment]
Vi har jo allerede begge to hver for seg *facepalm*

**Comment by danmichaelo** [comment]
Slått sammen
