### ISSUE TITLE
Petrokjemi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#833]
Dan Michael, kan du merge den norske Wikipedia-siden til den engelske på wikidata (sikkert litt feil terminologi her, men du skjønner hva jeg mener)? Og så knytte wiki-lenka til termen :)

--
URI: http://data.ub.uio.no/realfagstermer/c004890
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Petrokjemi%22
Soksed: https://soksed.biblionaut.net/concepts/REAL004890

**Comment by danmichaelo** [comment]
Oi, de hadde fått to sider på Wikidata. Flettet (merget) de sammen nå, og ser ut som det ble riktig i Soksed med en gang :)
