### ISSUE TITLE
Polare oxider

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#834]
Skal være "Polare oksider" på norsk :)

--
URI: http://data.ub.uio.no/realfagstermer/c008649
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Polare%20oxider%22
Soksed: https://soksed.biblionaut.net/concepts/REAL008649

**Comment by danmichaelo** [comment]
Takk, fikset!
