### ISSUE TITLE
Polyetylen

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#835]
Legg inn "Polyeten" også på norsk :)

--
URI: http://data.ub.uio.no/realfagstermer/c011292
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Polyetylen%22
Soksed: https://soksed.biblionaut.net/concepts/REAL011292

**Comment by anjamaa** [comment]
Og kanskje også "PE" :)

**Comment by danmichaelo** [comment]
Sant! Bra vi ikke hadde Polyeten som eget emneord ihvertfall :D
