### ISSUE TITLE
Proteinkrystallografi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#836]
Hvorfor er disse to én post? "-krystallografi" er bestemmeles av krystallstruktur, og det er jo ikke det samme som "-krystaller".

--
URI: http://data.ub.uio.no/realfagstermer/c012868
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Proteinkrystallografi%22
Soksed: https://soksed.biblionaut.net/concepts/REAL012868

**Comment by danmichaelo** [comment]
Tipper det har vært to emneord som vi har slått sammen fordi dokumentene handlet om det samme. Men vi burde nok fjernet Proteinkrystaller etterpå. Jeg gjør det nå.

Men generelt er det ikke noe i veien for at et emneord kan dekke flere begrep, så lenge det gir mening dokumentmessig. På "Industri" (https://soksed.biblionaut.net/concepts/REAL000028?view=mapping&q=Industri,) har vi f.eks. en rekke begreper som i prinsippet kunne vært egne emneord (ser nå at det mangler oversettelser), men som har blitt slått sammen fordi dokumentene overlappet så mye.

**Comment by mittinatten** [comment]
Noe av det vanskeligste i proteinkrystallografi er å få proteinet å krystallisere, så studiet av proteinkrystaller er vel et lite delfag av proteinkrystallografi. Men tror likevel det gir mening å slette det. Tror ikke noen intresserer seg for proteinkrystaller utenfor krystallografien (ingen biologisk relevans hva jeg vet).
