### ISSUE TITLE
Protonisering

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#837]
Det korrekte norske ordet er "Protonering"?

--
URI: http://data.ub.uio.no/realfagstermer/c008958
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Protonisering%22
Soksed: https://soksed.biblionaut.net/concepts/REAL008958

**Comment by danmichaelo** [comment]
Ja! http://www.termwiki.sprakradet.no/wiki/Protonering
