### ISSUE TITLE
Puriner

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#838]
Det er noe dumt med Wiki-sidene her, de er ikke kobla (og den på bokmål er veldig dårlig).

--
URI: http://data.ub.uio.no/realfagstermer/c005420
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Puriner%22
Soksed: https://soksed.biblionaut.net/concepts/REAL005420

**Comment by danmichaelo** [comment]
Koblet! Og gjort litt nødhjelp på artikkelen. Lyst til å jobbe videre med den? :heart_eyes:

**Comment by anjamaa** [comment]
Skulle gjerne gjort det hvis jeg hadde hatt tid!
