### ISSUE TITLE
Dobbeltstjerner vs Binære dobbeltstjerner

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#84]
@superLine @mittinatten Wikipedia lenker fra norsk Dobbeltstjerne til engelsk Binary star. Vi har både Dobbeltstjerner, Binære stjerner og Binære dobbeltstjerner. Kan dette ryddes til Dobbeltstjerner BF Binære stjerner, EN Binary stars? 

(Mens Binære dobbeltstjerner slettes)?

**Comment by bibliomari** [comment]
Omsider utført. Da dukket også Formørkelsesvariable dobbeltstjerner og Nære dobbeltstjerner opp, jeg har satt SO på dem. Men de kunne kanskje vært innlemmet i Dobbeltstjerner de også. @danmichaelo @mittinatten @superLine

**Comment by mittinatten** [comment]
`Formørkelsesvariable dobbeltstjerner` er en grei term mener jeg, det handler om hvordan de oppdages (`EN Eclipsing binaries`), men legg gjerne til `SO Dobbeltstjerner` og `BF Formørkelsesvariable binære stjerner` (og slett termen `Formørkelsesvariable binære stjerner`). Det ser ut som at `Nære dobbeltsstjerner` og er et etablert konsept (`EN Close binaries`).

**Comment by bibliomari** [comment]
Flott, tusen takk @mittinatten. Fiksa.
