### ISSUE TITLE
Reaksjonskinetikk

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#840]
Kobles med "Kjemisk kinetikk"?

--
URI: http://data.ub.uio.no/realfagstermer/c003758
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Reaksjonskinetikk%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003758

**Comment by mittinatten** [comment]
Ja, tenker spontant at reaksjonskinetikk burde være foretrukket.

**Comment by danmichaelo** [comment]
Enig! Slått sammen (Reaksjonskinetikk BF Kjemisk kinetikk)
