### ISSUE TITLE
Seksualitet

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#841]
Usikker på hvilken lenke denne skal ha? Ser ut som katalogpostene er litt av hvert.

--
URI: http://data.ub.uio.no/realfagstermer/c006767
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Seksualitet%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006767

**Comment by danmichaelo** [comment]
oida..

**Comment by Hypsibius** [comment]
Hm, det er mogeleg vi kan stramme det inn v å oppgi kontekst. Som evolusjonær biolog synest eg dei fleste her forsåvidt synest (semi-)'plausible' i ein større samanheng, men det er mogeleg vi bør dele mellom seksualitet i samanhengen 'seksuell reproduksjon' og i ein meir menneskeleg/psykologisk samanheng

**Comment by danmichaelo** [comment]
Lukker siden vi har #843
