### ISSUE TITLE
Seksuell reproduksjon

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#842]
Kan denne merges med "Kjønnet formering"?

--
URI: http://data.ub.uio.no/realfagstermer/c008247
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Seksuell%20reproduksjon%22
Soksed: https://soksed.biblionaut.net/concepts/REAL008247

**Comment by Hypsibius** [comment]
Absolutt!

**Comment by danmichaelo** [comment]
Lukker denne, så kan vi diskutere videre i #866
