### ISSUE TITLE
Silika

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#844]
Kan noen legge til "Silisiumdioksid" på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c007049
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Silika%22
Soksed: https://soksed.biblionaut.net/concepts/REAL007049

**Comment by danmichaelo** [comment]
Den hadde vi som eget emneord, gitt.. Slått sammen!
