### ISSUE TITLE
Silikonforbindelser

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#845]
Skulle postene på denne heller vært kobla til "Silisiumforbindelser"? De handler ikke om silikon ;)

--
URI: http://data.ub.uio.no/realfagstermer/c010003
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Silikonforbindelser%22
Soksed: https://soksed.biblionaut.net/concepts/REAL010003

**Comment by danmichaelo** [comment]
Lol!

Sletter den bare. Er man interessert i det ene av de to dokumentene er man neppe interessert i det andre..
