### ISSUE TITLE
Sogn Og Fjordane

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#846]
Liten o i "og" :)

--
URI: http://data.ub.uio.no/realfagstermer/c030310
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Sogn%20Og%20Fjordane%22
Soksed: https://soksed.biblionaut.net/concepts/REAL030310

**Comment by danmichaelo** [comment]
Takk :)
