### ISSUE TITLE
Søsken

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#847]
Skal den engelske oversettelsen være entall eller flertall?

--
URI: http://data.ub.uio.no/realfagstermer/c004557
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22S%C3%B8sken%22
Soksed: https://soksed.biblionaut.net/concepts/REAL004557

**Comment by Hypsibius** [comment]
Fleirtal
