### ISSUE TITLE
Theta

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#848]
Kan denne slås sammen med "Thetafunksjoner"?

--
URI: http://data.ub.uio.no/realfagstermer/c000709
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Theta%22
Soksed: https://soksed.biblionaut.net/concepts/REAL000709

**Comment by danmichaelo** [comment]
Slått sammen
