### ISSUE TITLE
Time-of-flight mass spectrometry

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#850]
Kan det på norsk også legges til "TOF-massespektrometri" eller liknende? Hør med Tone? Hun har kanskje forslag på et ordentlig norsk begrep?

--
URI: http://data.ub.uio.no/realfagstermer/c001561
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Time-of-flight%20mass%20spectrometry%22
Soksed: https://soksed.biblionaut.net/concepts/REAL001561

**Comment by danmichaelo** [comment]
Mm.. mistenker at det ikke finnes noe bra norsk begrep, men skal høre med Tone. TOF-massespektrometri er uansett lurt

**Comment by danmichaelo** [comment]
Flyvetidsmassespektrometri selvfølgelig! Fiksa

**Comment by danmichaelo** [comment]
ref. "Ord og uttrykk innen MS" i Massenytt: http://www.nsms.no/info/massenytt2-05.pdf
