### ISSUE TITLE
Titan

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#851]
Denne har poster om både grunnstoffet titan og månen Titan.

--
URI: http://data.ub.uio.no/realfagstermer/c012369
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Titan%22
Soksed: https://soksed.biblionaut.net/concepts/REAL012369

**Comment by Hypsibius** [comment]
Dele opp i Titan (Kjemi) og Titan (planet)?

**Comment by danmichaelo** [comment]
Det må vi gjøre. Eller kanskje `Titan (grunnstoff)` (så man ikke tror det er [kjemi på Titan](http://sci.esa.int/cassini-huygens/59352-chemistry-in-titan-s-atmosphere/))  og `Titan (måne)` (så ikke planetene blir sure).

En oppgave for [almar](https://github.com/scriptotek/almar)

**Comment by Hypsibius** [comment]
Ouch! Sorry. Lovar å drikke meir kaffi framover!

**Comment by danmichaelo** [comment]
Har delt dem opp. Kjører almar i morgen

**Comment by danmichaelo** [comment]
Gjort
