### ISSUE TITLE
Tropisk afrika

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#852]
Stor A i "Afrika".

--
URI: http://data.ub.uio.no/realfagstermer/c009498
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Tropisk%20afrika%22
Soksed: https://soksed.biblionaut.net/concepts/REAL009498

**Comment by danmichaelo** [comment]
Fiksa!

**Comment by BioHeidi** [comment]
Må flyttes til stedterm?

**Comment by danmichaelo** [comment]
Flyttet. Og slettet `Tropisk Afrika : Afrika`!
