### ISSUE TITLE
Tunneleffekt

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#853]
Kan "Tunnelering" også legges inn på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c002485
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Tunneleffekt%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002485

**Comment by danmichaelo** [comment]
Jah!
