### ISSUE TITLE
Waaler

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#855]
Dette er etternavnet på en av forfatterne, skal det være en term?

--
URI: http://data.ub.uio.no/realfagstermer/c009241
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Waaler%22
Soksed: https://soksed.biblionaut.net/concepts/REAL009241

**Comment by danmichaelo** [comment]
Selvbiografi...? :D 

Huff, sletta
