### ISSUE TITLE
Årsakssammenheng

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#856]
Kan noen legge til "Kausalitet" på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c002184
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22%C3%85rsakssammenheng%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002184

**Comment by danmichaelo** [comment]
Slått sammen
