### ISSUE TITLE
randverdi - grenseverdi

### ISSUE THREAD

**Issue by beatekh** [realfagstermer/realfagstermer#857]
Slå sammen?

Randverdiproblemer, https://data.ub.uio.no/realfagstermer/c006216
Grenseverdiproblemer, https://data.ub.uio.no/realfagstermer/c010591

**Comment by mittinatten** [comment]
Det er to forskjellige ting faktisk

**Grenseverdi**
Hva blir f(x) da x -> a?

**Randverdi**
For eksempel: Gitt at f(x) = g(x) da x tillhører mengden A, og D(f(x)) = 0 på mengden B (D er typisk en differensialoperator), hva er da f(x) på B.

**Comment by beatekh** [comment]
Aha, takk! Er border-value problem den rette engelske termen for grenseverdi?

**Comment by TorgunnKarolineMoe** [comment]
Støtter Simon, men holder en knapp på Limit value problems.

Hilsen Karoline

**Comment by beatekh** [comment]
Takk alle sammen, oppsummert:

Grenseverdiproblemer, https://data.ub.uio.no/realfagstermer/c010591
Endre engelsk term frå Border-value problems til
EN Limit value problems

Randverdiproblemer er ok.

**Comment by danmichaelo** [comment]
Supert, fiksa!

```
Grenseverdiproblemer
EN Limit value problems
```

```
Randverdiproblemer
Boundary value problems
```
