### ISSUE TITLE
Diels-alder

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#858]
Trenger tankestrek og versal A :)

--
URI: http://data.ub.uio.no/realfagstermer/c009631
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Diels-alder%22
Soksed: https://soksed.biblionaut.net/concepts/REAL009631

**Comment by danmichaelo** [comment]
`Diels–Alder-reaksjon` (tanke, så binde), right? La på `BF Diensyntese`. Kunne muligens vært slettet, men men..

**Comment by anjamaa** [comment]
Tankestrek og så bindestrek, ja :)

Ut ifra [Wiki-artikkelen](https://en.wikipedia.org/wiki/Diels%E2%80%93Alder_reaction) ser det ikke ut som produktene nødvendigvis er diener? F.eks. reaksjonene under "Stereoselectivity". Men diener er hvert fall reaktanter i reaksjonen.

**Comment by danmichaelo** [comment]
Rart navn slik sett, ja, men jeg tok det fra https://snl.no/diensyntese . Så lenge det er i bruk kan vi ha det med.
