### ISSUE TITLE
Eikosapentaensyre

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#859]
Trengs denne? Har ingen poster.

--
URI: http://data.ub.uio.no/realfagstermer/c006595
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Eikosapentaensyre%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006595

**Comment by mittinatten** [comment]
Stemmer for slette

**Comment by danmichaelo** [comment]
Sletta!
