### ISSUE TITLE
Behov for ny term? RRI/Responsible Research and Innovation

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#86]
http://en.wikipedia.org/wiki/Responsible_Research_and_Innovation

Har vore observatør på møte i fagmiljøa, og RRI ser ut til å vere viktig buzzword for NFR for tida. Eit kjapt søk viser at "ansvarlig forskning og innovasjon" BLIR brukt, men at det ikkje ser ut til å vere same faste, etablerte term. Har vi ein gammal term alt vi kan bruke? Eller er det behov for ein ny? Korleis grip vi dette an?

**Comment by bibliomari** [comment]
Jeg kjenner ikke til om vi har en brukbar term fra før, men å ønske seg en ny term går helt fint - du må bare ha et dokument å bruke den på først.

**Comment by Hypsibius** [comment]
Jepp, dette: http://bibsys-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?docId=BIBSYS_ILS143506811&vid=UBB 

Men er framleis ikkje heilt sikker på kva term det vil vere logisk å bruke på norsk. Omsetjing eller ein anglifisert versjon (som dei faktisk brukar i fagmljøa)

**Comment by bibliomari** [comment]
Kan jeg bruke Ansvarlig forskning og innovasjon, jf http://fpol.no/nye-takter-i-europeisk-forsknings-og-innovasjonspolitikk-ansvarlig-innovasjon/ ?

@Hypsibius

**Comment by bibliomari** [comment]
Med engelsk og akronym, selvsagt.

**Comment by Hypsibius** [comment]
Ja, det synest rett!

**Comment by Hypsibius** [comment]
Heisann! Denne forsvann kanskje i heile vårreingjeringa?

**Comment by danmichaelo** [comment]
mjjaaa

**Comment by Hypsibius** [comment]
Vil fortsatt gjerne ha den, altså?

**Comment by bibliomari** [comment]
Nuh, @Hypsibius. Beklager sendrektigheten!

**Comment by Hypsibius** [comment]
Hujja!

**Comment by starseekr** [comment]
Hoi! Er denne aktuell for Reproducible research på egenhånd også? Altså uten innovasjon? Finner ikke noe annet for det - burde kanskje vært en egen en for innovasjonsfritt? Etterprøvbarhet-typeting?
