### ISSUE TITLE
Entrofiering

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#862]
Det norske ordet er "Eutrofiering" :)

--
URI: http://data.ub.uio.no/realfagstermer/c002532
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Entrofiering%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002532

**Comment by Hypsibius** [comment]
!

**Comment by danmichaelo** [comment]
Fiksa!
