### ISSUE TITLE
Erythrocyter

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#863]
Kan noen rette til "Erytrocytter" og legge til "Røde blodlegemer" og "Røde blodceller" på norsk? :)

--
URI: http://data.ub.uio.no/realfagstermer/c006886
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Erythrocyter%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006886

**Comment by Hypsibius** [comment]
Slå saman med Røde Blodceller (REAL006842)

**Comment by danmichaelo** [comment]
Gjort. Ok med `Røde blodceller` som foretrukket term?

**Comment by Hypsibius** [comment]
Eg tenkjer det?

**Comment by danmichaelo** [comment]
Zzupert
