### ISSUE TITLE
Fluoriserende proteiner

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#864]
Skriveleif! "Fluorescerende" :)

--
URI: http://data.ub.uio.no/realfagstermer/c005697
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Fluoriserende%20proteiner%22
Soksed: https://soksed.biblionaut.net/concepts/REAL005697

**Comment by Hypsibius** [comment]
? Fluoriserende er vel korrekt norsk? Eller misforsto eg? https://www.ordnett.no/search?language=no&phrase=fluoriserende

**Comment by anjamaa** [comment]
"Fluoriserende" er et norsk ord, men det har en annen betydning. Her skal det være "Fluorescerende". Er også feil på nynorskoppføringa vår.

**Comment by mittinatten** [comment]
Hva betyr fluorisere?

**Comment by mittinatten** [comment]
GFP som akronym på termen? Kan jo være noen som søker på det (og YFP, etc, vet ikke helt hvor en skal dra grensen)

**Comment by danmichaelo** [comment]
Ordnett/Riksmålsordboka: "fluorisere (verb) uheld. fluorescere.". 

Betyr "uheld." uheldig (frarådet) form? Har ikke sett det før.

Ser ut som fluoriserende er ganske mye brukt, så jeg beholder den som alternativ term (helst skulle det vært en skjult term -- søkbar, men ikke synlig -- men det har vi ikke støtte for enda).. Akseptabelt, eller får noen fnatt av det?

**Comment by danmichaelo** [comment]
@mittinatten : [Grønt fluorescerende protein](http://ub-viz01.uio.no/okapi2/#/search?q=noubomn%3A%22Gr%C3%B8nt%20fluorescerende%20protein%22) hadde vi visst fra før.. Slå sammen med [Fluorescerende proteiner](http://ub-viz01.uio.no/okapi2/#/search?q=noubomn%3A%22Fluoriserende%20proteiner%22)? Noe ønske for foretrukket term?

**Comment by mittinatten** [comment]
Kan sikkert slå sammen, sånn som jeg har forstått det er GFP den naturlige formen, fra et eller annet fluorescerende havdyr. Så har man mutert det for å få andre farger for å kunne studere flere ting samtidig i en organism. Det finnes sikkert mange andre fluorescerende proteiner som er ubeslektet, men GFP er den som er mest brukt i mikrobiologien. Men vet ikke om det fortjener en egen innførsel. I hvert fall bør `Fluorescerende proteiner` være foretrukket.

Kanskje biologene har noen innspill? @realfagstermer/bio.

Når jeg undersøkte litt, før du rakk å svare, fikk jeg inntrykket fra ordnett at Fluorisere kunde bety tilføye Fluor? Altså en annen kjemisk prosess.

**Comment by anjamaa** [comment]
Prøvde å google, det virker nesten som "fluorisere" er en uheldig spredning av en skriveleif? Et par oppføringer fra universiteter (blant annet skolelaben på IBV her, men ser ut som IBV ellers bruker "fluorescerende"), men mye avisinnlegg og skoleprosjekter. I tillegg har jo "fluorisere" et mer norsk preg over seg enn "fluorescere", så hvert fall når man hører det muntlig kan jeg tenke meg at første faller mer naturlig (med mindre man allerede kjenner til siste). Uansett enig om `Fluorescerende proteiner` som hovedterm :)

Ja, ordnett forklarer og oversetter hvert fall "fluorisere" til å tilføre fluor(id) (i vann).

**Comment by danmichaelo** [comment]
Mm, sant :)

Men ihvertfall, nå har vi

```
REAL005697
Fluorescerende proteiner
BF Fluoriserende proteiner
BF Grønt fluorescerende protein
BF GFP
```

og så kan vi jo legge til flere farger ved behov
