### ISSUE TITLE
Flusspat

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#865]
Kan noen legge til "Fluoritt" på norsk? :)

--
URI: http://data.ub.uio.no/realfagstermer/c011863
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Flusspat%22
Soksed: https://soksed.biblionaut.net/concepts/REAL011863

**Comment by danmichaelo** [comment]
Fiksa!
