### ISSUE TITLE
Fyrokjemi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#867]
Er dette faktisk et ord eller feilstaving av "Fytokjemi" (som vi har allerede)?

--
URI: http://data.ub.uio.no/realfagstermer/c003366
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Fyrokjemi%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003366

**Comment by anjamaa** [comment]
Ser at noen av postene også er tagga med "Fytokjemi" og at noen inneholder "phytochemistry" i tittelen.

**Comment by danmichaelo** [comment]
Hadde vært en morsom term hvis den fantes.. Har fiksa!
