### ISSUE TITLE
Grunnbøker

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#87]
Grunnbøker kunne vært BF på Lærebøker?

**Comment by BioHeidi** [comment]
Jeg er enig. Det er hvertfall sånn det ser ut til å være brukt.

**Comment by bibliomari** [comment]
Hm, jeg oppdager omsider at jeg ikke har tilgang til rettekommandoen for form (sjanr).

**Comment by danmichaelo** [comment]
Kanskje like greit å vente på Alma

**Comment by danmichaelo** [comment]
Nå har jeg begynt å bruke `Grunnbøker` i betydningen `Innføringsbøker`, men jeg tror egentlig det er vanskelig å holde de fra hverandre og at det er like greit å slå sammen. Vi kan endre i 655 nå.

**Comment by Hypsibius** [comment]
Er også av den oppfatning at det er vanskeleg å halde desse frå kvarandre. Typiske lærebøker har jo titlar som 'Innføring i....' eller 'Introduction to...'

**Comment by BioHeidi** [comment]
Gjort! Da er jeg spent på om @danmichaelo s magiske skript klarer jobben.
