### ISSUE TITLE
Slå saman Marin fauna (REAL001540) og Marine dyr (REAL003078)

### ISSUE THREAD

**Issue by Hypsibius** [realfagstermer/realfagstermer#871]
![image](https://user-images.githubusercontent.com/9350370/30476293-e018fb74-9a09-11e7-9889-ec82629b5244.png)

![image](https://user-images.githubusercontent.com/9350370/30476312-ef426c66-9a09-11e7-873c-14f1bc52f9e0.png)

**Comment by BioHeidi** [comment]
Oh yeah.

**Comment by BioHeidi** [comment]
Gjort
