### ISSUE TITLE
Struktur / strukturer

### ISSUE THREAD

**Issue by BioHeidi** [realfagstermer/realfagstermer#872]
Har lyst til å slette de ganske litesigende termene "Struktur" og "Strukturer" som er brukt på en mengde dokumenter av alle slag. Har skummet gjennom de lange trefflistene og synes vel stort sett det er andre termer på dokumentene allerede, som passer bedre. Rop ut om noen gjerne vil beholde "Struktur" og/eller "Strukturer", så får vi bearbeide dette litt og sette opp en note for bruk.

**Comment by danmichaelo** [comment]
Begynte å rydde unna de enkleste:

```
$ almar --rem 'Strukturer' --rem 'Proteinstrukturer' --add 'Proteinstrukturer'
9 catalog records
$ almar --rem 'Strukturer' --rem 'Molekylstruktur' --add 'Molekylstruktur'
17 catalog records
$ almar --rem 'Strukturer' --rem 'Krystallstrukturer' --add 'Krystallstrukturer'
5 catalog records
$ almar --rem 'Strukturer' --rem 'Elektronstruktur' --add 'Elektronstruktur'
3 catalog records
$ almar --rem 'Strukturer' --rem 'Kjernestruktur' --add 'Kjernestruktur'
5 catalog records
$ almar --rem 'Strukturer' --rem 'Kjemiske strukturer' --add 'Kjemiske strukturer'
6 catalog records
```

og 

```
$ almar --rem 'Strukturer' --rem 'Proteiner' --add 'Proteinstrukturer'
39 catalog records
$ almar --rem 'Strukturer' --rem 'Krystaller' --add 'Krystallstrukturer'
8 catalog records
almar --rem 'Krystallografi' --rem 'Strukturer' --add 'Krystallstrukturer'
1 catalog records
$ almar --rem 'Strukturer' --rem 'Mekanikk' --add 'Strukturmekanikk'
5 catalog records
```

Så får vi litt bedre oversikt over hva som står igjen.

**Comment by Hypsibius** [comment]
Gogogo!

**Comment by grosyn** [comment]
Strukturer har blitt flytta til Struktur, men er enig i at me bør kvitta oss med Struktur òg.

**Comment by grosyn** [comment]
Sletta Struktur. Postane det var satt på hadde andre, meir pregnante emneord.
