### ISSUE TITLE
Coercivity

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#876]
Heter det `Koersivitet` eller noe på norsk? @TorgunnKarolineMoe 

--
URI: http://data.ub.uio.no/realfagstermer/c002146
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Coercivity%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002146

**Comment by anjamaa** [comment]
@danmichaelo

**Comment by danmichaelo** [comment]
Ser riktig ut. Kanskje vi tar med `Koersitivitet` også som alternativ term.

**Comment by danmichaelo** [comment]
La på begge. Ref http://www.electropedia.org/iev/iev.nsf/display?openform&ievref=121-12-69 for den siste
