### ISSUE TITLE
Cyclodextriner

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#877]
Kan noen endre til `Syklodekstriner` (+ `Sykliske dekstriner`) på norsk?

Får forresten ikke til å legge inn Wiki-artikkelen fordi bare vitenskapelige artikler kommer opp når jeg skriver Cyclodextrin(s)? https://en.wikipedia.org/wiki/Cyclodextrin

--
URI: http://data.ub.uio.no/realfagstermer/c006648
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Cyclodextriner%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006648

**Comment by danmichaelo** [comment]
Fikset.

Det var blitt sammenblanding av alfa-syklodekstrin og syklodekstrin på Wikidata. Har ryddet.
