### ISSUE TITLE
Deweys desimalklassifikasjon

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#878]
Kan noen legge til `Deweysystemet` og `DDK` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c010233
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Deweys%20desimalklassifikasjon%22
Soksed: https://soksed.biblionaut.net/concepts/REAL010233

**Comment by danmichaelo** [comment]
Gjort
