### ISSUE TITLE
Dioxospiraner

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#879]
Burde vel egentlig vært -okso- på norsk? Ser ut som det er et veldig snevert felt (~80 treff på Google) med én oppføring, trenger vi termen i det hele tatt?

--
URI: http://data.ub.uio.no/realfagstermer/c007586
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Dioxospiraner%22
Soksed: https://soksed.biblionaut.net/concepts/REAL007586

**Comment by danmichaelo** [comment]
Heller mot sletting

**Comment by BioHeidi** [comment]
I utgangspunktet bør ikke "kun ett treff" kvalifisere til sletting, alene.
Må se litt mer på denne om den likevel skal slettes :)

**Comment by anjamaa** [comment]
Jeg foreslår ikke sletting av alle med én term, altså :) Men jeg har foreslått det på en del termer som er så spesifikke at katalogpostene bør ha dem i tittelen.

**Comment by danmichaelo** [comment]
Slettet. 9 treff i google scholar blir litt for snevert til at det funker som emneord.
