### ISSUE TITLE
Hidden Markov Models

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#88]
Skal Hidden Markov models være `Skjulte Markovmodeller` på norsk? 

Belegg http://ask.bibsys.no/ask/action/show?kid=biblio&cmd=reload&pid=090035798

**Comment by bibliomari** [comment]
Gjerne for meg. Hvordan forholder dette seg til Markovmodeller - vi har endel emneord med Markov allerede. Gir det mening å bruke Markovmodeller, BF Skjulte Markovmodeller, eller oppretter jeg et eget med SO mellom? @mittinatten

**Comment by mittinatten** [comment]
Jeg mener det fortjener å være en egen term med SO, men hadde gjerne hatt innspill på hva som er en god norsk term.

**Comment by bibliomari** [comment]
Ja, jeg for min del synes den er knallgod, men jeg vet jo ikke hva det handler om. @knuthe er jo en språkets mann.

**Comment by mittinatten** [comment]
Jeg googlet litt og det ser ut som skjulte markovmodeller blir brukt en del i Norge. (med eller uten bindestrekk mellom markov og modeller).

**Comment by bibliomari** [comment]
Laget.
