### ISSUE TITLE
Enterotoxiner

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#880]
`Enterotoksiner` på norsk :)

--
URI: http://data.ub.uio.no/realfagstermer/c007435
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Enterotoxiner%22
Soksed: https://soksed.biblionaut.net/concepts/REAL007435

**Comment by danmichaelo** [comment]
Fiksa!
