### ISSUE TITLE
European Space Agency

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#881]
Skal vi legge til den norske oversettelsen også? Usikker på hvor mye den er i bruk? @superLine 

--
URI: http://data.ub.uio.no/realfagstermer/c006835
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22European%20Space%20Agency%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006835

**Comment by danmichaelo** [comment]
Denne må også flyttes til BARE (Bibsys autoritetsregister for personer, organisasjoner og sånt), la den til i #255
