### ISSUE TITLE
Foraminiferer

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#882]
Kan noen legge til `Poredyr` på norsk? :)

--
URI: http://data.ub.uio.no/realfagstermer/c006933
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Foraminiferer%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006933

**Comment by danmichaelo** [comment]
Lagt til som alternativ term. @BioHeidi : Bytt om hvis du synes det bør være foretrukket.
