### ISSUE TITLE
Hjernehinnebetennelse

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#884]
Kan noen legge til `Meningitt` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c009716
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hjernehinnebetennelse%22
Soksed: https://soksed.biblionaut.net/concepts/REAL009716

**Comment by danmichaelo** [comment]
Ja!
