### ISSUE TITLE
Hvaler

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#885]
Trengs en opprydning på katalogpostene :)

--
URI: http://data.ub.uio.no/realfagstermer/c030459
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hvaler%22
Soksed: https://soksed.biblionaut.net/concepts/REAL030459

**Comment by danmichaelo** [comment]
OBS: Her kan det også være feil i søket, skal sjekke

**Comment by Hypsibius** [comment]
Nyskjerrig, kva var problemet?  Er det fiksa? Mykje støy, men kvalar galore....

**Comment by Hypsibius** [comment]
Om det då ikkje er stadtermen dokke skulle ha...

**Comment by danmichaelo** [comment]
Tror ikke Okapi skilte mellom ulike MARC-felt. Har satt i gang en reindeksering, men det tar litt tid.

**Comment by anjamaa** [comment]
@Hypsibius Denne termen skulle være stedet, ja, men det var veldig mange dyr blant katalogpostene :(

**Comment by danmichaelo** [comment]
@anjamaa Mm, men det er en feil i søket (Okapi), ikke i katalogpostene :)

**Comment by Hypsibius** [comment]
Ah, Hvaler, mitt sommarparadis!

**Comment by danmichaelo** [comment]
Det var faktisk rot i katalogpostene :/ Har rydda med almar!
