### ISSUE TITLE
Homologi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#886]
Denne har hvert fall én katalogpost som må overføres til `Biologisk homologi`.

--
URI: http://data.ub.uio.no/realfagstermer/c005651
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Homologi%22
Soksed: https://soksed.biblionaut.net/concepts/REAL005651

**Comment by anjamaa** [comment]
Hadde det vært mulig å endre termene til `Homologi (biologi)` og `Homologi (matematikk)` eller noe, à la diskusjonen rundt `Titan`?

**Comment by danmichaelo** [comment]
Gjort! Flyttet det ene dokumentet. De andre ser greie ut. Slo sammen `Homologi (matematikk) BF Homologiteori`
