### ISSUE TITLE
Humangeografi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#887]
Tror "Humangeografi" er dansk? Kan denne slås sammen med `Samfunnsgeografi` (og droppe `Humangeografi`)?

--
URI: http://data.ub.uio.no/realfagstermer/c011730
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Humangeografi%22
Soksed: https://soksed.biblionaut.net/concepts/REAL011730

**Comment by danmichaelo** [comment]
Humord har valgt å innlemme det i `Samfunnsgeografi`, men beholdt termen: https://app.uio.no/ub/emnesok/humord/search?id=c09019

Det er kanskje ikke helt usannsynlig at termen har vært brukt på norsk også hvis den brukes på dansk, så kanskje vi skal beholde den som søkehjelp?

**Comment by anjamaa** [comment]
Ah, da kan vi gjøre det samme, ja :)

**Comment by danmichaelo** [comment]
Og da har vi gjort det :)
