### ISSUE TITLE
Hallusinogener

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#888]
Er ikke -cinogener dansk og svensk?

--
URI: http://data.ub.uio.no/realfagstermer/c012804
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hallusinogener%22
Soksed: https://soksed.biblionaut.net/concepts/REAL012804

**Comment by danmichaelo** [comment]
Du tenker på den alterative termen? Skader kanskje ikke at det er søkbart. Noen som er 90 år kan kanskje finne på å skrive det slik..?

**Comment by danmichaelo** [comment]
@anjamaa ?

**Comment by anjamaa** [comment]
Skulle vi ikke spare på gamle skrivemåter av hensyn til gæmlizene? ;P

**Comment by danmichaelo** [comment]
Jo, jeg bare hadde et spørsmålstegn der ;) Men da gjør vi det!
