### ISSUE TITLE
Kjempefamilien/maskeblomstfamilien

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#89]
@BioHeidi 

@mittinatten sier i #83: Når jeg søkte på kjemper fant jeg Kjempefamilen - det må være skrivefeil. I følge wikipeida skal det være Maskeblomstfamilien BF Kjempefamilien.

Jeg tør ikke gjøre noen endringer her, SNL har innførsel på begge to og med hver sitt vitenskapelige navn. Kan du fikse, Heidi?

**Comment by danmichaelo** [comment]
Hovedpoenget var nok at det manglet en "i" i [*Kjempefamilen*](http://data.ub.uio.no/realfagstermer/009128.html) ;)

**Comment by BioHeidi** [comment]
Fikset!
