### ISSUE TITLE
Lavoisier

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#890]
Slette (person)?

--
URI: http://data.ub.uio.no/realfagstermer/c009185
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Lavoisier%22
Soksed: https://soksed.biblionaut.net/concepts/REAL009185

**Comment by danmichaelo** [comment]
Ja!

**Comment by danmichaelo** [comment]
TODO: Legge til 610 $$a Antoine Laurent Lavoisier $$0 90210745
