### ISSUE TITLE
Meiose

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#891]
Kan noen legge til `Reduksjonsdeling` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c005515
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Meiose%22
Soksed: https://soksed.biblionaut.net/concepts/REAL005515

**Comment by danmichaelo** [comment]
Gjort
