### ISSUE TITLE
Svarte (folkegrupper)

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#892]
Denne er jo litt ... ja. Skal vi slette eller beholde (én katalogpost)?

--
URI: http://data.ub.uio.no/realfagstermer/c003932
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Svarte%20(folkegrupper)%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003932

**Comment by danmichaelo** [comment]
Øh, ja, folkegruppe blir uansett feil. Hvis vi skulle hatt et erstatningsemneord her måtte det kanskje vært noe ála WP sin "[Race and sports](https://en.wikipedia.org/wiki/Race_and_sports)".. Men vi snakker jo ikke om rase på samme måte som de gjør i Sambandsstatene, så tror ikke vi kan oversette direkte. Kanskje noe ála "Gener og idrett"? 

Vi kan også bare slette den. Dette er jo litt utenfor Realfagstermer kjerneområde og ikke noe vi trenger å bruke all verdens tid på.

**Comment by Hypsibius** [comment]
Den er definitivt ' litt ... ja',. Og vi snakkar ikkje om racial identity på same måte i Noreg som i USA. På den andre side, ved å fjerne alle emneord, fjernar vi og ein reiskap for å finne dokument som omhandlar diskriminering og over-/underrepresentasjon av visse folkegrupper i utdanning/politisk liv/politi and what have you. Gener og idrett bringer i alle fall meg over på tanken om ulike typer muskelceller fordelaktige for hhv spurt og langdistanse, evt. designerbaby-tenking. 

Har ingen veldig gode forslag, men ser at HUMORD brukar raseidentitet https://app.uio.no/ub/emnesok/humord/search?id=c08133. 

Alternativt kunne vi snakke, heller enn om ei spesifikk folkegruppe, om Folkegrupper evt Befolkningsgrupper. 

På den måten kan vi generalisere og samtidig ha ein term som ved behov kan kombinerast med Diskriminering, som vi forøvrig ikkje har. Vi hadde, men det betaud tydelegvis noke anna ;-)

**Comment by BioHeidi** [comment]
Denne diskuteres i deweyutvalget også, på sitt vis, der blir norske termer foreslått endret til "Afrikanere og personer av afrikansk opprinnelse", samt afroamerikanere der den engelske sier African americans.

**Comment by Hypsibius** [comment]
Men det handlar jo heller ikkje om nødendigvis om folk m afrikansk herkomst. Diskriminering på basis av intens pigmentering skjer mot australske urinvånarar, folk frå enkelte stillehavsøyar og ein del med indisk opphav. På grunn av felles problemstilling og identifikasjon på tvers av genetisk opphav, identifiserer fleire grupper seg som 'blacks', og endå meir som 'browns'.

**Comment by danmichaelo** [comment]
Det strandet litt på å finne en ny term til den ene boka, men nå fant jeg strengen [Genetisk variasjon : Mennesket](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c003932), som jeg tror kan passe (?) Hvis noen kommer på noe enda lurere er det bare å fikse!
