### ISSUE TITLE
Fleratomige molekyler

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#893]
Tja, jeg antar begrepet har oppstått fordi det innenfor teoretisk kjemi er tyngre å jobbe med molekyler med flere atomer, men de fleste molekyler har jo flere atomer så det blir samtidig en veldig rar term, spesielt når den står for seg selv.. Og når den bare er brukt på fire dokumenter synes jeg like godt vi kan slette den. Enig?

--
URI: http://data.ub.uio.no/realfagstermer/c000815
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Fleratomige%20molekyler%22
Soksed: https://soksed.biblionaut.net/concepts/REAL000815

**Comment by mittinatten** [comment]
Innstemmer

**Comment by danmichaelo** [comment]
Slettet
