### ISSUE TITLE
Chironomider

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#894]
Slå sammen med `Fjærmygg`? Virker som samme greia :)

--
URI: http://data.ub.uio.no/realfagstermer/c001366
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Chironomider%22
Soksed: https://soksed.biblionaut.net/concepts/REAL001366

**Comment by anjamaa** [comment]
@BioHeidi

**Comment by Hypsibius** [comment]
Jepp! Og legg til BF Fjørmygg

**Comment by BioHeidi** [comment]
Og LA Chironomidae. Her er det likevel greit å beholde termen som BF fordi vi fornorsker det slik.

(Tror forresten NN Fjørmygg ligger på allerede)

**Comment by BioHeidi** [comment]
Forresten, er det riktig nynorske termer på den? Chironomider på bokmål er Chironomid på nynorsk?

**Comment by Hypsibius** [comment]
Definitivt ikkje. Ville gått for NN Chironomidar (hankjønn)
