### ISSUE TITLE
Kjemotaksonomi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#896]
Slå sammen med `Kjemisk taksonomi`?

--
URI: http://data.ub.uio.no/realfagstermer/c006740
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kjemotaksonomi%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006740

**Comment by danmichaelo** [comment]
Gjort!
