### ISSUE TITLE
Kloroform

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#897]
Legge til `Triklormetan` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c011406
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kloroform%22
Soksed: https://soksed.biblionaut.net/concepts/REAL011406

**Comment by danmichaelo** [comment]
Gjort!
