### ISSUE TITLE
Konstruksjon av tabeller

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#898]
What, slette?

--
URI: http://data.ub.uio.no/realfagstermer/c013355
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Konstruksjon%20av%20tabeller%22
Soksed: https://soksed.biblionaut.net/concepts/REAL013355

**Comment by danmichaelo** [comment]
:dizzy_face: 

Slettet (sjekka at den ikke hadde MSC)
