### ISSUE TITLE
Linné

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#900]
Slette?

--
URI: http://data.ub.uio.no/realfagstermer/c006627
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Linn%C3%A9%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006627

**Comment by BioHeidi** [comment]
Var ikke han en slags person? Eller var han en kryptogam... ( @Violabibaluba kan du flytte denne til personer)

**Comment by Hypsibius** [comment]
https://upload.wikimedia.org/wikipedia/commons/7/7e/Twinflower.jpg

**Comment by anjamaa** [comment]
`Linné` ligger fortsatt i soksed, er han på vei ut?

**Comment by danmichaelo** [comment]
Sånn, borte!
