### ISSUE TITLE
Lykkepiller

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#901]
Skal termen ha dette navnet?

--
URI: http://data.ub.uio.no/realfagstermer/c013861
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Lykkepiller%22
Soksed: https://soksed.biblionaut.net/concepts/REAL013861

**Comment by mittinatten** [comment]
Helst ikke vel :) Slå sammen med `Antidepressiva`?

**Comment by danmichaelo** [comment]
Vi hadde `Selektive serotoninopptakere` også, så jeg begynte med å slå sammen med dem. Men ja, antakelig like greit å slå sammen med Antidepressiva også mtp. størrelsen på dokumentbelegget vårt. Kan heller skilles ut som eget begrep ved behov.
