### ISSUE TITLE
Metal-oxide semiconductor

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#902]
Finne norsk oversettelse? Eller slette?

--
URI: http://data.ub.uio.no/realfagstermer/c011606
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Metal-oxide%20semiconductor%22
Soksed: https://soksed.biblionaut.net/concepts/REAL011606

**Comment by danmichaelo** [comment]
Slått sammen med MOSFET
