### ISSUE TITLE
Metall-metallbindinger

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#903]
Slette?

--
URI: http://data.ub.uio.no/realfagstermer/c013733
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Metall-metallbindinger%22
Soksed: https://soksed.biblionaut.net/concepts/REAL013733

**Comment by danmichaelo** [comment]
Ikke i bruk (sjekket i Alma også), slettet
