### ISSUE TITLE
Metallothionein

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#904]
Slette?

--
URI: http://data.ub.uio.no/realfagstermer/c005293
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Metallothionein%22
Soksed: https://soksed.biblionaut.net/concepts/REAL005293

**Comment by BioHeidi** [comment]
Nei, beholde.

**Comment by danmichaelo** [comment]
Ferdig diskutert? Lukke saken?

**Comment by danmichaelo** [comment]
Beholdt

**Comment by danmichaelo** [comment]
Endret til `Metallotionein` som foretrukket term
