### ISSUE TITLE
Monosakkarider

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#905]
Legge til `Enkle sukkerarter` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c011098
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Monosakkarider%22
Soksed: https://soksed.biblionaut.net/concepts/REAL011098

**Comment by danmichaelo** [comment]
God idé, gjort!
