### ISSUE TITLE
Mr-tomografi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#906]
Slå sammen med `Magnetresonanstomografi` og legge til `MRI` på engelsk (den andre er låst)?

--
URI: http://data.ub.uio.no/realfagstermer/c002921
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Mr-tomografi%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002921

**Comment by anjamaa** [comment]
Og selvfølgelig rette til `MR-tomografi`! :)

**Comment by danmichaelo** [comment]
Hehe, gjort :) Rart, jeg hadde liksom et minne om å ha fikset denne før, men det må ha vært noe helt annet
