### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#907]
Rette til `MySQL` på norsk :)

--
URI: http://data.ub.uio.no/realfagstermer/c008209
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Mysql%22
Soksed: https://soksed.biblionaut.net/concepts/REAL008209

**Comment by danmichaelo** [comment]
Fiksa!
