### ISSUE TITLE
Oksygenaser

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#909]
Klarer noen å legge inn [denne](https://en.wikipedia.org/wiki/Oxygenase)? Den kommer ikke opp når jeg prøver, bare spesifikke oksygenaser :(

--
URI: http://data.ub.uio.no/realfagstermer/c007775
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Oksygenaser%22
Soksed: https://soksed.biblionaut.net/concepts/REAL007775

**Comment by danmichaelo** [comment]
Hm, ja, søket på Wikidata har litt forbedringspotensial :) Et tips, @anjamaa : Hvis du finner artikkelen på Wikipedia og trykker på "Edit links" eller "Rediger lenker" under språklista i venstremargen, så kommer du til Wikidata. Der finner du en "Q-kode" (en unik ID som alltid begynner med Q), som du kan kopiere over. I dette tilfellet: Q419615
