### ISSUE TITLE
Anvendt topologi

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#91]
Foreslår termen 

    Anvendt topologi
    EN Applied topology
    NN Kan vi bruke 'anvendt' her?

Belegg: http://ask.bibsys.no/ask/action/show?kid=biblio&cmd=reload&pid=150060882

**Comment by bibliomari** [comment]
Gjort. Usikker på nynorsken, lar den ligge til ekspertene.
