### ISSUE TITLE
Nervesystemet

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#911]
Endre til flertall? Med entall virker det som vi ønsker å avgrense til mennesket, men det er vel kanskje ikke egentlig ønskelig her?

--
URI: http://data.ub.uio.no/realfagstermer/c008424
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Nervesystemet%22
Soksed: https://soksed.biblionaut.net/concepts/REAL008424

**Comment by Hypsibius** [comment]
Mmmmm, i tvil. Behandlast slik i Dewey, også i komparativ anatomi. For meg kan vi godt behalde. Men klart, med meitemark med fem hjarte (eller var det ti) kan det vere vanskeleg å sknakke om 'hjertet' ;-) Dog konvensjon

**Comment by BioHeidi** [comment]
Kan godt beholdes slik. Jeg som ikke umiddelbart tenker (som et) menneske har ingen problemer med å like gjerne se for meg et gangliesystem eller diffust hydrasystem her.

**Comment by danmichaelo** [comment]
Ok, da beholder vi bare
