### ISSUE TITLE
Naturmedisin

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#912]
Hvordan avgrense mot `Folkemedisin`? Slå sammen eller legge på definisjon?

Tenkte først at `Naturmedisin` kanskje var avgrenset til medisinplanter og sånt, men ser at vi har et eget emneord for det: `Medisinplanter BF Medisinske planter BF Legeurter BF Urtemedisin BF Legeplanter`

--
URI: http://data.ub.uio.no/realfagstermer/c007828
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Naturmedisin%22
Soksed: https://soksed.biblionaut.net/concepts/REAL007828

**Comment by Hypsibius** [comment]
Hadde vi ikkje også ei anna sak på det?

**Comment by danmichaelo** [comment]
Jo! #127 

Kopierer teksten over dit
