### ISSUE TITLE
Black-scholes modell

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#913]
Trenger tankestrek og så bindestrek på norsk + versal S :)

--
URI: http://data.ub.uio.no/realfagstermer/c004059
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Black-scholes%20modell%22
Soksed: https://soksed.biblionaut.net/concepts/REAL004059

**Comment by danmichaelo** [comment]
Fiksa!
