### ISSUE TITLE
Byssustråder

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#914]
Slette eller beholde? Hvis beholde, er `Byssus filaments` riktig oversettelse, @BioHeidi?

--
URI: http://data.ub.uio.no/realfagstermer/c000243
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Byssustr%C3%A5der%22
Soksed: https://soksed.biblionaut.net/concepts/REAL000243

**Comment by Hypsibius** [comment]
Forstår det slik at Okapi er ustadig i øyeblikket og trefflista kan vere misvisande. Foreslår å behalde, så skal eg sjekke om det evt er andre dokument som treng termen

Trur korrekt omsetjing til engelsk berre er Byssus (som er filamentøst)

**Comment by BioHeidi** [comment]
Denne termen er visst slettet, men jeg fant ingen dok som jeg tror den kan passe på, har dere bruk for den vestpå?

**Comment by Hypsibius** [comment]
Ser ikkje slik ut. Meinte det fanst nokre oppgåver på temaet, men ingenting å finne i katalogen. Så då har eg ingen stad å putte emneorda heller.  Får legge inn ev ved behov!
