### ISSUE TITLE
Cepheider

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#915]
Ser ut som det skal være `Kefeider` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c008908
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Cepheider%22
Soksed: https://soksed.biblionaut.net/concepts/REAL008908

**Comment by danmichaelo** [comment]
Vi trenger ihvertfall ikke begge som separate emneord :O

Og sannelig har ikke  Språkrådet gjort et norvagiseringsvedtak for "kefeide" i 2004 :) http://www.sprakradet.no/localfiles/8181/kkdframlegg04a.pdf
