### ISSUE TITLE
Circa instans

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#916]
Det ser ut som `Circa instans` er tittelen på et verk? https://en.wikipedia.org/wiki/Matthaeus_Platearius
Slette?

--
URI: http://data.ub.uio.no/realfagstermer/c008642
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Circa%20instans%22
Soksed: https://soksed.biblionaut.net/concepts/REAL008642

**Comment by danmichaelo** [comment]
Korrekt! Beklager problemer med Okapi i går, men det var denne: https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlSearch.do?institution=UBO&vid=UBO&search_scope=bibsys_ils&query=any,contains,990005447954702201

**Comment by danmichaelo** [comment]
Slettet
