### ISSUE TITLE
Diadromi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#917]
Inne på Wikidata og ved siden av lenken til engelsk Wikipedia-side står det "Anadromi" på norsk, men det er bare én type diadromi. Er det mulig å rette opp?

--
URI: http://data.ub.uio.no/realfagstermer/c004034
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Diadromi%22
Soksed: https://soksed.biblionaut.net/concepts/REAL004034

**Comment by Hypsibius** [comment]
I Wikipedia, meinar du? Eller tenkte du å legge inn både katadromi og anadromi?

**Comment by danmichaelo** [comment]
> Inne på Wikidata og ved siden av lenken til engelsk Wikipedia-side står det "Anadromi" på norsk, men det er bare én type diadromi. Er det mulig å rette opp?

Egentlig bare å trykke "Edit" til høyre over boksen, så er du i gang (trenger ikke logge inn), men gjorde det nå.

Meen ja, skulle vi hatt med flere termer også? Er [fiskevandring](https://sv.wikipedia.org/wiki/Fiskvandring) en term som burde vært her eller der eller blir det for folkelig? @realfagstermer/bio

**Comment by Hypsibius** [comment]
Mtja, i så fall ville eg trenge ein streng, migrasjon: fisker, for å omfatte døgnvandringar, sesongvandringar, næringsvandringar og gytevandringar.

**Comment by anjamaa** [comment]
Drar frem denne igjen siden det er relatert! Ser at vi har både `Anadromi` og `Anadrome fisker`, kan de slås sammen? Og eventuelt legge til `Katadromi` på den eksisterende `Katadrome fisker`?

**Comment by danmichaelo** [comment]
@realfagstermer/bio ?

**Comment by Hypsibius** [comment]
Synest vi slår saman til Anadromi BF anadrome fisker, Endrar Katadrome fisker til BF, og legg inn Katadromi som hovudterm. OT Diadromi SO Migrasjon

**Comment by danmichaelo** [comment]
Ok, da har jeg fiksa!

```
Anadromi
BF Anadrome fisker
OT Diadromi
```

```
Katadromi
BF Katadrome fisker
OT Diadromi
```

```
Diadromi
SO Migrasjon
...(osv.)
```
