### ISSUE TITLE
Dibensodioksiner

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#919]
Rette til `Dibenzodioksiner` eller slette?

--
URI: http://data.ub.uio.no/realfagstermer/c005674
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Dibensodioksiner%22
Soksed: https://soksed.biblionaut.net/concepts/REAL005674

**Comment by BioHeidi** [comment]
Rette, og slå sammen med Dioksiner.

**Comment by BioHeidi** [comment]
Gjort
