### ISSUE TITLE
Programmeringsspråk

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#92]
Finnes det en grunn til at det heter Cspråk, Rspråk, etc og ikke `C (språk)`, `R (språk)` @knuthe?

**Comment by knuthe** [comment]
Ja. :-) Jeg tror det er nevnt tidligere også. Det ligger i historien. På Informatikkbiblioteket måtte vi lage  ord som gjorde det mulig å finne igjen bøker om disse språkene i et system som ikke klarte å søke på én bokstav (evt i kombinasjon med andre ord). Systemet kunne heller ikke takle C++ og C# (derfor cplusplus og csharp). Jeg er åpen for å finne andre løsninger, men først når jeg føler meg trygg på at de nye systemene er i stand til å takle det.

**Comment by mittinatten** [comment]
Ok, da skjønner jeg, lukker denne inntil videre.

**Comment by danmichaelo** [comment]
Duplikat av #27

**Comment by mittinatten** [comment]
Det burde jeg ha husket :)
