### ISSUE TITLE
Dioscorides

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#920]
Slette? Det er en person.

--
URI: http://data.ub.uio.no/realfagstermer/c007944
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Dioscorides%22
Soksed: https://soksed.biblionaut.net/concepts/REAL007944

**Comment by danmichaelo** [comment]
Sletta. La inn 600-innførsel i stedet (BARE)
