### ISSUE TITLE
Elektromyografi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#921]
Legge til `EMG` på norsk også?

--
URI: http://data.ub.uio.no/realfagstermer/c004907
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Elektromyografi%22
Soksed: https://soksed.biblionaut.net/concepts/REAL004907

**Comment by danmichaelo** [comment]
Ggjort
