### ISSUE TITLE
Hedmarkbassenget

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#922]
Trenger vi emner som ikke har noen katalogposter?

--
URI: http://data.ub.uio.no/realfagstermer/c031002
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hedmarkbassenget%22
Soksed: https://soksed.biblionaut.net/concepts/REAL031002

**Comment by BioHeidi** [comment]
Nei, slettes

**Comment by danmichaelo** [comment]
Okapi har fortsatt ikke fått helt kontroll på stedtermene, det er egentlig brukt på ett dokument: http://ub-viz01.uio.no/okapi2/#/search?q=990601256914702201

**Comment by BioHeidi** [comment]
aha, ok... da beholder vi den foreløpig.
