### ISSUE TITLE
Heliosat

### ISSUE THREAD

**Issue by jeanetvi** [realfagstermer/realfagstermer#924]
Ingen katalogposter tilknyttet søkeordet.

--
URI: http://data.ub.uio.no/realfagstermer/c008794
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Heliosat%22
Soksed: https://soksed.biblionaut.net/concepts/REAL008794

**Comment by danmichaelo** [comment]
Jo, én, jeg måtte bare fikse Okapi... Men uansett greit at du nevnte denne fordi den skal flyttes til et annet felt (#255)
