### ISSUE TITLE
Ephemeroptera

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#925]
Slå sammen med `Døgnfluer` :)

--
URI: http://data.ub.uio.no/realfagstermer/c003552
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Ephemeroptera%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003552

**Comment by BioHeidi** [comment]
En klassiker! @bibliomari husker du efemeridene?
Er bare å slå sammen ja, men fjerne Ephemeroptera fra BF, den ligger som latin til Døgnfluer.

**Comment by BioHeidi** [comment]
Gjort
