### ISSUE TITLE
Fermat

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#926]
Person, slette?

--
URI: http://data.ub.uio.no/realfagstermer/c000816
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Fermat%22
Soksed: https://soksed.biblionaut.net/concepts/REAL000816

**Comment by danmichaelo** [comment]
Lol, vi hadde også `Siste teorem` som eget emneord. Slo dem sammen til `Fermats siste teorem` jeg :D
