### ISSUE TITLE
Fysisk krystallografi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#927]
Er "fysisk krystallografi" en greie? Katalogposten handler om fysiske egenskaper hos krystaller? Slette?

--
URI: http://data.ub.uio.no/realfagstermer/c002583
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Fysisk%20krystallografi%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002583

**Comment by danmichaelo** [comment]
Kanskje det er en vri på [krystallfysikk](https://snl.no/krystallfysikk)? (en term jeg forresten heller ikke hadde hørt før, jeg har bare brukt krystallografi om dette)

**Comment by danmichaelo** [comment]
Uansett, sletter den
