### ISSUE TITLE
Fåbørstemarker

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#928]
Legge til flere termer på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c010585
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22F%C3%A5b%C3%B8rstemarker%22
Soksed: https://soksed.biblionaut.net/concepts/REAL010585

**Comment by Hypsibius** [comment]
Forslag? Fåbørsteormer/Fåbørsteormar? 

Vi kan godt ha dette som OT for meitemarker

**Comment by BioHeidi** [comment]
Jeg sier bare oligokjeter jeg, men det er ikke så god latin (heh heh).
Ingen feil å legge på Hypsibius' forslag. Latin finnes allerede på termen.

**Comment by danmichaelo** [comment]
Gjort. La på Fåbørstemakker også :)
