### ISSUE TITLE
Genetisk fingeravtrykk

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#929]
Legge til `DNA-testing`, `DNA-typing` og `DNA-profilering` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c009122
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Genetisk%20fingeravtrykk%22
Soksed: https://soksed.biblionaut.net/concepts/REAL009122

**Comment by danmichaelo** [comment]
Gjort!
