### ISSUE TITLE
Georadar

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#931]
Legge til `Bakkepenetrerende radar` og `BPR` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c004612
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Georadar%22
Soksed: https://soksed.biblionaut.net/concepts/REAL004612

**Comment by danmichaelo** [comment]
Slått sammen og utfleska
