### ISSUE TITLE
Halogenerte difenylforbindelser

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#932]
Slette?

--
URI: http://data.ub.uio.no/realfagstermer/c006756
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Halogenerte%20difenylforbindelser%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006756

**Comment by BioHeidi** [comment]
Foreslår å slå den sammen med Bifenyler (Bifenyler BF Halog...)

**Comment by danmichaelo** [comment]
*di*fenyl er uansett feil. Slettet den bare, jeg. Det ene dokumentet hadde allerede Bifenyler.

**Comment by anjamaa** [comment]
Men [SNL](https://snl.no/difenyl) og [NAOB](https://www.naob.no/ordbok/difenyl) har "difenyl"? Sistnevnte har kun "difenyl", ikke "bifenyl". Og vi finner ordet i diklordifenyltrikloretan (DDT).

**Comment by danmichaelo** [comment]
@anjamaa Takk, du har jo helt rett!

Men tror fortsatt vi ikke trenger `Halogenerte (bi|di)fenylforbindelser` som se-henv. på `Bifenyler BF Difenyler`? Det ser liksom litt tilfeldig ut med ett eksempel på bifenylforbindelser.

**Comment by anjamaa** [comment]
Tror ikke vi trenger `Halogenerte [...]`, nei :) Du kan eventuelt høre med Tone?
