### ISSUE TITLE
Hastigheter

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#933]
Dette virker som en litt dårlig term (og lite brukt)?

--
URI: http://data.ub.uio.no/realfagstermer/c000728
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hastigheter%22
Soksed: https://soksed.biblionaut.net/concepts/REAL000728

**Comment by Hypsibius** [comment]
Det burde vel i så fall vere 'Hastighet' som fenomen? 'Hastigheter' høyrest meir ut som eit knippe utvalde ;-)

**Comment by mittinatten** [comment]
Stemmer for sletting

**Comment by BioHeidi** [comment]
Gjort
