### ISSUE TITLE
Helmholtz

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#934]
Handler denne termen egentlig om "Helmholtz–Hodge decomposition"? Bør isåfall få nytt navn, for nå virker det som det bare er snakk om personen.

--
URI: http://data.ub.uio.no/realfagstermer/c004175
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Helmholtz%22
Soksed: https://soksed.biblionaut.net/concepts/REAL004175

**Comment by danmichaelo** [comment]
Ser sånn ut, ja! Boka har fått emneordene "Helmholtz" og "Dekomposisjon", men dette burde vært ett emneord. La inn

```
Helmholtz-dekomposisjon
BF Helmholtz–Hodge-dekomposisjon
```
