### ISSUE TITLE
Helsinki-deklarasjonen

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#935]
Slette? Ingen katalogposter.

--
URI: http://data.ub.uio.no/realfagstermer/c002759
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Helsinki-deklarasjonen%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002759

**Comment by danmichaelo** [comment]
Etter å ha fikset Okapi har den én post. Mulig vi vil flytte denne til BARE?

**Comment by anjamaa** [comment]
Vet ikke hva BARE er, så noen andre må bestemme :)

**Comment by danmichaelo** [comment]
BARE = Bibsys autoritetsregister. Det dekker en del ting vi ikke har i Realfagstermer (personer, organisasjoner, møter, konferanser, snart verkstitler), men sannsynligvis ikke dokumenter/avtaler, så det var et dårlig forslag.

**Comment by BioHeidi** [comment]
Men det er ikke emneord heller, vel? @Violabibaluba

**Comment by Violabibaluba** [comment]
Slettet. Er det verk? Skal slike i et eget felt i katalogposten? Vi må spørre en katalogperson. Mari? Juss har slike. @bibliomari
