### ISSUE TITLE
Herschel Space Observatory

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#936]
Wikipedia sier `Herschel-teleskopet` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c012007
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Herschel%20Space%20Observatory%22
Soksed: https://soksed.biblionaut.net/concepts/REAL012007

**Comment by danmichaelo** [comment]
La den inn i samlelista :)
