### ISSUE TITLE
Hieracium

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#937]
Legge til / endre til `Svever` og eventuelt `Sveveslekta`? https://no.wikipedia.org/wiki/Sveveslekta

--
URI: http://data.ub.uio.no/realfagstermer/c009412
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hieracium%22
Soksed: https://soksed.biblionaut.net/concepts/REAL009412

**Comment by BioHeidi** [comment]
Endre til Svever BF Sveveslekten/a EN Hawkweeds LA Hieracium sp.

**Comment by BioHeidi** [comment]
Svensk fibblor. 
Gjort
