### ISSUE TITLE
Hymenoptera

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#938]
Slå sammen med `Årevinger` :)

--
URI: http://data.ub.uio.no/realfagstermer/c004522
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hymenoptera%22
Soksed: https://soksed.biblionaut.net/concepts/REAL004522

**Comment by BioHeidi** [comment]
Seff! :)

**Comment by BioHeidi** [comment]
Og når jeg legger på label "ferdig diskutert" betyr det ikke at det ikke er lov å diskutere eller kommentere videre altså, det er bare for å lett finne tilbake til de som er ferdige nok til at en av oss kan fikse i emnesystemet. Det er ikke ment som "FERDIG SNAKKA!" :dagger:

**Comment by BioHeidi** [comment]
Gjort
