### ISSUE TITLE
Hypotetisk deduktiv metode

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#939]
Mangler bindestrek på norsk.

--
URI: http://data.ub.uio.no/realfagstermer/c011143
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hypotetisk%20deduktiv%20metode%22
Soksed: https://soksed.biblionaut.net/concepts/REAL011143

**Comment by Hypsibius** [comment]
Rett også på NN. Kan vi legge til HDM som BF-term?

**Comment by danmichaelo** [comment]
Fiksa og lagt til HDM
