### ISSUE TITLE
Topologisk kvantedatabehandling

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#94]
Vi trenger en term for "Topological quantum computer/-ing", i tråd med hva som allerede finnes foreslår jeg:

     Topologisk kvantedatabehandling
     EN Topological quantum computing
     SO/OT Kvantedatabehandling

Belegg: http://ask.bibsys.no/ask/action/show?kid=biblio&cmd=reload&pid=150098189
Wikipedia: http://en.wikipedia.org/wiki/Topological_quantum_computer

@knuthe @danmichaelo

**Comment by knuthe** [comment]
Jeg sitter med handa på rattet i øyeblikket og har lagt det inn. Tok sjansen på at nynorsktermen er lik bokmålstermen.

**Comment by mittinatten** [comment]
Det var jammen kjapt :)
