### ISSUE TITLE
Infrarød vibrasjon

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#940]
Slette? Ingen katalogposter.

--
URI: http://data.ub.uio.no/realfagstermer/c010441
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Infrar%C3%B8d%20vibrasjon%22
Soksed: https://soksed.biblionaut.net/concepts/REAL010441

**Comment by danmichaelo** [comment]
Bekreftet at den ikke har katalogposter. Sletter
