### ISSUE TITLE
Infusoria

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#941]
Legge til / endre til `Infusorier` og `Infusjonsdyr` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c003677
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Infusoria%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003677

**Comment by BioHeidi** [comment]
Vi har flimmerdyr som term, med en del andre greier på (bl.a. Infusjonsfyr), så vi legger heller Infusoria til denne. Og legger på latin Ciliophora.

**Comment by BioHeidi** [comment]
Gjort
