### ISSUE TITLE
Ingredienser

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#942]
Slette? Ingen katalogposter.

--
URI: http://data.ub.uio.no/realfagstermer/c010379
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Ingredienser%22
Soksed: https://soksed.biblionaut.net/concepts/REAL010379

**Comment by danmichaelo** [comment]
Fikset Okapi. Nå har den 8 treff. Meeeen tror egentlig ikke det forandrer saken, støtter sletting

**Comment by BioHeidi** [comment]
Slette. 7 like treff og en grøss.

**Comment by BioHeidi** [comment]
Gjort
