### ISSUE TITLE
Injeksjonskapillær matriksinterferenser

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#943]
Slette? Ingen katalogposter.

--
URI: http://data.ub.uio.no/realfagstermer/c002464
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Injeksjonskapill%C3%A6r%20matriksinterferenser%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002464

**Comment by danmichaelo** [comment]
Sletta!
