### ISSUE TITLE
Interglasial

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#944]
Legge til `Mellomistid` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c006153
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Interglasial%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006153

**Comment by danmichaelo** [comment]
Takk, gjort
