### ISSUE TITLE
Ionekanaler

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#945]
Den norske Wikipedia-siden heter "Kanalprotein", skal vi legge til `Kanalproteiner` og `Channel proteins`? @BioHeidi 

--
URI: http://data.ub.uio.no/realfagstermer/c005255
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Ionekanaler%22
Soksed: https://soksed.biblionaut.net/concepts/REAL005255

**Comment by BioHeidi** [comment]
Det kan vi godt.

**Comment by BioHeidi** [comment]
Gjort
