### ISSUE TITLE
Isonitrile forbindelser

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#947]
Slette?

--
URI: http://data.ub.uio.no/realfagstermer/c013760
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Isonitrile%20forbindelser%22
Soksed: https://soksed.biblionaut.net/concepts/REAL013760

**Comment by BioHeidi** [comment]
Ja.

**Comment by BioHeidi** [comment]
Gjort
