### ISSUE TITLE
Jernverk

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#948]
Slette? Ingen katalogposter.

--
URI: http://data.ub.uio.no/realfagstermer/c010365
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Jernverk%22
Soksed: https://soksed.biblionaut.net/concepts/REAL010365

**Comment by Violabibaluba** [comment]
Det er en feil i okapi. Vi lar den være

**Comment by danmichaelo** [comment]
Nå viser Okapi ett dokument igjen :)
