### ISSUE TITLE
Jpeg

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#949]
Rette til `JPEG` og `JPG` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c002838
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Jpeg%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002838

**Comment by danmichaelo** [comment]
Gjort!
