### ISSUE TITLE
(relativistisk) Kvantefeltteori

### ISSUE THREAD

**Issue by mittinatten** [realfagstermer/realfagstermer#95]
Vi har `Relativistisk kvanteteori BF Relativistisk kvantefeltteori` og `Relativistisk kvantemekanikk`, jeg lurer på om det i praksis finnes noen ikke-relativistike kvantefeltteorier. Derfor foreslår jeg

     Kvantefeltteori
     BF Relativistisk kvanteteori
     BF Relativistisk kvantefeltteori
     + det som allerede er der

Relativistisk kvantemekanikk er noe annet.
@danmichaelo

**Comment by knuthe** [comment]
Utført.
