### ISSUE TITLE
Kapitalverdimodellen

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#950]
Legge til `KVM` på norsk? Wikipedia sier "KVM-modellen", men det blir for dumt, og google ellers sier "KVM" :)

--
URI: http://data.ub.uio.no/realfagstermer/c000638
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kapitalverdimodellen%22
Soksed: https://soksed.biblionaut.net/concepts/REAL000638

**Comment by Violabibaluba** [comment]
Done

**Comment by danmichaelo** [comment]
Fikset Wikipedia også :D
