### ISSUE TITLE
Kaspiske Hav

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#953]
Rette til `Kaspiske hav` og legge til `Kaspihavet`?

--
URI: http://data.ub.uio.no/realfagstermer/c030453
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kaspiske%20Hav%22
Soksed: https://soksed.biblionaut.net/concepts/REAL030453

**Comment by Violabibaluba** [comment]
Gjort
