### ISSUE TITLE
Katadrom gyting

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#954]
Ingen katalogposter. Slå sammen med `Katadrome fisker`?

--
URI: http://data.ub.uio.no/realfagstermer/c001538
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Katadrom%20gyting%22
Soksed: https://soksed.biblionaut.net/concepts/REAL001538

**Comment by Hypsibius** [comment]
Absolutt

**Comment by Violabibaluba** [comment]
Vi slettet gytingen. oppretter ny hvis behov
