### ISSUE TITLE
Databeskyttelse og datavern

### ISSUE THREAD

**Issue by kaalrust** [realfagstermer/realfagstermer#956]
[Datavern](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c005416) og [Databeskyttelse](https://app.uio.no/ub/emnesok/realfagstermer/search?id=c010326) har begge Datavern som synonym på nynorsk, så det betyr kanskje at de kan slås sammen?

**Comment by mittinatten** [comment]
Trenger vi å skille mellom det og `Datasikkerhet`?

**Comment by grosyn** [comment]
Ingen har sagt noko til denne på nokre år. Ser at Humord kun har Datasikkerhet, så då slår eg saman våre 3. Dersom dette ikkje er ok, er det bare å protestera!

@BioHeidi @kyrretl

**Comment by BioHeidi** [comment]
Jeg protesterer ikke! 
Men kanskje vi må ta en runde og vekke emneredaksjonen av dvalen.

**Comment by grosyn** [comment]
Då var det gjort - katalogrydding og alt.
