### ISSUE TITLE
IEEE-standarder

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#957]
Greit å endre denne til form/sjanger, @Violabibaluba ?

**Comment by Violabibaluba** [comment]
Relatert til #935

**Comment by Violabibaluba** [comment]
Det holder med Standarder som form. Får treff på IEEE i andre felt i katalogen. Det er i allefall ikke et innholdsbeskrivende emneord! Gjelder da og så ANSI- og ISO-standarder. Rettes.

**Comment by danmichaelo** [comment]
Da har jeg rydda. Og slettet IEEE-standarder, ANSI-standarder og ISO-standarder.
