### ISSUE TITLE
Partisjonering

### ISSUE THREAD

**Issue by danmichaelo** [realfagstermer/realfagstermer#958]
Dette kan jo være så mangt.. Fristende å slette

--
URI: http://data.ub.uio.no/realfagstermer/c006605
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Partisjonering%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006605

**Comment by grosyn** [comment]
Endra til Partisjonering (Informasjonsteknologi), sidan det var i bruk på Informatikk-bøker.
