### ISSUE TITLE
Aseotropi

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#959]
s -> z :) Burde denne heller vært endra til `Azeotroper`? Kan ikke huske å ha sett `Azeotropy` brukt noe særlig, men `Azeotropes` og `Azeotropic` er mye brukt. Eventuelt bytte foretrukket term og beholde `Azeotropi` i lista?

--
URI: http://data.ub.uio.no/realfagstermer/c009359
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Aseotropi%22
Soksed: https://soksed.biblionaut.net/concepts/REAL009359

**Comment by danmichaelo** [comment]
Fiksa

```
Azeotroper
Azeotrope blandinger
Azeotropi
```

Så var det nynorsken da.. Gjetter på m. (`Azeotropar`) siden det f.eks. heter [heliotropar](http://ordbok.uib.no/perl/ordbok.cgi?OPP=*otrop&ant_bokmaal=5&ant_nynorsk=5&begge=+&ordbok=begge). Holder den, @Hypsibius ? De andre to er jo greie

**Comment by anjamaa** [comment]
Høres umusikalsk ut med "ei azeotrop" og "azeotropa", så jeg holder også en knapp på "azeotropar" :)

**Comment by Hypsibius** [comment]
Intuisjonen min seier at dette må bli eit hankjønnsord, sjølv om nynorskordboka ikkje gir meg mykjke å stø meg på :-D

**Comment by danmichaelo** [comment]
Fiksa
