### ISSUE TITLE
Bentiske foraminiferer

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#960]
Legge til `Bentiske poredyr` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c001929
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Bentiske%20foraminiferer%22
Soksed: https://soksed.biblionaut.net/concepts/REAL001929

**Comment by danmichaelo** [comment]
Gjort
