### ISSUE TITLE
Berthollider

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#961]
Legge til `Ikke-støkiometriske forbindelser` på norsk? Har lagt det til på engelsk :)

--
URI: http://data.ub.uio.no/realfagstermer/c005991
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Berthollider%22
Soksed: https://soksed.biblionaut.net/concepts/REAL005991

**Comment by danmichaelo** [comment]
Fikset i #987
