### ISSUE TITLE
Densities

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#963]
Mangler norsk ord? Trenger denne og `Tetthet` en opprydding/sortering?

--
URI: http://data.ub.uio.no/realfagstermer/c006785
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Densities%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006785

**Comment by danmichaelo** [comment]
Slettet. Brukt på ett dokument som generelt ikke virket veldig gjennomtenkt klassifisert
