### ISSUE TITLE
Dissipative strukturer

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#964]
Legge til `Dissipative systemer` og `Dissipative systems` og koble til Wiki-sidene?

--
URI: http://data.ub.uio.no/realfagstermer/c006792
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Dissipative%20strukturer%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006792

**Comment by danmichaelo** [comment]
Ja, med `Dissipative systemer` som foretrukket term
