### ISSUE TITLE
Distributed component object model

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#965]
Finnes det et norsk begrep? Og kan noen fikse versal i alle ordene? :)

--
URI: http://data.ub.uio.no/realfagstermer/c000839
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Distributed%20component%20object%20model%22
Soksed: https://soksed.biblionaut.net/concepts/REAL000839

**Comment by danmichaelo** [comment]
Dette er vel mer eller mindre et egennavn? Lar den stå, men med versaler :)
