### ISSUE TITLE
Dobbeltpulsarer

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#966]
Skulle denne heller vært `Binærpulsarer` (katalogposten handler om binary pulsars)? Virker på Wikipedia som at dobbeltpulsarer er én type binærpulsar (og i tillegg sjelden)? Eventuelt ha begge deler?

--
URI: http://data.ub.uio.no/realfagstermer/c010421
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Dobbeltpulsarer%22
Soksed: https://soksed.biblionaut.net/concepts/REAL010421

**Comment by anjamaa** [comment]
@superLine @danmichaelo

**Comment by danmichaelo** [comment]
For [dobbeltstjerner](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c007259) har vi binærstjerner som synonym, så tipper at [dobbeltpulsarer](http://data.ub.uio.no/skosmos/realfagstermer/nb/page/c010421) og binærpulsarer (lagt inn nå) også er synonymer. Vet ikke hva som er best norsk. Kanskje en jobb for @mariahammerstrom og termwikien?

**Comment by mariahammerstrom** [comment]
Når vi snakker om stjerner, er ikke "dobbeltstjerne" og "binærstjerne" helt synonymer, men jeg tror folk blander disse begrepene når de bruker dem. Dobbeltstjerne er som dere har definert det, mens binærstjerne er to stjerner som faktisk går i bane rundt hverandre (gravitasjonelt bundne), så "binærstjerne" kan bare brukes på den ene typen dobbeltstjerne dere har definert. 

Når det gjelder pulsarer, så ser jeg at astronomer bruker både "binærpulsar" og "dobbeltpulsar" om pulsarer som går i bane rundt hverandre, som gjør det forvirrende. For å matche ordbruken for stjerner best mulig, ville jeg satt "binærpulsar" som hovedbegrepet, og "dobbeltpulsar" som synonym.

**Comment by danmichaelo** [comment]
Takk, da gjør vi det!

Endret stjernedef. til "Stjerner som observert fra jorden har tilstrekkelig liten innbyrdes vinkelavstand til at de fremstår som par, enten de faktisk er nær hverandre (gravitasjonelt bundne binærstjerner) eller ikke (optiske dobbeltstjerner)".

Og så innser jeg at jeg burde være litt forsiktig med å snakke om synonymer.. Vi opererer egentlig ikke med det, men med indekstermer (hovedtermer) og henvisningstermer -- sistnevnte er ofte synonymer, men kan også være termer knytta til underordna eller nært relaterte begrep. Litt som på Wikipedia der nært relaterte begrep av og til omtales i samme artikkel :)

**Comment by mittinatten** [comment]
Ser ut som det mangler avsluttende parentese i definisjonen for dobbeltstjerner

**Comment by danmichaelo** [comment]
> Ser ut som det mangler avsluttende parentese i definisjonen for dobbeltstjerner

Ikke nå lenger (men det vises ikke i Skosmos før i morgen)
