### ISSUE TITLE
Epo

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#968]
Kan noen rette til `EPO` og legge til `Erytropoietin` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c001714
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Epo%22
Soksed: https://soksed.biblionaut.net/concepts/REAL001714

**Comment by danmichaelo** [comment]
Fiksa!
