### ISSUE TITLE
European Southern Observatory

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#969]
Endre til `Det europeiske sørobservatorium` / `Europeiske sørobservatorium` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c000260
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22European%20Southern%20Observatory%22
Soksed: https://soksed.biblionaut.net/concepts/REAL000260

**Comment by danmichaelo** [comment]
Ikke fikset, men flyttet problemet inn i #255
