### ISSUE TITLE
Dvale, vintersøvn, overvintring... 

### ISSUE THREAD

**Issue by bibliomari** [realfagstermer/realfagstermer#97]
@BioHeidi @Hypsibius 

Jeg trenger hjelp: Vi har Overvintring, som hvis vi skal beholde det bør defineres til overvintring av typen "fangstmannen overvintret på Svalbard". Men da kan det hende vi bør rydde på neon få andre poster. 

Ellers har vi: Hibernering, Dvale, Vinterdvale. Disse tre kan sikkert settes sammen på et vis :)

**Comment by Hypsibius** [comment]
Tenderer til å tenke at hibernering og dvale er det same, og at vinterdvale er ein muligheit (aestivation/sommardvale ein anna). Men korleis er det no igjen at dette forheld seg til andre typar dormantstadiar, @BioHeidi ? Anten det er nødvendige stadiar alle skal gjennom (tenk syttenårssikadar), klimarelaterte (årelange tørkeperioder) eller kortare kvilepauser? For alle desse går metabolsk aktivitet ned...

**Comment by Hypsibius** [comment]
*sjekkar i Norwegian Glossary for Campbell Biologi*: Dormancy - uvirksomhet/dvale

**Comment by Hypsibius** [comment]
Kom til 'dvale' sjekklista mi. Kan vi kome noko vidare her?

**Comment by BioHeidi** [comment]
Dormans, ja, @danmichaelo husker du deweynummeret ditt? ;-)

**Comment by BioHeidi** [comment]
Men ikke all overvintring er dvale eller hibernering el.l. Jeg rydder og tenker.

**Comment by danmichaelo** [comment]
> Dormans, ja, @danmichaelo husker du deweynummeret ditt? ;-)

Ja og nei, husker ikke *nummeret* ;) Så moro at det finnes en egen norsk glosebok for Campbell forresten! Men er den [umulig å oppdrive](http://ask.bibsys.no/ask/action/show?pid=144235587&kid=biblio)??

**Comment by bibliomari** [comment]
Si det, tilbakemelding fra leverandøren er:

*2014-11-13: Ukjent tittel (finnes ikke).

**Comment by Hypsibius** [comment]
Den norske gloseboka for Campbell er glimrande, men kan ikkje kjøpast åleine, gjett om eg forsøkte! Må kjøpast SAMAN med hovudboka. Voldsomt styr, mykje detektivarbeid frå vår bokkjøpsavdeling. Objectid:  141877103

**Comment by Hypsibius** [comment]
@BioHeidi Nøler med å bruke overvintring som paraplyterm, iom at det ikkje dekkjer 'oversomring' eller syttenårssikader. 

Men for meg kan overvintring godt gjelde både dei pelsjegarar og pelsdyr som ikkje går i hi. Og så kanskje vi finn ein fellesterm for alle former for dvalar? Korte, lange, sommar, vinter, tørke,is?

**Comment by Hypsibius** [comment]
Slik sett er vel dormans bedre, iom at det kan brukast for eincella og planter, i tillegg til *dyr*...

**Comment by BioHeidi** [comment]
Nå er det sånn:
Hibernering BF Vintersøvn, Vinterdvale, Dvale, Hvile
Overvintring som egen term

**Comment by BioHeidi** [comment]
Tror jeg også legger på Dormans som BF til Hibernering

**Comment by Hypsibius** [comment]
OK, slik eg oppfattar det er hibernering og dvale ganske einsbetydande. Sidan dvale er eit mykje meir brukt norsk ord, ville eg foreslå det som foretrukken term. Legg gjerne til dormans som BF-term, vil dessutan gjerne ha med estivering som BF-term

Overvintring bør vere ein SO-term. Men om Hvile følgjer med som generell term, synest eg det er ulogisk at Frøhvile skulle vere eigen term? Kan ikkje den få lov å vere med?

**Comment by BioHeidi** [comment]
Ja du har rett, dvale er mer norsk (men hibernering føles mer... vitenskapelig?). Uansett sikkert bra at Dvale er foretrukken.
Estivering og SO til Overvintring skal bli.
Frøhvile fikk være egen term fordi bruken var veldig fint fordelt på begrepene mellom dyr og planter, men det trenger det vel egentlig ikke å være.

Fint å ha deg mer tilbake, forresten!

**Comment by Hypsibius** [comment]
Sanneleg godt å vere tilbake også, @BioHeidi  :-) På'an med ny frisk, og spennande å sjå kva dokke har jobba med i mellomtida!

**Comment by grosyn** [comment]
Har no bytta oppslagsterm til Dvale. Har oppdatert katalogpostane.
