### ISSUE TITLE
Evodevo

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#970]
Legge til `Evolusjonær utviklingsbiologi` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c000168
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Evodevo%22
Soksed: https://soksed.biblionaut.net/concepts/REAL000168

**Comment by Hypsibius** [comment]
Jf denne: https://github.com/realfagstermer/realfagstermer/issues/218

**Comment by BioHeidi** [comment]
Jeg stemmer for det første, og til og med legge på BF Ontogenese!

**Comment by Hypsibius** [comment]
Enig m deg!

**Comment by BioHeidi** [comment]
Gjort!
