### ISSUE TITLE
European Space Research Organisation

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#971]
Endre til `Den europeiske romforskningsorganisasjon` / `Europeiske romforskningsorganisasjon` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c003779
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22European%20Space%20Research%20Organisation%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003779

**Comment by danmichaelo** [comment]
Ikke fikset, men flyttet problemet inn i #255
