### ISSUE TITLE
Fluviale sedimenter

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#973]
Slå sammen med `Fluvial sedimentologi`?

--
URI: http://data.ub.uio.no/realfagstermer/c012402
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Fluviale%20sedimenter%22
Soksed: https://soksed.biblionaut.net/concepts/REAL012402

**Comment by Hypsibius** [comment]
Det er i tråd med parallelle tilfelle. Typ Fisker/Ichthyologi

**Comment by danmichaelo** [comment]
Duplikat av #689 . Som jeg tror stagnerte litt..
