### ISSUE TITLE
Function level

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#975]
Versal L i "level"?

--
URI: http://data.ub.uio.no/realfagstermer/c001284
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Function%20level%22
Soksed: https://soksed.biblionaut.net/concepts/REAL001284

**Comment by danmichaelo** [comment]
Hm, litt rart. Emneordet har en note om programmeringsspråk, men det ser jo ut function-level er et programmeringsparadigme, mens [FP (Function Programming)](https://en.wikipedia.org/wiki/FP_(programming_language)) er språket.. Her må vi bestemme oss.  Og hvis vi bestemmer oss for paradigmet, skal det da oversettes? Kanskje den godeste @knuthe har en mening om saken?

**Comment by anjamaa** [comment]
Ut ifra Wikipedia virker det som [Function Level](https://en.wikipedia.org/wiki/FL_(programming_language)) er et programmeringsspråk, mens [function-level programming](https://en.wikipedia.org/wiki/Function-level_programming) er et programmeringsparadigme?

**Comment by danmichaelo** [comment]
Ah, den så jeg ikke, kanskje på tide å ta helg. Da gjør jeg bare om til "Function Level" ihvertfall

**Comment by anjamaa** [comment]
Helg høres uansett ut som en god idé :)
