### ISSUE TITLE
Funksjonell genomikk

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#976]
Legge til `Funksjonell genomforskning` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c011314
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Funksjonell%20genomikk%22
Soksed: https://soksed.biblionaut.net/concepts/REAL011314

**Comment by danmichaelo** [comment]
Gjort
