### ISSUE TITLE
Fødselsdepresjoner

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#977]
Legge til en eller flere av `Barseldepresjoner`, `Postpartum depresjoner` (og isåfall `PPD`), og `Postnatale depresjoner` på norsk? De to sistnevnte virker veldig som norskifiseringer av engelsk, men ser de er brukt en del på norsk likevel?

--
URI: http://data.ub.uio.no/realfagstermer/c011636
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22F%C3%B8dselsdepresjoner%22
Soksed: https://soksed.biblionaut.net/concepts/REAL011636

**Comment by Hypsibius** [comment]
Meir latin en engelsk, trur eg. Medisinsk språkbruk, greit å ha med som BF-termar.

**Comment by danmichaelo** [comment]
Skader ikke, la inn alle
