### ISSUE TITLE
Geosystemer

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#978]
Slå sammen med `Fysisk geografi`? Virker som det samme?

--
URI: http://data.ub.uio.no/realfagstermer/c001722
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Geosystemer%22
Soksed: https://soksed.biblionaut.net/concepts/REAL001722

**Comment by grosyn** [comment]
Både Geosystemer og Fysisk geografi har blitt flytta til Fysikalsk geografi (2018 og 2019).
