### ISSUE TITLE
Gevirer

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#979]
Legge til `Takker` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c003931
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Gevirer%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003931

**Comment by Hypsibius** [comment]
Antar det er nær nok...

**Comment by danmichaelo** [comment]
Lag til

**Comment by anjamaa** [comment]
@Hypsibius, ikke mitt felt, altså, men foreslo det fordi Wikipedia brukte dem om hverandre :)
