### ISSUE TITLE
Gjevilvatnet

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#980]
Legge til `Gjevillvatnet` på norsk?

--
URI: http://data.ub.uio.no/realfagstermer/c030623
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Gjevilvatnet%22
Soksed: https://soksed.biblionaut.net/concepts/REAL030623

**Comment by danmichaelo** [comment]
Gjort!
