### ISSUE TITLE
Herbig-Haro-objekter

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#982]
Bytter noen ut første bindestrek med en tankestrek? :)

--
URI: http://data.ub.uio.no/realfagstermer/c004452
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Herbig-Haro-objekter%22
Soksed: https://soksed.biblionaut.net/concepts/REAL004452

**Comment by danmichaelo** [comment]
Fikset (mens jeg tenkte tankestrektanker)
