### ISSUE TITLE
Hyperakkumulasjon

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#984]
Skal vi legge til `Hyperakkumulatorer` og `Hyperaccumulators` og lenke til [denne](https://en.wikipedia.org/wiki/Hyperaccumulator) Wiki-artikkelen?

--
URI: http://data.ub.uio.no/realfagstermer/c002932
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Hyperakkumulasjon%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002932

**Comment by danmichaelo** [comment]
Ja, det synes jeg må gå!
