### ISSUE TITLE
International Space Station

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#985]
Endre / legge til `Den internasjonale romstasjonen`?

--
URI: http://data.ub.uio.no/realfagstermer/c007595
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22International%20Space%20Station%22
Soksed: https://soksed.biblionaut.net/concepts/REAL007595

**Comment by danmichaelo** [comment]
Takk, lagt inn i #255
