### ISSUE TITLE
Flatskjermer

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#986]
Er det nødvendig å ha emneord hvor det ikke er katalogposter?

--
URI: http://data.ub.uio.no/realfagstermer/c012773
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Flatskjermer%22
Soksed: https://soksed.biblionaut.net/concepts/REAL012773

**Comment by Hypsibius** [comment]
Nei

**Comment by danmichaelo** [comment]
Slettet (dobbeltsjekka i Alma at det ikke var poster)
