### ISSUE TITLE
Ikke-støkiometri

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#987]
Slå sammen med `Berthollider`?

--
URI: http://data.ub.uio.no/realfagstermer/c012847
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Ikke-st%C3%B8kiometri%22
Soksed: https://soksed.biblionaut.net/concepts/REAL012847

**Comment by danmichaelo** [comment]
Oi, den var avansert! Skal vi bruke `Ikke-støkiometriske forbindelser` som hovedterm, mon tro?

**Comment by anjamaa** [comment]
Ja! Er ferdig med bachelor i kjemi nå og har aldri hørt om berthollider, hahaha.

**Comment by danmichaelo** [comment]
Sånn kan det gå :) Fiksa!
