### ISSUE TITLE
midlatitudes

### ISSUE THREAD

**Issue by mzyg** [realfagstermer/realfagstermer#99]
Har flere bøker om midlatitudes.
Foreslår 
`midlere breddegrader` 
`EN midlatitudes`
`middle latitudes`
      
@kristinran finnes en annen term på norsk? 
Extratropics på engelsk og? Blir jo mer brukt som adjektiv (extratropical, ekstratropisk)
 (Takk og hygglig, btw :-))

**Comment by bibliomari** [comment]
Tenker du dette som en slags geografisk angivelse? Jeg er usikker på hvordan vi best skal uttrykke det. Som "Midlere breddegrader" oppfatter jeg det som et stedsemneord. 

For øvrig har vi emneordet "tempererte soner" som kanskje forholder seg til midlere breddegrader på en måte. 

Jeg blir glad for utdyping :) @mzyg @kristinran

**Comment by mzyg** [comment]
Godt spørsmål. Det er jo mer en slags geografisk angivelse. Da trenger jeg kansjke lit veiledning hva skal brukes.
Tempererte soner (så ikke før at det finnes som emneord) er i prinsippet det sammen som midlere breddegrader. Trodde det er mer vanlig å bruke tempererte soner i biologisk kontekst mens midlere breddegrader brukes mer i atmosphærisk kontekst.
Men det ser ut som det er bare slik på engelsk og det holder faktisk med tempererte soner som emneord. Riktig? @kristinran

**Comment by kristinran** [comment]
Hmmm. her er jeg usikker. Tempererte soner vil fungere også i geologisk kontekst, er viktig i forhold til forvitring og ev. organisk produksjon som del av sedimentasjon. Hvilke fagmiljø bruker midlatitudes?

**Comment by danmichaelo** [comment]
Ser ut som det er meteorologi og klima.

http://www.bom.gov.au/climate/glossary/mid_latitudes.shtml

Finnes en Wikipedia-artikkel, men den er kildeløs...

https://en.wikipedia.org/wiki/Middle_latitudes

Ser ikke ut som det overlapper med Tempererte soner.

**Comment by mzyg** [comment]
Når man snakker om vær eller atmosfærisk sirkulasjon bruker man vanligvis ‘midlere breddegrader’ og ‘mid-latitudes’. 
http://forskning.no/fysikk-meteorologi-vaer-og-vind/2011/07/fly-lager-hull-i-skyene
http://no.wikipedia.org/wiki/Atmosf%C3%A6risk_sirkulasjon
http://regclim.met.no/norsk/Klimafakta/det_globale_klimasystemet.htm
Da er det ikke så vanlig å bruke ‘tempererte soner’ og derfor burde vi ha midlere breddegrader som term.
Tempererte (klima)soner finnes vanligvis i midlere breddegrader,(wiki-lenken fra @danmichaelo ?? + https://metlex.met.no/wiki/Tempererte_soner) . 
Termen blir vel flest brukt i biologisk/geologisk/geografisk sammenheng. Å definere en klimasone/område med breddegrader er jo veldig statisk. Det holder når man snakker generell om atmosfærisk sirkulasjon men det er ikke alltid tilstrekkelig for biologer og geologer som skal beskrive f. eks et habitat i en klimasone. 
Hva med 
midlere breddegrader BF tempererte soner
EN midlatitudes
middle latitudes
(temperate zones)
?

**Comment by mzyg** [comment]
97d054602 :-) trenger midlere breddegrader i meteorologi..

**Comment by danmichaelo** [comment]
Spørsmålet er kanskje: Er de som søker etter "Midlere breddegrader" (eller "Midlatitudes") også kanskje interessert i litteraturen merket "Tempererte (klima)soner", eller blir det mest støy?

LC har forresten Temperate climate BF Middle latitude climate, men vi trenger jo ikke følge dem :)
http://id.loc.gov/authorities/subjects/sh96008538.html

**Comment by mzyg** [comment]
Jeg syns det er okey det blir ikke for mye støy!
Temperate climate BF Middle latitude climate er i hvert fall okey. 

Det fins ikke så mange bøker om vær og tempererte soner da bruker man mid-latitudes, det betyr
når man søker etter vær og midlere breddegrader blir det også greit - ikke sant?

**Comment by danmichaelo** [comment]
Fint! Men forsto jeg det riktig at det er ok for deg med f.eks. `Temperert klima` som indeksterm, så lenge søk på `Midlere breddegrader` og `Midlatitudes` også funker (gir de samme treffene)?

```
Temperert klima
BF Tempererte soner
BF Midlere breddegrader
EN Temperate climate
EN Temperate climate
EN Midlatitudes
EN Middle latitudes
```

**Comment by mzyg** [comment]
Det er greit!

**Comment by bibliomari** [comment]
Gjort (omsider!)
