### ISSUE TITLE
Maurangrep

### ISSUE THREAD

**Issue by olavbje** [realfagstermer/realfagstermer#990]
Dette regner jeg som et lite faglig begrep

--
URI: http://data.ub.uio.no/realfagstermer/c006399
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Maurangrep%22
Soksed: https://soksed.biblionaut.net/concepts/REAL006399

**Comment by Hypsibius** [comment]
Vi har både Skadedyr og Skadeinsekt, det får halde

**Comment by danmichaelo** [comment]
og kan gjøre kombisøk: `Maur` + `Skadedyr` 

Slettet
