### ISSUE TITLE
Kalkalkalibergarter

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#991]
Er dette et ord? Det er nesten bare treff fra oss på google? Slette? Ingen katalogposter.

--
URI: http://data.ub.uio.no/realfagstermer/c003113
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kalkalkalibergarter%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003113

**Comment by danmichaelo** [comment]
Hm, den finnes jo i https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/kalkalkalibergarter . Men ellers var det tynt..

Får en del treff hvis jeg søker etter Kalkalkalibergarter i Alma, men bare i frie nøkkelord (653-felt).

Skal vi bare slette, @edinab ? Eller vil du ha denne?

**Comment by grosyn** [comment]
Blei sletta 2018-08-30
