### ISSUE TITLE
Kapillær lc-separasjon

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#992]
Rette til LC i versaler? Eller slette?

--
URI: http://data.ub.uio.no/realfagstermer/c002246
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kapill%C3%A6r%20lc-separasjon%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002246

**Comment by danmichaelo** [comment]
Slettet (#995)
