### ISSUE TITLE
Kapillær ph-gradient

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#993]
Rette til pH eller slette?

--
URI: http://data.ub.uio.no/realfagstermer/c003318
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kapill%C3%A6r%20ph-gradient%22
Soksed: https://soksed.biblionaut.net/concepts/REAL003318

**Comment by danmichaelo** [comment]
Slettet (#995)
