### ISSUE TITLE
Kapillærsoneelektroforese

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#994]
Slå sammen med `Kapillærelektroforese`? Virker som kapillærsoneelektroforese er den vanligste formen for kapillærelektroforese.

--
URI: http://data.ub.uio.no/realfagstermer/c012965
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kapill%C3%A6rsoneelektroforese%22
Soksed: https://soksed.biblionaut.net/concepts/REAL012965

**Comment by danmichaelo** [comment]
Enig (i at det virker sånn :D), slått sammen
