### ISSUE TITLE
Kapillærteori

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#995]
Slå sammen med `Kapillaritet`?

--
URI: http://data.ub.uio.no/realfagstermer/c001323
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kapill%C3%A6rteori%22
Soksed: https://soksed.biblionaut.net/concepts/REAL001323

**Comment by danmichaelo** [comment]
Gjort

**Comment by danmichaelo** [comment]
Sletta `Kapillærrør` samtidig. Vurderte sammenslåing, men det passet ikke helt med [det ene dokumentet](https://bibsys-almaprimo.hosted.exlibrisgroup.com:443/UBO:bibsys_ils:BIBSYS_ILS71470433930002201)

**Comment by danmichaelo** [comment]
og `Kapillær ph-gradient` og `Kapillær lc-separasjon`..

**Comment by danmichaelo** [comment]
og `Kapillæranalyse` (0 dok)
