### ISSUE TITLE
Kazhdan's egenskap

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#997]
Kan noen fjerne apostrofen? :)

--
URI: http://data.ub.uio.no/realfagstermer/c008006
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kazhdan's%20egenskap%22
Soksed: https://soksed.biblionaut.net/concepts/REAL008006

**Comment by danmichaelo** [comment]
Oi, fjernet :)
