### ISSUE TITLE
Kk-teori

### ISSUE THREAD

**Issue by anjamaa** [realfagstermer/realfagstermer#999]
Retter noen til "KK-teori"? :)

--
URI: http://data.ub.uio.no/realfagstermer/c002591
Bruk: http://ub-viz01.uio.no/okapi2/#/search?q=realfagstermer%3A%22Kk-teori%22
Soksed: https://soksed.biblionaut.net/concepts/REAL002591

**Comment by danmichaelo** [comment]
Retta!
